### ISSUE TITLE
[Bug] 实际连接的远程主机IP错误

### ISSUE THREAD

**Issue by 786259135** [Dreamacro/clash#1007]
------------------------------------------------------------------

### Clash config

<details>
  <summary>config.yaml</summary>

```yaml
mixed-port: 7890
# RESTful API for clash
external-controller: 127.0.0.1:9090
allow-lan: false
mode: rule
log-level: warning

dns:
  enable: true
  listen: :53
  enhanced-mode: redir-host
  nameserver:
    - 223.5.5.5
    - 114.114.114.114
    - tls://rubyfish.cn
  fallback:
    - 8.8.8.8
    - 1.1.1.1

rules:
  - IP-CIDR,1.1.1.1/32,DIRECT,no-resolve
  - IP-CIDR,2.2.2.2/32,DIRECT,no-resolve
  - MATCH,DIRECT
……
```

</details>

### Clash log

```
2020-10-08 22:15:38[info] [TCP] 192.168.1.2:59861 --> www.domain.org match IPCIDR(2.2.2.2/32) using DIRECT
2020-10-08 22:16:07[info] [TCP] 192.168.1.2:59863 --> www.domain.org match IPCIDR(1.1.1.1/32) using DIRECT
2020-10-08 22:16:15[info] [TCP] 192.168.1.2:59865 --> www.domain.org match IPCIDR(2.2.2.2/32) using DIRECT
……
```

### 环境 Environment
局域网内其它主机（192.168.1.2），clash部署采用旁路由模式部署（192.168.1.252），网关：192.168.1.1

* 操作系统 (the OS that the Clash core is running on)
MacOS

……
* 网路环境或拓扑 (network conditions/topology)

Clash 2020.09.27 linux amd64 Sun Sep 27 12:23:49 UTC 2020

……
* iptables，如果适用 (if applicable)
iptables -t nat -N clash
iptables -t nat -A clash -d 0.0.0.0/8 -j RETURN
iptables -t nat -A clash -d 10.0.0.0/8 -j RETURN
iptables -t nat -A clash -d 127.0.0.0/8 -j RETURN
iptables -t nat -A clash -d 169.254.0.0/16 -j RETURN
iptables -t nat -A clash -d 172.16.0.0/12 -j RETURN
iptables -t nat -A clash -d 192.168.12.252/32 -p tcp --dport 22 -j ACCEPT
iptables -t nat -A clash -d 192.168.0.0/16 -j RETURN
iptables -t nat -A clash -d 119.28.87.187/32 -j RETURN
iptables -t nat -A clash -d 129.226.4.20/32 -j RETURN
iptables -t nat -A clash -d 224.0.0.0/4 -j RETURN
iptables -t nat -A clash -d 240.0.0.0/4 -j RETURN
iptables -t nat -A clash -d 192.168.12.252 -j RETURN
iptables -t nat -A clash -p tcp -j REDIRECT --to-port 7892
iptables -t nat -I PREROUTING -p tcp -d 8.8.8.8 -j REDIRECT --to-port 7892
iptables -t nat -I PREROUTING -p tcp -d 8.8.4.4 -j REDIRECT --to-port 7892
iptables -t nat -A PREROUTING -p tcp -j clash
#udp
ip rule add fwmark 1 table 100
ip route add local default dev lo table 100
iptables -t mangle -N clash
iptables -t mangle -A clash -d 0.0.0.0/8 -j RETURN
iptables -t mangle -A clash -d 10.0.0.0/8 -j RETURN
iptables -t mangle -A clash -d 127.0.0.0/8 -j RETURN
iptables -t mangle -A clash -d 169.254.0.0/16 -j RETURN
iptables -t mangle -A clash -d 172.16.0.0/12 -j RETURN
iptables -t mangle -A clash -d 192.168.0.0/16 -j RETURN
iptables -t mangle -A clash -d 224.0.0.0/4 -j RETURN
iptables -t mangle -A clash -d 240.0.0.0/4 -j RETURN
iptables -t mangle -A clash -d 192.168.12.252 -j RETURN
iptables -t mangle -A clash -p udp -j TPROXY --on-port 7892 --tproxy-mark 1
iptables -t mangle -A PREROUTING -p udp -j clash

……
* ISP 有没有进行 DNS 污染 (is your ISP performing DNS pollution?)
……
* 其他 (any other information that would be useful)
……

### 重现问题的具体布骤 Steps to Reproduce
1.本机的DNS解析设置为旁路由的IP（192.168.1.250）
2. 一个DNS具有多个IP域名，例如：1.1.1.1，2.2.2.2
3.先正常访问一次域名
4.通过IP直接1.1.1.1访问22端口
5.通过IP直接2.2.2.2访问22端口

**我预期会发生……？**

通过IP访问时能正确连接到远程主机

**实际上发生了什么？**

通过1.1.1.1实际连接到的主机可能为2.2.2.2，或者2.2.2.2实际访问的主机为1.1.1.1
