### ISSUE TITLE
疑问：clash的log是只保存在内存中吗？而不是输入到本地的某个文件？如何修改config.yaml文件设置默认节点？

### ISSUE THREAD

**Issue by zhong-yuming** [Dreamacro/clash#1009]
系统是manjaro KDE，每次使用都需要进入Clash Dashboard修改代理模式和节点。自行修改了config.yaml，设置了默认模式，但是节点不知道如何设置。

同时也存在疑惑，clash生成的log似乎没有指定文件存储。望解答~谢谢！
@Dreamacro

**Comment by jack-053024** [comment]
系统是manjaro KDE，每次使用都需要进入Clash Dashboard修改代理模式和节点。自行修改了config.yaml，设置了默认模式，但是节点不知道如何设置。

同时也存在疑惑，clash生成的log似乎没有指定文件存储。望解答~谢谢！
@Dreamacro

**Comment by Dreamacro** [comment]
不存在内存中，输出到 stdout、stderr。默认为第一个节点，修改配置到第一个就行

**Comment by jack-053024** [comment]
> 不存在内存中，输出到 stdout、stderr。默认为第一个节点，修改配置到第一个就行

**感谢答疑！**关于第二个问题：默认节点。
我将全局代理设置成了默认选项，现在的默认节点是DIRECT。但是在我的config.yaml文件中，并没有任何提及到该节点为默认节点的地方，所以我不知道如何去修改（配置文件是从别人download下来的），请问一下我是否要自己添加某些属性或字段，来设置默认节点。

我的配置代码如下：
```yaml
# HTTP 代理端口
port: 7890 

# SOCKS5 代理端口
socks-port: 7891 

# Linux 和 macOS 的 redir 代理端口
redir-port: 7892 

# 允许局域网的连接
allow-lan: true

# 规则模式：Rule（规则） / Global（全局代理）/ Direct（全局直连）
mode: Global

# 设置日志输出级别 (默认级别：silent，即不输出任何内容，以避免因日志内容过大而导致程序内存溢出）。
# 5 个级别：silent / info / warning / error / debug。级别越高日志输出量越大，越倾向于调试，若需要请自行开启。
log-level: silent
# Clash 的 RESTful API
external-controller: '127.0.0.1:9090'

# RESTful API 的口令
secret: '' 

# 您可以将静态网页资源（如 clash-dashboard）放置在一个目录中，clash 将会服务于 `RESTful API/ui`
# 参数应填写配置目录的相对路径或绝对路径。
# external-ui: folder

proxies:
  - {"name":"[V2ray]proxy1","type":"vmess","server":"proxy1.hkcom.xyz","port":6635,"uuid":"58e75688-4ec5-33a4-ace8-e7c731cd7e4e","alterId":2,"cipher":"auto","udp":true}
  - {"name":"[V2ray]proxy2","type":"vmess","server":"ppyun2.hkcom.xyz","port":5526,"uuid":"58e55238-4ec5-61a4-ace4-e7c771cd7e4e","alterId":2,"cipher":"auto","udp":true,"network":"ws","ws-path":"/hls/cctv5phd.m3u8","ws-headers":{"Host":"18.185.239.238"},"tls":true}
  - {"name":"[V2ray]proxy3","type":"vmess","server":"ppyun3.hkcom.xyz","port":4843,"uuid":"58e55698-4ec1-31a4-ace4-e7c731cd7e4e","alterId":2,"cipher":"auto","udp":true}
```

再次感谢！
