### ISSUE TITLE
[Feature] proxy group providers

### ISSUE THREAD

**Issue by tslling** [Dreamacro/clash#1010]
感谢你向 Clash Core 提交 Feature Request！
在提交之前，请确认：

- [x] 我已经在 [Issue Tracker](……/) 中找过我要提出的请求

请注意，如果你并没有遵照这个 issue template 填写内容，我们将直接关闭这个 issue。

我都确认过了，我要继续提交。

------------------------------------------------------------------

请附上任何可以帮助我们解决这个问题的信息，如果我们收到的信息不足，我们将对这个 issue 加上 *Needs more information* 标记并在收到更多资讯之前关闭 issue。

### Clash core config

```
……
```

### Clash log

```
……
```

### 环境 Environment

* Clash Core 的操作系统 (the OS that the Clash core is running on)
……
* 使用者的操作系统 (the OS running on the client)
……
* 网路环境或拓扑 (network conditions/topology)
……
* iptables，如果适用 (if applicable)
……
* ISP 有没有进行 DNS 污染 (is your ISP performing DNS pollution?)
……
* 其他
……

### 说明 Description
现在的```proxy-groups```的```proxies```字段都是把```proxies```字段的```name```或者其他proxy group的```name```罗列组成的，这样重复比较多。所以希望支持和```rule-providers```类似的```proxy-group-providers```来减少这种重复，支持以script的形式来从```proxies```/```proxy-groups```中筛选特定的proxy组成新的group。

### 可能的解决方案 Possible Solution
比如像这样：
```yaml
proxy-groups:
- name: YouTube
  type: url-test
  url: http://cp.cloudflare.com/generate_204
  interval: "1800"
  proxies: 
  - |
    def filter():
      return [x["name"] for x in proxies if 'YouTube' in x["name"]]
```
