### ISSUE TITLE
[Bug]IOS 14 奈飞无法打开

### ISSUE THREAD

**Issue by geekotaku** [Dreamacro/clash#1012]
------------------------------------------------------------------

### Clash config

<details>
  <summary>config.yaml</summary>

```yaml
dns:
  enable: true
  listen: 0.0.0.0:53
  enhanced-mode: fake-ip
  nameserver:
    #- 119.29.29.29
    - https://cloudflare-dns.com/dns-query
```

</details>

### Clash log

```
……
```

### 环境 Environment

* 操作系统 (the OS that the Clash core is running on)
debian 10
* 网路环境或拓扑 (network conditions/topology)
路由器ubnt usg，外加debian 10 linux虚拟机一台
GFWList模式，将需要代理的流量导出到debian机器
* iptables，如果适用 (if applicable)
dnsmasq解析gfwlist列表中域名，返回fake-ip 198.16.0.0/24 策略路由到 debian

### 重现问题的具体布骤 Steps to Reproduce

iPad一台，ios13，netflix客户端播放没任何问题
升级到ios14，netflix提示错误，无法联网

经过wireshark抓包发现很多unknow type65的dns查询，没有返回应该有的fake-ip地址，而是直接返回类似cname的结果。
netflix的域名会重定向到amazonaws.com的域名，由于不在gfwlist的列表中导致奈飞打开失败。

经过一番google，发现以下帖子，这个是ios14开始新增的草案，貌似用来加速的。
https://www.v2ex.com/t/699027

### 可能的解决方案 Possible Solution

方案一： 使用上个帖子里说的dnspod 119的dns确实解决了这个问题，但是不是长远之计，试了一些其他的dns都已经支持了这个svcb草案。
方案二：修改源码middleware.go
删除 else if q.Qtype != D.TypeA {
    return next(r)
}
但是这样就用不了premium版本了。

希望官方给出解决方案，谢谢。
