### ISSUE TITLE
hosts 是否支持域名绑定多个地址

### ISSUE THREAD

**Issue by muink** [Dreamacro/clash#1031]
hosts 是否支持单个域名绑定多个地址, 比如这样？
``` yaml
hosts:
  'dns.alidns.com':
    - 223.5.5.5
    - '2400:3200::1'
    - 223.6.6.6
    - '2400:3200:baba::1'
```
