### ISSUE TITLE
[Bug]无法连接auth_chain_a协议的ssr单端口节点

### ISSUE THREAD

**Issue by athenakia** [Dreamacro/clash#1058]
### Clash config

关键节点信息去除了，如有需要，可通过其他联系方式（邮箱、Telegram等）提供节点信息
<details>
  <summary>config.yaml</summary>

```yaml
port: 7890

socks-port: 7891

redir-port: 7892

allow-lan: false

bind-address: '*'

mode: rule

log-level: debug

ipv6: false

external-controller: 127.0.0.1:9090

hosts:
  # '*.clash.dev': 127.0.0.1
  # '.dev': 127.0.0.1
  # 'alpha.clash.dev': '::1'

dns:
  enable: false
  listen: 0.0.0.0:53

  default-nameserver:
    - 114.114.114.114
    - 8.8.8.8
  
  nameserver:
    - 114.114.114.114 # default value
    - 8.8.8.8 # default value
proxies:
  - name: "ssr"
    type: ssr
    server: domain.com
    port: 8888
    cipher: rc4-md5
    password: "xxxx"
    obfs: plain
    protocol: auth_chain_a
    protocol-param: "10000:abcd"
    udp: true

proxy-groups:
  - name: "auto"
    type: select
    proxies:
      - ssr

rules:
  - DOMAIN-SUFFIX,vultr.com,auto
  - DOMAIN-KEYWORD,vultr,auto
  - DOMAIN,vultr.com,auto
  - DOMAIN-SUFFIX,ad.com,REJECT
  - GEOIP,CN,DIRECT
  - MATCH,auto
```

</details>

### Clash log

```
INFO[0000] Start initial compatible provider auto
INFO[0000] RESTful API listening at: 127.0.0.1:9090
INFO[0000] HTTP proxy listening at: 127.0.0.1:7890
INFO[0000] SOCKS proxy listening at: 127.0.0.1:7891
WARN[0000] Failed to start Redir UDP Listener: UDP redir not supported on current platform
INFO[0000] Redir proxy listening at: 127.0.0.1:7892
DEBU[0003] [DNS] lax-ca-us-ping.vultr.com --> 108.61.219.200
INFO[0003] [TCP] 127.0.0.1:57427 --> lax-ca-us-ping.vultr.com match Match() using auto[ssr]
然后就卡住了
```

### 环境 Environment

* 操作系统 (the OS that the Clash core is running on)
macOS 10.15.7
* 网路环境或拓扑 (network conditions/topology)
普通家庭宽带网络环境，一层路由器

* iptables，如果适用 (if applicable)
防火墙设置无误
* ISP 有没有进行 DNS 污染 (is your ISP performing DNS pollution?)
没有污染
* 其他 (any other information that would be useful)
暂无

### 说明 Description

使用的工具版本：
clash 最新release的clash-darwin-amd64-v1.2.0，以及最近测试版的二进制程序clash-darwin-amd64-2020.10.29.g5e54f48
sspanel dev分支的d6861ecb844e1def870f911e51f022871000fc7a
对接sspanel的ssr后端 fanvinga/docker-ssrmu
Shadowsocks-NG-R8 最后release，1.4.4-R8

### 重现问题的具体布骤 Steps to Reproduce

重现例子中，展示了3组对照，分别是
- 使用Shadowsocks-NG-R8和clash二进制程序连接auth_chain_a协议单端口节点
- 使用clash二进制程序连接auth_chain_a协议单端口节点（机场常用）和auth_chain_a协议普通节点（个人搭建）
- 使用clash二进制程序连接auth_chain_a协议单端口节点和连接auth_aes128_sha1协议单端口节点

---
下面以大多数机场服务商使用的sspanel-uim面板为例子
1. 搭建一个sspanel面板
2. 添加2个单端口承载用户使用auth_chain_a协议和auth_aes128_sha1协议
3. 添加2个单端口承载节点
4. 再添加2个节点，并都设置好端口偏移，和只启用单端口
5. 作为用户，在用户中心获得使用auth_chain_a节点信息，添加到Shadowsocks-NG-R8的节点面板，和Clash的config.yaml中
6. 打开terminal设置clash的http代理，输入`export http_proxy="http://localhost:7890"`
7. 使用`wget http://lax-ca-us-ping.vultr.com/vultr.com.100MB.bin`
8. 发现wget无法拉取文件，重复显示Retry
9. 在terminal换Shadowsocks-NG-R8的http代理，输入`unset http_proxy  && export http_proxy="http://localhost:1087"`
10. 终端输入`wget http://lax-ca-us-ping.vultr.com/vultr.com.100MB.bin`可以看到进度条，正常拉取文件
11. 修改clash.yaml配置文件中ssr节点信息，填写采用auth_aes128_sha1协议的节点，然后终端用回clash的http代理
12. wget正常拉取文件
13. 修改clash.yaml配置文件中ssr节点信息，填写自己搭建（使用逗比根据地脚本ssrmu.sh）的auth_aes128_sha1协议的节点（不需要使用协议参数进行鉴权）
14. wget正常拉取文件

**我预期会发生……？**

我预期clash.yaml中ssr节点使用auth_chain_a和auth_aes128_sha1协议一样正常使用，和Shadowsocks-NG-R8效果相同

**实际上发生了什么？**

使用clash二进制程序clash-darwin-amd64-v1.2.0无法连接auth_chain_a协议的ssr单端口节点

### 可能的解决方案 Possible Solution

我不懂clash代码，但是我觉得可能是使用auth_chain_a协议时，没有发送协议参数信息，或者其他相关问题。

### 更多信息 More Information
在clash对需要鉴权的auth_chain_a协议单端口节点连接时，python版ssr后端显示
```
ERROR    auth_chain.py:505 auth_chain_a data uncorrect auth HMAC-MD5 from ...

WARNING  common.py:302 unsupported addrtype 69, maybe wrong password or encryption method

WARNING  tcprelay.py:630 Protocol ERROR, TCP ogn data b'xxxxxxxxx...' from xxxx via port xxx

WARNING  tcprelay.py:647 TCP data redir b'github.com':80 b'xxxxx'
```
