### ISSUE TITLE
Endless DNS errors

### ISSUE THREAD

**Issue by BirkhoffLee** [Dreamacro/clash#106]
There's endless DNS errors appearing in the console:

 ```
DEBU[0680] [DNS] answer length is zero: &dns.Msg{MsgHdr:dns.MsgHdr{Id:0x2a4c, Response:true, Opcode:0, Authoritative:false, Truncated:false, RecursionDesired:true, RecursionAvailable:true, Zero:false, AuthenticatedData:false, CheckingDisabled:false, Rcode:0}, Compress:false, Question:[]dns.Question{dns.Question{Name:"dns.rubyfish.cn.", Qtype:0x1c, Qclass:0x1}}, Answer:[]dns.RR(nil), Ns:[]dns.RR{(*dns.SOA)(0xc0007e9c80)}, Extra:[]dns.RR{(*dns.OPT)(0xc00018d500)}}
DEBU[0680] [DNS] msg to ip error: Can't parse msg
```

along with some of my Shadowsocks server domain's errors. DNS section in `config.yml`:

```yaml
dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:53
  enhanced-mode: redir-host
  nameserver:
    - 119.29.29.29
    - 223.5.5.5
    - 114.114.114.114
    - tls://dns.rubyfish.cn:853
  fallback:
    - 101.132.183.99
    - tls://dns.rubyfish.cn:853
    - tls://dns.google
```
