### ISSUE TITLE
[Bug] 本地配置了rules访问dial DIRECT error: couldn't find ip

### ISSUE THREAD

**Issue by ishwy** [Dreamacro/clash#1067]
Clash config
```
port: 7890
socks-port: 7891
allow-lan: false
mode: rule
log-level: info
external-controller: '127.0.0.1:9090'
experimental:
    ignore-resolve-fail: true
dns:
    enable: true
    ipv6: false
    enhanced-mode: redir-host
    nameserver: [1.2.4.8, 223.5.5.5]
    fallback: ['tls://1.0.0.1:853', 'tls://dns.google:853']
rules:
    - 'DOMAIN,i.dddd.cc,DIRECT'
 .....
```
Clash log
```
2020-11-09 11:41:12[warning] dial DIRECT error: couldn't find ip
2020-11-09 11:41:15[warning] dial DIRECT error: couldn't find ip
2020-11-09 11:41:16[warning] dial DIRECT error: couldn't find ip
```
说明 Description
```
1. 使用的的规则判断,就如上面配置,我在上面写了***'DOMAIN,i.dddd.cc,DIRECT'***, 这个域名我在hosts映射的是我本机的127.0.0.1, 但是却报错couldn't find ip
2. 使用的是Mac Ver: 1.30.2
```
重现问题的具体布骤 Steps to Reproduce
```
1. 开启规则判断
2. 设置为系统代理
3. 配置rules规则
```
