### ISSUE TITLE
[Feature] 让开源版可以忽略规则中不支持的premium部分

### ISSUE THREAD

**Issue by Artoria2e5** [Dreamacro/clash#1102]
- [x] 我已经在 [Issue Tracker](……/) 中找过我要提出的请求

请注意，如果你并没有遵照这个 issue template 填写内容，我们将直接关闭这个 issue。

我都确认过了，我要继续提交。

### 说明 Description
现在非常多服务商（呃……）提供的 clash 订阅含有 premium 专属的一些内容，会导致开源版加载失败。开源版应该：
* （短期方案）加入跳过处理 premium 配置内容的功能，或者做个空壳实现跳跳警告
* （长期方案）达成一个“可忽略内容”的协定，例如说 key 以 `x-` 开头的都是可忽略的私有内容，并且把 premium 内容都这样迁移

### Clash core config & log
```yaml
# 有关部分
rule-providers:
  reject:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/reject.txt"
    path: ./ruleset/reject.yaml
    interval: 86400
  # ...
rules:
  - RULE-SET,reject,广告屏蔽
```

这个应该够了
![image](https://user-images.githubusercontent.com/6459309/100326461-f8f8f600-3004-11eb-84d4-679b48684ab1.png)

### 环境 Environment

* Windows amd64
* Clash 1.3.0 和 premium 20201120
