### ISSUE TITLE
[Bug] macOS 11.0.1（Big Sur） 下与最新版 adguard v2.5.1.928 不兼容

### ISSUE THREAD

**Issue by invisprints** [Dreamacro/clash#1105]
- [x] 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [x] 我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题
- [x] 这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题

### Clash config

<details>
  <summary>config.yaml</summary>

```yaml
port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
ipv6: true

tun:
  enable: true
  stack: system

dns:
  enable: true
  ipv6: true
  listen: 0.0.0.0:53
  enhanced-mode: redir-host # 或 fake-ip
  fake-ip-range: 198.18.0.1/16 # 如果你不知道这个参数的作用，请勿修改
  
  nameserver:
     - 1.2.4.8
     - 114.114.114.114
     - 223.5.5.5
     - tls://13800000000.rubyfish.cn:853
     
  fallback: # 与 nameserver 内的服务器列表同时发起请求，当规则符合 GEOIP 在 CN 以外时，fallback 列表内的域名服务器生效。
     - tls://13800000000.rubyfish.cn:853
     - tls://1.0.0.1:853
     - tls://dns.google:853
  fallback-filter:
    geoip: true # 默认
    ipcidr: # 在这个网段内的 IP 地址会被考虑为被污染的 IP
      - 240.0.0.0/4

proxies:
  - {name: name, server: ip, port: port, type: ss, cipher: cipher, password: password}

 proxy-groups:
  - name: 🔰 节点选择
    type: select
    proxies:
      - ♻️ 自动选择
      - 🎯 全球直连
      - name
  - name: ♻️ 自动选择
    type: url-test
    url: http://www.gstatic.com/generate_204
    interval: 300
    proxies:
      - name
  - name: 🎯 全球直连
    type: select
    proxies:
      - DIRECT
  - name: 🐟 漏网之鱼
    type: select
    proxies:
      - 🔰 节点选择
      - 🎯 全球直连
      - ♻️ 自动选择
      - name
rules:
 - GEOIP,CN,🎯 全球直连
 - MATCH,🐟 漏网之鱼
```

</details>

### Clash log

```
2020-11-28 16:08:52[info] [UDP] 127.0.0.1:64488 --> 2001:da8:8008:119:6d9:f5ff:fe98:7928 match GeoIP(CN) using 🎯 全球直连[DIRECT]
2020-11-28 16:08:52[info] [UDP] 127.0.0.1:49697 --> 2001:da8:8008:119:6d9:f5ff:fe98:7928 match GeoIP(CN) using 🎯 全球直连[DIRECT]
2020-11-28 16:08:52[info] [TCP] 127.0.0.1:60607 --> 31.13.93.26 match Match() using 🐟 漏网之鱼[c12s4]
2020-11-28 16:08:55[info] [TCP] 127.0.0.1:60609 --> 140.82.114.26 match Match() using 🐟 漏网之鱼[c12s4]
2020-11-28 16:08:56[info] [TCP] 127.0.0.1:60611 --> 140.82.114.26 match Match() using 🐟 漏网之鱼[c12s4]
```

### 环境 Environment

* 操作系统 (the OS that the Clash core is running on)
macOS 11.0.1
ClashX Pro 1.31.0.1 e77989 或 clash-darwin-amd64-2020.11.20 
* 网路环境或拓扑 (network conditions/topology)
无线局域网

### 说明 Description
macOS 11.0.1（Big Sur） 下，Clash 的代理功能与最新版 adguard v2.5.1.928 的广告过滤功能只能二选一。
Surge for Mac 能与 adguard 同时工作

### 重现问题的具体布骤 Steps to Reproduce

按照这里的说明设置 https://kb.adguard.com/en/macos/solving-problems/big-sur-issues
Surge 能正常工作（在增强模式下）
但 Clash 采用跟 Surge 相同的操作后无法代理网页，只能访问国内网站，无法访问代理网站。

**Comment by Fndroid** [comment]
高级设置里把upstream.proxy设置上就好了，协议``socks5``，端口是``mixed-port``

![image](https://user-images.githubusercontent.com/16091562/100546236-337bc080-329b-11eb-9db4-6793eb9c8b26.png)

但是这样的话，``PROCESS-NAME``规则就无法生效了。

**Comment by invisprints** [comment]
请问你的 Clash config 跟我一致吗？代理和广告过滤我还是只能二选一

**Comment by Fndroid** [comment]
和config没有关系，Adguard会在系统里安装一个VPN服务，你要像我上面这样设置之后，关闭ClashX的系统代理，这样流量先进入Adguard，经过Adguard再到Clash处理。

按照你到配置，也就是在高级设置里把upstream.proxy设置成``socks5://localhost:7891``，upstream.proxy.socks5udp改成``true``就好了。只要关闭ClashX的系统代理，流量就会在经过Adguard之后进入Clash。

**Comment by invisprints** [comment]
你用的是 ClashX 而不是 ClashX Pro 吗，顺便再问下你的DNS用的是系统默认的还是Clash 配置的？我按照你这样配置无法访问代理网站。你看我的 Clash log 里都是 IP 地址，感觉不太对

**Comment by Fndroid** [comment]
只有IP地址似乎是预期表现，即使是Surge也是这样，这个似乎是Adguard的问题。

如果是使用ClashX Pro，可以通过将系统DNS修改为``198.18.0.2``，这样Clash也能反推出来域名。

**Comment by invisprints** [comment]
你的意思是 clashX （非Pro）也可以同时实现广告过滤和代理功能吗？我提供的配置文件里DNS部分 disable也行吗？我一直无法实现代理和广告屏蔽同时work，想先找个最小实现看看。

**Comment by Fndroid** [comment]
可以同时使用，但也会有上面说的问题，比如只有IP没有域名，PROCESS-NAME规则无法使用。

没有域名的问题，应该是Adguard自身的问题。或者暂时的解决方案还是：使用ClashX Pro的增强模式，并把系统DNS改为``198.18.0.1``，默认是``198.18.0.2``

**Comment by Fndroid** [comment]
你这个配置文件有点问题，配置了dns和tun，但是tun里没有配置dns-hijack，所以ClashX Pro的增强模式下也用不了。你把dns和tun两个部分都删掉估计就行了。

**Comment by invisprints** [comment]
测试了下，还是有点问题
1. 使用 ClashX
AdGuard 部分如@Fndroid所说，把upstream.proxy设置成`socks5://localhost:7890`，`upstream.proxy.socks5udp`改成`true`
ClashX 部分关闭系统代理，配置文件如下：
<details>
  <summary>config.yaml</summary>

```yaml
port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
ipv6: true

proxies:
  - {name: name, server: ip, port: port, type: ss, cipher: cipher, password: password}

proxy-groups:
- name: 🔰 节点选择
  type: select
  proxies:
    - ♻️ 自动选择
    - 🎯 全球直连
    - name
- name: ♻️ 自动选择
  type: url-test
  url: http://www.gstatic.com/generate_204
  interval: 300
  proxies:
    - name
- name: 🎯 全球直连
  type: select
  proxies:
    - DIRECT
- name: 🐟 漏网之鱼
  type: select
  proxies:
    - 🔰 节点选择
    - 🎯 全球直连
    - ♻️ 自动选择
    - name

rules:
 - GEOIP,CN,🎯 全球直连
 - MATCH,🐟 漏网之鱼
```
</details>

其他都保持默认，测试效果是可以正常屏蔽广告，**无法代理国外网页**。

2. 使用 ClashX Pro
换成 ClashX Pro时重启了下电脑，尽量避免 bugOS 带来的影响
所有配置跟 1. 使用 ClashX 相同，区别是开启增强模式。仍然关闭系统代理。
测试效果是可以正常代理国外网页，**无法正常屏蔽广告**。

可能跟我电脑硬件也有关系。目前 workaround 是 Safari 换成 Edge，AdGuard 换成 uBlock Origin，不想折腾了。

感谢 @Fndroid 耐心解答！
