### ISSUE TITLE
[Bug] VMess HTTP/2 URLTest 阻塞

### ISSUE THREAD

**Issue by Sansui233** [Dreamacro/clash#1110]
------------------------------------------------------------------

### Clash config

<details>
  <summary>config.yaml</summary>

```yaml
mixed-port: 7891
# RESTful API for clashr
external-controller: 127.0.0.1:9091
allow-lan: false
mode: rule
log-level: warning

proxies:
  - {"name":"vmessh2","server":"awdhhawhuhudiihuawhuid.mhk.gs","type":"vmess","country":"🇭🇰 HK","port":443,"uuid":"44cded5c-b1b2-43ff-897f-e37ee1378f20","alterId":2,"cipher":"auto","network":"h2","servername":"awdhhawhuhudiihuawhuid.mhk.gs","http-opts":{},"h2-opts":{"host":["awdhhawhuhudiihuawhuid.mhk.gs"],"path":"/"},"tls":true,"skip-cert-verify":true}

proxy-groups:
  - name: "PROXY"
    type: url-test
    url: 'http://www.gstatic.com/generate_204'
    interval: 60
    proxies:
      - vmessh2
rules:
  - DOMAIN-SUFFIX,google.com,PROXY
  - DOMAIN-KEYWORD,google,DIRECT
  - DOMAIN,google.com,DIRECT
  - DOMAIN-SUFFIX,ad.com,REJECT
  - GEOIP,CN,DIRECT
  - MATCH,DIRECT
```

</details>

### Clash log

除了Info Start外，无有效日志输出

### 环境 Environment

* 操作系统 (the OS that the Clash core is running on)
macOS mojave
* 网路环境或拓扑 (network conditions/topology)
……
* iptables，如果适用 (if applicable)
……
* ISP 有没有进行 DNS 污染 (is your ISP performing DNS pollution?)
……
* 其他 (any other information that would be useful)
……

### 说明 Description

当对Vmess h2使用URLTest时，url为`http://www.gstatic.com/generate_204`，timeout为10000ms，进程会阻塞。

经过多次调试，发现阻塞代码位于：为component/vmess/conn.go > sendRequest()

```go
func (vc *Conn) sendRequest() error {
    ...
    _, err := vc.Conn.Write(h.Sum(nil)) // 阻塞
```

使用external control请求的URL为

```
http://127.0.0.1:9091/proxies/vmessh2/delay?url=http://www.gstatic.com/generate_204&timeout=10000
```

其中timeout设置为10s。但10s后并未释放连接而是继续卡在相同的地方。

使用的vmess h2 proxy见config，为DNS查找的ip有效但代理失效的proxy。

### 重现问题的具体布骤 Steps to Reproduce

- 使用上述config文件直接运行，使用external control进行delay请求即可复现。

**我预期会发生……？**
- 返回延迟测试值。

**实际上发生了什么？**
- 延迟测试阻塞，external api一直转圈。实际为sendRequest中阻塞。

### 可能的解决方案 Possible Solution

不太理解传输层的实现，抱歉。
