### ISSUE TITLE
[Bug] https 代理一段时间后失灵

### ISSUE THREAD

**Issue by zegnog** [Dreamacro/clash#1112]
------------------------------------------------------------------

### Clash config

<details>
  <summary>config.yaml</summary>

```yaml
dns:
  enable: true
  ipv6: false
  nameserver:
    - 114.114.114.114 # default value
    - 8.8.8.8 # default value
    - tls://dns.rubyfish.cn:853 # DNS over TLS
    - https://1.1.1.1/dns-query # DNS over HTTPS
 
# HTTP 代理端口
port: 7890

# SOCKS5 代理端口
socks-port: 7891

# Linux 和 macOS 的 redir 代理端口 (如需使用此功能，请取消注释)
# redir-port: 7892

# 允许局域网的连接（可用来共享代理）
allow-lan: false

# 规则模式：Rule（规则） / Global（全局代理）/ Direct（全局直连）
mode: Rule

# 设置日志输出级别 (默认级别：silent，即不输出任何内容，以避免因日志内容过大而导致程序内存溢出）。
# 5 个级别：silent / info / warning / error / debug。级别越高日志输出量越大，越倾向于调试，若需要请自行开启。
log-level: info

# clash 的 RESTful API
external-controller: 127.0.0.1:9090

# 您可以将静态网页资源（如 clash-dashboard）放置在一个目录中，clash 将会服务于 `${API}/ui`
# 参数应填写配置目录的相对路径或绝对路径。
# external-ui: folder

# RESTful API 的口令 (可选)
# secret: ""

# Clash for Windows
cfw-bypass:
  - qq.com
  # - music.163.com
  # - '*.music.126.net'
  - localhost
  - 127.*
  - 10.*
  - 172.16.*
  - 172.17.*
  - 172.18.*
  - 172.19.*
  - 172.20.*
  - 172.21.*
  - 172.22.*
  - 172.23.*
  - 172.24.*
  - 172.25.*
  - 172.26.*
  - 172.27.*
  - 172.28.*
  - 172.29.*
  - 172.30.*
  - 172.31.*
  - 192.168.*
  - <local>
cfw-latency-timeout: 5000

# 代理节点
proxies:
# 更多协议配置示例：https://github.com/Dreamacro/clash/blob/master/README.md

# 加密算法推荐：AEAD_AES_128_GCM AEAD_AES_192_GCM AEAD_AES_256_GCM AEAD_CHACHA20_POLY1305

# http
- name: "http"
  type: http
  server: server
  port: 443
  username: username
  password: passwd
  tls: true # https
  skip-cert-verify: true
# Shadowsocks + OBFS

# 代理组策略
proxy-groups:

# 代理节点选择
  - name: "ChinaVPN"
    type: select
    proxies: 
      - "http"
    url: "https://google.cn/generate_204"
    interval: 300
    tolerance: 1000

rules:
 
# 绕过代理 - 北美视频网站
- DOMAIN-SUFFIX,primevideo.com,DIRECT
- DOMAIN-SUFFIX,netflix.com,DIRECT
- DOMAIN-SUFFIX,youtube.com,DIRECT
- DOMAIN-SUFFIX,google.com,DIRECT
# 国内二级域名
- DOMAIN-SUFFIX,edu.cn,ChinaVPN
- DOMAIN-SUFFIX,gov.cn,ChinaVPN
# AcFun
- DOMAIN-SUFFIX,acfun.cn,ChinaVPN
- DOMAIN-SUFFIX,acfun.com,ChinaVPN
- DOMAIN-SUFFIX,aixifan.com,ChinaVPN
# 网易
- DOMAIN-SUFFIX,163.com,ChinaVPN
- DOMAIN-SUFFIX,126.com,ChinaVPN
- DOMAIN-SUFFIX,127.net,ChinaVPN
- DOMAIN-SUFFIX,netease.com,ChinaVPN
- DOMAIN-SUFFIX,163yun.com,ChinaVPN
- DOMAIN-SUFFIX,126.net,ChinaVPN
# 腾讯
# - DOMAIN-SUFFIX,qq.com,ChinaVPN
# - DOMAIN-SUFFIX,soso.com,ChinaVPN
# - DOMAIN-SUFFIX,qpic.cn,ChinaVPN
# - DOMAIN-SUFFIX,gtimg.cn,ChinaVPN
# - DOMAIN-SUFFIX,weixin.com,ChinaVPN
# - DOMAIN-SUFFIX,qlogo.cn,ChinaVPN
# - IP-CIDR,203.205.192.0/18,ChinaVPN
# 新浪
# - DOMAIN-SUFFIX,weibo.com,ChinaVPN
# - DOMAIN-SUFFIX,sinajs.cn,ChinaVPN
# - DOMAIN-SUFFIX,sina.com,ChinaVPN
# - DOMAIN-SUFFIX,sina.cn,ChinaVPN
# - DOMAIN-SUFFIX,sina.com.cn,ChinaVPN
# - DOMAIN-SUFFIX,sinaimg.cn,ChinaVPN
# - DOMAIN-SUFFIX,sinajs.cn,ChinaVPN
# - DOMAIN-SUFFIX,miaopai.com,ChinaVPN
# - DOMAIN-SUFFIX,xiaoka.tv,ChinaVPN
# - DOMAIN-SUFFIX,t.cn,ChinaVPN
# 阿里
# - DOMAIN-SUFFIX,aliyun.com,ChinaVPN
# - DOMAIN-SUFFIX,taobao.com,ChinaVPN
# - DOMAIN-SUFFIX,alicdn.com,ChinaVPN
# - DOMAIN-SUFFIX,tmall.com,ChinaVPN
# - DOMAIN-SUFFIX,mmstat.com,ChinaVPN
# - DOMAIN-SUFFIX,tbcdn.com,ChinaVPN
# - DOMAIN-SUFFIX,alibabacloud.com,ChinaVPN
# - DOMAIN-SUFFIX,alipay.com,ChinaVPN
# - DOMAIN-SUFFIX,hichina.com,ChinaVPN
- DOMAIN-SUFFIX,xiami.com,ChinaVPN
- DOMAIN-SUFFIX,xiami.net,ChinaVPN
# 百度
- DOMAIN-SUFFIX,baidu.com,ChinaVPN
- DOMAIN-SUFFIX,bdstatic.com,ChinaVPN
- DOMAIN-SUFFIX,bcebos.com,ChinaVPN
- DOMAIN-SUFFIX,baidupcs.com,ChinaVPN
- DOMAIN-SUFFIX,qianqian.com,ChinaVPN
# Bilibili
# - DOMAIN-SUFFIX,hdslb.com,ChinaVPN
# - DOMAIN-SUFFIX,bilibili.com,ChinaVPN
# - DOMAIN-SUFFIX,biliapi.com,ChinaVPN
# - DOMAIN-SUFFIX,geetest.com,ChinaVPN
# - DOMAIN-SUFFIX,acgvideo.com,ChinaVPN
# - DOMAIN-SUFFIX,bilivideo.com,ChinaVPN
# 湖南TV
- DOMAIN-SUFFIX,hitv.com,ChinaVPN
- DOMAIN-SUFFIX,hunantv.com,ChinaVPN
- DOMAIN-SUFFIX,mgtv.com,ChinaVPN
# Migu
- DOMAIN-SUFFIX,cmvideo.cn,ChinaVPN
- DOMAIN-SUFFIX,migu.cn,ChinaVPN
- DOMAIN-SUFFIX,miguvideo.com,ChinaVPN
# 优酷
- DOMAIN-SUFFIX,soku.com,ChinaVPN
- DOMAIN-SUFFIX,youku.com,ChinaVPN
- DOMAIN-SUFFIX,ykimg.com,ChinaVPN
# 爱奇艺
- DOMAIN-SUFFIX,iqiyi.com,ChinaVPN
- DOMAIN-SUFFIX,iqiyipic.com,ChinaVPN
- DOMAIN-SUFFIX,qy.net,ChinaVPN
# 搜狐
- DOMAIN-SUFFIX,sohu.com,ChinaVPN
- DOMAIN-SUFFIX,sohu.com.cn,ChinaVPN
- DOMAIN-SUFFIX,itc.cn,ChinaVPN
- DOMAIN-SUFFIX,v-56.com,ChinaVPN
# Kugou, Kuwo
- DOMAIN-SUFFIX,kugou.com,ChinaVPN
- DOMAIN-SUFFIX,kuwo.cn,ChinaVPN
- DOMAIN-SUFFIX,koowo.com,ChinaVPN
# 知乎
# - DOMAIN-SUFFIX,zhihu.com,ChinaVPN
# - DOMAIN-SUFFIX,zhimg.com,ChinaVPN
# 秀米
- DOMAIN-SUFFIX,xiumi.us,ChinaVPN
# 豆瓣
# - DOMAIN-SUFFIX,douban.com,ChinaVPN
# - DOMAIN-SUFFIX,doubanio.com,ChinaVPN
# 天眼查
- DOMAIN-SUFFIX,tianyancha.com,ChinaVPN
# IP地址测试
- DOMAIN-SUFFIX,ip138.com,ChinaVPN
 
# 中国IP
# - GEOIP,CN,ChinaVPN
 

- MATCH,DIRECT
……
```

</details>

### Clash log

```
time="2020-12-02T23:34:39+01:00" level=info msg="Start initial compatible provider ChinaVPN"
time="2020-12-02T23:34:39+01:00" level=info msg="RESTful API listening at: 127.0.0.1:9090"
time="2020-12-02T23:34:39+01:00" level=info msg="Mixed(http+socks5) proxy listening at: 127.0.0.1:7890"
time="2020-12-02T23:34:40+01:00" level=info msg="[TCP] 127.0.0.1:49938 --> raw.githubusercontent.com match Match() using DIRECT"
time="2020-12-02T23:34:40+01:00" level=info msg="[TCP] 127.0.0.1:49937 --> api.github.com match Match() using DIRECT"
time="2020-12-02T23:35:19+01:00" level=info msg="[TCP] 127.0.0.1:49984 --> mobile.pipe.aria.microsoft.com match Match() using DIRECT"
time="2020-12-02T23:35:19+01:00" level=info msg="[TCP] 127.0.0.1:49987 --> mobile.pipe.aria.microsoft.com match Match() using DIRECT"
time="2020-12-02T23:35:21+01:00" level=info msg="[TCP] 127.0.0.1:49990 --> clientservices.googleapis.com match Match() using DIRECT"
time="2020-12-02T23:35:27+01:00" level=info msg="[TCP] 127.0.0.1:50003 --> vscode-sync.trafficmanager.net match Match() using DIRECT"
time="2020-12-02T23:36:51+01:00" level=info msg="[TCP] 127.0.0.1:50101 --> www.google.com using GLOBAL"
time="2020-12-02T23:36:54+01:00" level=info msg="[TCP] 127.0.0.1:50106 --> safebrowsing.googleapis.com using GLOBAL"
time="2020-12-02T23:36:54+01:00" level=info msg="[TCP] 127.0.0.1:50108 --> chrome.google.com using GLOBAL"
time="2020-12-02T23:36:54+01:00" level=info msg="[TCP] 127.0.0.1:50114 --> s2.music.126.net using GLOBAL"
time="2020-12-02T23:36:55+01:00" level=info msg="[TCP] 127.0.0.1:50113 --> music.163.com using GLOBAL"
time="2020-12-02T23:36:55+01:00" level=info msg="[TCP] 127.0.0.1:50120 --> clients4.google.com using GLOBAL"
time="2020-12-02T23:36:56+01:00" level=info msg="[TCP] 127.0.0.1:50123 --> oauthaccountmanager.googleapis.com using GLOBAL"
time="2020-12-02T23:36:56+01:00" level=info msg="[TCP] 127.0.0.1:50126 --> d27xxe7juh1us6.cloudfront.net using GLOBAL"
time="2020-12-02T23:36:56+01:00" level=info msg="[TCP] 127.0.0.1:50135 --> content-autofill.googleapis.com using GLOBAL"
time="2020-12-02T23:36:56+01:00" level=info msg="[TCP] 127.0.0.1:50129 --> s6.music.126.net using GLOBAL"
time="2020-12-02T23:36:56+01:00" level=info msg="[TCP] 127.0.0.1:50131 --> acstatic-dun.126.net using GLOBAL"
time="2020-12-02T23:36:56+01:00" level=info msg="[TCP] 127.0.0.1:50141 --> translate.google.cn using GLOBAL"
time="2020-12-02T23:36:56+01:00" level=info msg="[TCP] 127.0.0.1:50140 --> re.popupblockerscript.com using GLOBAL"
time="2020-12-02T23:36:57+01:00" level=info msg="[TCP] 127.0.0.1:50156 --> p1.music.126.net using GLOBAL"
time="2020-12-02T23:36:57+01:00" level=info msg="[TCP] 127.0.0.1:50146 --> st.qa.igame.163.com using GLOBAL"
time="2020-12-02T23:36:57+01:00" level=info msg="[TCP] 127.0.0.1:50147 --> st.qa.igame.163.com using GLOBAL"
time="2020-12-02T23:36:57+01:00" level=info msg="[TCP] 127.0.0.1:50152 --> ac.dun.163.com using GLOBAL"
time="2020-12-02T23:36:57+01:00" level=info msg="[TCP] 127.0.0.1:50151 --> ac.dun.163.com using GLOBAL"
time="2020-12-02T23:36:57+01:00" level=info msg="[TCP] 127.0.0.1:50158 --> p2.music.126.net using GLOBAL"
time="2020-12-02T23:36:57+01:00" level=info msg="[TCP] 127.0.0.1:50164 --> p2.music.126.net using GLOBAL"
time="2020-12-02T23:36:57+01:00" level=info msg="[TCP] 127.0.0.1:50162 --> p2.music.126.net using GLOBAL"
time="2020-12-02T23:36:57+01:00" level=info msg="[TCP] 127.0.0.1:50167 --> p2.music.126.net using GLOBAL"
time="2020-12-02T23:36:57+01:00" level=info msg="[TCP] 127.0.0.1:50163 --> p2.music.126.net using GLOBAL"
time="2020-12-02T23:36:57+01:00" level=info msg="[TCP] 127.0.0.1:50165 --> p2.music.126.net using GLOBAL"
time="2020-12-02T23:36:57+01:00" level=info msg="[TCP] 127.0.0.1:50172 --> iad.g.163.com using GLOBAL"
time="2020-12-02T23:36:58+01:00" level=info msg="[TCP] 127.0.0.1:50175 --> userstyles.org using GLOBAL"
time="2020-12-02T23:36:59+01:00" level=info msg="[TCP] 127.0.0.1:50180 --> sp0.baidu.com using GLOBAL"
time="2020-12-02T23:37:31+01:00" level=info msg="[TCP] 127.0.0.1:50223 --> api.live.bilibili.com using GLOBAL"
time="2020-12-02T23:37:31+01:00" level=info msg="[TCP] 127.0.0.1:50225 --> api.vc.bilibili.com using GLOBAL"
time="2020-12-02T23:37:42+01:00" level=warning msg="dial ChinaVPN to s3.music.126.net error: server_url:443 connect error: read tcp4 192.168.123.139:50241->server_ip:443: wsarecv: An existing connection was forcibly closed by the remote host."
time="2020-12-02T23:37:43+01:00" level=warning msg="dial ChinaVPN to s3.music.126.net error: server_url:443 connect error: read tcp4 192.168.123.139:50244->server_ip:443: wsarecv: An existing connection was forcibly closed by the remote host."
time="2020-12-02T23:37:43+01:00" level=warning msg="dial ChinaVPN to st.qa.igame.163.com error: server_url:443 connect error: read tcp4 192.168.123.139:50247->server_ip:443: wsarecv: An existing connection was forcibly closed by the remote host."
time="2020-12-02T23:37:43+01:00" level=warning msg="dial ChinaVPN to st.qa.igame.163.com error: server_url:443 connect error: read tcp4 192.168.123.139:50248->server_ip:443: wsarecv: An existing connection was forcibly closed by the remote host."
time="2020-12-02T23:37:44+01:00" level=warning msg="dial ChinaVPN to st.qa.igame.163.com error: server_url:443 connect error: read tcp4 192.168.123.139:50252->server_ip:443: wsarecv: An existing connection was forcibly closed by the remote host."
time="2020-12-02T23:37:44+01:00" level=warning msg="dial ChinaVPN to st.qa.igame.163.com error: server_url:443 connect error: read tcp4 192.168.123.139:50250->server_ip:443: wsarecv: An existing connection was forcibly closed by the remote host."
time="2020-12-02T23:37:44+01:00" level=warning msg="dial ChinaVPN to iad.g.163.com error: server_url:443 connect error: read tcp4 192.168.123.139:50254->server_ip:443: wsarecv: An existing connection was forcibly closed by the remote host."
time="2020-12-02T23:37:45+01:00" level=warning msg="dial ChinaVPN to st.qa.igame.163.com error: server_url:443 connect error: read tcp4 192.168.123.139:50259->server_ip:443: wsarecv: An existing connection was forcibly closed by the remote host."
time="2020-12-02T23:37:45+01:00" level=warning msg="dial ChinaVPN to st.qa.igame.163.com error: server_url:443 connect error: read tcp4 192.168.123.139:50257->server_ip:443: wsarecv: An existing connection was forcibly closed by the remote host."
time="2020-12-02T23:37:45+01:00" level=warning msg="dial ChinaVPN to iad.g.163.com error: server_url:443 connect error: read tcp4 192.168.123.139:50261->server_ip:443: wsarecv: An existing connection was forcibly closed by the remote host."
time="2020-12-02T23:37:45+01:00" level=info msg="[TCP] 127.0.0.1:50267 --> ssl.gstatic.com match Match() using DIRECT"
time="2020-12-02T23:37:45+01:00" level=warning msg="dial ChinaVPN to st.qa.igame.163.com error: server_url:443 connect error: read tcp4 192.168.123.139:50264->server_ip:443: wsarecv: An existing connection was forcibly closed by the remote host."
time="2020-12-02T23:37:45+01:00" level=warning msg="dial ChinaVPN to st.qa.igame.163.com error: server_url:443 connect error: read tcp4 192.168.123.139:50265->server_ip:443: wsarecv: An existing connection was forcibly closed by the remote host."
time="2020-12-02T23:37:46+01:00" level=warning msg="dial ChinaVPN to s1.music.126.net error: server_url:443 connect error: read tcp4 192.168.123.139:50271->server_ip:443: wsarecv: An existing connection was forcibly closed by the remote host."
time="2020-12-02T23:37:46+01:00" level=warning msg="dial ChinaVPN to s1.music.126.net error: server_url:443 connect error: read tcp4 192.168.123.139:50273->server_ip:443: wsarecv: An existing connection was forcibly closed by the remote host."
time="2020-12-02T23:37:51+01:00" level=info msg="[TCP] 127.0.0.1:50279 --> chat-pa.clients6.google.com match DomainSuffix(google.com) using DIRECT"
time="2020-12-02T23:37:58+01:00" level=info msg="[TCP] 127.0.0.1:50289 --> play.google.com match DomainSuffix(google.com) using DIRECT"
time="2020-12-02T23:38:00+01:00" level=info msg="[TCP] 127.0.0.1:50294 --> play.google.com match DomainSuffix(google.com) using DIRECT"
time="2020-12-02T23:38:16+01:00" level=info msg="[TCP] 127.0.0.1:50312 --> qbwup.imtt.qq.com match Match() using DIRECT"
time="2020-12-02T23:38:17+01:00" level=info msg="[TCP] 127.0.0.1:50316 --> 21.client-channel.google.com match DomainSuffix(google.com) using DIRECT"
time="2020-12-02T23:38:28+01:00" level=info msg="[TCP] 127.0.0.1:50333 --> ota.nvidia.com match Match() using DIRECT"
time="2020-12-02T23:38:29+01:00" level=info msg="[TCP] 127.0.0.1:50336 --> events.gfe.nvidia.com match Match() using DIRECT"
time="2020-12-02T23:38:36+01:00" level=info msg="[TCP] 127.0.0.1:50349 --> imgstatic.rixcloud.app match Match() using DIRECT"
time="2020-12-02T23:38:42+01:00" level=info msg="[TCP] 127.0.0.1:50355 --> nexusrules.officeapps.live.com match Match() using DIRECT"
time="2020-12-02T23:38:42+01:00" level=info msg="[TCP] 127.0.0.1:50356 --> nexusrules.officeapps.live.com match Match() using DIRECT"
time="2020-12-02T23:38:48+01:00" level=warning msg="dial ChinaVPN to s3.music.126.net error: server_url:443 connect error: read tcp4 192.168.123.139:50367->server_ip:443: wsarecv: An existing connection was forcibly closed by the remote host."
time="2020-12-02T23:38:48+01:00" level=warning msg="dial ChinaVPN to s2.music.126.net error: server_url:443 connect error: read tcp4 192.168.123.139:50365->server_ip:443: wsarecv: An existing connection was forcibly closed by the remote host."
time="2020-12-02T23:38:49+01:00" level=warning msg="dial ChinaVPN to s3.music.126.net error: server_url:443 connect error: read tcp4 192.168.123.139:50370->server_ip:443: wsarecv: An existing connection was forcibly closed by the remote host."
time="2020-12-02T23:38:49+01:00" level=warning msg="dial ChinaVPN to s2.music.126.net error: server_url:443 connect error: read tcp4 192.168.123.139:50372->server_ip:443: wsarecv: An existing connection was forcibly closed by the remote host."
time="2020-12-02T23:38:49+01:00" level=info msg="[TCP] 127.0.0.1:50377 --> re.popupblockerscript.com match Match() using DIRECT"
time="2020-12-02T23:38:50+01:00" level=warning msg="dial ChinaVPN to st.qa.igame.163.com error: server_url:443 connect error: read tcp4 192.168.123.139:50376->server_ip:443: wsarecv: An existing connection was forcibly closed by the remote host."
time="2020-12-02T23:38:50+01:00" level=warning msg="dial ChinaVPN to st.qa.igame.163.com error: server_url:443 connect error: read tcp4 192.168.123.139:50375->server_ip:443: wsarecv: An existing connection was forcibly closed by the remote host."
time="2020-12-02T23:38:50+01:00" level=warning msg="dial ChinaVPN to st.qa.igame.163.com error: server_url:443 connect error: read tcp4 192.168.123.139:50382->server_ip:443: wsarecv: An existing connection was forcibly closed by the remote host."
time="2020-12-02T23:38:50+01:00" level=warning msg="dial ChinaVPN to st.qa.igame.163.com error: server_url:443 connect error: read tcp4 192.168.123.139:50380->server_ip:443: wsarecv: An existing connection was forcibly closed by the remote host."
time="2020-12-02T23:38:50+01:00" level=warning msg="dial ChinaVPN to iad.g.163.com error: server_url:443 connect error: read tcp4 192.168.123.139:50384->server_ip:443: wsarecv: An existing connection was forcibly closed by the remote host."
time="2020-12-02T23:38:50+01:00" level=warning msg="dial ChinaVPN to st.qa.igame.163.com error: server_url:443 connect error: read tcp4 192.168.123.139:50389->server_ip:443: wsarecv: An existing connection was forcibly closed by the remote host."
time="2020-12-02T23:38:50+01:00" level=warning msg="dial ChinaVPN to st.qa.igame.163.com error: server_url:443 connect error: read tcp4 192.168.123.139:50387->server_ip:443: wsarecv: An existing connection was forcibly closed by the remote host."
time="2020-12-02T23:38:51+01:00" level=warning msg="dial ChinaVPN to iad.g.163.com error: server_url:443 connect error: read tcp4 192.168.123.139:50392->server_ip:443: wsarecv: An existing connection was forcibly closed by the remote host."
time="2020-12-02T23:38:51+01:00" level=warning msg="dial ChinaVPN to st.qa.igame.163.com error: server_url:443 connect error: read tcp4 192.168.123.139:50395->server_ip:443: wsarecv: An existing connection was forcibly closed by the remote host."
time="2020-12-02T23:38:51+01:00" level=warning msg="dial ChinaVPN to st.qa.igame.163.com error: server_url:443 connect error: read tcp4 192.168.123.139:50396->server_ip:443: wsarecv: An existing connection was forcibly closed by the remote host."
time="2020-12-02T23:38:51+01:00" level=warning msg="dial ChinaVPN to s1.music.126.net error: server_url:443 connect error: read tcp4 192.168.123.139:50398->server_ip:443: wsarecv: An existing connection was forcibly closed by the remote host."
time="2020-12-02T23:38:51+01:00" level=info msg="[TCP] 127.0.0.1:50402 --> www.notion.so match Match() using DIRECT"
time="2020-12-02T23:38:52+01:00" level=warning msg="dial ChinaVPN to s1.music.126.net error: server_url:443 connect error: read tcp4 192.168.123.139:50401->server_ip:443: wsarecv: An existing connection was forcibly closed by the remote host."
time="2020-12-02T23:38:52+01:00" level=warning msg="dial ChinaVPN to sp0.baidu.com error: server_url:443 connect error: read tcp4 192.168.123.139:50406->server_ip:443: wsarecv: An existing connection was forcibly closed by the remote host."
time="2020-12-02T23:38:53+01:00" level=warning msg="dial ChinaVPN to sp0.baidu.com error: server_url:443 connect error: read tcp4 192.168.123.139:50408->server_ip:443: wsarecv: An existing connection was forcibly closed by the remote host."

……
```

### 环境 Environment

* 操作系统 (the OS that the Clash core is running on)
windows/android/padavan
……
* 网路环境或拓扑 (network conditions/topology)
……
* iptables，如果适用 (if applicable)
……
* ISP 有没有进行 DNS 污染 (is your ISP performing DNS pollution?)
no
……
* 其他 (any other information that would be useful)
……

### 说明 Description

我是用 gost 在服务端配置的 https 代理。一开始完全没有任何问题，switchyomega 和 clash 都可以正常工作。过了两天只有 switchyomega 可以正常工作，curl 也显示 https 代理无恙。 clash 报告 connection reset by peers 。使用了不同平台的 clash ，照着文档修改了很多次 clash 配置无果。
### 重现问题的具体布骤 Steps to Reproduce

1. gost 设置 https 代理，命令如下：
```bash
sudo docker run -d --name gost \
        -v ${CERT_DIR}:${CERT_DIR}:ro \
        --net=host ginuerzh/gost \
        -L "http2://${USER}:${PASS}@${BIND_IP}:${PORT}?cert=${CERT}&key=${KEY}&probe_resist=file:/home/username/nichijou/index.html&knock=www.baidu.com"
```
参见：[](https://github.com/haoel/haoel.github.io/blob/master/scripts/install.ubuntu.18.04.sh)
2. 使用附上的配置文件。
3. 不定期之后...

**我预期会发生……？**

https 代理正常。
**实际上发生了什么？**

read tcp4 local_ip:port->server_ip:443: read connection reset by peers
