### ISSUE TITLE
请问TUN模式下如何让rules生效？

### ISSUE THREAD

**Issue by felixding** [Dreamacro/clash#1126]
------------------------------------------------------------------

### Clash config

<details>
  <summary>config.yaml</summary>

```yaml
port: 7890
socks-port: 7891
redir-port: 7892
allow-lan: false
mode: Rule
log-level: debug
external-controller: '127.0.0.1:9090'
secret: ''

tun:
  enable: true
  stack: system
  macOS-auto-route: true # auto set global route
  macOS-auto-detect-interface: true # conflict with interface-name

dns:
  enable: true
  nameserver:
    - 8.8.8.8
  fallback:
    - tls://1.0.0.1:853
    - tls://dns.google:853
  enhanced-mode: redir-host

proxies:
  - name: "US"
    type: ss

proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
        - "US"

rules:
  - DOMAIN,ifconfig.me,DIRECT
  - MATCH,PROXY

```

</details>

### 环境 Environment

* 操作系统 (the OS that the Clash core is running on)

Mac OS 11.0.1

* 网路环境或拓扑 (network conditions/topology)

家庭Wi-Fi

* ISP 有没有进行 DNS 污染 (is your ISP performing DNS pollution?)

无

* 其他 (any other information that would be useful)

Clash版本：2020.10.09 darwin amd64 Premium

### 重现问题的具体布骤 Steps to Reproduce

在命令行下执行 `./clash -f config.yml`

**我预期会发生……？**

在浏览器中访问 `ifconfig.me` 时，显示家里真实的IP。

**实际上发生了什么？**

但实际上显示的是VPS的IP，说明规则没有生效。

### 可能的解决方案 Possible Solution

使用同一个配置文件+Clash X Pro的话，可以得到预期结果，正常显示家里的IP。

不清楚是否是配置文件的写法有问题，烦请作者和大家指教。
