### ISSUE TITLE
[Bug] 使用 winsw 注册为服务并自动启动，无法使用 TUN 模式

### ISSUE THREAD

**Issue by mrzhiin** [Dreamacro/clash#1156]
### Clash config

<details>
  <summary>config.yaml</summary>

```yaml
log-level: warning
# RESTful web API listening address
external-controller: 127.0.0.1:9090
ipv6: true
dns:
  enable: true
  # listen: 0.0.0.0:53
  ipv6: true
  default-nameserver:
    - 114.114.114.114
    - 8.8.8.8
    - "[2001:4860:4860::8888]:53"
    - "[240C::6666]:53"
  enhanced-mode: redir-host
  nameserver:
    - https://doh.pub/dns-query
    - https://dns.alidns.com/dns-query
tun:
  enable: true
  stack: gvisor # only gvisor
  dns-hijack:
    - 198.18.0.2:53 # when `fake-ip-range` is 198.18.0.1/16, should hijack 198.18.0.2:53
  macOS-auto-route: true # auto set global route for Windows
  # It is recommended to use `interface-name`
  macOS-auto-detect-interface: true # auto detect interface, conflict with `interface-name`
```

</details>

### Clash log

```
time="2020-12-29T15:33:05+08:00" level=error msg="Start Tun interface error: Element not found."
```

### 环境 Environment

- 操作系统 (the OS that the Clash core is running on)

  Windows 10 20H2

### 说明 Description

clash TUN 模式，使用 winsw 注册为服务并自动启动，启动后能看到 clash tun 网卡，但显示未连接。重启 clash 后，TUN 正常。

winsw 配置：

```
<service>
    <id>Clash</id>
    <name>Clash</name>
    <description>Clash</description>
    <workingdirectory>C:\Programs\Clash</workingdirectory>
    <executable>clash-windows-amd64</executable>
    <arguments>-d etc</arguments>
    <depend>LanmanServer</depend>
    <depend>Tcpip</depend>
    <depend>Dhcp</depend>
    <depend>WlanSvc</depend>
    <depend>hns</depend>
    <depend>nvagent</depend>
    <depend>NcdAutoSetup</depend>
    <depend>netprofm</depend>
    <depend>nsi</depend>
    <depend>RasMan</depend>
    <depend>RpcSs</depend>
    <depend>NlaSvc</depend>
    <depend>NetSetupSvc</depend>
    <depend>Netman</depend>
    <log mode="reset"></log>
</service>
```

### 可能的解决方案 Possible Solution

如果 winsw 配置为延迟启动，则能正常开启 TUN
