### ISSUE TITLE
[Feature]能否增加规则中可以直接匹配proxy的功能

### ISSUE THREAD

**Issue by grayguest** [Dreamacro/clash#1158]
感谢你向 Clash Core 提交 Feature Request！
在提交之前，请确认：

- [x] 我已经在 [Issue Tracker](……/) 中找过我要提出的请求

请注意，如果你并没有遵照这个 issue template 填写内容，我们将直接关闭这个 issue。

我都确认过了，我要继续提交。

------------------------------------------------------------------

请附上任何可以帮助我们解决这个问题的信息，如果我们收到的信息不足，我们将对这个 issue 加上 *Needs more information* 标记并在收到更多资讯之前关闭 issue。

### Clash core config

```
port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: 127.0.0.1:9090
secret: xxxxxx
proxies:
- name: SS-01-美西GIA-500M高速
  server: xxx
  port: xxx
  type: ss
  cipher: chacha20-ietf-poly1305
  password: xxx
rules:
- MATCH,SS-01-美西GIA-500M高速

……
```

### Clash log

```
……
```

### 环境 Environment

* Clash Core 的操作系统 (the OS that the Clash core is running on)
Linux Mint
* 使用者的操作系统 (the OS running on the client)
Linux Mint
* 网路环境或拓扑 (network conditions/topology)
……
* iptables，如果适用 (if applicable)
……
* ISP 有没有进行 DNS 污染 (is your ISP performing DNS pollution?)
……
* 其他
……

### 说明 Description

能否像上述clash core config那样可以在规则中使用proxies下的name作为分流规则编写的一种情况，当然可以增加proxy groups对应每一个proxies，但是感觉稍微麻烦了些，且proxy providers里面没法定义proxy groups。

### 可能的解决方案 Possible Solution

可以在规则中使用proxies下的name作为分流规则编写的一种情况
