### ISSUE TITLE
[Bug]proxy-providers和rule-providers的file模式中interval选项是有效果的

### ISSUE THREAD

**Issue by grayguest** [Dreamacro/clash#1160]
------------------------------------------------------------------

### Clash config

<details>
  <summary>config.yaml</summary>

```yaml
port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: 127.0.0.1:9090
secret: xx
proxies:
- name: SS-01
  server: 
  port: 7077
  type: ss
  cipher: chacha20-ietf-poly1305
  password: 
- name: SS-05
  server: 
  port: 7077
  type: ss
  cipher: chacha20-ietf-poly1305
  password: 
rule-providers:
  SS-08-台湾-影音解锁:
    type: file
    behavior: classical
    path: ./SS-08-台湾-影音解锁.yaml
    interval: 6
rules:
# - MATCH,SS-08-台湾-影音解锁
  - RULE-SET,SS-08-台湾-影音解锁,SS-08-台湾-影音解锁
```

</details>

### Clash log

```
……
```

### 环境 Environment

* 操作系统 (the OS that the Clash core is running on)
Linux Mint
* 网路环境或拓扑 (network conditions/topology)
Linux Mint

### 说明 Description

经测试，proxy-providers和rule-providers的file模式中interval选项都是有效果的，可以把interval设置成一个比较小的值试试，比如6

### 可能的解决方案 Possible Solution

建议修改下文档相关，文档中好像描述得是不可用。
