### ISSUE TITLE
[Bug] connectex: A socket operation was attempted to an unreachable network

### ISSUE THREAD

**Issue by LittleRey** [Dreamacro/clash#1164]
------------------------------------------------------------------

### Clash config

<details>
  <summary>config.yaml</summary>

```yaml
# port: 7890
# socks-port: 7891
redir-port: 7892
mixed-port: 7890
allow-lan: true
bind-address: '*'
mode: rule
log-level: info
external-controller: :9090
secret: ''
ipv6: true
#external-ui: folder

# interface-name: 


############################################## DNS ##############################################

dns:
  enable: true
  ipv6: true
  listen: 0.0.0.0:53
  enhanced-mode: redir-host


############################################ fake ip ############################################
#  fake-ip-range: 198.18.0.1/16
#  fake-ip-filter: 
#    - '*.lan'
#    - localhost.ptlogin2.qq.com


########################################### redir-host ###########################################
#hosts:
  # 'mtalk.google.com': 108.177.125.188
  # '*.clash.dev': 127.0.0.1
  # '.dev': 127.0.0.1
  # 'alpha.clash.dev': '::1'


  default-nameserver:
    - 94.140.14.140
    - 208.67.222.222
    - 185.222.222.222
    - 1.1.1.1
    - 8.8.8.8

  nameserver:
#filtering doh
    - https://dns-unfiltered.adguard.com/dns-query
    - https://101.6.6.6:8443/dns-query
    - https://dns.alidns.com/dns-query
    - https://i.233py.com/dns-query
    - https://doh.360.cn/dns-query
    - https://dns.containerpi.com/dns-query
    - https://doh.qis.io/dns-query
#    - https://doh.pub/dns-query
#    - https://dns.233py.com/dns-query

#    - tls://dns-tls.qis.io:853
#    - tls://one.one.one.one:853
#    - tls://dns.google:853

  fallback: 
# non-filtering doh
    - https://cloudflare-dns.com/dns-query
    - https://dns-nosec.quad9.net:5053/dns-query
    - https://dns.digitale-gesellschaft.ch/dns-query
    - https://dns.aa.net.uk/dns-query
    - https://rdns.faelix.net
    - https://doh.dnslify.com/dns-query

    - https://dns.google.com/dns-query
#    - tls://dns.google:853
 
  fallback-filter:
    geoip: true
#    ipcidr:
#    - 240.0.0.0/4

  experimental:
    ignore-resolve-fail: true
    
tun:
  enable: true
  stack: gvisor # only gvisor
#  dns-hijack:
#    - 114.114.114.114:53 # when `fake-ip-range` is 198.18.0.1/16, should hijack 198.18.0.2:53
  macOS-auto-route: true # auto set global route for Windows
  # It is recommended to use `interface-name`
  macOS-auto-detect-interface: true # auto detect interface, conflict with `interface-name`


proxy-providers:
  Config:


  Fly2:


  Game:


  Game1:


  Classic:


  NeteaseUnblock:


proxy-groups:
  - name: Proxy
    type: select
    use:
      - Config
      - Classic
      - Fly2
    proxies:
      - PingTest
      - DIRECT

    
  - name: PingTest
    type: url-test
    url: https://www.google.com/generate_204
    interval: 300
    use:
      - Config
      - Classic
      - Fly2
 
#  - name: LoadBalance
#    type: load-balance
#    use:
#      - Config
#      - Classic
#      - Fly2
#    url: https://www.google.com/generate_204
#    interval: 300
    
#  - name: DnsBlock
#    type: select
#    proxies:
#      - REJECT

  - name: Game
    type: select
    use:
      - Game1
      - Game
    proxies:
      - DIRECT
      - Proxy

  - name: NeteaseMusic
    type: select
    use:
      - NeteaseUnblock
    proxies:
      - DIRECT
 
  - name: DirectConnect
    type: select
    use:
      - Config
      - Classic
      - Fly2
    proxies:
      - DIRECT
      - Proxy

  - name: Final
    type: select
    use:
      - Config
      - Classic
      - Fly2
    proxies:
      - DIRECT
      - Proxy

rule-providers:
  Local:
    type: http
    behavior: classical
    path: ./Rule-Providers/Local.list
    url: https://cors.buildtest.site/https://gist.githubusercontent.com/LittleRey/2fc3a89115d2d24167bdc19a61523c77/raw/Local.list
    interval: 1800

  Proxy:
    type: http
    behavior: classical
    path: ./Rule-Providers/Proxy.list
    url: https://cors.buildtest.site/https://gist.githubusercontent.com/LittleRey/2fc3a89115d2d24167bdc19a61523c77/raw/Proxy.list
    interval: 1800

  Win-Game:
    type: http
    behavior: classical
    path: ./Rule-Providers/Win-Game.list
    url: https://cors.buildtest.site/https://gist.githubusercontent.com/LittleRey/2fc3a89115d2d24167bdc19a61523c77/raw/Win-Game.list
    interval: 1800

  NeteaseMusic:
    type: http
    behavior: classical
    path: ./Rule-Providers/NeteaseMusic.list
    url: https://cors.buildtest.site/https://gist.githubusercontent.com/LittleRey/2fc3a89115d2d24167bdc19a61523c77/raw/NeteaseMusic.list
    interval: 1800

  NeteaseMedia:
    type: http
    behavior: classical
    path: ./Rule-Providers/NeteaseMedia.list
    url: https://cors.buildtest.site/https://gist.githubusercontent.com/LittleRey/2fc3a89115d2d24167bdc19a61523c77/raw/NeteaseMedia.list
    interval: 1800

  GeoIP-Foreign:
    type: http
    behavior: classical
    path: ./Rule-Providers/GeoIP-Foreign.list
    url: https://cors.buildtest.site/https://gist.githubusercontent.com/LittleRey/2fc3a89115d2d24167bdc19a61523c77/raw/GeoIP-Foreign.list
    interval: 1800

  GeoIP-CN:
    type: http
    behavior: classical
    path: ./Rule-Providers/GeoIP-CN.list
    url: https://cors.buildtest.site/https://gist.githubusercontent.com/LittleRey/2fc3a89115d2d24167bdc19a61523c77/raw/GeoIP-CN.list
    interval: 1800

rules:
 - RULE-SET,Local,DirectConnect
 - RULE-SET,NeteaseMedia,DirectConnect
 - RULE-SET,NeteaseMusic,NeteaseMusic
 - RULE-SET,Win-Game,Game
 - RULE-SET,Proxy,Proxy
 - RULE-SET,GeoIP-CN,DirectConnect
 - RULE-SET,GeoIP-Foreign,Proxy


 - MATCH,Final
```

</details>

### Clash log

```
time="2021-01-03T22:10:30+08:00" level=warning msg="[TCP] dial DirectConnect (match RuleSet/Local) to gist.github.com error: dial tcp4 192.168.2.213:0->243.185.187.39:443: connectex: A socket operation was attempted to an unreachable network."
time="2021-01-03T22:10:35+08:00" level=warning msg="[TCP] dial DirectConnect (match RuleSet/Local) to gist.github.com error: dial tcp4 192.168.2.213:0->243.185.187.39:443: connectex: A socket operation was attempted to an unreachable network."
time="2021-01-03T22:10:35+08:00" level=warning msg="[TCP] dial DirectConnect (match RuleSet/Local) to gist.github.com error: dial tcp4 192.168.2.213:0->243.185.187.39:443: connectex: A socket operation was attempted to an unreachable network."
```

### 环境 Environment

* 操作系统 (the OS that the Clash core is running on)
……
* 网路环境或拓扑 (network conditions/topology)
……
* iptables，如果适用 (if applicable)
……
* ISP 有没有进行 DNS 污染 (is your ISP performing DNS pollution?)
……
* 其他 (any other information that would be useful)
……

### 重现问题的具体布骤 Steps to Reproduce

1. [First Step]
2. [Second Step]
3. ……

**我预期会发生……？**

**实际上发生了什么？**
