### ISSUE TITLE
[Bug] windows上的tun模式导致dns泄露

### ISSUE THREAD

**Issue by rayc345** [Dreamacro/clash#1177]
------------------------------------------------------------------

### Clash config

<details>
  <summary>config.yaml</summary>

```yaml
mixed-port: 7890
allow-lan: true
mode: rule
log-level: debug
ipv6: true
external-controller: 127.0.0.1:9090
external-ui: dashboard

dns:
  enable: true
  default-nameserver:
    - 114.114.114.114
    - 8.8.8.8
  enhanced-mode: fake-ip # redir-host
  fake-ip-range: 198.18.0.1/16
  use-hosts: true
  fake-ip-filter:
    - '*.lan'
    - localhost.ptlogin2.qq.com
  nameserver:
    - tls://dns.rubyfish.cn:853
  fallback:
    - tls://dns.rubyfish.cn:853
    - https://1.1.1.1/dns-query
  fallback-filter:
    geoip: true
    ipcidr:
      - 240.0.0.0/4

tun:
  enable: true
  stack: gvisor
  dns-hijack:
    - 198.18.0.2:53
  macOS-auto-route: true
  macOS-auto-detect-interface: true

proxies:
  - name: "Proxy"
    type: vmess
    server: 00000
    port: 0000
    uuid: 000000
    alterId: 1
    cipher: auto

rules:
  - MATCH,Proxy
……
```

</details>

### Clash log

```
time="2021-01-12T14:49:16+08:00" level=debug msg="[TUN] hijack udp dns: 198.18.0.2:53"
time="2021-01-12T14:49:16+08:00" level=debug msg="[TUN] hijack udp dns: 198.18.0.2:53"
time="2021-01-12T14:49:16+08:00" level=debug msg="[TUN] hijack udp dns: 198.18.0.2:53"
time="2021-01-12T14:49:16+08:00" level=info msg="[TCP] 198.18.0.1:1054 --> r2---sn-a5mlrn7z.googlevideo.com match RuleSet(Global) using Proxy[Unicom]"
time="2021-01-12T14:49:16+08:00" level=debug msg="[TUN] hijack udp dns: 198.18.0.2:53"
time="2021-01-12T14:49:16+08:00" level=debug msg="[DNS] client.wns.windows.com --> 52.139.250.253"
time="2021-01-12T14:49:16+08:00" level=info msg="[TCP] 198.18.0.1:1056 --> client.wns.windows.com match Match() using Proxy[Unicom]"
time="2021-01-12T14:49:16+08:00" level=info msg="[UDP] 198.18.0.1:64161 --> 239.255.255.250 match IPCIDR(224.0.0.0/4) using DIRECT"
time="2021-01-12T14:49:16+08:00" level=debug msg="[TUN] hijack udp dns: 198.18.0.2:53"
time="2021-01-12T14:49:16+08:00" level=info msg="[TCP] 198.18.0.1:1064 --> yt4.ggpht.com match RuleSet(Global) using Proxy[Unicom]"
time="2021-01-12T14:49:16+08:00" level=debug msg="[TUN] hijack udp dns: 198.18.0.2:53"
time="2021-01-12T14:49:16+08:00" level=debug msg="[TUN] hijack udp dns: 198.18.0.2:53"
time="2021-01-12T14:49:16+08:00" level=info msg="[TCP] 198.18.0.1:1066 --> r4---sn-a5mlrn7z.googlevideo.com match RuleSet(Global) using Proxy[Unicom]"
time="2021-01-12T14:49:16+08:00" level=debug msg="[Metadata PreHandle] error: fake DNS record 198.18.255.255 missing"
time="2021-01-12T14:49:16+08:00" level=debug msg="[Metadata PreHandle] error: fake DNS record 198.18.255.255 missing"
time="2021-01-12T14:49:16+08:00" level=debug msg="[Metadata PreHandle] error: fake DNS record 198.18.255.255 missing"
time="2021-01-12T14:49:17+08:00" level=debug msg="[TUN] hijack udp dns: 198.18.0.2:53"
time="2021-01-12T14:49:17+08:00" level=debug msg="[TUN] hijack udp dns: 198.18.0.2:53"
time="2021-01-12T14:49:17+08:00" level=debug msg="[TUN] hijack udp dns: 198.18.0.2:53"
time="2021-01-12T14:49:17+08:00" level=info msg="[TCP] 198.18.0.1:1068 --> safebrowsing.googleapis.com match RuleSet(Global) using Proxy[Unicom]"
……
```

### 环境 Environment

* 操作系统 (the OS that the Clash core is running on)
Win10 x64
* 网路环境或拓扑 (network conditions/topology)
通过路由器PPPoE
* iptables，如果适用 (if applicable)
……
* ISP 有没有进行 DNS 污染 (is your ISP performing DNS pollution?)
有
* 其他 (any other information that would be useful)
……

### 重现问题的具体布骤 Steps to Reproduce

1. 使用上述文档作为配置启动clash（高级版）
2. 开启WireShark监控本地网卡流量
3. 浏览网页

**我预期会发生……？**
由于配置文件中的DNS服务器均为DoT DoH，Wireshark不应该截取到DNS请求

**实际上发生了什么？**
Wireshark探测到DNS请求，并显示出了我访问的网址。DNS请求的对象是路由器。（系统DNS服务器）
