### ISSUE TITLE
[Bug] 在运行一段时间后，出现DNS查询无法响应的情况

### ISSUE THREAD

**Issue by hitomi500** [Dreamacro/clash#1179]
------------------------------------------------------------------

### Clash config

<details>
  <summary>config.yaml</summary>

```yaml
port: 7890
socks-port: 7891
redir-port: 7892
allow-lan: true
bind-address: "*"
mode: Rule
log-level: debug
dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:53
  enhanced-mode: redir-host
  nameserver:
    - tls://223.5.5.5:853
    - https://223.5.5.5/dns-query
    - https://223.6.6.6/dns-query
  fallback:
    - tls://1.1.1.1:853
    - tls://8.8.8.8:853
    - tls://8.8.4.4:853
    - https://1.1.1.1/dns-query
    - https://1.0.0.1/dns-query
  fallback-filter:
    geoip: true
    ipcidr:
      - 240.0.0.0/4
……
```

</details>

### Clash log

```
……
```

### 环境 Environment

* 操作系统 (the OS that the Clash core is running on)
Ubuntu 20.04
* 网路环境或拓扑 (network conditions/topology)
位于主路由上，透明代理
* iptables，如果适用 (if applicable)
```iptables
# Generated by iptables-save v1.6.1 on Sun Jan  3 08:52:50 2021
*mangle
:PREROUTING ACCEPT [1199:101149]
:INPUT ACCEPT [1199:101149]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [878:74621]
:POSTROUTING ACCEPT [878:74621]
COMMIT
# Completed on Sun Jan  3 08:52:50 2021
# Generated by iptables-save v1.6.1 on Sun Jan  3 08:52:50 2021
*nat
:PREROUTING ACCEPT [1:36]
:INPUT ACCEPT [1:36]
:OUTPUT ACCEPT [6:431]
:POSTROUTING ACCEPT [2:161]
:Clash - [0:0]
-A PREROUTING -p tcp -j Clash
-A POSTROUTING -o eth0 -j MASQUERADE
-A Clash -d 0.0.0.0/8 -j RETURN
-A Clash -d 10.0.0.0/8 -j RETURN
-A Clash -d 127.0.0.0/8 -j RETURN
-A Clash -d 169.254.0.0/16 -j RETURN
-A Clash -d 172.16.0.0/12 -j RETURN
-A Clash -d 192.168.0.0/16 -j RETURN
-A Clash -d 224.0.0.0/4 -j RETURN
-A Clash -d 240.0.0.0/4 -j RETURN
-A Clash -p tcp -j REDIRECT --to-ports 7892
COMMIT
# Completed on Sun Jan  3 08:52:50 2021
# Generated by iptables-save v1.6.1 on Sun Jan  3 08:52:50 2021
*filter
:INPUT ACCEPT [738:69577]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [503:46873]
-A INPUT -i eth1 -p tcp -m tcp --dport 53 -j ACCEPT
-A INPUT -i eth1 -p udp -m udp --dport 53 -j ACCEPT
-A INPUT -i eth1 -p tcp -m tcp --dport 22 -j ACCEPT
-A INPUT -i eth1 -p udp -m udp --dport 22 -j ACCEPT
-A INPUT -i eth1 -p udp -m udp --dport 67:68 -j ACCEPT
-A FORWARD -i eth1 -o eth0 -j ACCEPT
COMMIT
# Completed on Sun Jan  3 08:52:50 2021
```
* ISP 有没有进行 DNS 污染 (is your ISP performing DNS pollution?)
存在DNS污染
* 其他 (any other information that would be useful)
……

### 说明 Description

在运行一段时间后，出现DNS查询无法响应的情况

```
dig @192.168.2.1 www.youtube.com

; <<>> DiG 9.16.1-Ubuntu <<>> @192.168.2.1 www.youtube.com
; (1 server found)
;; global options: +cmd
;; connection timed out; no servers could be reached
```
### 重现问题的具体布骤 Steps to Reproduce

1. 配置主路由，并配好路由转发
2. 运行一两天
3. dns解析无法响应，导致网页无法打开
4. 重启后正常

**我预期会发生……？**

DNS解析高可用
**实际上发生了什么？**

DNS查询无法响应
### 更多信息 More Information
有可能我这个只是个人需求，可以给出相关的思路，我或许可以给自己的路由器编译出适合自己应用场景的客户端。
