### ISSUE TITLE
[Bug] panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by getizumo** [Dreamacro/clash#1183]
------------------------------------------------------------------

### Clash config

<details>
  <summary>config.yaml</summary>

```yaml
port: 7890
socks-port: 7891
redir-port: 7892
allow-lan: false
mode: Rule
log-level: debug
external-controller: '127.0.0.1:9090'
secret: ''

tun:
  enable: true
  macOS-auto-route: true # auto set global route
  macOS-auto-detect-interface: true # conflict with interface-name
  stack: gvisor
  dns-hijack:
    - 198.18.0.2:53

dns:
  enable: true
  listen: 127.0.0.1:53
  nameserver:
    - 8.8.8.8
    - 1.2.4.8
    - 114.114.114.114
    - 223.5.5.5
    - tls://dns.rubyfish.cn:853
  fallback:
    - tls://1.0.0.1:853
    - tls://dns.google:853
  enhanced-mode: redir-host
  use-hosts: true
  fake-ip-range: 198.18.0.1/16

# 代理节点
proxies:

# 代理组策略
proxy-groups:
  # 代理节点选择
  - name: "PROXY"
    type: select
    proxies:
  # 白名单模式 PROXY，黑名单模式 DIRECT
  - name: "Final"
    type: select
    proxies:
      - "PROXY"
      - "DIRECT"

# 规则
rules:
  - MATCH,PROXY
```

</details>

### Clash log

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0xc pc=0x6289da]

goroutine 89 [running]:
github.com/Dreamacro/clash/proxy/stack/gvisor.(*Gvisor).ReadFrom(0x11c5c420, 0x137be000, 0x5000, 0x8000, 0x8000, 0x8c4920, 0x12e3d980, 0x8c4920, 0x12e3d960, 0x0, ...)

[2021-01-08 10:03:48.678] [info] stderr: 	github.com/Dreamacro/clash/proxy/stack/gvisor/gvisor.go:188 +0xaa
github.com/Dreamacro/clash/proxy/tun.(*TUN).acceptUDP(0x11cc3860)
	github.com/Dreamacro/clash/proxy/tun/adapter.go:123 +0x62
created by github.com/Dreamacro/clash/proxy/tun.(*TUN).process
	github.com/Dreamacro/clash/proxy/tun/adapter.go:230 +0xe3
```

### 环境 Environment

* 操作系统 (the OS that the Clash core is running on)
Windows 10 64 bit

### 重现问题的具体布骤 Steps to Reproduce

在具有管理员权限的命令行中执行 `clash.exe -f config.yml` 即出现此错误。Clash版本为 `Premium 1.3.5 i386` 。
