### ISSUE TITLE
  dns-hijack:     - tcp://*.*.*.*:53这样的格式可以拦截所有的tcp dns么？

### ISSUE THREAD

**Issue by LittleRey** [Dreamacro/clash#1184]
```
tun:
  enable: true
  stack: gvisor # only gvisor
  dns-hijack:
    - tcp://*.*.*.*:53
  macOS-auto-route: true
  macOS-auto-detect-interface: true
```
```
  dns-hijack:
    - tcp://*.*.*.*:53
 ```
使用    - tcp://*.*.*.*:53可以替代所有的Tcp dns么类似 - tcp://1.0.0.1:53
这样可以拦截所有的tcp dns 么
