### ISSUE TITLE
Can't solve ss-server domain on Android

### ISSUE THREAD

**Issue by oocococo** [Dreamacro/clash#119]
As there's no /etc/resolv.conf on Android, when shadowsocks servers' address are domains, clash would have trouble looking up the ip address and connecting to them. After I manually created /etc/resolv.conf, clash worked well.
I wonder if there's a way to solve this problem.

**Comment by xuan880** [comment]
Use directly **go build -o bin/clash-dev** Compile

**Comment by Dreamacro** [comment]
you can use dns config:

```yml
dns:
  enable: true
  nameserver:
    - 114.114.114.114
```
