### ISSUE TITLE
Trouble setting up TProxy or TUN mode

### ISSUE THREAD

**Issue by hummblebee** [Dreamacro/clash#1190]
I'm running the latest premium version on Linux Mint 20 and all is well except when I try to setup Transparent Proxy or TUN mode, I lose internet connectivity!
I have followed the steps in https://lancellc.gitbook.io/clash/start-clash/clash-udp-tproxy-support but I'm not sure what do with **Step 4**! Can anyone elaborate?

Here's my config.yaml:

```
# Port of HTTP(S) proxy server on the local end
port: 7890

# Port of SOCKS5 proxy server on the local end
socks-port: 7891

# Transparent proxy server port for Linux and macOS (Redirect TCP and TProxy UDP)
redir-port: 7892

# Transparent proxy server port for Linux (TProxy TCP and TProxy UDP)
tproxy-port: 7893

allow-lan: false
bind-address: '*'

mode: rule
log-level: info
ipv6: false


# Outbound interface name
interface-name: en0

# DNS server settings
dns:
  enable: true
  listen: 0.0.0.0:1053
  # ipv6: false # when the false, response to AAAA questions will be empty

  default-nameserver:
    - 1.1.1.1
    - 8.8.8.8
  enhanced-mode: redir-host # or fake-ip
  fake-ip-range: 198.18.0.1/16 # Fake IP addresses pool CIDR

  nameserver:
    - 'tls://1.1.1.1:853'
    - 'tls://dns.google:853'
    - https://1.1.1.1/dns-query # DNS over HTTPS

  fallback:
    - tcp://1.1.1.1:53
    - 
  fallback-filter:
    geoip: true
    ipcidr:
      # - 240.0.0.0/4
    # domain:
    #   - '+.google.com'
    #   - '+.facebook.com'
    #   - '+.youtube.com'


proxy-providers:
  us-shadowsocks:
    type: file
    path: ./us-shadowsocks.yaml
    health-check:
      enable: true
      interval: 300
      url: http://www.gstatic.com/generate_204
  us-vmess:
    type: file
    path: ./us-vmess.yaml
    health-check:
      enable: true
      interval: 300
      url: http://www.gstatic.com/generate_204
  us-trojan:
    type: file
    path: ./us-trojan.yaml
    health-check:
      enable: true
      interval: 300
      url: http://www.gstatic.com/generate_204


proxy-groups:
  - name: US-Proxy
    type: load-balance
    use:
      - us-vmess
      - us-shadowsocks
      - us-trojan
    url: 'http://www.gstatic.com/generate_204'
    interval: 3600
    # lazy: true
    # disable-udp: true
    strategy: consistent-hashing # or round-robin    # for load-balance type
    # tolerance: 50    # for url-test type

  - name: PROXY
    type: select
    url: 'http://www.gstatic.com/generate_204'
    interval: 3600
    proxies:
      - US-Proxy
      - DIRECT


rule-providers:
  social-networks:
    behavior: "domain" # domain, ipcidr or classical (premium core only)
    type: file
    path: ./rules-social-networks.yaml
  software-dev:
    behavior: "domain"
    type: file
    path: ./rules-software-dev.yaml
  blogs:
    behavior: "domain"
    type: file
    path: ./rules-blogs.yaml
  work:
    behavior: "domain"
    type: file
    path: ./rules-work.yaml
  play:
    behavior: "domain"
    type: file
    path: ./rules-play.yaml
  others:
    behavior: "domain"
    type: file
    path: ./rules-others.yaml


rules:
  - PROCESS-NAME, java, PROXY
  - PROCESS-NAME, studio.sh, PROXY
  - PROCESS-NAME, idea.sh, PROXY
  - PROCESS-NAME, Telegram, PROXY

  - GEOIP,IR,DIRECT

  # optional param "no-resolve" for IP rules (GEOIP, IP-CIDR, IP-CIDR6)
  - SRC-IP-CIDR,192.168.1.0/24,DIRECT,no-resolve
  - IP-CIDR,127.0.0.0/8,DIRECT,no-resolve
  # - DST-PORT,80,DIRECT
  # - SRC-PORT,7777,DIRECT

  # Premium feature only
  - RULE-SET,social-networks,PROXY
  - RULE-SET,software-dev,PROXY
  - RULE-SET,blogs,PROXY
  - RULE-SET,work,PROXY
  - RULE-SET,play,PROXY
  - RULE-SET,others,PROXY

  - MATCH,DIRECT
```

**Comment by Dreamacro** [comment]
与 surge 的增强模式类似，比如我刚刚搜到的 https://www.maemo.cc/2019/12/29/accelerate-nintendo-switch-with-mac-surge.html

**Comment by hummblebee** [comment]
Thanks for the URL, but I don't understand Chinese and even the google translation wasn't that much helpful. From what I understand it was a guide on setting up Clash on a router but I'm trying to implement TProxy or TUN proxy on the same machine. Any ideas?

**Comment by Dreamacro** [comment]
Do you mean you want to setup a transparent proxy on a single machine?

**Comment by hummblebee** [comment]
Exactly, you got it right. I'm running Linux Mint 20 on my machine that's connected to a DSL Modem and I'd like to proxy some websites based on rules.

I tried those tools, the first one installed with following message:

```
Install successfully

Home directory at /srv/clash

All dns traffic will be redirected to 1.0.0.1:53
Please use clash core's 'tun.dns-hijack' to handle it
```
And then I copied my config files to `/srv/clash` with the following modifications:
```
tun:
  enable: true
  stack: system # or gvisor
  # macOS-auto-route: true
  # macOS-auto-detect-interface: true
  dns-hijack:
    - 1.0.0.1:53
    - tcp://1.1.1.1:53

experimental:
  interface-name: en0 # your interface-name, only for TUN mode 1
```

Started clash, internet connectivity was OK but proxy was not working!

The second tool I believe is intended for deploying clash with a GUI for setting up rules and etc.  I have no trouble with those steps, I have created my rules and config files and clash is running okay in SOCKS or HTTP proxy but not in TProxy or TUN.
