### ISSUE TITLE
[Bug]直接对 ip 地址发起请求时，clash 会去连接解析到此 ip 的域名，有可能会出现问题

### ISSUE THREAD

**Issue by Hohalu** [Dreamacro/clash#1200]
------------------------------------------------------------------

### Clash config

<details>
  <summary>config.yaml</summary>

```yaml
……
```

</details>

### Clash log

```
……
```

### 环境 Environment

* 操作系统 (the OS that the Clash core is running on)
……
* 网路环境或拓扑 (network conditions/topology)
……
* iptables，如果适用 (if applicable)
……
* ISP 有没有进行 DNS 污染 (is your ISP performing DNS pollution?)
……
* 其他 (any other information that would be useful)
……

### 说明 Description

在路由器上使用 clash 做透明代理 DNS 为 redir-host 模式。将域名解析到特定 ip 后对此域名发起一次连接，之后直接连接此 ip 地址，例如使用 ip 进行 SSH 连接，这时在 clash 的连接里看到 clash 并未直接连接此 ip，而是去连接之前的域名。而如果这时此域名被解析到了其他 ip，那么直接对之前 ip 发起的连接就会因此而失败。

### 重现问题的具体布骤 Steps to Reproduce

1. 将域名解析到一个 ip 并连接一次此域名
2. 直接连接此 ip

**我预期会发生……？**

clash 对此 ip 进行连接

**实际上发生了什么？**

clash 连接的是解析到此 ip 的域名，但如果此时域名被解析到了另一个 ip，连接就会失败

**Comment by akw5454521** [comment]
RDNS？没听说Clash还有这功能

**Comment by Dreamacro** [comment]
可以使用 fakeip

**Comment by niphor** [comment]
@Dreamacro 请问redir–host 模式这个问题有解决方案么？
主要是
1. 在主路由上面用fake–ip，影响比较大，难以顾全。
2. 如果proxy里server写的ip，ws里header写了域名，就必须保证域名dns的a记录与server的ip一致，否则就会连到其它上IP上。

另外本身也部署了mosdns等用于专门处理dns

**Comment by Dreamacro** [comment]
redir-host 已经删除。

> 在主路由上面用 fake–ip，影响比较大，难以顾全。

我这里网关使用 fakeip 并包含这么一些设备：iOS 手机、iPadOS 平板、macOS 电脑、两台 Linux VM、Xbox 游戏机、安卓电视盒子。没有在使用中发现 fakeip 的问题。

2 没看懂

**Comment by niphor** [comment]
@Dreamacro 感谢回复


1.我这是因为Linux VM 里跑的比较杂，像是smartdns，mosdns一些DNS相关的工具，也有DDNS这一类的跑这
之前fake-ip用了一段时间，就又用回去了。。。

2.的话 有2个场景
第一个：
假设 `xyz.cn` A记录是 `1.2.3.4`

测试环境是：
Clash Premium 2023.01.29
OpenClash v0.45.87-beta (Redir-Host TUN混合)

[参考配置](https://github.com/Hackl0us/SS-Rule-Snippet/blob/main/LAZY_RULES/Clash_Premium.yaml)，运行配置如下：
```
dns:
  ...
  enable: true
  enhanced-mode: fake-ip
  fake-ip-filter:
     ...
     - "xyz.cn"
     - "+.*" //OpenClash 增加的
  nameserver:
    - 192.168.0.110:888 // 本地Mosdns
  fallback-filter:
    geoip: false
    ipcidr:
       ...
    domain:
       ....  //google相关
  fallback:
    - 192.168.0.110:888 // 本地Mosdns
tun:
  enable: true
  stack: system
  auto-route: false
  auto-detect-interface: false
  dns-hijack:
  - tcp://any:53
proxies:
  - name: DL1
    type: vmess
    server: 1.2.3.4
    network: ws
    ws-opts:
      headers:
        Host: xyz.cn

rules:
  - IP-CIDR,1.2.3.4/32,DIRECT
  - DOMAIN-SUFFIX,xyz.cn,DIRECT
  ...
```

此时是在路由器上运行的透明代理，使用过了DL1代理（只需要使用过）
在局域网中，电脑A访问了一下：https://xyz.cn

此时 如果 xyz.cn的A记录变化了，比如开了Cloudflare的防护，A记录变成了 1.1.1.1
只要在局域网中，电脑A去Ping xyz.cn 确认 A记录变成了1.1.1.1
去访问 https:// **1.2.3.4** 时，会出现 CF的"Direct IP access not allowed"或者其它

原因是访问`https://1.2.3.4` 在Clash连接列表里出现的是访问`xyz.cn:443`,类似于把 `1.2.3.4`“解析”到了CF上去了...

第二个是出现 代理套娃的时候
xyz.cn 的A记录是 1.2.3.4
配置如下
```
proxies:
  - name: DL1
    type: vmess
    server: 1.2.3.4
    network: ws
    ws-opts:
      headers:
        Host: xyz.cn  //虽然IP不同，但是用的相同的域名
  - name: DL2
    type: vmess
    server: 4.3.2.1
    network: ws
    ws-opts:
      headers:
        Host: xyz.cn  //虽然IP不同，但是用的相同的域名
```
路由跑着透明代理，用的DL1
笔记本B，由于经常外出，开的DL2
当笔记本B连入局域网时，本意是使用`4.3.2.1`的服务器，但实际xyz.cn在路由上经过DNS查询后直接是连接到的`1.2.3.4`上
