### ISSUE TITLE
[BUG] 发生异常崩溃  panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by Skyxim** [Dreamacro/clash#1207]
------------------------------------------------------------------

### Clash config

<details>
  <summary>config.yaml</summary>

```yaml
mixed-port: 10808
redir-port: 7892
port: 7890
socks-port: 7891
mode: rule
log-level: silent
external-controller: 0.0.0.0:9090
secret: "123456"
allow-lan: true
bind-address: '*'
hosts:
##Custom HOSTS##
#  experimental hosts, support wildcard (e.g. *.clash.dev Even *.foo.*.example.com)
#  static domain has a higher priority than wildcard domain (foo.example.com > *.example.com)
#  NOTE: hosts don't work with `fake-ip`
#  '*.clash.dev': 127.0.0.1
#  'alpha.clash.dev': '::1'
  # 'raw.githubusercontent.com': 151.101.192.133
##Custom HOSTS END##
dns:
  enable: true
  enhanced-mode: redir-host
  #listen: ':53'
  listen: 127.0.0.1:6666
  # fake-ip-filter:
  #   - 'dns.msftncsi.com'
  #   - 'www.msftncsi.com'
  #   - 'www.msftconnecttest.com' 
##Custom DNS##
  nameserver:
  # - 192.168.1.1
  - tls://223.5.5.5:853
  - tls://223.6.6.6:853
  fallback:
  - tls://8.8.8.8:853
  - tls://8.8.4.4:853
  # - https://208.67.222.222:443
  # - tls://1.1.1.1:853
  fallback-filter:
    geoip: true
    ipcidr:
      - 0.0.0.0/8
      - 10.0.0.0/8
      - 100.64.0.0/10
      - 127.0.0.0/8
      - 169.254.0.0/16
      - 172.16.0.0/12
      - 192.0.0.0/24
      - 192.0.2.0/24
      - 192.88.99.0/24
      - 192.168.0.0/16
      - 198.18.0.0/15
      - 198.51.100.0/24
      - 203.0.113.0/24
      - 224.0.0.0/4
      - 240.0.0.0/4
      - 255.255.255.255/32
#interface-name: WLAN
tun:
  enable: true
  stack: gvisor # only gvisor
  dns-hijack:
    - 8.8.8.8:53
  #   - 198.18.0.2:53 # when `fake-ip-range` is 198.18.0.1/16, should hijack 198.18.0.2:53
  # macOS-auto-route: true # mac or windows
  # # mac or windows
  # macOS-auto-detect-interface: true

proxy-providers:
  HKSR:
    type: http #type of the provider, it can be a HTTP or a File
    path: ./provider/HKSR.yaml #where is the file, ./ relative to clash home
    url: xxx
    interval: 80000 #auto-update interval,only available when type is HTTP
    health-check: #health check option start at here
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 600
  HKV2:
    type: http #type of the provider, it can be a HTTP or a File
    path: ./provider/HKV2.yaml #where is the file, ./ relative to clash home
    url: xxx
    interval: 80000 #auto-update interval,only available when type is HTTP
    health-check: #health check option start at here
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 600
  SSPV2:
    type: http
    path: ./provider/SSPV2.yaml
    url: xxx
    interval: 80000
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 600
  SSPSR:
    type: http
    path: ./provider/SSPSR.yaml
    url: xxx
    interval: 80000
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 600
           
proxy-groups:
- name: Proxy
  type: select
  proxies:
  - LoadBalance
  - LoadBalance-V2

  use:
    - SSPSR
    - SSPV2
- name: LoadBalance-V2
  type: load-balance
  use:
    - HKV2
  url: http://www.gstatic.com/generate_204
  interval: 300
- name: LoadBalance
  type: load-balance
  use:
    - HKV2
    - HKSR
  url: http://www.gstatic.com/generate_204
  interval: 300
- name: Others
  type: select
  proxies:
  - DIRECT
  use:
  - SSPV2
  - SSPSR
- name: Apple
  type: select
  proxies:
  - DIRECT
  - Proxy
- name: Microsoft
  type: select
  proxies:
  - DIRECT
  - Proxy
- name: Steam
  type: select
  proxies:
  - DIRECT
  - Proxy
- name: AsianTV
  type: select
  use: 
    - SSPSR
    - SSPV2
  proxies:
  - DIRECT
  - Proxy
- name: GlobalTV
  type: select
  proxies:
  - DIRECT
  - Proxy
  use:
  - SSPSR
  - SSPV2
- name: Speedtest
  type: select
  proxies:
  - Proxy
  - DIRECT

rule-providers:
  Unbreak:
    type: http
    behavior: classical
    path: ./rule_provider/Unbreak.yaml
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/UnBan.yaml
    interval: 86400
  Reject:
    type: http
    behavior: classical
    path: ./rule_provider/Reject.yaml
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/BanEasyList.yaml
    interval: 86400 
  Proxylist:
    type: http
    behavior: classical
    path: ./rule_provider/Proxy.yaml
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/ProxyLite.yaml
    interval: 86400
  Developer:
    type: http
    behavior: classical
    path: ./rule_provider/Developer.yaml
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/Developer.yaml
    interval: 86400
  BilibiliHMT:
    type: http
    behavior: classical
    path: ./rule_provider/BilibiliHMT.yaml
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/BilibiliHMT.yaml
    interval: 86400
  China:
    type: http
    behavior: classical
    path: ./rule_provider/China.yaml
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/ChinaDomain.yaml
    interval: 86400 
  ChinaIP:
    type: http
    behavior: ipcidr
    path: ./rule_provider/ChinaIP.yaml
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/ChinaCompanyIp.yaml
    interval: 86400 
  LocalAreaNetwork:
    type: http
    behavior: classical
    path: ./rule_provider/LocalAreaNetwork.yaml
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/LocalAreaNetwork.yaml
    interval: 86400 
  Apple:
    type: http
    behavior: classical
    path: ./rule_provider/Apple.yaml
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/Apple.yaml
    interval: 86400
  Microsoft:
    type: http
    behavior: classical
    path: ./rule_provider/Microsoft.yaml
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/Microsoft.yaml
    interval: 86400
  SteamCN:
    type: http
    behavior: classical
    path: ./rule_provider/Steam.yaml
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/SteamCN.yaml
    interval: 86400
rules:
##Custom Rules Start

# - DOMAIN-KEYWORD,tonymacx86, JMS-US
# - DOMAIN-SUFFIX,gmail.com,JMS-US
- DOMAIN-KEYWORD,onenote,Proxy
- DOMAIN-SUFFIX,login.microsoft.com,Proxy
- DOMAIN-SUFFIX,login.live.com,Proxy
- DOMAIN-SUFFIX,outlook.office365.com,Proxy
- DOMAIN-SUFFIX,d.docs.live.net,Proxy
- DOMAIN-SUFFIX,roaming.officeapps.live.com,Proxy
- DOMAIN-SUFFIX,skyxim.com,DIRECT
# - DOMAIN-SUFFIX,gmail.com,Proxy
- DOMAIN-SUFFIX,tonymacx86.com,Others
 
##Custom Rules End

##Custom Rules Set Start
- RULE-SET,LocalAreaNetwork,DIRECT
- RULE-SET,Unbreak,DIRECT
- RULE-SET,Reject,REJECT
- RULE-SET,Developer,Proxy
- RULE-SET,BilibiliHMT,AsianTV
- RULE-SET,Proxylist,Proxy
- RULE-SET,Microsoft,Microsoft
- RULE-SET,Apple,Apple
- RULE-SET,China,DIRECT
- RULE-SET,ChinaIP,DIRECT
- RULE-SET,SteamCN,Steam
# optional param "no-resolve" for IP rules (GEOIP, IP-CIDR, IP-CIDR6)
- IP-CIDR,127.0.0.0/8,DIRECT
- GEOIP,CN,DIRECT
##Custom Rules Set End

- MATCH,Proxy

```

</details>

### Clash log

```
Jan 30 11:40:47 debian bypass-proxy[16110]: time="2021-01-30T11:40:47+08:00" level=info msg="DNS server listeni>
Jan 30 11:46:36 debian bypass-proxy[16110]: panic: runtime error: invalid memory address or nil pointer derefer>
Jan 30 11:46:36 debian bypass-proxy[16110]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0xa64>
Jan 30 11:46:36 debian bypass-proxy[16110]: goroutine 424 [running]:
Jan 30 11:46:36 debian bypass-proxy[16110]: github.com/Dreamacro/clash/adapters/inbound.parseConnAddr(0xd1d200,>
Jan 30 11:46:36 debian bypass-proxy[16110]:         github.com/Dreamacro/clash/adapters/inbound/tun.go:70 +0x147
Jan 30 11:46:36 debian bypass-proxy[16110]: github.com/Dreamacro/clash/adapters/inbound.NewTUNSocket(...)
Jan 30 11:46:36 debian bypass-proxy[16110]:         github.com/Dreamacro/clash/adapters/inbound/tun.go:23
Jan 30 11:46:36 debian bypass-proxy[16110]: github.com/Dreamacro/clash/proxy/tun.(*TUN).acceptTCP(0xc0000c8000)
Jan 30 11:46:36 debian bypass-proxy[16110]:         github.com/Dreamacro/clash/proxy/tun/adapter.go:115 +0x196
Jan 30 11:46:36 debian bypass-proxy[16110]: created by github.com/Dreamacro/clash/proxy/tun.(*TUN).process
Jan 30 11:46:36 debian bypass-proxy[16110]:         github.com/Dreamacro/clash/proxy/tun/adapter.go:229 +0xec
Jan 30 11:46:36 debian systemd[1]: clash.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Jan 30 11:46:36 debian systemd[1]: clash.service: Failed with result 'exit-code'.
Jan 30 11:46:36 debian systemd[1]: clash.service: Consumed 2.581s CPU time.

```

### 环境 Environment

* 操作系统 (the OS that the Clash core is running on)
Debian bullseye
kernel verion;5.10.0-2-amd64
* 网路环境或拓扑 (network conditions/topology)
……
* iptables，如果适用 (if applicable)
……
* ISP 有没有进行 DNS 污染 (is your ISP performing DNS pollution?)
……
* 其他 (any other information that would be useful)
……

### 重现问题的具体布骤 Steps to Reproduce

**我预期会发生……？**

稳定运行
**实际上发生了什么？**

发生异常崩溃
