### ISSUE TITLE
[Feature]请求GLOBAL中默认顺序可调整

### ISSUE THREAD

**Issue by xyxu1024** [Dreamacro/clash#1213]
感谢你向 Clash Core 提交 Feature Request！
在提交之前，请确认：

- [yes] 我已经在 [Issue Tracker](……/) 中找过我要提出的请求

请注意，如果你并没有遵照这个 issue template 填写内容，我们将直接关闭这个 issue。

我都确认过了，我要继续提交。

------------------------------------------------------------------

请附上任何可以帮助我们解决这个问题的信息，如果我们收到的信息不足，我们将对这个 issue 加上 *Needs more information* 标记并在收到更多资讯之前关闭 issue。

### Clash core config

```
mixed-port: 7890

allow-lan: true

external-controller: '0.0.0.0:9090'

external-ui: 'webui'

mode: global

proxies:
  - name: "SS"
  - name: "VMESS"

proxy-groups:
- name: "PROXY"
  type: select
  proxies:
    - "VMESS"
    - "SS"
```

### Clash log

```
……
```

### 环境 Environment

* Clash Core 的操作系统 (the OS that the Clash core is running on)
……
* 使用者的操作系统 (the OS running on the client)
……
* 网路环境或拓扑 (network conditions/topology)
……
* iptables，如果适用 (if applicable)
……
* ISP 有没有进行 DNS 污染 (is your ISP performing DNS pollution?)
……
* 其他
……

### 说明 Description

默认在GLOBAL模式下，首选的是DIRECT：
curl http://127.0.0.1:9090/proxies/GLOBAL/
{"all":["DIRECT","REJECT","SS","VMESS","PROXY"],"history":[],"name":"GLOBAL","now":"DIRECT","type":"Selector"}

每次启动都需要PUT使得GLOBAL选中PROXY：
curl -X PUT -H "Content-Type: application/json" -d '{"name": "PROXY"}' http://127.0.0.1:9090/proxies/GLOBAL/

我想要实现在config.yaml中可以调整Select顺序，比如：
proxy-groups:
- name: "GLOBAL"
  type: select
  proxies:
    - "PROXY"
    - "DIRECT"
    - “REJECT”
