### ISSUE TITLE
[Feature]建议自动更新/自定义Country.mmdb文件

### ISSUE THREAD

**Issue by luwah** [Dreamacro/clash#1219]
感谢你向 Clash Core 提交 Feature Request！
在提交之前，请确认：

- [ ] 我已经在 [Issue Tracker](……/) 中找过我要提出的请求

请注意，如果你并没有遵照这个 issue template 填写内容，我们将直接关闭这个 issue。

我都确认过了，我要继续提交。

------------------------------------------------------------------

请附上任何可以帮助我们解决这个问题的信息，如果我们收到的信息不足，我们将对这个 issue 加上 *Needs more information* 标记并在收到更多资讯之前关闭 issue。

### Clash core config

```
……
```

### Clash log

```
……
```

### 环境 Environment

* Clash Core 的操作系统 (the OS that the Clash core is running on)
……
* 使用者的操作系统 (the OS running on the client)
……
* 网路环境或拓扑 (network conditions/topology)
……
* iptables，如果适用 (if applicable)
……
* ISP 有没有进行 DNS 污染 (is your ISP performing DNS pollution?)
……
* 其他
……

### 说明 Description

建议为Country.mmdb文件提供自动更新的功能，目前的更新方式是手动删除改文件，待下次启动是重新下载；或者自行下载好改文件然后放在指定目录下启动；个人认为这个文件可以像providers一样的方式进行更新。

另外建议提供自定义Country.mmdb文件来源，这样由于某些原因在初始化启动时难以下载到完整Country.mmdb的可能性会降低？
### 可能的解决方案 Possible Solution

可以放在rule-providers或者单列一项：
```
rule-providers:
  Country.mmdb
    type: http # file = mamually update
    url: "url"
    interval: 3600 # 0 = disabled auto-update
    path: ./Country.mmdb
```
