### ISSUE TITLE
> Rule Set is easy to read and edit for end users, so I think it is better to implement a `rule-provider` to support both ruleset and rule script, something like:

### ISSUE THREAD

**Issue by xyxu1024** [Dreamacro/clash#1237]
> Rule Set is easy to read and edit for end users, so I think it is better to implement a `rule-provider` to support both ruleset and rule script, something like:
> 
> ```
> rule-provider:
>   google:
>     type: set
>     path: google.yaml
>     url: https://example.com/google.yaml
>     interval: 3600
>     use: proxy-group-us
>   netflix:
>     type: set
>     path: netflix.yaml
>     url: https://example.com/netflix.yaml
>     interval: 3600
>     use: proxy-group-media
>   custom:
>     type: script
>     path: custom.script
>     url: https://example.com/custom.script
>     interval: 3600
>     use: proxy-group-other
> ```

I think this style of config is inflexible. In one hand, users can’t switch rule set’s proxy group easily. In the other hand, I think separating rules and script is not easy of maintaining, users will jump in different files to add,  modify or delete rules.

In my opinion:

Here’s an example of config.yaml:
```
proxy-provider:
 hk:
  type: http
  path: ./hk.yaml
  url: http://remote.lancelinked.icu/files/hk.yaml
  interval: 3600
  health-check:
   enable: true
   url: http://www.gstatic.com/generate_204
   interval: 300
 us:
  type: file
  path: /home/lance/.clash/provider/us.yaml
  health-check:
   enable: true
   url: http://www.gstatic.com/generate_204
   interval: 300

Proxy Group:
  - name: Proxy
    type: select
    proxies:
      - hk
      - us

rule-provider:
 googleset:
    type: http #or file
    path: ./googleset.yaml
    url: https://example.com/google.yaml
    interval: 3600
 
Rule:
 - SET-MATCH, googleset, Proxy

```
Here is an example of rule set file:
```
rules:

  - DOMAIN-SUFFIX,ampproject.org
  - DOMAIN-SUFFIX,appspot.com
  - DOMAIN-SUFFIX,blogger.com
  - DOMAIN-SUFFIX,getoutline.org

dnsmap:

  - HOST, abc.com, 1.2.3.4
  - DNS-SERVER, def.com, 8.8.8.8 #or system

rewrite:
  - URL-REWRITE, ^http://www\.google\.cn http://www.google.com, header # 302 or REJECT
  - HEADER-REWRITE, ^http://example.com,header-replace=User-Agent, Unknown

script:

  - http-response, ^http://www.example.com/test, script-path=test.js, max-size=16384, debug=true
```

_Originally posted by @lincolnguang in https://github.com/Dreamacro/clash/issues/272#issuecomment-586992806_
