### ISSUE TITLE
[Feature] 绑定多个端口号，并且可选的将某个端口号指定使用某个 proxy-group

### ISSUE THREAD

**Issue by hronro** [Dreamacro/clash#1242]
感谢你向 Clash Core 提交 Feature Request！
在提交之前，请确认：

- [x ] 我已经在 [Issue Tracker](……/) 中找过我要提出的请求

请注意，如果你并没有遵照这个 issue template 填写内容，我们将直接关闭这个 issue。

我都确认过了，我要继续提交。

------------------------------------------------------------------

### 说明 Description

希望可以增加绑定多个端口号，并且可选的将某个端口号指定使用某个 proxy-group。

我目前的使用场景是使用 [mosdns](https://github.com/IrineSistiana/mosdns) 来做 DNS 解析 （因为 Clash 内置的 DNS 功能比较简单满足不了我的需求），并且需要在查询 Netflix 的域名和其他被墙的域名的时候使用不同的代理来查询。如果使用 Clash 来作为代理的话，似乎做不到由连接到 Clash 的 client 来指定使用某一个特定的 proxy group。所以我想能不能让 Clash 支持绑定不同的端口号，并且在绑定端口号的时候可以指定这个端口号全部走某一个 proxy group，这样连接到 Clash 的 client 只要按需去连接不同的 port 就可以使用 clash 中某一特定的 proxy group。

### 可能的解决方案 Possible Solution

希望 config.yml 中支持类似的写法：

```yaml
socks-port: # socks-port 支持数组以同时绑定多个端口
  - 7891 # 如果是数字则保持和以前一样的行为
  - port: 7892 # 如果是对象则可以指定这个端口全部走某一个 proxy-group
    proxy-group: DNS
  - port: 7893
    proxy-group: Netflix

proxy-groups:
  - name: Proxy
    type: select
    proxies:
      - p1
      - p2
  - name: DNS
    type: select
    proxies:
      - p1
      - p2
  - name: Netflix
    type: select
    proxies:
      - p1
      - p2
```
