### ISSUE TITLE
Improvement about DNS config(TLS and TCP dns)

### ISSUE THREAD

**Issue by comzyh** [Dreamacro/clash#126]
DNS part of clash config is confusing, I'm planning to submit a PR to fix  two problems.

### When using TLS DNS server, the `port` field cannot be omitted

For example, If I'm using following configure
```
dns:
  enable: true # set true to enable dns (default is false)
  ipv6: false # default is false
  listen: 0.0.0.0:53
  # enhanced-mode: redir-host
  nameserver:
    - tls://1.1.1.1
```

Read the code
https://github.com/Dreamacro/clash/blob/e7997a035bfcbc943c0b71de2b0367a8183e8676/config/config.go#L373-L382
When using `tls://1.1.1.1:853`, SplitHostPortwill generate an error  `address tls://1.1.1.1:853: too many colons in address`

But When using `tls://1.1.1.1`, 
The `hostname` equals `tls` and the port equals `//1.1.1.1` without error generated
Red the code
https://github.com/Dreamacro/clash/blob/e7997a035bfcbc943c0b71de2b0367a8183e8676/config/config.go#L390-L396
Then, **a nameserver config with `Host` equal "tls" is created without any error log**

So, the code to set a default `853` port  is useless
https://github.com/Dreamacro/clash/blob/e7997a035bfcbc943c0b71de2b0367a8183e8676/config/config.go#L407

### Clash doesn't support TCP DNS server

For now,  Clash doesn't support UDP. So if I want to use DNS servers via proxy, I must choose TCP (or tcp-tls) server. 

I tried config like `tcp://1.1.1.1`, It didn't work and **didn't genrate any error log too**. The same reason as above
