### ISSUE TITLE
[Bug] Proxy Group 没有独立的 url-test 测试结果，导致代理选择失效

### ISSUE THREAD

**Issue by david9991** [Dreamacro/clash#1267]
Clash 的 Proxy Group 没有维护自己的 url-test 的测试结果，而是将其 url-test 的测试结果更新到全局的 Proxy 中。当多个 Proxy Group 使用不同的 URL 对同一个 Proxy 进行测速时，结果将互相覆盖，导致 Proxy 选择错误。
如：
```
  - name: "home-net"
    type: url-test
    proxies:
      - proxy1
      - proxy2
    url: "http://192.168.72.1"
    interval: 10
  - name: "office-net"
    type: url-test
    proxies:
      - proxy1
      - proxy2
    url: "http://192.168.3.1"
    interval: 10
```
假设 proxy1 只能连上 192.168.72.1，而 proxy2 只能连上 192.168.3.1.
当 home-net 使用 192.168.72.1 进行测速时，proxy1 是 100ms，而 proxy2 应该是 timeout，
而当 office-net 使用 192.168.3.1 进行测速时，proxy1 应该是 timeout，而 proxy2 应该是 200ms。
但由于 Proxy Group 并不维护自己的测速结果，而是将结果更新到全局 Proxy 记录中，因此导致全局的测速结果为：proxy1 = 100ms, proxy2 = 200ms。
对于这两个不同的 Proxy Group 来说，测速结果就都是：proxy1 = 100ms, proxy2 = 200ms 了，导致 home-net, office-net 都会选择 proxy1 做为代理。（其实 office-net 本应该选择 proxy2）。
以上问题，同样发生于使用手动 Speed Test 更新 Proxy 测速，同样会影响 Proxy Group 的选择策略。
由此，Proxy Group 应该拥有自己的测速结果，而不是使用全局 Proxy 的测速结果。

**Comment by david9991** [comment]
此问题也受到 DIRECT 内建代理的影响

```
- name: "home-net"
    type: url-test
    proxies:
      - DIRECT
      - proxy1
    url: "http://192.168.72.1"
    interval: 10
  - name: "office-net"
    type: url-test
    proxies:
      - DIRECT
      - proxy2
    url: "http://192.168.3.1"
    interval: 10
```

由于 DIRECT 内建代理永远不会 timeout，因此如果在 Proxy Group 中使用了 DIRECT 代理，那么问题将更加复杂。如果 proxy1 或 proxy2 有任何一个 timeout ，那么 Proxy Group 将自动选择 DIRECT，哪怕 DIRECT 对于 url 测速地址根本不可达。
