### ISSUE TITLE
[Feature] rule-providers 支持 payload type

### ISSUE THREAD

**Issue by ihotte** [Dreamacro/clash#1273]
由于机场提供的配置文件差异较大，不同配置代理行为不一致，所以想在 OpenWrt 上重写配置文件，以统一所有客户端的代理规则，代替机场的原始配置文件。

如下所示可能会有一个自定义的规则集，在移动端或者外网环境下可能不可达，rule-providers 能否提供一个 payload type 直接将规则写入主配置文件.

---
```
rule-providers:
  custom:
    type: http
    behavior: classical
    url: 'http://192.168.5.1:7899/ui/rules/custom.yaml'
    path: /var/clash/rules/custom.yaml
    interval: 3600

  gfw:
    type: http
    behavior: domain
    url: 'https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/gfw.txt'
    path: /etc/clash/rulesets/gfw.yaml
    interval: 86400
```

custom.yaml
```
payload:
  - IP-CIDR6,fd00::/8,no-resolve
  - IP-CIDR6,240e::/18
  - IP-CIDR6,2408:8000::/20
  - IP-CIDR6,2409:8000::/20
  - DOMAIN-SUFFIX,local
  - DOMAIN-SUFFIX,smtp
  - DOMAIN-KEYWORD,aria2
  - DOMAIN-KEYWORD,announce
  - DOMAIN-KEYWORD,torrent
  - DOMAIN-KEYWORD,tracker
```

---
```
rule-providers:
  custom:
    type: payload
    behavior: classical
    url: 'http://192.168.5.2:7899/ui/rules/custom.yaml'
    path: /var/clash/rules/custom.yaml
    interval: 3600
    payload:
      - IP-CIDR6,fd00::/8,no-resolve
      - IP-CIDR6,240e::/18
      - IP-CIDR6,2408:8000::/20
      - IP-CIDR6,2409:8000::/20
      - DOMAIN-SUFFIX,local
      - DOMAIN-SUFFIX,smtp
      - DOMAIN-KEYWORD,aria2
      - DOMAIN-KEYWORD,announce
      - DOMAIN-KEYWORD,torrent
      - DOMAIN-KEYWORD,tracker

  gfw:
    type: http
    behavior: domain
    url: 'https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/gfw.txt'
    path: /etc/clash/rulesets/gfw.yaml
    interval: 86400
```
