### ISSUE TITLE
[Feature]能否增加rule-groups特性

### ISSUE THREAD

**Issue by If-Not-Defined** [Dreamacro/clash#1282]
感谢你向 Clash Core 提交 Feature Request！
在提交之前，请确认：

- [x] 我已经在 [Issue Tracker](……/) 中找过我要提出的请求
### Clash core config

```
proxies:
  - name: "vmess-1"
    type: vmess
    server: server-1
    port: 443
    uuid: uuid
    alterId: 0
    cipher: none
    tls: true
    skip-cert-verify: false
    network: tcp

  - name: "vmess-2"
    type: vmess
    server: server-2
    port: 443
    uuid: uuid
    alterId: 0
    cipher: none
    tls: true
    skip-cert-verify: false
    network: tcp

proxy-groups:
  - name: "指定路线"
    type: select
    proxies:
      - vmess-1
      - vmess-2
      - DIRECT
      - REJECT

rules:
  - name: "代理黑名单"
    sub-rules:
      - RULE-SET,推荐代理域名,指定路线
      - MATCH,DIRECT

  - name: "直连白名单"
    sub-rules:
      - RULE-SET,推荐直连域名,DIRECT
      - MATCH,指定路线

  - name: "不分流"
    sub-rules:
      - MATCH,指定路线

rule-groups:
  - name: "分流规则"
    type: select
    rules:
      - 代理黑名单
      - 直连白名单
      - 不分流

rule-providers:
  推荐代理域名:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/proxy.txt"
    path: ./ruleset/proxy.yaml
    interval: 10080

  推荐直连域名:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/direct.txt"
    path: ./ruleset/direct.yaml
    interval: 10080
```
### 说明 Description

 
如以上配置所示, 能否增加rule-groups特性, 方便在不同场景下使用不同的分流规则.
