### ISSUE TITLE
tun not work  on ubuntu 

### ISSUE THREAD

**Issue by wxf4150** [Dreamacro/clash#1284]
my config
```
tun:
  enable: true
  stack: system # or gvisor
  #macOS-auto-route: true
  #macOS-auto-detect-interface: true
interface-name: enp4s0

port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: 127.0.0.1:9090
secret: ""
ipv6: true
dns:
  enable: true
  listen: 0.0.0.0:1053
  enhanced-mode:  redir-host #fake-ip
# ifake-ip-range: 198.18.0.1/16
# dns-hijack:
#    - 127.0.0.1:1053
  nameserver:
    - 1.2.4.8
    - 119.29.29.29
    - 223.5.5.5
    - 114.114.114.114
    - tls://dns.rubyfish.cn:853
    - https://1.1.1.1
    - https://doh.opendns.com/dns-query
```
system:
ubuntu20.04

clash -v
Clash 2021.02.21 linux amd64 Sun Feb 21 03:57:57 UTC 2021

route -n
```
内核 IP 路由表
目标            网关            子网掩码        标志  跃点   引用  使用 接口
0.0.0.0         10.17.7.254     0.0.0.0         UG    100    0        0 enp4s0
10.17.4.0       0.0.0.0         255.255.252.0   U     100    0        0 enp4s0
169.254.0.0     0.0.0.0         255.255.0.0     U     1000   0        0 utun
198.18.0.0      0.0.0.0         255.255.0.0     U     0      0        0 utun
```

curl https://www.google.com   **#not work!!**

**Comment by techblack** [comment]
simple use:
```
dns:
  enable: true
  listen: 127.0.0.1:1053
  enhanced-mode:  fake-ip
  ifake-ip-range: 198.18.0.1/16
```
然后把 本机dns的上游设置为127.0.0.1:1053
即可
