### ISSUE TITLE
[Bug] DNS UDP 监听地址由 127.0.0.1 变成 0.0.0.0

### ISSUE THREAD

**Issue by laggardkernel** [Dreamacro/clash#1288]
感谢你向 Clash Core 提交 issue！
在提交之前，请确认：

- [ ] 如果你可以自己 debug 并解决的话，提交 PR 吧！
- [x] 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [ ] 我已经使用 dev 分支版本测试过，问题依旧存在
- [x] 我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题
- [x] 这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题

请注意，如果你并没有遵照这个 issue template 填写内容，我们将直接关闭这个 issue。

------------------------------------------------------------------

### Clash config

<details>
  <summary>config.yaml</summary>

```yaml
# DNS [[[
dns:
  enable: true
  ipv6: false
  listen: 127.0.0.1:53
  enhanced-mode: redir-host # or fake-ip
  # only available in fake-ip mod
  # fake-ip-range: 198.18.0.1/16 # Fake IP addresses pool CIDR
  # fake-ip-filter:
  #   - '*.lan'
  default-nameserver:
    - tls://223.5.5.5:853
  nameserver:
    - tls://dns.pub:853
  # Concurrent request with nameserver, fallback used when GEOIP isn't CN
  fallback:
    - 208.67.222.222:443
    - 208.67.220.220:443
    # - 9.9.9.9:9953
    # GFW starts blocking DoT, DoH?
    # - tls://dns.google
  fallback-filter:
    geoip: true
    # ipcidr:
    #   - 240.0.0.0/4
    # domain:
    #   - '+.google.com'
    #   - '+.facebook.com'
    #   - '+.youtube.com'

# ]]]
# TUN [[[
# Ignored by ClashX Pro.
tun:
  enable: true
  # stack implementation: system, gvisor
  # system doesn't work some time on macOS
  stack: gvisor
  macOS-auto-route: true
  macOS-auto-detect-interface: true
  dns-hijack:
    - tcp://8.8.8.8:53

# ]]]
```

</details>

### Clash log

```
INFO[0000] DNS server listening at: 127.0.0.1:53
INFO[0000] Mixed(http+socks5) proxy listening at: :7890
INFO[0000] RESTful API listening at: 127.0.0.1:9090
```

### 环境 Environment

* 操作系统 (the OS that the Clash core is running on)
  * macOS 10.14.6
* 网路环境或拓扑 (network conditions/topology)
……
* iptables，如果适用 (if applicable)
...
* ISP 有没有进行 DNS 污染 (is your ISP performing DNS pollution?)
  * yes, ISP 有在 53 口劫持
* 其他 (any other information that would be useful)
...

```
❯ clash -v
Clash 2021.03.10 darwin amd64 Wed Mar 10 13:30:39 UTC 2021
```

上面是 premium 版本，非 premium 版自 homebrew 安装，存在如下的同样问题。

### 说明 Description
DNS 监听地址设置 `127.0.0.1:53`，此时 `lsof -i :53` 查看的确监听在 localhost。但在系统设置->网络中设置DNS地址为 Clash 的 DNS 服务地址 127.0.0.1 后。`lsof -i :53` 查看兼容地址变为了 0.0.0.0.

```
❯ sudo lsof -i :53
COMMAND   PID USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
clash   20036 root    8u  IPv4 0x75e12377175b6c39      0t0  UDP *:domain
```

我在 AdGuardHome 中发现了同样的问题（二者没有直接关联，分开测试的），是不是你们用了相同的依赖什么的。

另外，我用 dnsmasq 和 mosdns 作了对比，这两个软件没有这种问题。

AdguardTeam/AdGuardHome#2807
