### ISSUE TITLE
[Bug] How to use geosite.dat

### ISSUE THREAD

**Issue by sayomelu** [Dreamacro/clash#1292]
https://github.com/v2fly/domain-list-community

it is much easier to select a bunch of site which conbined by categories, and it is much easier to write than the `rules:` section.

**Comment by cjwddtc** [comment]
this isn't a bug,and this tool is designed as a rule-base tunnel,but you still can use geosite.dat by this project: [https://github.com/Loyalsoldier/clash-rules](url)

**Comment by sayomelu** [comment]
it is hard to use rule providers, i have to import each provider by:

```
proxy:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/proxy.txt"
    path: ./ruleset/proxy.yaml
    interval: 86400
```

geosite.dat only have to download one file, and then set all categories.

and the rule providers part is not open source.
