### ISSUE TITLE
[Bug] 设置 fallback 检测方式时，DIRECT 有时会成功导致发生意外的网络切换

### ISSUE THREAD

**Issue by hurongyang** [Dreamacro/clash#1300]
我的组策略如下
```
proxy-groups:
  - name: Proxy
    type: fallback
    url: 'http://www.google.com/generate_204'
    interval: 60
    proxies:
      - DIRECT
      - vpnAuto

```

这导致我在家里不能翻墙的网络中，DIRECT 测速显示偶尔会成功，导致我线路切换到直连，不知道是为什么，
下面是现象截图
![image](https://user-images.githubusercontent.com/17896811/111295785-be37ce00-8686-11eb-96db-8ea6e2d8788a.png)
