### ISSUE TITLE
群晖 docker 使用 bridge 貌似会发生回环

### ISSUE THREAD

**Issue by wangliangliang2** [Dreamacro/clash#1310]
### Clash config

<details>
  <summary>config.yaml</summary>

```yaml
mixed-port: 7890
redir-port: 7892
allow-lan: true
bind-address: 0.0.0.0
mode: rule
log-level: debug
ipv6: false
# external-controller: 0.0.0.0:9090
dns:
  ipv6: false
  enable: true
  listen: 0.0.0.0:3535
  enhanced-mode: redir-host
  fake-ip-range: 198.18.0.1/16
  use-hosts: true
  default-nameserver:
    - 114.114.114.114
  nameserver:
    - 223.5.5.5
    - https://rubyfish.cn/dns-query
  fallback:
    - tcp://1.1.1.1
    - tls://8.8.8.8:853
  fallback-filter:
    geoip: true
    ipcidr:                      # ips in these subnets will be considered polluted
      - 240.0.0.0/4
    domain:
      - '+.google.com'
      - '+.facebook.com'
      - '+.youtube.com'
      - '+.twitter.com'
      - '+.instagram.com'
      - '+.github.com'
```

</details>

### Clash log

```
docker run  --rm --name=clash -ti -v /volume1/docker/clash/config.yaml:/root/.config/clash/config.yaml -p 3535:3535/udp -p 7890:7890 -p 7892:7892 --dns=8.8.8.8 dreamacro/clash-premium:latest
省略加载配置
INFO[0014] DNS server listening at: 0.0.0.0:3535
INFO[0014] Redir proxy listening at: 0.0.0.0:7892
INFO[0014] Mixed(http+socks5) proxy listening at: 0.0.0.0:7890
INFO[0024] [TCP] 172.17.0.1:33724 --> 172.17.0.2 match RuleSet(lancidr) using DIRECT
INFO[0024] [TCP] 172.17.0.2:45096 --> 172.17.0.2 match RuleSet(lancidr) using DIRECT
```

### 环境 Environment

* 操作系统 (the OS that the Clash core is running on)

		群晖 Linux DiskStation 4.4.59+ #23824 SMP PREEMPT Fri Oct 26 18:34:33 CST 2018 x86_64 GNU/Linux synology_apollolake_918+

* 网路环境或拓扑 (network conditions/topology)

		

* iptables，如果适用 (if applicable)

		#clash_dns 转发
		iptables -t nat -N clash_dns 
		iptables -t nat -A clash_dns -p udp --dport 53 -d 192.168.0.0/16 -j DNAT --to-destination 192.168.1.1:3535
		iptables -t nat -A clash_dns -p tcp --dport 53 -d 192.168.0.0/16 -j DNAT --to-destination 192.168.1.1:3535
		iptables -t nat -A PREROUTING -p tcp --dport 53 -d 192.168.0.0/16 -j clash_dns
		iptables -t nat -A PREROUTING -p udp --dport 53 -d 192.168.0.0/16 -j clash_dns
		iptables -t nat -N clash #創建名爲clash的規則
		#不對本地進行代理 内部流量不转发给 CLASH 直通
		iptables -t nat -A clash -d 0.0.0.0/8 -j RETURN
		iptables -t nat -A clash -d 10.0.0.0/8 -j RETURN
		iptables -t nat -A clash -d 127.0.0.0/8 -j RETURN
		iptables -t nat -A clash -d 169.254.0.0/16 -j RETURN
		iptables -t nat -A clash -d 172.16.0.0/12 -j RETURN
		iptables -t nat -A clash -d 192.168.0.0/16 -j RETURN
		iptables -t nat -A clash -d 224.0.0.0/4 -j RETURN
		iptables -t nat -A clash -d 240.0.0.0/4 -j RETURN
		iptables -t nat -A clash -p tcp !-s 172.16.0.0/12 -j REDIRECT --to-ports 7892
		iptables -t nat -A PREROUTING -p tcp -j clash	

### 说明 Description
遇到的问题是：
INFO[0024] [TCP] 172.17.0.2:xxx --> 172.17.0.2 match RuleSet(lancidr) using DIRECT 一直打印 [随便访问 一个网页，都会发生这个日志。并不是特意无聊自己访问172.17.0.x导致的日志。]
CPU 跑到98% ，猜测应该是回环了。
想问是群晖下不能使用network：bridge 模式吗？如果使用host模式是正常的。
另外如果能用network：bridge  应该怎么弄呢
