### ISSUE TITLE
[Bug]115下载时cfw占用下载带宽，并且下载完毕后cfw仍然占用带宽下载

### ISSUE THREAD

**Issue by jiaminxun** [Dreamacro/clash#1311]
115下载时，CFW会占用同样的带度，比如115下载一个文件，6M的速度，那么CFW会另外占用6M的带宽，此时电脑的总下载速度就是12M，115下载暂停、删除下载任务或下载任务完毕后，CFW仍然占用6M的带宽继续下载，一直不知道下载什么东西，只有重启或关闭CFW客户端网络才会停止下载,另外要是在打开115下载前，把system proxy关闭，再开115下载，就不会出现这种情况。
在CFW那边提交BUG，F大说是核心问题https://github.com/Fndroid/clash_for_windows_pkg/issues/1663

------------------------------------------------------------------

### Clash config

<details>
  <summary>config.yaml</summary>

```yaml
……
```

</details>

### Clash log

```
……
```

### 环境 Environment

* 操作系统 (the OS that the Clash core is running on)
……
* 网路环境或拓扑 (network conditions/topology)
……
* iptables，如果适用 (if applicable)
……
* ISP 有没有进行 DNS 污染 (is your ISP performing DNS pollution?)
……
* 其他 (any other information that would be useful)
……

### 重现问题的具体布骤 Steps to Reproduce

1. [First Step]
2. [Second Step]
3. ……

**我预期会发生……？**

**实际上发生了什么？**

**Comment by xjasonlyu** [comment]
cfw -> system bypass -> *.115.com

**Comment by jiaminxun** [comment]
> cfw -> system bypass -> *.115.com

此方法无效

**Comment by xjasonlyu** [comment]
理论上你绕过系统代理，clash根本就不会接管流量才对。

**Comment by jiaminxun** [comment]
> 理论上你绕过系统代理，clash根本就不会接管流量才对。

这是0.14.6时正常使用115下载的，2个线程，下载速度13M。
![1](https://user-images.githubusercontent.com/57553009/113470005-cd8b8980-9484-11eb-9aad-836503e90a80.jpg)
这是最新的0.15.1，CFW占用了一个线程，下载速度只有6M，
![2](https://user-images.githubusercontent.com/57553009/113470022-f01da280-9484-11eb-889d-98ae529cb03c.jpg)
![3](https://user-images.githubusercontent.com/57553009/113470026-f3189300-9484-11eb-97b4-b91eee70e5c5.jpg)

**Comment by xjasonlyu** [comment]
你IDM代理怎么设置的。。

**Comment by RtYkk** [comment]
请问这个问题修复了吗？我在使用 [Filebrowser Enhanced](https://hub.docker.com/r/80x86/filebrowser) 进行串流的时候遇到了几乎一模一样的问题，已经换用 Qv2ray 进行过对比测试无此问题。使用的已经是最新的 Clash for Windows，Core Version 是 2021.04.08 Premium。

**Comment by Dreamacro** [comment]
@RtYkk 除非给出一个最小能复现的方式，否则根本不清楚问题在哪。我自己本身没出现过这个问题

**Comment by RtYkk** [comment]
@Dreamacro 


------------------------------------------------------------------



### Clash config



<details>
  <summary>config.yaml</summary>


```yaml
mixed-port: 7890
redir-port: 7892
allow-lan: false
mode: global
log-level: debug
external-controller: 127.0.0.1:1834
secret: ''

# System proxy will ignore these domains(or ipnet)
cfw-bypass:
  - localhost
  - 127.*
  - 10.*
  - 172.16.*
  - 172.17.*
  - 172.18.*
  - 172.19.*
  - 172.20.*
  - 172.21.*
  - 172.22.*
  - 172.23.*
  - 172.24.*
  - 172.25.*
  - 172.26.*
  - 172.27.*
  - 172.28.*
  - 172.29.*
  - 172.30.*
  - 172.31.*
  - 192.168.*
  - <local>

# Proxies module latency test settings
cfw-latency-timeout: 3000 # seconds
cfw-latency-url: http://www.gstatic.com/generate_204

# Identify strategy of breaking connections after switching to a new proxy/profile/mode
# Options for proxy: none, chain(proxy group in connection chains), all
# Options for profile: true, false
# Options for mode: true, false
cfw-conn-break-strategy:
  proxy: none
  profile: true
  mode: false

# Run child process after CFW started
# Refer: https://docs.cfw.lbyczf.com/contents/childprocess.html
cfw-child-process: []

# Will be ignored after profile selection
Proxy:
  - name: Shadowsocks
    type: socks5
    server: 127.0.0.1
    port: 1080
Proxy Group:
  - name: Proxy
    type: select
    proxies:
      - Shadowsocks
Rule:
  - 'MATCH,DIRECT'

```

</details>

### Clash log



```
time="2021-05-02T13:31:51+08:00" level=info msg="[TCP] 127.0.0.1:1216 --> 163.*.*.* match Match() using Proxy[TEST]"
time="2021-05-02T13:31:52+08:00" level=info msg="[TCP] 127.0.0.1:1227 --> 163.*.*.* match Match() using Proxy[TEST]"
time="2021-05-02T13:31:52+08:00" level=info msg="[TCP] 127.0.0.1:1229 --> 163.*.*.* match Match() using Proxy[TEST]"
time="2021-05-02T13:31:52+08:00" level=info msg="[TCP] 127.0.0.1:1232 --> 163.*.*.* match Match() using Proxy[TEST]"
time="2021-05-02T13:31:52+08:00" level=info msg="[TCP] 127.0.0.1:1234 --> 163.*.*.* match Match() using Proxy[TEST]"
time="2021-05-02T13:31:57+08:00" level=info msg="[TCP] 127.0.0.1:1246 --> 163.*.*.* match Match() using Proxy[TEST]"
time="2021-05-02T13:31:57+08:00" level=info msg="[TCP] 127.0.0.1:1243 --> 163.*.*.* match Match() using Proxy[TEST]"
time="2021-05-02T13:31:57+08:00" level=info msg="[TCP] 127.0.0.1:1244 --> 163.*.*.* match Match() using Proxy[TEST]"
time="2021-05-02T13:32:04+08:00" level=info msg="[TCP] 127.0.0.1:1264 --> 163.*.*.* match Match() using Proxy[TEST]"
time="2021-05-02T13:34:31+08:00" level=info msg="[TCP] 127.0.0.1:1819 --> 163.*.*.* match Match() using Proxy[TEST]"
time="2021-05-02T13:34:32+08:00" level=info msg="[TCP] 127.0.0.1:1822 --> 163.*.*.* match Match() using Proxy[TEST]"
```

### 环境 Environment

* 操作系统 (the OS that the Clash core is running on)
  Windows 10 2004 企业版
* 网路环境或拓扑 (network conditions/topology)
  ……
* iptables，如果适用 (if applicable)
  ……
* ISP 有没有进行 DNS 污染 (is your ISP performing DNS pollution?)
  与此无关
* 其他 (any other information that would be useful)
  **我使用了 tap**，使用的代理是 Trojan

### 说明 Description



### 重现问题的具体布骤 Steps to Reproduce

1. 我是在我远程的一个 VPS 上搭建了 [Filebrowser Enhanced](https://hub.docker.com/r/80x86/filebrowser) 的服务来尝试进行网络串流
2. 随便点开一个视频，正常加载
3. 关闭视频

**我预期会发生……？**


连接中断，没有上传下载速度

**实际上发生了什么？**


继续占用大量带宽，除非手动 Close Connection 或者关闭 Clash

### 可能的解决方案 Possible Solution





idk

### 更多信息 More Information

首先我可以确定这是 Clash 的问题，一开始我也曾怀疑是 Filebrowser Enhanced 的问题，但是当我换用了 Qv2ray 来进行控制变量发现无法复现。我甚至还怀疑是不是速度显示错了，还装了个 TrafficMonitor 来进行对照，可以看录屏的右下角。然后我就想起了这个 Issue，发现我的情况确实很相似，下面有一段录屏。

https://user-images.githubusercontent.com/45971730/116810878-c38aa280-ab78-11eb-86eb-eed6cc3f984a.mp4

然后这是我在已经点了'×'之后的 Connections 情况，因为有一些个人信息，恕我无法通过录屏呈现。
![Clash_for_Windows_pSftdWLfqW](https://user-images.githubusercontent.com/45971730/116810952-3431bf00-ab79-11eb-9654-d20d1c7fbd0b.png)

Qv2ray 我确认过，在点了'×'之后是没有速度的，我就不重复上传录屏了，如果还需要更详细的信息我都可以提供。
