### ISSUE TITLE
[Bug]url-test同样的测速链接，手动测速和自动测速显示的延迟差距很大

### ISSUE THREAD

**Issue by xqXQzzz1** [Dreamacro/clash#1345]
------------------------------------------------------------------

### Clash config

<details>
  <summary>config.yaml</summary>

```
mixed-port: 7890
allow-lan: false
mode: rule
log-level: info
external-controller: 127.0.0.1:9090
ipv6: true
dns:
  enable: true
  ipv6: true
  listen: 0.0.0.0:53
  enhanced-mode: redir-host
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
  nameserver:
    - 223.5.5.5
    - 119.29.29.29
    - 114.114.114.114
    - https://dns.alidns.com/dns-query
  fallback:
    - 8.8.8.8
    - tls://dns.rubyfish.cn:853
    - https://cloudflare-dns.com/dns-query
  fallback-filter:
    geoip: true
proxies:
   ~
proxy-groups:
  - name: ♻️ 自动选择
    type: url-test
    url: http://www.gstatic.com/generate_204
    interval: 2400
    tolerance: 100
    proxies:
        ~
rule-providers:
   ~
rules:
   ~
```

</details>

### Clash log

```

```

### 环境 Environment

* 操作系统 (the OS that the Clash core is running on)
win10
* 网路环境或拓扑 (network conditions/topology)
……
* iptables，如果适用 (if applicable)
……
* ISP 有没有进行 DNS 污染 (is your ISP performing DNS pollution?)
……
* 其他 (any other information that would be useful)
……

### 重现问题的具体布骤 Steps to Reproduce

1. [First Step]
2. [Second Step]
3. ……

**我预期会发生……？**

自动测速和手动测速延迟相同
**实际上发生了什么？**

自动测速900ms，而手动为120ms
自动测速：
![image](https://user-images.githubusercontent.com/35725489/114258471-37fa7780-99f9-11eb-8e94-b53ed2d6cc2b.png)
手动测速：
![image](https://user-images.githubusercontent.com/35725489/114258489-5ceeea80-99f9-11eb-9b58-bb6fd4b210af.png)

### 更多信息 More Information
使用的是yacd面板手动测速。
