### ISSUE TITLE
[Bug]使用proxy-providers时，benchmark 全fail

### ISSUE THREAD

**Issue by ArsenicX** [Dreamacro/clash#1353]
### 环境 Environment

* 操作系统 (the OS that the Clash core is running on)
windows 10 version 1909
mac os 10.15.7

配置用的是自己编辑的 config ，里面写了 proxy-providers，引用的是机场的订阅链接
在benchmark的时候发现所有节点都是fail，但是我的节点是能正常使用的。
我改了系统时间、换了benchmark url，发现始终都是全 fail

然后我不用自己的config，改成直接使用机场的订阅链接的配置之后，benchmark就有效了，不全是 fail 了
然后我又试着用回自己编辑的 config ，在里面手动添加了两条 proxies 节点，再次benchmark，proxy-providers的依旧还是全 fail，但是手动添加的那两条能正常测延迟了

我不知道是什么原因，但猜测应该是 proxy-providers 的问题吧，希望大佬能解决下

**Comment by Dreamacro** [comment]
clash 配置呢

**Comment by ArsenicX** [comment]
> clash 配置呢

这个是配置

```
port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090

proxies:
  - {"name":"V4-中转9999|广港-新加坡|x2.5|V2ray","type":"vmess","server":"lixxxxxxxxxxxxz","port":51196,"uuid":"XXXXXXXXXXXXXX","alterId":0,"cipher":"auto","udp":true,"network":"ws","ws-path":"/v2ray","ws-headers":{"Host":"lxxxxxxxxxxz"}}


proxy-providers:
  j01.best:
    type: http
    path: ./profiles/j01.best.yaml
    url: https://xxxxxxxxxxxxxxxxxxx
    interval: 18000


proxy-groups: 
  - name: PROXY
    type: select
    proxies:
      - V4-中转9999|广港-新加坡|x2.5|V2ray
    use:
      - j01.best


rules:
 - DOMAIN-SUFFIX,access-sngapm.qcloud.com , REJECT
 - DOMAIN-SUFFIX,store.steampowered.com , DIRECT
 - GEOIP,CN,DIRECT
 - MATCH,PROXY

```
