### ISSUE TITLE
求助！OpenWrt redir能代理，Tproxy无法代理（Tun也无法代理）

### ISSUE THREAD

**Issue by leiusual** [Dreamacro/clash#1358]
------------------------------------------------------------------

### Clash config
<details>
  <summary>config.yaml</summary>

```yaml
tproxy-port: 7890
allow-lan: true
bind-address: '*'
mode: rule
log-level: debug
ipv6: false
external-controller: 0.0.0.0:9090
external-ui: dashboard
tun:
  enable: false
  stack: system
dns:
  enable: true
  listen: 0.0.0.0:7853
  ipv6: false
  enhanced-mode: redir-host
  nameserver:
    - https://dns.alidns.com/dns-query
proxy-providers:
  hk-iplc:
    type: file
    path: ./proxy/hk-iplc.yaml
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 3600
  hk-iepl:
    type: file
    path: ./proxy/hk-iepl.yaml
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 3600
  us-bwh:
    type: file
    path: ./proxy/us-bwh.yaml
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 3600
  us-iepl:
    type: file
    path: ./proxy/us-iepl.yaml
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 3600
proxy-groups:
  - name: HK-iplc
    type: fallback
    use:
      - hk-iplc
    url: http://www.gstatic.com/generate_204
    interval: 300
  - name: HK-iepl
    type: fallback
    use:
      - hk-iepl
    url: http://www.gstatic.com/generate_204
    interval: 300
  - name: HK
    type: select
    proxies:
      - HK-iplc
      - HK-iepl
  - name: US-bwh
    type: fallback
    use:
      - us-bwh
    url: http://www.gstatic.com/generate_204
    interval: 300
  - name: US-iepl
    type: fallback
    use:
      - us-iepl
    url: http://www.gstatic.com/generate_204
    interval: 300
  - name: US
    type: select
    proxies:
      - US-bwh
      - US-iepl
  - name: PROXY
    type: select
    proxies:
      - HK
      - US
      - DIRECT
rule-providers:
  direct:
    type: file
    behavior: classical
    path: ./ruleset/direct.yaml
rules:
  - RULE-SET,direct,DIRECT
  - GEOIP,CN,DIRECT
  - MATCH,PROXY

```

</details>

### Clash log
```
无日志
```

### 环境 Environment

* 操作系统 (the OS that the Clash core is running on)
OpenWrt 
* 网路环境或拓扑 (network conditions/topology)
光猫 - OpenWrt路由器- 电脑
* iptables，如果适用 (if applicable)
```
ip route add local default dev lo table 100
ip rule add fwmark 1 lookup 100

iptables -t mangle -N CLASH
iptables -t mangle -A CLASH -d 0/8 -j RETURN
iptables -t mangle -A CLASH -d 10/8 -j RETURN
iptables -t mangle -A CLASH -d 100.64/10 -j RETURN
iptables -t mangle -A CLASH -d 127/8 -j RETURN
iptables -t mangle -A CLASH -d 169.254/16 -j RETURN
iptables -t mangle -A CLASH -d 172.16/12 -j RETURN
iptables -t mangle -A CLASH -d 192/24 -j RETURN
iptables -t mangle -A CLASH -d 192.0.2/24 -j RETURN
iptables -t mangle -A CLASH -d 192.88.99/24 -j RETURN
iptables -t mangle -A CLASH -d 192.168/16 -j RETURN
iptables -t mangle -A CLASH -d 198.18/15 -j RETURN
iptables -t mangle -A CLASH -d 198.51.100/24 -j RETURN
iptables -t mangle -A CLASH -d 203.0.113/24 -j RETURN
iptables -t mangle -A CLASH -d 224/4 -j RETURN
iptables -t mangle -A CLASH -d 240/4 -j RETURN
iptables -t mangle -A CLASH -d 255.255.255.255/32 -j RETURN

iptables -t mangle -A CLASH -p udp -j TPROXY --tproxy-mark 1 --on-port 7890
iptables -t mangle -A CLASH -p tcp -j TPROXY --tproxy-mark 1 --on-port 7890

# Apply
iptables -t mangle -A PREROUTING -j CLASH
```
* ISP 有没有进行 DNS 污染 (is your ISP performing DNS pollution?)
无
* 其他 (any other information that would be useful)
……

### 重现问题的具体布骤 Steps to Reproduce

1. Docker 容器运行 
docker run -d --restart=always --device=/dev/net/tun --cap-add NET_ADMIN --network host -v clash:/root/.config/clash/ --name clash dreamacro/clash-premium:2021.04.08
2. 配置策略路由
3. 添加Iptables规则
4. 取消dnsmasq (Ignore resolve file)文件解析，配置DNS forwardings ：127.0.0.1#7853

**我预期会发生……？**
电脑能访问

**实际上发生了什么？**
电脑无法访问网络

求助，不知道什么问题。同样的配置方式在Raspbian下都能正常代理（电脑设置网关后），但是在OpenWrt系统下就是不行。

如果改成redir方式只代理tcp就可以（iptables 如下）
```
iptables -t nat -N CLASH
iptables -t nat -A CLASH -d 0/8 -j RETURN
iptables -t nat -A CLASH -d 10/8 -j RETURN
iptables -t nat -A CLASH -d 100.64/10 -j RETURN
iptables -t nat -A CLASH -d 127/8 -j RETURN
iptables -t nat -A CLASH -d 169.254/16 -j RETURN
iptables -t nat -A CLASH -d 172.16/12 -j RETURN
iptables -t nat -A CLASH -d 192/24 -j RETURN
iptables -t nat -A CLASH -d 192.0.2/24 -j RETURN
iptables -t nat -A CLASH -d 192.88.99/24 -j RETURN
iptables -t nat -A CLASH -d 192.168/16 -j RETURN
iptables -t nat -A CLASH -d 198.18/15 -j RETURN
iptables -t nat -A CLASH -d 198.51.100/24 -j RETURN
iptables -t nat -A CLASH -d 203.0.113/24 -j RETURN
iptables -t nat -A CLASH -d 224/4 -j RETURN
iptables -t nat -A CLASH -d 240/4 -j RETURN
iptables -t nat -A CLASH -d 255.255.255.255/32 -j RETURN
iptables -t nat -A CLASH -p tcp -j REDIRECT --to-port 7890

iptables -t nat -A PREROUTING -p tcp -j CLASH
```
