### ISSUE TITLE
[Bug]使用httping方式ping google，fallback有时候延迟返回很大类似于丢包tcp重发那种那感觉，同一个节点使用select选择就没问题

### ISSUE THREAD

**Issue by Skyxim** [Dreamacro/clash#1363]
------------------------------------------------------------------

### Clash config

<details>
  <summary>config.yaml</summary>

```yaml
proxy-groups:
- name: Proxy
  type: select
  proxies:
    - DIRECT
    - PC-VMESS
    - LoadBalance-IEPL
    - LoadBalance-IPCL
    - LoadBalance-HK
    - LoadBalance-SG
    - LoadBalance-US
    - Fallback-HK
    - Fallback-SG
  use:
    - SS
- name: PC-VMESS
  type: select
  use:
    - PC
- name: LoadBalance-IPCL
  type: load-balance
  use:
    - HK-IPLC
  url: http://www.gstatic.com/generate_204
  interval: 180
  lazy: true
- name: LoadBalance-IEPL
  type: load-balance
  use:
    - HK-IEPL
  url: http://www.gstatic.com/generate_204
  interval: 90
  lazy: true
- name: LoadBalance-HK
  type: load-balance
  use:
    - HK
  url: http://www.gstatic.com/generate_204
  interval: 90
  lazy: true
- name: Fallback-HK
  type: fallback
  use:
    - HK-IEPL
    - HK-IPLC
  url: http://www.gstatic.com/generate_204
  interval: 90
  lazy: true
- name: LoadBalance-SG
  type: load-balance
  use:
    - SG
  url: http://www.gstatic.com/generate_204
  interval: 90
  lazy: true
- name: Fallback-SG
  type: fallback
  use:
    - SG
  url: http://www.gstatic.com/generate_204
  interval: 180
  lazy: true
- name: LoadBalance-US
  type: load-balance
  use:
    - US
  url: http://www.gstatic.com/generate_204
  interval: 180
  lazy: true
```

</details>

### Clash log

```
……
```

### 环境 Environment

* 操作系统 (the OS that the Clash core is running on)
OpenWrt 21.02, r15934-112d1052ac
5.10.21-rockchip64
Clash 2021.04.08 linux arm64 with go1.16.3 Thu Apr  8 14:40:38 UTC 2021
* 网路环境或拓扑 (network conditions/topology)
tun模式下运行的透明网关
* iptables，如果适用 (if applicable)
# Generated by iptables-save v1.8.7 on Sun Apr 18 09:02:34 2021
*nat
:PREROUTING ACCEPT [949:73528]
:INPUT ACCEPT [129:8686]
:OUTPUT ACCEPT [351:22583]
:POSTROUTING ACCEPT [1195:85639]
:MINIUPNPD - [0:0]
:MINIUPNPD-POSTROUTING - [0:0]
:openclash - [0:0]
:openclash_output - [0:0]
:postrouting_lan_rule - [0:0]
:postrouting_rule - [0:0]
:postrouting_wan_rule - [0:0]
:prerouting_lan_rule - [0:0]
:prerouting_rule - [0:0]
:prerouting_wan_rule - [0:0]
:zone_lan_postrouting - [0:0]
:zone_lan_prerouting - [0:0]
:zone_wan_postrouting - [0:0]
:zone_wan_prerouting - [0:0]
-A PREROUTING -d 8.8.4.4/32 -p tcp -m tcp --dport 53 -j ACCEPT
-A PREROUTING -d 8.8.8.8/32 -p tcp -m tcp --dport 53 -j ACCEPT
-A PREROUTING -d 8.8.4.4/32 -p tcp -m tcp --dport 53 -j ACCEPT
-A PREROUTING -d 8.8.8.8/32 -p tcp -m tcp --dport 53 -j ACCEPT
-A PREROUTING -p udp -m udp --dport 53 -j REDIRECT --to-ports 53
-A PREROUTING -p tcp -m tcp --dport 53 -j REDIRECT --to-ports 53
-A PREROUTING -m comment --comment "!fw3: Custom prerouting rule chain" -j prerouting_rule
-A PREROUTING -i br-lan -m comment --comment "!fw3" -j zone_lan_prerouting
-A PREROUTING -p tcp -j openclash
-A PREROUTING -p tcp -j openclash
-A OUTPUT -j openclash_output
-A OUTPUT -j openclash_output
-A POSTROUTING -m comment --comment "!fw3: Custom postrouting rule chain" -j postrouting_rule
-A POSTROUTING -o br-lan -m comment --comment "!fw3" -j zone_lan_postrouting
-A MINIUPNPD -p tcp -m tcp --dport 13787 -j DNAT --to-destination 10.0.0.75:1080
-A MINIUPNPD -p udp -m udp --dport 13787 -j DNAT --to-destination 10.0.0.75:3027
-A MINIUPNPD -p udp -m udp --dport 31385 -j DNAT --to-destination 10.0.0.205:31385
-A MINIUPNPD-POSTROUTING -s 10.0.0.75/32 -p tcp -m tcp --sport 1080 -j MASQUERADE --to-ports 13787
-A MINIUPNPD-POSTROUTING -s 10.0.0.75/32 -p udp -m udp --sport 3027 -j MASQUERADE --to-ports 13787
-A MINIUPNPD-POSTROUTING -s 10.0.0.205/32 -p udp -m udp --sport 31385 -j MASQUERADE --to-ports 31385
-A openclash -m set --match-set localnetwork dst -j RETURN
-A openclash -m set --match-set china_ip_route dst -j RETURN
-A openclash -p tcp -j REDIRECT --to-ports 7892
-A openclash_output -p tcp -m tcp --sport 1688 -j RETURN
-A openclash_output -m set --match-set localnetwork dst -j RETURN
-A openclash_output -m set --match-set china_ip_route dst -j RETURN
-A openclash_output -p tcp -m owner ! --uid-owner 65534 -j REDIRECT --to-ports 7892
-A zone_lan_postrouting -m comment --comment "!fw3: Custom lan postrouting rule chain" -j postrouting_lan_rule
-A zone_lan_prerouting -m comment --comment "!fw3: Custom lan prerouting rule chain" -j prerouting_lan_rule
-A zone_wan_postrouting -j MINIUPNPD-POSTROUTING
-A zone_wan_postrouting -m comment --comment "!fw3: Custom wan postrouting rule chain" -j postrouting_wan_rule
-A zone_wan_prerouting -m comment --comment "!fw3: Custom wan prerouting rule chain" -j prerouting_wan_rule
-A zone_wan_prerouting -j MINIUPNPD
* ISP 有没有进行 DNS 污染 (is your ISP performing DNS pollution?)
无
* 其他 (any other information that would be useful)
协议使用ss 加密是rc4-md5

### 重现问题的具体布骤 Steps to Reproduce

1. 使用fallback 通过httping这款工具对www.google.com进行http方式延迟测试
2. 有大量的延迟波动，不清楚是否是丢包 tcp等待重发
3. 当使用select手动选择fallback时相同节点，并未发现大量的这样的延迟波动
ps.我也不清楚是否是真的bug，希望有所解答解决这个问题就行
**我预期会发生……？**

在使用select时并没有发现明显的延迟波动
**实际上发生了什么？**

使用fallback，会有多次结果波动很大，具体如图
### 更多信息 More Information
使用fallback时的延迟测试
<img width="1970" alt="QQ20210418-084816@2x" src="https://user-images.githubusercontent.com/70276018/115130813-511cad00-a025-11eb-8615-3c837ec012b9.png">
使用select策略组的延迟测试
<img width="1701" alt="QQ20210418-084938@2x" src="https://user-images.githubusercontent.com/70276018/115130835-7f9a8800-a025-11eb-8778-885ccde4b4f5.png">
