### ISSUE TITLE
[Feature]请问D大能否增加一个单独的DNSmasq或是单独指定DNS功能在Clash中

### ISSUE THREAD

**Issue by lumikumi** [Dreamacro/clash#1376]
感谢你向 Clash Core 提交 Feature Request！
在提交之前，请确认：

- [ ] 我已经在 [Issue Tracker](……/) 中找过我要提出的请求

请注意，如果你并没有遵照这个 issue template 填写内容，我们将直接关闭这个 issue。

我都确认过了，我要继续提交。

------------------------------------------------------------------

请附上任何可以帮助我们解决这个问题的信息，如果我们收到的信息不足，我们将对这个 issue 加上 *Needs more information* 标记并在收到更多资讯之前关闭 issue。

### Clash core config

```
……
```

### Clash log

```
……
```

### 环境 Environment

* Clash Core 的操作系统 (the OS that the Clash core is running on)
……
* 使用者的操作系统 (the OS running on the client)
……
* 网路环境或拓扑 (network conditions/topology)
……
* iptables，如果适用 (if applicable)
……
* ISP 有没有进行 DNS 污染 (is your ISP performing DNS pollution?)
……
* 其他
……

### 说明 Description

因为现在Clash会劫持53端口无法与DNSmasq并存
我现在很需要DNSmasq的指定DNS功能
就是例如:
server=/baidu.com/1.1.1.1
server=/sina.com/114.114.114.114
这样我可以单独指定某个域名或者某些域名只是用固定DNS来解析

**Comment by luwah** [comment]
dns:
  enable: false
  listen: 0.0.0.0:53
你可以自定义端口

**Comment by xyxu1024** [comment]
你可以让clash用别的端口
```
dns:
  enable: true
  ipv6: true
  listen: ':1053'
```
然后dnsmasq的上游服务器指向clash
```
no-hosts
no-resolv
server=127.0.0.1#1053
```

**Comment by icpz** [comment]
可以尝试一下 dev 分支，加入了 nameserver-policy 字段来单独制定 dns #1406

**Comment by emacsnt** [comment]
请问nameserver-policy是否支持通配符或者说，它的匹配模式是exact或者是包含？
dns:
  enable: true
  listen: '0.0.0.0:53'
  nameserver-policy:
    '*.baidu.com': '114.114.114.114'

**Comment by icpz** [comment]
> 请问nameserver-policy是否支持通配符或者说，它的匹配模式是exact或者是包含？
> 
> dns:
> 
>   enable: true
> 
>   listen: '0.0.0.0:53'
> 
>   nameserver-policy:
> 
>     '*.baidu.com': '114.114.114.114'

支持，与 host 字段匹配策略一致

**Comment by emacsnt** [comment]
发现在premium版本里面不工作，指定的域名仍然走nameserver定义的dns server来解析
配置:
dns:
  enable: true
  listen: 0.0.0.0:1053
  nameserver-policy:
    'aaa.bbb.ccc': '127.0.0.1'
  enhanced-mode: fake-ip
  nameserver:
    - https://1.1.1.1/dns-query
    - tls://8.8.8.8:853

log:
WARN[0005] [TCP] dial 🐟 漏网之鱼 (match Match/) to 8.8.8.8 error: aaa.bbb.ccc:2003 connect error: all DNS requests failed, first error: context deadline exceeded
WARN[0005] [TCP] dial 🐟 漏网之鱼 (match Match/) to 8.8.8.8 error: aaa.bbb.ccc:2003 connect error: all DNS requests failed, first error: context deadline exceeded
WARN[0005] [TCP] dial 🐟 漏网之鱼 (match Match/) to 8.8.8.8 error: aaa.bbb.ccc:2003 connect error: all DNS requests failed, first error: context deadline exceeded
WARN[0005] [TCP] dial 🐟 漏网之鱼 (match Match/) to 1.1.1.1 error: aaa.bbb.ccc:2003 connect error: all DNS requests failed, first error: context deadline exceeded
WARN[0005] [TCP] dial 🐟 漏网之鱼 (match Match/) to 1.1.1.1 error: aaa.bbb.ccc:2003 connect error: all DNS requests failed, first error: context deadline exceeded

**Comment by icpz** [comment]
配置文件可以在前后用三个反引号扩起来吗，像这样：

\`\`\`
#your config here
\`\`\`

**Comment by emacsnt** [comment]
```
mixed-port: 7890
socks-port: 7891
redir-port: 7892
allow-lan: true
bind-address: "*"
mode: Rule
log-level: info
external-controller: :9090
secret: 123456
external-ui: /usr/share/clash/dashboard

dns:
  enable: true
  listen: 0.0.0.0:1053
  nameserver-policy:
    'aaa.bbb.ccc': '127.0.0.1'
  enhanced-mode: fake-ip
  nameserver:
    - https://1.1.1.1/dns-query
    - tls://8.8.8.8:853

tun:
  enable: true
  stack: system

proxies:
  - {name: HK 01, server: aaa.bbb.ccc, port: 2003, type: vmess, uuid: uuidxxxx, alterId: 1, cipher: auto, tls: false, network: ws, ws-path: /, udp: true}
```

log:
WARN[0005] [TCP] dial fish 漏网之鱼 (match Match/) to 8.8.8.8 error: aaa.bbb.ccc:2003 connect error: all DNS requests failed, first error: context deadline exceeded
WARN[0005] [TCP] dial fish 漏网之鱼 (match Match/) to 8.8.8.8 error: aaa.bbb.ccc:2003 connect error: all DNS requests failed, first error: context deadline exceeded
WARN[0005] [TCP] dial fish 漏网之鱼 (match Match/) to 8.8.8.8 error: aaa.bbb.ccc:2003 connect error: all DNS requests failed, first error: context deadline exceeded
WARN[0005] [TCP] dial fish 漏网之鱼 (match Match/) to 1.1.1.1 error: aaa.bbb.ccc:2003 connect error: all DNS requests failed, first error: context deadline exceeded
WARN[0005] [TCP] dial fish 漏网之鱼 (match Match/) to 1.1.1.1 error: aaa.bbb.ccc:2003 connect error: all DNS requests failed, first error: context deadline exceeded
