### ISSUE TITLE
[Feature] interface-name应用到proxies或者proxy-groups支持从不同的outbound出流量

### ISSUE THREAD

**Issue by GainSury** [Dreamacro/clash#1383]
- [x] 我已经在 [Issue Tracker](……/) 中找过我要提出的请求

### 说明 Description

目前clash对多outbound的支持不是很好，仅仅在profile层面支持参数interface-name绑定单个interface，能否将interface-name应用到proxies或者proxy-groups来支持从不同的outbound出流量。
考虑到部分接口不太稳定，比如usb移动网卡，WiFi，参考surge的做法，增加allow-other-interface: Optional (Default: false).来缓解接口不存在时使用其他接口的情况。

示例
```yaml
proxies:
 - name: "ss1"
    type: ss
    server: server
    port: 443
    cipher: chacha20-ietf-poly1305
    password: "password"
    interface-name: en0
    allow-other-interface: false
    # udp: true

proxy-groups:
    # select is used for selecting proxy or proxy group
  # you can use RESTful API to switch proxy is recommended for use in GUI.
  - name: Proxy
    type: select
    interface-name: en1
    # disable-udp: true
    proxies:
      - ss1
      - ss2
      - vmess1
      - auto
```

 参考：
1. #1118 
2. https://manual.nssurge.com/policy/proxy.html
