### ISSUE TITLE
做旁路由，安卓手机无法打开网页

### ISSUE THREAD

**Issue by AlexYangYH** [Dreamacro/clash#1386]
主路由：192.168.1.1
旁路由：192.168.1.2，网关、DNS: 192.168.1.1

上网手机：
安卓手机： IP: 192.168.1.11，网关、DNS为192.168.1.2
苹果手机： IP: 192.168.1.15，网关、DNS为192.168.1.2

Clash 配置文件如下

```
redir-port: 7892
mixed-port: 7890
allow-lan: true
authentication:
  - "xxxxxxx:xxxxxxx"
mode: Rule
log-level: info
ipv6: true
external-controller: 0.0.0.0:9090
external-ui: ui
secret: "xxxxxx"
dns:
  enable: true
  ipv6: true
  listen: 0.0.0.0:53
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  nameserver:
    - https://dns.rubyfish.cn/dns-query
    - https://223.5.5.5/dns-query
    - https://dns.pub/dns-query
  fallback:
    - https://1.0.0.1/dns-query
    - https://public.dns.iij.jp/dns-query
    - https://dns.twnic.tw/dns-query
  fallback-filter:
    geoip: true
    ipcidr:
      - 240.0.0.0/4
      - 0.0.0.0/32
      - 127.0.0.1/32
    domain:
      - +.google.com
      - +.facebook.com
      - +.youtube.com
      - +.xn--ngstr-lra8j.com
      - +.google.cn
      - +.googleapis.cn
      - +.gvt1.com

store-selected: false

下略
```

iptables 按以下设置：

```
iptables -t nat -N Clash
iptables -t nat -A Clash -d 192.168.0.0/16 -j RETURN
iptables -t nat -A Clash -p tcp -j REDIRECT --to-ports 7892
iptables -t nat -A PREROUTING -p tcp -j Clash
```

目前情况：
1. iOS设备可以上外网
2. 安卓设备可以用play store, YouTube等应用
3. 安卓浏览器打不开Google, duckduckgo等，打开ip111.cn 从谷歌访问没有显示IP地址

Clash记录如下

1. 安卓打开play store, 下载正常, 请求地址是IP不是域名

```
2021-05-02 08:54:50[info] [TCP]
192.168.1.11:39556 --> 172.217.160.74 match Match() using Proxy[proxy1]

```

2. 安卓打开https://www.google.com/ncr, 无法打开, 请求地址是IP不是域名

```
2021-05-02 08:54:50[info] [TCP]
192.168.1.11:42930 --> 108.160.165.139 match Match() using Proxy[proxy1]
```

3. 苹果打开https://www.google.com/ncr, 可以打开, 请求地址是域名

```
2021-05-02 08:55:56[info] [TCP]
192.168.1.15:49301 --> www.google.com match DomainKeyword(google) using Proxy[proxy1]
```
