### ISSUE TITLE
[Bug]Clash Core 未能正确关闭连接

### ISSUE THREAD

**Issue by RtYkk** [Dreamacro/clash#1387]
我决定单独开一个 Issue，因为虽然我遇到的问题和 #1311 或许有一些相似之处但并貌似并不完全一样。在正常浏览的时候，我并没有感觉 Clash 有占用我一个线程影响速度，我遇到的问题主要是连接关不了。而且原 Author 悍然直接关闭 Issue 让我失去了对我反馈的问题的掌控感。

------------------------------------------------------------------

### Clash config

<details>
  <summary>config.yaml</summary>

```yaml
mixed-port: 7890
redir-port: 7892
allow-lan: false
mode: global
log-level: debug
external-controller: 127.0.0.1:1834
secret: ''

# System proxy will ignore these domains(or ipnet)
cfw-bypass:
  - localhost
  - 127.*
  - 10.*
  - 172.16.*
  - 172.17.*
  - 172.18.*
  - 172.19.*
  - 172.20.*
  - 172.21.*
  - 172.22.*
  - 172.23.*
  - 172.24.*
  - 172.25.*
  - 172.26.*
  - 172.27.*
  - 172.28.*
  - 172.29.*
  - 172.30.*
  - 172.31.*
  - 192.168.*
  - <local>

# Proxies module latency test settings
cfw-latency-timeout: 3000 # seconds
cfw-latency-url: http://www.gstatic.com/generate_204

# Identify strategy of breaking connections after switching to a new proxy/profile/mode
# Options for proxy: none, chain(proxy group in connection chains), all
# Options for profile: true, false
# Options for mode: true, false
cfw-conn-break-strategy:
  proxy: none
  profile: true
  mode: false

# Run child process after CFW started
# Refer: https://docs.cfw.lbyczf.com/contents/childprocess.html
cfw-child-process: []

# Will be ignored after profile selection
Proxy:
  - name: Shadowsocks
    type: socks5
    server: 127.0.0.1
    port: 1080
Proxy Group:
  - name: Proxy
    type: select
    proxies:
      - Shadowsocks
Rule:
  - 'MATCH,DIRECT'

```

</details>

### Clash log

```
time="2021-05-02T13:31:51+08:00" level=info msg="[TCP] 127.0.0.1:1216 --> 163.*.*.* match Match() using Proxy[TEST]"
time="2021-05-02T13:31:52+08:00" level=info msg="[TCP] 127.0.0.1:1227 --> 163.*.*.* match Match() using Proxy[TEST]"
time="2021-05-02T13:31:52+08:00" level=info msg="[TCP] 127.0.0.1:1229 --> 163.*.*.* match Match() using Proxy[TEST]"
time="2021-05-02T13:31:52+08:00" level=info msg="[TCP] 127.0.0.1:1232 --> 163.*.*.* match Match() using Proxy[TEST]"
time="2021-05-02T13:31:52+08:00" level=info msg="[TCP] 127.0.0.1:1234 --> 163.*.*.* match Match() using Proxy[TEST]"
time="2021-05-02T13:31:57+08:00" level=info msg="[TCP] 127.0.0.1:1246 --> 163.*.*.* match Match() using Proxy[TEST]"
time="2021-05-02T13:31:57+08:00" level=info msg="[TCP] 127.0.0.1:1243 --> 163.*.*.* match Match() using Proxy[TEST]"
time="2021-05-02T13:31:57+08:00" level=info msg="[TCP] 127.0.0.1:1244 --> 163.*.*.* match Match() using Proxy[TEST]"
time="2021-05-02T13:32:04+08:00" level=info msg="[TCP] 127.0.0.1:1264 --> 163.*.*.* match Match() using Proxy[TEST]"
time="2021-05-02T13:34:31+08:00" level=info msg="[TCP] 127.0.0.1:1819 --> 163.*.*.* match Match() using Proxy[TEST]"
time="2021-05-02T13:34:32+08:00" level=info msg="[TCP] 127.0.0.1:1822 --> 163.*.*.* match Match() using Proxy[TEST]"
```

### 环境 Environment

* 操作系统 (the OS that the Clash core is running on)
  Windows 10 2004 企业版
* 网路环境或拓扑 (network conditions/topology)
  ……
* iptables，如果适用 (if applicable)
  ……
* ISP 有没有进行 DNS 污染 (is your ISP performing DNS pollution?)
  与此无关
* 其他 (any other information that would be useful)
  **我使用了 tap**，使用的代理是 Trojan

### 重现问题的具体布骤 Steps to Reproduce

1. 我是在我远程的一个 VPS 上搭建了 [Filebrowser Enhanced](https://hub.docker.com/r/80x86/filebrowser) 的服务来尝试进行网络串流
2. 随便点开一个视频，正常加载
3. 关闭视频

**我预期会发生……？**

连接中断，没有上传下载速度

**实际上发生了什么？**

继续占用大量带宽，除非手动 Close Connection 或者关闭 Clash

### 可能的解决方案 Possible Solution

idk

### 更多信息 More Information

首先我可以确定这是 Clash 的问题，一开始我也曾怀疑是 Filebrowser Enhanced 的问题，但是当我换用了 Qv2ray 来进行控制变量发现无法复现。我甚至还怀疑是不是速度显示错了，还装了个 TrafficMonitor 来进行对照，可以看录屏的右下角。然后我就想起了这个 Issue，发现我的情况确实很相似，下面有一段录屏。

https://user-images.githubusercontent.com/45971730/116810878-c38aa280-ab78-11eb-86eb-eed6cc3f984a.mp4

然后这是我在已经点了'×'之后的 Connections 情况，因为有一些个人信息，恕我无法通过录屏呈现。
![Clash_for_Windows_pSftdWLfqW](https://user-images.githubusercontent.com/45971730/116810952-3431bf00-ab79-11eb-9654-d20d1c7fbd0b.png)

Qv2ray 我确认过，在点了'×'之后是没有速度的，我就不重复上传录屏了，如果还需要更详细的信息我都可以提供。

我目前这个应该是 100% 复现的，我试了十次有余都能复现。如果说本 Issue 上面的 115 下载不能 100% 复现，我认为我这个复现成本还是比较低的。开个 VPS，装个 Docker，再在 Docker 里面起个 Filebrowser Enhanced，随便播放一个大概几百 MB 的视频，然后再关掉，就能复现了。而且我上面这个情况，**就算我把整个网页都关掉，也没用**，还在占带宽。

> 如果不使用 tap 使用 TUN 呢？如果只用系统代理呢

系统代理：稳定复现
TUN：稳定复现，但好像没走？……
![Clash_for_Windows_cQW04KJPe4](https://user-images.githubusercontent.com/45971730/116814502-d8246600-ab8b-11eb-82de-e04121659b3f.png)
