### ISSUE TITLE
[Bug] 在 TUN 模式時網卡設定多 IP 會無法連線

### ISSUE THREAD

**Issue by bestpika** [Dreamacro/clash#1388]
### Clash config

<details>
  <summary>config.yaml</summary>

```yaml
tun:
  enable: true
  stack: gvisor
  dns-hijack:
    - 198.18.0.2:53
  macOS-auto-route: true
  macOS-auto-detect-interface: true
dns:
  enable: true
  enhanced-mode: redir-host
  nameserver:
    - 127.0.0.1 # 我有在本機裝 AGH 但這跟這問題應該無關
  fake-ip-filter:
    - "dns.msftncsi.com"
    - "www.msftncsi.com"
    - "www.msftconnecttest.com"
rules:
  - MATCH,DIRECT
```

</details>

### Clash log

```
time="2021-05-04T11:22:14+08:00" level=warning msg="[TCP] dial DIRECT (match Match/) to www.google.com error: dial tcp4 172.16.120.20:0->172.217.160.100:443: i/o timeout"
time="2021-05-04T11:22:15+08:00" level=warning msg="[TCP] dial DIRECT (match Match/) to www.google.com error: dial tcp4 172.16.120.20:0->172.217.160.100:443: i/o timeout"
time="2021-05-04T11:22:19+08:00" level=warning msg="[TCP] dial DIRECT (match Match/) to www.google.com error: dial tcp4 172.16.120.20:0->172.217.160.100:443: i/o timeout"
time="2021-05-04T11:22:20+08:00" level=warning msg="[TCP] dial DIRECT (match Match/) to www.google.com error: dial tcp4 172.16.120.20:0->172.217.160.100:443: i/o timeout"
time="2021-05-04T11:22:20+08:00" level=warning msg="[TCP] dial DIRECT (match Match/) to www.google.com error: dial tcp4 172.16.120.20:0->172.217.160.100:443: i/o timeout"
```

### 环境 Environment

* 操作系统 (the OS that the Clash core is running on)
  Windows 10 x64
* 网路环境或拓扑 (network conditions/topology)
* iptables，如果适用 (if applicable)
* ISP 有没有进行 DNS 污染 (is your ISP performing DNS pollution?)
* 其他 (any other information that would be useful)

### 说明 Description

這張網卡我設定了兩個 IP 位址，分別是 192.168.xxx.xxx 及 172.16.xxx.xxx
然後當我啟動 Clash 時我發現流量似乎都被導向到 172.16 去
然而那個 IP 我根本沒有設定任何 gateway
然後我只要把 172.16.xxx.xxx 刪除就通了

但在沒有啟用 Clash 的時候這個網路設定沒有任何問題

### 重现问题的具体布骤 Steps to Reproduce

1. Enable System Proxy

**我预期会发生……？**

連線應該被導向 192.168.xxx.xxx

**实际上发生了什么？**

連線被導向到沒有設定 gateway 的 172.16.xxx.xxx
