### ISSUE TITLE
[Bug]http header 中的 host 伪装不生效

### ISSUE THREAD

**Issue by gzleangle** [Dreamacro/clash#1398]
感谢你向 Clash Core 提交 issue！
在提交之前，请确认：

- [ ] 如果你可以自己 debug 并解决的话，提交 PR 吧！
- [x] 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [ ] 我已经使用 dev 分支版本测试过，问题依旧存在
- [x] 我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题
- [x] 这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题

------------------------------------------------------------------

### Clash config

<details>
  <summary>config.yaml</summary>

```yaml
port: 7890
socks-port: 7891
allow-lan: false
bind-address: '*'
mode: rule
log-level: info
ipv6: true
external-controller: 127.0.0.1:9090

dns:
  enable: true
  listen: 0.0.0.0:5300
  ipv6: true
  default-nameserver:
    - 8.8.8.8
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  nameserver:
    - 8.8.8.8

proxies:
  - name: Proxy
    type: vmess
    server:
    port:
    uuid:
    alterId: 0
    cipher: auto
    udp: true
    network: http
    http-opts:
      method: "GET"
      path:
        - '/'
      headers:
        Host:
          - "example.com"

rules:
  - IP-CIDR,10.0.0.0/8,DIRECT
  - IP-CIDR,127.0.0.0/8,DIRECT
  - IP-CIDR,172.16.0.0/12,DIRECT
  - IP-CIDR,192.168.0.0/16,DIRECT
  - MATCH,Proxy
```

</details>

或

<details>
  <summary>config.yaml</summary>

```yaml
port: 7890
socks-port: 7891
allow-lan: false
bind-address: '*'
mode: rule
log-level: info
ipv6: true
external-controller: 127.0.0.1:9090

dns:
  enable: true
  listen: 0.0.0.0:5300
  ipv6: true
  default-nameserver:
    - 8.8.8.8
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  nameserver:
    - 8.8.8.8

proxies:
  - name: Proxy
    type: vmess
    server:
    port:
    uuid:
    alterId: 0
    cipher: auto
    udp: true
    network: http
    http-opts:
      method: "GET"
      path:
        - '/'
      headers:
        Host: ["example.com"]

rules:
  - IP-CIDR,10.0.0.0/8,DIRECT
  - IP-CIDR,127.0.0.0/8,DIRECT
  - IP-CIDR,172.16.0.0/12,DIRECT
  - IP-CIDR,192.168.0.0/16,DIRECT
  - MATCH,Proxy
```

</details>

### 环境 Environment

* 操作系统 (the OS that the Clash core is running on)
linux armv8

### 说明 Description

不知道是不是配置文件写错了，试了上面2个配置文件，抓包http header中的Host并没有变为example.com。找了下相关issue，对提到的Host写法也试了，抓包的Host还是没有变为example.com。请看下是什么问题，谢谢
