### ISSUE TITLE
[Bug] tun 模式在硬件 J1900 下仅能达到 100Mbps 左右的速度

### ISSUE THREAD

**Issue by overcache** [Dreamacro/clash#1405]
------------------------------------------------------------------

### Clash config

<details>
  <summary>config.yaml</summary>

```yaml
mixed-port: 7890
allow-lan: true
bind-address: '*'
mode: rule
log-level: warning
ipv6: false
external-controller: 127.0.0.1:9090
interface-name: ppp0
profile:
  store-selected: false
  tracing: true
hosts:
  # '.dev': 127.0.0.1
  # 'alpha.clash.dev': '::1'

dns:
  enable: true
  listen: 0.0.0.0:1053
  ipv6: false # when the false, response to AAAA questions will be empty
  default-nameserver:
    - 114.114.114.114
    - 8.8.8.8
  enhanced-mode: redir-host # or fake-ip
  fake-ip-range: 198.18.0.1/16 # Fake IP addresses pool CIDR
  use-hosts: true # lookup hosts and return IP record
  fake-ip-filter:
    - '*.lan'
    - localhost.ptlogin2.qq.com
  nameserver:
    # - 127.0.0.1:5353 # dnsmasq->isp
    - 114.114.114.114
    - tls://dns.rubyfish.cn:853 # DNS over TLS
  fallback:
    - 8.8.8.8 # default value
    - tls://dns.rubyfish.cn:853 # DNS over TLS

  fallback-filter:
    geoip: true
    ipcidr:
      - 240.0.0.0/4
    # domain:
    #   - '+.google.com'
    #   - '+.facebook.com'
    #   - '+.youtube.com'

tun:
  enable: true
  stack: gvisor # gvisor/system
  dns-hijack:
    - tcp://8.8.8.8:53
    - 8.8.8.8:53

    # nftable 直接dnat到 127.0.0.1:1053, 会发现无法解析dns
    # 改成 dnat 到 11.22.33.44:55, 然后在此处 hijack 就行
    - 11.22.33.44:55

proxies:
  - name: "snk"
    type: vmess
    server: 1.1.1.1
    port: 8001
    uuid: xxxx
    alterId: 64
    cipher: auto
    udp: true

proxy-groups:
  - name: PROXY
    type: select
    # disable-udp: true
    proxies:
      - snk


rules:
  # 根据来源ip路由: 家里的一些设备需要不经过代理(如果有问题的话, 把这个规则挪到nftables里吧)
  - SRC-IP-CIDR,10.0.0.224/27,DIRECT
  - MATCH,PROXY

```

</details>

### Clash log

```
……
```

### 环境 Environment

* 操作系统 (the OS that the Clash core is running on)
```bash
❯ neofetch
       _,met$$$$$gg.          root@router
    ,g$$$$$$$$$$$$$$$P.       -----------
  ,g$$P"     """Y$$.".        OS: Debian GNU/Linux bullseye/sid x86_64
 ,$$P'              `$$$.     Host: YL-J1900-V1
',$$P       ,ggs.     `$$b:   Kernel: 5.7.0-1-amd64
`d$$'     ,$P"'   .    $$$    Uptime: 37 days, 14 hours, 32 mins
 $$P      d$'     ,    $$P    Packages: 1031 (dpkg)
 $$:      $$.   -    ,d$$'    Shell: zsh 5.8
 $$;      Y$b._   _,d$P'      Terminal: /dev/pts/4
 Y$$.    `.`"Y$$$$P"'         CPU: Intel Celeron J1900 (4) @ 2.415GHz
 `$$b      "-.__              GPU: Intel Atom Processor Z36xxx/Z37xxx Series Graphics & Display
  `Y$$                        Memory: 496MiB / 1882MiB
   `Y$$.
     `$$b.
       `Y$$b.
          `"Y$b._
              `"""


❯ clash -v
Clash 2021.05.08 linux amd64 with go1.16.3 Sat May  8 11:37:04 UTC 2021


❯ nft -v
nftables v0.9.8 (E.D.S.)

❯ ip addr show dev utun
135: utun: <POINTOPOINT,MULTICAST,NOARP,UP,LOWER_UP> mtu 9000 qdisc pfifo_fast state UNKNOWN group default qlen 500
    link/none
    inet 198.18.0.1/16 scope global utun
       valid_lft forever preferred_lft forever
    inet6 fe80::5fed:ce81:7b04:c577/64 scope link stable-privacy
       valid_lft forever preferred_lft forever

❯ ethtool utun
Settings for utun:
        Supported ports: [  ]
        Supported link modes:   Not reported
        Supported pause frame use: No
        Supports auto-negotiation: No
        Supported FEC modes: Not reported
        Advertised link modes:  Not reported
        Advertised pause frame use: No
        Advertised auto-negotiation: No
        Advertised FEC modes: Not reported
        Speed: 10Mb/s
        Duplex: Full
        Auto-negotiation: off
        Port: Twisted Pair
        PHYAD: 0
        Transceiver: internal
        MDI-X: Unknown
        Current message level: 0x00000000 (0)

        Link detected: yes



```

* 网路环境或拓扑 (network conditions/topology)
光猫 - 软路由(拨号) - 交换机 - 终端

* iptables，如果适用 (if applicable)
```bash
❯ nft list ruleset
table ip filter {
        chain INPUT {
                type filter hook input priority filter; policy drop;
                ct state { established, related } accept
                ct state invalid drop
                iifname "lo" accept
                ip protocol icmp accept
                iif "enp3s0" accept
        }

        chain FORWARD {
                type filter hook forward priority filter; policy accept;
                oifname "ppp0" tcp flags syn tcp option maxseg size set rt mtu
        }
}
table ip nat {
        chain POSTROUTING {
                type nat hook postrouting priority srcnat; policy accept;
                oifname "ppp0" masquerade
        }
}
table ip clash {
        chain local {
                type route hook output priority filter; policy accept;
                ip protocol != { tcp, udp } accept
                meta cgroup 114514 accept
                ip daddr { 10.0.0.0/8, 127.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16, 224.0.0.0/4 } accept
                ct state new ct mark set 0x0001bf52
                ct mark 0x0001bf52 meta mark set 0x0001bf52
        }

        chain forward {
                type filter hook prerouting priority filter; policy accept;
                ip protocol != { tcp, udp } accept
                iif "utun" accept
                ip daddr { 10.0.0.0/8, 127.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16, 224.0.0.0/4 } accept
                meta mark set 0x0001bf52
        }

        chain local-dns-redirect {
                type nat hook output priority filter; policy accept;
                ip protocol != { tcp, udp } accept
                meta cgroup 114514 accept
                ip daddr 127.0.0.0/8 accept
                udp dport 53 dnat to 11.22.33.44:55
                tcp dport 53 dnat to 11.22.33.44:55
        }

        chain forward-dns-redirect {
                type nat hook prerouting priority filter; policy accept;
                ip protocol != { tcp, udp } accept
                udp dport 53 dnat to 11.22.33.44:55
                tcp dport 53 dnat to 11.22.33.44:55
        }
}
```

* ISP 有没有进行 DNS 污染 (is your ISP performing DNS pollution?)
未知

* 其他 (any other information that would be useful)
……

### 说明 Description

clash 以 tun 模式运行在网关(cpu J1900)时, 使用 speedtest.net 进行测试时, 速度无法超过 130 Mbps, cpu 负载平均达到87%. 预期可以跑满 300Mbps 的带宽.

### 重现问题的具体布骤 Steps to Reproduce

1. 使用 https://github.com/Kr328/clash-premium-installer 配置网关模式. (调整了 udp port 53 的 dnat 地址, config.yaml 设置了相应的 dns-hijack)
2. 使用 [speedtest-cli](https://install.speedtest.net/app/cli/ookla-speedtest-1.0.0-x86_64-linux.tgz) 在网关进行测速, 或者使用 [speedtest.net](https://www.speedtest.net/) 在终端进行测速

**我预期会发生……？**

预期能大概测出 300Mbps 的下行速率, cpu负载在80%左右

**实际上发生了什么？**

测试结果 100Mbps 左右, cpu负载平均90%
```bash
❯ ./speedtest

   Speedtest by Ookla

     Server: MyRepublic - Singapore (id = 5935)
        ISP: Digital Ocean
    Latency:    48.50 ms   (0.74 ms jitter)
   Download:   117.52 Mbps (data used: 120.2 MB)
     Upload:    88.44 Mbps (data used: 102.7 MB)
Packet Loss:     0.0%
 Result URL: https://www.speedtest.net/result/c/f9f8f96c-064b-4814-935f-da26cad8e5f6
```
![Screenshot 2021-05-16 at 12 38 20](https://user-images.githubusercontent.com/1908329/118386449-1b7dda80-b64a-11eb-863e-3dc58d6ab6ff.png)

### iperf3 对 utun 的测试结果
```bash
# 网关上执行
iperf --bind 198.18.0.1 -s
```
```bash
# 网关上执行
❯ iperf3 -c 198.18.0.1
Connecting to host 198.18.0.1, port 5201
[  5] local 198.18.0.1 port 53128 connected to 198.18.0.1 port 5201
[ ID] Interval           Transfer     Bitrate         Retr  Cwnd
[  5]   0.00-1.00   sec   999 MBytes  8.37 Gbits/sec    0   2.12 MBytes
[  5]   1.00-2.00   sec   965 MBytes  8.09 Gbits/sec    0   2.50 MBytes
[  5]   2.00-3.00   sec   952 MBytes  8.00 Gbits/sec    0   2.50 MBytes
[  5]   3.00-4.00   sec   960 MBytes  8.05 Gbits/sec    0   2.75 MBytes
[  5]   4.00-5.00   sec   950 MBytes  7.96 Gbits/sec    0   2.87 MBytes
[  5]   5.00-6.00   sec   972 MBytes  8.16 Gbits/sec    0   3.06 MBytes
[  5]   6.00-7.00   sec   996 MBytes  8.35 Gbits/sec    0   3.06 MBytes
[  5]   7.00-8.00   sec   990 MBytes  8.31 Gbits/sec    0   3.06 MBytes
[  5]   8.00-9.00   sec   959 MBytes  8.05 Gbits/sec    0   3.06 MBytes
[  5]   9.00-10.00  sec   966 MBytes  8.10 Gbits/sec    0   3.06 MBytes
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bitrate         Retr
[  5]   0.00-10.00  sec  9.48 GBytes  8.15 Gbits/sec    0             sender
[  5]   0.00-10.00  sec  9.48 GBytes  8.14 Gbits/sec                  receiver

iperf Done.
```

### 带宽速度
```bash
❯ ./speedtest

   Speedtest by Ookla

     Server: ChinaTelecom 5G - Guangzhou (id = 27594)
        ISP: China Telecom
    Latency:     2.73 ms   (0.10 ms jitter)
   Download:   297.18 Mbps (data used: 134.3 MB)
     Upload:    97.22 Mbps (data used: 43.8 MB)
Packet Loss:     0.0%
 Result URL: https://www.speedtest.net/result/c/b8b2e13f-ed52-4cf8-92f2-30f9bce5ebb4
```

**Comment by Dreamacro** [comment]
直接测网关是不准确的，绑定在网关测的是 TUN 的 io 性能，不经过 clash。可以设置一个 host 用 `nip.io` 指向内网 ip，在用 iperf 测试，这样能测出经过 clash 时的 io 性能（这个时候 clash 里应该会有日志）

**Comment by overcache** [comment]
好吧, 目前还没有其他可以使用iperf3测试的设备.

抛开tun的io性能不谈, 网速达到100Mbps的时候, cpu负载已经90%了, 瓶颈应该不是io了吧.

**Comment by Kr328** [comment]
是不推荐使用 stack: gvisor

在 Android 的 高通骁龙 845 上仅有 200Mbps DOWN 和 10Mbps UP
更换到 类 stack: system 实现后 UP/DOWN 都能达到 3Gbps

**Comment by overcache** [comment]
> 是不推荐使用 stack: gvisor
> 
> 在 Android 的 高通骁龙 845 上仅有 200Mbps DOWN 和 10Mbps UP
> 更换到 类 stack: system 实现后 UP/DOWN 都能达到 3Gbps

能说一下测试方法吗？3Gbps是直连的速度吧，系统有没有代理协议的加解密开销。我用gvisor或者system差别都不大，想再排查一下。

**Comment by cjwddtc** [comment]
@Kr328 我也很好奇你的配置，我测试下来性能redir>tproxy>tun，我用的r4s redir能跑满千兆，tproxy就会出现网卡irq亲和的cpu核心满载其他核心只有一半占用但是有跑不满兆（大概500m的样子）的情况，tun只有300m更惨。

**Comment by Kr328** [comment]
@overcache @cjwddtc 

最近 Android 测试出来多线程大概 2Gbps (高通骁龙 845 的 一加 6

不过最近是是更换了 lwip 的 tcpip 协议栈 和 之前的 Android 的类 stack: system 性能与 lwip 类似 (lwip 会需要更少的 CPU 和 内存

Android 的 tun 实现与 clash premium 实现仍然是存在差异的
类 system 实现是 https://github.com/Kr328/tun2socket
lwip 实现是 https://github.com/Kr328/tun2socket-lwip

#### 测试方法

配置
```yaml
dns:
  enable: true
  enhanced-mode: fake-ip
  use-hosts: false
  nameserver:
     - 114.114.114.114
hosts:
  "local.lan": "127.0.0.1"
```

本地服务端
```bash
# iperf3 -s
```

本地客户端
```bash
iperf3 -c local.lan -P 4
```

客户端和服务的都跑在手机上

最近一次测试的结果
![image](https://user-images.githubusercontent.com/39107975/120841160-be68ab00-c59d-11eb-860b-d02f51c70d31.png)

#### 其他
就算是在 x86 的台式机上 tun 性能也远不如 socks5/http connect/redirect 
毕竟经过 lo 的连接是不需要任何封包拆包和做各种管理
tun 仍然需要一个协议栈来建立 TCP

不过 最近的 lwip 协议栈 在 x86 的台式机上 已经能跑到 socks5 的 2/3 的性能 (11Gbps vs 17Gbps
