### ISSUE TITLE
TProxy + Fake IP 透明代理下如何设置 iptables 拦劫 198.18.0.1/16 的 ICMP 请求

### ISSUE THREAD

**Issue by phlinhng** [Dreamacro/clash#1417]
### Clash config
```yaml
tproxy-port: 7893
dns:
  enable: true
  listen: 0.0.0.0:53
  ipv6: false
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter: # fake ip white domain list
    - '*.lan'
    - localhost.ptlogin2.qq.com
  default-nameserver:
    - 223.5.5.5
    - 119.29.29.29
  nameserver:
    - 223.5.5.5
    - 119.29.29.29
  fallback:
    - https://101.6.6.6/dns-query
    - https://dns.alidns.com/dns-query
```

</details>

### 环境 Environment

* 操作系统 (the OS that the Clash core is running on)
网关: 192.168.6.2, Linux 20.10 
子网: 192.168.6.0/24
* 网路环境或拓扑 (network conditions/topology)
Linux 主机做为内网 DHCP 网关与内网 DNS
* iptables，如果适用 (if applicable)
```
# ROUTE RULES
ip rule add fwmark 1 table 100
ip route add local 0.0.0.0/0 dev lo table 100

# CREATE TABLE
iptables -t mangle -N clash

# RETURN LOCAL AND LANS
iptables -t mangle -A clash -d 0.0.0.0/8 -j RETURN
iptables -t mangle -A clash -d 10.0.0.0/8 -j RETURN
iptables -t mangle -A clash -d 127.0.0.0/8 -j RETURN
iptables -t mangle -A clash -d 169.254.0.0/16 -j RETURN
iptables -t mangle -A clash -d 172.16.0.0/12 -j RETURN
iptables -t mangle -A clash -d 192.168.50.0/16 -j RETURN
iptables -t mangle -A clash -d 192.168.9.0/16 -j RETURN

iptables -t mangle -A clash -d 224.0.0.0/4 -j RETURN
iptables -t mangle -A clash -d 240.0.0.0/4 -j RETURN

# FORWARD ALL
iptables -t mangle -A clash -p udp -j TPROXY --on-port 7893 --tproxy-mark 1
iptables -t mangle -A clash -p tcp -j TPROXY --on-port 7893 --tproxy-mark 1

# REDIRECT
iptables -t mangle -A PREROUTING -j clash

# HIJACK ICMP
iptables -t nat -A PREROUTING -p icmp -d 198.18.0.1/16 -j DNAT --to-destination 127.0.0.1
iptables -t filter -A FORWARD -p icmp -d 127.0.0.1 -j ACCEPT
```
* ISP 有没有进行 DNS 污染 (is your ISP performing DNS pollution?)
无
* 其他 (any other information that would be useful)

### 说明 Description

在目前的设置下，一般上网完全正常。对一般 IP（非 Fake IP）的 ICMP 请求也完全正常。
有使用`tcpdump icmp`测试过，子网内所有终端 (192.168.6.x) 发的 ICMP 请求能正常到达网关并顺利得到回应。

但是在 Fake IP 模式下，域名请求会由 Clash DNS 返回 `198.18.0.1/16` 段内的 Fake IP
正常来说，对 Fake IP 发送 icmp 是不会有任何回应的。
因此我想让网关设备抢答 `198.18.0.1/16` 的 ICMP 包，伪造一个回应，达成像[这篇文章](https://lev.shield.asia/index.php/Ops/31.html)的效果。然而没有成功

除了以上的指令外，我还试过将 127.0.0.1 换成 223.5.5.5
```
iptables -t nat -A PREROUTING -p icmp -d 198.18.0.1/16 -j DNAT --to-destination 223.5.5.5
iptables -t filter -A FORWARD -p icmp -d 223.5.5.5 -j ACCEPT
```
依然 ping 不通 198.18.x.x

另外，我试过拦劫其他 IP，例如 1.1.1.1。
```
iptables -t nat -A PREROUTING -p icmp -d 1.1.1.1 -j DNAT --to-destination 127.0.0.1
iptables -t filter -A FORWARD -p icmp -d 127.0.0.1 -j ACCEPT
```
这样设置后，网关本身还是能 ping 通 1.1.1.1，但是子网的设备 ping 1.1.1.1 没有响应了
