### ISSUE TITLE
proxy-groups 下 use 和 proxies 共存 url-test 模式会忽略 proxies 下的代理

### ISSUE THREAD

**Issue by Jial08** [Dreamacro/clash#1429]
------------------------------------------------------------------

### Clash config

<details>
  <summary>config.yaml</summary>

```yaml
port: 7890
socks-port: 7891
allow-lan: false
bind-address: "*"
mode: rule
log-level: info
external-controller: 127.0.0.1:9090
hosts:
dns:
  enable: true
  listen: 0.0.0.0:53
  ipv6: true
  default-nameserver:
    - 223.5.5.5
    - 114.114.114.114
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.lan'
    - '*.linksys.com'
    - '*.linksyssmartwifi.com'
    - 'swscan.apple.com'
    - 'mesu.apple.com'
    - '*.msftconnecttest.com'
    - '*.msftncsi.com'
    - 'time.*.com'
    - 'time.*.gov'
    - 'time.*.edu.cn'
    - 'time.*.apple.com'

    - 'time1.*.com'
    - 'time2.*.com'
    - 'time3.*.com'
    - 'time4.*.com'
    - 'time5.*.com'
    - 'time6.*.com'
    - 'time7.*.com'

    - 'ntp.*.com'
    - 'ntp.*.com'
    - 'ntp1.*.com'
    - 'ntp2.*.com'
    - 'ntp3.*.com'
    - 'ntp4.*.com'
    - 'ntp5.*.com'
    - 'ntp6.*.com'
    - 'ntp7.*.com'

    - '*.time.edu.cn'
    - '*.ntp.org.cn'
    - '+.pool.ntp.org'

    - 'time1.cloud.tencent.com'
    - '+.music.163.com'
    - '*.126.net'
    - 'musicapi.taihe.com'
    - 'music.taihe.com'
    - 'songsearch.kugou.com'
    - 'trackercdn.kugou.com'
    - '*.kuwo.cn'
    - 'api-jooxtt.sanook.com'
    - 'api.joox.com'
    - 'joox.com'
    - '+.y.qq.com'
    - '+.music.tc.qq.com'
    - 'aqqmusic.tc.qq.com'
    - '+.stream.qqmusic.qq.com'
    - '*.xiami.com'
    - '+.music.migu.cn'
    - '+.srv.nintendo.net'
    - '+.stun.playstation.net'
    - 'xbox.*.microsoft.com'
    - '+.xboxlive.com'
    - 'localhost.ptlogin2.qq.com'
    - 'proxy.golang.org'
    - 'stun.*.*'
    - 'stun.*.*.*'

  nameserver:
    - https://doh.pub/dns-query
    - https://dns.alidns.com/dns-query

  fallback-filter:
    geoip: false
    ipcidr:
      - 240.0.0.0/4
      - 0.0.0.0/32

tun:
  enable: false
  stack: system
  macOS-auto-route: true
  macOS-auto-detect-interface: true
  dns-hijack:
    - tcp://8.8.8.8:53
    - tcp://8.8.4.4:53

proxies:
  - name: self
    server: server
    port: port
    type: ssr
    password: password
    cipher: aes-256-cfb
    protocol: origin
    protocol-param:
    obfs: plain
    obfs-param:

proxy-groups:
  - name: ♻️ auto
    type: url-test
    use:
      - other
    proxies:
      - self
    url: 'http://www.gstatic.com/generate_204'
    interval: 300
      
proxy-providers:
  other:
    type: http
    url: url
    path: ./other.yaml
    interval: 3600
    health-check:
      enable: true
      interval: 600
      url: http://www.gstatic.com/generate_204

rule-providers:
  apple-proxy:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/Hackl0us/SS-Rule-Snippet@master/Rulesets/Clash/Basic/Apple-proxy.yaml"
    path: ./ruleset/Apple-proxy.yaml
    interval: 3600

  apple-direct:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/Hackl0us/SS-Rule-Snippet@master/Rulesets/Clash/Basic/Apple-direct.yaml"
    path: ./ruleset/Apple-direct.yaml
    interval: 3600

  cn:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/Hackl0us/SS-Rule-Snippet@master/Rulesets/Clash/Basic/CN.yaml"
    path: ./ruleset/CN.yaml
    interval: 3600

  ad-keyword:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/Hackl0us/SS-Rule-Snippet@master/Rulesets/Clash/Basic/common-ad-keyword.yaml"
    path: ./ruleset/common-ad-keyword.yaml
    interval: 3600

  foreign:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/Hackl0us/SS-Rule-Snippet@master/Rulesets/Clash/Basic/foreign.yaml"
    path: ./ruleset/foreign.yaml
    interval: 3600

  telegram:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/Hackl0us/SS-Rule-Snippet@master/Rulesets/Clash/App/social/Telegram.yaml"
    path: ./ruleset/Telegram.yaml
    interval: 3600

  lan:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/Hackl0us/SS-Rule-Snippet@master/Rulesets/Clash/Basic/LAN.yaml"
    path: ./ruleset/LAN.yaml
    interval: 3600

rules:
  - RULE-SET,apple-proxy,♻️ auto
  - RULE-SET,apple-direct,DIRECT
  - RULE-SET,cn,DIRECT
  - RULE-SET,ad-keyword,REJECT
  - RULE-SET,foreign,♻️ auto
  - RULE-SET,telegram,♻️ auto
  - RULE-SET,lan,DIRECT
  - GEOIP,CN,DIRECT
  - MATCH,♻️ auto
```

</details>

### 环境 Environment

* 操作系统：win10教育版1909，版本：18363.1256
* ClashCore：2021.05.08 Premium (51034)

### 说明 Description

proxy-groups 的同一个 name 下有 use 和 proxies 且 type 为 url-test 时，不会测速和选择 proxies 下的节点

### 重现问题的具体布骤 Steps to Reproduce

1. 当用如下配置时：
```yaml
proxies:
  - name: self
    ...

proxy-groups:
  - name: ♻️ auto
    type: url-test
    use:
      - other
    proxies:
      - self
    url: 'http://www.gstatic.com/generate_204'
    interval: 300

proxy-providers:
  other:
    type: http
    url: ...
    path: ./other.yaml
    interval: 3600
    health-check:
      enable: true
      interval: 600
      url: http://www.gstatic.com/generate_204
```

效果如下：
![Snipaste_2021-05-27_13-25-31](https://user-images.githubusercontent.com/25861104/119770757-37f20080-beef-11eb-98a6-89b7d71b3f29.png)
即 self 节点不测数也不选择

2. 当把 proxies 配置移动到 my.yaml  文件中时，如下配置：
```yaml
proxy-groups:
  - name: ♻️ auto
    type: url-test
    use:
      - my
      - other
    url: 'http://www.gstatic.com/generate_204'
    interval: 300

proxy-providers:
  my:
    type: file
    path: ./my.yaml
    health-check:
      enable: true
      interval: 600
      url: http://www.gstatic.com/generate_204
  other:
    type: http
    url: ...
    path: ./other.yaml
    interval: 3600
    health-check:
      enable: true
      interval: 600
      url: http://www.gstatic.com/generate_204
```
效果如下：
![image](https://user-images.githubusercontent.com/25861104/119772605-075f9600-bef2-11eb-85b7-b36794f4f303.png)

测速了也选择了最快的节点 self

**注意**：proxies 必须从主配置文件中删除后写入 my.yaml 中才能有 2 的效果，否则还是如 1 的效果

**预期行为**

希望在 use 和 proxies 共存时也能达到 2 的效果
