### ISSUE TITLE
[Bug] TUN网卡有时无法正常关闭

### ISSUE THREAD

**Issue by returnL** [Dreamacro/clash#1434]
------------------------------------------------------------------

### Clash config

<details>
  <summary>config.yaml</summary>

```yaml
mixin: # object
  dns:
    enable: true
    listen: 0.0.0.0:53
    ipv6: false
    enhanced-mode: fake-ip
    fake-ip-range: 198.18.0.1/16
    fake-ip-filter:
      - "dns.msftncsi.com"
      - "www.msftncsi.com"
      - "+.msftconnecttest.com"
      - "+.qq.com"
      - "+.music.163.com"
      - "+.music.162.com"
      - "*.lan"
      - '*.*.*.*.srv.nintendo.net'
      - '*.*.*.stun.playstation.net'
      - 'xbox.*.microsoft.com'
      - '*.*.*.xboxlive.com'
    nameserver:
      - https://dns.alidns.com/dns-query
      - https://doh.pub/dns-query
      - 223.5.5.5
      - 119.29.29.29
      - tls://dns.google:853
  
  #interface-name: WLAN

  tun:
    enable: true
    stack: gvisor
    dns-hijack:
      - 198.18.0.2:53
    auto-route: true
    auto-detect-interface: true # 自动检测出口网卡
```

</details>

### Clash log

```
……
```

### 环境 Environment

* 操作系统 (the OS that the Clash core is running on)
Windows 10 21H1，Core版本为2021.05.08 Premium
* 网路环境或拓扑 (network conditions/topology)
光猫 - 路由器 - 终端
* iptables，如果适用 (if applicable)
……
* ISP 有没有进行 DNS 污染 (is your ISP performing DNS pollution?)
无
* 其他 (any other information that would be useful)
……

### 说明 Description

使用Clash for Windows的Mixin开关TUN模式，关闭Mixin后，Clash网卡有概率依旧存在，而此时TUN模式已经关闭，导致无法上网。
![image](https://user-images.githubusercontent.com/44701395/120152318-e95ea200-c21f-11eb-8df0-359031ddcfaf.png)

### 重现问题的具体布骤 Steps to Reproduce

1. CFW运行在后台，未使用Lightweight Mode
2. 通过关闭Mixin来关闭TUN
3. TUN模式的Clash网卡未关闭，依旧存在

**我预期会发生……？**
Mixin关闭后，TUN模式关闭，Clash网卡也关闭

**实际上发生了什么？**
Mixin关闭后，TUN模式关闭，Clash网卡却依旧存在

### 更多信息 More Information
在我使用过程中，Clash网卡无法正常关闭的情况比正常关闭的情况多，往往是无法正常关闭的
