### ISSUE TITLE
[Bug] IPv6 节点支持问题

### ISSUE THREAD

**Issue by leonsyc** [Dreamacro/clash#1439]
------------------------------------------------------------------

### Clash config

<details>
  <summary>config.yaml</summary>

```yaml
  - name: "🇭🇰 HK v6" 
    type: ss 
    server: [aaaa::a8aa:ff:fe09:57d8]
    port: 1234
    cipher: aes-256-gcm
    password: "passswdddd"
    udp: true

```

</details>

### Clash log

```
2021/06/05 18:12:51.982  [info] [Auto Upgrade] Finish Subscription result: 托管配置文件格式不正确: proxy 9: 'server' expected type 'string', got unconvertible type '[]interface {}'
```

### 环境 Environment

* 操作系统 (the OS that the Clash core is running on)
macOS, Android 

### 说明 Description

v6地址的节点无法添加/使用

### 重现问题的具体布骤 Steps to Reproduce
v6 only 机器上自建ss。修改clash配置文件时，发现无论怎么填写server信息都会报错。
按照wiki中添加 [] 报错 'server' expected type 'string', got unconvertible type '[]interface {}'
[v6地址]前后再加上引号''，或者完全不加[] 的话能够通过，但是无法使用。展开v6地址缩写结果一样。
