### ISSUE TITLE
[Wiki] Configuration chapter Proxy Providers sample code error

### ISSUE THREAD

**Issue by plain-dev** [Dreamacro/clash#1442]
[> ***Browse***](https://github.com/Dreamacro/clash/wiki/configuration#proxy-providers)

***After editing***

```yaml
proxy-providers:
  provider1:
    type: http
    url: "url"
    interval: 3600
    path: ./provider1.yaml
    health-check:
      enable: true
      interval: 600
      # lazy: true
      url: http://www.gstatic.com/generate_204
  test:
    type: file
    path: /test.yaml
    health-check:
      enable: true
      interval: 36000
      url: http://www.gstatic.com/generate_204
```
