### ISSUE TITLE
ios手机配置wifi http代理，机器为局域网机器，QQ音乐无法使用？

### ISSUE THREAD

**Issue by xiaod-dev** [Dreamacro/clash#1446]
------------------------------------------------------------------

<!-- 
请附上任何可以帮助我们解决这个问题的信息，如果我们收到的信息不足，我们将对这个 issue 加上 *Needs more information* 标记并在收到更多资讯之前关闭 issue。
Make sure to add **all the information needed to understand the bug** so that someone can help. If the info is missing we'll add the 'Needs more information' label and close the issue until there is enough information.
-->

### Clash config
<!--
在下方附上 Clash core 脱敏后配置文件的内容
Paste the Clash core configuration below.
-->

<details>
  <summary>config.yaml</summary>

````yaml
port: 7890                                                                                                                                                                                                         
socks-port: 7891                                                                                                                                                                                                   
redir-port: 7892                                                                                                                                                                                                   
allow-lan: false                                                                                                                                                                                                   
mode: Rule                                                                                                                                                                                                         
log-level: silent                                                                                                                                                                                                  
external-controller: '127.0.0.1:9090'                                                                                                                                                                              
secret: '1234' 
````

</details>

### Clash log
<!--
在下方附上 Clash Core 的日志，log level 使用 DEBUG
Paste the Clash core log below with the log level set to `DEBUG`.
-->
```
……
```

### 环境 Environment

* 操作系统 (the OS that the Clash core is running on)
clash部署环境为Ubuntu18.04
手机为ios系统
* 网路环境或拓扑 (network conditions/topology)
机器部署在局域网中，和手机相同的网段。


### 说明 Description

<!--
请详细、清晰地表达你要提出的论述，例如这个问题如何影响到你？你想实现什么功能？
-->

内网一台机器部署了Clash，手机想通过lan来连接这台Clash服务进行FQ，ios在wifi中配置了http代理后，其他网站都正常访问，但是QQ音乐一直不能使用。

### 更多信息 More Information
![image](https://user-images.githubusercontent.com/21277644/122661114-9726f600-d1b9-11eb-9eaf-a2a60b607584.png)

![image](https://user-images.githubusercontent.com/21277644/122661152-ea994400-d1b9-11eb-87a5-cdc3cd201b0f.png)



![image](https://user-images.githubusercontent.com/21277644/122661107-85455300-d1b9-11eb-8910-1473556e63ba.png)
