### ISSUE TITLE
Vmess 无法代理

### ISSUE THREAD

**Issue by eromoe** [Dreamacro/clash#1453]
我的v2rayN 客户端代理完全没问题
![image](https://user-images.githubusercontent.com/3938751/123261286-24a37680-d529-11eb-9175-97f94fa6d019.png)

配置到clash 里头，就完全无法代理
配置减到最少了，还是不行，折腾了2个小时，一点头绪都没有，
```
mixed-port: 7890
allow-lan: false
external-controller: 127.0.0.1:9090
secret: ""
proxies:
  - name: test
    type: vmess
    server: xxxxxxxxxxxxxxx
    port: "443"
    uuid: xxxxxxxxxxxxxxxxxxxx
    alterId: 0
    cipher: auto
    tls: true
    network: ws
    ws-path: /hello
    ws-headers:
      Host: xxxxxxxxxxxxxxxxxxx
proxy-groups:
  - name: PROXY
    type: select
    proxies:
      - test
```

另外我也配置了一个ss 的链接，同样无法运行，ss 客户端却可以。
