### ISSUE TITLE
关于github.io被isp污染后如何解决？

### ISSUE THREAD

**Issue by sqlpxc** [Dreamacro/clash#1459]
# 已知的解决方案(对于我来说)

> 1. 使用fake-ip
> 2. 打开system proxy
> 3. 假如在redir模式下，可以设置nameserver为DNS over TLS解决

# 我的疑问
因为npx和system proxy有一些冲突所以我不启用
## 在redir的情况下，为什么fallback不能用？
我设置nameserver为`223.5.5.5`，fallback为`tls://dns.rubyfish.cn:853`发现并不能正确访问，但是如果把nameserver设置为`tls://dns.rubyfish.cn:853`就可以正常访问了，不是在判断不为CN的情况下会使用fallback的值吗？为什么被解析为127.0.0.1时不会使用fallback的请求结果

**Comment by Dreamacro** [comment]
是路由器还是本机使用 Linux？

目前 DNS 请求是不是都走 Clash 的 DNS Server？

DNS 可以强行指定 domain 走 fallback dns:
```yaml
fallback-filter:
    geoip: true
    ipcidr:
      # - 240.0.0.0/4
    # domain:
    #   - '+.google.com'
    #   - '+.facebook.com'
    #   - '+.youtube.com'
```

**Comment by sqlpxc** [comment]
我使用的是cfw在本机使用，dns请求确实走clash，我只是想知道为什么github.io被污染为127.0.0.1时不会使用fallback结果（我可以确定我的github.io被污染为127.0.0.1）
我的配置在如下情况：
![图片](https://user-images.githubusercontent.com/38583139/123600482-4ce0ed00-d829-11eb-989b-a824a3612efc.png)
但是nslookup为:
![图片](https://user-images.githubusercontent.com/38583139/123600661-7863d780-d829-11eb-9a4c-46d427e1cffd.png)
但是当我修改为：
![图片](https://user-images.githubusercontent.com/38583139/123601130-e3ada980-d829-11eb-9aca-8e5fa0a8796c.png)
nslookup此时变为:
![图片](https://user-images.githubusercontent.com/38583139/123601175-f3c58900-d829-11eb-903d-62236b2e1885.png)

**Comment by sqlpxc** [comment]
我在代码中有看到这样的一行代码：
![图片](https://user-images.githubusercontent.com/38583139/123601430-4010c900-d82a-11eb-857a-b0ccd5c0594c.png)
所以我猜测是否是因为127.0.0.1的判断为空导致的，但是我不是很确定。

**Comment by Dreamacro** [comment]
fallback-filter 里有个 domain 的选项，可以有域名的通配。。

**Comment by sqlpxc** [comment]
我知道有这个选项，但是我就是想知道默认情况下为什么不行？

**Comment by Dreamacro** [comment]
这个 IsoCode 为空是一个「LAN」的 hack，在 mmdb 数据库中，内网地址的 IsoCode 为空。

这个 hack 会在 go 1.17 出来的时候被新的 IsPrivate() 替换。

所以这里的逻辑实际上是：当结果为内网或者为 CN 地址时，不会被 filter

**Comment by sqlpxc** [comment]
那被污染为内网地址那岂不是只能手动配置（像github.io这样）即使是fake-ip也要配置域名，要维护一个域名表岂不是相当麻烦emmmm

**Comment by sqlpxc** [comment]
感觉应该在判断为内网ip时，也要再请求一次fallback，然后以fallback的结果为准才比较符合逻辑。。。（

**Comment by sqlpxc** [comment]
话说clash有没有dns缓存？

**Comment by Dreamacro** [comment]
还可以按 cidr 做 fallback，我就是这么做的

```yaml
fallback-filter:
  geoip: false
  ipcidr:
    - 0.0.0.0/32
  listen: 0.0.0.0:53
  nameserver:
    - 192.168.1.1
    - 192.168.88.1
  fallback:
    - https://doh.pub/dns-query
```

> 感觉应该在判断为内网 ip 时，也要再请求一次 fallback，然后以 fallback 的结果为准才比较符合逻辑……（

不能，因为通常情况下 nameserver 里的配置会包含系统 dns server，比如公司或者家里有特殊的域名解析，如果 fallback 到 DoT 会导致内网域名直接失效

> 话说 clash 有没有 dns 缓存？

当然有
