### ISSUE TITLE
[Bug] Clash 重启后 url-test 和 fallback 没有立即测速

### ISSUE THREAD

**Issue by ihotte** [Dreamacro/clash#1463]
Clash 重启后 url-test 和 fallback 没有立即测速，此时如果这两个组的第一个节点不可用将导致从 clash 启动后到 interval 参数的这段时间内无法正常代理

```
proxy-groups:
-
  name: "海外"
  type: select
  proxies:
    - "低延迟"
    - "高可用"

-
  name: "低延迟"
  type: url-test
  lazy: false
  url: 'http://www.gstatic.com/generate_204'
  interval: 250
  tolerance: 80
  proxies:
    ...

-
  name: "高可用"
  type: fallback
  lazy: false
  url: 'http://www.gstatic.com/generate_204'
  interval: 300
  proxies:
    ...
```
