### ISSUE TITLE
[Bug] type: fallback无法跳过失效的trojan节点

### ISSUE THREAD

**Issue by onlyJinx** [Dreamacro/clash#1466]
------------------------------------------------------------------

### Clash config

```yaml
port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: debug
external-controller: 127.0.0.1:9090
cfw-bypass:
  - qq.com
  - localhost
proxies:
  - name: "trojan1"
    type: trojan
    server: www.baidu.com
    port: 443
    password: yourpsk
  - name: Trojan-gRPC_
    server: xxxxxx
    port: 443
    type: trojan
    password: "xxxxxxxxxxxxxx"
    network: grpc
    sni: xxxxxxxxxxxxxxx
    udp: true
    grpc-opts:
      grpc-service-name: "xxxx"
proxy-groups:
  - name: "fallback-auto"
    type: fallback
    proxies:
      - trojan1
      - Trojan-gRPC_
    url: 'http://www.gstatic.com/generate_204'
    interval: 300

rules:
  - MATCH,fallback-auto
<details>
  <summary>config.yaml</summary>
```

</details>

### Clash log

```
time="2021-06-30T22:16:32+08:00" level=info msg="[TCP] 127.0.0.1:6856 --> www.baidu.com match Match() using fallback-auto[trojan1]"
time="2021-06-30T22:16:32+08:00" level=info msg="[TCP] 127.0.0.1:6571 --> www.baidu.com match Match() using fallback-auto[trojan1]"
time="2021-06-30T22:16:32+08:00" level=info msg="[TCP] 127.0.0.1:3370 --> www.baidu.com match Match() using fallback-auto[trojan1]"
time="2021-06-30T22:16:32+08:00" level=info msg="[TCP] 127.0.0.1:1855 --> www.baidu.com match Match() using fallback-auto[trojan1]"
time="2021-06-30T22:16:32+08:00" level=info msg="[TCP] 127.0.0.1:13880 --> beacons.gcp.gvt2.com match Match() using fallback-auto[trojan1]"
time="2021-06-30T22:16:32+08:00" level=info msg="[TCP] 127.0.0.1:10204 --> beacons.gcp.gvt2.com match Match() using fallback-auto[trojan1]"
time="2021-06-30T22:16:38+08:00" level=info msg="[TCP] 127.0.0.1:10206 --> v10.events.data.microsoft.com match Match() using fallback-auto[trojan1]"
time="2021-06-30T22:16:38+08:00" level=info msg="[TCP] 127.0.0.1:11044 --> github.com match Match() using fallback-auto[trojan1]"
time="2021-06-30T22:16:38+08:00" level=info msg="[TCP] 127.0.0.1:13386 --> github.com match Match() using fallback-auto[trojan1]"
time="2021-06-30T22:16:38+08:00" level=info msg="[TCP] 127.0.0.1:10580 --> google.com match Match() using fallback-auto[trojan1]"
time="2021-06-30T22:16:38+08:00" level=info msg="[TCP] 127.0.0.1:11085 --> beacons.gcp.gvt2.com match Match() using fallback-auto[trojan1]"
time="2021-06-30T22:16:38+08:00" level=info msg="[TCP] 127.0.0.1:10411 --> beacons.gvt2.com match Match() using fallback-auto[trojan1]"
time="2021-06-30T22:16:38+08:00" level=info msg="[TCP] 127.0.0.1:1856 --> beacons.gcp.gvt2.com match Match() using fallback-auto[trojan1]"
time="2021-06-30T22:16:38+08:00" level=info msg="[TCP] 127.0.0.1:14622 --> google.com match Match() using fallback-auto[trojan1]"
time="2021-06-30T22:16:38+08:00" level=info msg="[TCP] 127.0.0.1:5232 --> beacons.gvt2.com match Match() using fallback-auto[trojan1]"
time="2021-06-30T22:16:38+08:00" level=info msg="[TCP] 127.0.0.1:13977 --> beacons.gcp.gvt2.com match Match() using fallback-auto[trojan1]"
time="2021-06-30T22:16:38+08:00" level=info msg="[TCP] 127.0.0.1:13138 --> beacons.gcp.gvt2.com match Match() using fallback-auto[trojan1]"
time="2021-06-30T22:16:38+08:00" level=info msg="[TCP] 127.0.0.1:7915 --> beacons.gcp.gvt2.com match Match() using fallback-auto[trojan1]"
time="2021-06-30T22:16:38+08:00" level=info msg="[TCP] 127.0.0.1:12849 --> beacons.gcp.gvt2.com match Match() using fallback-auto[trojan1]"
time="2021-06-30T22:16:38+08:00" level=info msg="[TCP] 127.0.0.1:1857 --> beacons2.gvt2.com match Match() using fallback-auto[trojan1]"
time="2021-06-30T22:16:38+08:00" level=info msg="[TCP] 127.0.0.1:13703 --> beacons2.gvt2.com match Match() using fallback-auto[trojan1]"
time="2021-06-30T22:16:38+08:00" level=info msg="[TCP] 127.0.0.1:3716 --> beacons.gvt2.com match Match() using fallback-auto[trojan1]"
time="2021-06-30T22:16:38+08:00" level=info msg="[TCP] 127.0.0.1:5268 --> beacons.gvt2.com match Match() using fallback-auto[trojan1]"
time="2021-06-30T22:16:38+08:00" level=info msg="[TCP] 127.0.0.1:5141 --> beacons3.gvt2.com match Match() using fallback-auto[trojan1]"
time="2021-06-30T22:16:38+08:00" level=info msg="[TCP] 127.0.0.1:6014 --> beacons3.gvt2.com match Match() using fallback-auto[trojan1]"
time="2021-06-30T22:16:38+08:00" level=info msg="[TCP] 127.0.0.1:5170 --> beacons2.gvt2.com match Match() using fallback-auto[trojan1]"
time="2021-06-30T22:16:38+08:00" level=info msg="[TCP] 127.0.0.1:1858 --> beacons2.gvt2.com match Match() using fallback-auto[trojan1]"
time="2021-06-30T22:16:38+08:00" level=info msg="[TCP] 127.0.0.1:1858 --> beacons4.gvt2.com match Match() using fallback-auto[trojan1]"
time="2021-06-30T22:16:38+08:00" level=info msg="[TCP] 127.0.0.1:5142 --> beacons4.gvt2.com match Match() using fallback-auto[trojan1]"
……
```

### 环境 Environment

* 操作系统 (the OS that the Clash core is running on)
……
* 网路环境或拓扑 (network conditions/topology)
……
* iptables，如果适用 (if applicable)
……
* ISP 有没有进行 DNS 污染 (is your ISP performing DNS pollution?)
……
* 其他 (any other information that would be useful)
……

### 说明 Description

想用fallback绕过失效的节点，但是好像没有打到我的预期，配置有两个节点，都是trojan，第一个是失效的，我使用的时候发现clash并没有跳过去这个失效的节点。是我配置的问题吗？

### 重现问题的具体布骤 Steps to Reproduce

1. [First Step]
2. [Second Step]
3. ……

**我预期会发生……？**

**实际上发生了什么？**
