### ISSUE TITLE
[Bug] 请问新版本的配置怎么才能支持ws的v2ray?

### ISSUE THREAD

**Issue by jaychoubaby** [Dreamacro/clash#1469]
### Clash config

<details>
  <summary>config.yaml</summary>

这是之前旧的版本写法，可以正常使用：

```yaml
- name: "jaychou"
    type: vmess
    server: jaychou.com
    port: 443
    uuid: 729kjb42-cb9c-4ca1-811a-d0e6jsiie6d4
    alterId: 123
    cipher: auto
    tls: true
    network: ws
    ws-path: /abc
    ws-headers:
      Host: jaychou.com
```

这是新版本写法，无法使用：

```yaml
- { name: jaychou, type: vmess, server: jaychou.com, port: '443', uuid: 729kjb42-cb9c-4ca1-811a-d0e6jsiie6d4, alterId: 123, cipher: auto, udp: false, tls: true, network: ws, ws-path: '/abc', ws-headers: { host: 'jaychou.com'}}
```
</details>

### Clash log

```
没有错误日志，也可以显示节点，但是无法使用
```

### 环境 Environment

* 操作系统 (the OS that the Clash core is running on)
macos  windows10

### 说明 Description

麻烦帮忙看一下，谢谢。
