### ISSUE TITLE
[BUG] Aria2在启用tun的模式下无法走代理

### ISSUE THREAD

**Issue by sqlpxc** [Dreamacro/clash#1470]
------------------------------------------------------------------

### Clash config

<details>
  <summary>config.yaml</summary>

```yaml
mixin: # object
  dns:
    enable: true
    enhanced-mode: redir-host # redir-host或者fake-ip
    nameserver:
      - 192.168.3.1
      - 114.114.114.114
      - 223.5.5.5
    fallback:
      - tls://dns.rubyfish.cn:853
    fallback-filter:
      geoip: true
      ipcidr:
        - 127.0.0.1/32
        - 0.0.0.0/32
      domain:
        - '+.github.io'
    fake-ip-filter:
      - "dns.msftncsi.com"
      - "www.msftncsi.com"
      - "www.msftconnecttest.com"
# interface-name: WLAN # 出口网卡名称，或者使用下方的自动检测
  tun:
    enable: true
    stack: gvisor
    dns-hijack:
      - 198.18.0.2:53
    macOS-auto-route: true
    macOS-auto-detect-interface: true # 自动检测出口网卡

```

</details>

### 环境 Environment

* 操作系统 (the OS that the Clash core is running on)
windows 10 CFW

### Aria2报错如图

![图片](https://user-images.githubusercontent.com/38583139/124352759-f6aee800-dc34-11eb-99b4-ff148dcf56a2.png)
