### ISSUE TITLE
[Bug] windows 10 下 无法上网，提示route ip+net: no such network interface

### ISSUE THREAD

**Issue by nkta3m** [Dreamacro/clash#1478]
windows 10 下使用 clash x64 1.6版本
------------------------------------------------------------------

### Clash config

<details>
  <summary>config.yaml</summary>

```yaml
# HTTP(S) and SOCKS5 共用端口
mixed-port: 1080

# 允许局域网的连接（可用来共享代理）
allow-lan: false

# 规则模式：Rule（规则） / Global（全局代理）/ Direct（全局直连）
mode: Rule

log-level: silent

# RESTful API for clash
external-controller: 127.0.0.1:9090
external-ui: yacd

# RESTful API 的口令 (可选)
secret: ""

# 出站网卡接口
interface-name: en0

# 实验性功能
experimental:
  ignore-resolve-fail: true # 忽略 DNS 解析失败，默认值为 true


# DNS 设置
dns:
  enable: false
  ipv6: false
  listen: ':53'
  default-nameserver:
    - 114.114.114.110
    - 185.228.168.168
  enhanced-mode: fake-ip
#   enhanced-mode: redir-host
  # 如果你不知道这个参数的作用，请勿修改
  fake-ip-range: '198.18.0.1/16'
  fake-ip-filter:

  nameserver:
    - 114.114.114.114
    - https://doh.pub/dns-query
    - https://dns.alidns.com/dns-query

  fallback-filter:
    geoip: false
    ipcidr:
      - 240.0.0.0/4
      - 0.0.0.0/32
proxies:
# Trojan
- name: "gcp-hk-c"

```

</details>

### Clash log

```
dial DIRECT (match DomainSuffix/firefox.com) to detectportal.firefox.com error: route ip+net: no such network interface
```

### 环境 Environment

* 操作系统 (the OS that the Clash core is running on)
windows 10
* 网路环境或拓扑 (network conditions/topology)
无
* iptables，如果适用 (if applicable)
无
* ISP 有没有进行 DNS 污染 (is your ISP performing DNS pollution?)
无
* 其他 (any other information that would be useful)
……

### 重现问题的具体布骤 Steps to Reproduce

1. [First Step]
2. [Second Step]
3. ……

**我预期会发生……？**

**实际上发生了什么？**
