### ISSUE TITLE
[Feature] 建议将 proxy-providers 和 rule-providers 两个字段加入到 clash 的启动参数中，以增加灵活性。

### ISSUE THREAD

**Issue by hadkins1** [Dreamacro/clash#1481]
### 说明 Description

proxy-providers 和 rule-providers 两个特性非常方便，可以避免每次从托管服务器更新 yaml 文件时手动修改来添加自己的本地代理和规则。但在使用中遇到的问题是，通常从托管服务器得到的 yaml 文件中并没有这两个字段，导致想要启动这两个功能仍然需要手动去修改 yaml 文件，添加这两个字段以跟本地文件进行关联，这样违背了这两个特性的设计初衷，并没有方便多少。即使从服务端修改，在他们的 yaml 文件中提供这两个字段，其本地规则和代理文件的路径和文件名也都是写死在 yaml 文件中的，缺乏灵活性。

### 可能的解决方案 Possible Solution

建议将 proxy-providers 和 rule-providers 两个字段加入到 clash 的启动参数中，以增加灵活性以及使用便利性。
例如：
`
clash -d ~/.config/clash -f ~/.config/clash/config.yaml -ext-ui ~/.config/clash/dash-board -proxy-providers ~/.config/clash/localproxies.txt -rule-providers ~/.config/clash/localrules.txt
`

**Comment by Dreamacro** [comment]
从其他文件合并 proxy provider 和 rule provider 并没有什么意义。因为实际上你还是无法控制主配置文件中 proxy group 里使用 provider 的 name，rules 里也没法控制是否使用 rule provider。

正确的做法其实是自己写主配置文件，如果你的「托管服务器」支持节点筛选地区（可以是一个完整的 clash 配置文件，直接支持 provider 的或许不多，但支持地区筛选的应该不少），由于 proxy provider 里需要的字段是 proxies，所以可以把一个正常的 clash 配置文件作为一个 provider 来实现所谓的节点和规则分离

```yaml
proxy-providers:
  hk:
    type: http
    url: "server/path?filter=hk"
    interval: 3600
    path: ./provider1.yaml
    health-check:
      enable: true
      interval: 600
      # lazy: true
      url: http://www.gstatic.com/generate_204
```
