### ISSUE TITLE
[BUG] domain 类型 rule provider 中的规则未匹配

### ISSUE THREAD

**Issue by tty7tyil** [Dreamacro/clash#1487]
### Clash config

<details>
  <summary>config.yaml</summary>

```yaml
mode: "rule"

dns:
  enable: true
  listen: ":53"
  enhanced-mode: "redir-host"

  default-nameserver:
    - "223.5.5.5:53"
    - "1.0.0.1:53"

  nameserver:
    - "https://rubyfish.cn/dns-query"
  fallback:
    - "https://dns.rubyfish.cn/dns-query"

  fallback-filter:
    geoip: true

rule-providers:
  proxy-domain:
    behavior: "domain"
    path: "rule-provider_proxy-domain"

rules:
  - "RULE-SET, proxy-domain, Proxy"
  - "GEOIP, CN, DIRECT"
  - "MATCH, Final"
```

</details>

<details>
  <summary>rule-provider_proxy-domain</summary>

``` yaml
payload:
  - "android.clients.google.com"
  - "+.android.clients.google.com"
  - "+.google.com"
```

</details>

### Clash log

```
   Info: [APP] Logcat level: debug
   Info: [APP] request force GC
   Info: [UDP] x.x.x.x:p --> android.clients.google.com match Match() using Final[DIRECT]
Warning: [TCP] dial Final (match Match/) to android.clients.google.com error: dial tcp4 x.x.x.x:p: i/o timeout
  Debug: Proxy UDP is not supported
```

### 环境 Environment

* 操作系统: Android 11, Clash for Android
* ISP 有没有进行 DNS 污染: True

### 重现问题的具体布骤 Steps to Reproduce

1. 启动 Clash for Android
2. 打开 Google Play Store
3. 观察 log

**我预期会发生……？**  
`android.clients.google.com` 匹配到 `RULE-SET, proxy-domain, Proxy` 并进入代理

**实际上发生了什么？**  
三种写法全部被忽略，匹配到最后的 `MATCH`

### 更多信息 More Information

若不使用 rule provider，直接在 rules 里写 `DOMAIN-SUFFIX, google.com, Proxy` 则匹配无问题。  
其它流量如浏览器访问 `google.com` 可正常匹配到 `RULE-SET, proxy-domain, Proxy`。

若更改 rule provider 类型为 classical，内容改写为 `  - "DOMAIN-SUFFIX, google.com"` 则匹配也无问题，仅在类型为 domain 时可复现。
