### ISSUE TITLE
[Bug]Windows 下TUN如果stack使用system仍然显示无法联网

### ISSUE THREAD

**Issue by Solitaryender** [Dreamacro/clash#1488]
------------------------------------------------------------------

### Clash config

<details>
  <summary>config.yaml</summary>

```yaml
mixin: 
  dns:
    enable: true
    enhanced-mode: fake-ip 
    use-hosts: true
    default-nameserver:
      - 223.5.5.5 
      - 208.67.222.222 
      - 1.0.0.1 
    fake-ip-range: 198.18.0.1/16 
    fake-ip-filter: 
      - "dns.msftncsi.com"
      - "www.msftncsi.com"
      - "www.msftconnecttest.com"
    nameserver: 
      - https://dns.alidns.com/dns-query
      - https://dns.pub/dns-query 
    fallback: 
      - https://freedns.controld.com/p0 
      - https://cloudflare-dns.com/dns-query 
      - https://doh.dns.sb/dns-query 
    fallback-filter:
      geoip: true 
      ip-cidr: 
        - 240.0.0.0/4
        - 127.0.0.1/8
        - 0.0.0.0/32
      domain: 
        - "+.github.com"
        - "+.youtube.com"
    nameserver-policy:
      "dns.msftncsi.com": "https://dns.alidns.com/dns-query"
      "www.msftncsi.com": "https://dns.alidns.com/dns-query"
      "www.msftconnecttest.com": "https://dns.alidns.com/dns-query"
  tun: {
     enable: true,
     stack: system,
     "dns-hijack": ["198.18.0.2:53",],
     "auto-route": true,
     "auto-detect-interface": true
    }
```
</details>

### Clash log

```
time="2021-07-13T17:16:18+08:00" level=info msg="Mixed(http+socks5) proxy listening at: 127.0.0.1:7890"
time="2021-07-13T17:16:18+08:00" level=info msg="RESTful API listening at: 127.0.0.1:5315"
time="2021-07-13T17:16:23+08:00" level=debug msg="[DNS] push.services.mozilla.com --> 54.69.123.126"
time="2021-07-13T17:17:39+08:00" level=debug msg="Generate GUID: {330EAEF8-7578-5DF2-D97B-8DADC0EA85CB}"
time="2021-07-13T17:17:39+08:00" level=info msg="[Wintun] CreateAdapter: Creating adapter"
time="2021-07-13T17:17:39+08:00" level=info msg="[Wintun] SelectDriver: Using existing driver 0.11"
time="2021-07-13T17:17:40+08:00" level=info msg="Tun Proxy listening at: Clash(198.18.0.1)"
time="2021-07-13T17:17:40+08:00" level=debug msg="[Stack] Failed to dummy bind, retry in 1 second... (1/10)"
time="2021-07-13T17:17:41+08:00" level=debug msg="[Stack] Failed to dummy bind, retry in 1 second... (2/10)"
time="2021-07-13T17:17:42+08:00" level=debug msg="[Stack] Failed to dummy bind, retry in 1 second... (3/10)"
time="2021-07-13T17:17:43+08:00" level=debug msg="[Stack] Failed to dummy bind, retry in 1 second... (4/10)"
time="2021-07-13T17:17:44+08:00" level=debug msg="[Stack] Address %!w(net.IP=[198 18 0 1]) ready for bind"
time="2021-07-13T17:17:46+08:00" level=debug msg="[DNS] resolve detectportal.firefox.com error: couldn't find ip"
time="2021-07-13T17:17:46+08:00" level=debug msg="[DNS] resolve detectportal.firefox.com error: couldn't find ip"
time="2021-07-13T17:17:46+08:00" level=debug msg="[DNS] resolve detectportal.firefox.com error: couldn't find ip"
time="2021-07-13T17:17:46+08:00" level=debug msg="[DNS] resolve detectportal.firefox.com error: couldn't find ip"
time="2021-07-13T17:17:46+08:00" level=debug msg="[Rule] find process name Process error: process not found"
time="2021-07-13T17:17:46+08:00" level=debug msg="[Rule] find process name Process error: process not found"
time="2021-07-13T17:17:46+08:00" level=info msg="[TCP] 127.0.0.1:7748 --> detectportal.firefox.com match Match() using FirstChoice[Relay]"
time="2021-07-13T17:17:46+08:00" level=info msg="[TCP] 127.0.0.1:7708 --> detectportal.firefox.com match Match() using FirstChoice[Relay]"
time="2021-07-13T17:17:46+08:00" level=info msg="[TCP] 127.0.0.1:7747 --> detectportal.firefox.com match Match() using FirstChoice[Relay]"
time="2021-07-13T17:17:46+08:00" level=info msg="[TCP] 127.0.0.1:7709 --> detectportal.firefox.com match Match() using FirstChoice[Relay]"
```

### 环境 Environment

* 操作系统 (the OS that the Clash core is running on)
Windows
* 网路环境或拓扑 (network conditions/topology)
#……
* iptables，如果适用 (if applicable)
#……
* ISP 有没有进行 DNS 污染 (is your ISP performing DNS pollution?)
有
* 其他 (any other information that would be useful)
#……

### 重现问题的具体布骤 Steps to Reproduce

1. 设置Clash for Windows Mixin如所给配置，tun的stack属性设置为system（事先已经做好tun的开启的准备）
2. 开启Mixin以开启tun（nameserver-policy是为了tun网卡连接检测）

**我预期会发生……？**

根据GithubWiki，Windows下的clash的tun可以设置stack为system
![图片](https://user-images.githubusercontent.com/65836154/125423341-df713f94-36a2-4c1d-9ef7-d6b9c0e7b912.png)

那么Clash理应正常联网，并且网络显示Internet连接，就如同stack设置为gvisor的情况一样
![图片](https://user-images.githubusercontent.com/65836154/125423766-e2ea6409-076c-4ac9-a036-5bd032ed8621.png)
![图片](https://user-images.githubusercontent.com/65836154/125424961-ef4d0c27-debe-4daa-a6bc-14d6b183dded.png)

**实际上发生了什么？**

![图片](https://user-images.githubusercontent.com/65836154/125423627-b1327b8d-f1c4-4076-82f1-6cb7e68b8e5a.png)
如图，tun的stack设置为system情况下检测TUN的网络连接为断开
但是Clash仍然可以正常联网
![图片](https://user-images.githubusercontent.com/65836154/125425307-d570550c-f653-48e8-8ab2-8ad09ee7f1bd.png)
但是请求并不会被TUN截取，就好像TUN不存在一样
