### ISSUE TITLE
GeoIP没有分流国内的网站[Bug]

### ISSUE THREAD

**Issue by adrianzhang** [Dreamacro/clash#1501]
------------------------------------------------------------------

### Clash config

<details>
  <summary>config.yaml</summary>

```yaml
port: 7890
socks-port: 7891
redir-port: 7892
allow-lan: true
bind-address: '192.168.1.2'
mode: rule
log-level: debug
ipv6: false
external-controller: 192.168.1.2:19090
external-ui: folder
interface-name: eth0
hosts:
  # '*.clash.dev': 127.0.0.1
  # '.dev': 127.0.0.1
  # 'alpha.clash.dev': '::1'
dns:
  enable: false
  listen: 0.0.0.0:53
  # ipv6: false # when the false, response to AAAA questions will be empty
  # These nameservers are used to resolve the DNS nameserver hostnames below.
  # Specify IP addresses only
  default-nameserver:
    - 114.114.114.114
    - 8.8.8.8
  enhanced-mode: redir-host # or fake-ip
  fake-ip-range: 198.18.0.1/16 # Fake IP addresses pool CIDR
  # use-hosts: true # lookup hosts and return IP record

  # Hostnames in this list will not be resolved with fake IPs
  # i.e. questions to these domain names will always be answered with their
  # real IP addresses
  # fake-ip-filter:
  #   - '*.lan'
  #   - localhost.ptlogin2.qq.com

  # Supports UDP, TCP, DoT, DoH. You can specify the port to connect to.
  # All DNS questions are sent directly to the nameserver, without proxies
  # involved. Clash answers the DNS question with the first result gathered.
  nameserver:
    - 114.114.114.114 # default value
    - 8.8.8.8 # default value
    - tls://dns.rubyfish.cn:853 # DNS over TLS
    - https://1.1.1.1/dns-query # DNS over HTTPS
  # When `fallback` is present, the DNS server will send concurrent requests
  # to the servers in this section along with servers in `nameservers`.
  # The answers from fallback servers are used when the GEOIP country
  # is not `CN`.
  # fallback:
  #   - tcp://1.1.1.1
  # If IP addresses resolved with servers in `nameservers` are in the specified
  # subnets below, they are considered invalid and results from `fallback`
  # servers are used instead.
  #
  # IP address resolved with servers in `nameserver` is used when
  # `fallback-filter.geoip` is true and when GEOIP of the IP address is `CN`.
  #
  # If `fallback-filter.geoip` is false, results from `nameserver` nameservers
  # are always used if not match `fallback-filter.ipcidr`.
  #
  # This is a countermeasure against DNS pollution attacks.
  fallback-filter:
    geoip: true
    ipcidr:
      # - 240.0.0.0/4
    # domain:
    #   - '+.google.com'
    #   - '+.facebook.com'
    #   - '+.youtube.com'
proxies:
  - name: "xxx"
    type: vmess
    server: xxx.com
    port: 443
    uuid: xxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    alterId: 32
    cipher: auto
    udp: true
    tls: true
    # skip-cert-verify: true
    # servername: example.com # priority over wss host
    network: ws
    ws-path: /xx
    # ws-headers:
    #   Host: v2ray.com
  - name: "xxxxxxx"
    type: vmess
    server: xxxxxx.com
    port: 443
    uuid: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    alterId: 32
    cipher: auto
    udp: true
    tls: true
    # skip-cert-verify: true
    # servername: example.com # priority over wss host
    network: ws
    ws-path: /xx
    # ws-headers:
    #   Host: v2ray.com
  - name: "xxxxxxxxx"
    type: vmess
    server: xxxxxxxxxxxxx.com
    port: 443
    uuid: xxxxxxxxxxxxxxxxxxxxxxxxxxxx
    alterId: 32
    cipher: auto
    udp: true
    tls: true
    # skip-cert-verify: true
    # servername: example.com # priority over wss host
    network: ws
    ws-path: /xxxxx

  - name: "socks"
    type: socks5
    server: 127.0.0.1
    port: xxxxx
    udp: true

  # Trojan
  - name: "trojan"
    type: trojan
    server: xxxxx.com
    port: 443
    password: xxxxxxxxxxxxx
    udp: true
    # sni: example.com # aka server name
    # alpn:
    #   - h2
    #   - http/1.1
    # skip-cert-verify: true
  
proxy-groups:
  # relay chains the proxies. proxies shall not contain a relay. No UDP support.
  # Traffic: clash <-> http <-> vmess <-> ss1 <-> ss2 <-> Internet
  # - name: "relay"
  #   type: relay
  #   proxies:
  #     - http
  #     - vmess
  #     - ss1
  #     - ss2
  # url-test select which proxy will be used by benchmarking speed to a URL.
  - name: "auto"
    type: url-test
    proxies:
      - socks
      - xxxx
      - xxxxxx
      - xxxxxxxx
    tolerance: 150
    url: 'http://www.gstatic.com/generate_204'
    interval: 300
  # fallback selects an available policy by priority. The availability is tested by accessing an URL, just like an auto url-test group.
  - name: "fallback-auto"
    type: fallback
    proxies:
      - trojan
      - xxx
      - socks
      - xxxxx
      - xxxxxxx
    url: 'http://www.gstatic.com/generate_204'
    interval: 300
  # load-balance: The request of the same eTLD+1 will be dial to the same proxy.
  - name: "load-balance"
    type: load-balance
    proxies:
      - xxx
      - socks
      - xxxxxx
    url: 'http://www.gstatic.com/generate_204'
    interval: 300
  # select is used for selecting proxy or proxy group
  # you can use RESTful API to switch proxy is recommended for use in GUI.
  # - name: Proxy
  #   type: select
  #   proxies:
  #     - ss1
  #     - ss2
  #     - vmess1
  #     - auto

  # - name: UseProvider
  #   type: select
  #   use:
  #     - provider1
  #   proxies:
  #     - Proxy
  #     - DIRECT
proxy-providers:
  # provider1:
  #   type: http
  #   url: "url"
  #   interval: 3600
  #   path: ./provider1.yaml
  #   health-check:
  #     enable: true
  #     interval: 600
  #     url: http://www.gstatic.com/generate_204
  # test:
  #   type: file
  #   path: /test.yaml
  #   health-check:
  #     enable: true
  #     interval: 36000
  #     url: http://www.gstatic.com/generate_204
rules:
  - DOMAIN-SUFFIX,xxx.com（VPS1）,DIRECT
  - DOMAIN-SUFFIX,xxxxxx.com（VPS2）,DIRECT
  - DOMAIN-SUFFIX,xxxxxxxx.com（VPS3）,DIRECT
  - DOMAIN-SUFFIX,xxxxxxxxxxxxxxxx（VPS4）,DIRECT
  - DOMAIN-SUFFIX,xxxxxxxxxxxxxxxxxxx（VPS5）,DIRECT
  - DOMAIN-SUFFIX,drive.google.com,auto
  - DOMAIN-SUFFIX,youtube.com,auto
  - DOMAIN-SUFFIX,google.com,fallback-auto
  - DOMAIN,google.com,fallback-auto
  - DOMAIN-SUFFIX,ad.com,REJECT
  #- SRC-IP-CIDR,192.168.1.201/32,DIRECT
  # optional param "no-resolve" for IP rules (GEOIP, IP-CIDR, IP-CIDR6)
  - IP-CIDR,127.0.0.0/8,DIRECT
  - IP-CIDR,192.168.0.0/16,DIRECT
  - IP-CIDR,xxx.xxx.xxx.xxx/32,DIRECT
  - IP-CIDR,8.8.8.8/32,fallback-auto
  - IP-CIDR,8.8.4.4/32,fallback-auto
  - IP-CIDR,1.1.1.1/32,fallback-auto
  - GEOIP,CN,DIRECT
  # - DST-PORT,80,DIRECT
  # - SRC-PORT,7777,DIRECT
  # - RULE-SET,apple,REJECT # Premium only
  - MATCH,load-balance
```

</details>

### Clash log

```
（略）全是连接VPS的信息，没有任何match GeoIP信息。
```

### 环境 Environment

* 操作系统 (the OS that the Clash core is running on)
Ubuntu20.04
* 网路环境或拓扑 (network conditions/topology)
作为其他电脑的网关，本机的Gateway是ISP路由器
* iptables，如果适用 (if applicable)
```
sudo iptables -t nat -L
Chain PREROUTING (policy ACCEPT)
target     prot opt source               destination
clash      tcp  --  anywhere             anywhere

Chain INPUT (policy ACCEPT)
target     prot opt source               destination

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination

Chain POSTROUTING (policy ACCEPT)
target     prot opt source               destination

Chain clash (1 references)
target     prot opt source               destination
RETURN     all  --  anywhere             xxx.xxx.xxx.xxx 
RETURN     all  --  anywhere             0.0.0.0/8
RETURN     all  --  anywhere             10.0.0.0/8
RETURN     all  --  anywhere             localhost/8
RETURN     all  --  anywhere             169.254.0.0/16
RETURN     all  --  anywhere             172.16.0.0/12
RETURN     all  --  anywhere             192.168.0.0/16
RETURN     all  --  anywhere             base-address.mcast.net/4
RETURN     all  --  anywhere             240.0.0.0/4
REDIRECT   tcp  --  anywhere             anywhere             redir ports 7892
```

* ISP 有没有进行 DNS 污染 (is your ISP performing DNS pollution?)
自建的DNS，进行国内外分流，国外的走TCP经过本clash代理，国内的指向ISP的DNS。经电脑确认，测试的几个国内网站DNS结果均通过ipinfo查询得知为国内IP
* 其他 (any other information that would be useful)
下载了最新的Country.mmdb（7月12日版），放在/etc/clash文件夹内，config.yaml也在这个文件夹内。
systemd如下：
```
[Unit]
Description=Clash Daemon
After=network.target

[Service]
#Type=simple
User=root
Restart=on-failure
WorkingDirectory=/usr/local/bin
ExecStart=/usr/local/bin/clash -d /etc/clash

[Install]
WantedBy=multi-user.target
```

### 重现问题的具体布骤 Steps to Reproduce

1. 局域网另一台电脑MacOS，设置网关为运行该Clash的Ubuntu机器，DNS为局域网内专门的DNS服务器，带国内外分流解析。
2. 使用Safari或Chrome，访问taobao.com/jd.com/iqiyi.com/bilibili.com等国内网站，Chrome安装ipinfo插件以得知页面所在国
3. 使用Safari时，iqiyi.com是中文，taobao/jd都是国际页面，bilibili是中文，但都比较慢。
4. 使用Chrome时，iqiyi.com也是英文页面，taobao/jd都是国际页面，bilibili中文，ipinfo插件显示4个页面都来自国外。

**我预期会发生……？**

局域网内电脑在访问国内网站的时候，从DNS得到国内IP，TCP请求按本机Gateway的设置，发到运行Clash这个机器，通过iptables NAT表的设置将请求转发Clash，Clash根据IP，match GeoIP内CN条目的都直接连接（也就是转发给ISP路由器）。

**实际上发生了什么？**

访问国内网站，Clash全部给到代理去了，没有match到GeoIP

### 更多信息 More Information
访问chiphell.com是国内页面。
