### ISSUE TITLE
[Bug] tap模式不支持 process name ，tun支持

### ISSUE THREAD

**Issue by debao1996lu** [Dreamacro/clash#1503]
------------------------------------------------------------------

### Clash config

<details>
  <summary>config.yaml</summary>

```yaml
……

port: 7890
socks-port: 7891
redir-port: 7892
allow-lan: false
mode: rule
log-level: silent
external-controller: 127.0.0.1:9090
secret: ""
proxies:
  - name: socks5://127.0.0.1:10808
    type: socks5
    server: 127.0.0.1
    port: "10808"
  - name: http://127.0.0.1:10809
    type: http
    server: 127.0.0.1
    port: "10809"
proxy-groups:
  - name: 选择组
    proxies:
      - http://127.0.0.1:10809
      - socks5://127.0.0.1:10808
    type: select
rules:
  - PROCESS-NAME,wv2ray.exe,DIRECT
  - SRC-IP-CIDR,0.0.0.0/0,选择组
dns:
  enable: true
  enhanced-mode: redir-host
  listen: 0.0.0.0:53
  nameserver:
    - https://223.5.5.5/dns-query
```

</details>

### Clash log

```


……
```

### 环境 Environment

* 操作系统 (the OS that the Clash core is running on)
……windows10 
* 网路环境或拓扑 (network conditions/topology)
……
* iptables，如果适用 (if applicable)
……
* ISP 有没有进行 DNS 污染 (is your ISP performing DNS pollution?)
……
* 其他 (any other information that would be useful)
……

### 说明 Description

tap模式下，走代理本地时process name 规则无效 ，tun模式可以

### 重现问题的具体布骤 Steps to Reproduce

1. [First Step]
2. [Second Step]
3. ……

**我预期会发生……？**

**实际上发生了什么？**
