### ISSUE TITLE
[Bug] dashboard连接页空白，ip地址没有换。请问我哪里做错了

### ISSUE THREAD

**Issue by alexlai97** [Dreamacro/clash#1504]
------------------------------------------------------------------

### Clash config

<details>
  <summary>config.yaml</summary>

```yaml
port: 7890
socks-port: 7891
redir-port: 7892
allow-lan: false
mode: rule
log-level: debug
ipv6: true
external-controller: '127.0.0.1:9090'
secret: "" 

profile:
  # Store the `select` results in $HOME/.config/clash/.cache
  # set false If you don't want this behavior
  # when two different configurations have groups with the same name, the selected values are shared
  store-selected: true

dns:
  enable: true
  nameserver:
    - 1.2.4.8
    - 114.114.114.114
    - 223.5.5.5
    - 8.8.8.8
    - tls://dns.rubyfish.cn:853
  fallback:
    - tls://1.0.0.1:853
    - tls://dns.google:853

proxies:
  - ommited
 
proxy-groups:
- name: "PROXY"
  type: select
  proxies:
    - "US2"
    - "US4"
    - "US5"
    - "DE1"
    - "SG1"
    - "JP4"
    - "KR1"
    - ...
……
```

</details>

### Clash log

I tried setting log-level to "debug", but no messages appeared in clash-dashboard

### 环境 Environment

* 操作系统 (the OS that the Clash core is running on)
Linux (Archlinux)

### 说明 Description
我设置好config，在terminal run
![image](https://user-images.githubusercontent.com/17771269/126708585-12911041-baf1-4229-9945-ff47590c4a67.png)
然后可以在dashboard看到一些proxies，以及他们的ping
![image](https://user-images.githubusercontent.com/17771269/126708368-0ab43610-4723-418b-ae2f-381082a86646.png)
![image](https://user-images.githubusercontent.com/17771269/126708451-70c708ca-43df-487c-abb4-f513a2b7ce2a.png)

但是，
- 我访问https://whatismyipaddress.com/  ，发现还是原来的ip 地址。
- dashboard上日志页是空白的 （即使是log-level: debug)
- dashboard上连接页是空白的

我在dashboard上尝试把代理模式换成全局，但ip也没变。

请问怎么提供iptables，我尝试了下面
![image](https://user-images.githubusercontent.com/17771269/126709125-7dae2858-cbea-4fc7-9459-0670b2c799f8.png)

我还需要提供什么信息吗？感谢
