### ISSUE TITLE
[Bug] dial DIRECT to [host] error: lookup [host]: no such host

### ISSUE THREAD

**Issue by liby** [Dreamacro/clash#1507]
------------------------------------------------------------------

### Clash config

<details>
  <summary>config.yaml</summary>

```yaml
# 2021-07-21 01:00
# Port of HTTP(S) proxy server on the local end
# port: 7890

# Port of SOCKS5 proxy server on the local end
# socks-port: 7891

# Transparent proxy server port for Linux and macOS (Redirect TCP and TProxy UDP)
# redir-port: 7892

# Transparent proxy server port for Linux (TProxy TCP and TProxy UDP)
# tproxy-port: 7893

# HTTP(S) and SOCKS5 server on the same port
# mixed-port: 7893

# authentication of local SOCKS5/HTTP(S) server
# authentication:
#  - "user1:pass1"
#  - "user2:pass2"

# Set to true to allow connections to the local-end server from
# other LAN IP addresses
allow-lan: false

# This is only applicable when `allow-lan` is `true`
# '*': bind all IP addresses
# 192.168.122.11: bind a single IPv4 address
# "[aaaa::a8aa:ff:fe09:57d8]": bind a single IPv6 address
bind-address: '*'

# Clash router working mode
# rule: rule-based packet routing
# global: all packets will be forwarded to a single endpoint
# direct: directly forward the packets to the Internet
mode: Script

# Clash by default prints logs to STDOUT
# info / warning / error / debug / silent
log-level: info

# When set to false, resolver won't translate hostnames to IPv6 addresses
ipv6: false

# RESTful web API listening address
external-controller: 127.0.0.1:9090

# A relative path to the configuration directory or an absolute path to a
# directory in which you put some static web resource. Clash core will then
# serve it at `${API}/ui`.
# external-ui: folder

# Secret for the RESTful API (optional)
# Authenticate by spedifying HTTP header `Authorization: Bearer ${secret}`
# ALWAYS set a secret if RESTful API is listening on 0.0.0.0
# secret: ""

# Outbound interface name
# interface-name: en0

# Static hosts for DNS server and connection establishment (like /etc/hosts)
#
# Wildcard hostnames are supported (e.g. *.clash.dev, *.foo.*.example.com)
# Non-wildcard domain names have a higher priority than wildcard domain names
# e.g. foo.example.com > *.example.com > .example.com
# P.S. +.foo.com equals to .foo.com and foo.com
hosts:
  # '*.clash.dev': 127.0.0.1
  # '.dev': 127.0.0.1
  # 'alpha.clash.dev': '::1'

  # Firebase Cloud Messaging
  'mtalk.google.com': 108.177.125.188
  # Google Dl
  'dl.google.com': 180.163.151.161
  'dl.l.google.com': 180.163.151.161

# DNS server settings
# This section is optional. When not present, the DNS server will be disabled.
dns:
  enable: false
  listen: 0.0.0.0:53
  # ipv6: false # when the false, response to AAAA questions will be empty

  # These nameservers are used to resolve the DNS nameserver hostnames below.
  # Specify IP addresses only
  default-nameserver:
    - 119.29.29.29
    - 1.0.0.1
  enhanced-mode: redir-host # or fake-ip
  fake-ip-range: 198.18.0.1/16 # Fake IP addresses pool CIDR
  # use-hosts: true # lookup hosts and return IP record

  # Hostnames in this list will not be resolved with fake IPs
  # i.e. questions to these domain names will always be answered with their
  # real IP addresses
  fake-ip-filter:
    - '*.lan'
    - localhost.ptlogin2.qq.com
    - '+.srv.nintendo.net'
    - '+.stun.playstation.net'
    - '+.msftconnecttest.com'
    - '+.msftncsi.com'
    - '+.xboxlive.com'
    - 'msftconnecttest.com'
    - 'xbox.*.microsoft.com'

  # Supports UDP, TCP, DoT, DoH. You can specify the port to connect to.
  # All DNS questions are sent directly to the nameserver, without proxies
  # involved. Clash answers the DNS question with the first result gathered.
  nameserver:
    - 119.29.29.29
    - 223.5.5.5
    - tls://dns.rubyfish.cn:853 # DNS over TLS
    - https://1.1.1.1/dns-query # DNS over HTTPS

  # When `fallback` is present, the DNS server will send concurrent requests
  # to the servers in this section along with servers in `nameservers`.
  # The answers from fallback servers are used when the GEOIP country
  # is not `CN`.
  # fallback:
  #   - tcp://1.1.1.1

  # If IP addresses resolved with servers in `nameservers` are in the specified
  # subnets below, they are considered invalid and results from `fallback`
  # servers are used instead.
  #
  # IP address resolved with servers in `nameserver` is used when
  # `fallback-filter.geoip` is true and when GEOIP of the IP address is `CN`.
  #
  # If `fallback-filter.geoip` is false, results from `nameserver` nameservers
  # are always used if not match `fallback-filter.ipcidr`.
  #
  # This is a countermeasure against DNS pollution attacks.
  fallback-filter:
    geoip: true
    ipcidr:
      # - 240.0.0.0/4
    # domain:
    #   - '+.google.com'
    #   - '+.facebook.com'
    #   - '+.youtube.com'

# 服务器节点订阅
proxy-providers:
  AgentList: # Agent 机场订阅链接
    type: http
    url: "https://xxx.yt/ACbDxC2"
    interval: 3600
    path: "./Proxy/agent.yaml" # 不同机场不同命名
    health-check:
      enable: true
      interval: 600
      url: http://www.gstatic.com/generate_204

proxy-groups:
  # 手动选择订阅节点
  - name: "Agent"
    type: select # 亦可使用 fallback 或 load-balance
    use: # 注意此处是「use」
      - AgentList # 这是上面「proxy-providers」的名称

  # url-test 可以自动选择与指定 URL 测速后，延迟最短的服务器
  - name: "AUTO"
    type: url-test
    use:
      - AgentList
    url: 'http://www.gstatic.com/generate_204'
    interval: 300


  # Fallback 比较实用的策略组类型，用于测试服务器节点的可用性，当第一个节点不可用时切换到第二个，以此类推。
  - name: "FALLBACK"
    type: fallback
    use:
      - AgentList
    url: 'http://www.gstatic.com/generate_204'
    interval: 300

  # 代理节点选择
  - name: "PROXY"
    type: select
    proxies:
      - FALLBACK
      - AUTO

  # 白名单模式 PROXY, 黑名单模式 DIRECT, 不知道别动
  - name: "MATCH"
    type: select
    proxies:
      - PROXY
      - DIRECT

  # 国际流媒体服务
  - name: "Streaming"
    type: select
    proxies:
      - PROXY
      # - Ohter proxies

rule-providers:
  Unbreak:
    type: http
    behavior: classical
    path: ./RuleSet/Unbreak.yaml
    url: https://cdn.jsdelivr.net/gh/DivineEngine/Profiles@master/Clash/RuleSet/Unbreak.yaml
    interval: 86400

  Streaming:
    type: http
    behavior: classical
    path: ./RuleSet/StreamingMedia/Streaming.yaml
    url: https://cdn.jsdelivr.net/gh/DivineEngine/Profiles@master/Clash/RuleSet/StreamingMedia/Streaming.yaml
    interval: 86400

  Global:
    type: http
    behavior: classical
    path: ./RuleSet/Global.yaml
    url: https://cdn.jsdelivr.net/gh/DivineEngine/Profiles@master/Clash/RuleSet/Global.yaml
    interval: 86400

  China:
    type: http
    behavior: classical
    path: ./RuleSet/China.yaml
    url: https://cdn.jsdelivr.net/gh/DivineEngine/Profiles@master/Clash/RuleSet/China.yaml
    interval: 86400

  ChinaIP:
    type: http
    behavior: ipcidr
    path: ./RuleSet/Extra/ChinaIP.yaml
    url: https://cdn.jsdelivr.net/gh/DivineEngine/Profiles@master/Clash/RuleSet/Extra/ChinaIP.yaml
    interval: 86400

script:
  code: |
    def main(ctx, metadata):
      if metadata["host"] == "gist.github.com":
        return "PROXY"

      ip = ctx.resolve_ip(metadata["host"]) or metadata["dst_ip"]
      if ip == "":
        return "DIRECT"

      code = ctx.geoip(ip)
      if code == "LAN" or code == "CN":
        return "DIRECT"

      directList = ['ChinaIP', 'Unbreak', 'China']
      for name in directList:
        if ctx.rule_providers[name].match(metadata):
          ctx.log('[China] matched %s' % metadata["host"])
          return "DIRECT"

      if ctx.rule_providers["Streaming"].match(metadata):
        return "Streaming"

      if ctx.rule_providers["Global"].match(metadata):
        return "PROXY"

      return "PROXY" # default policy for requests which are not matched by any other script
```

</details>

### Clash log

```
2021-07-24 13:06:51[warning] [Script] resolve github.com ip failed: lookup github.com: no such host
2021-07-24 13:06:51[warning] [TCP] dial DIRECT to github.com error: lookup github.com: no such host
2021-07-24 13:06:51[warning] [Script] resolve github.com ip failed: lookup github.com: no such host
2021-07-24 13:06:51[warning] [TCP] dial DIRECT to github.com error: lookup github.com: no such host
```

### 环境 Environment

* 操作系统 (the OS that the Clash core is running on)
  - macOS 10.15.7 (19H524)

* 网路环境或拓扑 (network conditions/topology)
  - Internet -> Router -> Devices
 
* iptables，如果适用 (if applicable)
  - 无配置

* ISP 有没有进行 DNS 污染 (is your ISP performing DNS pollution?)

在那一段时间 nslookup 也找不到
```
❯ nslookup
> github.com
Server:		192.168.50.1
Address:	192.168.50.1#53

** server can't find github.com: SERVFAIL
```

* 其他 (any other information that would be useful)
……

### 说明 Description

偶尔在浏览器网页时，会发现某几个网页打不开，但同时间浏览器 Google 之类的网页没问题，查看日志能看到 `no such host`. 报错，Github、Gist 等 host 此类问题频发，隔几分钟就会恢复正常

### 重现问题的具体布骤 Steps to Reproduce

1. 浏览器网页
2. This Site Can't Be Reached Error in Chrome

**我预期会发生……？**

正常打开网页站点

**实际上发生了什么？**

无法访问网页

### 可能的解决方案 Possible Solution

- 感觉是 DNS 解析的问题，但它时好时坏，我我也不太确定了

### 更多信息 More Information

- DNS 解析使用的是路由器上的自己设置的 DNS 服务，后续可以考虑换成 ISP 提供的继续观察一下
  ![image](https://user-images.githubusercontent.com/38807139/126858612-39acf183-84fa-41e2-8372-64aea80fecb3.png)
