### ISSUE TITLE
[Bug] trojan-grpc service-name中包含感叹号"!"时无法正常解析

### ISSUE THREAD

**Issue by onlyJinx** [Dreamacro/clash#1542]
### Verify steps

- [x]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

v1.6.5

### What OS are you seeing the problem on?

Linux

### Clash config

```yaml
...
  - name: trojan-grpc
    server: xxx.com
    port: 443
    type: trojan
    password: "xxxxxxxxxxxxxxxxx"
    network: grpc
    sni: xxx.com
    udp: true
    grpc-opts:
      grpc-service-name: "f9COMCGwmQ_HeVP4WPiX!BuoIUupJhjHvg"
...
```

### Description

配置中grpc-service-name包含感叹号时无法连接，我检查nginx log时，发现请求的路径是把!转成%21在发送给服务端，然后nginx不能正常把流量转给v2ray，我把配置里(nginx和v2ray)的感叹号删了就可以。
```
root@ip:# cat /etc/nginx/logs/access.log
127.0.0.1 - - [16/Aug/2021:05:56:35 +0000] "POST /f9COMCGwmQ_HeVP4WPiX%21BuoIUupJhjHvg/Tun HTTP/2.0" 200 0 "-" "grpc-go/1.36.0"
127.0.0.1 - - [16/Aug/2021:05:56:43 +0000] "POST /f9COMCGwmQ_HeVP4WPiX%21BuoIUupJhjHvg/Tun HTTP/2.0" 200 0 "-" "grpc-go/1.36.0"
127.0.0.1 - - [16/Aug/2021:05:56:43 +0000] "POST /f9COMCGwmQ_HeVP4WPiX%21BuoIUupJhjHvg/Tun HTTP/2.0" 200 0 "-" "grpc-go/1.36.0"
127.0.0.1 - - [16/Aug/2021:05:56:52 +0000] "POST /f9COMCGwmQ_HeVP4WPiX%21BuoIUupJhjHvg/Tun HTTP/2.0" 200 0 "-" "grpc-go/1.36.0"
```
这应该是clash的问题，因为我使用vless+grpc时(客户端为v2rayN)，grpc-service-name是可以包含!的，下面是使用vless+grpc的nginx log
```
root@ip:# cat /etc/nginx/logs/access.log
127.0.0.1 - - [16/Aug/2021:06:06:18 +0000] "POST /r28qWlpHVmxQK1GaPGewXUNBBMYniEb!3w/Tun HTTP/2.0" 200 444 "-" "grpc-go/1.39.0"
127.0.0.1 - - [16/Aug/2021:06:06:23 +0000] "POST /r28qWlpHVmxQK1GaPGewXUNBBMYniEb!3w/Tun HTTP/2.0" 200 444 "-" "grpc-go/1.39.0"
```
