### ISSUE TITLE
[Bug] 一个 fakeip、mapping 和 多ip域名 的协作问题

### ISSUE THREAD

**Issue by fakeboboliu** [Dreamacro/clash#1545]
### Verify steps

- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

latest

### What OS are you seeing the problem on?

Windows

### Clash config

```yaml
略（原issue作者未提供，我只是根据以前贡献的经验简单看了下）
```

### Description

如果开启 fakeip 的话，在逻辑上来说可能会有 [此 issue](https://github.com/Fndroid/clash_for_windows_pkg/issues/2139) 的问题出现，流程如下：

 - 通过浏览器访问域名，此时增强模式下，clash 的 redir 用 cache mapping 记录下你的域名对应 ip
 - 通过 ssh 客户端访问 ip，[tunnel](https://github.com/Dreamacro/clash/blob/baf03b81e36e3c5d8b9a370ebb82dd2b25b4a58d/tunnel/tunnel.go#L120) 开始解析 metadata，并在 L134 的 FindHostByIP 中，从 redir 的 mapping 中得到了你的域名
 - 因为 fakeip 打开，上述文件 L139 在 metadata 中删除了你的目标ip
 - L321，因为 metadata 中没有 ip 只有 host，隧道开始通过 dns 寻找 host 对应 ip
 - 你的连接被发到一个错误的 ip，因为你的域名有三个 ip 随机顺序返回

因为连续十几个小时没睡了，头脑有点不太工作，如果此问题不存在的话请 close

暂时没想到什么解决方案

**Comment by renbaoshuo** [comment]
```yaml
port: 7890
socks-port: 7891
redir-port: 7892
mixed-port: 7893
allow-lan: false
mode: Rule
log-level: info
ipv6: true
dns:
  enable: true
  ipv6: true
  listen: :53
  enhanced-mode: redir-host
  use-hosts: true 
  nameserver:
    - https://dns.google/dns-query
    - https://doh.pub/dns-query
    - https://cloudflare-dns.com/dns-query
    - https://dns.alidns.com/dns-query
    - https://doh.sb/dns-query
tun:
  enable: true
  ipv6: true
  stack: system
  dns-hijack:
    - 198.18.0.2:53
  auto-route: true
  auto-detect-interface: true
```

这是 https://github.com/Fndroid/clash_for_windows_pkg/issues/2139 中提到的问题出现时使用的配置文件（部分），已略去敏感信息。
