### ISSUE TITLE
TUN 模式下，网卡显示无internet访问权限，可能是虚拟网卡未分配IP导致

### ISSUE THREAD

**Issue by kinsui** [Dreamacro/clash#1549]
### Verify steps

- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

Clash 2021.07.03 windows amd64 with go1.16.5 Sat Jul  3 13:23:06 UTC 2021

### What OS are you seeing the problem on?

Windows

### Clash config

```yaml
dns:
  enable: true
  listen: 0.0.0.0:53
  default-nameserver:
    - 119.29.29.29
    - 223.5.5.5
  enhanced-mode: redir-host 
tun:
  enable: true
  stack: system # system || gvisor
  dns-hijack:
    - 198.18.0.2:53 # when `fake-ip-range` is 198.18.0.1/16, should hijack 198.18.0.2:53
  auto-route: true # auto set global route for Windows
  auto-detect-interface: true
```

### Description

已详细阅读相关issue：[1407](https://github.com/Dreamacro/clash/issues/1407) [1659](https://github.com/Fndroid/clash_for_windows_pkg/issues/1659)  

搜索了wintun和windows提示no internet access的[相关问题](https://www.reddit.com/r/nordvpn/comments/hmb8lg/when_connected_to_a_vpn_windows_shows_as_no/)和[解决方案](https://docs.microsoft.com/en-us/answers/questions/63441/windows-shows-no-internet-access-but-it-worked.html#answer-container-66997)，目前猜测应该是开启虚拟网卡后未分配ip导致的，理论上在tun创建完成后设置网卡IP即可修复这个问题。

clash启动tun后默认为手动设置ip但是IP栏为空，此时微软系软件会提示网络异常，尤其office无法正常使用，如下图：
![20210818103036](https://user-images.githubusercontent.com/23612126/129830987-2916fce9-719b-42ea-aff0-0b91389c8d65.png)  

手动修改ip设置为自动获取ip后，网卡状态恢复正常：
![20210818103931](https://user-images.githubusercontent.com/23612126/129831094-05aea8da-1ec8-4c13-9dce-c6363636a5ab.png)
