### ISSUE TITLE
新开一个端口转发给7890作为一条规则

### ISSUE THREAD

**Issue by yiyayamaya** [Dreamacro/clash#1568]
### Verify steps

- [x]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

clash-linux-amd64-nightly-g69f99e3

### What OS are you seeing the problem on?

Linux

### Clash config

```yaml
port: 7890
socks-port: 30001
mode: rule

script:
  shortcuts:
    chromein: src_ip  == "127.0.0.1" and type=="Socks5"
rules:
  - SCRIPT,chromein,proxy    
  - MATCH,DIRECT
```

### Description

感谢开发者。你好，我跟这位的问题有点像 #629 

我希望整个chrome走clash的一行规则，然后chrome再自己用插件分流。

我试了 #173 里面process-name的方式 但是没效果呢 (可能是我process-name写错了chrome google-chrome-stable都不行)
 
请问只能用我上面的那种方式实现吗(把Socks流量完全交给chrome)

有没有用clash新开一个http端口然后转发给7890作为一行规则这种操作呢？
