### ISSUE TITLE
使用VMess套Cloudflare并自选IP后，在clash中如何配置？

### ISSUE THREAD

**Issue by f2sky** [Dreamacro/clash#1571]
### Clash version
v1.6.5

### Description
clash中配置关键字好像和VMess官方的不大一致，然后尝试了很多种填写方法，都没有成功连接。
（改配置能正常翻墙，在其它客户端可正常使用）

**Comment by Maasea** [comment]
配置文件中正常配置vmess,但是在clash配置里增加一条hosts记录，例如
```
hosts:                            
   '*.clash.dev': 127.0.0.1 
   'alpha.clash.dev': ::1
```

**Comment by akw5454521** [comment]
你贴出来脱敏的配置写法看看

**Comment by f2sky** [comment]
@akw5454521 
之前的配置如下：
name: "VMess-auto-IP"
  type: vmess
  server: domain08.mqcjuc.ml
  port: 443
  uuid: xxxxxxxxxx
  alterId: 0
  cipher: auto
  udp: true
  tls: true
  skip-cert-verify: false
  network: ws
  host: A
  ws-path: /xxxxxxxxxxx
  sni: A
  # ws-headers: #这一行后面不要写东西
  #   Host: v2ray.com # 填你的主机名


@Maasea 
> 配置文件中正常配置vmess,但是在clash配置里增加一条hosts记录指向自选的IP，例如
前面提到的「配置文件」和后面的「clash配置」分别是哪个文件？自定义的还是自带的配置文件？

**Comment by Maasea** [comment]
@f2sky  
[配置文件]和[clash配置]都是指clash 的配置文件。配置定向IP要注意，sni和host 填是绑定的域名（注意区别host 和 hosts）。

[clash配置文件]：
```
hosts:
  'YourDomain': IP

proxies: 
  - type: vmess
    cipher: auto
    name: VA
    server: YourDomain
    port: 443
    udp: false
    uuid: UUID
    alterId: "0"
    network: ws
    tls: true
    ws-path: /
    ws-headers:
      host: YourDomain
```
如果你使用Clash for Windows，你可以在mixin里填入hosts方便后续更改
[Mixin配置如下]
```
mixin: 
  hosts:
    'YourDomain': IP
```
