### ISSUE TITLE
[Bug] 启动clash，能访问YouTube，但是dashboard面板就是连不上

### ISSUE THREAD

**Issue by melodyjerry** [Dreamacro/clash#1585]
### Clash version

1.6.5

### What OS are you seeing the problem on?

Linux

### Clash config

```yaml
port: 7890
socks-port: 7891
redir-port: 7892
allow-lan: false
mode: Rule
log-level: silent
external-controller: '0.0.0.0:9090'
secret: ''
```

### Description

检查了下，配置文件没有动过。启动clash，能访问YouTube，但是dashboard面板就是连不上
![image](https://user-images.githubusercontent.com/47730856/132288703-5d7fd735-a610-4d73-b867-4e640ad8451d.png)
