### ISSUE TITLE
最新内核P0907。script shortcuts问题

### ISSUE THREAD

**Issue by flyhigherpi** [Dreamacro/clash#1588]
### Verify steps

- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

Premium 2021.09.07

### What OS are you seeing the problem on?

Windows

### Clash config

```yaml
script:
  shortcuts:
    limit: src_ip == "192.168.2.44/32" and dst_port == 443
rules:
  - SCRIPT,limit,REJECT
```

### Description

大大，这样该IP依旧能访问443端口。写法有误？
这个功能有没具体写法说明书呢
