### ISSUE TITLE
[Bug] socks5节点总是超时无法连接

### ISSUE THREAD

**Issue by ceylog** [Dreamacro/clash#1590]
### Clash version

1.6.5

### What OS are you seeing the problem on?

Windows

### Clash config

```yaml
port: 7890
socks-port: 7891
allow-lan: false
bind-address: '*'
mode: rule
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090



proxies:
  - name: hk1
  - name: hk2
  - name: sg2
  - name: "zaVPN"
    type: "socks5"
    server: "127.0.0.1"
    port: "1080" 

proxy-groups:

  # url-test select which proxy will be used by benchmarking speed to a URL.
  - name: "auto"
    type: url-test
    proxies:
      - hk1
      - hk2
      - sg2
    # tolerance: 150
    # lazy: true
    url: 'http://connect.rom.miui.com/generate_204'
    interval: 300

  # load-balance: The request of the same eTLD+1 will be dial to the same proxy.
  - name: "load-balance"
    type: load-balance
    proxies:
      - hk1
      - hk2
    url: 'http://www.gstatic.com/generate_204'
    interval: 300
    # strategy: consistent-hashing # or round-robin

  # select is used for selecting proxy or proxy group
  # you can use RESTful API to switch proxy is recommended for use in GUI.
  - name: Proxy
    type: select
    # disable-udp: true
    proxies:
      - auto
  - name: zaWORK
    type: select
    proxies:
      - zaVPN

rules:
  - DOMAIN-SUFFIX,xx.com,zaWORK
  - DOMAIN-SUFFIX,xx.net,zaWORK
  - DOMAIN-SUFFIX,google.com,auto
  - DOMAIN-KEYWORD,google,auto
  - DOMAIN,google.com,auto
  - DOMAIN-SUFFIX,ad.com,REJECT
  - SRC-IP-CIDR,192.168.1.201/32,DIRECT
  # optional param "no-resolve" for IP rules (GEOIP, IP-CIDR, IP-CIDR6)
  - IP-CIDR,127.0.0.0/8,DIRECT
  - GEOIP,CN,DIRECT
  - DST-PORT,80,DIRECT
  - SRC-PORT,7777,DIRECT
  - MATCH,auto
```

### Description

socks5节点测试总是超时，无法连接，其他节点都正常，该socks5 节点使用其他软件连接正常  ,socks5节点是本地搭建
