### ISSUE TITLE
[Bug] http://clash.razord.top 面板，无法远程访问路由器的controller 

### ISSUE THREAD

**Issue by holefrog** [Dreamacro/clash#1597]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

 clash-linux-armv5  v1.6.5

### What OS are you seeing the problem on?

Linux

### Clash config

```yaml
port: 8888
socks-port: 8889
redir-port: 8890

mode: rule

allow-lan: true

bind-address: "*"

log-level: info

ipv6: false

external-controller: 0.0.0.0:6372
secret: mysecret
```

### Clash log

```shell
linux没找到log。请问路径和文件名？
```

### Description

你好。

用http://clash.razord.top，在ubuntu或者windows计算机上测试相同的配置文件，127.0.0.1:6372 加secret可以正常访问。

安装在路由器（192.168.2.1）上面后，在"外部网络"--"端口转发"中开启转发，把192.168.2.1:6372转发到外面。
tcp        0      0 :::6372                                             :::*                                                LISTEN      
tcp        0      0 :::30000                                            :::*                                                LISTEN      
tcp        0      0 :::8888                                             :::*                                                LISTEN      
tcp        0      0 :::8889                                             :::*                                                LISTEN      
tcp        0      0 :::8890    

远程用路由器ip或ddns域名均无法访问clash的6372端口。

但远程可以用ssh登录路由器的30000端口。

请问会是哪里配置不正常呢？

多谢
