### ISSUE TITLE
Failed to start Redir UDP Listener: operation not permitted

### ISSUE THREAD

**Issue by onlyJinx** [Dreamacro/clash#1602]
### Verify steps

- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [x]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [x]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

1.7.0

### What OS are you seeing the problem on?

Linux

### Clash config

```yaml
mixed-port: 1080
allow-lan: true
external-controller: 127.0.0.1:9090
redir-port: 7892
secret: ''
external-ui: ui
dns:
  enable: true
  listen: 0.0.0.0:53
  default-nameserver:
    - 114.114.114.114
    - 8.8.8.8
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16 # Fake IP addresses pool CIDR
  nameserver:
    - 114.114.114.114 # default value
    - 8.8.8.8 # default value
    - tls://dns.rubyfish.cn:853 # DNS over TLS
    - https://1.1.1.1/dns-query # DNS over HTTPS
proxies:
...
proxy-providers:
...
```

### Clash log

```shell
● clash.service - Clash Server
     Loaded: loaded (/etc/systemd/system/clash.service; enabled; vendor preset: disabled)
     Active: active (running) since Fri 2021-09-10 00:13:11 CST; 3s ago
   Main PID: 2298 (clash)
      Tasks: 10 (limit: 9388)
     Memory: 7.4M
        CPU: 124ms
     CGroup: /system.slice/clash.service
             └─2298 /etc/clash/clash -d /etc/clash/

9月 10 00:13:11 ruo-x550jx clash[2298]: time="2021-09-10T00:13:11+08:00" level=info msg="Start initial provider CN2-GIA"
9月 10 00:13:11 ruo-x550jx clash[2298]: time="2021-09-10T00:13:11+08:00" level=info msg="Start initial provider NSD"
9月 10 00:13:11 ruo-x550jx clash[2298]: time="2021-09-10T00:13:11+08:00" level=info msg="Start initial provider BWH"
9月 10 00:13:11 ruo-x550jx clash[2298]: time="2021-09-10T00:13:11+08:00" level=info msg="Start initial provider TOKYO"
9月 10 00:13:11 ruo-x550jx clash[2298]: time="2021-09-10T00:13:11+08:00" level=info msg="Start initial compatible provider ⛱️ china"
9月 10 00:13:11 ruo-x550jx clash[2298]: time="2021-09-10T00:13:11+08:00" level=info msg="Start initial compatible provider 🐠 other"
9月 10 00:13:11 ruo-x550jx clash[2298]: time="2021-09-10T00:13:11+08:00" level=warning msg="Failed to start Redir UDP Listener: operation not permitted"
9月 10 00:13:11 ruo-x550jx clash[2298]: time="2021-09-10T00:13:11+08:00" level=info msg="Redirect proxy listening at: [::]:7892"
9月 10 00:13:11 ruo-x550jx clash[2298]: time="2021-09-10T00:13:11+08:00" level=info msg="RESTful API listening at: 127.0.0.1:9090"
9月 10 00:13:11 ruo-x550jx clash[2298]: time="2021-09-10T00:13:11+08:00" level=info msg="Mixed(http+socks) proxy listening at: [::]:1080"
```

### Description

我参考这个issue写了clash.servicee。但是运行是好像是因为权限问题无法监听53端口。https://github.com/Dreamacro/clash/issues/555#issuecomment-595651217

我已经在service文件里加了
```
CapabilityBoundingSet=CAP_NET_BIND_SERVICE
AmbientCapabilities=CAP_NET_BIND_SERVICE
```
但是好像没有效果，我现在不知道该如何修改这个service，所以来请教一下开发者。

PS. 
如果使用```setcap cap_net_bind_service,cap_net_admin+ep  /path/clash```，再使用命令行方式直接运行```/ptah/clash -d /clash-home```是可以解决，但这不是我想要的，因为我想用daemon的方式来运行clash。

下面是完整的service文件

[ruo-x550jx ~]# cat /etc/systemd/system/clash.service
[Unit]
Description=Clash Server
After=network.target
[Service]
CapabilityBoundingSet=CAP_NET_BIND_SERVICE
AmbientCapabilities=CAP_NET_BIND_SERVICE
ExecStart=/etc/clash/clash -d /etc/clash/
User=clash
Group=clash
[Install]
WantedBy=multi-user.target

**Comment by fakeboboliu** [comment]
你应当先尝试 `setenforce 0` 关闭 SELinux 后是否工作

如果是，再打开 SELinux 并跟随红帽的文档进行 troubleshooting，或者就让他这样关着（不推荐，但是如果你懒得管了可以这样做）

> Whenever faced with a problem, some people say "Lets keep SELinux enabled." Now, they have two problems.

**Comment by onlyJinx** [comment]
我今天不在家里，所以我用我另一台电脑debian10来测试，我发现debian10是没有SELinux的，具体请看下面的输出内容
```
root@debian:~# setenforce 0
-bash: setenforce: command not found
```
```
root@debian:~# systemctl status clash
● clash.service - Clash daemon, A rule-based proxy in Go.
   Loaded: loaded (/etc/systemd/system/clash.service; enable   Active: inactive (dead) since Thu 2021-09-09 08:23:23 EDT  Process: 635 ExecStart=/etc/clash/clash -d /etc/clash (cod Main PID: 635 (code=exited, status=0/SUCCESS)

Sep 09 07:52:39 debian clash[635]: time="2021-09-09T07:52:39Sep 09 07:52:39 debian clash[635]: time="2021-09-09T07:52:39Sep 09 07:52:39 debian clash[635]: time="2021-09-09T07:52:39Sep 09 07:52:39 debian clash[635]: time="2021-09-09T07:52:39Sep 09 07:52:39 debian clash[635]: time="2021-09-09T07:52:39Sep 09 07:52:39 debian clash[635]: time="2021-09-09T07:52:39Sep 09 07:52:39 debian clash[635]: time="2021-09-09T07:52:39Sep 09 08:23:23 debian systemd[1]: Stopping Clash daemon, A Sep 09 08:23:23 debian systemd[1]: clash.service: Succeeded.Sep 09 08:23:23 debian systemd[1]: Stopped Clash daemon, A rroot@debian:~#
```



root@debian:~# cat /etc/systemd/system/clash.service
```
[Unit]
Description=Clash daemon, A rule-based proxy in Go.
After=network.target

[Service]
User=clash
Group=clash
Type=simple
CapabilityBoundingSet=CAP_NET_BIND_SERVICE
AmbientCapabilities=CAP_NET_BIND_SERVICE
Restart=always
ExecStart=/etc/clash/clash -d /etc/clash

[Install]
WantedBy=multi-user.target
```
root@debian:~# cat /etc/clash/config.yaml
```
port: 7890
socks-port: 7891
redir-port: 7892
mode: rule
log-level: info
external-controller: 127.0.0.1:9090
dns:
  enable: true
  listen: 0.0.0.0:53
  default-nameserver:
    - 114.114.114.114
    - 8.8.8.8
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  # use-hosts: true # lookup hosts and return IP record
  nameserver:
    - 114.114.114.114 # default value
    - 8.8.8.8 # default value
    - tls://dns.rubyfish.cn:853 # DNS over TLS
    - https://1.1.1.1/dns-query # DNS over HTTPS
...
```
