### ISSUE TITLE
[Bug] Windows TUN 无法正常使用

### ISSUE THREAD

**Issue by bemarkt** [Dreamacro/clash#1627]
### Verify steps

- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

Premium 2021.09.15

### What OS are you seeing the problem on?

Windows

### Clash config

```yaml
tun:
    enable: true
    stack: system # gvisor
    dns-hijack:
      - 198.18.0.2:53
    auto-route: true
    auto-detect-interface: true
dns:
    enable: true
    ipv6: false
    listen: 0.0.0.0:53
    enhanced-mode: fake-ip
    fake-ip-range: 198.18.0.1/16
    fake-ip-filter:
      # === LAN ===
      - '*.lan'
      - '*.localdomain'
      - '*.example'
      - '*.invalid'
      - '*.localhost'
      - '*.test'
      - '*.local'
      - '*.home.arpa'
      # === Linksys Wireless Router ===
      - '*.linksys.com'
      - '*.linksyssmartwifi.com'
      # === ASUS Router ===
      - '*.router.asus.com'
      # === Apple Software Update Service ===
      - 'swscan.apple.com'
      - 'mesu.apple.com'
      # === Windows 10 Connnect Detection ===
      - '*.msftconnecttest.com'
      - '*.msftncsi.com'
      - 'msftconnecttest.com'
      - 'msftncsi.com'
      # === Google ===
      - 'lens.l.google.com'
      - 'stun.l.google.com'
      ## Golang
      - 'proxy.golang.org'
      # === NTP Service ===
      - 'time.*.com'
      - 'time.*.gov'
      - 'time.*.edu.cn'
      - 'time.*.apple.com'
      - 'time1.*.com'
      - 'time2.*.com'
      - 'time3.*.com'
      - 'time4.*.com'
      - 'time5.*.com'
      - 'time6.*.com'
      - 'time7.*.com'
      - 'ntp.*.com'
      - 'ntp1.*.com'
      - 'ntp2.*.com'
      - 'ntp3.*.com'
      - 'ntp4.*.com'
      - 'ntp5.*.com'
      - 'ntp6.*.com'
      - 'ntp7.*.com'
      - '*.time.edu.cn'
      - '*.ntp.org.cn'
      - '+.pool.ntp.org'
      - 'time1.cloud.tencent.com'
      # === Game Service ===
      ## Nintendo Switch
      - '+.srv.nintendo.net'
      ## Sony PlayStation
      - '+.stun.playstation.net'
      ## Microsoft Xbox
      - 'xbox.*.microsoft.com'
      - 'xnotify.xboxlive.com'
      # === Other ===
      ## QQ Quick Login
      - 'localhost.ptlogin2.qq.com'
      - 'localhost.sec.qq.com'
      ## STUN Server
      - 'stun.*.*'
      - 'stun.*.*.*'
      - '+.stun.*.*'
      - '+.stun.*.*.*'
      - '+.stun.*.*.*.*'
    default-nameserver:
      - 208.67.222.222
      - 119.29.29.29
    nameserver:
      - 119.29.29.29
      - 223.5.5.5
    fallback:
      - tcp://208.67.222.222:5353
      - https://doh.pub/dns-query
      - https://dns.twnic.tw/dns-query
    fallback-filter:
      geoip: true
      geoip-code: CN
      ipcidr:
        - 0.0.0.0/32
        - 100.64.0.0/10
        - 127.0.0.0/8
        - 240.0.0.0/4
        - 255.255.255.255/32
```

### Clash log

```shell
对所有服务器查询时，日志中只显示一个服务器的UDP请求。
```

### Description

wintun版本: 0.13 0.12
预期结果：
![image](https://user-images.githubusercontent.com/25723505/133532907-7db1949a-205b-4be7-9913-640969db5fe4.png)
使用TUN结果：
![image](https://user-images.githubusercontent.com/25723505/133534921-7ab23c35-da16-4898-83d6-fee00a9e3245.png)

在 TUN模式下使用 steam 自带的服务器浏览器查看时无法显示所有的服务器信息，在游戏中查询一样无法全部显示。使用 wireshark 抓包本地网络显示并没有向全部服务器发送UDP查询请求，clash log中也只存在对一个服务器的发送udp记录；当单独对一个未响应的服务器进行查询时，可以显示相应信息，wireshark以及clash中都显示相应的log：
![image](https://user-images.githubusercontent.com/25723505/133539054-bf00d673-f904-4c6f-8c37-bac60f7dd0e6.png)
而且使用**TAP模式**或**Netch wintun模式**以及**直连**进行测试都可以达到预期结果，抓包中也有显示向所有服务器发送查询请求。
