### ISSUE TITLE
[Feature] 将配置于hosts文件的解析作为DNS解析通过Clash DNS服务器返回

### ISSUE THREAD

**Issue by fxzxmicah** [Dreamacro/clash#1636]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

将Hosts文件中的DNS解析作为优先的DNS解析从Clash的DNS服务器返回。

下图是一个示例，`NAT.local`配置于系统Hosts文件，但是此时无法通过nslookup查询到。
![image](https://user-images.githubusercontent.com/48860358/134100797-b04c6f84-23e3-45e9-8426-3fc8abc06134.png)

**Comment by zhongfly** [comment]
```yaml
dns:
  use-hosts: true # lookup hosts and return IP record
```
这样？

**Comment by fxzxmicah** [comment]
> ```yaml
> dns:
>   use-hosts: true # lookup hosts and return IP record
> ```
> 
> 这样？

是这样写的，但是没用。nslookup里面没有。

**Comment by Student414** [comment]
我是把系统自带的DNS添加到了clash dns配置段中，在透明代理里面bypass systemd-resolve用户的流量，这样可以实现使用运营商DNS+本地hosts+其他DNS解析域名。
```
dns:
  enable: true
  ipv6: true
  listen: 0.0.0.0:1053
  enhanced-mode: redir-host # or fake-ip
  use-hosts: true
  nameserver:
    #- 119.29.29.29 # 腾讯DNSPod
    - 127.0.0.53
    - 180.76.76.76 # 百度
    - 223.5.5.5 # 阿里
    # - 2400:3200::1
  fallback:
    - 8.8.8.8
    #- tls://185.222.222.222
    #- tls://8.8.8.8 # Google
    #- tls://1.1.1.1 # cloudflare
    #- https://1.1.1.1/dns-query # cloudflare
  fallback-filter:
    geoip: true
    ipcidr:
      - 240.0.0.0/4
```
```
# DNS
if $enable_dns ;then
    iptables -t nat -N TPROXY_DNS_LOCAL
    iptables -t nat -A TPROXY_DNS_LOCAL -p udp ! --dport 53 -j RETURN
    iptables -t nat -A TPROXY_DNS_LOCAL -m owner --uid-owner clash -j RETURN
    iptables -t nat -A TPROXY_DNS_LOCAL -m owner --uid-owner systemd-resolve -j RETURN
    iptables -t nat -A TPROXY_DNS_LOCAL -p udp --dport 53 -j REDIRECT --to-ports $dns_port
    iptables -t nat -A OUTPUT -p udp -j TPROXY_DNS_LOCAL

    iptables -t nat -N TPROXY_DNS_EXTERNAL
    iptables -t nat -A TPROXY_DNS_EXTERNAL -p udp ! --dport 53 -j RETURN
    iptables -t nat -A TPROXY_DNS_EXTERNAL -p udp --dport 53 -j REDIRECT --to-ports $dns_port
    iptables -t nat -A PREROUTING -p udp -j TPROXY_DNS_EXTERNAL
fi
```
