### ISSUE TITLE
[Bug] 重新连接网络时，clash的 CPU 占用率30%，内存1.5G [已补 log 及网卡状态截图]

### ISSUE THREAD

**Issue by uuip** [Dreamacro/clash#1672]
### Verify steps

- [ ]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [ ]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

2021.9.15 pro

### What OS are you seeing the problem on?

Windows

### Clash config

```yaml
dns:
      enable: true
      enhanced-mode: redir-host #fake-ip
      fake-ip-filter:
        - '*.msftconnecttest.com'
        - '*.msftncsi.com'
      default-nameserver:
        - 223.5.5.5
        - 119.29.29.29
      nameserver:
        - 223.5.5.5
        - 119.29.29.29
        - https://dns.alidns.com/dns-query
        - https://doh.pub/dns-query
    fallback:
       - 'https://public.dns.iij.jp/dns-query'
       - 'https://dns.quad9.net/dns-query'
     fallback-filter:
      geoip: false
      geoip-code: CN
       ipcidr:
         - 240.0.0.0/4
       domain:
         - '+.google.com'
         - '+.googlevideo.com'
         - '+.facebook.com'
         - '+.twitter.com'
         - '+.youtube.com'
         - '+.xn--ngstr-lra8j.com'
         - '+.google.cn'
         - '+.googleapis.cn'
         - '+.googleapis.com'
         - '+.gvt1.com'
    tun:
      enable: true
      stack: system
      dns-hijack:
        - 198.18.0.2:53
      auto-route: true
      auto-detect-interface: true
```

2021.11.02 更新目前配置
```yaml
  dns:
    enable: true
    enhanced-mode: fake-ip #redir-host
    fake-ip-filter:
      - '*.msftconnecttest.com'
      - '*.msftncsi.com'
    default-nameserver:
      - 223.5.5.5
      - 119.29.29.29
    nameserver:
      - 223.5.5.5
      - 119.29.29.29
      - https://dns.alidns.com/dns-query
      - https://doh.pub/dns-query
#    fallback:
#      - udp://127.0.0.1:5053
#    fallback-filter:
#      geoip: false
#      geoip-code: CN
#      ipcidr:
#        - 240.0.0.0/4
#      domain:
#        - '+.google.com'
#        - '+.googlevideo.com'
#        - '+.facebook.com'
#        - '+.twitter.com'
#        - '+.youtube.com'
#        - '+.xn--ngstr-lra8j.com'
#        - '+.google.cn'
#        - '+.googleapis.cn'
#        - '+.googleapis.com'
#        - '+.gvt1.com'
  tun:
    enable: true
    stack: system
    dns-hijack:
      - 198.18.0.2:53
    auto-route: true
    auto-detect-interface: true
```
### Clash log
[2021-11-02-012714.log](https://github.com/Dreamacro/clash/files/7455124/2021-11-02-012714.log)
```shell
[2021-11-02-012714.log](https://github.com/Dreamacro/clash/files/7455124/2021-11-02-012714.log)
```

### Description
1.  使用 tun + redir-host ，fallback  中 geo true + cn。发现此问题后改用fake-ip，仍会触发。

2.  实际情形：
也许家里的路由器性能不行吧，晚高峰隔三岔五连不上路由器的WiFi（连接一段时间后，WiFi断开）。
公司的路由器经常出现因为连接人数太多，而导致WiFi被挤下WiFi
上不了网，我看下连接，无线断了，手工重连。clash 一直开着。在此过程中，听到风扇叫，打开任务管理器，看了下状态。

3.  重现方法：正常网络+clash正常时候时，手动点击Windows的网络管理，断开WiFi连接。

<img width="1132" alt="屏幕截图 2021-10-13 005916" src="https://user-images.githubusercontent.com/16631174/137336062-9ebcdee2-0f3b-4509-bc42-d2fe10973d48.png">
