### ISSUE TITLE
[Bug] Wintun stack 使用 system，tun网卡会出现“无网络访问权限”的故障

### ISSUE THREAD

**Issue by daiyeqi** [Dreamacro/clash#1674]
### Verify steps

- [ ]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [ ]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

Premium 2021.09.15

### What OS are you seeing the problem on?

Windows

### Clash config

```yaml
port: 1080
socks-port: 1088
# redir-port: 7892
# tproxy-port: 7893
# mixed-port: 7890

allow-lan: false
bind-address: "*"
mode: rule

# Clash by default prints logs to STDOUT
# info / warning / error / debug / silent
log-level: warning

# When set to false, resolver won't translate hostnames to IPv6 addresses
ipv6: true

# RESTful web API listening address
external-controller: 127.0.0.1:15363

# Secret for the RESTful API (optional)
# Authenticate by spedifying HTTP header `Authorization: Bearer ${secret}`
# ALWAYS set a secret if RESTful API is listening on 0.0.0.0
# secret: ""

# Static hosts for DNS server and connection establishment (like /etc/hosts)
#
# Wildcard hostnames are supported (e.g. *.clash.dev, *.foo.*.example.com)
# Non-wildcard domain names have a higher priority than wildcard domain names
# e.g. foo.example.com > *.example.com > .example.com
# P.S. +.foo.com equals to .foo.com and foo.com
hosts:
  # '*.clash.dev': 127.0.0.1
  # '.dev': 127.0.0.1
  # 'alpha.clash.dev': '::1'

# DNS server settings
# This section is optional. When not present, the DNS server will be disabled.
dns:
  enable: true
  listen: 0.0.0.0:53
  ipv6: true # when the false, response to AAAA questions will be empty

  # These nameservers are used to resolve the DNS nameserver hostnames below.
  # Specify IP addresses only
  default-nameserver:
    - 119.29.29.29
    - 1.1.1.1
  enhanced-mode: redir-host # or fake-ip
  # fake-ip-range: 198.18.0.1/16 # Fake IP addresses pool CIDR
  # use-hosts: true # lookup hosts and return IP record

  # Hostnames in this list will not be resolved with fake IPs
  # i.e. questions to these domain names will always be answered with their
  # real IP addresses
  # fake-ip-filter:
  #   - '*.lan'
  #   - localhost.ptlogin2.qq.com

  # Supports UDP, TCP, DoT, DoH. You can specify the port to connect to.
  # All DNS questions are sent directly to the nameserver, without proxies
  # involved. Clash answers the DNS question with the first result gathered.
  nameserver:
    - 119.29.29.29 # default value
    - 1.1.1.1 # default value
    - "[2402:4e00::]:53"
    - "[2606:4700:4700::1111]:53"
    - https://1.1.1.1/dns-query # DNS over HTTPS

  # When `fallback` is present, the DNS server will send concurrent requests
  # to the servers in this section along with servers in `nameservers`.
  # The answers from fallback servers are used when the GEOIP country
  # is not `CN`.
  # fallback:
  #   - tcp://1.1.1.1

tun:
  enable: true
  stack: system # system or gvisor
  dns-hijack:
    - 198.18.0.2:53 # when `fake-ip-range` is 198.18.0.1/16, should hijack 198.18.0.2:53
  auto-route: true # auto set global route
  # auto-detect-interface: true # conflict with interface-name

interface-name: 以太网

proxies:
  # Trojan
  - name: trojan
    type: trojan
    server: xxx.app
    port: 443
    password: ******
    udp: true
    sni: xxx.app

proxy-groups:
  - name: PROXY
    type: select
    proxies:
      - trojan

rule-providers:
  proxycidr:
    type: file
    behavior: ipcidr
    path: ./ruleset/proxycidr.yaml

  proxy:
    type: file
    behavior: domain
    path: ./ruleset/proxy.yaml

  directcidr:
    type: file
    behavior: ipcidr
    path: ./ruleset/directcidr.yaml

  direct:
    type: file
    behavior: domain
    path: ./ruleset/direct.yaml

  lancidr:
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/lancidr.txt"
    path: ./ruleset/lancidr.yaml
    interval: 86400

  private:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/private.txt"
    path: ./ruleset/private.yaml
    interval: 86400

  gfw:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/gfw.txt"
    path: ./ruleset/gfw.yaml
    interval: 86400

  greatfire:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/greatfire.txt"
    path: ./ruleset/greatfire.yaml
    interval: 86400

  tld-not-cn:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/tld-not-cn.txt"
    path: ./ruleset/tld-not-cn.yaml
    interval: 86400

  telegramcidr:
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/telegramcidr.txt"
    path: ./ruleset/telegramcidr.yaml
    interval: 86400

rules:
  - RULE-SET,lancidr,DIRECT
  - RULE-SET,private,DIRECT
  - RULE-SET,directcidr,DIRECT
  - RULE-SET,direct,DIRECT
  - RULE-SET,proxycidr,PROXY
  - RULE-SET,proxy,PROXY
  - RULE-SET,gfw,PROXY
  - RULE-SET,greatfire,PROXY
  - RULE-SET,telegramcidr,PROXY
  - RULE-SET,tld-not-cn,PROXY
  - MATCH,DIRECT

```

### Description

Wintun的情况下，stack 如果使用 system，clash 启动后，tun网卡会出现“无网络访问权限”的故障，部分 Windows 的应用会提示网络未连接，但这个时候是能正常上网的。可以通过执行 `ipconfig /renew ` 命令恢复正常，但多少有点麻烦。

如果使用 stack 使用 gvisor 的话，steam 又会出现无法登录的故障。

所以请问下大佬该问题是否在修复的计划中？

https://github.com/Dreamacro/clash/issues/1488#issuecomment-878999293
