### ISSUE TITLE
[Bug] trojan+ws经过cdn中转时出现malformed http response报错

### ISSUE THREAD

**Issue by plutonemhikari** [Dreamacro/clash#1676]
### Verify steps

- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

dev分支最新版

### What OS are you seeing the problem on?

Linux

### Clash config

```yaml
socks-port: 1080
proxies:
  - name: trojan-ws
    type: trojan
    server: example.com
    port: 443
    password: my_passwd
    sni: example.com
    network: ws
    ws-opts:
      path: /ws
      headers:
        Host: example.com
proxy-groups:
  - name: proxy
    type: select
    proxies: 
    - trojan-ws
    - DIRECT

rules:
  - GEOIP,LAN,DIRECT
  - MATCH,proxy
```

### Clash log

```shell
2021-10-17 6:44:59[warning] [TCP] dial proxy (match DomainSuffix/jsdelivr.net) to cdn.jsdelivr.net:443 error: example.com:443 connect error: dial example:443 error: malformed HTTP response "\x00\x00\x12\x04\x00\x00\x00\x00\x00\x00\x03\x00\x00\x01\x00\x00\x04\x00\x01\x00\x00\x00\x05\x00\xff\xff\xff\x00\x00\x04\b\x00\x00\x00\x00\x00\u007f\xff\x00\x00\x00\x00\b\a\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01"
2021-10-17 6:45:00[warning] [TCP] dial proxy (match DomainSuffix/jsdelivr.net) to cdn.jsdelivr.net:443 error: example.com:443 connect error: dial example:443 error: malformed HTTP response "\x00\x00\x12\x04\x00\x00\x00\x00\x00\x00\x03\x00\x00\x01\x00\x00\x04\x00\x01\x00\x00\x00\x05\x00\xff\xff\xff\x00\x00\x04\b\x00\x00\x00\x00\x00\u007f\xff\x00\x00\x00\x00\b\a\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01"
```

### Description

服务端使用v2ray-core和trojan-go都会出现这种状况，如果不用CDN中转则不会出现这种状况，但是使用同样配置的vmess协议即使通过cloudflare的CDN中转也可以正常使用。客户端改用trojan-go也可以正常使用。
