### ISSUE TITLE
[求助]  透明代理时Tproxy模式代理自身流量问题

### ISSUE THREAD

**Issue by onlyJinx** [Dreamacro/clash#1684]
### Verify steps

- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

最新版

### What OS are you seeing the problem on?

Linux

### Clash config

```yaml
tproxy-port: 7893
mode: rule
allow-lan: true
log-level: debug
ipv6: false
dns:
  enable: true
  listen: 0.0.0.0:5353
  default-nameserver:
    - 223.5.5.5
    - 8.8.8.8
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  nameserver:
    - 223.5.5.5
    - 114.114.114.114 
  fallback:
    - tcp://1.1.1.1
proxies:
...
proxy-groups:
...
rules:
  - GEOIP,CN,DIRECT
  - MATCH,proxy
```

### Clash log

```shell
无log
```

### Description

我使用下面的iptables规则时可以让其他机器进行透明代理(网关地址指向linux)，但是linux自身无法走代理，看了一下其他issue https://github.com/Dreamacro/clash/issues/555 ，好像是使用REDIRECT的，但是我想使用Tproxy，下面是能正常代理其他接入设备流量的规则。

```
#添加路由表
ip rule add fwmark 1 table 100
ip route add local 0.0.0.0/0 dev lo table 100

iptables -t mangle -N clash

#绕过内网地址
iptables -t mangle -A clash -d 0.0.0.0/8 -j RETURN
iptables -t mangle -A clash -d 10.0.0.0/8 -j RETURN
iptables -t mangle -A clash -d 127.0.0.0/8 -j RETURN
iptables -t mangle -A clash -d 169.254.0.0/16 -j RETURN
iptables -t mangle -A clash -d 172.16.0.0/12 -j RETURN
iptables -t mangle -A clash -d 192.168.50.0/16 -j RETURN
iptables -t mangle -A clash -d 192.168.9.0/16 -j RETURN
iptables -t mangle -A clash -d 224.0.0.0/4 -j RETURN
iptables -t mangle -A clash -d 240.0.0.0/4 -j RETURN

#重定向全部流量
iptables -t mangle -A clash -p udp -j TPROXY --on-port 7893 --tproxy-mark 1
iptables -t mangle -A clash -p tcp -j TPROXY --on-port 7893 --tproxy-mark 1
iptables -t mangle -A PREROUTING -j clash

#重定向DNS查询流量到Clash
iptables -t nat -A PREROUTING 1 -p udp --dport 53 -j REDIRECT --to-ports 5353
```

我在上面的基础上，再给OUTPUT链的流量打上标签 1 ，让流量重新回到PREROUTING链上，这样相当于让本机流量重新走一遍。
```
iptables -t nat -N self
#绕过SSH流量
iptables -t nat -A self -p tcp --sport 22 -j RETURN
#绕过clash发出的流量
iptables -t nat -A self -m owner --uid-owner clash -j RETURN

iptables -t nat -A self -p udp -j MARK --set-mark 1
iptables -t nat -A self -p tcp -j MARK --set-mark 1
iptables -t nat -A OUTPUT -j self
```

但结果并不是我想的那样，本机流量并没有发到calsh上，不知道是我那一步想漏了。。。
