### ISSUE TITLE
[Bug] tun模式下透明网关用IP访问不走代理

### ISSUE THREAD

**Issue by skill7899** [Dreamacro/clash#1702]
### Verify steps

- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

2021.09.15

### What OS are you seeing the problem on?

Linux

### Clash config

```yaml
mixed-port: 7890
tproxy-port: 7893
redir-port: 7892
# RESTful API for clash
external-controller: 0.0.0.0:9090
external-ui: dash-ui
tun:
  enable: true
  # stack: gvisor
  stack: system
  dns-hijack:
  # - 198.18.0.2:53
    - tcp://8.8.8.8:53
    - tcp://8.8.4.4:53
fake-ip-range: 198.18.0.1/16
allow-lan: true
bind-address: "*"
dns:
  enable: true
  #nameserver-policy:
  default-nameserver:
    - 114.114.114.114
    - 8.8.8.8
  nameserver:
    - https://doh.pub/dns-query
    - https://dns.alidns.com/dns-query
  fallback-filter:
    geoip: true
  enhanced-mode: fake-ip #redir-host
  listen: 0.0.0.0:1053
```

### Description

用域名是走tun模式，但是用ip直接访问流量不走clash，iptable要是设置了redirect到7892端口，流量是走代理了，但是会导致upnp异常，主路由上不设置了lan snat转换，外网没有办法访问里面的机器。设置了nat类型也变化了。tun模式并没有接管所有流量
