### ISSUE TITLE
[Bug] rule-providers配置的初始化和自带DNS服务的问题

### ISSUE THREAD

**Issue by yusiwen** [Dreamacro/clash#1707]
### Verify steps

- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

1.7.1

### What OS are you seeing the problem on?

Linux

### Clash config

```yaml
# 示例配置
dns:
  enable: true
  ...
rule-providers:
  reject:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/reject.txt"
    path: ./ruleset/reject.yaml
    interval: 86400
```

### Clash log

```shell
clash-client | time="2021-11-01T06:47:05Z" level=fatal msg="Parse config error: initial rule provider proxy error: Get \"https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/reject.txt\": lookup cdn.jsdelivr.net 127.0.0.1:53: read: connection refused"
```

### Description

我目前是用Clash自带的DNS服务，把操作系统的systemd-resolvd停掉了，一直用的没问题。今天我看到premium版本有rule-providers的配置功能，就试了一下，发现clash启动时解析配置文件时，会去下载rule-providers配置里指定的文件，但是这时DNS服务还没启动，所以域名解析失败了，进而Clash进程启动失败。

我想问一下各位大佬：clash自带的DNS服务平时各位是怎么使用的，能不能作为系统的默认DNS resolver呢？感觉如果把clash自带的DNS启在非53端口上，有意义么？在iptables里DNS查询流程转发过来的话，能排除clash自己么？
