### ISSUE TITLE
[Bug] ] fullcone with system stack but I get unsupported server with gvisor stack

### ISSUE THREAD

**Issue by fsheidaiee** [Dreamacro/clash#1717]
### Verify steps

- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

Premium 2021.09.15

### What OS are you seeing the problem on?

Windows

### Clash config

```yaml
mixed-port: 7890
allow-lan: true
ipv6: true
mode: Rule
log-level: info
external-controller: 127.0.0.1:8080
external-ui: dashboard
dns:
  enable: true
  listen: 0.0.0.0:1055
  default-nameserver:
    - 1.1.1.1
    - 8.8.8.8
  ipv6: true
  enhanced-mode: redir-host
  nameserver:
    - https://dns.nextdns.io/dns-query
tun:
  enable: true
  stack: gvisor
  dns-hijack:
    - 198.18.0.2:53
  auto-route: true
  auto-detect-interface: true

rules:
  - IP-CIDR,198.18.0.0/15,✅ Direct
  - PROCESS-NAME,AdguardSvc.exe,✅ Direct
  - PROCESS-NAME,uTorrent.exe,✅ Direct
  - PROCESS-NAME,explorer.exe,✅ Direct
  - PROCESS-NAME,terminal64.exe,✅ Direct
  - PROCESS-NAME,Skype.exe,✅ Direct
  - PROCESS-NAME,anydesk.exe,✅ Direct
  - PROCESS-NAME,Clash.exe,✅ Direct
  - PROCESS-NAME,whatsapp.exe,✅ Direct
  - PROCESS-NAME,SamsungFlow.exe,✅ Direct
  - PROCESS-NAME,yogadns.exe,✅ Direct
  - DOMAIN-SUFFIX,IR,✅ Direct
  - DOMAIN-SUFFIX,amazon.com,✅ Direct
  - IP-CIDR,192.168.0.0/16,✅ Direct,no-resolve
  - IP-CIDR,10.0.0.0/8,✅ Direct,no-resolve
  - IP-CIDR,172.16.0.0/12,✅ Direct,no-resolve
  - IP-CIDR,127.0.0.0/8,✅ Direct,no-resolve
  - IP-CIDR,100.64.0.0/10,✅ Direct,no-resolve
  - IP-CIDR6,::1/128,✅ Direct,no-resolve
  - IP-CIDR6,fc00::/7,✅ Direct,no-resolve
  - IP-CIDR6,fe80::/10,✅ Direct,no-resolve
  - IP-CIDR6,fd00::/8,✅ Direct,no-resolve
  - DOMAIN-KEYWORD,clash.razord.top,✅ Direct
  - DOMAIN-KEYWORD,yacd.haishan.me,✅ Direct
```

### Clash log

```shell
21-11-06 15:29:52
info
[UDP] 198.18.0.1:xxxx --> stun.syncthing.net:3478 match Match() using 🔰 Select xxxxx
```

### Description

Hi
I use clash premium with gvisor and wintun.
everything works fine
when I test with net type tester, I get usupported server
![image](https://user-images.githubusercontent.com/74687186/140608927-f0775e28-955e-4627-95ea-c3f594b25204.png)

but with the same server and same config (but only with system stack) I get fullcone in windows 10/11
I hope you can fix this issue.
the reason I use gvisor is that its more compatible with windows and with system stack sometimes I get too much ram usage from clash and the latency also gets higher than gvisor.
thanks
