### ISSUE TITLE
[Bug] Premium 2021.11.08的tun模式与termius的mosh有兼容性问题

### ISSUE THREAD

**Issue by baraja** [Dreamacro/clash#1733]
### Verify steps

- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

Premium 2021.11.08

### What OS are you seeing the problem on?

Windows, Linux

### Clash config

```yaml
我使用mixin切换tun模式，配置如下：
mixin: # object
  tun:
    enable: true
    stack: gvisor
    dns-hijack:
      - 198.18.0.2:53
    auto-route: true
    auto-detect-interface: true
```

### Description

clash更新到Premium 2021.11.08之后，出现了一个奇怪的问题：tun模式下mosh协议ssh登录vps，终端里不显示任何buffer
bug的重现有这几个条件：
一、使用tun模式（无论是system还是gvisor都能重现bug）
二、使用termius的mosh协议（而非ssh协议）ssh登录vps，SSH协议则一切正常
三、退回到前一个版本(2021.09.15)，没有此bug（旧版文件覆盖回来，bug立马消失，新版覆盖回去，bug立马出现）
四、linux和windows下都可以复现该bug（使用的gui均为clash for windows）
五、登录后终端里不显示buffer的情况下，关闭tun模式（使用mixin）则buffer立刻显现。

mosh走的是udp，新版的udp处理是不是可能有些问题？因为前一个版本是完全正常的
