### ISSUE TITLE
据说clash很好，但是不知道配置文件长啥样子，该怎么配置！

### ISSUE THREAD

**Issue by zxlhhyccc** [Dreamacro/clash#175]

**Comment by Dreamacro** [comment]
https://github.com/Dreamacro/clash#config

**Comment by zxlhhyccc** [comment]
这里很多条代码，请问是用哪个直接修改哪个对吗？比如我的是SSR和v2ray（ws+tls），是不是直接修改我需要的相应代码，其他的都不要，保留一些必须的，如：谷歌测试连接。

**Comment by zxlhhyccc** [comment]
还有就是，我看了一下这个规则模板，好像不支持SSR协议，而是支持SS协议！

**Comment by beyondkmp** [comment]
@zxlhhyccc 是的，不支持ssr

**Comment by zxlhhyccc** [comment]
我不喜欢SS，什么时候可以加SSR支持，还有就是如果我只配置v2ray，可是配置模板代码那么多，请问配置文件改怎么做修改？

**Comment by Dreamacro** [comment]
@zxlhhyccc 我不喜欢 SSR，所以不会增加 SSR 的支持。vmess 的问题找到你要的那个配置格式，填上你的 server 信息，删掉其他不需要的配置就行了。

**Comment by lisaac** [comment]
@Dreamacro 借地问一下，关于 DNS 段中的 ipv6 选项

```
dns:
  enable: true # set true to enable dns (default is false)
  ipv6: false # default is false
  ...
```

不知道此选项的作用是什么？ 是否是屏蔽返回的AAAA记录？
我测试了一下，好像不是这个作用。
