### ISSUE TITLE
[Feature] 根据目的地址是IPv4还是IPv6分流

### ISSUE THREAD

**Issue by yuedai** [Dreamacro/clash#1753]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

概述： 在同一个Proxy Group下，某些proxy只处理IPV6流量；其他Proxy可以处理IPv4或者都处理。
解释：
        我用clash主要是翻墙回国内的。我发现一些纯IPV6的VPS价格比较实惠，流量也比较便宜。我的这个需求是，在Proxy Group里选择节点的时候，可以将IPV4流量和IPV6流量分流到不同的Proxy上。

**Comment by yuedai** [comment]
我没有接触过Clash的code base, 不过如果同学们可以给个大概的设计，我愿意尝试写个PR.

**Comment by Dreamacro** [comment]
有个不太严谨的配置可以做到

```yaml
script:
  shortcuts:
    ipv6: "':' in dst_ip or ':' in resolve_ip(host)"

rules:
  - SCRIPT,ipv6,ipv6Proxy
```
