### ISSUE TITLE
[Bug] 缓存持久化降低响应DNS速度

### ISSUE THREAD

**Issue by InsOnYou** [Dreamacro/clash#1775]
### Verify steps

- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

2021.11.08

### What OS are you seeing the problem on?

Linux

### Clash config

```yaml
rule-providers:
  TikTok:
    type: http
    behavior: classical
    path: "/etc/openclash/rule_provider/TikTok.yaml"
    url: https://cdn.jsdelivr.net/gh/DivineEngine/Profiles@master/Clash/RuleSet/StreamingMedia/Video/TikTok.yaml
    interval: 86400

  Netflix(By lhie1):
    type: http
    behavior: classical
    path: "/etc/openclash/rule_provider/Netflix-lhie1.yaml"
    url: https://cdn.jsdelivr.net/gh/lhie1/Rules@master/Clash/Provider/Media/Netflix.yaml
    interval: 86400

  Netflix:
    type: http
    behavior: classical
    path: "/etc/openclash/rule_provider/Netflix.yaml"
    url: https://cdn.jsdelivr.net/gh/DivineEngine/Profiles@master/Clash/RuleSet/StreamingMedia/Video/Netflix.yaml
    interval: 86400

  icloud:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/icloud.txt"
    path: ./ruleset/icloud.yaml
    interval: 86400

  apple:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/apple.txt"
    path: ./ruleset/apple.yaml
    interval: 86400

  direct:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/direct.txt"
    path: ./ruleset/direct.yaml
    interval: 86400

  private:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/private.txt"
    path: ./ruleset/private.yaml
    interval: 86400

  proxy:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/proxy.txt"
    path: ./ruleset/proxy.yaml
    interval: 86400

rules:
  - IP-CIDR,211.138.180.2/32,DIRECT,no-resolve
  - SRC-IP-CIDR,192.168.2.128/25,DIRECT
  
  - IP-CIDR,0.0.0.0/8,DIRECT,no-resolve
  - IP-CIDR,10.0.0.0/8,DIRECT,no-resolve
  - IP-CIDR,100.64.0.0/10,DIRECT,no-resolve
  - IP-CIDR,127.0.0.0/8,DIRECT,no-resolve
  - IP-CIDR,169.254.0.0/16,DIRECT,no-resolve
  - IP-CIDR,172.16.0.0/12,DIRECT,no-resolve
  - IP-CIDR,192.0.0.0/24,DIRECT,no-resolve
  - IP-CIDR,192.0.2.0/24,DIRECT,no-resolve
  - IP-CIDR,192.88.99.0/24,DIRECT,no-resolve
  - IP-CIDR,192.168.0.0/16,DIRECT,no-resolve
  - IP-CIDR,198.18.0.0/15,DIRECT,no-resolve
  - IP-CIDR,198.51.100.0/24,DIRECT,no-resolve
  - IP-CIDR,203.0.113.0/24,DIRECT,no-resolve
  - IP-CIDR,224.0.0.0/3,DIRECT,no-resolve
  - IP-CIDR6,::1/128,DIRECT,no-resolve
  - IP-CIDR6,fc00::/7,DIRECT,no-resolve
  - IP-CIDR6,fe80::/10,DIRECT,no-resolve
  - IP-CIDR6,fd00::/8,DIRECT,no-resolve
  
  - RULE-SET,private,DIRECT
  
  - DOMAIN-SUFFIX,i.passcloud.xyz,DIRECT
  - DOMAIN-SUFFIX,265.com,PROXY
  - DOMAIN-SUFFIX,2mdn.net,PROXY
  - DOMAIN-SUFFIX,adservice.google.com,PROXY
  - DOMAIN-SUFFIX,app-measurement.com,PROXY
  - DOMAIN-SUFFIX,beacons.gcp.gvt2.com,PROXY
  - DOMAIN-SUFFIX,beacons.gvt2.com,PROXY
  - DOMAIN-SUFFIX,beacons2.gvt2.com,PROXY
  - DOMAIN-SUFFIX,beacons3.gvt2.com,PROXY
  - DOMAIN-SUFFIX,c.admob.com,PROXY
  - DOMAIN-SUFFIX,c.android.clients.google.com,PROXY
  - DOMAIN-SUFFIX,cache.pack.google.com,PROXY
  - DOMAIN-SUFFIX,checkin.gstatic.com,PROXY
  - DOMAIN-SUFFIX,clickserve.dartsearch.net,PROXY
  - DOMAIN-SUFFIX,clientservices.googleapis.com,PROXY
  - DOMAIN-SUFFIX,connectivitycheck.gstatic.com,PROXY
  - DOMAIN-SUFFIX,corp.google.com,PROXY
  - DOMAIN-SUFFIX,crl.pki.goog,PROXY
  - DOMAIN-SUFFIX,csi.gstatic.com,PROXY
  - DOMAIN-SUFFIX,dl.google.com,PROXY
  - DOMAIN-SUFFIX,dl.l.google.com,PROXY
  - DOMAIN-SUFFIX,doubleclick.net,PROXY
  - DOMAIN-SUFFIX,firebase-settings.crashlytics.com,PROXY
  - DOMAIN-SUFFIX,fonts.googleapis.com,PROXY
  - DOMAIN-SUFFIX,fonts.gstatic.com,PROXY
  - DOMAIN-SUFFIX,g1.gstatic.com,PROXY
  - DOMAIN-SUFFIX,g2.gstatic.com,PROXY
  - DOMAIN-SUFFIX,google-analytics.com,PROXY
  - DOMAIN-SUFFIX,googleadservices.com,PROXY
  - DOMAIN-SUFFIX,googleanalytics.com,PROXY
  - DOMAIN-SUFFIX,googleoptimize.com,PROXY
  - DOMAIN-SUFFIX,googlesyndication.com,PROXY
  - DOMAIN-SUFFIX,googletagmanager.com,PROXY
  - DOMAIN-SUFFIX,googletagservices.com,PROXY
  - DOMAIN-SUFFIX,gstaticadssl.l.google.com,PROXY
  - DOMAIN-SUFFIX,gtm.oasisfeng.com,PROXY
  - DOMAIN-SUFFIX,imasdk.googleapis.com,PROXY
  - DOMAIN-SUFFIX,ocsp.pki.goog,PROXY
  - DOMAIN-SUFFIX,pagead-googlehosted.l.google.com,PROXY
  - DOMAIN-SUFFIX,pki-goog.l.google.com,PROXY
  - DOMAIN-SUFFIX,recaptcha.net,PROXY
  - DOMAIN-SUFFIX,redirector.gvt1.com,PROXY
  - DOMAIN-SUFFIX,regioninfo-pa.googleapis.com,PROXY
  - DOMAIN-SUFFIX,safebrowsing-cache.google.com,PROXY
  - DOMAIN-SUFFIX,safebrowsing.googleapis.com,PROXY
  - DOMAIN-SUFFIX,ssl-google-analytics.l.google.com,PROXY
  - DOMAIN-SUFFIX,ssl.gstatic.com,PROXY
  - DOMAIN-SUFFIX,toolbarqueries.google.com,PROXY
  - DOMAIN-SUFFIX,tools.google.com,PROXY
  - DOMAIN-SUFFIX,tools.l.google.com,PROXY
  - DOMAIN-SUFFIX,translate.googleapis.com,PROXY
  - DOMAIN-SUFFIX,translation.googleapis.com,PROXY
  - DOMAIN-SUFFIX,update.googleapis.com,PROXY
  - DOMAIN-SUFFIX,www-google-analytics.l.google.com,PROXY
  - DOMAIN-SUFFIX,www-googletagmanager.l.google.com,PROXY
  - DOMAIN-SUFFIX,www.gstatic.com,PROXY

  - DOMAIN-SUFFIX,bamgrid.com,Disney+
  - DOMAIN-SUFFIX,disneyplus.com,Disney+
  - DOMAIN-SUFFIX,disney-plus.net,Disney+
  - DOMAIN-SUFFIX,disneystreaming.com,Disney+
  - DOMAIN-SUFFIX,dssott.com,Disney+
  - DOMAIN,cdn.registerdisney.go.com,Disney+

  - RULE-SET,Netflix(By lhie1),Netflix
  - RULE-SET,Netflix,Netflix
  - RULE-SET,TikTok,Tiktok
  - RULE-SET,icloud,DIRECT
  - RULE-SET,apple,DIRECT
  - RULE-SET,direct,DIRECT
  - RULE-SET,proxy,PROXY
  - GEOIP,CN,DIRECT
  - GEOIP,US,🇺🇸US
  - MATCH,PROXY

proxy-groups:
- name: PROXY
  type: select
  proxies:
  - DIRECT
  use:
  - SPCloud
  - iQZone
  - SPss
- name: Netflix
  type: select
  proxies:
  - PROXY
  use:
  - SPCloud
  - iQZone
- name: Disney+
  type: select
  proxies:
  - PROXY
  use:
  - SPCloud
  - iQZone
- name: Tiktok
  type: select
  proxies:
  - PROXY
  - DIRECT
  use:
  - SPCloud
- name: 🇺🇸US
  type: select
  proxies:
  - PROXY
  use:
  - SPCloud
  - iQZone
- name: Final
  type: select
  proxies:
  - PROXY
  - DIRECT
```

### Description

使用2021.11.08的tun版本，开启fake-ip和缓存持久化，clash需要花费30ms-100ms来响应DNS请求。关闭缓存持久化后响应时间在2ms以内。
