### ISSUE TITLE
[Feature] failover and load balance in proxy group

### ISSUE THREAD

**Issue by modaresimr** [Dreamacro/clash#1784]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

in proxy group we can add several proxy and set the type to failover or load balance

but Is there any possibility to have failover and load balance together? it means that load-balance the available proxies

### Possible Solution

```
proxy-groups:
   - name: Proxy
     proxies:
       - p1
       - p2
       - p3
     type: load-balance+fallback
     url: http://www.gstatic.com/generate_204
     interval: 600
```
