### ISSUE TITLE
ubuntu 20.04    clash-linux-amd64-v1.8.0.gz   启动出现问题

### ISSUE THREAD

**Issue by liuyatian** [Dreamacro/clash#1785]
### Verify steps

- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

clash-linux-amd64-v1.8.0

### What OS are you seeing the problem on?

Linux

### Clash config

```yaml
#---------------------------------------------------#

# HTTP 代理端口
port: 7890

# SOCKS5 代理端口
socks-port: 7891

# Linux 和 macOS 的 redir 代理端口
redir-port: 7892

# 允许局域网的连接
allow-lan: true

# 规则模式：Rule（规则） / Global（全局代理）/ Direct（全局直连）
mode: Rule

# 设置日志输出级别 (默认级别：silent，即不输出任何内容，以避免因日志内容过大而导致程序内存溢出）。
# 5 个级别：silent / info / warning / error / debug。级别越高日志输出量越大，越倾向于调试，若需要请自行开启。log-level: silent
# Clash 的 RESTful API
external-controller: '0.0.0.0:9090'

# RESTful API 的口令
secret: ''

# 您可以将静态网页资源（如 clash-dashboard）放置在一个目录中，clash 将会服务于 `RESTful API/ui`
# 参数应填写配置目录的相对路径或绝对路径。
# external-ui: folder
```

### Clash log

```shell
INFO[0000] Start initial compatible provider Proxy      
INFO[0000] Start initial compatible provider Domestic   
INFO[0000] Start initial compatible provider GlobalTV   
INFO[0000] Start initial compatible provider AsianTV    
INFO[0000] Start initial compatible provider Others
```

### Description

按照教程操作 clash 出现问题
![2021-11-29 17-56-46 的屏幕截图](https://user-images.githubusercontent.com/29629414/143846722-b0dcb64b-973f-49a6-9102-3c9d7e633360.png)
![2021-11-29 17-58-20 的屏幕截图](https://user-images.githubusercontent.com/29629414/143846937-870a1c23-cb5c-4e21-94dd-4ffb1dc5a2d9.png)
现在进行到第四步的时候，变成这样
![2021-11-29 18-00-35 的屏幕截图](https://user-images.githubusercontent.com/29629414/143847233-b1c5eacb-d772-4393-9ad5-ecb0385aa6e5.png)
但是一直停留在这个画面，点确认也不好使
![2021-11-29 18-01-54 的屏幕截图](https://user-images.githubusercontent.com/29629414/143847461-53c3e419-4f34-4bb0-bb0f-36b8b03219a2.png)
请各位指点一下
