### ISSUE TITLE
[Bug] PROCESS-NAME规则的匹配问题

### ISSUE THREAD

**Issue by returnL** [Dreamacro/clash#1789]
### Verify steps

- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

Premium 2021.11.08

### What OS are you seeing the problem on?

Windows

### Clash config

```yaml
tun:
    enable: true
    stack: system
    dns-hijack:
      - 198.18.0.2:53
    auto-route: true
    auto-detect-interface: true

rules:
  - PROCESS-NAME,uTorrent,DIRECT
  - PROCESS-NAME,uTorrent.exe,DIRECT
  - DOMAIN-SUFFIX,tjupt.org,China-Websites
  - GEOIP,CN,China-Websites
  - MATCH,Final
```

### Clash log

```shell
time="2021-11-30T22:27:52+08:00" level=info msg="[TCP] 198.18.0.1:1066 --> tracker-public.tjupt.org:443 match DomainSuffix(tjupt.org) using China-Websites[DIRECT]"
time="2021-11-30T22:27:53+08:00" level=info msg="[TCP] 198.18.0.1:1057 --> tracker-public.tjupt.org:443 match DomainSuffix(tjupt.org) using China-Websites[DIRECT]"
```

### Description

在开启了TUN模式的状态下，我对uTorrent.exe使用PROCESS-NAME规则使其直连，但该规则似乎并未生效，log显示的匹配到了其他规则。

在uTorrent.exe中，下载时一些连接匹配到了`GEOIP,CN,China-Websites`走了直连，更新tracker时匹配到了`DOMAIN-SUFFIX,tjupt.org,China-Websites`走了直连。但是`PROCESS-NAME,uTorrent.exe,DIRECT`是写在最前面的，应该到该命令时就已经能判断走直连了，不会再看后面的规则。

之前的版本log显示的都是匹配到了`PROCESS-NAME,uTorrent.exe,DIRECT`规则，不知最近的更新是否有修改影响到了这部分

当我把`DOMAIN-SUFFIX,tjupt.org,China-Websites`注释掉之后，再更新tracker便走了代理，`PROCESS-NAME,uTorrent.exe,DIRECT`失效了
