### ISSUE TITLE
[Feature] nftables 设置透明代理后不显示域名/文档补全

### ISSUE THREAD

**Issue by Yakkhini** [Dreamacro/clash#1801]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

我在我的机器上，使用nftables做透明代理，把流量转给了clash。这是我的nftables代理设置：

```
#!/usr/bin/nft -f
# vim:set ts=2 sw=2 et:

include "/etc/nftables/private.nft"

table ip nat {
	chain proxy {
		ip daddr $private_list accept
		meta skuid clash accept
		ip protocol tcp redirect to :7892
#		ip protocol udp redirect to :7892
	}

	chain output {
		type nat hook output priority filter; policy accept;
		goto proxy
	}

	chain prerouting {
		type nat hook prerouting priority dstnat; policy accept;
		goto proxy
	}
}

table ip mangle {
	chain filter {
		ip daddr $private_list accept
		meta skuid clash accept
		return
	}

	chain output {
		type route hook output priority mangle; policy accept;
		jump filter
		ip protocol udp mark set 0x233
	}

	chain prerouting {
		type filter hook prerouting priority mangle; policy accept;
		jump filter
		ip protocol udp tproxy to 127.0.0.1:7892
	}
}
```

（ip rules 和 ip route 已经正确设置过，此处省略。）

但是问题在于，在clash后台无法显示我想访问网站的域名，也没有做dns代理。
![vortexlove@20211205165449](https://user-images.githubusercontent.com/59007159/144740137-d5ae14bb-bcea-4dab-8afc-10e7c0844752.png)
![vortexlove@20211205165459](https://user-images.githubusercontent.com/59007159/144740141-70bef913-1c69-4424-bfd0-6a1150c411da.png)

我想是因为我在nftables中的设置缺少了dns对53端口的特定转发，导致的这种情况。这一问题导致的直接结果是我在clash中设置的域名规则（domain-suffix, domain...?)全部失效。

我在网上和这里的各个issue中寻找正确的nftables设置方式，但是它们往往是iptables的设置形式，或者缺少dns流量的正确配置内容。在此希望大家不吝赐教，我该怎样配置我的nftables呢？

ps. 不管是nftables，还是iptables，对于普通用户来说它们的配置都有些艰难。同时透明代理在linux中其实很重要（环境变量设置proxy的方式无法代理udp包）。同时，这两者的配置文件其实不会因个人电脑状况的不同而产生太大差异。所以我建议，能否将透明代理的正确方式（至少是iptables，nftables的正确配置方式）写入本项目的wiki？如果可以的话，应该能帮到很多人。谢谢大家！

### Possible Solution

2021.12.10：

这几天一直在研究，终于写出了在本机做透明代理的nftables文件。我贴在这里，希望可以帮到其他人：
```
table ip nat {
  chain output {
    type nat hook output priority filter; policy accept;
    ip daddr 127.0.0.1/8 counter return
    ip protocol tcp ip daddr 8.8.8.8 counter redirect to :7892
    ip protocol tcp ip daddr 1.1.1.1 counter redirect to :7892
    ip protocol tcp ip daddr 1.0.0.1 counter redirect to :7892
    meta skuid clash counter return
    ip protocol tcp counter redirect to :7892
    udp dport 53 counter redirect to :1053
  }
  chain prerouting {
    type nat hook prerouting priority dstnat; policy accept;
    ip protocol tcp counter redirect to :7892
    udp dport 53 counter redirect to :1053
    tcp dport 7892 counter
    tcp dport 53 counter
    meta skuid clash counter return
  }
  chain debug {
    type filter hook prerouting priority filter; policy accept;
    meta skuid clash counter
    ip protocol tcp counter
    tcp dport 7892 counter
    udp dport 1053 counter
    udp dport 53 counter
  }
}

table ip mangle {
    chain output {
      type route hook output priority mangle; policy accept;
      ip daddr 127.0.0.1/8 counter return
      ip daddr 224.0.0.0/4 counter return
      ip daddr 192.168.0.0/16 counter return
      meta skuid clash counter return
      udp dport 53 counter return
      ip protocol udp counter mark set 1
  }
    chain prerouting {
      type filter hook prerouting priority mangle; policy accept;
      ip daddr 127.0.0.1/8 counter return
      ip daddr 224.0.0.0/4 counter return
      ip daddr 192.168.0.0/16 counter return
      meta skuid clash counter return
      udp dport 53 counter return
      udp dport 1053 counter return
      ip protocol udp tproxy to 127.0.0.1:7892
  }
}

```

关键在于，普通udp的dns请求可能会被污染，所以尽量使用doh的server name. 

```
dns:
  enable: true # set true to enable dns (default is false)
  ipv6: false # default is false
  listen: 0.0.0.0:1053
  nameserver: # resolve dns nameserver host, should fill pure IP
    - https://223.5.5.5/dns-query
    - https://doh.pub/dns-query
  fallback:
    - https://1.1.1.1/dns-query
    - https://1.0.0.1/dns-query
    - https://8.8.8.8/dns-query
  fallback-filter:
    geoip: true                  # default
    geoip-code: CN
```

但仅仅这样，fallback中的dns请求（clash的fallback默认直连）会因为被墙所以请求失败。所以在nftables中也要特定地设置目的地是dns服务器ip的连接会被代理。

```
table ip nat {
  chain output {
    type nat hook output priority filter; policy accept;
    ip daddr 127.0.0.1/8 counter return
    ip protocol tcp ip daddr 8.8.8.8 counter redirect to :7892
    ip protocol tcp ip daddr 1.1.1.1 counter redirect to :7892
    ip protocol tcp ip daddr 1.0.0.1 counter redirect to :7892
```

同理，如果使用其他dns server，只要是国外的server都需要在nftables设置文件中设置重定向到代理端口。（如果使用的是iptables，也一样。）

注意这个要写在clash用户过滤规则之前，因为dns请求是clash发出的。

至于局域网连接的回环问题，由于网上查到的各种配置文件大多的形式都非本机自己代理的配置，所以我一次一次试出来了以上几个写进去的ip规则。如果有人参考我这份文件出现了局域网流量回环问题，把造成回环的目的ip写入规则就行了。

至于ip rule ip route 的配置，网上很好查到，就不赘述了。感谢在网上写教程和向我解答的各位，在本项目的issue讨论中学到了很多。如果我的理解有错误，欢迎大家指出纠正。

_No response_

**Comment by thank243** [comment]
使用ipt直接劫持53 udp到clash的dns端口或者dnsmasq直接劫持

**Comment by Yakkhini** [comment]
> 使用ipt直接劫持53 udp到clash的dns端口或者dnsmasq直接劫持

请问详细的配置文件怎么写呢，我使用的是nft

**Comment by thank243** [comment]
> > 使用ipt直接劫持53 udp到clash的dns端口或者dnsmasq直接劫持
> 
> 请问详细的配置文件怎么写呢，我使用的是nft

请不要做伸手党，pro x项目里面官方文档有写。

**Comment by Yakkhini** [comment]
> > > 使用ipt直接劫持53 udp到clash的dns端口或者dnsmasq直接劫持
> > 
> > 
> > 请问详细的配置文件怎么写呢，我使用的是nft
> 
> 请不要做伸手党，pro x项目里面官方文档有写。

抱歉，感谢你的回复。

**Comment by Yakkhini** [comment]
这几天一直在研究，终于写出了在本机做透明代理的nftables文件。我贴在这里，希望可以帮到其他人：
```
table ip nat {
  chain output {
    type nat hook output priority filter; policy accept;
    ip daddr 127.0.0.1/8 counter return
    ip protocol tcp ip daddr 8.8.8.8 counter redirect to :7892
    ip protocol tcp ip daddr 1.1.1.1 counter redirect to :7892
    ip protocol tcp ip daddr 1.0.0.1 counter redirect to :7892
    meta skuid clash counter return
    ip protocol tcp counter redirect to :7892
    udp dport 53 counter redirect to :1053
  }
  chain prerouting {
    type nat hook prerouting priority dstnat; policy accept;
    ip protocol tcp counter redirect to :7892
    udp dport 53 counter redirect to :1053
    tcp dport 7892 counter
    tcp dport 53 counter
    meta skuid clash counter return
  }
  chain debug {
    type filter hook prerouting priority filter; policy accept;
    meta skuid clash counter
    ip protocol tcp counter
    tcp dport 7892 counter
    udp dport 1053 counter
    udp dport 53 counter
  }
}

table ip mangle {
    chain output {
      type route hook output priority mangle; policy accept;
      ip daddr 127.0.0.1/8 counter return
      ip daddr 224.0.0.0/4 counter return
      ip daddr 192.168.0.0/16 counter return
      meta skuid clash counter return
      udp dport 53 counter return
      ip protocol udp counter mark set 1
  }
    chain prerouting {
      type filter hook prerouting priority mangle; policy accept;
      ip daddr 127.0.0.1/8 counter return
      ip daddr 224.0.0.0/4 counter return
      ip daddr 192.168.0.0/16 counter return
      meta skuid clash counter return
      udp dport 53 counter return
      udp dport 1053 counter return
      ip protocol udp tproxy to 127.0.0.1:7892
  }
}

```

关键在于，普通udp的dns请求可能会被污染，所以尽量使用doh的server name. 

```
dns:
  enable: true # set true to enable dns (default is false)
  ipv6: false # default is false
  listen: 0.0.0.0:1053
  nameserver: # resolve dns nameserver host, should fill pure IP
    - https://223.5.5.5/dns-query
    - https://doh.pub/dns-query
  fallback:
    - https://1.1.1.1/dns-query
    - https://1.0.0.1/dns-query
    - https://8.8.8.8/dns-query
  fallback-filter:
    geoip: true                  # default
    geoip-code: CN
```

但仅仅这样，fallback中的dns请求（clash的fallback默认直连）会因为被墙所以请求失败。所以在nftables中也要特定地设置目的地是dns服务器ip的连接会被代理。

```
table ip nat {
  chain output {
    type nat hook output priority filter; policy accept;
    ip daddr 127.0.0.1/8 counter return
    ip protocol tcp ip daddr 8.8.8.8 counter redirect to :7892
    ip protocol tcp ip daddr 1.1.1.1 counter redirect to :7892
    ip protocol tcp ip daddr 1.0.0.1 counter redirect to :7892
```

同理，如果使用其他dns server，只要是国外的server都需要在nftables设置文件中设置重定向到代理端口。（如果使用的是iptables，也一样。）

注意这个要写在clash用户过滤规则之前，因为dns请求是clash发出的。

至于局域网连接的回环问题，由于网上查到的各种配置文件大多的形式都非本机自己代理的配置，所以我一次一次试出来了以上几个写进去的ip规则。如果有人参考我这份文件出现了局域网流量回环问题，把造成回环的目的ip写入规则就行了。

至于ip rule ip route 的配置，网上很好查到，就不赘述了。感谢在网上写教程和向我解答的各位，在本项目的issue讨论中学到了很多。如果我的理解有错误，欢迎大家指出纠正。
