### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by paladin4fan** [Dreamacro/clash#1809]
### Verify steps

- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

2021.11.08 premium

### Clash config

```yaml
---
port: 7890
socks-port: 7891
allow-lan: true
mode: rule
log-level: silent
external-controller: 0.0.0.0:9090
proxies:
proxy-groups:
rules:
dns:
  nameserver:
  - 119.28.28.28
  - 223.6.6.6
  fallback:
  - tls://8.8.8.8:853
  - 9.9.9.9
  - https://208.67.220.220
  enable: true
  ipv6: true
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  listen: 0.0.0.0:7874
  fake-ip-filter:
  - "*.lan"
  - "*.localdomain"
  - "*.example"
  - "*.invalid"
  - "*.localhost"
  - "*.test"
  - "*.local"
  - "*.home.arpa"
  - time.*.com
  - time.*.gov
  - time.*.edu.cn
  - time.*.apple.com
  - time1.*.com
  - time2.*.com
  - time3.*.com
  - time4.*.com
  - time5.*.com
  - time6.*.com
  - time7.*.com
  - ntp.*.com
  - ntp1.*.com
  - ntp2.*.com
  - ntp3.*.com
  - ntp4.*.com
  - ntp5.*.com
  - ntp6.*.com
  - ntp7.*.com
  - "*.time.edu.cn"
  - "*.ntp.org.cn"
  - "+.pool.ntp.org"
  - time1.cloud.tencent.com
  - music.163.com
  - "*.music.163.com"
  - "*.126.net"
  - musicapi.taihe.com
  - music.taihe.com
  - songsearch.kugou.com
  - trackercdn.kugou.com
  - "*.kuwo.cn"
  - api-jooxtt.sanook.com
  - api.joox.com
  - joox.com
  - y.qq.com
  - "*.y.qq.com"
  - streamoc.music.tc.qq.com
  - mobileoc.music.tc.qq.com
  - isure.stream.qqmusic.qq.com
  - dl.stream.qqmusic.qq.com
  - aqqmusic.tc.qq.com
  - amobile.music.tc.qq.com
  - "*.xiami.com"
  - "*.music.migu.cn"
  - music.migu.cn
  - "*.msftconnecttest.com"
  - "*.msftncsi.com"
  - msftconnecttest.com
  - msftncsi.com
  - localhost.ptlogin2.qq.com
  - localhost.sec.qq.com
  - "+.srv.nintendo.net"
  - "+.stun.playstation.net"
  - xbox.*.microsoft.com
  - xnotify.xboxlive.com
  - "+.battlenet.com.cn"
  - "+.wotgame.cn"
  - "+.wggames.cn"
  - "+.wowsgame.cn"
  - "+.wargaming.net"
  - proxy.golang.org
  - stun.*.*
  - stun.*.*.*
  - "+.stun.*.*"
  - "+.stun.*.*.*"
  - "+.stun.*.*.*.*"
  - heartbeat.belkin.com
  - "*.linksys.com"
  - "*.linksyssmartwifi.com"
  - "*.router.asus.com"
  - mesu.apple.com
  - swscan.apple.com
  - swquery.apple.com
  - swdownload.apple.com
  - swcdn.apple.com
  - swdist.apple.com
  - lens.l.google.com
  - stun.l.google.com
  - "*.discordapp.com"
  - "*.discord.media"
  default-nameserver:
  - 119.28.28.28
  - 223.6.6.6
  - 9.9.9.9
redir-port: 7892
tproxy-port: 7895
mixed-port: 7893
secret: '123456'
bind-address: "*"
external-ui: "/usr/share/openclash/dashboard"
ipv6: true
tun:
  enable: true
  stack: system
  dns-hijack:
  - tcp://8.8.8.8:53
  - tcp://8.8.4.4:53
profile:
  store-selected: true
  store-fake-ip: true
```

### Clash log

```shell
time="2021-12-09T12:45:12+08:00" level=info msg="RESTful API listening at: 127.0.0.1:14579"
time="2021-12-09T12:45:12+08:00" level=info msg="Mixed(http+socks) proxy listening at: 127.0.0.1:7890"
time="2021-12-09T12:45:14+08:00" level=info msg="Start initial compatible provider 🎥 NETFLIX"
time="2021-12-09T12:45:14+08:00" level=info msg="Start initial compatible provider 🎮 游戏服务"
time="2021-12-09T12:45:14+08:00" level=info msg="Start initial compatible provider 🎯 全球直连"
time="2021-12-09T12:45:14+08:00" level=info msg="Start initial compatible provider ♻️ 自动选择"
time="2021-12-09T12:45:14+08:00" level=info msg="Start initial compatible provider 🔰 节点选择"
time="2021-12-09T12:45:14+08:00" level=info msg="Start initial compatible provider 🛑 全球拦截"
time="2021-12-09T12:45:14+08:00" level=info msg="Start initial compatible provider 🐟 漏网之鱼"
time="2021-12-09T12:45:19+08:00" level=info msg="Start initial compatible provider 🐟 漏网之鱼"
time="2021-12-09T12:45:19+08:00" level=info msg="Start initial compatible provider 🛑 全球拦截"
time="2021-12-09T12:45:19+08:00" level=info msg="Start initial compatible provider 🎯 全球直连"
time="2021-12-09T12:45:19+08:00" level=info msg="Start initial compatible provider ♻️ 自动选择"
time="2021-12-09T12:45:19+08:00" level=info msg="Start initial compatible provider 🔰 节点选择"
time="2021-12-09T12:45:19+08:00" level=info msg="Start initial compatible provider 🎮 游戏服务"
time="2021-12-09T12:45:19+08:00" level=info msg="Start initial compatible provider 🎥 NETFLIX"
time="2021-12-09T12:45:19+08:00" level=debug msg="Generate GUID: {330EAEF8-7578-5DF2-D97B-8DADC0EA85CB}"
time="2021-12-09T12:45:19+08:00" level=info msg="Tun Proxy listening at: Clash(198.18.0.1)"
time="2021-12-09T12:45:19+08:00" level=debug msg="[Stack] Failed to dummy bind, retry in 1 second... (1/10)"
time="2021-12-09T12:45:20+08:00" level=debug msg="[Stack] Failed to dummy bind, retry in 1 second... (2/10)"
time="2021-12-09T12:45:21+08:00" level=info msg="[TCP] 127.0.0.1:14802 --> mtalk.google.com:5228 match Domain(mtalk.google.com) using 🎯 全球直连[DIRECT]"
time="2021-12-09T12:45:21+08:00" level=debug msg="[Stack] Failed to dummy bind, retry in 1 second... (3/10)"
time="2021-12-09T12:45:22+08:00" level=info msg="[TCP] 127.0.0.1:14808 --> ims-prod06.adobelogin.com:443 match Match() using 🐟 漏网之鱼[DIRECT]"
time="2021-12-09T12:45:23+08:00" level=debug msg="[Stack] Failed to dummy bind, retry in 1 second... (4/10)"
time="2021-12-09T12:45:23+08:00" level=info msg="[TCP] 127.0.0.1:14890 --> ims-prod06.adobelogin.com:443 match Match() using 🐟 漏网之鱼[DIRECT]"
time="2021-12-09T12:45:24+08:00" level=debug msg="[Stack] Address %!w(net.IP=[198 18 0 1]) ready for bind"
time="2021-12-09T12:45:24+08:00" level=info msg="[TCP] 127.0.0.1:13179 --> discord.com:443 match DomainSuffix(discord.com) using 🔰 节点选择[🇭🇰 Azure 香港XXXX]"
time="2021-12-09T12:45:24+08:00" level=info msg="[TCP] 127.0.0.1:13221 --> mtalk.google.com:5228 match Domain(mtalk.google.com) using 🎯 全球直连[DIRECT]"
time="2021-12-09T12:45:25+08:00" level=info msg="[TCP] 127.0.0.1:3058 --> santa-clara48.discord.media:443 match DomainSuffix(discord.media) using 🔰 节点选择[🇭🇰 Azure 香港XXXX]"
time="2021-12-09T12:45:26+08:00" level=info msg="[TCP] 127.0.0.1:3089 --> whois.pconline.com.cn:443 match Match() using 🐟 漏网之鱼[DIRECT]"
time="2021-12-09T12:45:26+08:00" level=info msg="[TCP] 127.0.0.1:3091 --> myip.ipip.net:80 match Match() using 🐟 漏网之鱼[DIRECT]"
time="2021-12-09T12:45:26+08:00" level=info msg="[TCP] 127.0.0.1:3092 --> www.baidu.com:443 match Match() using 🐟 漏网之鱼[DIRECT]"
time="2021-12-09T12:45:26+08:00" level=info msg="[TCP] 127.0.0.1:3093 --> s1.music.126.net:443 match Match() using 🐟 漏网之鱼[DIRECT]"
time="2021-12-09T12:45:26+08:00" level=info msg="[TCP] 127.0.0.1:3094 --> github.com:443 match DomainKeyword(github) using 🔰 节点选择[🇭🇰 Azure 香港 XXXX]"
time="2021-12-09T12:45:26+08:00" level=info msg="[TCP] 127.0.0.1:3096 --> www.youtube.com:443 match DomainKeyword(youtube) using 🔰 节点选择[🇭🇰 Azure 香港 XXXX]"
time="2021-12-09T12:45:26+08:00" level=info msg="[TCP] 127.0.0.1:3090 --> api-ipv4.ip.sb:443 match Match() using 🐟 漏网之鱼[DIRECT]"
time="2021-12-09T12:45:26+08:00" level=info msg="[TCP] 127.0.0.1:3095 --> api.ipify.org:443 match Match() using 🐟 漏网之鱼[DIRECT]"
time="2021-12-09T12:45:35+08:00" level=info msg="[TCP] 127.0.0.1:7822 --> santa-clara48.discord.media:443 match DomainSuffix(discord.media) using 🔰 节点选择[🇭🇰 Azure 香港 XXXX]"
time="2021-12-09T12:45:46+08:00" level=info msg="[TCP] 127.0.0.1:11805 --> santa-clara48.discord.media:443 match DomainSuffix(discord.media) using 🔰 节点选择[🇭🇰 Azure 香港 XXXX]"
time="2021-12-09T12:45:55+08:00" level=info msg="[TCP] 127.0.0.1:9006 --> www.showroom-live.com:443 match Match() using 🐟 漏网之鱼[DIRECT]"
time="2021-12-09T12:45:55+08:00" level=info msg="[TCP] 127.0.0.1:9007 --> www.showroom-live.com:443 match Match() using 🐟 漏网之鱼[DIRECT]"
time="2021-12-09T12:45:57+08:00" level=info msg="[TCP] 127.0.0.1:11256 --> santa-clara48.discord.media:443 match DomainSuffix(discord.media) using 🔰 节点选择[🇭🇰 Azure 香港 XXXX]"
time="2021-12-09T12:46:04+08:00" level=info msg="[TCP] 127.0.0.1:3520 --> activity.windows.com:443 match Match() using 🐟 漏网之鱼[DIRECT]"
time="2021-12-09T12:46:22+08:00" level=info msg="[TCP] 127.0.0.1:10835 --> santa-clara9683.discord.media:443 match DomainSuffix(discord.media) using 🔰 节点选择[🇨🇳 中国-台湾 XXXX ]"
time="2021-12-09T12:46:26+08:00" level=info msg="[TCP] 127.0.0.1:10839 --> safebrowsing.googleapis.com:443 match DomainKeyword(google) using 🔰 节点选择[🇨🇳 中国-台湾 XXXX]"
```

### Description

试过OpenClash和Clash for windows
Openclash开启Tun mode或者勾选UDP转发
CFW启动TUN MODE
就会链接不上discord的语音频道 报错“没有路径”
Openclash的web面板中 有命中的UDP链接 但是没有流量
CFW的web面板里直接看不到任何UDP流量
关闭TUN模式后可以连上语音频道
