### ISSUE TITLE
增加 dns cache 持久化功能？

### ISSUE THREAD

**Issue by qiangd6** [Dreamacro/clash#181]
hi，clash是个非常棒的工具，我自己家的主路由已经装了clash，非常好，谢谢作者的工作！

目前有个问题，我想分流局域网内某一个特定ip的所有tcp连接（因故无法再该设备上设置http代理，其他的设备都设置了clash的http代理）那我在用clash的dns结合enhanced-mode: redir-host来做到这一点，因此整个局域网里的设备都需要用clash的DNS来解析，时不时会碰到解析较慢的情况发生，请问能否增加dns解析结果的cache功能？

再次感谢！

**Comment by Dreamacro** [comment]
现在的解析就是带有 cache 的, 你可以通过 dig 的 ttl 来判断

**Comment by qiangd6** [comment]
> 现在的解析就是带有 cache 的, 你可以通过 dig 的 ttl 来判断

hi，谢谢你的回复，我还有个问题 ^_^

一开始我家的方案是disable了clash的dns，只用http和socks5代理，根据域名分流，iPhone把http代理设置好即可，完美；

后来想在电视盒子上airplay看ytb，然而盒子无法设置全局http代理，就在主路由器（openwrt x86）上开了clash的dns和redir；在iptables里把盒子ip的tcp链接都redirect给redir端口，但这种情况下，clash的dns的nameserver和fallback设置的都是1.2.4.8或者阿里dns，然后竟然工作正常；但是若我只用clash的redir，不用clash的dns（比如用openwrt自己的dns），airplay ytb就不正常了

是不是我哪里理解的不对？

**Comment by Dreamacro** [comment]
http、socks 这种比较上层的代理都能拿到域名的，而像更底层的流量获取途径，如 redir、TUN 都是只能拿到 ip 的，所以需要一点 trick 去拿到域名，用的就是 dns server，如果不想用 clash 的 dns server, 就自己往 nameserver 里加上其他 dns 服务，但 dns 请求必须先经过 clash

**Comment by qiangd6** [comment]
谢谢！

“就自己往 nameserver 里加上其他 dns 服务，但 dns 请求必须先经过 clash”

比如说我想用1.2.4.8，具体该如何操作呢？

**Comment by Dreamacro** [comment]
```yml
dns:
  nameserver:
    - 1.2.4.8
```

**Comment by recall704** [comment]
你可以本地搞个 dnsmasq，然后

```yaml
dns:
  nameserver:
    - 127.0.0.1:5353
```

**Comment by qiangd6** [comment]
> ```yaml
> dns:
>   nameserver:
>     - 1.2.4.8
> ```

目前是这样的：
```yaml
dns:
  enable: true
  listen: 0.0.0.0:53
  enhanced-mode: redir-host
  nameserver:
    - 1.2.4.8
    - 223.5.5.5
  fallback:
    - 1.2.4.8
    - 223.5.5.5
```

不知是否正确？

目前盒子、iPhone、Windows电脑上网正常，行为符合预期，盒子可以airplay ytb

但是家里的mac都没法上网了，看了一下好像是没有获取DNS（即主路由器的IP地址192.168.1.1），很奇怪，我看看是不是DHCP服务器设定的问题

**Comment by qiangd6** [comment]
> 你可以本地搞个 dnsmasq，然后
> 
> ```yaml
> dns:
>   nameserver:
>     - 127.0.0.1:5353
> ```

呃，我是个小白，这个dnsmasq起的dns服务是在5353端口咩？
那仍然需要clash在0.0.0.0:53开一个DNS服务对么？只不过它consuem的是5353的服务？

**Comment by comzyh** [comment]
你是怎么用 Clash 替换原有路由器上的 DNS 功能的？大部分的 Openwrt 路由的 DNS 都是 dnsmasq 提供的。同时 dnsmasq 也提供 DHCP， 如果你把 dnsmasq 关了确实会拿不到地址。

不过你说**只是拿不到 DNS**，这个比较奇怪，不知道你怎么设置的。

**Comment by qiangd6** [comment]
> 你是怎么用 Clash 替换原有路由器上的 DNS 功能的？大部分的 Openwrt 路由的 DNS 都是 dnsmasq 提供的。同时 dnsmasq 也提供 DHCP， 如果你把 dnsmasq 关了确实会拿不到地址。
> 
> 不过你说**只是拿不到 DNS**，这个比较奇怪，不知道你怎么设置的。

我看了个YouTube上的视频，先把openwrt lede的原有dns服务改端口到5353，然后再config.yml里面enable dns，就这样：

```
dns:
  enable: true
  listen: 0.0.0.0:53
  enhanced-mode: redir-host
  nameserver:
    - 1.2.4.8
    - 223.5.5.5
  fallback:
    - 1.2.4.8
    - 223.5.5.5
```
