### ISSUE TITLE
[Bug] wss connection cannot go through clash

### ISSUE THREAD

**Issue by duhd1993** [Dreamacro/clash#1814]
### Verify steps

- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

Premium 2021.12.07

### What OS are you seeing the problem on?

macOS

### Clash config

```yaml
mixed-port: 7890
external-controller: 127.0.0.1:9090
allow-lan: false
mode: rule
log-level: debug

dns:
  enable: true
  ipv6: true
  nameserver:
    - https://1.1.1.1/dns-query
    - https://dns.google/dns-query

proxies:

proxy-groups:
  - name: "OUT"
    type: select
    proxies:
      - DIRECT
      - proxy1
rules:
  - MATCH,OUT
```

### Description

I cannot use discord when connected to clash. It doesn't matter what proxy is used or it's just DIRECT.
```wss://gateway.discord.gg/?encoding=json&v=9&compress=zlib-stream``` This connection is always in pending state.
Initially, I only set HTTP/HTTPS proxy in system. Later I set socks proxy as well. But it made no difference. 

I'm not 100% sure about the problem. I noticed that sometimes it works after I restart clash. Actually I wrote this post and deleted multiple times because I find out it went through after restart. 

In this issue https://github.com/Dreamacro/clash/issues/236, it was suggested to try websocat, here is the outcome:
```
$ websocat -t --ws-c-uri=wss://echo.websocket.events/ - ws-c:ssl-connect:cmd:'socat - proxy:127.0.0.1:echo.websocket.events:443,proxyport=7890'
websocat: connection closed via error
websocat: error running
```
Clash log shows 
```
time="2021-12-09T15:06:18-05:00" level=info msg="[TCP] 127.0.0.1:55221 --> echo.websocket.events:443 match Mat    ch() using OUT[DIRECT]"
```
