### ISSUE TITLE
[Bug] DNS 泄露(TUN+fake ip+no resolve)

### ISSUE THREAD

**Issue by codafi21** [Dreamacro/clash#1828]
### Verify steps

- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

2021.12.07 premium via CFW

### What OS are you seeing the problem on?

Windows

### Clash config

```yaml
port: 7890
socks-port: 7891
allow-lan: true
mode: rule
log-level: info
external-controller: 0.0.0.0:9090
proxies:😒[redacted]
proxy-groups:😒[redacted]
rules:😒[redacted]
dns:
  enable: true
  enhanced-mode: fake-ip
  nameserver:
    - 114.114.114.114
tun:
  enable: true
  stack: system
  dns-hijack:
    - 198.18.0.2:53 
  auto-route: true
  auto-detect-interface: true
```

### Clash log

```shell
time="2021-12-15T22:42:47+08:00" level=info msg="[TCP] 198.18.0.1:50775 --> dnsleaktest.com:443 match Match() using 😒[redacted]
time="2021-12-15T22:42:49+08:00" level=debug msg="[TUN] hijack udp dns: 198.18.0.2:53"
time="2021-12-15T22:42:49+08:00" level=info msg="[TCP] 198.18.0.1:50777 --> 20e91f8e-0fa7-4646-a6c0-fc1e557e4897.test.dnsleaktest.com:443 match Match() using 😒[redacted]
time="2021-12-15T22:42:50+08:00" level=debug msg="[TUN] hijack udp dns: 198.18.0.2:53"
time="2021-12-15T22:42:50+08:00" level=info msg="[TCP] 198.18.0.1:50779 --> ce152c16-651c-42a1-86e5-f30031ab5807.test.dnsleaktest.com:443 match Match() using 😒[redacted]
time="2021-12-15T22:42:53+08:00" level=debug msg="[TUN] hijack udp dns: 198.18.0.2:53"
time="2021-12-15T22:42:53+08:00" level=info msg="[TCP] 198.18.0.1:50781 --> c744741c-9ced-498d-a7f8-458e692a0537.test.dnsleaktest.com:443 match Match() using 😒[redacted]
time="2021-12-15T22:42:54+08:00" level=debug msg="[TUN] hijack udp dns: 198.18.0.2:53"
time="2021-12-15T22:42:54+08:00" level=info msg="[TCP] 198.18.0.1:50783 --> 67eb0d1e-c3be-4319-9471-a5a960a4d426.test.dnsleaktest.com:443 match Match() using 😒[redacted]
time="2021-12-15T22:42:55+08:00" level=debug msg="[TUN] hijack udp dns: 198.18.0.2:53"
time="2021-12-15T22:42:55+08:00" level=info msg="[TCP] 198.18.0.1:50785 --> 6bc15ebb-7b87-48c6-98ba-8049df5f9521.test.dnsleaktest.com:443 match Match() using 😒[redacted]
time="2021-12-15T22:42:56+08:00" level=debug msg="[TUN] hijack udp dns: 198.18.0.2:53"
time="2021-12-15T22:42:56+08:00" level=info msg="[TCP] 198.18.0.1:50787 --> b5fbd8cf-8c56-4c1c-8728-bf822a2a84e5.test.dnsleaktest.com:443 match Match() using 😒[redacted]
```

### Description

![Screenshot 2021-12-15 225349](https://user-images.githubusercontent.com/93474348/146210571-6cc06268-1335-46c0-8e5c-5d098ff2d1ca.png)
对geoip和ipcidr启用no-resolve，且在日志里完全没有dns请求的情况下，dns仍会泄露。
