### ISSUE TITLE
[Feature] Add DOMAIN-SET support to Clash Premium's `rule-providers`

### ISSUE THREAD

**Issue by SukkaW** [Dreamacro/clash#1838]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

Surge's `DOMAIN-SET` is designed for a large number of domain names list file, supports fast search for thousands of records. Each line in the file is a domain name if a line begins with `.` matches all sub-domains (matches the behavior of `DOMAIN-SUFFIX`) and the domain name itself (matches `DOMAIN`).

### Possible Solution

```yaml
rule-providers:
  cncidr:
    type: http
    behavior: domainset # domainset here
    url: "https://example.com/domainset.txt" # It is a plain text file
    path: ./ruleset/domainset.txt
    interval: 86400
```
