### ISSUE TITLE
[Bug][报错404][TCP] dial 🎬Youtube to www.youtube.com:443 error: dial example.xyz error: 404 Not Found

### ISSUE THREAD

**Issue by ankeliei** [Dreamacro/clash#1878]
### Verify steps

- [ ]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [ ]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

1.9.0

### What OS are you seeing the problem on?

Linux

### Clash config

```yaml
port: 7890
socks-port: 7891
redir-port: 7892
allow-lan: true
mode: rule
log-level: info
external-controller: 0.0.0.0:9090
external-ui: clash-dashboard
secret: ''
dns:
  enable: false
  ipv6: false
  listen: '0.0.0.0:53'
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  nameserver:
    - 114.114.114.114
    - 'tcp://223.5.5.5'
  fallback:
    - 'tls://223.5.5.5:853'
    - 'https://223.5.5.5/dns-query'
  fallback-filter:
    geoip: true
    ipcidr:
      - 240.0.0.0/4
============================================
version: '3'
services:
  clash:
    # ghcr.io/dreamacro/clash
    # ghcr.io/dreamacro/clash-premium
    # dreamacro/clash
    # dreamacro/clash-premium
    image: dreamacro/clash
    container_name: clash
    volumes:
      - ./config.yaml:/root/.config/clash/config.yaml
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime
      - ./clash-dashboard:/root/.config/clash/clash-dashboard # dashboard volume
    logging:
      driver: 'json-file'
      options:
        max-size: "1m"
    ports:
      - "7890:7890"
      - "7891:7891"
      # - "53:53/tcp"
      # - "53:53/udp"
      # - "9090:9090" # external controller (Restful API)
    # # TUN
    # cap_add:
    #   - NET_ADMIN
    # devices:
    #   - /dev/net/tun
    restart: always
    network_mode: "host" # or "host" on Linux
```

### Clash log

```shell
clash    | time="2022-01-04T18:58:55+08:00" level=info msg="Start initial compatible provider 🍎苹果服务"
clash    | time="2022-01-04T18:58:55+08:00" level=info msg="Start initial compatible provider 🎬国外媒体"
clash    | time="2022-01-04T18:58:55+08:00" level=info msg="Start initial compatible provider 🚀直接连接"
clash    | time="2022-01-04T18:58:55+08:00" level=info msg="Start initial compatible provider 🔰国外流量"
clash    | time="2022-01-04T18:58:55+08:00" level=info msg="Start initial compatible provider 🎬Netflix"
clash    | time="2022-01-04T18:58:55+08:00" level=info msg="Start initial compatible provider ⚓️其他流量"
clash    | time="2022-01-04T18:58:55+08:00" level=info msg="Start initial compatible provider 🎬Youtube"
clash    | time="2022-01-04T18:58:55+08:00" level=info msg="Start initial compatible provider 🎬哔哩哔哩"
clash    | time="2022-01-04T18:58:55+08:00" level=info msg="Start initial compatible provider ✈️Telegram"
clash    | time="2022-01-04T18:58:55+08:00" level=info msg="RESTful API listening at: [::]:9090"
clash    | time="2022-01-04T18:58:55+08:00" level=info msg="HTTP proxy listening at: [::]:7890"
clash    | time="2022-01-04T18:58:55+08:00" level=info msg="SOCKS proxy listening at: [::]:7891"
clash    | time="2022-01-04T18:58:55+08:00" level=info msg="Redirect proxy listening at: [::]:7892"
clash    | time="2022-01-04T18:58:55+08:00" level=info msg="DNS server listening at: [::]:53"
clash    | time="2022-01-04T18:59:38+08:00" level=debug msg="[DNS] incoming.telemetry.mozilla.org --> 34.120.208.123"
clash    | time="2022-01-04T18:59:38+08:00" level=warning msg="[TCP] dial ⚓️其他流量 (match Match/) to incoming.telemetry.mozilla.org:443 error: dial example.xyz:1309 error: 404 Not Found"
clash    | time="2022-01-04T18:59:38+08:00" level=debug msg="[DNS] incoming.telemetry.mozilla.org --> 34.120.208.123"
clash    | time="2022-01-04T18:59:38+08:00" level=warning msg="[TCP] dial 🎬Youtube (match DomainSuffix/youtube.com) to www.youtube.com:443 error: dial example.xyz:1309 error: 404 Not Found"
clash    | time="2022-01-04T18:59:38+08:00" level=warning msg="[TCP] dial ⚓️其他流量 (match Match/) to incoming.telemetry.mozilla.org:443 error: dial example.xyz:1309 error: 404 Not Found"
clash    | time="2022-01-04T18:59:38+08:00" level=debug msg="[DNS] incoming.telemetry.mozilla.org --> 34.120.208.123"
clash    | time="2022-01-04T18:59:38+08:00" level=warning msg="[TCP] dial 🎬Youtube (match DomainSuffix/youtube.com) to www.youtube.com:443 error: dial example.xyz:1309 error: 404 Not Found"
clash    | time="2022-01-04T18:59:39+08:00" level=warning msg="[TCP] dial ⚓️其他流量 (match Match/) to incoming.telemetry.mozilla.org:443 error: dial example.xyz:1309 error: 404 Not Found"
```

### Description

环境是在ubuntu21.10，根据wiki配置docker及docker-compose的安装方式，配置文件如上。

表现是控制面板节点全灰色，国内网站direct可以正常访问，国外的就不行，到控制台中clash报错error: dial example.xyz:1309 error: 404 Not Found。

1. docker援引的镜像是官方镜像，报错之后怀疑安装双系统引起时间同步问题，设置好了系统时间，并设置了docker配置文件的一些时间同步到宿主机的选项，log中可见clash的时间已经符合实际时间，但未能解决404问题。
2. 考虑到clash报错占用53端口的问题，配置文件设置dns_enable_false，不能解决404问题。
3. google之后发现是ubuntu默认有占用53端口的服务，遂根据教程（ https://www.qualityology.com/tech/ubuntu-port-53-already-in-use-how-to-free-the-dns-port/ ）进行设置，并恢复配置文件设置dns_enable_true，只是解决了53端口占用的问题，未解决404问题。

折腾两天，小白都快任务驱动型学会docker基本使用了🥲，求救
