### ISSUE TITLE
[Bug] incorrect value type of Metadata in premium core

### ISSUE THREAD

**Issue by kamingchan** [Dreamacro/clash#1879]
### Verify steps

- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

2022.01.02

### Clash config

```yaml
null
```

### Description

```go
interface Metadata {
  type: string // socks5、http
  network: string // tcp
  host: string
  src_ip: string
  src_port: string
  dst_ip: string
  dst_port: string
}
```

As wiki mentioned, `src_port` & `dst_port` are string. But actually they are integer. Comparing between string and integer always return False in Python.

**Comment by Dreamacro** [comment]
You need to provide the content of your script

**Comment by kamingchan** [comment]
```yaml
script:
    shortcuts:
        quic: network == 'udp' and dst_port == 443 # can match quic
        dumy: network == 'udp' and dst_port == '443' # always return False
```

I think the description in wiki need to be updated. `dst_port` & `src_port` are integer not string.
