### ISSUE TITLE
[Bug] Start DNS server error: missing port in address

### ISSUE THREAD

**Issue by WenisOK** [Dreamacro/clash#1880]
### Verify steps

- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

1.9.0

### What OS are you seeing the problem on?

Linux

### Clash config

```yaml
port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
externel-contorller: '0.0.0.0:9990'
secret: '123456'
external-ui: /home/wenisok/.clash/clash-dashboard
experimental:
  ignore-resolve-fail: true
```

### Clash log

```shell
INFO[0000] HTTP proxy listening at: [::]:7890           
INFO[0000] SOCKS proxy listening at: [::]:7891          
ERRO[0000] Start DNS server error: missing port in address
```

### Description

ERRO[0000]  Start DNS server error: missing port in address

**Comment by baekqiu** [comment]
我也遇到一样的问题，只需要下载1.8的clash版本即可，不要用1.9版的
I also encountered the same problem, just download the 1.8 clash version, don’t use the 1.9 version

**Comment by Dreamacro** [comment]
fixed, 这个 error 输出不影响正常使用

**Comment by WenisOK** [comment]
> 我也遇到一样的问题，只需要下载1.8的clash版本即可，不要用1.9版的 I also encountered the same problem, just download the 1.8 clash version, don’t use the 1.9 version

好的，我现在使用1.8.0版本，但是我现在无法使用web管理，浏览器显示拒绝链接

**Comment by mengdie101** [comment]
我也是这样，更新了最新版没错误提示了但是节点都连不上，只好先退回1.8用了

**Comment by maddie** [comment]
> 我也是这样，更新了最新版没错误提示了但是节点都连不上，配置都没动，就是用不了，只好先退回1.8用了

VMess nodes? There are changes to `ws-path` and `ws-headers`, in v1.9.0 changelog:

```
Change
- remove forward compatible codes in 2022 as agreed
  - migrate cache
  - ws-headers and ws-path on vmess
```

**Comment by mengdie101** [comment]
> > 我也是这样，更新了最新版没错误提示了但是节点都连不上，配置都没动，就是用不了，只好先退回1.8用了
> 
> VMess nodes? There are changes to `ws-path` and `ws-headers`, in v1.9.0 changelog:
> 
> ```
> Change
> - remove forward compatible codes in 2022 as agreed
>   - migrate cache
>   - ws-headers and ws-path on vmess
> ```
> 
> You should migrate these options into `ws-opts` section, see Wiki.

谢谢，我用的是VMess，看了Wiki还是没明白怎么怎么修改，节点是下面这个样子的，要怎么修改呢
  - {name: "***", server: ***, port: ***, type: vmess, uuid: ***, alterId: 0, cipher: auto, tls: false, skip-cert-verify: false, network: ws, ws-path: /***, ws-headers: {Host: www.baidu.com}}

**Comment by maddie** [comment]
```yaml
- name: "***"
  type: vmess
  server: ***
  port: ***
  uuid: ***
  alterId: 0
  cipher: auto
  udp: true
  tls: true
  skip-cert-verify: true
  network: ws
  ws-opts:
    headers:
      Host: www.baidu.com
    path: /path
```

**Comment by mengdie101** [comment]
> ```yaml
> - name: "***"
>   type: vmess
>   server: ***
>   port: ***
>   uuid: ***
>   alterId: 0
>   cipher: auto
>   udp: true
>   tls: true
>   skip-cert-verify: true
>   network: ws
>   ws-opts:
>     headers:
>       Host: www.baidu.com
>     path: /path
> ```
> 
> Instead of `ws-path` and `ws-headers` in the top level, rename them to `path` and `headers` and put them into `ws-opts`.
谢谢，终于明白了，要改成这样
  - {name: "***", server: ***, port: ***, type: vmess, uuid: ***, alterId: 0, cipher: auto, tls: false, skip-cert-verify: false, network: ws, ws-opts: {path: /path, headers: {Host: www.baidu.com}}}

**Comment by TheCGDF** [comment]
但这报错仍然是个问题，即使将dns enable设置为false，并且设置好端口：
```yaml
dns:
  enable: false
  listen: 0.0.0.0:53
```
依然会报红色error：`Start DNS server error: missing port in address `

这一点非常容易令使用者产生误解

这个报错没有产生任何有用的信息，反而引导使用者向错误的方向思考，纯属浪费debug时间

既然没有开启dns，就不应该再多此一举检查dns相关设置，更不应该产生这种有害于debug的报错
