### ISSUE TITLE
[Bug]  rules匹配不起作用

### ISSUE THREAD

**Issue by adrianzhang** [Dreamacro/clash#1899]
### Verify steps

- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

1.8.0, 1.9.0, 1.6.5

### What OS are you seeing the problem on?

Linux

### Clash config

```yaml
# Port of HTTP(S) proxy server on the local end
port: 7890

# Port of SOCKS5 proxy server on the local end
socks-port: 7891

# Transparent proxy server port for Linux and macOS
redir-port: 7892

# HTTP(S) and SOCKS5 server on the same port
# mixed-port: 7890

# authentication of local SOCKS5/HTTP(S) server
# authentication:
#  - "user1:pass1"
#  - "user2:pass2"

# Set to true to allow connections to the local-end server from
# other LAN IP addresses
#allow-lan: false
allow-lan: true

# This is only applicable when `allow-lan` is `true`
# '*': bind all IP addresses
# 192.168.122.11: bind a single IPv4 address
# "[aaaa::a8aa:ff:fe09:57d8]": bind a single IPv6 address
#bind-address: '*'
bind-address: '192.168.x.y'

# Clash router working mode
# rule: rule-based packet routing
# global: all packets will be forwarded to a single endpoint
# direct: directly forward the packets to the Internet
mode: rule

# Clash by default prints logs to STDOUT
# info / warning / error / debug / silent
#log-level: info
log-level: silent
#log-level: debug

# When set to false, resolver won't translate hostnames to IPv6 addresses
ipv6: false

# RESTful web API listening address
#external-controller: 127.0.0.1:9090
external-controller: 192.168.x.y:19090

# A relative path to the configuration directory or an absolute path to a
# directory in which you put some static web resource. Clash core will then
# serve it at `http://{{external-controller}}/ui`.
external-ui: folder

# Secret for the RESTful API (optional)
# Authenticate by spedifying HTTP header `Authorization: Bearer ${secret}`
# ALWAYS set a secret if RESTful API is listening on 0.0.0.0
# secret: ""

# Outbound interface name
interface-name: eth0

# Static hosts for DNS server and connection establishment, only works
# when `dns.enhanced-mode` is `redir-host`.
#
# Wildcard hostnames are supported (e.g. *.clash.dev, *.foo.*.example.com)
# Non-wildcard domain names have a higher priority than wildcard domain names
# e.g. foo.example.com > *.example.com > .example.com
# P.S. +.foo.com equals to .foo.com and foo.com
hosts:
  # '*.clash.dev': 127.0.0.1
  # '.dev': 127.0.0.1
  # 'alpha.clash.dev': '::1'

# DNS server settings
# This section is optional. When not present, the DNS server will be disabled.
dns:
  enable: false
  listen: 0.0.0.0:53
  # ipv6: false # when the false, response to AAAA questions will be empty

  # These nameservers are used to resolve the DNS nameserver hostnames below.
  # Specify IP addresses only
  default-nameserver:
    - 114.114.114.114
    - 8.8.8.8
  enhanced-mode: redir-host # or fake-ip
  fake-ip-range: 198.18.0.1/16 # Fake IP addresses pool CIDR
  # use-hosts: true # lookup hosts and return IP record

  # Hostnames in this list will not be resolved with fake IPs
  # i.e. questions to these domain names will always be answered with their
  # real IP addresses
  # fake-ip-filter:
  #   - '*.lan'
  #   - localhost.ptlogin2.qq.com

  # Supports UDP, TCP, DoT, DoH. You can specify the port to connect to.
  # All DNS questions are sent directly to the nameserver, without proxies
  # involved. Clash answers the DNS question with the first result gathered.
  nameserver:
    - 114.114.114.114 # default value
    - 8.8.8.8 # default value
    - tls://dns.rubyfish.cn:853 # DNS over TLS
    - https://1.1.1.1/dns-query # DNS over HTTPS

  # When `fallback` is present, the DNS server will send concurrent requests
  # to the servers in this section along with servers in `nameservers`.
  # The answers from fallback servers are used when the GEOIP country
  # is not `CN`.
  # fallback:
  #   - tcp://1.1.1.1

  # If IP addresses resolved with servers in `nameservers` are in the specified
  # subnets below, they are considered invalid and results from `fallback`
  # servers are used instead.
  #
  # IP address resolved with servers in `nameserver` is used when
  # `fallback-filter.geoip` is true and when GEOIP of the IP address is `CN`.
  #
  # If `fallback-filter.geoip` is false, results from `nameserver` nameservers
  # are always used if not match `fallback-filter.ipcidr`.
  #
  # This is a countermeasure against DNS pollution attacks.
  fallback-filter:
    geoip: true
    ipcidr:
      # - 240.0.0.0/4
    # domain:
    #   - '+.google.com'
    #   - '+.facebook.com'
    #   - '+.youtube.com'

proxies:

  - name: "vmess-vps1"
    type: vmess
    server: vps1.fqdn
    port: 443
    uuid: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    alterId: 0
    cipher: auto
    udp: true
    tls: true
    # skip-cert-verify: true
    # servername: example.com # priority over wss host
    network: ws
    ws-path: /vps1path
    # ws-headers:
    #   Host: v2ray.com


  - name: "vmess-vpseu"
    type: vmess
    server: vpseu.fqdn
    port: 443
    uuid: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    alterId: 0
    cipher: auto
    udp: true
    tls: true
    # skip-cert-verify: true
    # servername: example.com # priority over wss host
    network: ws
    ws-opts:
      path: /vpseupath
      ws-headers:
        Host: vpseu.fqdn

  - name: "vmess-vpsus"
    type: vmess
    server: vpsus.fqdn
    port: 443
    uuid: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    alterId: 0
    cipher: auto
    udp: true
    tls: true
    # skip-cert-verify: true
    # servername: example.com # priority over wss host
    network: ws
    ws-opts:
      path: /vpsuspath
      headers:
        Host: vpsus.fqdn

proxy-groups:

  # url-test select which proxy will be used by benchmarking speed to a URL.
  - name: "auto"
    type: url-test
    proxies:
      - vmess-vps1
      - vmess-vpsus
      - vmess-vpseu
    tolerance: 150
    url: 'http://www.gstatic.com/generate_204'
    interval: 300

  # fallback selects an available policy by priority. The availability is tested by accessing an URL, just like an auto url-test group.
  - name: "fallback-vpseu"
    type: fallback
    proxies:
      - vmess-vpseu
    url: 'http://www.gstatic.com/generate_204'
    interval: 300

  - name: "fallback-vpsus"
    type: fallback
    proxies:
      - vmess-vpsus
    url: 'http://www.gstatic.com/generate_204'
    interval: 300

  - name: "fallback-auto"
    type: fallback
    proxies:
      - vmess-vps1
    url: 'http://www.gstatic.com/generate_204'
    interval: 300

  # load-balance: The request of the same eTLD+1 will be dial to the same proxy.
  - name: "load-balance"
    type: load-balance
    proxies:
      - vmess-vps1
      - vmess-vpsus
      - vmess-vpseu
    url: 'http://www.gstatic.com/generate_204'
    interval: 300

rules:
  - DOMAIN-SUFFIX,vps1.fqdn,DIRECT
  - DOMAIN-SUFFIX,vpsus.fqdn,DIRECT
  - DOMAIN-SUFFIX,vpseu.fqdn,DIRECT
  # test rules
  - DOMAIN-SUFFIX,ipinfo.io,fallback-vpseu
  - DOMAIN-KEYWORD,ipinfo,fallback-vpseu
  #- SRC-IP-CIDR,192.168.1.201/32,DIRECT
  # optional param "no-resolve" for IP rules (GEOIP, IP-CIDR, IP-CIDR6)
  - IP-CIDR,127.0.0.0/8,DIRECT
  - IP-CIDR,192.168.0.0/16,DIRECT
  - IP-CIDR,vps1.ip.addr/32,DIRECT
  - IP-CIDR,vpseu.ip.addr/32,DIRECT
  - IP-CIDR,vpsus.ip.addr/32,DIRECT
  - IP-CIDR,8.8.8.8/32,fallback-auto
  - GEOIP,CN,DIRECT
  # - DST-PORT,80,DIRECT
  # - SRC-PORT,7777,DIRECT
  # - RULE-SET,apple,REJECT # Premium only
  - MATCH,fallback-auto
```

### Clash log

```shell
所有非中国IP都match vmess-vps1
```

### Description

网络结构是使用这个安装了Clash的Linux作为网关，iptables实现局域网流量导向clash direct port。
局域网里另外有单独的DNS Server，国外域名走Clash匹配8.8.8.8这一行。
局域网其他电脑的网关指向这个Linux机器，dns指向上述DNS server。

想要实现用不同的proxy group指向不同国家。
设置测试性clash config如上。
从其他电脑上访问ipinfo.io，发现ip地址仍然为`vps1.ip.addr`。且在该网关上运行` curl -x socks5://192.168.x.y:7891 https://ipinfo.io`也是得到`vps1.ip.addr`。
也就是说`- DOMAIN-KEYWORD,ipinfo,fallback-vpseu`和`- DOMAIN-SUFFIX,ipinfo.io,fallback-vpseu`并没有起作用，最后还是通过`- MATCH,fallback-auto` 这一行规则访问的。
