### ISSUE TITLE
[Bug] Premium 内核似乎存在内存泄漏的问题

### ISSUE THREAD

**Issue by Leezeke** [Dreamacro/clash#1902]
### Verify steps

- [ ]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [x]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

Premium: 2022.01.03

### What OS are you seeing the problem on?

Linux

### Clash config

```yaml
mixed-port: 7989
port: 7990
socks-port: 7991
redir-port: 7992
tproxy-port: 7993
ipv6: true
allow-lan: true
bind-address: "*"
mode: rule
log-level: info
external-controller: 0.0.0.0:9190
external-ui: dashboard
dns:
  enable: true
  listen: 0.0.0.0:5400
  enhanced-mode: redir-host
  use-hosts: true
  nameserver:
    - udp://127.0.0.1:65353
interface-name: enp2s0
tun:
  enable: true
  stack: gvisor
proxies:
```

### Clash log

```shell
没有发现日志中有特别的异常
```

### Description

使用 clash premium 作为透明代理(tun)，似乎发生了内存泄漏，在运行了不到 48 个小时后，内存占用了 9 个多 G，这是 systemd 状态信息 
![图片](https://user-images.githubusercontent.com/45861815/149088087-55564a7d-733e-4286-9d9d-ed306cc009b8.png)
