### ISSUE TITLE
[Bug] 无法DIRECT访问6to4隧道地址

### ISSUE THREAD

**Issue by c15412** [Dreamacro/clash#1903]
### Verify steps

- [x]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

Premium 2022.01.03

### What OS are you seeing the problem on?

Windows

### Clash config

```yaml
port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
省略了
proxy-groups:
省略了

rules:
  - IP-CIDR6,::ffff:c0a8:0/112,🎯直连
  - IP-CIDR6,::ffff:a00:0/112,🎯直连
  - DOMAIN-SUFFIX,local,🎯 全球直连
  - IP-CIDR,192.168.0.0/16,🎯 全球直连,no-resolve
  - IP-CIDR,10.0.0.0/8,🎯 全球直连,no-resolve
  - IP-CIDR,172.16.0.0/12,🎯 全球直连,no-resolve
  - IP-CIDR,127.0.0.0/8,🎯 全球直连,no-resolve
  - IP-CIDR,100.64.0.0/10,🎯 全球直连,no-resolve
  - IP-CIDR6,::1/128,🎯 全球直连,no-resolve
  - IP-CIDR6,fc00::/7,🎯 全球直连,no-resolve
  - IP-CIDR6,fe80::/10,🎯 全球直连,no-resolve
  - IP-CIDR6,fd00::/8,🎯 全球直连,no-resolve
  其他省略
proxy-providers: {}
rule-providers: {}
```

### Clash log

```shell
time="2022-01-12T13:46:28+08:00" level=warning msg="[TCP] dial 直连 (match IPCIDR/::ffff:127.0.0.0/112) to [::ffff:127.0.0.1]:51069 error: dial tcp6: address ::ffff:127.0.0.1: no suitable address found"
……
time="2022-01-12T13:47:28+08:00" level=warning msg="[TCP] dial 直连 (match IPCIDR/::ffff:192.168.0.0/112) to [::ffff:192.168.1.3]:51069 error: dial tcp6: address ::ffff:192.168.1.3: no suitable address found"
```

### Description

更新新的内核（2022-01-03）以后，6to4隧道地址如果被规则选定使用DIRECT，则无法正常访问，包括但不限于本地地址，添加no-resolve也无法正常访问。
同时如果我退回旧的版本，则无此问题，如2021-12-07
