### ISSUE TITLE
[Bug] MacOS vmess-ws-tls V2ray可以通，clash配置始终不行

### ISSUE THREAD

**Issue by wangbc423** [Dreamacro/clash#1915]
### Verify steps

- [ ]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [x]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [ ]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

1.9.0

### What OS are you seeing the problem on?

macOS

### Clash config

```yaml
proxies:
  - name: "vmess"
    type: vmess
    server: 123.com
    port: 443
    uuid: 8868e2e9-fbbd-4c43-98e8-35e07e28c111
    alterId: 0
    cipher: auto
    udp: false
    tls: true
    skip-cert-verify: false
    network: ws
    ws-path: /r5
```

### Description

v2ray配置如下：
```
 "outbounds": [{
    "protocol": "vmess",
    "settings": {
      "vnext": [
        {
          "address": "123.com",
          "port": 443,
          "users": [
            {
              "id": "8868e2e9-fbbd-4c43-98e8-35e07e28c111",
              "alterId": 0
            }
          ]
        }
      ]
    },
    "streamSettings": {
      "network": "ws",
      "security": "tls",
      "wsSettings": {
        "path": "/r5"
      }
    }
  }],
```
