### ISSUE TITLE
[Feature] 

### ISSUE THREAD

**Issue by Sagittarius** [Dreamacro/clash#1922]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

在开启tun模式后，docker-compose log -f看到的日志全是IP地址，没有域名信息，并且有大量的DNS请求，而非，并且所有的域名规则都没有被使用，除了GeoIP就是Final了，是我配置的原因吗：

```
clash-premium    | time="2022-01-20T07:40:09Z" level=info msg="[TCP] 192.168.50.62:60740 --> 95.92.23.212:7442 match Match() using Final[[VMess] 🇺🇸 美国L2 中继M1S3 [2]]"
clash-premium    | time="2022-01-20T07:40:09Z" level=info msg="[UDP] 192.168.50.62:45017 --> 8.8.8.8:53 match Match() using Final[[VMess] 🇺🇸 美国L2 中继M1S3 [2]]"
clash-premium    | time="2022-01-20T07:40:09Z" level=info msg="[UDP] 198.18.0.1:31250 --> 8.8.8.8:53 match Match() using Final[[VMess] 🇺🇸 美国L2 中继M1S3 [2]]"
clash-premium    | time="2022-01-20T07:40:09Z" level=info msg="[TCP] 192.168.50.62:40376 --> 195.201.31.194:80 match Match() using Final[[VMess] 🇺🇸 美国L2 中继M1S3 [2]]"
clash-premium    | time="2022-01-20T07:40:10Z" level=info msg="[UDP] 192.168.50.62:35787 --> 8.8.8.8:53 match Match() using Final[[VMess] 🇺🇸 美国L2 中继M1S3 [2]]"
clash-premium    | time="2022-01-20T07:40:10Z" level=info msg="[TCP] 192.168.50.62:56500 --> 213.227.149.178:6888 match Match() using Final[[VMess] 🇺🇸 美国L2 中继M1S3 [2]]"
clash-premium    | time="2022-01-20T07:40:10Z" level=info msg="[TCP] 192.168.50.62:59496 --> 89.245.7.70:15994 match Match() using Final[[VMess] 🇺🇸 美国L2 中继M1S3 [2]]"
clash-premium    | time="2022-01-20T07:40:10Z" level=warning msg="[TCP] dial DIRECT (match GeoIP/CN) to 61.140.72.242:15994 error: dial tcp4 61.140.72.242:15994: i/o timeout"
clash-premium    | time="2022-01-20T07:40:10Z" level=warning msg="[TCP] dial DIRECT (match GeoIP/CN) to 14.120.51.50:8444 error: dial tcp4 14.120.51.50:8444: i/o timeout"
clash-premium    | time="2022-01-20T07:40:10Z" level=info msg="[UDP] 192.168.50.62:52574 --> 8.8.8.8:53 match Match() using Final[[VMess] 🇺🇸 美国L2 中继M1S3 [2]]"
clash-premium    | time="2022-01-20T07:40:10Z" level=warning msg="[TCP] dial DIRECT (match GeoIP/CN) to 115.223.147.197:6888 error: dial tcp4 115.223.147.197:6888: i/o timeout"
clash-premium    | time="2022-01-20T07:40:11Z" level=info msg="[UDP] 198.18.0.1:60630 --> 8.8.8.8:53 match Match() using Final[[VMess] 🇺🇸 美国L2 中继M1S3 [2]]"
clash-premium    | time="2022-01-20T07:40:11Z" level=info msg="[TCP] 192.168.50.62:47154 --> 51.81.46.170:6969 match Match() using Final[[VMess] 🇺🇸 美国L2 中继M1S3 [2]]"
clash-premium    | time="2022-01-20T07:40:11Z" level=info msg="[TCP] 192.168.50.62:38578 --> 77.21.122.97:11444 match Match() using Final[[VMess] 🇺🇸 美国L2 中继M1S3 [2]]"
clash-premium    | time="2022-01-20T07:40:11Z" level=info msg="[TCP] 192.168.50.62:34874 --> 94.50.189.141:8444 match Match() using Final[[VMess] 🇺🇸 美国L2 中继M1S3 [2]]"
clash-premium    | time="2022-01-20T07:40:12Z" level=info msg="[TCP] 192.168.50.62:47174 --> 51.81.46.170:6969 match Match() using Final[[VMess] 🇺🇸 美国L2 中继M1S3 [2]]"
clash-premium    | time="2022-01-20T07:40:12Z" level=info msg="[UDP] 198.18.0.1:23809 --> 8.8.8.8:53 match Match() using Final[[VMess] 🇺🇸 美国L2 中继M1S3 [2]]"
clash-premium    | time="2022-01-20T07:40:13Z" level=info msg="[TCP] 192.168.50.62:49202 --> 79.31.177.125:6888 match Match() using Final[[VMess] 🇺🇸 美国L2 中继M1S3 [2]]"
clash-premium    | time="2022-01-20T07:40:13Z" level=warning msg="[TCP] dial DIRECT (match GeoIP/CN) to 115.52.86.148:8444 error: dial tcp4 115.52.86.148:8444: i/o timeout"
clash-premium    | time="2022-01-20T07:40:14Z" level=info msg="[UDP] 198.18.0.1:4601 --> 8.8.8.8:53 match Match() using Final[[VMess] 🇺🇸 美国L2 中继M1S3 [2]]"
clash-premium    | time="2022-01-20T07:40:14Z" level=info msg="[TCP] 192.168.50.62:50278 --> 91.35.106.223:15994 match Match() using Final[[VMess] 🇺🇸 美国L2 中继M1S3 [2]]"
clash-premium    | time="2022-01-20T07:40:14Z" level=info msg="[TCP] 192.168.50.62:39226 --> 89.212.130.217:8444 match Match() using Final[[VMess] 🇺🇸 美国L2 中继M1S3 [2]]"
clash-premium    | time="2022-01-20T07:40:14Z" level=info msg="[TCP] 192.168.50.62:47228 --> 51.81.46.170:6969 match Match() using Final[[VMess] 🇺🇸 美国L2 中继M1S3 [2]]"
clash-premium    | time="2022-01-20T07:40:15Z" level=info msg="[UDP] 198.18.0.1:53541 --> 8.8.8.8:53 match Match() using Final[[VMess] 🇺🇸 美国L2 中继M1S3 [2]]"
clash-premium    | time="2022-01-20T07:40:15Z" level=info msg="[TCP] 192.168.50.62:47238 --> 51.81.46.170:6969 match Match() using Final[[VMess] 🇺🇸 美国L2 中继M1S3 [2]]"
clash-premium    | time="2022-01-20T07:40:16Z" level=info msg="[TCP] 192.168.50.62:42222 --> 89.113.136.130:6888 match Match() using Final[[VMess] 🇺🇸 美国L2 中继M1S3 [2]]"
clash-premium    | time="2022-01-20T07:40:16Z" level=warning msg="[TCP] dial DIRECT (match GeoIP/CN) to 110.17.48.188:11444 error: dial tcp4 110.17.48.188:11444: connect: connection refused"
clash-premium    | time="2022-01-20T07:40:16Z" level=info msg="[TCP] 192.168.50.62:34982 --> 109.86.108.126:18644 match Match() using Final[[VMess] 🇺🇸 美国L2 中继M1S3 [2]]"
clash-premium    | time="2022-01-20T07:40:17Z" level=info msg="[UDP] 198.18.0.1:17793 --> 8.8.8.8:53 match Match() using Final[[VMess] 🇺🇸 美国L2 中继M1S3 [2]]"
clash-premium    | time="2022-01-20T07:40:18Z" level=info msg="[TCP] 192.168.50.62:34114 --> 213.22.196.29:8444 match Match() using Final[[VMess] 🇺🇸 美国L2 中继M1S3 [2]]"
clash-premium    | time="2022-01-20T07:40:18Z" level=info msg="[UDP] 198.18.0.1:29764 --> 8.8.8.8:53 match Match() using Final[[VMess] 🇺🇸 美国L2 中继M1S3 [2]]"
clash-premium    | time="2022-01-20T07:40:18Z" level=warning msg="[TCP] dial DIRECT (match GeoIP/CN) to 121.225.36.206:7442 error: dial tcp4 121.225.36.206:7442: i/o timeout"
clash-premium    | time="2022-01-20T07:40:19Z" level=info msg="[TCP] 192.168.50.62:46140 --> 188.218.84.165:15994 match Match() using Final[[VMess] 🇺🇸 美国L2 中继M1S3 [2]]"
clash-premium    | time="2022-01-20T07:40:19Z" level=info msg="[TCP] 192.168.50.62:36286 --> 99.43.31.152:7442 match Match() using Final[[VMess] 🇺🇸 美国L2 中继M1S3 [2]]"
clash-premium    | time="2022-01-20T07:40:20Z" level=info msg="[UDP] 198.18.0.1:53347 --> 8.8.8.8:53 match Match() using Final[[VMess] 🇺🇸 美国L2 中继M1S3 [2]]"
clash-premium    | time="2022-01-20T07:40:20Z" level=info msg="[TCP] 192.168.50.62:35342 --> 54.36.126.137:6969 match Match() using Final[[VMess] 🇺🇸 美国L2 中继M1S3 [2]]"
clash-premium    | time="2022-01-20T07:40:21Z" level=info msg="[TCP] 192.168.50.62:35348 --> 54.36.126.137:6969 match Match() using Final[[VMess] 🇺🇸 美国L2 中继M1S3 [2]]"
clash-premium    | time="2022-01-20T07:40:21Z" level=info msg="[UDP] 198.18.0.1:12672 --> 8.8.8.8:53 match Match() using Final[[VMess] 🇺🇸 美国L2 中继M1S3 [2]]"
clash-premium    | time="2022-01-20T07:40:21Z" level=info msg="[TCP] 192.168.50.62:35358 --> 54.36.126.137:6969 match Match() using Final[[VMess] 🇺🇸 美国L2 中继M1S3 [2]]"
clash-premium    | time="2022-01-20T07:40:22Z" level=info msg="[TCP] 192.168.50.62:37912 --> 178.143.167.14:8444 match Match() using Final[[VMess] 🇺🇸 美国L2 中继M1S3 [2]]"
clash-premium    | time="2022-01-20T07:40:22Z" level=info msg="[TCP] 192.168.50.62:51506 --> 85.131.125.222:6888 match Match() using Final[[VMess] 🇺🇸 美国L2 中继M1S3 [2]]"
clash-premium    | time="2022-01-20T07:40:22Z" level=info msg="[TCP] 192.168.50.62:35388 --> 54.36.126.137:6969 match Match() using Final[[VMess] 🇺🇸 美国L2 中继M1S3 [2]]"
clash-premium    | time="2022-01-20T07:40:23Z" level=info msg="[UDP] 198.18.0.1:6872 --> 8.8.8.8:53 match Match() using Final[[VMess] 🇺🇸 美国L2 中继M1S3 [2]]"
clash-premium    | time="2022-01-20T07:40:23Z" level=info msg="[TCP] 192.168.50.62:42730 --> 54.39.179.91:6699 match Match() using Final[[VMess] 🇺🇸 美国L2 中继M1S3 [2]]"
clash-premium    | time="2022-01-20T07:40:23Z" level=warning msg="[TCP] dial DIRECT (match GeoIP/CN) to 117.30.64.60:6888 error: dial tcp4 117.30.64.60:6888: i/o timeout"
clash-premium    | time="2022-01-20T07:40:23Z" level=info msg="[TCP] 192.168.50.62:40988 --> 47.14.25.82:15994 match Match() using Final[[VMess] 🇺🇸 美国L2 中继M1S3 [2]]"
clash-premium    | time="2022-01-20T07:40:24Z" level=info msg="[TCP] 192.168.50.62:42750 --> 54.39.179.91:6699 match Match() using Final[[VMess] 🇺🇸 美国L2 中继M1S3 [2]]"
clash-premium    | time="2022-01-20T07:40:24Z" level=info msg="[UDP] 198.18.0.1:9601 --> 8.8.8.8:53 match Match() using Final[[VMess] 🇺🇸 美国L2 中继M1S3 [2]]"
clash-premium    | time="2022-01-20T07:40:24Z" level=info msg="[TCP] 192.168.50.62:42770 --> 54.39.179.91:6699 match Match() using Final[[VMess] 🇺🇸 美国L2 中继M1S3 [2]]"
clash-premium    | time="2022-01-20T07:40:25Z" level=info msg="[TCP] 192.168.50.62:44704 --> 188.252.191.125:6888 match Match() using Final[[VMess] 🇺🇸 美国L2 中继M1S3 [2]]"
```
我是用docker host模式启动的，无法给utun指定用户
是iptables的问题吗？

docker-compose.yaml:
version: '3'
services:
  clash-premium:
    # ghcr.io/dreamacro/clash
    # ghcr.io/dreamacro/clash-premium
    # dreamacro/clash
    # dreamacro/clash-premium
    cap_add:
      - NET_ADMIN
    image: ghcr.io/dreamacro/clash-premium:latest
    container_name: clash-premium
    restart: always
    devices:
      - "/dev/net/tun:/dev/net/tun"
    volumes:
      - /mnt/vincent/smb/vincent/clash/:/root/.config/clash/
    network_mode: host
    environment:
      - TZ=Asia/Shanghai
    logging:
      driver: "json-file"
      options:
        max-size: "200m"
  clash_web:
    image: haishanh/yacd:latest
    container_name: clash-yacd
    environment:
      - TZ=Asia/Shanghai
    restart: always
    ports:
      # 容器外 web 访问端口  :  80
      - 9009:80
    depends_on:
      # 依赖于上面的clash服务，在clash启动后，web才启动
      - clash-premium

**Comment by Dreamacro** [comment]
可以配置 hijack 把系统自己的 dns 拦截掉

**Comment by Dreamacro** [comment]
可以配置 hijack 把系统自己的 dns 拦截掉

**Comment by Sagittarius** [comment]
> 可以配置 hijack 把系统自己的 dns 拦截掉
已经配置了的：

```
port: 7890
socks-port: 7891
redir-port: 7892
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
# external-ui: yacd
secret: 123456
bind-address: "*"
# 出口网卡
interface-name: enp6s0
profile:
  # open tracing exporter API
  tracing: true
dns:
  enable: true
  ipv6: true
  listen: 0.0.0.0:53
  enhanced-mode: redir-host
  nameserver:
    - 114.114.114.114 # 真实请求DNS，可多设置几个
    - 223.5.5.5
tun:
  enable: true
  stack: gvisor # 或 system
  dns-hijack:
    - 1.0.0.1:53
```

**Comment by Dreamacro** [comment]
日志里是 8.8.8.8，但是看你 hijack 并没有啊。另外 tun 有一键脚本的 https://github.com/Kr328/clash-premium-installer

**Comment by Sagittarius** [comment]
> 日志里是 8.8.8.8，但是看你 hijack 并没有啊。另外 tun 有一键脚本的 https://github.com/Kr328/clash-premium-installer

哦，原来是8.8.8.8的，我贴这里的时候改过了。另外，我/etc/resolve.conf里有8.8.8.8和114.114.114.114是否有影响的？
关于那个一键脚本，我之前跑过，好像跑完，网络完全出不去了，啥都访问不了，把脚本里面加的策略删掉就正常了

**Comment by Sagittarius** [comment]
解决了，研究了很多天iptables的意思，以及之前对dns-hijack有误解，原来它是拦截你系统的DNS，也就是系统配置的DNS如果和dns-hijack匹配上，就会被tun拦截下来，返回tun提供的DNS解析结果，这样我就好理解多了。
另外，那个关于[一键脚本](https://github.com/Kr328/clash-premium-installer)，虽然我环境支持nft，但是执行完，网络不通，让人非常崩溃，还是iptables好理解一点。
附上我的环境：
操作系统：TrueNAS-SCALE-22.02-RC.2
clash运行模式：docker的host模式（所以tun也是归属root用户，没有用户模式）
其他：系统上有k8s，部署了不少k8s的服务供局域网访问，所以iptables策略有很多都是k8s的，使用iptables时一定要小心，加策略之前先看一下有没有原来的策略存在。
iptables脚本：
```bash
#!/bin/bash
ipset create localnetwork hash:net
ipset add localnetwork 127.0.0.0/8
ipset add localnetwork 10.0.0.0/8
ipset add localnetwork 169.254.0.0/16
ipset add localnetwork 192.168.0.0/16
ipset add localnetwork 224.0.0.0/4
ipset add localnetwork 240.0.0.0/4
ipset add localnetwork 172.16.0.0/12

iptables -t mangle -N CLASH
iptables -t mangle -F CLASH
# 这条一定要放在最上面，我就遇到了一个问题，我在k8s上部署了nextcloud，执行完策略后发现就无法访问了。
# k8s给nextcloud定义了一个域名，接收流量的时候内部流转给nextcloud服务时候，只有k8s内部的dns 172.16.0.163才能解开
# 从clash日志看，这个dns 172.16.0.163被tun拦截了，所以在给53端口流量打标志之前，先把局域网地址过滤掉
iptables -t mangle -A CLASH -m set --match-set localnetwork dst -j RETURN
iptables -t mangle -A CLASH -m addrtype --dst-type BROADCAST -j RETURN
iptables -t mangle -A CLASH -p tcp --dport 53 -j MARK --set-mark 0x162
iptables -t mangle -A CLASH -p udp --dport 53 -j MARK --set-mark 0x162
iptables -t mangle -A CLASH -d 198.18.0.0/16 -j MARK --set-mark 0x162
iptables -t mangle -A CLASH -j MARK --set-mark 0x162

# 如果是网关，可以加上这两条，过滤高流量
# iptables -t mangle -A PREROUTING -p udp -m udp --dport 4096:65535 -j RETURN
# iptables -t mangle -A PREROUTING -p tcp -m tcp --dport 8192:65535 -j RETURN
iptables -t mangle -A PREROUTING -m set ! --match-set localnetwork dst -j MARK --set-mark 0x162
# 由root用户发起的流量，不经过TUN，如果系统本身都是运行在root下的，建议不要执行这条
# iptables -t mangle -D OUTPUT -m owner --uid-owner 0 -j RETURN
iptables -t mangle -A OUTPUT -j CLASH

ip route replace default dev utun table 0x162
ip rule add fwmark 0x162 lookup 0x162

sysctl -w net/ipv4/ip_forward=1
sysctl -w net.ipv4.conf.utun.rp_filter=0
```

config.yaml:
```

port: 7890
socks-port: 7891
redir-port: 7892
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
# external-ui: yacd
secret: 123456
bind-address: "*"
# 出口网卡
interface-name: enp6s0
profile:
  # open tracing exporter API
  tracing: true
dns:
  enable: true
  # listen: 0.0.0.0:53
  ipv6: true
  fake-ip-range: 198.18.0.1/16
  enhanced-mode: redir-host
  # enhanced-mode: fake-ip
  # 支持 UDP / TCP / DoT / DoH 协议的 DNS 服务，可以指明具体的连接端口号。
  # 所有 DNS 请求将会直接发送到服务器，不经过任何代理。
  # Clash 会使用最先获得的解析记录回复 DNS 请求
  nameserver:
    - 114.114.114.114 # 真实请求DNS，可多设置几个
    - 223.5.5.5
  # 在以下列表的域名将不会被解析为 fake ip，这些域名相关的解析请求将会返回它们真实的 IP 地址
  fake-ip-filter:
    # === LAN ===
    - '*.lan'
    # === Linksys Wireless Router ===
    - '*.linksys.com'
    - '*.linksyssmartwifi.com'
    # === Apple Software Update Service ===
    - 'swscan.apple.com'
    - 'mesu.apple.com'
    # === Windows 10 Connnect Detection ===
    - '*.msftconnecttest.com'
    - '*.msftncsi.com'

  # 当 fallback 参数被配置时, DNS 请求将同时发送至上方 nameserver 列表和下方 fallback 列表中配置的所有 DNS 服务器.
  # 当解析得到的 IP 地址的地理位置不是 CN 时，clash 将会选用 fallback 中 DNS 服务器的解析结果。
  fallback:
    - https://1.0.0.1/dns-query
    - https://8.8.4.4/dns-query
    - tls://8.8.8.8:853
    - tls://1.0.0.1:853

  # 如果使用 nameserver 列表中的服务器解析的 IP 地址在下方列表中的子网中，则它们被认为是无效的，
  # Clash 会选用 fallback 列表中配置 DNS 服务器解析得到的结果。
  #
  # 当 fallback-filter.geoip 为 true 且 IP 地址的地理位置为 CN 时，
  # Clash 会选用 nameserver 列表中配置 DNS 服务器解析得到的结果。
  #
  # 当 fallback-filter.geoip 为 false, 如果解析结果不在 fallback-filter.ipcidr 范围内，
  # Clash 总会选用 nameserver 列表中配置 DNS 服务器解析得到的结果。
  #
  # 采取以上逻辑进行域名解析是为了对抗 DNS 投毒攻击。
  fallback-filter:
    geoip: true
    ipcidr:
      - 240.0.0.0/4
    domain:
    - '+.google.com'
    - '+.facebook.com'
    - '+.youtube.com'
    - '+.discord.com'

tun:
  enable: true
  stack: system # 或 system
  dns-hijack:
    - 114.114.114.114:53
    - 1.0.0.1:53
    - 8.8.8.8:53
```
