### ISSUE TITLE
[Bug] 最简配置，无效

### ISSUE THREAD

**Issue by codthing** [Dreamacro/clash#1933]
### Verify steps

- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

0.19.6

### What OS are you seeing the problem on?

windows10

_No response_

### Clash config

```yaml
proxies:
  - name: Shadowsocks
    type: socks5
    server: 127.0.0.1
    port: 1080
proxy-groups:
  - name: Proxy
    type: select
    proxies:
      - Shadowsocks
rules:
  - "MATCH,DIRECT"
```

### Description

我没有时间去弄清clash的运行机制，我只是按照中文文档的最简示例去配置文件，启动服务。但是并不能成功翻栏杆。

![动画](https://user-images.githubusercontent.com/16655229/150647459-88fdf7fc-b527-46d3-bcda-e4d4dd414b99.gif)
