### ISSUE TITLE
[Bug] windows版icloud无法正常同步，clash已经走直连

### ISSUE THREAD

**Issue by paulpaulzhang** [Dreamacro/clash#1945]
### Verify steps

- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

2022.01.27

### What OS are you seeing the problem on?

Windows

### Clash config

```yaml
proxy-groups:
  - name: 🚀 节点选择
    type: select
    proxies:
      - ♻️ 自动选择
    name: 🍎 苹果服务
    type: select
    proxies:
      - 🚀 节点选择
      - 🎯 全球直连
```

### Description

已尝试过规则里面设置直连，代理模式设置直连，都无法正常同步，不知道该怎么解决这个问题，网页版访问一切正常
![image](https://user-images.githubusercontent.com/40710267/151745047-f354dafa-576d-4a89-a748-e641cb60eacf.png)
![image](https://user-images.githubusercontent.com/40710267/151745076-d074f262-1890-4d3d-867d-c356f1e0cbda.png)
