### ISSUE TITLE
[Bug] 节点排序问题

### ISSUE THREAD

**Issue by hackenfu** [Dreamacro/clash#1952]
### Verify steps

- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

premium 20220127

### What OS are you seeing the problem on?

Windows, Linux

### Clash config

```yaml
proxy-groups:
  - name: "load-balance"
    type: load-balance
    use:
      - 香港 IEPL
    url: 'http://www.gstatic.com/generate_204'
    interval: 300
    strategy: consistent-hashing

  - name: "Google"
    type: fallback
    use:
      - 新加坡 IEPL
    proxies:
      - load-balance
    url: 'http://www.gstatic.com/generate_204'
    interval: 300
```

### Description

现有香港IEPL和新加坡IEPL两组proxy-providers，其中香港6个节点，新加坡只有1个。我想实现的功能是：
fallback优先新加坡，断线的话跳转到香港，但香港启用负载均衡。
上述config启用后，发现proxies总在use之前，而不是我设置的顺序。根据https://github.com/Dreamacro/clash/issues/664，似乎这不是一个bug，而是作者有意而为。作者提出的“可以将 proxies 里的东西单独封装成一个 provider”，感觉好像不适合我这种情况？或者我不太会封装，请指教，谢谢！
