### ISSUE TITLE
[Bug] UDP dial DIRECT not support

### ISSUE THREAD

**Issue by ruisiji** [Dreamacro/clash#1953]
### Verify steps

- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

Premium 2022.01.27

### What OS are you seeing the problem on?

Linux

### Clash config

```yaml
mixed-port: 7890
mode: rule
log-level: info
interface-name: eth0

tun:
  enable: true
  stack: system
  auto-route: true
  auto-detect-interface: true

dns:
  enable: true
  listen: 127.0.0.153:53
  enhanced-mode: fake-ip
  nameserver:
    - 223.5.5.5

proxy-groups:
  - name: PROXY
    type: select
    proxies:
      - DIRECT

rules:
- IP-CIDR,10.0.0.0/8,DIRECT
- IP-CIDR,100.64.0.0/10,DIRECT
- IP-CIDR,127.0.0.0/8,DIRECT
- IP-CIDR,172.16.0.0/12,DIRECT
- IP-CIDR,192.168.0.0/16,DIRECT
- MATCH,DIRECT
```

### ip route/nftables

```
#!/bin/bash

# netfilter mark
NETFILTER_MARK=114514

# iproute rule table id
IPROUTE_TABLE_ID=114

ip route replace default dev utun table "$IPROUTE_TABLE_ID"

ip rule del fwmark "$NETFILTER_MARK" lookup "$IPROUTE_TABLE_ID" > /dev/null 2> /dev/null
ip rule add fwmark "$NETFILTER_MARK" lookup "$IPROUTE_TABLE_ID"

nft -f - << EOF
define LOCAL_SUBNET = {127.0.0.0/8, 224.0.0.0/4, 192.168.0.0/16, 10.0.0.0/8, 172.16.0.0/12}

table clash
flush table clash

table clash {
    chain local {
        type route hook output priority 0; policy accept;

        ip protocol != { tcp, udp } accept

        ct state new ct mark set $NETFILTER_MARK
        ct mark $NETFILTER_MARK mark set $NETFILTER_MARK
    }

    chain forward {
        type filter hook prerouting priority 0; policy accept;

        ip protocol != { tcp, udp } accept

        iif utun accept
        ip daddr \$LOCAL_SUBNET accept

        mark set $NETFILTER_MARK
    }
}
EOF

sysctl -w net/ipv4/ip_forward=1

exit 0
```

### Clash log

```shell
level=warning msg="[UDP] dial DIRECT (match GeoIP/CN) to 0.debian.pool.ntp.org:123 error: not support"
level=warning msg="[UDP] dial DIRECT (match Match/) to 0.debian.pool.ntp.org:123 error: not support"
level=warning msg="[UDP] dial DIRECT (match DomainSuffix/ntp.org) to 0.debian.pool.ntp.org:123 error: not support"
level=warning msg="[UDP] dial DIRECT (match Match/) to cdnjs.cloudflare.com:443 error: not support"
level=warning msg="[UDP] dial DIRECT (match GeoIP/CN) to safebrowsing.googleapis.com:443 error: not support"
```

### Description

I used nftables to mark and redirect packets to Clash, this is not included in clash config file.

The fake-ip-filter `+.ntp.org` has no impact on the result, removing it still throws `not support` warning.

**The issue is no matter which rule is matched, using `UDP` with `DIRECT` will throw the `not support` warning message.**

If I use DomainSuffix to let the domains go through a proxy server, it has no error.

## Reproduce steps

1. Set DNS to 127.0.0.153 in /etc/resolv.conf
2. Start clash with the config.yaml (you can either use a real proxy or just DIRECT)
3. Execute the script(if you use ssh to login the VM, you may need to re-login the VM after this cmd)
4. nc -zuv baidu.com 5555 # or other commands to send UDP packets
