### ISSUE TITLE
[Bug] Clash Rule Provider can be not filtered

### ISSUE THREAD

**Issue by qzi** [Dreamacro/clash#1955]
### Verify steps

- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

clash-darwin-amd64-2022.01.27

### What OS are you seeing the problem on?

macOS

### Clash config

```yaml
rule-providers:

  Netflix: {type: http, behavior: classical, path: ./Filter/Netflix, url: https://cdn.jsdelivr.net/gh/Semporia/Clash-X@master/Filter/Netflix.yaml, interval: 3600}
  YouTube: {type: http, behavior: classical, path: ./Filter/YouTube, url: https://cdn.jsdelivr.net/gh/Semporia/Clash-X@master/Filter/YouTube.yaml, interval: 3600}
  Telegram: {type: http, behavior: classical, path: ./Filter/Telegram, url: https://cdn.jsdelivr.net/gh/Semporia/Clash-X@master/Filter/Telegram.yaml, interval: 3600}


rules:

  - RULE-SET,Netflix,Netflix 
  - RULE-SET,YouTube,YouTube 
  - RULE-SET,Telegram,Telegram
```

### Clash log

```shell
log 里面只匹配了direct和match, 时不时也有匹配其他rule set, 但是经常匹配不到, 经过咨询也有其他人确认了这个问题

没有报错
```

### Description

log 里面只匹配了direct和match, 时不时也有匹配其他rule set, 但是经常匹配不到, 经过咨询也有其他人确认了这个问题

我在 clash-darwin-amd64-2022.01.27 和 clash-darwin-amd64-n2022-02-05-ga78e77d 测试过都有这个问题
