### ISSUE TITLE
[Bug] vmess + grpc 一直报 received DATA after END_STREAM

### ISSUE THREAD

**Issue by zgc** [Dreamacro/clash#1979]
### Verify steps

- [ ]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

Premium 2022.01.27

### Clash config

```yaml
proxies:
- name: xxx
  type: vmess
  server: www.xxx.com
  port: 443
  uuid: xxx-xxx-xxx-xxx-xxx
  alterId: 0
  cipher: auto
  udp: true
  skip-cert-verify: false
  tls: true
  servername: www.xxx.com
  network: grpc
  grpc-opts:
    grpc-service-name: xxx
```

### Clash log

```shell
received DATA after END_STREAM
```

### Description

日志一直报：protocol error: received DATA after END_STREAM
[Xray-core v1.5.2](https://github.com/XTLS/Xray-core/releases/tag/v1.5.2)更新日志有提到相关问题，是因为我套了cf cdn。
希望作者能添加参数 `initial_windows_size: number `
::: tip 通过 Cloudflare CDN 时，可将值设为 524288，即禁用动态窗口机制（Dynamic Window）,可防止 Cloudflare CDN 发送意外的 h2 GOAWAY 帧以关闭现有连接。 :::
https://github.com/XTLS/Xray-docs-next/blob/5ece68eec9d730047396b76c8463e961da37a236/docs/config/transports/grpc.md
