### ISSUE TITLE
[Bug] 访问纯ipv6网站时dns解析会有问题

### ISSUE THREAD

**Issue by Y32Gcnte8z** [Dreamacro/clash#1980]
### Verify steps

- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

premium 2022.01.27

### What OS are you seeing the problem on?

Linux

### Clash config

```yaml
ipv6: true
mode: script
log-level: info
dns:
  enable: true
  ipv6: true
  enhanced-mode: fake-ip
  fake-ip-filter:
    - 'ping.archlinux.org'
  nameserver:
    - tls://223.5.5.5:853

tun:
  enable: true
  stack: system
  dns-hijack:
    - 198.18.0.2:53
    - tcp://198.18.0.2:53

proxies:
  - name: PROXY
    type: trojan
    server: myhost.host
    port: 443
    password: mypasswd
    sni: myhost.host
    udp: true

proxy-groups:
  - name: 🔰 节点选择
    type: select
    proxies:
      - PROXY

script:
  code: |
    def main(ctx, metadata):  
      ip = metadata["dst_ip"]
      if ip != "" and ctx.geoip(ip) == 'LAN':
        return "DIRECT"
      ip = ctx.resolve_ip(metadata["host"])
      ctx.log(ip)
      if ctx.geoip(ip) == "CN":
        return "DIRECT"
      return "🔰 节点选择"
```

### Clash log
```
2022-02-20 12:04:57[warning] [Script] resolve test6.ustc.edu.cn ip failed: couldn't find ip: test6.ustc.edu.cn
2022-02-20 12:04:57[info] [TCP] 198.18.0.1:41218 --> test6.ustc.edu.cn:80 using 🔰 节点选择 by Script
```
### Description

具体表现为纯ipv6网站（比如test6.ustc.edu.cn）在匹配到IP规则时dns解析结果为空，于是会最终匹配到match。
