### ISSUE TITLE
[Bug] Start Mixed(http+socks) server error

### ISSUE THREAD

**Issue by yuhenghuang** [Dreamacro/clash#1983]
### Verify steps

- [ ]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [ ]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

1.9

### What OS are you seeing the problem on?

Windows

### Clash config

```yaml
mixed-port: 7890

# 允许局域网的连接
allow-lan: true

# 规则模式：Rule（规则） / Global（全局代理）/ Direct（全局直连）
mode: rule

# 设置日志输出级别 (默认级别：silent，即不输出任何内容，以避免因日志内容过大而导致程序内存溢出）。
# 5 个级别：silent / info / warning / error / debug。级别越高日志输出量越大，越倾向于调试，若需要请自行开启。
log-level: debug
# Clash 的 RESTful API
external-controller: '0.0.0.0:9090'

# RESTful API 的口令
secret: '' 

# 您可以将静态网页资源（如 clash-dashboard）放置在一个目录中，clash 将会服务于 `RESTful API/ui`
# 参数应填写配置目录的相对路径或绝对路径。
# external-ui: folder
external-ui: clash-dashboard
```

### Clash log

```shell
time="2022-02-21T09:24:59+08:00" level=error msg="Start Mixed(http+socks) server error: listen tcp :7890: bind: An attempt was made to access a socket in a way forbidden by its access permissions."
time="2022-02-21T09:24:59+08:00" level=error msg="Start DNS server error: missing port in address"
time="2022-02-21T09:24:59+08:00" level=info msg="RESTful API listening at: [::]:9090"
```

### Description

I can check connection informations (e.g. proxy server lag) from the external ui, but accessing through the port `7890` got no response. Restarting system doesn't resolve the bug.

This problem occurred suddenly without any noticable changes from last successful launch. (clash version and config file stayed the same as last time). And I am now using the same config on macOS using *ClashX* without any problem.

One possibility is the port being occupied by other programs while after checking the port list I found no such program. Thus, I ruled it out.

I tend to think this is caused by some random **windows update**, but still submit the issue here in case someone else is having the same one.
