### ISSUE TITLE
[Bug] TUN模式下出现大量连接

### ISSUE THREAD

**Issue by FishMagic** [Dreamacro/clash#1991]
### Verify steps

- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [ ]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

2022.01.27 Premium

### What OS are you seeing the problem on?

Windows

### Clash config

```yaml
mixed-port: 7890
allow-lan: true
external-controller: 127.0.0.1:57910
secret: 
mode: Script
proxies:
  - name: Adguard VPN
    type: socks5
    server: 127.0.0.1
    port: 9095
    udp: true
proxy-groups:
  - name: Proxy
    type: fallback
    proxies:
      - Adguard VPN
      - DIRECT
    url: 'http://www.gstatic.com/generate_204'
    interval: 300
  - name: MatchProxy
    type: select
    proxies:
      - Adguard VPN
      - DIRECT
dns:
  enable: true
  use-hosts: true
  listen: 127.0.0.1:28898
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  default-nameserver:
    - 114.114.114.114
    - 8.8.8.8
  nameserver:
    - https://1.1.1.1/dns-query
    - 1.1.1.1
    - 8.8.8.8
  fake-ip-filter:
  - "dns.msftncsi.com"
  - "www.msftncsi.com"
  - "www.msftconnecttest.com"
  - "*.local"
  - "*.lan"
  - "*.qq.com"
  - "*.ftmc.me"
  - "*.ubi.com"
  fallback-filter:
    geoip: true
    geoip-code: CN
    ipcider: []
    domain: []
rule-providers:
  direct:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/direct.txt"
    path: "./ruleset/direct.yaml"
    interval: 86400
  private:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/private.txt"
    path: "./ruleset/private.yaml"
    interval: 86400
  cncidr:
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/cncidr.txt"
    path: ./ruleset/cncidr.yaml
    interval: 86400
  lancidr:
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/lancidr.txt"
    path: ./ruleset/lancidr.yaml
    interval: 86400
  gfwlist:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/gfw.txt"
    path: ./ruleset/gfwlist.yaml
    interval: 86400
  telegramcidr:
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/telegramcidr.txt"
    path: ./ruleset/telegramcidr.yaml
    interval: 86400
  proxylist:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/proxy.txt"
    path: ./ruleset/proxylist.yaml
    interval: 86400
  greatfire:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/greatfire.txt"
    path: ./ruleset/greatfire.yaml
    interval: 86400
script:
  code: |
    def main(ctx, metadata):
      directLists = ["direct", "private", "cncidr", "lancidr"]
      proxyLists = ["gfwlist", "telegramcidr", "proxylist", "greatfire"]

      for directRuleName in directLists:
        if ctx.rule_providers[directRuleName].match(metadata):
          return "DIRECT"
      for proxyRuleName in proxyLists:
        if ctx.rule_providers[proxyRuleName].match(metadata):
          return "Proxy"
      return "MatchProxy"
mixin: # object
  interface-name: Wi-Fi
  tun:
    enable: true
    stack: gvisor
    auto-route: true
    # auto-detect-interface: true
    dns-hijack:
      - 198.18.0.2:53
  dns:
    enable: true
    use-hosts: true
    listen: 127.0.0.1:28898
    enhanced-mode: fake-ip
    fake-ip-range: 198.18.0.1/16
    default-nameserver:
      - 114.114.114.114
      - 8.8.8.8
    nameserver:
      - https://1.1.1.1/dns-query
      - 1.1.1.1
      - 8.8.8.8
    fake-ip-filter:
    - "dns.msftncsi.com"
    - "www.msftncsi.com"
    - "www.msftconnecttest.com"
    - "*.local"
    - "*.lan"
    - "*.qq.com"
    - "*.ubi.com"
    fallback-filter:
      geoip: true
      geoip-code: CN
      ipcider: []
      domain: []
```

### Clash log

日志过长, 见 https://pastebin.ubuntu.com/p/NRTK8Tmm3X/

### Description

使用TUN模式时出现大量连接, 导致系统资源占用过高, 且无法使用网络
已尝试过升级至最新版本
已尝试过自动检测网卡, 和手动指定网卡
从未开启过网络共享

**Comment by Dreamacro** [comment]
看起来你的 dns 不是 clash？日志都是 dns 又经过 clash 走了一次，但是和你 dns 配置一致。 先去掉 adguard 试试？

**Comment by FishMagic** [comment]
Adguard的DNS保护已经是关掉了的, 并且也尝试过关掉Adguard.
![image](https://user-images.githubusercontent.com/31554762/155829585-538492d2-286e-4fe8-8859-8cc59deb807b.png)

**Comment by FishMagic** [comment]
系统DNS为路由器172.21.92.96, 直接使用二进制模式同样会爆炸, 配置如下
```yaml
mixed-port: 7890
allow-lan: true
external-controller: 127.0.0.1:57910
secret: 
mode: Script
proxies:
  - name: Adguard VPN
    type: socks5
    server: 127.0.0.1
    port: 9095
    udp: true
proxy-groups:
  - name: Proxy
    type: fallback
    proxies:
      - Adguard VPN
      - DIRECT
    url: 'http://www.gstatic.com/generate_204'
    interval: 300
  - name: MatchProxy
    type: select
    proxies:
      - Adguard VPN
      - DIRECT
dns:
  enable: true
  use-hosts: true
  listen: 127.0.0.1:28898
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  default-nameserver:
    - 114.114.114.114
    - 8.8.8.8
  nameserver:
    - https://1.1.1.1/dns-query
    - 1.1.1.1
    - 8.8.8.8
  fake-ip-filter:
  - "dns.msftncsi.com"
  - "www.msftncsi.com"
  - "www.msftconnecttest.com"
  - "*.local"
  - "*.lan"
  - "*.qq.com"
  - "*.ubi.com"
  fallback-filter:
    geoip: true
    geoip-code: CN
    ipcider: []
    domain: []
rule-providers:
  direct:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/direct.txt"
    path: "./ruleset/direct.yaml"
    interval: 86400
  private:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/private.txt"
    path: "./ruleset/private.yaml"
    interval: 86400
  cncidr:
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/cncidr.txt"
    path: ./ruleset/cncidr.yaml
    interval: 86400
  lancidr:
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/lancidr.txt"
    path: ./ruleset/lancidr.yaml
    interval: 86400
  gfwlist:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/gfw.txt"
    path: ./ruleset/gfwlist.yaml
    interval: 86400
  telegramcidr:
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/telegramcidr.txt"
    path: ./ruleset/telegramcidr.yaml
    interval: 86400
  proxylist:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/proxy.txt"
    path: ./ruleset/proxylist.yaml
    interval: 86400
  greatfire:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/greatfire.txt"
    path: ./ruleset/greatfire.yaml
    interval: 86400
interface-name: Wi-Fi
tun:
  enable: true
  stack: gvisor
  auto-route: true
  # auto-detect-interface: true
  dns-hijack:
    - 198.18.0.2:53
script:
  code: |
    def main(ctx, metadata):
      directLists = ["direct", "private", "cncidr", "lancidr"]
      proxyLists = ["gfwlist", "telegramcidr", "proxylist", "greatfire"]

      for directRuleName in directLists:
        if ctx.rule_providers[directRuleName].match(metadata):
          return "DIRECT"
      for proxyRuleName in proxyLists:
        if ctx.rule_providers[proxyRuleName].match(metadata):
          return "Proxy"
      return "MatchProxy"
```
