### ISSUE TITLE
vmess+tls+ws 开启 early data 就无法连接

### ISSUE THREAD

**Issue by Hreint** [Dreamacro/clash#1994]
### Verify steps

- [ ]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

2022.01.27 Premium

### What OS are you seeing the problem on?

Windows

### Clash config

```yaml
- name: 
    type: vmess
    server: 
    port: 
    uuid: 
    alterId: 0
    cipher: auto
    network: ws
    tls: true
    skip-cert-verify: false
    ws-opts:
      path: /
      max-early-data: 2048
      early-data-header-name: Sec-WebSocket-Protocol
```

### Description

我使用的配置是 vmess+tls+ws，但我发现只要我在我的配置文件里加上 max-early-data: 2048 和 early-data-header-name: Sec-WebSocket-Protocol 两行，就无法连接了。如图所示：

当配置文件为下图这样时，点击测速就直接超时：
![2022-02-26_224637](https://user-images.githubusercontent.com/64591583/155861485-daf66736-4ca1-4b4b-b0bf-a0e2d5440354.png)
![2022-02-26_224627](https://user-images.githubusercontent.com/64591583/155861497-7b68dd06-de32-401f-a9fc-fce7330fa382.png)

只要删掉 max-early-data: 2048 和 early-data-header-name: Sec-WebSocket-Protocol 两行，就又可以使用了：
![2022-02-26_224518](https://user-images.githubusercontent.com/64591583/155861520-c4b92660-6613-403d-977b-e8b8600fc0dd.png)
![2022-02-26_224613](https://user-images.githubusercontent.com/64591583/155861523-2b70bfb4-72ea-4c9d-968b-ae28ffbcb635.png)

同样的配置，使用 v2rayN (使用 v2fly_core)并在 /path 后面加 ?ed=2048 就可以用：
![2022-02-26_224348](https://user-images.githubusercontent.com/64591583/155861564-654de724-13eb-4921-a533-86852be1d557.png)

经测试，clash 无论是加 max-early-data: 2048 和 early-data-header-name: Sec-WebSocket-Protocol 还是加 ?ed=2048，都会导致节点不可用。

我在测试时发现，若 v2rayN 使用的不是 v2fly_core，而是 xray_core 的话，在 /path 后添加 ?ed=2048 同样会导致节点不可用 (我的服务器安装的是 v2fly)，因此我怀疑 clash 的这个问题会不会与此有关。(无论是在服务端还是客户端，我安装的 v2fly_core 或 xray_core 都为最新版。)
