### ISSUE TITLE
[Feature] 关于新增 PROXY-PORT 规则可行性探讨

### ISSUE THREAD

**Issue by ihotte** [Dreamacro/clash#2001]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

- 机场提供的节点一般都有同时在线数限制，局域网内一般将 Clash 部署在 OpenWrt 路由器上，可以满足大多说普通用户使用。

- 但是对于部分需要使用全局代理的用户存在限制，比如传统使用 `SwitchyOmega` 插件习惯自定义规则的浏览器用户。

- 奈非对节点要求比较高，需要使用特定节点才能正常浏览

  

举个例子：比如机场提供的配置文件中 `jsdelivr.com` 属于直连，但实际 `jsdelivr.com` 需要代理才能访问（近期被屏蔽），此时内网用户将无法访问 `jsdelivr.com`，并且无法在用户端干预。

---

- 新增一组动态端口配置 `ports`，在默认端口之外供用户自行配置。

- 新增 `PROXY-PORT` 匹配规则，根据代理的入口端口匹配代理（组）

```
ports:
- port: 7891
  type: socks
- port: 7892
  type: socks
- port: 7893
  type: http
...

rules:
- PROXY-PORT,7891,代理
- PROXY-PORT,7892,油管
- PROXY-PORT,7893,奈非
...
```

可以通过 HTTP(s)/Socks 等入口端口指定访问规则，使 Clash 具备根据端口选择代理分组的能力，从而可以聚合不同机场的节点。

### 相关 issues

[根据入口协议类型分别设定不同的转发规则 #629](https://github.com/Dreamacro/clash/issues/629)
[绑定多个端口号，并且可选的将某个端口号指定使用某个 proxy-group #1242](https://github.com/Dreamacro/clash/issues/1242)
[新开一个端口转发给7890作为一条规则 #1568](https://github.com/Dreamacro/clash/issues/1568)
[能否增加第二个 Socks5 全局端口，绕过域名规则匹配  #1995](https://github.com/Dreamacro/clash/issues/1995)
[route based on HTTP/Socks authentication user #1584](https://github.com/Dreamacro/clash/pull/1584) 这个 pull 有个  `AUTH-USER` 规则，不过 Chrome 的 Socks5 不支持 Auth。
