### ISSUE TITLE
proxy-providers下载机场或者引用文件的逻辑

### ISSUE THREAD

**Issue by DockerCS** [Dreamacro/clash#2012]
### Verify steps

- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

2022.01.27 Premium

### Clash config

```yaml
# > 「Dler Cloud机场」所有节点
  DlerCloud:
    type: http
    url: https://dler.cloud/subscribe/XXXXXXXXXXXXXX?protocols=ss&list=clash
    path: ./Proxy/DlerCloud.yaml
    interval: 21600
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 600

  # > 「Dler Cloud机场」香港HC节点
  UrlTestList:
    type: file
    path: ./Proxy/DlerCloud.yaml
    filter: "香港 HC|CC"
    interval: 21600
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 600

  # > 「Dler Cloud机场」HC节点
  FallbackList:
    type: file
    path: ./Proxy/DlerCloud.yaml
    filter: "(台湾|香港|新加坡|日本|美国) HC|CC"
    interval: 21600
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 600

  # > 「Dler Cloud机场」所有节点
  ProxyList:
    type: file
    path: ./Proxy/DlerCloud.yaml
    interval: 21600
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 600

  # > 「Dler Cloud机场」香港IEPL和香港HC节点
  AppleList:
    type: file
    path: ./Proxy/DlerCloud.yaml
    filter: "香港 (IEPL|HC|CC)"
    interval: 21600
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 600

  SpeedtestList:
    type: file
    path: ./Proxy/DlerCloud.yaml
    filter: "HC|CC"
    interval: 21600
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 600

  PayPalList:
    type: file
    path: ./Proxy/DlerCloud.yaml
    filter: "HC|CC"
    interval: 21600
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 600

  NetflixList:
    type: file
    path: ./Proxy/DlerCloud.yaml
    filter: "巴西|HC|CC"
    interval: 21600
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 600

  HBOMaxList:
    type: file
    path: ./Proxy/DlerCloud.yaml
    filter: "(台湾|香港|新加坡|日本|美国) HC|CC"
    interval: 21600
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 600

  DisneyPlusList:
    type: file
    path: ./Proxy/DlerCloud.yaml
    filter: "(台湾|香港|新加坡|日本|美国) HC|CC"
    interval: 21600
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 600

  ScholarList:
    type: file
    path: ./Proxy/DlerCloud.yaml
    filter: "(台湾|香港|新加坡|日本|美国) HC|CC"
    interval: 21600
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 600
```

### Description

![5DC135D6-38B3-4711-920A-7630E14F4105](https://user-images.githubusercontent.com/26867628/156914452-f14758ae-b904-48e8-85dd-a7a810526910.png)

机场订阅文件不是从上到下依次下载么？

如图以及我的配置所示，先去寻找AppleList这个在不在，而不是首先下载第一条proxy provider
