### ISSUE TITLE
[Feature] Script shortcut 支持更多函数 | Script shortcut support more functions

### ISSUE THREAD

**Issue by Masaiki** [Dreamacro/clash#2021]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

想要实现的：
```yaml
script:
  shortcuts:
    majsoul: host.startswith('majsoul-hk')
rules:
  - SCRIPT,majsoul,Proxy
```
 
规则里只有后缀匹配和关键词匹配 感觉有的时候还是需要前缀匹配
这个时候去换用Script模式又不太值当 关键词匹配有匹配错的可能而且性能上会比前缀匹配差
