### ISSUE TITLE
[Bug] auto-detect-interface doesn't work when there are multiple utun devices

### ISSUE THREAD

**Issue by attachonku** [Dreamacro/clash#2026]
### Verify steps

- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

Premium 2022.01.27

### What OS are you seeing the problem on?

macOS

### Clash config

```yaml
tun:
  enable: true
  stack: system
  dns-hijack:
    - tcp://8.8.8.8:53
  auto-route: true
  auto-detect-interface: true

proxy-groups:
  - name: "VPN5"
    type: select
    interface-name: utun5
    proxies:
      - "DIRECT"
   - name: "VPN6"
    type: select
    interface-name: utun6
    proxies:
      - "DIRECT"
    - name: "VPN7"
    type: select
    interface-name: utun7
    proxies:
      - "DIRECT"
 rules:
  - IP-CIDR,10.8.0.0/16,VPN5
  - IP-CIDR,10.9.0.0/16,VPN6
  - IP-CIDR,10.10.0.0/16,VPN7
```

### Clash log

```shell
[warning] [TCP] dial VPN5 (match IPCIDR/10.8.0.0/16) to my.openvpnresources.websites:443 error: dial tcp4 10.8.0.3:443: i/o timeout
[warning] [TCP] dial VPN5 (match IPCIDR/10.8.0.0/16) to my.openvpnresources.websites:443 error: dial tcp4 10.8.0.3:443: i/o timeout
```

### Description

If I use clash tun mode, I got utun4(198.18.0.1), All requests start here, it works fine. then I use openvpn at the same time , I got utun5(openvpn), I can't get access utun5(10.8.x.x) resources.  

After I add some rules, proxy-groups. specify interface-name, **it's troublesome but it works fine again.**  

**But I have two or three OpenVPN connections,** So I got utun5(10.8.x.x)、utun6(10.9.x.x)、utun7(10.10.x.x)，and I can't specify utun name for each connection(because macOS/tunnelblick does not support).  

If the network is interrupted and reconnected after the computer sleeps, or I just want to connect one of them. the utun name also changes, **and the interface name must be re-specified in the configuration file each time. If I don't quickly adjust the interface name, all routing table records may lost sometimes, this caused me to have to restart my computer.**   

Can you please add auto-detect-interface for this situation? For example, detect the utun name to which the ip belongs.
