### ISSUE TITLE
[Feature] Trojan Early Data Support

### ISSUE THREAD

**Issue by xjasonlyu** [Dreamacro/clash#2034]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

@Dreamacro 看了一下 Clash 的 Trojan 没有明确支持 earlyData 这个 feature，但是因为clash实现trojan ws用的还是vmess部分的代码，所以理论上给 Trojan 支持 earlyData 应该加几行代码就差不多了(?)

另外，clash确实又可以在path后面加`?ed=2048`这样来使trojan开启earlyData🧐。。
但是这样配置又是不可以的：
```yaml
ws-opts:
  max-early-data: 2048
  early-data-header-name: Sec-WebSocket-Protocol
```

至于Server端，`trojan-go`版似乎不支持earlyData，但是v2fly/xray都是有trojan earlyData的。
