### ISSUE TITLE
[Bug] 规则匹配问题

### ISSUE THREAD

**Issue by Zhou-Account-Remember** [Dreamacro/clash#2045]
### Verify steps

- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

Premium 2022.03.21

### What OS are you seeing the problem on?

Windows

### Clash config

```yaml
port: 7890
socks-port: 7891
redir-port: 7892
mixed-port: 7893
allow-lan: false
mode: Rule
log-level: info
external-controller: 127.0.0.1:9090
proxy-groups:
  - name: PROXY
    type: url-test
    use:
      - proxy
    url: http://www.gstatic.com/generate_204
    interval: 300
  - name: m
    type: select
    proxies:
      - DIRECT
      - PROXY
proxy-providers:
  proxy:
    type: http
    path: ./s.yml
    interval: 3600
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300
rules:
  - RULE-SET,rule,PROXY
  - MATCH,m
rule-providers:
  rule:
    type: file
    behavior: domain
    path: ./rule.yaml
    interval: 86400
```

### Clash log

```shell
time="2022-03-25T18:44:36+08:00" level=info msg="RESTful API listening at: 127.0.0.1:4743"
time="2022-03-25T18:44:36+08:00" level=info msg="Mixed(http+socks) proxy listening at: 127.0.0.1:7890"
time="2022-03-25T18:44:36+08:00" level=warning msg="[TCP] dial DIRECT to raw.githubusercontent.com:443 error: lookup raw.githubusercontent.com: getaddrinfow: The requested name is valid, but no data of the requested type was found."
time="2022-03-25T18:44:36+08:00" level=warning msg="[TCP] dial DIRECT to raw.githubusercontent.com:443 error: lookup raw.githubusercontent.com: getaddrinfow: The requested name is valid, but no data of the requested type was found."
time="2022-03-25T18:44:36+08:00" level=info msg="[TCP] 127.0.0.1:4756 --> api.github.com:443 doesn't match any rule using DIRECT"
time="2022-03-25T18:44:36+08:00" level=info msg="Start initial provider proxy"
time="2022-03-25T18:44:36+08:00" level=info msg="Start initial compatible provider m"
time="2022-03-25T18:44:36+08:00" level=info msg="Start initial rule provider rule"
time="2022-03-25T18:44:36+08:00" level=info msg="[TCP] 127.0.0.1:4752 --> passport.baidu.com:443 match Match() using m[DIRECT]"
time="2022-03-25T18:44:37+08:00" level=info msg="[TCP] 127.0.0.1:4753 --> f-log-win-extension.grammarly.io:443 match Match() using m[DIRECT]"
time="2022-03-25T18:44:39+08:00" level=info msg="[TCP] 127.0.0.1:4790 --> capi.grammarly.com:443 match Match() using m[DIRECT]"
time="2022-03-25T18:44:40+08:00" level=info msg="[TCP] 127.0.0.1:4792 --> capi.grammarly.com:443 match Match() using m[DIRECT]"
time="2022-03-25T18:44:41+08:00" level=info msg="[TCP] 127.0.0.1:4794 --> femetrics.grammarly.io:443 match Match() using m[DIRECT]"
time="2022-03-25T18:44:42+08:00" level=info msg="[TCP] 127.0.0.1:4796 --> alive.github.com:443 match Match() using m[DIRECT]"
time="2022-03-25T18:44:47+08:00" level=info msg="[TCP] 127.0.0.1:4801 --> zh.wikipedia.org:443 match Match() using m[DIRECT]"
time="2022-03-25T18:44:50+08:00" level=info msg="[TCP] 127.0.0.1:4804 --> gnar.grammarly.com:443 match Match() using m[DIRECT]"
time="2022-03-25T18:45:16+08:00" level=info msg="[TCP] 127.0.0.1:4818 --> edge.microsoft.com:80 match Match() using m[DIRECT]"
time="2022-03-25T18:45:18+08:00" level=info msg="[TCP] 127.0.0.1:4820 --> zh.wikipedia.org:443 match Match() using m[DIRECT]"
time="2022-03-25T18:45:18+08:00" level=info msg="[TCP] 127.0.0.1:4823 --> zh.wikipedia.org:443 match Match() using m[DIRECT]"
```

### Description

rule.yaml存在以下内容：
```
payload:
  - '+.ja.wikipedia.org'
  - '+.wikipedia.org'
```
`'+.wikipedia.org'`没有与zh.wikipedia.org匹配。

**Comment by Dreamacro** [comment]
试试现在最新的 latest 呢

**Comment by Zhou-Account-Remember** [comment]
> 试试现在最新的 latest 呢

解决了上述问题，但是出现了新的问题：
config.yaml：
```
port: 7890
allow-lan: false
mode: Rule
log-level: debug
external-controller: 127.0.0.1:9090
proxy-groups:
  - name: PROXY
    type: url-test
    use:
      - proxy
    url: http://www.gstatic.com/generate_204
    interval: 300
  - name: m
    type: select
    proxies:
      - DIRECT
      - PROXY
proxy-providers:
  proxy:
    type: http
    path: ./s.yml
    interval: 3600
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300
rules:
  - RULE-SET,direct,DIRECT
  - RULE-SET,proxy,PROXY
  - MATCH,m
rule-providers:
  direct:
    type: file
    behavior: domain
    path: ./direct.yaml
  proxy:
    type: file
    behavior: domain
    path: ./proxy.yaml
```
direct.yaml：
```
payload:
  - '+.le.com'
```
proxy.yaml：
```
payload:
  - '+.google.com'
```
日志：
```
time="2022-03-30T19:37:03+08:00" level=info msg="Start initial provider proxy"
time="2022-03-30T19:37:03+08:00" level=info msg="Start initial compatible provider m"
time="2022-03-30T19:37:03+08:00" level=info msg="Start initial rule provider direct"
time="2022-03-30T19:37:03+08:00" level=info msg="Start initial rule provider proxy"
time="2022-03-30T19:37:03+08:00" level=info msg="RESTful API listening at: 127.0.0.1:9090"
time="2022-03-30T19:37:03+08:00" level=info msg="HTTP proxy listening at: 127.0.0.1:7890"
time="2022-03-30T19:37:04+08:00" level=info msg="[TCP] 127.0.0.1:11674 --> f-log-win-extension.grammarly.io:443 match Match() using m[DIRECT]"
time="2022-03-30T19:37:05+08:00" level=info msg="[TCP] 127.0.0.1:11659 --> femetrics.grammarly.io:443 match Match() using m[DIRECT]"
time="2022-03-30T19:37:08+08:00" level=warning msg="[TCP] dial DIRECT (match RuleSet/direct) to www.google.com:443 error: dial tcp4 199.16.158.8:443: i/o timeout"
time="2022-03-30T19:37:13+08:00" level=warning msg="[TCP] dial DIRECT (match RuleSet/direct) to www.google.com:443 error: dial tcp4 199.16.158.8:443: i/o timeout"
time="2022-03-30T19:37:20+08:00" level=warning msg="[TCP] dial DIRECT (match RuleSet/direct) to www.google.com:443 error: dial tcp4 199.16.158.8:443: i/o timeout"
time="2022-03-30T19:37:25+08:00" level=warning msg="[TCP] dial DIRECT (match RuleSet/direct) to www.google.com:443 error: dial tcp4 199.16.158.8:443: i/o timeout"
```
www.google.com 被`'+.le.com'`匹配了。
