### ISSUE TITLE
[Bug] 使用bbolt后arm路由器无法正常使用cache问题，此问题从2021.09.15之后一致存在

### ISSUE THREAD

**Issue by Awkee** [Dreamacro/clash#2047]
### Verify steps

- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

使用bbolt每个版本

### What OS are you seeing the problem on?

Linux

### Clash config

```yaml
port: 7890
socks-port: 1080 # SOCKS5代理端口，DNS请求会中转
redir-port: 3333 # 透明代理端口
allow-lan: true
mode: Rule
log-level: info # 日志显示级别： debug-问题调试，info-基本信息
external-controller: 0.0.0.0:9090
secret: route
hosts:
  router.asus.com: 192.168.50.1
# 透明代理开启DNS
dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:1053
  enhanced-mode: redir-host # redir-host or fake-ip
  fake-ip-range: 198.18.0.1/16 # Fake IP addresses pool CIDR
  use-hosts: false # lookup hosts and return IP record
  nameserver:
    - 114.114.114.114
  # 提供 fallback 时，如果GEOIP非 CN 中国时使用 fallback 解析
  fallback:
    - 8.8.8.8 # Google DNS over TCP
    - 1.1.1.1 # cloudflare DNS over TCP
    - tls://8.8.8.8:853 # Google DNS over TLS
    - tls://1.1.1.1:853 # cloudflare DNS over TLS
    - https://dns.google/dns-query # Google DNS over HTTPS
    - https://cloudflare-dns.com/dns-query # cloudflare DNS over HTTPS
  # 强制DNS解析使用`fallback`配置
  fallback-filter:
    # true: CN使用nameserver解析，非CN使用fallback
    geoip: true
    # geoip设置为false时有效： 不匹配`ipcidr`地址时会使用`nameserver`结果，匹配`ipcidr`地址时使用`fallback`结果。
    ipcidr:
      - 240.0.0.0/4
# DIY组保留的个人节点
proxies: []
# 配置规则参考文档： https://github.com/Dreamacro/clash/wiki/configuration
# 设置代理提供者(远程订阅地址+本地订阅文件)
proxy-providers:
...
```

### Description

自从使用了`go.etcd.io/bbolt`之后，我在armv8路由器上再也无法使用cache文件了，每个`Premium`新版本总是报如下错误信息:
```txt
INFO[0004] Start initial rule provider video_netflix    
INFO[0004] Start initial rule provider google           
INFO[0005] Start initial rule provider video_iqiyi      
INFO[0005] Start initial rule provider applications     
WARN[0005] [CacheFile] can't open cache file: invalid argument
INFO[0005] DNS server listening at: [::]:1053           
INFO[0005] HTTP proxy listening at: [::]:7890           
INFO[0005] SOCKS proxy listening at: [::]:1080          
INFO[0005] Redirect proxy listening at: [::]:3333       
INFO[0005] RESTful API listening at: [::]:9090          
```

`WARN[0005] [CacheFile] can't open cache file: invalid argument`这段警告内容在开源代码里可以看到，是在[这个位置](https://github.com/Dreamacro/clash/blob/cb95326aca85b89da6182d0f72ee215354f59cc2/component/profile/cachefile/cache.go#L152), 我猜`premium`版本内容跟这个大概一致。

于是，我将这段代码提取出来写了一段测试代码，结果在ARM路由器上运行正常，没有报错`invalid argument`信息，**这该怎么解释呢?**

测试代码如下：
```golang
package main

import (
	"log"
	"time"
	"os"
	bbolt "go.etcd.io/bbolt"
)


func main() {
	var fileMode     os.FileMode = 0o666
	var dbFile = "/tmp/abc/my.db"
	options := bbolt.Options{Timeout: time.Second}
	db, err := bbolt.Open( dbFile, fileMode, &options)
	defer db.Close()
	switch err {
	case bbolt.ErrInvalid, bbolt.ErrChecksum, bbolt.ErrVersionMismatch:
		if err = os.Remove(dbFile); err != nil {
			log.Fatal("[CacheFile] remove invalid cache file error: %s", err.Error())
			break
		}
		log.Println("[CacheFile] remove invalid cache file and create new one")
		db, err = bbolt.Open(dbFile, fileMode, &options)
	}
	if err != nil {
		log.Fatal("[CacheFile] can't open cache file: %s", err.Error())
	}
}
```

**按测试来看，`bbolt`库可以在arm路由器上正常运行，是否跟哪些编译参数有关系导致出现上面问题呢？**
