### ISSUE TITLE
[Bug] 连接到开启 TUN 模式（DNS 服务器）的设备，无法使用 FaceTime

### ISSUE THREAD

**Issue by WePosts** [Dreamacro/clash#2050]
### Verify steps

- [ ]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [ ]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

Clash Premium 2022.03.21

### What OS are you seeing the problem on?

Linux

### Clash config

```yaml
port: 7890

socks-port: 7891

allow-lan: true

mode: global

log-level: debug

external-controller: 0.0.0.0:9090

external-ui: dashboard

secret: "0"

dns:
  enable: true
  listen: 0.0.0.0:53
  
  enhanced-mode: fake-ip # or redir-host
  
  nameserver:
    - 114.114.114.114 # default value
    - 8.8.8.8 # default value

proxy-groups:

  - name: Provider-A
    type: select
    use:
      - ProviderA

proxy-providers:

  ProviderA:
    type: http
    url: a.url
    interval: 3600
    path: ./ProviderA.yaml
    health-check:
      enable: true
      interval: 600
      url: http://www.gstatic.com/generate_204

tun:
  enable: true
  stack: system
```

### Clash log

```shell
2022-03-29 10:11:36[info] [TCP] 192.168.3.78:58051 --> query.ess.apple.com:443 using GLOBAL
2022-03-29 10:11:36[info] [TCP] 192.168.3.78:58052 --> gateway.icloud.com:443 using GLOBAL
2022-03-29 10:11:36[info] [TCP] 192.168.3.78:58053 --> gateway.icloud.com:443 using GLOBAL
2022-03-29 10:11:36[info] [TCP] 192.168.3.78:58055 --> gateway.icloud.com:443 using GLOBAL
```

### Description

想在 Apple TV 上使用 SharePlay (同播共享) 的时候遇到一些问题。

因为 Apple TV 上的 设置 - 网络 的选项中，只有配置 IP 和 DNS 的选项。所以在局域网内的 设备R 上开启了 TUN 和 fake-ip，把 Apple TV 的 “路由器” IP  地址设置为 设备R 的 IP，DNS 服务器设置为 198.18.0.1，来解决播放节目时的卡顿和缓冲问题。

[在 Apple TV 开始 SharePlay](https://support.apple.com/zh-cn/HT213071) 需要这样几个步骤：
1. 在 iOS 设备上开始 FaceTime 通话
2. 在 Apple TV 上点击 SharePlay 的选项
3. 在 iOS 设备上确认
4. Apple TV 开始 SharePlay

前三个步骤都很顺利，但在 iOS 设备上点击确认后，tvOS 依旧停留在 “在 ____（iOS 设备名）上确认” 的界面，始终无法开始播放。

如果在 Apple TV 不调整网络设置，直接连接，是可以正常开始的——但播放节目会非常卡。

怀疑是 FaceTime 对网络连接有要求。又测试了几种情况：

- 在 iOS 设备上，将 “路由器” IP 调整为 设备R，DNS 调整为 198.18.0.1（与之前提到的 Apple TV 的配置一样） 
可以发起 FaceTime 但不能正常接通，提示：FaceTime 通话不可用
- 在 iOS 设备上，不使用代理直接连接网络
FaceTime 可以正常使用
- 在 iOS 设备上，将 HTTP 代理配置为 设备R 的 IP 和 端口
可以正常拨打/接通 FaceTime

想尝试通过调整配置的方式解决一下。
