### ISSUE TITLE
clash专业版，无法通过controller api获取流量traffic信息

### ISSUE THREAD

**Issue by tomven1990** [Dreamacro/clash#2052]
### Verify steps

- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

专业版 Clash latest windows amd64 with go1.18 Mon 21 Mar 2022 01:53:10 PM UTC

### What OS are you seeing the problem on?

Windows

### Clash config

```yaml
port: 7890 

# SOCKS5 代理端口
socks-port: 7891 

# Linux 和 macOS 的 redir 代理端口
redir-port: 7892 

# 允许局域网的连接
allow-lan: true

# 规则模式：Rule（规则） / Global（全局代理）/ Direct（全局直连）
mode: Rule

# 设置日志输出级别 (默认级别：silent，即不输出任何内容，以避免因日志内容过大而导致程序内存溢出）。
# 5 个级别：silent / info / warning / error / debug。级别越高日志输出量越大，越倾向于调试，若需要请自行开启。
log-level: debug
# Clash 的 RESTful API
external-controller: '127.0.0.1:53402'
external-ui: dashboard
experimental:
  ignore-resolve-fail: true
# RESTful API 的口令
secret: 'c7efc187-a97a-xxxx-xxxx-xxxxxxxxx' 

# 您可以将静态网页资源（如 clash-dashboard）放置在一个目录中，clash 将会服务于 `RESTful API/ui`
# 参数应填写配置目录的相对路径或绝对路径。
# external-ui: folder

dns:
  enable: true
  ipv6: false
  default-nameserver:
    - 8.8.8.8
    - 8.8.4.4
  enhanced-mode: fake-ip
  fake-ip-filter:
    - '*.lan'
  nameserver:
    - 223.5.5.5
    - 223.6.6.6

tun:
  enable: true
  stack: system # or gvisor
  dns-hijack:
    - 198.18.0.2:53
  auto-route: true
  auto-detect-interface: true

proxies:
  - {"name":"falstlink","type":"vmess","server":"xxxxx","port":58511,"uuid":"xxxxxx","alterId":0,"cipher":"auto","udp":true}
  - {"name":"proxycheck","type":"vmess","server":"xxxxx","port":22224,"uuid":"xxxxxxx","alterId":0,"cipher":"auto","udp":true}

proxy-groups:
-
  name: DIRECT_OUT
  type: select
  proxies:
    - DIRECT
-
  name: PROXY_V
  type: select
  proxies:
    - falstlink
    - DIRECT
-
  name: PROXY_CHECK
  type: select
  proxies:
    - proxycheck


# 规则
rules:
  - DOMAIN-SUFFIX,baidu.com,PROXY_CHECK
  - GEOIP,CN,DIRECT_OUT
  - MATCH,PROXY_V
```

### Clash log

```shell
无
```

### Description

clash专业版，无法通过controller api获取流量信息，请求无法响应。通过客户端查看连接好像是调用ws://connnections，请问是什么原因？文档没更新？
<img width="647" alt="image" src="https://user-images.githubusercontent.com/2385355/160903938-c5895c89-ffb7-47cc-81e4-fd5513e2c331.png">
