### ISSUE TITLE
[Bug] Proxy connection using domain name will timeout if the first dns server is unavailable

### ISSUE THREAD

**Issue by Olivina** [Dreamacro/clash#2055]
### Verify steps

- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

v1.10.0

### What OS are you seeing the problem on?

Linux

### Clash config

```yaml
#I'm pretty sure the clash config isn't the problem. But if necessary:
mixed-port: 7899
allow-lan: true
mode: rule
log-level: debug
external-controller: '0.0.0.0:9090'
secret: ''
proxies:
  -
    name: <name>
    type: ss
    server: [domain name]
    port: '*****'
    cipher: aes-128-gcm
    password: ****
    udp: false
    plugin: obfs
    plugin-opts:
      mode: http
      host: ****
# remains are similar
```

### Clash log

```shell
# tty1
> export http_proxy=http://127.0.0.1:7899/ https_proxy=http://127.0.0.1:7899/ all_proxy=socks5://127.0.0.1:7899/
> curl baidu.com
...
# connection failed

# tty2
> clash -f xxxx.yaml
INFO[0000] Start initial compatible provider *** 
INFO[0000] Start initial compatible provider ***
INFO[0000] Start initial compatible provider ***
INFO[0000] Mixed(http+socks) proxy listening at: [::]:7899 
INFO[0000] RESTful API listening at: [::]:9090          
DEBU[0013] [DNS] resolve baidu.com error: lookup baidu.com: i/o timeout 
WARN[0018] [TCP] dial *** (match Match/) to baidu.com:80 error: <domain_name>:<port> connect error: lookup ***: i/o timeout
```

## Problem:
If the proxy use domain name and the first DNS specified in the `/etc/resolv.conf` is not available, then the `Clash` client will timeout and directly close the connection without the attempt to trying the next available DNS, thus the connection will not be established even there are available DNSes.

Maybe it's because the go library use `gethostbyname()` as backend which waits for a long time exceeding the `Clash`'s  timeout limit before the next try.

## Possible Solutions:
Two options:
1. set a longer timeout for the DNS request and cache the result
2. we can read the servers specified in `/etc/resolv.conf`, enumerate the servers and use `getaddrinfo()` instead in concurrency.
