### ISSUE TITLE
[Bug] UDP直接直连

### ISSUE THREAD

**Issue by ryanccn** [Dreamacro/clash#2058]
### Verify steps

- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

1.10

### What OS are you seeing the problem on?

macOS

### Clash config

```yaml
proxies:

proxy-groups:
  - name: Proxy
    type: select
    proxies:
      - 🇭🇰
      - 🇯🇵
      - 🇬🇧
      - 🇺🇸
      - 🌎
  - name: 🇭🇰
    type: select
    proxies:
      - HK01
      - HK02
      - HK03
      - HK04
      - HK05
      - HK06
      - HK07
      - HK08
      - HK09
      - HK10
      - HK11
      - HK12
  - name: 🇯🇵
    type: select
    proxies:
      - JP01
      - JP02
      - JP03
      - JP04
      - JP05
      - JP06
      - JP07
      - JP08
  - name: 🇬🇧
    type: select
    proxies:
      - UK01
      - UK02
      - UK03
  - name: 🇺🇸
    type: select
    proxies:
      - US01
      - US02
      - US03
      - US04
      - US05
      - US06
      - US07
      - US08
  - name: 🌎
    type: select
    proxies:
      - HK01
      - HK02
      - HK03
      - HK04
      - HK05
      - HK06
      - HK07
      - HK08
      - HK09
      - HK10
      - HK11
      - HK12
      - JP01
      - JP02
      - JP03
      - JP04
      - JP05
      - JP06
      - JP07
      - JP08
      - KR01
      - KR02
      - KR03
      - NL01
      - NL02
      - NL03
      - RU01
      - RU02
      - RU03
      - SF-AU01
      - SF-AU02
      - SF-AU03
      - SF-BR01
      - SF-BR02
      - SF-BR03
      - SF-CA01
      - SF-CA02
      - SF-CA03
      - SF-FR01
      - SF-FR02
      - SF-FR03
      - SF-GM01
      - SF-GM02
      - SF-GM03
      - SF-IT01
      - SF-IT02
      - SF-IT03
      - SG01
      - SG02
      - SG03
      - TH01
      - TH02
      - TH03
      - TR01
      - TR02
      - TR03
      - TW01
      - TW02
      - TW03
      - UK01
      - UK02
      - UK03
      - US01
      - US02
      - US03
      - US04
      - US05
      - US06
      - US07
      - US08
      - VN01
      - VN02
      - VN03
rule-providers:
  apple-proxy:
    type: http
    behavior: classical
    url: https://cdn.jsdelivr.net/gh/Hackl0us/SS-Rule-Snippet@master/Rulesets/Clash/Basic/Apple-proxy.yaml
    path: ./ruleset/Apple-proxy.yaml
    interval: 3600
  apple-direct:
    type: http
    behavior: classical
    url: https://cdn.jsdelivr.net/gh/Hackl0us/SS-Rule-Snippet@master/Rulesets/Clash/Basic/Apple-direct.yaml
    path: ./ruleset/Apple-direct.yaml
    interval: 3600
  cn:
    type: http
    behavior: classical
    url: https://cdn.jsdelivr.net/gh/Hackl0us/SS-Rule-Snippet@master/Rulesets/Clash/Basic/CN.yaml
    path: ./ruleset/CN.yaml
    interval: 3600
  ad-keyword:
    type: http
    behavior: classical
    url: https://cdn.jsdelivr.net/gh/Hackl0us/SS-Rule-Snippet@master/Rulesets/Clash/Basic/common-ad-keyword.yaml
    path: ./ruleset/common-ad-keyword.yaml
    interval: 3600
  lan:
    type: http
    behavior: classical
    url: https://cdn.jsdelivr.net/gh/Hackl0us/SS-Rule-Snippet@master/Rulesets/Clash/Basic/LAN.yaml
    path: ./ruleset/LAN.yaml
    interval: 3600
rules:
  - DOMAIN-SUFFIX,kkcoding.net,DIRECT
  - DOMAIN-SUFFIX,etiger.vip,DIRECT
  - DOMAIN-SUFFIX,acwing.com,DIRECT
  - DOMAIN-SUFFIX,seedasdan.com,DIRECT
  - DOMAIN-SUFFIX,youkaoshi.cn,DIRECT
  - DOMAIN-SUFFIX,bilibili.com,DIRECT
  - DOMAIN-SUFFIX,bilivideo.com,DIRECT
  - DOMAIN-SUFFIX,xmoj.tech,DIRECT
  - DOMAIN-SUFFIX,noi.cn,DIRECT
  - DOMAIN-SUFFIX,youku.com,DIRECT
  - DOMAIN-SUFFIX,dious.cc,DIRECT
  - DOMAIN-SUFFIX,luogu.com.cn,DIRECT
  - DOMAIN-SUFFIX,chinathinksbig.com,DIRECT
  - DOMAIN-SUFFIX,huaweicloud.com,DIRECT
  - DOMAIN-SUFFIX,huawei.com,DIRECT
  - DOMAIN-SUFFIX,testdaily.cn,DIRECT
  - DOMAIN-SUFFIX,eeo.cn,DIRECT
  - DOMAIN-SUFFIX,126.net,DIRECT
  - PROCESS-NAME,QQ,DIRECT
  - PROCESS-NAME,ClassIn,DIRECT
  - PROCESS-NAME,EeoUpdater,DIRECT
  - PROCESS-NAME,Zhumu,DIRECT
  - PROCESS-NAME,NeteaseMusic,DIRECT
  - PROCESS-NAME,TencentMeeting,DIRECT
  - PROCESS-NAME,WeChat,DIRECT
  - PROCESS-NAME,DingTalk,DIRECT
  - RULE-SET,apple-proxy,Proxy
  - RULE-SET,apple-direct,DIRECT
  - RULE-SET,cn,DIRECT
  - RULE-SET,ad-keyword,REJECT
  - RULE-SET,lan,DIRECT
  - MATCH,Proxy
```

### Description

<img width="674" alt="Screen Shot 2022-04-04 at 21 32 42" src="https://user-images.githubusercontent.com/70191398/161559157-0ae088d5-c5db-4996-89e7-be86afc516e0.png">

凡是使用QUIC（基于UDP）的网站都会直接直连。。。

我是在用ClashX Pro （TUN模式）的
