### ISSUE TITLE
[Bug] OpenWrt上运行一段时间后报错 connect: permission denied

### ISSUE THREAD

**Issue by crysislinux** [Dreamacro/clash#2063]
### Verify steps

- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

Clash v1.10.0 linux amd64 with go1.18 Sat Mar 19 06:03:38 UTC 2022

### What OS are you seeing the problem on?

Linux

### Clash config

```yaml
tproxy-port: 12345
allow-lan: true
bind-address: '*'
mode: rule

log-level: warning

# When set to false, resolver won't translate hostnames to IPv6 addresses
ipv6: true

# Outbound interface name
#interface-name: en0

# fwmark on Linux only
routing-mark: 100

proxies:
  - name: "hk1"
    type: trojan
    server: ipv6 ip
    port: 23456
    password: password
    udp: true
    sni: somedomain.com
    alpn:
      - h2
      - http/1.1
   ...还有一些别的server
proxy-groups:
  - name: "hk"
    type: load-balance
    proxies:
      - hk1
    url: 'http://clients3.google.com/generate_204'
    interval: 300
    strategy: round-robin

rules:
  - MATCH,hk
```

### Clash log

```shell
因为一般要运行几天可能才会出现一次这个问题，所以只有warning日志

Fri Apr  8 19:28:47 2022 daemon.info clash[3939]: time="2022-04-08T11:28:47Z" level=warning msg="[TCP] dial hk (match Match/) to remote server ip:443 error: [my server ipv6 ip]:23456 connect error: dial tcp6 [my server ipv6 ip]:23456: connect: permission denied"
```

### Description

一般要运行几天可能才会出现一次这个问题，出问题是不断报告 connect: permission denied，此时代理不通，无法自行恢复，重启后会恢复正常
