### ISSUE TITLE
[Bug] Linux 系统使用 tun 之后 docker 无法创建 network

### ISSUE THREAD

**Issue by moonheart** [Dreamacro/clash#2071]
### Verify steps

- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

Premium 2022.04.11

### What OS are you seeing the problem on?

Linux

### Clash config

```yaml
mixed-port: 7890
allow-lan: false
mode: rule
log-level: debug
ipv6: false
external-controller: 127.0.0.1:9090
profile:
  store-selected: true

tun:
  enable: true
  stack: gvisor # system gvisor
  auto-route: true
  auto-detect-interface: true
  dns-hijack:
    - 127.0.0.1:53

dns:
  enable: true
  listen: 0.0.0.0:53
  ipv6: false
  nameserver:
    - 8.8.8.8
    - 1.1.1.1
  enhanced-mode: fake-ip # fake-ip redir-host
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.lan'
    - '*.localdomain'
    - '*.example'
    - '*.invalid'
    - '*.localhost'
    - '*.test'
    - '*.local'
    - '*.home.arpa'
    - router.asus.com
    - localhost.sec.qq.com
    - localhost.ptlogin2.qq.com
    - '+.msftconnecttest.com'
```

### Description

clash 使用 tun 之后，docker 无法创建网络， 关闭 tun 之后能够正常创建。

```
# docker network create test
Error response from daemon: could not find an available, non-overlapping IPv4 address pool among the defaults to assign to the network
```
