### ISSUE TITLE
节点域名是通过什么DNS解析的？

### ISSUE THREAD

**Issue by wpzzz** [Dreamacro/clash#2077]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

我有一个节点 s1.server.com 
域名dns默认指向A服务器IP ,电信指向B服务器ip，因为电信连接B较快
但是在clash里，好像只能指向A 
我本地是电信，dig s1.server.com 默认指向B，@119.29.29 和@223.5.5.5 也都指向B， 只有@国外DNS才指向A，单clash连接后测IP总是A，修改配置文件把s1.server.com 添加进fake-ip-filter和nameserver-policy都无效。
cfa和安卓版测试都一样

```
port: 7890
socks-port: 7891
allow-lan: false
mode: Rule
log-level: info
external-controller: 127.0.0.1:9090


dns:
  enable: true
  #listen: 0.0.0.0:53
  ipv6: false
  enhanced-mode: fake-ip
  default-nameserver:
    - 119.29.29.29
    - 223.5.5.5
  nameserver:
    - https://doh.pub/dns-query
    - https://223.5.5.5/dns-query
  fallback:
    - tls://one.one.one.one:853
    - tls://dns.google:853
    - https://1.1.1.1/dns-query
    - https://dns.twnic.tw/dns-query
    - https://dns.adguard.com/dns-query
    - https://doh.dns.sb/dns-query

fake-ip-filter:
    - 's1.server.com'


fallback-filter:
    geoip: true
    geoip-code: CN
    ipcidr:
      - 240.0.0.0/4
    domain:
      - '+.google.com'
      - '+.facebook.com'
      - '+.youtube.com'


nameserver-policy:
  #   's1.server.com': '119.29.29.29'
```

**Comment by wpzzz** [comment]
```
dns:
  enable: true
  ipv6: false
  enhanced-mode: fake-ip
  nameserver-policy:
    's1.server.com': '119.29.29.29'
```
这样可以了， 但是好奇fake-ip-filter里面的为啥无效
