### ISSUE TITLE
建议DNS模块增加一个host映射的功能

### ISSUE THREAD

**Issue by xjasonlyu** [Dreamacro/clash#208]
clash 的`dns`模块已经挺好用了，但是唯独缺少一个类似自定义域名返回特定IP的映射功能

如果能直接在`dns`那里返回的话，有一些就不用到`rule`那里专门去设置匹配的规则的，而且最好`host`功能可以支持通配*域名。

**Comment by Dreamacro** [comment]
```yaml
dns:
  hosts:
    '*.clash.dev': 127.0.0.1
    'alpha.clash.dev': '::1'
```

implementation in dev branch, have a try
