### ISSUE TITLE
[Bug] fake-ip 模式下没有返回 fake-ip

### ISSUE THREAD

**Issue by moonheart** [Dreamacro/clash#2083]
### Verify steps

- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

Clash latest linux amd64 with go1.18.1 Sat 16 Apr 2022 07:56:37 AM UTC

### Clash config

```yaml
mixed-port: 7890
allow-lan: false
mode: rule
log-level: debug
ipv6: false
external-controller: 127.0.0.1:9090
external-ui: /srv/clash/yacd/
profile:
  store-selected: true

tun:
  enable: true
  stack: gvisor # system gvisor
  auto-route: true
  auto-detect-interface: true
  dns-hijack:
    - 127.0.0.1:53

dns:
  enable: true
  listen: 0.0.0.0:53
  ipv6: false
  default-nameserver:
    - 1.1.1.1
  nameserver:
    - 1.1.1.1
  fallback:
    - 1.1.1.1
  enhanced-mode: redir-host # fake-ip redir-host
  fake-ip-range: 198.18.0.1/16
```

### Clash log

```shell
4月 17 21:14:16 tb14p-debian clash[50026]: time="2022-04-17T21:14:16+08:00" level=info msg="[UDP] 198.18.0.1:39673 --> 192.168.50.1:53 match RuleSet(lancidr) using DIRECT"
4月 17 21:14:16 tb14p-debian clash[50026]: time="2022-04-17T21:14:16+08:00" level=info msg="[TCP] 198.18.0.1:45778 --> 142.251.42.238:80 match Match() using PROXY[XXXXXXXX]"
```

### Description

fake-ip 模式下并且开启tun, 正常来说应该会拦截操作系统的 dns 请求直接返回 fake-ip-range 中的一个 ip, 但是在我的设备上和预期的行为不一致。
从上方的日志可以看出，clash 直接调用了操作系统的 dns 地址进行了解析并返回，后续一条日志中的 `142.251.42.238` 就是解析出来的 ip。这一点从抓包中也可以看出来。

执行 `curl http://google.com -v`
```
*   Trying 142.251.42.238:80...
* Connected to google.com (142.251.42.238) port 80 (#0)
> GET / HTTP/1.1
> Host: google.com
> User-Agent: curl/7.82.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 301 Moved Permanently
< Location: http://www.google.com/
< Content-Type: text/html; charset=UTF-8
< Date: Sun, 17 Apr 2022 13:14:16 GMT
< Expires: Tue, 17 May 2022 13:14:16 GMT
< Cache-Control: public, max-age=2592000
< Server: gws
< Content-Length: 219
< X-XSS-Protection: 0
< X-Frame-Options: SAMEORIGIN
< 
<HTML><HEAD><meta http-equiv="content-type" content="text/html;charset=utf-8">
<TITLE>301 Moved</TITLE></HEAD><BODY>
<H1>301 Moved</H1>
The document has moved
<A HREF="http://www.google.com/">here</A>.
</BODY></HTML>
* Connection #0 to host google.com left intact
```
`sudo tcpdump -i utun -n -U`
```
21:14:16.422283 IP 198.18.0.1.39673 > 192.168.50.1.53: 42477+ A? google.com. (28)
21:14:16.422295 IP 198.18.0.1.39673 > 192.168.50.1.53: 20453+ AAAA? google.com. (28)
21:14:16.456732 IP 192.168.50.1.53 > 198.18.0.1.39673: 20453 0/1/0 (78)
21:14:16.456823 IP 192.168.50.1.53 > 198.18.0.1.39673: 42477 1/0/0 A 142.251.42.238 (44)
21:14:16.457295 IP 198.18.0.1.45778 > 142.251.42.238.80: Flags [S], seq 595867789, win 62720, options [mss 8960,sackOK,TS val 3932398600 ecr 0,nop,wscale 7], length 0
21:14:16.457634 IP 142.251.42.238.80 > 198.18.0.1.45778: Flags [S.], seq 176343989, ack 595867790, win 65535, options [mss 8960,sackOK,TS val 2896606613 ecr 3932398600,nop,wscale 0], length 0
21:14:16.457681 IP 198.18.0.1.45778 > 142.251.42.238.80: Flags [.], ack 1, win 490, options [nop,nop,TS val 3932398600 ecr 2896606613], length 0
21:14:16.457845 IP 198.18.0.1.45778 > 142.251.42.238.80: Flags [P.], seq 1:75, ack 1, win 490, options [nop,nop,TS val 3932398600 ecr 2896606613], length 74: HTTP: GET / HTTP/1.1

```
我不确定是我哪儿配置有问题还是设备上有其他的干扰项。这导致的问题是可能存在的 dns 污染，比如 raw.githubusercontent.com 被解析到了 0.0.0.0

clash 使用 systemd 进行管理
```
❯ systemctl cat clash
# /etc/systemd/system/clash.service
[Unit]
Description=A rule based proxy tunnel
After=network-online.target nftables.service iptabels.service

[Service]
Type=simple
LimitNOFILE=65535
ExecStart =/usr/bin/clash -d /srv/clash

[Install]
WantedBy=multi-user.target
```
