### ISSUE TITLE
[Bug] TPROXY UDP error: address already in use

### ISSUE THREAD

**Issue by vvtommy** [Dreamacro/clash#2085]
### Verify steps

- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

Clash 2022.04.17 linux arm64 with go1.18.1 Sun Apr 17 13:53:06 UTC 202

### What OS are you seeing the problem on?

Linux

### Clash config

```yaml
redir-port: 7892
rules:
  - MATCH,DIRECT


dns:
  enable: true
  listen: 0.0.0.0:1053
  enhanced-mode: redir-host
  default-nameserver:
    - 114.114.114.114
    - 8.8.8.8
  nameserver:
    - 114.114.114.114
    - 114.114.115.115
  fallback:
    - tls://cloudflare-dns.com:853
    - tls://dns.google:853
    - tls://dns.quad9.net:853
    - tls://security-filter-dns.cleanbrowsing.org:853
    - https://1.1.1.1/dns-query
    - 127.0.0.1:40053
port: 7890
socks-port: 7891
mixed-port: 8899
allow-lan: true
mode: Rule
log-level: debug
```

### Description
如题，发送 UDP 之后均出现超时。日志中只记录了一条发送记录。在对比了 [v1.10.0](https://github.com/Dreamacro/clash/tree/v1.10.0) 后发现在 `WriteBack` 时发生错误: `address already in use`。

在下面三个场景上使用命令测试：
- mosdns(53) `dig baidu.com @114.114.114.114`
- avahi-daemon(5353) `dig www.google.com @208.67.222.222 -p5353`
- ntpd(123) `ntpdate -q ntp.aliyun.com`

Premium 2022.04.17 的测试结果：
- mosdns(53) 出现问题
- avahi-daemon(5353) 出现问题
- ntpd(123) 出现问题

v1.10.0 的测试结果
- mosdns(53) 出现问题
- avahi-daemon(5353) 工作正常
- ntpd(123) 出现问题
