### ISSUE TITLE
[Bug] 无法访问 docker 容器映射出来的端口

### ISSUE THREAD

**Issue by moonheart** [Dreamacro/clash#2087]
### Verify steps

- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

Clash latest linux amd64 with go1.18.1 Sun 17 Apr 2022 01:54:36 PM UTC

### What OS are you seeing the problem on?

Linux

### Clash config

```yaml
mixed-port: 7890
allow-lan: false
mode: rule
log-level: debug
ipv6: false
external-controller: 127.0.0.1:9090
external-ui: /srv/clash/yacd/
profile:
  store-selected: true
  store-fake-ip: true

tun:
  enable: true
  stack: gvisor # system gvisor
  auto-route: true
  auto-detect-interface: true
  dns-hijack:
    - any:53

dns:
  enable: true
  listen: 0.0.0.0:53
  ipv6: false
  default-nameserver:
    - 223.5.5.5
  nameserver:
    - 223.5.5.5
    - 10.2.1.1
  fallback:
    - 10.2.1.1
    - 223.5.5.5
  enhanced-mode: fake-ip # fake-ip redir-host
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.lan'
    - '*.localdomain'
    - '*.example'
    - '*.invalid'
    - '*.localhost'
    - 'localhost'
    - '*.test'
    - '*.local'
    - '*.home.arpa'
    - router.asus.com
    - localhost.sec.qq.com
    - localhost.ptlogin2.qq.com
    - '+.msftconnecttest.com'
```

### Clash log

```shell
4月 19 14:05:42 tb14p-debian clash[729191]: time="2022-04-19T14:05:42+08:00" level=warning msg="[TCP] dial DIRECT (match RuleSet/lancidr) to 172.17.0.3:80 error: dial tcp4 172.17.0.3:80: i/o timeout"
```

### Description

我运行了一个 nginx 容器，映射端口 50006:80 `docker run -d --name nginx -p 50006:80 nginx`
容器 ip 为 `172.17.0.3`，和上面日志一样
```
docker inspect nginx | grep '"IPAddress"'
            "IPAddress": "172.17.0.3",
                    "IPAddress": "172.17.0.3",
```
发现无法访问 127.0.0.1:50006
```
❯ curl 127.0.0.1:50006 -v
*   Trying 127.0.0.1:50006...
* Connected to 127.0.0.1 (127.0.0.1) port 50006 (#0)
> GET / HTTP/1.1
> Host: 127.0.0.1:50006
> User-Agent: curl/7.82.0
> Accept: */*
> 
* Empty reply from server
* Closing connection 0
curl: (52) Empty reply from server
```
也无法访问 172.17.0.3:80 
```
❯ curl 172.17.0.3:80 -v
*   Trying 172.17.0.3:80...
* Connected to 172.17.0.3 (172.17.0.3) port 80 (#0)
> GET / HTTP/1.1
> Host: 172.17.0.3
> User-Agent: curl/7.82.0
> Accept: */*
> 
* Recv failure: 连接被对方重设
* Closing connection 0
curl: (56) Recv failure: 连接被对方重设
```
在容器内访问自身是正常的：
```
docker exec nginx curl 127.0.0.1 -v
*   Trying 127.0.0.1:80...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0* Connected to 127.0.0.1 (127.0.0.1) port 80 (#0)
> GET / HTTP/1.1
> Host: 127.0.0.1
> User-Agent: curl/7.74.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Server: nginx/1.21.6
< Date: Tue, 19 Apr 2022 06:25:07 GMT
< Content-Type: text/html
< Content-Length: 615
< Last-Modified: Tue, 25 Jan 2022 15:03:52 GMT
< Connection: keep-alive
< ETag: "61f01158-267"
< Accept-Ranges: bytes
< 
{ [615 bytes data]
100   615  100   615    0     0   600k      0 --:--:-- --:--:-- --:--:--  600k
* Connection #0 to host 127.0.0.1 left intact
<!DOCTYPE html>
<html>
<head>
<title>Welcome to nginx!</title>
<style>
html { color-scheme: light dark; }
body { width: 35em; margin: 0 auto;
font-family: Tahoma, Verdana, Arial, sans-serif; }
</style>
</head>
<body>
<h1>Welcome to nginx!</h1>
<p>If you see this page, the nginx web server is successfully installed and
working. Further configuration is required.</p>

<p>For online documentation and support please refer to
<a href="http://nginx.org/">nginx.org</a>.<br/>
Commercial support is available at
<a href="http://nginx.com/">nginx.com</a>.</p>

<p><em>Thank you for using nginx.</em></p>
</body>
</html>

```
关闭 clash 后一切正常，我不确定是我的配置有问题还是设备上有其他的干扰

附：

host 的 `iptables -t nat -nvL`
```
Chain PREROUTING (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination         
  742 76080 DOCKER     all  --  *      *       0.0.0.0/0            0.0.0.0/0            ADDRTYPE match dst-type LOCAL

Chain INPUT (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain OUTPUT (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 DOCKER     all  --  *      *       0.0.0.0/0           !127.0.0.0/8          ADDRTYPE match dst-type LOCAL

Chain POSTROUTING (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination         
  959 61819 MASQUERADE  all  --  *      !docker0  172.17.0.0/16        0.0.0.0/0           
    4   306 MASQUERADE  all  --  *      !br-309fdbb50f02  172.18.0.0/16        0.0.0.0/0           
    0     0 MASQUERADE  tcp  --  *      *       172.18.0.2           172.18.0.2           tcp dpt:9443
    0     0 MASQUERADE  tcp  --  *      *       172.17.0.2           172.17.0.2           tcp dpt:19999
    0     0 MASQUERADE  tcp  --  *      *       172.17.0.5           172.17.0.5           tcp dpt:80
    0     0 MASQUERADE  tcp  --  *      *       172.17.0.6           172.17.0.6           tcp dpt:16686
    0     0 MASQUERADE  tcp  --  *      *       172.17.0.6           172.17.0.6           tcp dpt:14250
    0     0 MASQUERADE  tcp  --  *      *       172.17.0.3           172.17.0.3           tcp dpt:80

Chain DOCKER (2 references)
 pkts bytes target     prot opt in     out     source               destination         
   16   960 RETURN     all  --  docker0 *       0.0.0.0/0            0.0.0.0/0           
    0     0 RETURN     all  --  br-309fdbb50f02 *       0.0.0.0/0            0.0.0.0/0           
    0     0 DNAT       tcp  --  !br-309fdbb50f02 *       0.0.0.0/0            0.0.0.0/0            tcp dpt:9443 to:172.18.0.2:9443
    0     0 DNAT       tcp  --  !docker0 *       0.0.0.0/0            0.0.0.0/0            tcp dpt:19999 to:172.17.0.2:19999
    0     0 DNAT       tcp  --  !docker0 *       0.0.0.0/0            0.0.0.0/0            tcp dpt:4785 to:172.17.0.5:80
    0     0 DNAT       tcp  --  !docker0 *       0.0.0.0/0            0.0.0.0/0            tcp dpt:16686 to:172.17.0.6:16686
    0     0 DNAT       tcp  --  !docker0 *       0.0.0.0/0            0.0.0.0/0            tcp dpt:14250 to:172.17.0.6:14250
    0     0 DNAT       tcp  --  !docker0 *       0.0.0.0/0            0.0.0.0/0            tcp dpt:50006 to:172.17.0.3:80
```
