### ISSUE TITLE
[Bug] dial tcp4 cloudflareIP:443 i/o time out

### ISSUE THREAD

**Issue by ShiinaKaze** [Dreamacro/clash#2088]
### Verify steps

- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

ClashX

### What OS are you seeing the problem on?

macOS

### Clash config

```yaml
# #---------------------------------------------------#
# ## 配置文件需要放置在 $HOME/.config/clash/*.yaml

# ## 这份文件是clashX的基础配置文件，请尽量新建配置文件进行修改。
# ## ！！！只有这份文件的端口设置会随ClashX启动生效

# ## 如果您不知道如何操作，请参阅 官方Github文档 https://github.com/Dreamacro/clash/blob/dev/README.md
# #---------------------------------------------------#

port: 7890
socks-port: 7891
# Set to true to allow connections to the local-end server from
# other LAN IP addresses
allow-lan: false

# Clash router working mode
# rule: rule-based packet routing
# global: all packets will be forwarded to a single endpoint
# direct: directly forward the packets to the Internet
mode: rule

# Clash by default prints logs to STDOUT
# info / warning / error / debug / silent
log-level: info

# When set to false, resolver won't translate hostnames to IPv6 addresses
ipv6: false

# RESTful web API listening address
external-controller: 127.0.0.1:9090

proxies:
  - name: US
    server: 104.20.61.218
    port: 443
    type: vmess
    uuid: uuid
    alterId: 0
    cipher: auto
    tls: true
    network: ws
    ws-opts:
        path: /
        headers:
          Host: example.com

proxy-groups:
  - name: Proxy
    type: select
    proxies:
      - US

rules:
  - GEOIP,CN,DIRECT
  - MATCH,Proxy
```

### Description
出错：
![8631E5CCB8910409091558574E13973B](https://user-images.githubusercontent.com/89641145/163940977-0335ce21-c4bc-404e-a2de-0a003eff8251.jpg)
正常：
![8927DCDCEF998B57B7663502FDBDA3BC](https://user-images.githubusercontent.com/89641145/163940990-844741ff-16b5-4f57-8a5c-d60402f32730.jpg)
节点协议：vmess
节点服务位置：heroku容器
因直接使用会有极高延迟，所以使用cloudflare的serverless服务cloudflare worker进行反代理
问题出现i/o timeout 错误，已检查节点服务本身无问题。
