### ISSUE TITLE
[Feature] 希望增加IP+端口组口的规则

### ISSUE THREAD

**Issue by skill7899** [Dreamacro/clash#2106]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

目前的rules，要么是IP，要么端口，没有组合一起用的。

**Comment by Dreamacro** [comment]
```yaml
script:
  shortcuts:
    rule: dst_ip == '192.168.1.1' and dst_port == 443

rules:
  - SCRIPT,rule,REJECT
```
