### ISSUE TITLE
[Bug] 在使用过程中只有部分能走代理，如Idea，chrome等，但是有些软件不走代理如Navicat等

### ISSUE THREAD

**Issue by shengyiwen** [Dreamacro/clash#2109]
### Verify steps

- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

1.10.0

### Clash config

```yaml
# (HTTP and SOCKS5 in one port)
port: 7890
socks-port: 7891
# RESTful API for clash
external-controller: 127.0.0.1:9090
allow-lan: true
mode: rule
log-level: debug
tun:
  enable: true
  stack: system
proxies:
  - name: "dev-socks5"
    type: socks5
    server: xxxx
    port: 17890
    username: xxx
    password: xxx
    tls: false
    skip-cert-verify: false
    # udp: true
  - name: "extern-vmess"
    type: vmess
    server: xxxx
    port: 12306
    uuid: xxxxx
    alterId: 64
    cipher: auto
    ttls: false
    skip-cert-verify: false

proxy-groups:
  - name: "extern-vmess-group"
    type: select
    proxies:
      - extern-vmess
      - DIRECT
  - name: "dev-socks5-group"
    type: select
    proxies:
      - dev-socks5
      - DIRECT  

rules:
  - DOMAIN-SUFFIX,google.com,extern-vmess-group
  - DOMAIN-KEYWORD,google,extern-vmess-group
  - DOMAIN,google.com,extern-vmess-group
  - DOMAIN-SUFFIX,ad.com,REJECT
  - GEOIP,CN,DIRECT
  - IP-CIDR,192.168.1.0/24,dev-socks5-group,no-resolve
  - MATCH,DIRECT
```

### Description

你好，本机ip为192.168.31.209，代理192.168.1.128到公司内网。通过Idea等打开没有问题，但是使用navicat打开却无法访问。然后修改日志模式为Debug，发现Navicat没有做拦截，所以咨询一下，希望有懂的大牛指教一下
