### ISSUE TITLE
Fake-ip模式下，使用DoT会观察到clash一直在请求DoT的域名

### ISSUE THREAD

**Issue by 3andero** [Dreamacro/clash#211]
以红鱼dns为例：
![image](https://user-images.githubusercontent.com/31029660/59822190-5263ec80-935e-11e9-8f59-b27682e121ee.png)
配置如下：
```
dns:
  enable: true
  enhanced-mode: fake-ip
  listen: 0.0.0.0:53
  nameserver:
    - tls://dns.rubyfish.cn:853
Rule:
  - DOMAIN-SUFFIX,rubyfish.cn,DIRECT
```
不是很明白原因，我推测如果让DNS里的请求单独处理，不走clash的规则，这个问题会被解决？
另外，在某些时候能看到，如果一个代理服务器的地址是域名，这个域名被clash重复请求的记录。

**Comment by 3andero** [comment]
另外，本问题可以被暂时缓解，原因不明，dns.sb的DoT（可能仅此一家）用IP地址当域名，只要同时使用这个DoT，就不会看到大量重复请求的记录，配置如下：
```
dns:
  enable: true
  enhanced-mode: fake-ip
  listen: 0.0.0.0:53
  nameserver:
    - tls://edns.233py.com:853
    - tls://185.222.222.222:853
```
**其他的DoT如果强行使用ip地址替代域名，则会导致这个DNS无效，大概是因为建立TLS链接的时候会验证host name，而DNS.SB的host name即ip。**
