### ISSUE TITLE
[Bug] 可能不是clash的bug,请问应该如何解决匹配域名规则失效的问题

### ISSUE THREAD

**Issue by thincen** [Dreamacro/clash#2123]
### Verify steps

- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

v1.10.0

### Clash config

```yaml
mixed-port: 7890
redir-port: 7893
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
dns:
  enable: true
  listen: 0.0.0.0:53
  # 相对干净的国内 明文 DNS 服务器地址
  default-nameserver:
    - 119.29.29.29
    - 223.5.5.5
  enhanced-mode: redir-host
  # 解析国内域名时使用的加密 DNS 服务器地址
  nameserver:
    - https://223.5.5.5/dns-query
    - https://119.29.29.29/dns-query
  fallback:
    - https://dns.cloudflare.com/dns-query
    - https://dns.google/dns-query
  fallback-filter:
    geoip: true
    geoip-code: CN
...
proxy-groups:
...
  - name: 🐟 漏网之鱼
    type: select
    proxies:
      - 🎯 全球直连
rules:
  - DOMAIN-SUFFIX,github.com,PROXY
  - MATCH,🐟 漏网之鱼
```

### Clash log

```shell
May 11 16:46:21 debian clash[9270]: time="2022-05-11T16:46:21+08:00" level=warning msg="[TCP] dial 🐟 漏网之鱼 (match Match/) to 140.82.113.3:443 error: dial tcp4 140.82.113.3:443: i/o timeout"
```

### Description

在局域网一台叫debian的主机上使用clash，设置iptables，没有使用fake-ip，域名规则设置github.com使用名为PROXY的代理

实际访问github.com时，log中记录是ip，没有域名信息导致匹配规则失效。
如果使用mixed-port手动代理则不会出现上述现象，成功匹配并代理

查询了之前的Issue，dns缓存、不使用DoT、DoH作为nameserver还是复现
ios的youtube客户端，MATCH设置为PROXY，也没能正常访问
