### ISSUE TITLE
[Bug] 有时候一些网页，在直连能打开的情况下，经过clash会打不开，clash里会显示direct timeout

### ISSUE THREAD

**Issue by ted423** [Dreamacro/clash#2131]
### Verify steps

- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

2022.04.17 Premium (2297)

### Clash config

```yaml
port: 7890
socks-port: 7891
redir-port: 7892
allow-lan: false
mode: Rule
log-level: info
external-controller: 0.0.0.0:9090
secret: ""
cfw-latency-url: http://cp.cloudflare.com/generate_204
proxies:

proxy-groups:
  - name: PROXY
    type: select
    proxies:
      - URLTest 自动选择
      - Fallback 故障转移
      - 🇭🇰 Hong Kong 01
      - 🇭🇰 Hong Kong 02
      - 🇭🇰 Hong Kong 03
      - 🇭🇰 Hong Kong 04
      - 🇭🇰 Hong Kong 05
      - 🇭🇰 Hong Kong 06
      - 🇭🇰 Hong Kong 07
      - 🇭🇰 Hong Kong 08
      - 🇭🇰 Hong Kong 09
      - 🇭🇰 Hong Kong 10
      - 🇭🇰 Hong Kong 11
      - 🇭🇰 Hong Kong 12
      - 🇭🇰 Hong Kong 13
      - 🇭🇰 Hong Kong 14
      - 🇭🇰 Hong Kong 15
      - 🇭🇰 Hong Kong 16
      - 🇯🇵 Japan 01 | Media
      - 🇯🇵 Japan 02 | Media
      - 🇯🇵 Japan 03 | Media
      - 🇯🇵 Japan 04 | Media
      - 🇯🇵 Japan 05 | Media
      - 🇯🇵 Japan 06 | Media
      - 🇸🇬 Singapore 01 | Media
      - 🇸🇬 Singapore 02 | Media
      - 🇸🇬 Singapore 03 | Media
      - 🇸🇬 Singapore 04 | Media
      - 🇸🇬 Singapore 05 | Media
      - 🇸🇬 Singapore 06 | Media
      - 🇹🇼 Taiwan 01
      - 🇹🇼 Taiwan 02
      - 🇹🇼 Taiwan 03
      - 🇹🇼 Taiwan 04
      - 🇹🇼 Taiwan 05
      - 🇹🇼 Taiwan 06
      - 🇹🇼 Taiwan 07
      - 🇹🇼 Taiwan 08
      - 🇺🇸 United States 01 | Media
      - 🇺🇸 United States 02 | Media
      - 🇺🇸 United States 03 | Media
      - 🇺🇸 United States 04 | Media
      - 🇺🇸 United States 05 | Media
  - name: URLTest 自动选择
    type: url-test
    proxies:
      - 🇭🇰 Hong Kong 01
      - 🇭🇰 Hong Kong 02
      - 🇭🇰 Hong Kong 03
      - 🇭🇰 Hong Kong 04
      - 🇭🇰 Hong Kong 05
      - 🇭🇰 Hong Kong 06
      - 🇭🇰 Hong Kong 07
      - 🇭🇰 Hong Kong 08
      - 🇭🇰 Hong Kong 09
      - 🇭🇰 Hong Kong 10
      - 🇭🇰 Hong Kong 11
      - 🇭🇰 Hong Kong 12
      - 🇭🇰 Hong Kong 13
      - 🇭🇰 Hong Kong 14
      - 🇭🇰 Hong Kong 15
      - 🇭🇰 Hong Kong 16
      - 🇯🇵 Japan 01 | Media
      - 🇯🇵 Japan 02 | Media
      - 🇯🇵 Japan 03 | Media
      - 🇯🇵 Japan 04 | Media
      - 🇯🇵 Japan 05 | Media
      - 🇯🇵 Japan 06 | Media
      - 🇸🇬 Singapore 01 | Media
      - 🇸🇬 Singapore 02 | Media
      - 🇸🇬 Singapore 03 | Media
      - 🇸🇬 Singapore 04 | Media
      - 🇸🇬 Singapore 05 | Media
      - 🇸🇬 Singapore 06 | Media
      - 🇹🇼 Taiwan 01
      - 🇹🇼 Taiwan 02
      - 🇹🇼 Taiwan 03
      - 🇹🇼 Taiwan 04
      - 🇹🇼 Taiwan 05
      - 🇹🇼 Taiwan 06
      - 🇹🇼 Taiwan 07
      - 🇹🇼 Taiwan 08
      - 🇺🇸 United States 01 | Media
      - 🇺🇸 United States 02 | Media
      - 🇺🇸 United States 03 | Media
      - 🇺🇸 United States 04 | Media
      - 🇺🇸 United States 05 | Media
    url: http://www.gstatic.com/generate_204
    interval: 300
  - name: Fallback 故障转移
    type: fallback
    proxies:
      - 🇭🇰 Hong Kong 01
      - 🇭🇰 Hong Kong 02
      - 🇭🇰 Hong Kong 03
      - 🇭🇰 Hong Kong 04
      - 🇭🇰 Hong Kong 05
      - 🇭🇰 Hong Kong 06
      - 🇭🇰 Hong Kong 07
      - 🇭🇰 Hong Kong 08
      - 🇭🇰 Hong Kong 09
      - 🇭🇰 Hong Kong 10
      - 🇭🇰 Hong Kong 11
      - 🇭🇰 Hong Kong 12
      - 🇭🇰 Hong Kong 13
      - 🇭🇰 Hong Kong 14
      - 🇭🇰 Hong Kong 15
      - 🇭🇰 Hong Kong 16
      - 🇯🇵 Japan 01 | Media
      - 🇯🇵 Japan 02 | Media
      - 🇯🇵 Japan 03 | Media
      - 🇯🇵 Japan 04 | Media
      - 🇯🇵 Japan 05 | Media
      - 🇯🇵 Japan 06 | Media
      - 🇸🇬 Singapore 01 | Media
      - 🇸🇬 Singapore 02 | Media
      - 🇸🇬 Singapore 03 | Media
      - 🇸🇬 Singapore 04 | Media
      - 🇸🇬 Singapore 05 | Media
      - 🇸🇬 Singapore 06 | Media
      - 🇹🇼 Taiwan 01
      - 🇹🇼 Taiwan 02
      - 🇹🇼 Taiwan 03
      - 🇹🇼 Taiwan 04
      - 🇹🇼 Taiwan 05
      - 🇹🇼 Taiwan 06
      - 🇹🇼 Taiwan 07
      - 🇹🇼 Taiwan 08
      - 🇺🇸 United States 01 | Media
      - 🇺🇸 United States 02 | Media
      - 🇺🇸 United States 03 | Media
      - 🇺🇸 United States 04 | Media
      - 🇺🇸 United States 05 | Media
    url: http://www.gstatic.com/generate_204
    interval: 300
  - name: Final
    type: select
    proxies:
      - PROXY
      - DIRECT
  - name: Domestic
    type: select
    proxies:
      - DIRECT
      - 🇭🇰 Hong Kong 01
      - 🇭🇰 Hong Kong 02
      - 🇭🇰 Hong Kong 03
      - 🇭🇰 Hong Kong 04
      - 🇭🇰 Hong Kong 05
      - 🇭🇰 Hong Kong 06
      - 🇭🇰 Hong Kong 07
      - 🇭🇰 Hong Kong 08
      - 🇭🇰 Hong Kong 09
      - 🇭🇰 Hong Kong 10
      - 🇭🇰 Hong Kong 11
      - 🇭🇰 Hong Kong 12
      - 🇭🇰 Hong Kong 13
      - 🇭🇰 Hong Kong 14
      - 🇭🇰 Hong Kong 15
      - 🇭🇰 Hong Kong 16
      - 🇯🇵 Japan 01 | Media
      - 🇯🇵 Japan 02 | Media
      - 🇯🇵 Japan 03 | Media
      - 🇯🇵 Japan 04 | Media
      - 🇯🇵 Japan 05 | Media
      - 🇯🇵 Japan 06 | Media
      - 🇸🇬 Singapore 01 | Media
      - 🇸🇬 Singapore 02 | Media
      - 🇸🇬 Singapore 03 | Media
      - 🇸🇬 Singapore 04 | Media
      - 🇸🇬 Singapore 05 | Media
      - 🇸🇬 Singapore 06 | Media
      - 🇹🇼 Taiwan 01
      - 🇹🇼 Taiwan 02
      - 🇹🇼 Taiwan 03
      - 🇹🇼 Taiwan 04
      - 🇹🇼 Taiwan 05
      - 🇹🇼 Taiwan 06
      - 🇹🇼 Taiwan 07
      - 🇹🇼 Taiwan 08
      - 🇺🇸 United States 01 | Media
      - 🇺🇸 United States 02 | Media
      - 🇺🇸 United States 03 | Media
      - 🇺🇸 United States 04 | Media
      - 🇺🇸 United States 05 | Media
  - name: Apple
    type: select
    proxies:
      - DIRECT
      - PROXY
  - name: GlobalMedia
    type: select
    proxies:
      - PROXY
      - DIRECT
      - 🇭🇰 Hong Kong 01
      - 🇭🇰 Hong Kong 02
      - 🇭🇰 Hong Kong 03
      - 🇭🇰 Hong Kong 04
      - 🇭🇰 Hong Kong 05
      - 🇭🇰 Hong Kong 06
      - 🇭🇰 Hong Kong 07
      - 🇭🇰 Hong Kong 08
      - 🇭🇰 Hong Kong 09
      - 🇭🇰 Hong Kong 10
      - 🇭🇰 Hong Kong 11
      - 🇭🇰 Hong Kong 12
      - 🇭🇰 Hong Kong 13
      - 🇭🇰 Hong Kong 14
      - 🇭🇰 Hong Kong 15
      - 🇭🇰 Hong Kong 16
      - 🇯🇵 Japan 01 | Media
      - 🇯🇵 Japan 02 | Media
      - 🇯🇵 Japan 03 | Media
      - 🇯🇵 Japan 04 | Media
      - 🇯🇵 Japan 05 | Media
      - 🇯🇵 Japan 06 | Media
      - 🇸🇬 Singapore 01 | Media
      - 🇸🇬 Singapore 02 | Media
      - 🇸🇬 Singapore 03 | Media
      - 🇸🇬 Singapore 04 | Media
      - 🇸🇬 Singapore 05 | Media
      - 🇸🇬 Singapore 06 | Media
      - 🇹🇼 Taiwan 01
      - 🇹🇼 Taiwan 02
      - 🇹🇼 Taiwan 03
      - 🇹🇼 Taiwan 04
      - 🇹🇼 Taiwan 05
      - 🇹🇼 Taiwan 06
      - 🇹🇼 Taiwan 07
      - 🇹🇼 Taiwan 08
      - 🇺🇸 United States 01 | Media
      - 🇺🇸 United States 02 | Media
      - 🇺🇸 United States 03 | Media
      - 🇺🇸 United States 04 | Media
      - 🇺🇸 United States 05 | Media
  - name: HKMTMedia
    type: select
    proxies:
      - DIRECT
      - PROXY
      - 🇭🇰 Hong Kong 01
      - 🇭🇰 Hong Kong 02
      - 🇭🇰 Hong Kong 03
      - 🇭🇰 Hong Kong 04
      - 🇭🇰 Hong Kong 05
      - 🇭🇰 Hong Kong 06
      - 🇭🇰 Hong Kong 07
      - 🇭🇰 Hong Kong 08
      - 🇭🇰 Hong Kong 09
      - 🇭🇰 Hong Kong 10
      - 🇭🇰 Hong Kong 11
      - 🇭🇰 Hong Kong 12
      - 🇭🇰 Hong Kong 13
      - 🇭🇰 Hong Kong 14
      - 🇭🇰 Hong Kong 15
      - 🇭🇰 Hong Kong 16
      - 🇯🇵 Japan 01 | Media
      - 🇯🇵 Japan 02 | Media
      - 🇯🇵 Japan 03 | Media
      - 🇯🇵 Japan 04 | Media
      - 🇯🇵 Japan 05 | Media
      - 🇯🇵 Japan 06 | Media
      - 🇸🇬 Singapore 01 | Media
      - 🇸🇬 Singapore 02 | Media
      - 🇸🇬 Singapore 03 | Media
      - 🇸🇬 Singapore 04 | Media
      - 🇸🇬 Singapore 05 | Media
      - 🇸🇬 Singapore 06 | Media
      - 🇹🇼 Taiwan 01
      - 🇹🇼 Taiwan 02
      - 🇹🇼 Taiwan 03
      - 🇹🇼 Taiwan 04
      - 🇹🇼 Taiwan 05
      - 🇹🇼 Taiwan 06
      - 🇹🇼 Taiwan 07
      - 🇹🇼 Taiwan 08
      - 🇺🇸 United States 01 | Media
      - 🇺🇸 United States 02 | Media
      - 🇺🇸 United States 03 | Media
      - 🇺🇸 United States 04 | Media
      - 🇺🇸 United States 05 | Media
  - name: Ads
    type: select
    proxies:
      - REJECT
      - DIRECT
  - name: JP
    type: select
    proxies:
      - 🇯🇵 Japan 01 | Media
      - 🇯🇵 Japan 02 | Media
      - 🇯🇵 Japan 03 | Media
      - 🇯🇵 Japan 04 | Media
      - 🇯🇵 Japan 05 | Media
      - 🇯🇵 Japan 06 | Media
  - name: TW
    type: select
    proxies:
      - 🇹🇼 Taiwan 01
      - 🇹🇼 Taiwan 02
      - 🇹🇼 Taiwan 03
      - 🇹🇼 Taiwan 04
      - 🇹🇼 Taiwan 05
      - 🇹🇼 Taiwan 06
      - 🇹🇼 Taiwan 07
      - 🇹🇼 Taiwan 08
  - name: Github
    type: select
    proxies:
      - PROXY
      - Final
  - name: Steam
    type: select
    proxies:
      - PROXY
      - Final
rules:
  - GEOIP,CN,Domestic
  - MATCH,Final
proxy-providers: {}
rule-providers: {}
```

### Clash log

```shell
time="2022-05-09T15:24:16+08:00" level=warning msg="[TCP] dial Final (match Match/) to www.themoviedb.org:443 error: dial tcp4 18.65.159.129:443: i/o timeout"
time="2022-05-09T15:24:16+08:00" level=warning msg="[TCP] dial Final (match Match/) to images-na.ssl-images-amazon.com:443 error: dial tcp4 18.65.184.152:443: i/o timeout"
time="2022-05-09T15:24:21+08:00" level=warning msg="[TCP] dial Final (match Match/) to www.themoviedb.org:443 error: dial tcp4 18.65.159.125:443: i/o timeout"
```

### Description

使用的CFW

感觉可能是core的问题，就报在这里，
遇到这种情况的时候网络确实不太稳定，不过感觉clash的timeout判定更短。
有时候是网络网页能打开的，但是经过clash的时候一定不行，虽然有时候多试几次不经过clash也会打不开

之前在这里开了个问题
https://github.com/Fndroid/clash_for_windows_pkg/issues/2996

很早以前有遇到，不过当时以为是clash不走ipc6的问题（）
由于issue没法保存草稿，我先发出来再关掉，然后试试dev版本

There was an error creating your issue: body is too long (maximum is 65536 characters). 所以我把rule删一下

**Comment by ted423** [comment]
现在试了，切换drv版本也会出问题

**Comment by XiGou** [comment]
这个问题我也遇到过
就是有些网站把clash关掉, 可以正常访问
但是通过clash 的 direct规则命中之后访问, 就会超时

**Comment by aniyyy** [comment]
同样的问题，clash的direct好像有点问题。

**Comment by SplitGemini** [comment]
premium 2022.08.26仍未解决，访问bilivideo.cn会timeout

**Comment by ted423** [comment]
今天确实又遇到了，并且某些站点不能走代理

**Comment by SplitGemini** [comment]
> premium 2022.08.26仍未解决，访问bilivideo.cn会timeout

好像是dns问题

**Comment by ted423** [comment]
> > premium 2022.08.26仍未解决，访问bilivideo.cn会timeout
> 
> 好像是dns问题

我遇到的不是，timeout的log里解析的有IP

**Comment by SplitGemini** [comment]
> 

确实，我遇到好多个国内网站直连timeout了，没办法我暂时用浏览器插件路由一遍再走clash

**Comment by SplitGemini** [comment]
> > > premium 2022.08.26仍未解决，访问bilivideo.cn会timeout
> > 
> > 
> > 好像是dns问题
> 
> 我遇到的不是，timeout的log里解析的有IP

确实，我遇到好多个国内网站直连timeout了，没办法我暂时用浏览器插件路由一遍再走clash

**Comment by wanmyj** [comment]
这个问题我已经workaround了。

我遇到的问题：运行模式 `fake IP`，代理模式 `rule`，规则外路由选择，`direct` ------ 这种模式下，访问外国不被墙的网站，而且走到final rule(或者叫match、规则外路由选择 )里面的direct，则会提示错误 `error: dial tcp4 443: i/o timeout`

解决办法：
1. yaml配置文件里，把运营商的DNS放到fallback DNS组里
2. yaml配置文件里，` fallback-filter` 项目下，把 `geoip: true` 改为 `geoip: false`

可能原因：
对于一个url，fallback 与 nameserver 内的服务器列表同时发起请求，如果不改以上配置，当url对应的IP 符合 GEOIP非CN时，会强制使用fallback列表内的域名服务器返回的IP，然而，这又是一个没有match到任何规则的url，根据规则外路由选择会走direct，相当于用direct方式请求fallback的DNS服务器，返回不出来结果，自然就连不上网页了。

**Comment by SplitGemini** [comment]
> 这个问题我已经workaround了。
> 
> 我遇到的问题：运行模式 `fake IP`，代理模式 `rule`，规则外路由选择，`direct` ------ 这种模式下，访问外国不被墙的网站，而且走到final rule(或者叫match、规则外路由选择 )里面的direct，则会提示错误 `error: dial tcp4 443: i/o timeout`
> 
> 解决办法：
> 
> 1. yaml配置文件里，把运营商的DNS放到fallback DNS组里
> 2. yaml配置文件里，` fallback-filter` 项目下，把 `geoip: true` 改为 `geoip: false`
> 
> 可能原因： 对于一个url，fallback 与 nameserver 内的服务器列表同时发起请求，如果不改以上配置，当url对应的IP 符合 GEOIP非CN时，会强制使用fallback列表内的域名服务器返回的IP，然而，这又是一个没有match到任何规则的url，根据规则外路由选择会走direct，相当于用direct方式请求fallback的DNS服务器，返回不出来结果，自然就连不上网页了。

只需要步骤1就行吧，而且一直fallback dns就有可以国内正常使用的dns，不应该影响国内ip的直连

**Comment by wanmyj** [comment]
> > 这个问题我已经workaround了。
> > 我遇到的问题：运行模式 `fake IP`，代理模式 `rule`，规则外路由选择，`direct` ------ 这种模式下，访问外国不被墙的网站，而且走到final rule(或者叫match、规则外路由选择 )里面的direct，则会提示错误 `error: dial tcp4 443: i/o timeout`
> > 解决办法：
> > 
> > 1. yaml配置文件里，把运营商的DNS放到fallback DNS组里
> > 2. yaml配置文件里，` fallback-filter` 项目下，把 `geoip: true` 改为 `geoip: false`
> > 
> > 可能原因： 对于一个url，fallback 与 nameserver 内的服务器列表同时发起请求，如果不改以上配置，当url对应的IP 符合 GEOIP非CN时，会强制使用fallback列表内的域名服务器返回的IP，然而，这又是一个没有match到任何规则的url，根据规则外路由选择会走direct，相当于用direct方式请求fallback的DNS服务器，返回不出来结果，自然就连不上网页了。
> 
> 只需要步骤1就行吧，而且我的fallback dns一直就有可以国内正常使用的dns，不应该影响国内ip的直连

我遇到的情况是国内IP一直很快，国外非封锁IP才会走入timeout。

Update to original answer：
理论上来说，这两项做一项就可以。
但是，今天发现我昨天说的方法还是有概率出现timeout，我把fallback的其他dns全关掉，只留运营商的DNS，就再也没出过这个问题了。

因为一直没搞清楚clash到底开源闭源，就没研究源码。反正对我就是个工具，解决问题就凑合用了

**Comment by ted423** [comment]
```
dns:
  enable: false
  ipv6: false
  default-nameserver:
    - 223.5.5.5
    - 119.29.29.29
  enhanced-mode: redir-host
  fake-ip-range: 198.18.0.1/16
  use-hosts: true
```
我这边一直是这个配置
