### ISSUE TITLE
[Bug] Windows上开启TUN后没有“拦截”掉DNS请求，依旧会向物理网卡发送DNS请求

### ISSUE THREAD

**Issue by returnL** [Dreamacro/clash#2136]
### Verify steps

- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

Premium 2022.04.17

### What OS are you seeing the problem on?

Windows

### Clash config

```yaml
tun:
  enable: true
  stack: system
  auto-route: true
  dns-hijack:
    - any:53
    - tcp://any:53
interface-name: WLAN
dns:
  enable: true
  ipv6: false
  listen: 127.0.0.1:8853
  enhanced-mode: fake-ip
  default-nameserver:
    - 119.29.29.29
    - 223.5.5.5
    - 1.0.0.1
  nameserver:
    - https://dns.pub/dns-query
    - https://dns.alidns.com/dns-query
  fallback:
    - tls://1.0.0.1
    - https://public.dns.iij.jp/dns-query
    - tls://8.8.4.4
  fallback-filter:
    geoip: false
    ipcidr:
      - 0.0.0.0/32
  fake-ip-filter:
    - "+.lan"
    - "*.localdomain"
    - "*.example"
    - "*.invalid"
    - "*.localhost"
    - "*.test"
    - "*.local"
    - "*.home.arpa"
    - "time.*.com"
    - "time.*.gov"
    - "time.*.edu.cn"
    - "time.*.apple.com"
    - "time1.*.com"
    - "time2.*.com"
    - "time3.*.com"
    - "time4.*.com"
    - "time5.*.com"
    - "time6.*.com"
    - "time7.*.com"
    - ntp.ntsc.ac.cn
    - "ntp.*.com"
    - "ntp1.*.com"
    - "ntp2.*.com"
    - "ntp3.*.com"
    - "ntp4.*.com"
    - "ntp5.*.com"
    - "ntp6.*.com"
    - "ntp7.*.com"
    - "*.time.edu.cn"
    - "*.ntp.org.cn"
    - "+.pool.ntp.org"
    - "time1.cloud.tencent.com"
    - "music.163.com"
    - "*.music.163.com"
    - "*.126.net"
    - "musicapi.taihe.com"
    - "music.taihe.com"
    - "songsearch.kugou.com"
    - "trackercdn.kugou.com"
    - "*.kuwo.cn"
    - "api-jooxtt.sanook.com"
    - "api.joox.com"
    - "joox.com"
    - "y.qq.com"
    - "*.y.qq.com"
    - "streamoc.music.tc.qq.com"
    - "mobileoc.music.tc.qq.com"
    - "isure.stream.qqmusic.qq.com"
    - "dl.stream.qqmusic.qq.com"
    - "aqqmusic.tc.qq.com"
    - "amobile.music.tc.qq.com"
    - "*.xiami.com"
    - "*.music.migu.cn"
    - "music.migu.cn"
    - "*.msftconnecttest.com"
    - "*.msftncsi.com"
    - "msftconnecttest.com"
    - "msftncsi.com"
    - "localhost.ptlogin2.qq.com"
    - "localhost.sec.qq.com"
    - "+.srv.nintendo.net"
    - "+.stun.playstation.net"
    - "xbox.*.microsoft.com"
    - "xnotify.xboxlive.com"
    - "+.battlenet.com.cn"
    - "+.wotgame.cn"
    - "+.wggames.cn"
    - "+.wowsgame.cn"
    - "+.wargaming.net"
    - "proxy.golang.org"
    - "stun.*.*"
    - "stun.*.*.*"
    - "+.stun.*.*"
    - "+.stun.*.*.*"
    - "+.stun.*.*.*.*"
    - "heartbeat.belkin.com"
    - "*.linksys.com"
    - "*.linksyssmartwifi.com"
    - "*.router.asus.com"
    - "mesu.apple.com"
    - "swscan.apple.com"
    - "swquery.apple.com"
    - "swdownload.apple.com"
    - "swcdn.apple.com"
    - "swdist.apple.com"
    - "lens.l.google.com"
    - "stun.l.google.com"
    - "+.nflxvideo.net"
    - "*.square-enix.com"
    - "*.finalfantasyxiv.com"
    - "*.ffxiv.com"
```

### Description

Windows上网卡的DNS设置为了局域网中Adguard Home的地址，然后Clash开启TUN模式，DNS设置如上，nameserver中并没有填写Adguard Home的地址，但是开启TUN模式后，在Adguard Home的日志里面仍然能够看到Windows上的DNS请求。
DNS请求没有只走Clash里设置的DNS，同时还走了物理网卡上的DNS，没有被Clash“拦截”掉。下图是Adguard Home的日志截图

![image](https://user-images.githubusercontent.com/44701395/168458338-5a8809e4-9a59-4e8b-bf1e-ae5ee29875d1.png)

如果在Windows上设置了系统代理，那么走系统代理的网站在Adguard Home的日志里就看不到DNS请求，DNS请求只走了Clash的DNS而没有走物理网卡的DNS。做到了“拦截”。

我在Windows 10和11上都发现了此现象，不确定这算不算Bug，我的理解是开启TUN之后，系统的所有DNS请求应该只走Clash不会再向物理网卡的DNS服务器发送请求。希望开发者能看一下。

**Comment by luwah** [comment]
请问dns-hijack填写198.18.0.2:53的话有没有尝试过？还会不会出现该情况？
如果还是如上的情况，那么看看log-level=debug时输出的DNS相关信息?

**Comment by returnL** [comment]
> 请问dns-hijack填写198.18.0.2:53的话有没有尝试过？还会不会出现该情况？ 如果还是如上的情况，那么看看log-level=debug时输出的DNS相关信息?

试过填`198.18.0.2:53`了，情况依旧。而且看log也没意义呀，Clash的DNS确实生效了，看log看不出什么问题；只是物理网卡的DNS服务器其实可以不收到DNS请求，因为Clash已经处理了DNS。

**Comment by returnL** [comment]
`dns-hijack` 是生效的，我碰到的问题不是`dns-hijack`没有配置好导致clash无法匹配域名规则。
而是我记得之前使用旧版本的Clash Premium，物理网卡上设置的DNS服务器在电脑开启了TUN之后确实是收不到来自电脑的DNS请求的，不知从哪个版本开始，开启了TUN之后，物理网卡仍然会收到DNS请求

**Comment by qist** [comment]
你dns 监听的是 listen: 127.0.0.1:8853 你总要转发到这个端口把。

**Comment by ElemenTP** [comment]
疑似是Windows的Feature  
https://github.com/Dreamacro/clash/issues/1177#issuecomment-758524782

**Comment by returnL** [comment]
> 疑似是Windows的Feature [#1177 (comment)](https://github.com/Dreamacro/clash/issues/1177#issuecomment-758524782)

感谢。在组策略编辑器中，启用`计算机配置->管理模板->网络->DNS客户端->禁用智能多宿主名称解析 ` ，就可以避免这个问题了

**Comment by ElemenTP** [comment]
> > 疑似是Windows的Feature [#1177 (comment)](https://github.com/Dreamacro/clash/issues/1177#issuecomment-758524782)
> 
> 感谢。在组策略编辑器中，启用`计算机配置->管理模板->网络->DNS客户端->禁用智能多宿主名称解析 ` ，就可以避免这个问题了

看了一下该策略的描述，启用该策略禁用智能多宿主名称解析，“则 DNS 客户端将不执行优化。 将首先跨所有网络发出 DNS 查询。如果 DNS 查询失败，则发出 LLMNR 查询；如果 LLMNR 查询失败，则发出 NetBT 查询。”，没有理解错的话，仍然会在所有网卡上发起DNS查询。似乎只有把所有网卡的DNS地址改为198.18.0.2是最稳妥的

**Comment by qist** [comment]
```
dns:
  enable: true
  listen: 0.0.0.0:53
  ipv6: false
  enhanced-mode: redir-host
  fake-ip-range: 198.19.0.1/16
  .........

tun:
  enable: true
  stack: gvisor
  dns-hijack:
    - 198.19.0.2:53
  auto-route: true
  auto-detect-interface: true
```
这样就不会有那么多问题。
