### ISSUE TITLE
[Feature] 当前是否不支持（v2ray 的）socks5+websocket+tls 模式

### ISSUE THREAD

**Issue by ragnaroks** [Dreamacro/clash#2138]
### Verify steps

- [x]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

如下两个代理配置：
```yaml
proxies:
  - name: p1
    type: socks5
    server: 1.1.1.1
    port: 443
    network: ws
    servername: the.domain.tld
    tls: true
    skip-cert-verify: true
    udp: false
    ws-opts:
      path: /v2ray
      headers:
        Host: the.domain.tld
      max-early-data: 0
  - name: p2
    type: socks5
    server: 1.1.1.1
    port: 443
    network: ws
    plugin: v2ray-plugin
    plugin-opts:
      mode:  websocket
      tls: true
      skip-cert-verify: true
      host: the.domain.tld
      path: /v2ray
      mux: false
      headers:
        Host: the.domain.tld
```
任意请求日志均显示：
```plain
time="2022-05-15T23:06:05+08:00" level=warning msg="[TCP] dial p1 (match Match/) to edge.microsoft.com:443 error: SOCKS version error"
time="2022-05-15T23:07:05+08:00" level=warning msg="[TCP] dial p2 (match Match/) to edge.microsoft.com:443 error: SOCKS version error"
```
