### ISSUE TITLE
在域名匹配前是否会因为Process而进行域名查询

### ISSUE THREAD

**Issue by xqXQzzz1** [Dreamacro/clash#2141]
### Verify steps

- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

Version 2022.04.17

### What OS are you seeing the problem on?

Windows

### Clash config

```yaml
dns:
  enable: true
  ipv6: true
  listen: 0.0.0.0:53
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - "*.lan"
    - "*.linksys.com"
    - "*.linksyssmartwifi.com"
    - swscan.apple.com
    - mesu.apple.com
    - "*.msftconnecttest.com"
    - "*.msftncsi.com"
    - time.*.com
    - time.*.gov
    - time.*.edu.cn
    - time.*.apple.com
    - time1.*.com
    - time2.*.com
    - time3.*.com
    - time4.*.com
    - time5.*.com
    - time6.*.com
    - time7.*.com
    - ntp.*.com
    - ntp.*.com
    - ntp1.*.com
    - ntp2.*.com
    - ntp3.*.com
    - ntp4.*.com
    - ntp5.*.com
    - ntp6.*.com
    - ntp7.*.com
    - "*.time.edu.cn"
    - "*.ntp.org.cn"
    - +.pool.ntp.org
    - time1.cloud.tencent.com
    - +.music.163.com
    - "*.126.net"
    - musicapi.taihe.com
    - music.taihe.com
    - songsearch.kugou.com
    - trackercdn.kugou.com
    - "*.kuwo.cn"
    - api-jooxtt.sanook.com
    - api.joox.com
    - joox.com
    - +.y.qq.com
    - +.music.tc.qq.com
    - aqqmusic.tc.qq.com
    - +.stream.qqmusic.qq.com
    - "*.xiami.com"
    - +.music.migu.cn
    - +.srv.nintendo.net
    - +.stun.playstation.net
    - xbox.*.microsoft.com
    - +.xboxlive.com
    - localhost.ptlogin2.qq.com
    - proxy.golang.org
    - stun.*.*
    - stun.*.*.*
  nameserver:
    - dhcp://en0
    - 223.5.5.5
    - 119.29.29.29
    - 114.114.114.114
    - 43.226.158.91:777
  fallback:
    - 8.8.8.8
    - tls://dns.google:853
    - https://i.passcloud.xyz/dns-query
    - https://sm2.doh.pub/dns-query
  fallback-filter:
    geoip: true
    geoip-code: CN
    domain:
      - +.nfmovies.com
```

### Clash log

```shell
22-05-18 18:42:08 info
[TCP] 192.168.1.111:63088 --> lookpic.com:80 match RuleSet(Proxy_Classical) using 🚀 节点选择[F.TW.彰化⇠HiNet:RC32228]
22-05-18 18:42:07 debug
[DNS] lookpic.com --> 104.21.233.187
22-05-18 18:42:07 debug
[Process] find process lookpic.com: netlink message: NLMSG_ERROR
```

### Description

是否会由于存在process-name，导致将lookpic.com类似的域名认为process，从而进行一次DNS解析？
