### ISSUE TITLE
[Feature] Rule Support Logic AND

### ISSUE THREAD

**Issue by zzc-tongji** [Dreamacro/clash#2147]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

For example, I would like to let traffic **[from 192.168.1.0/24] AND [to port 80]** to go through the proxy. What should I do?

### Possible Solution

I believe rule like `AND,(SRC-IP-CIDR,10.10.10.11/32&&DST-PORT,80),PROXY` is necessary.

**Comment by Dreamacro** [comment]
use [script shortcut](https://github.com/Dreamacro/clash/wiki/premium-core-features#script-shortcut) instead

```yaml
script:
  shortcuts:
    xxHTTP: src_ip == '10.10.10.11' and dst_port == 80

rules:
  - SCRIPT,xxHTTP,PROXY
```
