### ISSUE TITLE
[Bug] Socks5 proxy and rules

### ISSUE THREAD

**Issue by cornoctopus** [Dreamacro/clash#2154]
### Verify steps

- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

Clash Premium 2022.05.18 linux amd64 with go1.18.2

### What OS are you seeing the problem on?

Linux

### Clash config

```yaml
socks-port: 7891

# Transparent proxy server port for Linux (TProxy TCP and TProxy UDP)
 tproxy-port: 7893

# Set to true to allow connections to the local-end server from
# other LAN IP addresses
allow-lan: true

# This is only applicable when `allow-lan` is `true`
# '*': bind all IP addresses
# 192.168.122.11: bind a single IPv4 address
# "[aaaa::a8aa:ff:fe09:57d8]": bind a single IPv6 address
bind-address: '*'

# Clash router working mode
# rule: rule-based packet routing
# global: all packets will be forwarded to a single endpoint
# direct: directly forward the packets to the Internet
mode: rule

# Clash by default prints logs to STDOUT
# info / warning / error / debug / silent
log-level: info

# When set to false, resolver won't translate hostnames to IPv6 addresses
ipv6: false

# Outbound interface name
#interface-name: ens33

# fwmark on Linux only
routing-mark: 6666

# Static hosts for DNS server and connection establishment (like /etc/hosts)
#
# Wildcard hostnames are supported (e.g. *.clash.dev, *.foo.*.example.com)
# Non-wildcard domain names have a higher priority than wildcard domain names
# e.g. foo.example.com > *.example.com > .example.com
# P.S. +.foo.com equals to .foo.com and foo.com
hosts:
  # '*.clash.dev': 127.0.0.1
  # '.dev': 127.0.0.1
  # 'alpha.clash.dev': '::1'

profile:
  # Store the `select` results in $HOME/.config/clash/.cache
  # set false If you don't want this behavior
  # when two different configurations have groups with the same name, the selected values are shared
  store-selected: false

  # persistence fakeip
  store-fake-ip: true

# DNS server settings
# This section is optional. When not present, the DNS server will be disabled.
dns:
  enable: true
  listen: 0.0.0.0:53
  # ipv6: false # when the false, response to AAAA questions will be empty

  # These nameservers are used to resolve the DNS nameserver hostnames below.
  # Specify IP addresses only
  default-nameserver:
    - 8.8.8.8
    - 8.8.4.4
  enhanced-mode: fake-ip # or fake-ip
  fake-ip-range: 198.18.0.1/16 # Fake IP addresses pool CIDR
  # use-hosts: true # lookup hosts and return IP record
  
  # Supports UDP, TCP, DoT, DoH. You can specify the port to connect to.
  # All DNS questions are sent directly to the nameserver, without proxies
  # involved. Clash answers the DNS question with the first result gathered.
  nameserver:
    - 8.8.8.8 # default value
    - 8.8.4.4 # default value
    - tls://dns.rubyfish.cn:853 # DNS over TLS
    - https://1.1.1.1/dns-query # DNS over HTTPS
    - dhcp://ens33 # dns from dhcp

proxies:
  # socks5
  - name: "socks"
    type: socks5
    server: 123.123.123.123
    port: 18237
     username: user
     password: pass
    # tls: true
    # skip-cert-verify: true
    # udp: true

proxy-groups:
   # url-test select which proxy will be used by benchmarking speed to a URL.
  - name: "auto"
    type: url-test
    proxies:
      - socks5
    # tolerance: 150
    # lazy: true
    url: 'http://www.gstatic.com/generate_204'
    interval: 300

  # select is used for selecting proxy or proxy group
  # you can use RESTful API to switch proxy is recommended for use in GUI.
  - name: proxy
    type: select
    # disable-udp: true
    proxies:
      - socks5
      
rules:
  - DOMAIN-SUFFIX,google.com,auto
  - DOMAIN-KEYWORD,google,auto
  - DOMAIN,google.com,auto
  - DOMAIN-SUFFIX,etsy.com,auto
  - DOMAIN-KEYWORD,etsy,auto
  - DOMAIN,etsy.com,auto
  - DOMAIN-SUFFIX,ad.com,REJECT
  - SRC-IP-CIDR,192.168.1.201/32,DIRECT
  # optional param "no-resolve" for IP rules (GEOIP, IP-CIDR, IP-CIDR6)
  - IP-CIDR,127.0.0.0/8,DIRECT
  - GEOIP,CN,DIRECT
  - DST-PORT,80,DIRECT
  - SRC-PORT,7777,DIRECT
  - RULE-SET,apple,REJECT # Premium only

  - MATCH,auto
```

### Clash log

```shell
INFO[0000] Mixed(http+socks) proxy listening at: 127.0.0.1:7890 
INFO[0001] [TCP] 127.0.0.1:51340 --> www.etsy.com:443 doesn't match any rule using DIRECT 
INFO[0001] [TCP] 127.0.0.1:51342 --> bat.bing.com:443 doesn't match any rule using DIRECT 
INFO[0001] [TCP] 127.0.0.1:51344 --> www.googletagmanager.com:443 doesn't match any rule using DIRECT 
INFO[0002] [TCP] 127.0.0.1:51346 --> 8666735.fls.doubleclick.net:443 doesn't match any rule using DIRECT 
INFO[0002] [TCP] 127.0.0.1:51348 --> 9910951.fls.doubleclick.net:443 doesn't match any rule using DIRECT 
INFO[0002] [TCP] 127.0.0.1:51350 --> www.dwin1.com:443 doesn't match any rule using DIRECT 
INFO[0002] [TCP] 127.0.0.1:51360 --> 8666735.fls.doubleclick.net:443 doesn't match any rule using DIRECT 
INFO[0002] [TCP] 127.0.0.1:51356 --> web.btncdn.com:443 doesn't match any rule using DIRECT 
INFO[0002] [TCP] 127.0.0.1:51354 --> s.pinimg.com:443 doesn't match any rule using DIRECT 
INFO[0002] [TCP] 127.0.0.1:51362 --> ct.pinterest.com:443 doesn't match any rule using DIRECT 
INFO[0002] [TCP] 127.0.0.1:51358 --> pt.ispot.tv:443 doesn't match any rule using DIRECT 
INFO[0002] [TCP] 127.0.0.1:51364 --> mozilla.cloudflare-dns.com:443 doesn't match any rule using DIRECT 
INFO[0002] [TCP] 127.0.0.1:51372 --> www.google-analytics.com:443 doesn't match any rule using DIRECT 
INFO[0003] [TCP] 127.0.0.1:51374 --> resources.xg4ken.com:443 doesn't match any rule using DIRECT 
INFO[0003] [TCP] 127.0.0.1:51376 --> d.agkn.com:443 doesn't match any rule using DIRECT
```

### Description

Hi. Thanks for your great work. I need some help with my config, I read gitbook but seems like I don't have enough of knowledge. I don't understand why connection go without proxy? I write simple rule, add my socks5 proxy but without luck. I test on etsy.com becayse they banned russian ips. Mozilla firefox and FoxyProxy (settings are 127.0.0.1:7890) Thanks.
