### ISSUE TITLE
[Bug] premium版本每分钟请求一次 http://127.0.0.1/alive 问题

### ISSUE THREAD

**Issue by xx10n31y** [Dreamacro/clash#2156]
### Verify steps

- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

Clash 2022.04.17 linux amd64 with go1.18.1 Sun Apr 17 13:53:05 UTC 2022

### What OS are you seeing the problem on?

Linux

### Clash config

```yaml
mixed-port: 7890
socks-port: 7891
allow-lan: true
bind-address: '*'
mode: rule
log-level: info
ipv6: false
external-controller: 192.168.1.110:9090
#secret: ""
#external-folder: ''
profile:
  tracing: false
dns:
  enable: true
  ipv6: false
  #listen: 0.0.0.0:53
  default-nameserver:
    - 114.114.115.115
    - 8.8.4.4
  enhanced-mode: redir-host # fake-ip
  fake-ip-range: 192.18.0.1/16
  use-hosts: true
  fake-ip-filter:
    - '*.lan'
    - ip.sb
    - '*.qq.com'
    - loki
  nameserver:
    - 202.96.128.86
    - 202.96.128.166
    - 202.96.134.33
  fallback:
    - 8.8.4.4
    - tls://dns.google
    - tls://1.1.1.1
  fallback-filter:
    geoip: true
    ipcidr:
      - 240.0.0.0/4
```

### Description

使用premium版本每分钟请求一次http://localhost/alive是因为什么, 出于哪方面的需要

![image](https://user-images.githubusercontent.com/57975788/170833732-a8c46be0-ed28-4509-949e-2fc6508a9de1.png)
