### ISSUE TITLE
[Bug] 系统代理 路由器无法登录

### ISSUE THREAD

**Issue by quehub** [Dreamacro/clash#2158]
### Verify steps

- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

v1.10.6

### What OS are you seeing the problem on?

macOS

### Clash config

```yaml
mixed-port: 8633
allow-lan: false
bind-address: "*"
ipv6: true
# rule / global/ direct (默认为 Rule 模式)
mode: rule
# info / warning / error / debug / silent
log-level: info
external-controller: 0.0.0.0:9090
experimental:
  ignore-resolve-fail: true # ignore dns resolve fail, default value is true
hosts:
  "router.asus.com": 192.168.7.1

profile:
  store-selected: true
  tracing: false
  store-fake-ip: false

dns:
  enable: true
  ipv6: true
  default-nameserver:
    - 1.0.0.1
  enhanced-mode: fake-ip #redir-host or fake-ip
  fake-ip-range: 198.18.0.1/16 # Fake IP addresses pool CIDR
  use-hosts: false # lookup hosts and return IP record
  nameserver:
    - tls://x.passcloud.xyz:853
    - tls://b.iqiq.io:853
    - tls://1.0.0.1:853
    - tls://dns.google:853
  fake-ip-filter:
    - "*.lan"
    - "router.asus.com"

tun:
  enable: true
  stack: gvisor # gvisor or system
  macOS-auto-route: true
  macOS-auto-detect-interface: true
  dns-hijack:
    - any:53
    - tcp://any:53
```

### Clash log

```shell
2022/05/30, 12:14:43.638  [info] applicationWillFinishLaunching
2022/05/30, 12:14:43.668  [info] applicationDidFinishLaunching
2022/05/30, 12:14:43.669  [info] Appversion: 1.93.1.1 1.93.1.1
2022/05/30, 12:14:43.720  [info] postFinishLaunching
2022/05/30, 12:14:43.796  [debug] checkInstall
2022/05/30, 12:14:43.799  [info] initClashCore
2022/05/30, 12:14:43.800  [info] initClashCore finish
2022/05/30, 12:14:43.807  [info] Trying start proxy
2022/05/30, 12:14:43.819  [info] Start proxy done
2022/05/30, 12:14:43.823  [info] autoUpdateEnable did not enable,autoUpateTimer invalidated.
2022/05/30, 12:14:43.974  [debug] helper version 1.9 require version 1.9
2022/05/30, 12:14:43.974  [info] check helper using time: 0.17581796646118164
2022/05/30, 12:14:44.000  [error] enableProxy fail: 0 0
2022/05/30, 12:14:44.752  [info] port config updated,new: 8633,8633
2022/05/30, 12:14:44.752  [debug] enableProxy
2022/05/30, 12:14:44.757  [info] Startup: enableStatusAtLastExit = false, settings = false
2022/05/30, 12:14:44.758  [debug] Auto selecting GLOBAL PROXY
2022/05/30, 12:14:44.758  [debug] Auto selecting Google BWG-TJ
2022/05/30, 12:14:44.758  [debug] Auto selecting FINAL PROXY
2022/05/30, 12:14:44.758  [debug] Auto selecting PROXY BWG-TJ
2022/05/30, 12:14:44.758  [debug] Auto selecting HOME DIRECT
2022/05/30, 12:14:44.762  [debug] trafficWebSocket did Connect
2022/05/30, 12:14:44.763  [debug] loggingWebSocket did Connect
2022/05/30, 12:14:48.994  [info] start crash logger
2022/05/30, 12:14:51.452  [info] [TCP] 127.0.0.1:62858 --> 192.168.7.1:80 match IPCIDR(192.168.7.0/24) using HOME[DIRECT]
2022/05/30, 12:14:51.738  [info] [TCP] 127.0.0.1:62860 --> 192.168.7.1:80 match IPCIDR(192.168.7.0/24) using HOME[DIRECT]
2022/05/30, 12:14:51.902  [info] [TCP] 127.0.0.1:62862 --> 192.168.7.1:80 match IPCIDR(192.168.7.0/24) using HOME[DIRECT]
2022/05/30, 12:14:51.903  [info] [TCP] 127.0.0.1:62864 --> 192.168.7.1:80 match IPCIDR(192.168.7.0/24) using HOME[DIRECT]
```

### Description

环境
```bash
华硕路由器 RT-AC1900P 3.0.0.4.386_48262-g5071673 
clash image: dreamacro/clash-premium, clashx pro 1.93.1.1
v2ray 5.0.6
chromium Version 101.0.4951.64 (Official Build, ungoogled-chromium) (x86_64)
Safari Version 15.5 (17613.2.7.1.8)
fireFix 91.9.1esr (64-bit)
mac os 12.4 (21F79)
```
设置为系统代理到clash-premium或clashx，使用chromium和Safari浏览器请求
路由器IP会跳转到/Main_Login.asp,/js/https_redirect/https_redirect.js，js/jquery.js 浏览器一直转圈
Inspect 网络中 上面三个请求的response都是空的。 
```bash
# General
Request URL: http://192.168.7.1/Main_Login.asp
Request Method: GET
Status Code: 200 OK
Remote Address: 127.0.0.1:8633
Referrer Policy: strict-origin-when-cross-origin
# Response Headers
Cache-Control: no-cache, no-store, must-revalidate
Connection: keep-alive
Content-Type: text/html
Date: Mon, 30 May 2022 04:21:02 GMT
Expires: 0
Keep-Alive: timeout=4
Pragma: no-cache
Proxy-Connection: keep-alive
Server: httpd/2.0
X-Frame-Options: SAMEORIGIN
X-Xss-Protection: 1; mode=block
# Request Headers
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
Accept-Encoding: gzip, deflate
Accept-Language: en-US,en;q=0.9
Cookie: asus_token= clickedItem_tab=0
Host: 192.168.7.1
Proxy-Connection: keep-alive
Referer: http://192.168.7.1/
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.64 Safari/537.36
```

Firefox却是正常的，可以正常登录
clash x pro 只开增强模式 Chromium 和 Safari 都可以正常登录
本地搭建v2ray做测试，依然使用系统代理Chromium 和 Safari , 也可以正常登录
v2ray配置如下

```yaml
log:
  loglevel: error
inbounds:
  - listen: 127.0.0.1
    port: 1080
    protocol: socks
    settings:
      auth: noauth
      udp: false
    sniffing:
      destOverride:
        - http
        - tls
      enabled: true
    tag: socks-in
  - listen: 127.0.0.1
    port: 1087
    protocol: http
    sniffing:
      destOverride:
        - http
        - tls
      enabled: true
    tag: http-in
outbounds:
  - protocol: freedom
    settings: {}
    tag: direct
  - protocol: blackhole
    settings: {}
    tag: reject
routing:
  domainStrategy: IPIfNonMatch
  rules:
    - inboundTag:
        - socks-in
        - http-in
      outboundTag: direct
      type: field
    - ip:
        - geoip:cn
        - geoip:private
      outboundTag: direct
      type: field
    - domain:
        - geosite:geolocation-!cn
        - nintendo.net
        - youtube.com
        - twitter.com
      outboundTag: proxy
      type: field
```
日志内容
```bash
V2Ray 5.0.6 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.18.1 darwin/amd64)
A unified platform for anti-censorship.
2022/05/30 11:26:01 127.0.0.1:58223 accepted http://192.168.7.1/ [direct]
2022/05/30 11:26:02 127.0.0.1:58225 accepted http://192.168.7.1/Main_Login.asp [direct]
2022/05/30 11:26:02 127.0.0.1:58227 accepted http://192.168.7.1/js/jquery.js [direct]
2022/05/30 11:26:02 127.0.0.1:58229 accepted http://192.168.7.1/js/https_redirect/https_redirect.js [direct]
2022/05/30 11:26:03 127.0.0.1:58231 accepted http://192.168.7.1/images/New_ui/login_bg.png [direct]
2022/05/30 11:26:03 127.0.0.1:58233 accepted http://192.168.7.1/images/New_ui/icon_titleName.png [direct]
2022/05/30 11:26:03 127.0.0.1:58235 accepted http://router.asus.com/chdom.json?hostname=192.168.7.1 [direct]
2022/05/30 11:26:09 127.0.0.1:58236 accepted http://192.168.7.1/images/favicon.png [direct]
```

如需要其他数据我再补充
