### ISSUE TITLE
Error: x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by CharlotteFallices** [Dreamacro/clash#2167]
### Verify steps

- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

latest

### What OS are you seeing the problem on?

macOS

### Clash config

```yaml
socks-port: 7891
mode: rule
log-level: debug
proxies:
  -
    name: "Proxy"
    type: vmess
    server: "$SERVERNAME"
    port: 443
    uuid: $UUID
    alterId: 0
    cipher: auto
    network: ws
    ws-path: "$WSPATH"
    tls: true
proxy-groups:
  -
    name: Proxies
    type: select
    proxies:
      - "Proxy"
rules:
  - GEOIP,LAN,DIRECT
  - MATCH,Proxies
```

### Description

The log shows:
```shell
[TCP] dial Proxies (match Match/) to $HOSTNAME:443 error: dial $SERVERNAME:443 error: x509: certificate signed by unknown authority
```
The certificate is signed by Cloudflare and be verified in Safari and can be queried in the macOS Keychain.
