### ISSUE TITLE
[Bug] 我开启clashX后钉钉-与人的聊天窗口-文件-在线编辑功能无法使用，一直转圈

### ISSUE THREAD

**Issue by keepkay** [Dreamacro/clash#2173]
### Verify steps

- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

clashX

### What OS are you seeing the problem on?

macOS

### Clash config

```yaml
基础配置如下
mixed-port: 7892
allow-lan: true
bind-address: '*'
mode: rule
log-level: info
external-controller: '127.0.0.1:9092'
dns:
    enable: false
    ipv6: false
    default-nameserver: [223.5.5.5, 119.29.29.29]
    enhanced-mode: redir-host
    fake-ip-range: 198.18.0.1/16
    use-hosts: true

clashX版本：264d5c
macoS：12.2.1 
钉钉版本：6.5.12
```

### Description

现象描述：
开启clashX后钉钉-文件-在线编辑excel时不显示下方sheet + 一直转圈
关闭clashX后刷新立即正常，观察了日志及代理，钉钉的这个在线编辑模块一直匹配走的直链，但是开着clashX就是一直转圈打不开。。
尝试：将clashX设置为直连模式也是一直转圈无法访问
