### ISSUE TITLE
FATA[0000] Parse config error: external-ui: /root/clash/ui not exist [Bug] 

### ISSUE THREAD

**Issue by 2715481617** [Dreamacro/clash#2176]
### Verify steps

- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

clash-linux-amd64-v1.10.6.gz

### What OS are you seeing the problem on?

Linux

### Clash config

```yaml
mixed-port: 7890
redir-port: 7892
tproxy-port: 7893
allow-lan: true
bind-address: '*'
mode: rule
log-level: info
ipv6: false
geodata-mode: true
tcp-concurrent: true
external-controller: 0.0.0.0:9090
external-ui: ui
# interface-name: en0
routing-mark: 6666
iptables:
  enable: true
  # inbound-interface: en0
hosts:
  "localhost": 127.0.0.1
sniffer:
  enable: true
  sniffing:
    - tls
    - http
  skip-domain:
    - 'Mijia Cloud'
    - '+.apple.com'
  force-domain:
    - '+'
  port-whitelist:
    - 80
    - 443
dns:
  enable: true
  ipv6: false
  enhanced-mode: redir-host
  listen: 0.0.0.0:1053
  use-hosts: true
  nameserver:
    # - dhcp://en0
    - 223.5.5.5
    - 119.29.29.29

proxies:

proxy-groups:
  - { name: "PROXY", type: select, proxies: ["香港-负载均衡"], use: ["auVPN"] }
  - { name: "香港-负载均衡", type: load-balance, use: ["auVPN"], filter: HK, url: https://www.gstatic.com/generate_204, interval: 300 }

proxy-providers:
  auVPN:
    type: http
    url: https://api.inforun.work/v1/service/10066269?hmac=FBD56ED184F647A5F010AA84DBF11BD48091D540AE65877BDB66442C942382CE&lang=en&templateId=3111
    interval: 300
    path: ./proxy-providers/auVPN.yaml
    health-check: { enable: true, interval: 300, url: https://gstatic.com/generate_204 }

rules:
  - DST-PORT,123/136/137-139/2195-2197/5223/5228-5230,DIRECT
  - DOMAIN,clash.razord.top,DIRECT
  - DOMAIN,yacd.haishan.me,DIRECT
  - DOMAIN,api.inforun.work,DIRECT
  - DOMAIN,dy.chaitech.co,DIRECT
  - DOMAIN,repo.t5.work,DIRECT
  - DOMAIN-SUFFIX,splashtop.com,DIRECT
  - GEOSITE,google@cn,DIRECT
  - GEOSITE,apple@cn,DIRECT
  - GEOSITE,icloud@cn,DIRECT
  - GEOSITE,microsoft@cn,DIRECT
  - GEOSITE,category-scholar-cn,DIRECT
  - GEOSITE,category-scholar-!cn,PROXY
  - GEOSITE,geolocation-cn,DIRECT
  - GEOSITE,geolocation-!cn,PROXY
  - GEOIP,private,DIRECT,no-resolve
  - GEOIP,telegram,PROXY,no-resolve
  - GEOIP,cn,DIRECT
  - MATCH,PROXY
```

### Description

Prompt this ：FATA[0000] Parse config error: external-ui: /root/clash/ui not exist      after execution ./clash -d
