### ISSUE TITLE
[Bug] 间歇性出现连接已重置

### ISSUE THREAD

**Issue by fredericky123** [Dreamacro/clash#2179]
### Verify steps

- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

1.10.6

### Clash config

```yaml
dns:
  enable: true # set true to enable dns (default is false)
  ipv6: true # default is false
  listen: 127.0.0.1:53
  default-nameserver: # resolve dns nameserver host, should fill pure IP
     - 223.5.5.5
     - 119.29.29.29
     - 114.114.114.114
     # - 8.8.8.8
     # - 8.8.4.4
     # - 1.2.4.8

  enhanced-mode: fake-ip #  # or fake-ip /redir-host
  fake-ip-range: 198.18.0.1/16 # if you don't know what it is, don't change it
  fake-ip-filter: # fake ip white domain list
     - '*.lan'
     - localhost.ptlogin2.qq.com
  nameserver:
     - 127.0.0.1
     # - 223.5.5.5
     # - 119.29.29.29
     # - 114.114.114.114
     # - tls://dns.rubyfish.cn:853 # dns over tls
     # - https://1.1.1.1/dns-query # dns over https
     # - dhcp://en0 # dns from dhcp
  fallback: # concurrent request with nameserver, fallback used when GEOIP country isn't CN
     - 1.1.1.1
     # - 1.0.0.1
     # - 'tls://1dot1dot1dot1.cloudflare-dns.com'
     # - 8.8.8.8
     # - 8.8.4.4
     # - 1.2.4.8
    # - tcp://1.1.1.1
```

### Description

基本锁定是dns的问题，好奇怪，不断尝试更换dns也没解决
本地安装了adguard用于接管dns查询，即使不接管也会频繁出现此错误

**Comment by CharlotteFallices** [comment]
Trying to configure DNS manually instead of using AdGuard's one-click service might be helpful:
```yaml
dns:
  enable: true
  ipv6: true
  listen: '127.0.0.1:53'
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  nameserver:
    - 94.140.14.15
    - 94.140.15.16
  fallback:
    - 'tls://dns-family.adguard.com'
    - 'https://dns-family.adguard.com/dns-query'
```
