### ISSUE TITLE
[Bug] DNS lookup timeout while fetching proxy provider configuration at startup

### ISSUE THREAD

**Issue by lingo9** [Dreamacro/clash#2182]
### Verify steps

- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

Clash 2022.05.18 linux amd64 with go1.18.2 Wed May 18 10:49:41 UTC 2022

### What OS are you seeing the problem on?

Linux

### Clash config

```yaml
proxy-groups:
  - name: auto
    type: select
    use:
      - provider1

proxy-providers:
  provider1:
    type: http
    url: "https://baidu.com/"
    interval: 3600
    path: ./provider1.yaml

rules:
  - MATCH, auto
```

### Clash log

```shell
INFO[0000] Start initial provider provider1
ERRO[0005] initial proxy provider provider1 error: Get "https://baidu.com/": lookup baidu.com: i/o timeout
configuration file /root/.config/clash/config.yaml test failed
```

### Description

I've tested with [dreamacro/clash-premium](https://hub.docker.com/r/dreamacro/clash-premium/tags) and my own docker image built from:

```
FROM alpine:latest
RUN apk add --no-cache ca-certificates tzdata
COPY /clash /
CMD ["/bin/sh"]
```

`curl https://baidu.com` works fine.
