### ISSUE TITLE
[Bug] 在安卓上关闭wifi面板会报错cpu使用率暴涨

### ISSUE THREAD

**Issue by lq-259** [Dreamacro/clash#2184]
### Verify steps

- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

clash-linux-armv8-v1.10.6

### What OS are you seeing the problem on?

Linux

### Clash config

```yaml
mixed-port: 7890
tproxy-port: 7891
allow-lan: true
geodata-mode: true
unified-delay: true
mode: rule
log-level: info
ipv6: true
profile:
  store-fake-ip: false
external-controller: 0.0.0.0:9090
external-ui: yacd

#tun设置
tun:
  enable: false
  stack: system
  dns-hijack:
    - '0.0.0.0:53'
  auto-route: 
# 技术原因，enable必须在tun:的下一行

dns:
  enable: true
  listen: 0.0.0.0:1053
  ipv6: false
  default-nameserver:
    - 8.8.8.8
    - 223.5.5.5
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - localhost.ptlogin2.qq.com
  fallback-filter:
    geoip: true
    geoip-code: CN
  nameserver:
    - https://h.iqiq.io:777/dns-query
    - https://dns.alidns.com/dns-query
    - https://doh.pub/dns-query
  fallback:
    - https://h.iqiq.io:777/dns-query
    - https://doh.opendns.com/dns-query
    - https://dns.adguard.com/dns-query
    - https://dns.google/dns-query
proxies:
proxy-providers:
proxy-groups:
rules:
  - GEOIP,CN,国内,no-resolve
  - MATCH,代理
```

### Clash log

```shell
time="2022-06-15T07:17:11Z" level=debug msg="[Process] 124.71.213.192 from process /system/bin/app_process32"
time="2022-06-15T07:17:11Z" level=info msg="[UDP] 10.2.199.179:45847 --> 124.71.213.192:3478 match GeoIP(CN) using 国内[DIRECT]"
time="2022-06-15T07:17:18Z" level=debug msg="[Process] 139.159.180.193 from process /system/bin/app_process32"
time="2022-06-15T07:17:18Z" level=info msg="[UDP] 10.2.199.179:40649 --> 139.159.180.193:3478 match GeoIP(CN) using 国内[DIRECT]"
time="2022-06-15T07:17:26Z" level=debug msg="[Process] 124.71.213.192 from process /system/bin/app_process32"
time="2022-06-15T07:17:26Z" level=info msg="[UDP] 10.2.199.179:42679 --> 124.71.213.192:3478 match GeoIP(CN) using 国内[DIRECT]"
time="2022-06-15T07:17:30Z" level=error msg="External controller serve error: accept tcp 127.0.0.1:9090: accept: invalid argument"
time="2022-06-15T07:17:30Z" level=debug msg="[Process] 139.159.180.193 from process /system/bin/app_process32"
time="2022-06-15T07:17:30Z" level=info msg="[UDP] 10.2.199.179:42679 --> 139.159.180.193:3478 match GeoIP(CN) using 国内[DIRECT]"
```

### Description

在miui上使用clash for magisk发现这个问题，在单独启动clash内核时关闭wifi也会出现这个问题可以排除是clash for magisk的问题，不确定是否是miui或clash的问题
