### ISSUE TITLE
我的clash在开启tun 与 热点共享的情况下，电脑无法继续上网，共享的热点也无法上网

### ISSUE THREAD

**Issue by hel0112** [Dreamacro/clash#2185]
### Verify steps

- [ ]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [ ]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

v0.19.21

### What OS are you seeing the problem on?

Windows

### Clash config

```yaml
mixed-port: 7890
allow-lan: false
external-controller: 127.0.0.1:1285
secret: 9c3232f8-9ba7-4510-9d4c-9b9dc475a8f5
```

### Description

我的clash在开启tun 与 热点共享的情况下，电脑无法继续上网，共享的热点也无法上网
