### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by lambdaplus** [Dreamacro/clash#2188]
### Verify steps

- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

2022.06.19 Premium

### What OS are you seeing the problem on?

Linux

### Clash config

```yaml
mixd-port: 7890
redir-port: 7892
tproxy-port: 7893
allow-lan: true
mode: rule
log-level: warning
external-controller: :9091
external-ui: ui
secret: '' 

profile:
  store-selected: true
  store-fake-ip: true

interface-name: enp3s0
auto-redir:
  enable: true
  auto-route: true

tun:
  enable: true
  stack: system # gvisor
  auto-route: true
  dns-hijack:
    - any:53
    
# interface-name: enp3s0
# routing-mark: 7777
# ebpf:
#   redirect-to-tun:
#     - enp3s0

dns:
  enable: true
  enhanced-mode: fake-ip # redir-host
  nameserver:
    # - 211.138.24.66
    # - 114.114.114.114
    - https://doh.pub/dns-query
    - tls://223.5.5.5:853
  fallback:
    - https://doh.sb/dns-query
    - https://1.1.1.1/dns-query
  fallback-filter:
    geoip: false
    ipcidr:
      - 0.0.0.0/32

......

rules:
  # 白名单模式
  - SCRIPT,VideoUdp,REJECT
  - RULE-SET,applications,DIRECT
  - DOMAIN,clash.razord.top,DIRECT
  - DOMAIN,yacd.haishan.me,DIRECT
  - DOMAIN,services.googleapis.cn,PROXY
  - DOMAIN-SUFFIX,github.com,PROXY
  - RULE-SET,private,DIRECT
  - RULE-SET,reject,REJECT
  - RULE-SET,hijacking,REJECT
  - RULE-SET,StreamingSE,StreamingSE
  - RULE-SET,Streaming,Streaming
  - RULE-SET,icloud,DIRECT
  - RULE-SET,apple,DIRECT
  - RULE-SET,google,PROXY
  - RULE-SET,proxy,PROXY
  - RULE-SET,direct,DIRECT
  - RULE-SET,lancidr,DIRECT
  - RULE-SET,cncidr,DIRECT
  - RULE-SET,telegramcidr,PROXY
  - GEOIP,LAN,DIRECT
  - GEOIP,CN,DIRECT
  - MATCH,PROXY
```

### Description

1、旁路由模式，根据指定设备的mac下发网关和DNS。网关为Ubuntu的ip，DNS为运营商DNS
2 、auto-redir模式下，github.com打不开，Google和Youtube都没问题。
3、Tun模式下，GitHub google YouTube 可以打开
4、以上配置文件除了auto-redir和Tun的eBPF外，其他均相同
5、PC和Android设备都是这种情况
