### ISSUE TITLE
[Bug] 树莓派无法运行clash，系统无法sudo

### ISSUE THREAD

**Issue by Dream-build** [Dreamacro/clash#2194]
### Verify steps

- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

clash-linux-armv7-v1.11.0

### Clash config

```yaml
port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
  - {name: 🇺🇸 Eva - US - GIA CN2 - V2ray, server: eva.marythunt.xyz, port: 33243, type: vmess, uuid: d022f57c-484d-4a17-b405-967d7497efdb, alterId: 0, cipher: auto, tls: false, skip-cert-verify: false, network: ws, ws-opts: {path: /, headers: {Host: eva.marythunt.xyz}}, udp: true}
  - {name: 🇺🇸 Eva - US - Trojan, server: eva.marythunt.xyz, port: 443, type: trojan, password: !<str> 372815193, skip-cert-verify: false, udp: true}
  - {name: 🇰🇷 Cindy - KR - CN2 - V2ray, server: cindy.marythunt.xyz, port: 23333, type: vmess, uuid: a8fb075f-8b18-42e5-9f72-c2f91fb20e2d, alterId: 0, cipher: auto, tls: false, skip-cert-verify: false, network: ws, ws-opts: {path: /, headers: {Host: cindy.marythunt.xyz}}, udp: true}
  - {name: 🇰🇷 Cindy - KR - Trojan, server: cindy.marythunt.xyz, port: 443, type: trojan, password: !<str> 372815193, skip-cert-verify: false, udp: true}
  - {name: 🇯🇵 Tulip - CN2 - JP, server: tulip.marythunt.xyz, port: 42195, type: vmess, uuid: ad86c5ed-591a-481e-aa51-27dd4bd31410, alterId: 0, cipher: auto, tls: false, skip-cert-verify: false, network: ws, ws-opts: {path: /, headers: {Host: tulip.marythunt.xyz}}, udp: true}
  - {name: 🇯🇵 Mokuba - JP - Trojan, server: mokuba.marythunt.xyz, port: 443, type: trojan, password: !<str> 372815193, skip-cert-verify: false, udp: true}
  - {name: 🇩🇪 Mosaic - DE - V2ray, server: mosaic.marythunt.xyz, port: 38635, type: vmess, uuid: c194da53-7beb-47aa-a2f8-1e98d64cea2c, alterId: 0, cipher: auto, tls: false, skip-cert-verify: false, network: ws, ws-opts: {path: /, headers: {Host: mosaic.marythunt.xyz}}, udp: true}
  - {name: 🇩🇪 Mosaic - DE - Trojan, server: mosaic.marythunt.xyz, port: 443, type: trojan, password: !<str> 372815193, skip-cert-verify: false, udp: true}
  - {name: 🇷🇺 Sara - RU - V2ray, server: sara.marythunt.xyz, port: 46375, type: vmess, uuid: d8ebfd85-f0f9-4971-99e2-fd9d1fb48a6c, alterId: 0, cipher: auto, tls: false, skip-cert-verify: false, network: ws, ws-opts: {path: /, headers: {Host: sara.marythunt.xyz}}, udp: true}
  - {name: 🇷🇺 Sara - RU - Trojan, server: sara.marythunt.xyz, port: 443, type: trojan, password: !<str> 372815193, skip-cert-verify: false, udp: true}
  - {name: 🇺🇸 Zero - US - Trojan, server: zero.marythunt.xyz, port: 443, type: trojan, password: !<str> 372815193, skip-cert-verify: false, udp: true}
  - {name: 🇺🇸 Polaris - US - V2ray, server: polaris.marythunt.xyz, port: 33401, type: vmess, uuid: a9db5820-ec66-4428-9e16-2a604db50c08, alterId: 0, cipher: auto, tls: false, skip-cert-verify: false, network: ws, ws-opts: {path: /, headers: {Host: polaris.marythunt.xyz}}, udp: true}
```

### Clash log

```shell
暂无
```

### Description

树莓派上安装clash，进行sudo clash后没有反应，如图：
![N8E6Q2CGXC%K5E@HY$DQ0J0](https://user-images.githubusercontent.com/65228306/175771148-7ae44618-629e-4ed1-a25e-8e21e3f8b714.jpg)
但是解压过后的clash文件已经放在该文件夹了，如图：
![7Q2MF`R0$ICDC~{4Z((OP33](https://user-images.githubusercontent.com/65228306/175771171-c65ab535-216c-4533-9f8b-4a111988e991.jpg)
树莓派的config及其他配置已经按照这个教程完成：https://kevinxli.medium.com/set-up-clash-client-on-your-raspberry-pi-4-54e77f7f7fe4
求救XD
