### ISSUE TITLE
[Bug] providers 参数 interval 上限

### ISSUE THREAD

**Issue by kayanouriko** [Dreamacro/clash#2195]
### Verify steps

- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

2020.08.16 Premium (58595)

### What OS are you seeing the problem on?

macOS, Windows

### Clash config

```yaml
rule-providers:
    reject:
        type: http
        behavior: domain
        url: 'url'
        path: ./url.yaml
        interval: 86400
```

### Description

proxy-providers 和 rule-providers 的 interval 参数是否存在上限问题, 超过一定数值就会失效?
我自己测试 interval 设置为 86400 无法生效, providers 将不在更新.
我认为这两个 providers 的外部维护 url 更新周期一般来说也不会短于 24 小时, 是否可以适当延长这个参数的时间上限, 以避免过多不必要的更新请求?
