### ISSUE TITLE
[Bug] 判断dns是否生效

### ISSUE THREAD

**Issue by Wrandz** [Dreamacro/clash#2201]
### Verify steps

- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

2022.06.19 Premium

### What OS are you seeing the problem on?

Windows

### Clash config

```yaml
dns:
  enable: false
  listen: 0.0.0.0:53
  nameserver-policy:
    'www.bing.com': '223.5.5.5'
```

### Description

本地运营商的dns对 bing.com 域名进行了污染，无法正常访问，通过修改电脑dns测试，发现阿里云223.5.5.5可以正常解析 bing.com 。因此想要针对该域名单独设置一个dns。我只想对该域名进行单独的dns设置，对其他的域名，都按照默认的dns。
如上所示，能否在不配置nameserver的情况下，只配置nameserver-policy字段来实现这一目的？
由于clash目前无法根据log文件判断使用了哪一个dns，因此特来询问，不胜感激。
注意我没有开tun模式，就是普通的使用。

**Comment by Wrandz** [comment]
另外还有一事不解的是：dns的配置必须要enhanced-mode吗？特别不理解的是，如果不是必须的话，redir-host模式岂不是有无配置都可以。

**Comment by Dreamacro** [comment]
dns 必须要 enable

> dns 的配置必须要 enhanced-mode 吗

不是

> redir-host 模式岂不是有无配置都可以。

redir-host 无论如何都不建议使用

**Comment by Wrandz** [comment]
谢谢 @Dreamacro 。运用浅薄的网络知识，测试了一下发现如下代码可以正常使用
```
dns:
  enable: true
  listen: 0.0.0.0:53
  nameserver:
    - 192.168.1.1
  nameserver-policy:
    'www.bing.com': '223.5.5.5'
```

一开始以为在不配置nameserver的情况下，会默认走dhcp的dns，只针对例外的"www.bing.com"走指定的dns查询。发现cfw有如下提示：
![Snipaste_2022-07-04_11-04-32](https://user-images.githubusercontent.com/70056470/177082826-a30cbe6d-9327-431c-a4df-e02594f53136.png)

在nameserver字段配置了
`- dhcp://en0`
之后提示找不到这个网卡，发现Windows上网卡似乎不叫这个名字，干脆用了路由器的ip。
