### ISSUE TITLE
既然 fake-ip 或 redir-host 是为了解决 clash 只能 "看不到" 域名的问题，那么 dns 无污染的情况下是否可以只用 ip 分流？

### ISSUE THREAD

**Issue by m2acgi** [Dreamacro/clash#2203]
### Verify steps

- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

v1.11.0

### What OS are you seeing the problem on?

Linux

### Clash config

```yaml
mixed-port: 1080

allow-lan: false
bind-address: '*'

mode: rule

log-level: debug

ipv6: false

proxies:
  - name: "ss-1"
    type: ss
    server: x.x.x.x
    port: 1234
    cipher: aes-256-gcm
    password: "password"
    udp: true

  - name: "ss-2"
    type: ss
    server: y.y.y.y
    port: 1234
    cipher: aes-256-gcm
    password: "password"
    udp: true


proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
      - ss-1
      - ss-2

rules:
  - IP-CIDR,10.0.0.0/8,DIRECT
  - IP-CIDR,172.16.0.0/12,DIRECT
  - IP-CIDR,192.168.0.0/16,DIRECT

  - GEOIP,CN,DIRECT

  - MATCH,PROXY
```
```


### Clash log

_No response_

### Description

tun2socks 透明代理与 clash socks 一起使用时，既然 fake-ip 或 redir-host 是为了解决 clash 只能 "看不到" 域名的问题，那么假设用的 dns 是无污染的情况下，是否可以只用 ip 分流？不使用 fake-ip 也不用 redir-host.
