### ISSUE TITLE
[Bug] 程序启动后出现大量连接，导致cpu占用极高

### ISSUE THREAD

**Issue by Fengzi2333** [Dreamacro/clash#2204]
### Verify steps

- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

Premium 2022.06.19

### Clash config

```yaml
mixed-port: 7890
allow-lan: false
external-controller: 127.0.0.1:9460
secret: 
ipv6: true
rule-providers:
  reject:
    type: http
    behavior: domain
    url: 
    path: ./ruleset/reject.yaml
    interval: 86400

  icloud:
    type: http
    behavior: domain
    url: 
    path: ./ruleset/icloud.yaml
    interval: 86400

  apple:
    type: http
    behavior: domain
    url: 
    path: ./ruleset/apple.yaml
    interval: 86400

  google:
    type: http
    behavior: domain
    url: 
    path: ./ruleset/google.yaml
    interval: 86400

  proxy:
    type: http
    behavior: domain
    url: 
    path: ./ruleset/proxy.yaml
    interval: 86400

  direct:
    type: http
    behavior: domain
    url: 
    path: ./ruleset/direct.yaml
    interval: 86400

  private:
    type: http
    behavior: domain
    url: 
    path: ./ruleset/private.yaml
    interval: 86400

  gfw:
    type: http
    behavior: domain
    url: 
    path: ./ruleset/gfw.yaml
    interval: 86400

  greatfire:
    type: http
    behavior: domain
    url: 
    path: ./ruleset/greatfire.yaml
    interval: 86400

  tld-not-cn:
    type: http
    behavior: domain
    url: 
    path: ./ruleset/tld-not-cn.yaml
    interval: 86400

  telegramcidr:
    type: http
    behavior: ipcidr
    url: 
    path: ./ruleset/telegramcidr.yaml
    interval: 86400

  cncidr:
    type: http
    behavior: ipcidr
    url: 
    path: ./ruleset/cncidr.yaml
    interval: 86400

  lancidr:
    type: http
    behavior: ipcidr
    url: 
    path: ./ruleset/lancidr.yaml
    interval: 86400

  applications:
    type: http
    behavior: classical
    url: 
    path: ./ruleset/applications.yaml
    interval: 86400

proxies:
  - name: Debug
    type: http
    server: 127.0.0.1
    port: 7890

proxy-groups:
  - name: PROXY
    type: select
    proxies:
      - Debug

rules:
  - RULE-SET,applications,DIRECT
  - DOMAIN,clash.razord.top,DIRECT
  - DOMAIN,yacd.haishan.me,DIRECT
  - RULE-SET,private,DIRECT
  - RULE-SET,reject,REJECT
  - RULE-SET,tld-not-cn,PROXY
  - RULE-SET,gfw,PROXY
  - RULE-SET,google,PROXY
  - RULE-SET,greatfire,PROXY
  - RULE-SET,telegramcidr,PROXY
  - MATCH,DIRECT
```

### Clash log

```shell
time="2022-07-05T10:20:54+08:00" level=info msg="Start initial compatible provider PROXY"
time="2022-07-05T10:20:54+08:00" level=info msg="Start initial rule provider reject"
time="2022-07-05T10:20:56+08:00" level=info msg="Start initial rule provider gfw"
time="2022-07-05T10:20:56+08:00" level=info msg="Start initial rule provider apple"
time="2022-07-05T10:20:56+08:00" level=info msg="Start initial rule provider proxy"
time="2022-07-05T10:20:57+08:00" level=info msg="Start initial rule provider private"
time="2022-07-05T10:20:57+08:00" level=info msg="Start initial rule provider google"
time="2022-07-05T10:20:57+08:00" level=info msg="Start initial rule provider cncidr"
time="2022-07-05T10:20:58+08:00" level=info msg="Start initial rule provider tld-not-cn"
time="2022-07-05T10:20:58+08:00" level=info msg="Start initial rule provider applications"
time="2022-07-05T10:20:58+08:00" level=info msg="Start initial rule provider greatfire"
time="2022-07-05T10:20:59+08:00" level=info msg="Start initial rule provider telegramcidr"
time="2022-07-05T10:20:59+08:00" level=info msg="Start initial rule provider icloud"
time="2022-07-05T10:20:59+08:00" level=info msg="Start initial rule provider direct"
time="2022-07-05T10:21:00+08:00" level=info msg="Start initial rule provider lancidr"
time="2022-07-05T10:21:00+08:00" level=info msg="RESTful API listening at: 127.0.0.1:9460"
time="2022-07-05T10:21:00+08:00" level=info msg="Mixed(http+socks) proxy listening at: 127.0.0.1:7890"
time="2022-07-05T10:21:00+08:00" level=debug msg="[Process] 140.82.114.26 from process \\Device\\HarddiskVolume5\\Program Files\\Google\\Chrome\\Application\\chrome.exe"
time="2022-07-05T10:21:01+08:00" level=info msg="[TCP] 127.0.0.1:9630 --> 140.82.114.26:443 match Match() using DIRECT"
time="2022-07-05T10:24:58+08:00" level=info msg="Start initial compatible provider PROXY"
time="2022-07-05T10:24:58+08:00" level=info msg="Start initial rule provider private"
time="2022-07-05T10:24:58+08:00" level=info msg="Start initial rule provider gfw"
time="2022-07-05T10:24:58+08:00" level=info msg="Start initial rule provider greatfire"
time="2022-07-05T10:24:59+08:00" level=info msg="Start initial rule provider tld-not-cn"
time="2022-07-05T10:24:59+08:00" level=info msg="Start initial rule provider lancidr"
time="2022-07-05T10:24:59+08:00" level=info msg="Start initial rule provider reject"
time="2022-07-05T10:24:59+08:00" level=info msg="Start initial rule provider cncidr"
time="2022-07-05T10:25:00+08:00" level=info msg="Start initial rule provider apple"
time="2022-07-05T10:25:00+08:00" level=info msg="Start initial rule provider proxy"
time="2022-07-05T10:25:00+08:00" level=info msg="Start initial rule provider direct"
time="2022-07-05T10:25:00+08:00" level=info msg="Start initial rule provider icloud"
time="2022-07-05T10:25:00+08:00" level=info msg="Start initial rule provider applications"
time="2022-07-05T10:25:00+08:00" level=info msg="Start initial rule provider telegramcidr"
time="2022-07-05T10:25:00+08:00" level=info msg="Start initial rule provider google"
time="2022-07-05T10:25:00+08:00" level=info msg="RESTful API listening at: 127.0.0.1:9460"
time="2022-07-05T10:25:00+08:00" level=info msg="Mixed(http+socks) proxy listening at: 127.0.0.1:7890"
time="2022-07-05T10:25:01+08:00" level=debug msg="[Process] 140.82.113.26 from process \\Device\\HarddiskVolume5\\Program Files\\Google\\Chrome\\Application\\chrome.exe"
time="2022-07-05T10:25:01+08:00" level=info msg="[TCP] 127.0.0.1:2368 --> 140.82.113.26:443 match Match() using DIRECT"
time="2022-07-05T10:25:05+08:00" level=debug msg="[Process] bolt.dropbox.com from process \\Device\\HarddiskVolume5\\Program Files (x86)\\Dropbox\\Client\\Dropbox.exe"
time="2022-07-05T10:25:05+08:00" level=debug msg="[Process] bolt.dropbox.com from process \\Device\\HarddiskVolume2\\Downloads\\programs\\clash-windows-amd64-v3-2022.06.19\\clash-windows-amd64-v3.exe"
time="2022-07-05T10:25:05+08:00" level=info msg="[TCP] 127.0.0.1:2371 --> bolt.dropbox.com:443 match RuleSet(gfw) using PROXY[Debug]"
time="2022-07-05T10:25:05+08:00" level=info msg="[TCP] 127.0.0.1:2372 --> bolt.dropbox.com:443 match RuleSet(gfw) using PROXY[Debug]"
time="2022-07-05T10:25:05+08:00" level=debug msg="[Process] bolt.dropbox.com from process \\Device\\HarddiskVolume2\\Downloads\\programs\\clash-windows-amd64-v3-2022.06.19\\clash-windows-amd64-v3.exe"
time="2022-07-05T10:25:05+08:00" level=debug msg="[Process] bolt.dropbox.com from process \\Device\\HarddiskVolume2\\Downloads\\programs\\clash-windows-amd64-v3-2022.06.19\\clash-windows-amd64-v3.exe"
time="2022-07-05T10:25:05+08:00" level=debug msg="[Process] bolt.dropbox.com from process \\Device\\HarddiskVolume2\\Downloads\\programs\\clash-windows-amd64-v3-2022.06.19\\clash-windows-amd64-v3.exe"
time="2022-07-05T10:25:05+08:00" level=info msg="[TCP] 127.0.0.1:2374 --> bolt.dropbox.com:443 match RuleSet(gfw) using PROXY[Debug]"
time="2022-07-05T10:25:05+08:00" level=debug msg="[Process] bolt.dropbox.com from process \\Device\\HarddiskVolume2\\Downloads\\programs\\clash-windows-amd64-v3-2022.06.19\\clash-windows-amd64-v3.exe"
time="2022-07-05T10:25:05+08:00" level=info msg="[TCP] 127.0.0.1:2375 --> bolt.dropbox.com:443 match RuleSet(gfw) using PROXY[Debug]"
time="2022-07-05T10:25:05+08:00" level=debug msg="[Process] bolt.dropbox.com from process \\Device\\HarddiskVolume2\\Downloads\\programs\\clash-windows-amd64-v3-2022.06.19\\clash-windows-amd64-v3.exe"
time="2022-07-05T10:25:05+08:00" level=info msg="[TCP] 127.0.0.1:2376 --> bolt.dropbox.com:443 match RuleSet(gfw) using PROXY[Debug]"
time="2022-07-05T10:25:05+08:00" level=debug msg="[Process] bolt.dropbox.com from process \\Device\\HarddiskVolume2\\Downloads\\programs\\clash-windows-amd64-v3-2022.06.19\\clash-windows-amd64-v3.exe"
time="2022-07-05T10:25:05+08:00" level=info msg="[TCP] 127.0.0.1:2377 --> bolt.dropbox.com:443 match RuleSet(gfw) using PROXY[Debug]"
time="2022-07-05T10:25:05+08:00" level=debug msg="[Process] bolt.dropbox.com from process \\Device\\HarddiskVolume2\\Downloads\\programs\\clash-windows-amd64-v3-2022.06.19\\clash-windows-amd64-v3.exe"
time="2022-07-05T10:25:05+08:00" level=info msg="[TCP] 127.0.0.1:2378 --> bolt.dropbox.com:443 match RuleSet(gfw) using PROXY[Debug]"
time="2022-07-05T10:25:05+08:00" level=debug msg="[Process] bolt.dropbox.com from process \\Device\\HarddiskVolume2\\Downloads\\programs\\clash-windows-amd64-v3-2022.06.19\\clash-windows-amd64-v3.exe"
time="2022-07-05T10:25:05+08:00" level=info msg="[TCP] 127.0.0.1:2379 --> bolt.dropbox.com:443 match RuleSet(gfw) using PROXY[Debug]"
time="2022-07-05T10:25:05+08:00" level=debug msg="[Process] bolt.dropbox.com from process \\Device\\HarddiskVolume2\\Downloads\\programs\\clash-windows-amd64-v3-2022.06.19\\clash-windows-amd64-v3.exe"
time="2022-07-05T10:25:05+08:00" level=info msg="[TCP] 127.0.0.1:2380 --> bolt.dropbox.com:443 match RuleSet(gfw) using PROXY[Debug]"
time="2022-07-05T10:25:05+08:00" level=debug msg="[Process] bolt.dropbox.com from process \\Device\\HarddiskVolume2\\Downloads\\programs\\clash-windows-amd64-v3-2022.06.19\\clash-windows-amd64-v3.exe"
time="2022-07-05T10:25:05+08:00" level=info msg="[TCP] 127.0.0.1:2381 --> bolt.dropbox.com:443 match RuleSet(gfw) using PROXY[Debug]"
time="2022-07-05T10:25:05+08:00" level=debug msg="[Process] bolt.dropbox.com from process \\Device\\HarddiskVolume2\\Downloads\\programs\\clash-windows-amd64-v3-2022.06.19\\clash-windows-amd64-v3.exe"
time="2022-07-05T10:25:05+08:00" level=info msg="[TCP] 127.0.0.1:2382 --> bolt.dropbox.com:443 match RuleSet(gfw) using PROXY[Debug]"
time="2022-07-05T10:25:05+08:00" level=info msg="[TCP] 127.0.0.1:2373 --> bolt.dropbox.com:443 match RuleSet(gfw) using PROXY[Debug]"
time="2022-07-05T10:25:05+08:00" level=info msg="[TCP] 127.0.0.1:2383 --> bolt.dropbox.com:443 match RuleSet(gfw) using PROXY[Debug]"
time="2022-07-05T10:25:05+08:00" level=debug msg="[Process] bolt.dropbox.com from process \\Device\\HarddiskVolume2\\Downloads\\programs\\clash-windows-amd64-v3-2022.06.19\\clash-windows-amd64-v3.exe"
time="2022-07-05T10:25:05+08:00" level=debug msg="[Process] bolt.dropbox.com from process \\Device\\HarddiskVolume2\\Downloads\\programs\\clash-windows-amd64-v3-2022.06.19\\clash-windows-amd64-v3.exe"
time="2022-07-05T10:25:05+08:00" level=info msg="[TCP] 127.0.0.1:2384 --> bolt.dropbox.com:443 match RuleSet(gfw) using PROXY[Debug]"
time="2022-07-05T10:25:05+08:00" level=debug msg="[Process] bolt.dropbox.com from process \\Device\\HarddiskVolume2\\Downloads\\programs\\clash-windows-amd64-v3-2022.06.19\\clash-windows-amd64-v3.exe"
time="2022-07-05T10:25:05+08:00" level=info msg="[TCP] 127.0.0.1:2385 --> bolt.dropbox.com:443 match RuleSet(gfw) using PROXY[Debug]"
time="2022-07-05T10:25:05+08:00" level=debug msg="[Process] bolt.dropbox.com from process \\Device\\HarddiskVolume2\\Downloads\\programs\\clash-windows-amd64-v3-2022.06.19\\clash-windows-amd64-v3.exe"
time="2022-07-05T10:25:05+08:00" level=info msg="[TCP] 127.0.0.1:2386 --> bolt.dropbox.com:443 match RuleSet(gfw) using PROXY[Debug]"
time="2022-07-05T10:25:05+08:00" level=debug msg="[Process] bolt.dropbox.com from process \\Device\\HarddiskVolume2\\Downloads\\programs\\clash-windows-amd64-v3-2022.06.19\\clash-windows-amd64-v3.exe"
time="2022-07-05T10:25:05+08:00" level=info msg="[TCP] 127.0.0.1:2387 --> bolt.dropbox.com:443 match RuleSet(gfw) using PROXY[Debug]"
time="2022-07-05T10:25:05+08:00" level=info msg="[TCP] 127.0.0.1:2388 --> bolt.dropbox.com:443 match RuleSet(gfw) using PROXY[Debug]"
time="2022-07-05T10:25:05+08:00" level=debug msg="[Process] bolt.dropbox.com from process \\Device\\HarddiskVolume2\\Downloads\\programs\\clash-windows-amd64-v3-2022.06.19\\clash-windows-amd64-v3.exe"
time="2022-07-05T10:25:05+08:00" level=debug msg="[Process] bolt.dropbox.com from process \\Device\\HarddiskVolume2\\Downloads\\programs\\clash-windows-amd64-v3-2022.06.19\\clash-windows-amd64-v3.exe"
time="2022-07-05T10:25:05+08:00" level=info msg="[TCP] 127.0.0.1:2389 --> bolt.dropbox.com:443 match RuleSet(gfw) using PROXY[Debug]"
time="2022-07-05T10:25:05+08:00" level=debug msg="[Process] bolt.dropbox.com from process \\Device\\HarddiskVolume2\\Downloads\\programs\\clash-windows-amd64-v3-2022.06.19\\clash-windows-amd64-v3.exe"
time="2022-07-05T10:25:05+08:00" level=info msg="[TCP] 127.0.0.1:2390 --> bolt.dropbox.com:443 match RuleSet(gfw) using PROXY[Debug]"
time="2022-07-05T10:25:05+08:00" level=info msg="[TCP] 127.0.0.1:2391 --> bolt.dropbox.com:443 match RuleSet(gfw) using PROXY[Debug]"
time="2022-07-05T10:25:05+08:00" level=debug msg="[Process] bolt.dropbox.com from process \\Device\\HarddiskVolume2\\Downloads\\programs\\clash-windows-amd64-v3-2022.06.19\\clash-windows-amd64-v3.exe"
time="2022-07-05T10:25:05+08:00" level=debug msg="[Process] bolt.dropbox.com from process \\Device\\HarddiskVolume2\\Downloads\\programs\\clash-windows-amd64-v3-2022.06.19\\clash-windows-amd64-v3.exe"
time="2022-07-05T10:25:05+08:00" level=info msg="[TCP] 127.0.0.1:2392 --> bolt.dropbox.com:443 match RuleSet(gfw) using PROXY[Debug]"
time="2022-07-05T10:25:05+08:00" level=debug msg="[Process] bolt.dropbox.com from process \\Device\\HarddiskVolume2\\Downloads\\programs\\clash-windows-amd64-v3-2022.06.19\\clash-windows-amd64-v3.exe"
time="2022-07-05T10:25:05+08:00" level=info msg="[TCP] 127.0.0.1:2393 --> bolt.dropbox.com:443 match RuleSet(gfw) using PROXY[Debug]"
time="2022-07-05T10:25:05+08:00" level=info msg="[TCP] 127.0.0.1:2394 --> bolt.dropbox.com:443 match RuleSet(gfw) using PROXY[Debug]"
time="2022-07-05T10:25:05+08:00" level=debug msg="[Process] bolt.dropbox.com from process \\Device\\HarddiskVolume2\\Downloads\\programs\\clash-windows-amd64-v3-2022.06.19\\clash-windows-amd64-v3.exe"
time="2022-07-05T10:25:05+08:00" level=debug msg="[Process] bolt.dropbox.com from process \\Device\\HarddiskVolume2\\Downloads\\programs\\clash-windows-amd64-v3-2022.06.19\\clash-windows-amd64-v3.exe"
time="2022-07-05T10:25:05+08:00" level=info msg="[TCP] 127.0.0.1:2395 --> bolt.dropbox.com:443 match RuleSet(gfw) using PROXY[Debug]"
time="2022-07-05T10:25:05+08:00" level=info msg="[TCP] 127.0.0.1:2396 --> bolt.dropbox.com:443 match RuleSet(gfw) using PROXY[Debug]"
time="2022-07-05T10:25:05+08:00" level=debug msg="[Process] bolt.dropbox.com from process \\Device\\HarddiskVolume2\\Downloads\\programs\\clash-windows-amd64-v3-2022.06.19\\clash-windows-amd64-v3.exe"
time="2022-07-05T10:25:05+08:00" level=debug msg="[Process] bolt.dropbox.com from process \\Device\\HarddiskVolume2\\Downloads\\programs\\clash-windows-amd64-v3-2022.06.19\\clash-windows-amd64-v3.exe"
time="2022-07-05T10:25:05+08:00" level=info msg="[TCP] 127.0.0.1:2397 --> bolt.dropbox.com:443 match RuleSet(gfw) using PROXY[Debug]"
time="2022-07-05T10:25:05+08:00" level=debug msg="[Process] bolt.dropbox.com from process \\Device\\HarddiskVolume2\\Downloads\\programs\\clash-windows-amd64-v3-2022.06.19\\clash-windows-amd64-v3.exe"
time="2022-07-05T10:25:05+08:00" level=info msg="[TCP] 127.0.0.1:2398 --> bolt.dropbox.com:443 match RuleSet(gfw) using PROXY[Debug]"
time="2022-07-05T10:25:05+08:00" level=info msg="[TCP] 127.0.0.1:2399 --> bolt.dropbox.com:443 match RuleSet(gfw) using PROXY[Debug]"
time="2022-07-05T10:25:05+08:00" level=debug msg="[Process] bolt.dropbox.com from process \\Device\\HarddiskVolume2\\Downloads\\programs\\clash-windows-amd64-v3-2022.06.19\\clash-windows-amd64-v3.exe"
time="2022-07-05T10:25:05+08:00" level=info msg="[TCP] 127.0.0.1:2400 --> bolt.dropbox.com:443 match RuleSet(gfw) using PROXY[Debug]"
time="2022-07-05T10:25:05+08:00" level=debug msg="[Process] bolt.dropbox.com from process \\Device\\HarddiskVolume2\\Downloads\\programs\\clash-windows-amd64-v3-2022.06.19\\clash-windows-amd64-v3.exe"
time="2022-07-05T10:25:05+08:00" level=info msg="[TCP] 127.0.0.1:2401 --> bolt.dropbox.com:443 match RuleSet(gfw) using PROXY[Debug]"
time="2022-07-05T10:25:05+08:00" level=debug msg="[Process] bolt.dropbox.com from process \\Device\\HarddiskVolume2\\Downloads\\programs\\clash-windows-amd64-v3-2022.06.19\\clash-windows-amd64-v3.exe"
time="2022-07-05T10:25:05+08:00" level=info msg="[TCP] 127.0.0.1:2402 --> bolt.dropbox.com:443 match RuleSet(gfw) using PROXY[Debug]"
time="2022-07-05T10:25:05+08:00" level=debug msg="[Process] bolt.dropbox.com from process \\Device\\HarddiskVolume2\\Downloads\\programs\\clash-windows-amd64-v3-2022.06.19\\clash-windows-amd64-v3.exe"
time="2022-07-05T10:25:05+08:00" level=debug msg="[Process] bolt.dropbox.com from process \\Device\\HarddiskVolume2\\Downloads\\programs\\clash-windows-amd64-v3-2022.06.19\\clash-windows-amd64-v3.exe"
time="2022-07-05T10:25:05+08:00" level=info msg="[TCP] 127.0.0.1:2403 --> bolt.dropbox.com:443 match RuleSet(gfw) using PROXY[Debug]"
time="2022-07-05T10:25:05+08:00" level=debug msg="[Process] bolt.dropbox.com from process \\Device\\HarddiskVolume2\\Downloads\\programs\\clash-windows-amd64-v3-2022.06.19\\clash-windows-amd64-v3.exe"
time="2022-07-05T10:25:05+08:00" level=info msg="[TCP] 127.0.0.1:2404 --> bolt.dropbox.com:443 match RuleSet(gfw) using PROXY[Debug]"
time="2022-07-05T10:25:05+08:00" level=info msg="[TCP] 127.0.0.1:2405 --> bolt.dropbox.com:443 match RuleSet(gfw) using PROXY[Debug]"
time="2022-07-05T10:25:05+08:00" level=debug msg="[Process] bolt.dropbox.com from process \\Device\\HarddiskVolume2\\Downloads\\programs\\clash-windows-amd64-v3-2022.06.19\\clash-windows-amd64-v3.exe"
time="2022-07-05T10:25:05+08:00" level=debug msg="[Process] bolt.dropbox.com from process \\Device\\HarddiskVolume2\\Downloads\\programs\\clash-windows-amd64-v3-2022.06.19\\clash-windows-amd64-v3.exe"
time="2022-07-05T10:25:05+08:00" level=info msg="[TCP] 127.0.0.1:2406 --> bolt.dropbox.com:443 match RuleSet(gfw) using PROXY[Debug]"
time="2022-07-05T10:25:05+08:00" level=debug msg="[Process] bolt.dropbox.com from process \\Device\\HarddiskVolume2\\Downloads\\programs\\clash-windows-amd64-v3-2022.06.19\\clash-windows-amd64-v3.exe"
time="2022-07-05T10:25:05+08:00" level=info msg="[TCP] 127.0.0.1:2407 --> bolt.dropbox.com:443 match RuleSet(gfw) using PROXY[Debug]"
time="2022-07-05T10:25:05+08:00" level=debug msg="[Process] bolt.dropbox.com from process \\Device\\HarddiskVolume2\\Downloads\\programs\\clash-windows-amd64-v3-2022.06.19\\clash-windows-amd64-v3.exe"
time="2022-07-05T10:25:05+08:00" level=info msg="[TCP] 127.0.0.1:2408 --> bolt.dropbox.com:443 match RuleSet(gfw) using PROXY[Debug]"
time="2022-07-05T10:25:05+08:00" level=info msg="[TCP] 127.0.0.1:2409 --> bolt.dropbox.com:443 match RuleSet(gfw) using PROXY[Debug]"
time="2022-07-05T10:25:05+08:00" level=debug msg="[Process] bolt.dropbox.com from process \\Device\\HarddiskVolume2\\Downloads\\programs\\clash-windows-amd64-v3-2022.06.19\\clash-windows-amd64-v3.exe"
time="2022-07-05T10:25:05+08:00" level=debug msg="[Process] bolt.dropbox.com from process \\Device\\HarddiskVolume2\\Downloads\\programs\\clash-windows-amd64-v3-2022.06.19\\clash-windows-amd64-v3.exe"
time="2022-07-05T10:25:05+08:00" level=info msg="[TCP] 127.0.0.1:2410 --> bolt.dropbox.com:443 match RuleSet(gfw) using PROXY[Debug]"
time="2022-07-05T10:25:05+08:00" level=debug msg="[Process] bolt.dropbox.com from process \\Device\\HarddiskVolume2\\Downloads\\programs\\clash-windows-amd64-v3-2022.06.19\\clash-windows-amd64-v3.exe"
time="2022-07-05T10:25:05+08:00" level=info msg="[TCP] 127.0.0.1:2411 --> bolt.dropbox.com:443 match RuleSet(gfw) using PROXY[Debug]"
time="2022-07-05T10:25:05+08:00" level=debug msg="[Process] bolt.dropbox.com from process \\Device\\HarddiskVolume2\\Downloads\\programs\\clash-windows-amd64-v3-2022.06.19\\clash-windows-amd64-v3.exe"
time="2022-07-05T10:25:05+08:00" level=info msg="[TCP] 127.0.0.1:2412 --> bolt.dropbox.com:443 match RuleSet(gfw) using PROXY[Debug]"
time="2022-07-05T10:25:05+08:00" level=info msg="[TCP] 127.0.0.1:2413 --> bolt.dropbox.com:443 match RuleSet(gfw) using PROXY[Debug]"
time="2022-07-05T10:25:05+08:00" level=debug msg="[Process] bolt.dropbox.com from process \\Device\\HarddiskVolume2\\Downloads\\programs\\clash-windows-amd64-v3-2022.06.19\\clash-windows-amd64-v3.exe"
```

### Description

程序启动后出现大量连接，导致cpu占用极高，连接来源似乎是clash
