### ISSUE TITLE
[Bug] 空IP被匹配到代理

### ISSUE THREAD

**Issue by K2M74** [Dreamacro/clash#2214]
### Verify steps

- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [x]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

clash-windows-amd64-v3-v1.11.4

### What OS are you seeing the problem on?

Windows

### Clash config

```yaml
ipv6: false

dns:
    enable: false

rules:
 - DOMAIN-SUFFIX,local,DIRECT
 - IP-CIDR,0.0.0.0/32,DIRECT
 - IP-CIDR,127.0.0.0/8,DIRECT
 - IP-CIDR,192.168.0.0/16,DIRECT
 - IP-CIDR,172.16.0.0/12,DIRECT
 - IP-CIDR,10.0.0.0/8,DIRECT
 - IP-CIDR,100.64.0.0/10,DIRECT
 - IP-CIDR6,::/128,DIRECT
 - IP-CIDR6,::1/128,DIRECT
 - IP-CIDR6,fc00::/7,DIRECT
 - IP-CIDR6,fe80::/10,DIRECT
 - IP-CIDR6,fd00::/8,DIRECT
 - GEOIP,CN,DIRECT
 - MATCH,代理
```

### Description

因为有些需求需要DNS上面拦截一些域名，我选择了空IP：0.0.0.0、:: 作为回答，这样反应很快。
但现在似乎在我明确直连的情况下，它依然走了代理。
![image](https://user-images.githubusercontent.com/50667472/178139049-f91210c2-91fe-4ee3-9ca9-ee471397c287.png)
我该如何配置让它生效？
