### ISSUE TITLE
请示一个最简单的示例

### ISSUE THREAD

**Issue by viponedream** [Dreamacro/clash#2216]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

新人看了一下配置,  https://github.com/Dreamacro/clash/wiki/configuration, 
发现特别复杂.

请问一下, 我要走全局, tun或tap模式的话, 目前手头有一个 trojan节点,要怎么用上我们这个高大上的clash啊.
我是在ubuntu服务器上面运行走全局的.

希望有一些简易的示例可以参考.

**Comment by itKelis** [comment]
找到proxies条目按上面提示添加节点信息即可
proxies:
  # Trojan
  - name: "trojan"
    type: trojan
    server: server
    port: 443
    password: yourpsk
    # udp: true
    # sni: example.com # aka server name
    # alpn:
    #   - h2
    #   - http/1.1
    # skip-cert-verify: true

**Comment by BirkhoffLee** [comment]
```yaml
mode: rule 

tun:
  enable: true
  stack: system
  auto-route: true
  auto-detect-interface: true

auto-redir:
  enable: true
  auto-route: true

dns:
  enable: true
  listen: 0.0.0.0:53
  default-nameserver:
    - 114.114.114.114
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  nameserver:
    - 114.114.114.114
    - 8.8.8.8

  fallback:
    - tcp://1.1.1.1
    - 'tcp://1.1.1.1#en0'

proxies:
  - name: "trojan"
    type: trojan
    server: server
    port: 443
    password: yourpsk
    # udp: true
    # sni: example.com # aka server name
    # alpn:
    #   - h2
    #   - http/1.1
    # skip-cert-verify: true

rules:
  - MATCH,trojan
```

用 sudo 执行，必须是 Premium core
