### ISSUE TITLE
[Bug] clash tun模式下 外网udp 端口转发

### ISSUE THREAD

**Issue by Victor2333** [Dreamacro/clash#2221]
### Verify steps

- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

Premium 2022.07.07

### What OS are you seeing the problem on?

Linux

### Clash config

```yaml
dns:
  enable: true
  listen: 0.0.0.0:53
  default-nameserver:
    - 8.8.8.8
  enhanced-mode: fake-ip # or redir-host (not recommended)
  fake-ip-range: 198.18.0.1/16 # Fake IP addresses pool CIDR
  fake-ip-filter:
    - localhost
    - '*.victor-tang.synology.me'
    - 'victor-tang.synology.me'  
  nameserver:
    - 192.168.0.29 # default value
  fallback:
    - 8.8.8.8 # default value
    - https://1.1.1.1/dns-query # DNS over HTTPS
  fallback-filter:
    geoip: true
    geoip-code: CN
tun:
  enable: true
  stack: system # or gvisor
  dns-hijack:
    - any:53
    - tcp://any:53
  auto-route: true
  auto-detect-interface: true
```

### Clash log

```shell
Jul 13 02:54:34 victor-ubuntu-server clash[1933]: time="2022-07-13T02:54:34Z" level=info msg="[UDP] 198.18.0.1:22024 --> 101.82.80.184:33886 match RuleSet(cncidr) using direct[DIRECT]"
Jul 13 02:55:52 victor-ubuntu-server clash[1933]: time="2022-07-13T02:55:52Z" level=info msg="[UDP] 198.18.0.1:22024 --> 101.82.80.184:33907 match RuleSet(cncidr) using direct[DIRECT]"
```

### Description

clash tun模式下 外网udp 端口转发 返回的udp数据到不了客户端

tcp: 路由 -> server ok, server->路由  ok
udp:路由 -> server ok, server->clash ok, clash -> 路由 failed

问题是为什么tcp 在auto-route: true的情况下 就不会走clash clash也没有对应的日志
但是udp就走了clash 并且 返回会失败

<img width="357" alt="image" src="https://user-images.githubusercontent.com/20839187/178641249-fed040d7-cd36-4caf-b785-41fcf8276329.png">
改成tcp就没有问题
<img width="333" alt="image" src="https://user-images.githubusercontent.com/20839187/178641332-de2dfc69-4950-4cfa-bca4-8b2ffb9d7213.png">
