### ISSUE TITLE
[Bug] Ubuntu + Docker + Clash Premium 下开启 TUN 后透明代理无效

### ISSUE THREAD

**Issue by HouCoder** [Dreamacro/clash#2223]
### Verify steps

- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

Premium 2022.07.07

### What OS are you seeing the problem on?

Linux

### Clash config

```yaml
port: 7890
socks-port: 7891
redir-port: 7892
allow-lan: true
bind-address: "*"
mode: Rule
log-level: debug
external-controller: 0.0.0.0:9090
secret: "xxx-xxx"
dns:
  enable: true
  listen: 0.0.0.0:53
  ipv6: true
  enhanced-mode: fake-ip
  nameserver:
    - 223.5.5.5
    - 223.6.6.6

tun:
  enable: true
  stack: system
  auto-route: true
  auto-detect-interface: true
```

### Description

Docker compose 配置：

```
clash:
  image: dreamacro/clash-premium@sha256:ec643c3daa464733db9045b1b4cbc30de8ccfb5360f09da8e37c5200d7ef8bb7
  privileged: true
  devices:
    - /dev/net/tun
  network_mode: "host"
  volumes:
    - ./clash/config.yaml:/root/.config/clash/config.yaml
  restart: "always"
```

根据官方文档在 docker 里成功运行，修改局域网的其它设备的网络设置，将 DNS 和网关指向 Clash 运行的服务器 IP 后不能访问网络，同样的配置脱离 Docker 环境直接运行 Clash Premium 二进制文件则可以正常开启透明代理功能，观察 docker log 未发现异常。

之前的方案是 Clash + iptables nat 方案，工作正常，现在移除 iptables nat 规则后直接开启 TUN 模式后反而不正常了。
