### ISSUE TITLE
[Bug] auto-route + openvpn 下，openvpn 路由表不能工作

### ISSUE THREAD

**Issue by x2c3z4** [Dreamacro/clash#2229]
### Verify steps

- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

Clash 2022.06.19 linux amd64 with go1.18.3 Sun Jun 19 05:24:35 UTC 2022

### What OS are you seeing the problem on?

Linux

### Clash config

```yaml
dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:53
  enhanced-mode: fake-ip
  nameserver:
  - 119.29.29.29
  - https://1.1.1.1/dns-query
  - 45.90.28.57
  - 223.5.5.5
  fallback:
  - 114.114.114.114
  - tls://8.8.8.8:853
  fallback-filter:
    geoip: true
    ipcidr:
      - 240.0.0.0/4
redir-port: 7892
ipv6: false
profile:
  tracing: true
  store-selected: true
tun:
  enable: true
  stack: system # or gvisor
  dns-hijack:
    - any:53
    - tcp://any:53
  auto-route: true
  auto-detect-interface: true
```

### Description

路由表如下，tun0 是 openvpn 设备，tun0 匹配行是 openvpn 下发的路由表。
局域网机器无法访问 192.168.16.x 等 openvpn 网段，但是运行 clash 的网关机器可以访问 openvpn 网段。

```
22-07-20 22:05:48 root@198.18.0.1:$ ip route
default via 192.168.50.1 dev enp1s0 proto static metric 100
10.7.0.0/24 dev wg0 proto kernel scope link src 10.7.0.13
10.8.0.0/20 via 10.8.0.101 dev tun0
10.8.0.101 dev tun0 proto kernel scope link src 10.8.0.102
192.168.16.0/20 via 10.8.0.101 dev tun0
192.168.32.0/20 via 10.8.0.101 dev tun0
192.168.48.0/20 via 10.8.0.101 dev tun0
192.168.50.0/24 dev enp1s0 proto kernel scope link src 192.168.50.5 metric 100
192.168.64.0/20 via 10.8.0.101 dev tun0
192.168.80.0/20 via 10.8.0.101 dev tun0
192.168.96.0/20 via 10.8.0.101 dev tun0
192.168.112.0/20 via 10.8.0.101 dev tun0
198.18.0.0/16 dev utun proto kernel scope link src 198.18.0.1
```
