### ISSUE TITLE
[Feature] External controller端口修改

### ISSUE THREAD

**Issue by Bollie15** [Dreamacro/clash#2230]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

下载clash后，然后导入了机场订阅链接，
```yaml
port: 7890
socks-port: 7891
redir-port: 7892
allow-lan: false
mode: rule
log-level: silent
external-controller: '127.0.0.1:9090'
secret: ''

...................
................
```
运行报错
```shell
$ ./clash -d . &
[2] 399543
$ INFO[0000] Start initial compatible provider "xxxxx"
INFO[0000] Start initial compatible provider "xxx"
INFO[0000] Start initial compatible provider "xxx"
ERRO[0000] External controller listen error: listen tcp 127.0.0.1:9090: bind: address already in use 
WARN[0000] [CacheFile] can't open cache file: timeout
```

报错原因，服务器上某个程序占用了端口：
```shell
# lsof -i:9090
COMMAND    PID       USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
yyy xx prometheus    3u  IPv6  68703      0t0  TCP *:websm (LISTEN)
yyy xx prometheus   59u  IPv6  97377      0t0  TCP localhost:43612->localhost:websm (ESTABLISHED)
yyy xx prometheus   62u  IPv6  43053      0t0  TCP localhost:websm->localhost:43612 (ESTABLISHED)
```

我的尝试：
1. 将机场节点配置文件的external-controller: '127.0.0.1:9090'端口改为`7893`后并且导入环境变量`export https_proxy=http://127.0.0.1:7890 http_proxy=http://127.0.0.1:7890 all_proxy=socks5://127.0.0.1:7890`后使用`curl`什么都不返回

所以想请问怎么修改这个 external-controller: '127.0.0.1:9090' ？谢谢:)
