### ISSUE TITLE
[Bug] Windows TUN 下即使全局模式或匹配到了规则，Clash 仍向 dns.nameserver 查询，导致因墙内 DNS 污染引起的访问失败

### ISSUE THREAD

**Issue by slusludy** [Dreamacro/clash#2231]
### Verify steps

- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

Premium 2022.07.07 amd64v3

### What OS are you seeing the problem on?

Windows

### Clash config

```yaml
tun:
  enable: true
  dns-hijack:
    - 198.18.0.2:53
  stack: gvisor
  auto-route: true
  auto-detect-interface: true
dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:53
  enhanced-mode: redir-host
  fake-ip-range: 198.18.0.0/16
  use-hosts: false
  default-nameserver:
    - 223.5.5.5
  nameserver:
    # 本机运行着 DNS 服务器软件，目的是通过这个 DNS 服务器软件看到 Clash 的查询结果，这个 DNS 服务器软件的上游服务器是墙内公共 DNS 服务器
    - 127.0.0.1
```

### Description

如配置文件所述，本机运行着 DNS 服务器软件，目的是通过这个 DNS 服务器软件看到 Clash 的查询结果，这个 DNS 服务器软件的上游服务器是墙内公共 DNS 服务器。wintun.dll 用的是官网最新版本 0.14.1.0，且带 WireGuard LLC 有效的数字签名。
下面是对照测试，每行是一次测试，每行内最后 4 列是结果，其余列是初始条件。
||设置host？|代理/TUN|规则/全局|匹配到的规则|Clash查询dns.nameserver？|curl成功？|VPS日志|
|---|---|---|---|---|---|---|---|
|1|×|代理|规则|域名后缀|×|√|域名|
|2|×|TUN|规则|域名后缀|√，污染|×|IP|
|3|×|TUN|全局|域名，全局|√，污染|×|IP|
|4|√|TUN|规则|IP，`Match`|×|√|IP|

将这个表格展开细说就是：
- 没有设置 host 条目，将 Clash 作为 HTTP 代理服务器，规则匹配模式，执行 `curl -v -x http://127.0.0.1:12345 https://www.google.com`
  - Clash 匹配到了 `DOMAIN-SUFFIX,google.com,翻墙` 的规则
  - Clash 不会向 `dns.nameserver` 查询
  - `curl` 访问成功
  - 墙外 VPS 的日志显示访问了域名
- 没有设置 host 条目，Clash 工作在 TUN 模式下，**规则匹配模式或全局模式**，执行 `curl -v https://www.google.com`
  - **在规则模式下，Clash 匹配到了 `DOMAIN-SUFFIX,google.com,翻墙`的规则；在全局模式下，域名匹配到了全局**。_既然都匹配到的不是 `Match` 规则，那就都不应该查询 `dns.nameserver`_
  - **Clash 会向 `dns.nameserver` 查询到被污染了的 IP 地址**，且这个地址是墙外合法的公网地址
  - `curl` 访问超时，且访问的 IP 地址与 Clash 查到的被污染的 IP 地址相同
  - 墙外 VPS 的日志显示访问了 Clash 查到的被污染了的 IP 地址
- 在 Windows 的 hosts 文件设置正确的条目，Clash 工作在 TUN 模式下，规则匹配模式，执行 `curl -v https://www.google.com`
  - Clash 匹配到了 `Match` 的规则，这条连接记录只有 IP 地址，没有域名，且 IP 地址正是手动设定在 host 条目里的 IP 地址
  - Clash 不会向 `dns.nameserver` 查询
  - `curl` 访问成功，且访问的 IP 地址正是手动设定在 host 条目里的 IP 地址
  - 墙外 VPS 的日志显示访问了手动设置在 host 条目里的 IP 地址，没显示域名。

综上所述，Windows Clash 工作在 TUN 模式下时总会查询 dns.nameserver，且会因墙内 DNS 污染导致翻墙失败；而将 Clash 仅从 TUN 模式换为 HTTP 代理模式，完全不改配置文件其他部分，则不会因墙内 DNS 污染产生问题。
