### ISSUE TITLE
[Bug] !开头的节点密码可能导致读取失败

### ISSUE THREAD

**Issue by futurkk** [Dreamacro/clash#2233]
### Verify steps

- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

v 1.11.4

### What OS are you seeing the problem on?

Windows

### Clash config

```yaml
配置文件中节点密码部分
如果节点密码为
password="!12345678"
clash读出
password=""
不知是否是!的问题
```

### Description

配置文件中节点密码部分
如果节点密码为
password="!12345678"
clash读出
password=""
不知是否是!的问题

**Comment by sinowood** [comment]
Another password bug: config file parse errror with all-digit password in trojan proxy:

```
port: 7890
socks-port: 7891
allow-lan: true
bind-address: '*'
mode: global
log-level: info

proxies:
- name: somename
  server: some.name.ml
  port: 443
  type: trojan
  password: 213218259897123
  skip-cert-verify: true
proxy-groups:
- name: 手动选择
  type: select
  proxies:
  - somename
```

Version: `Clash v1.11.4 && Clash v1.11.4 Clash 2022.07.07 (linux mipsle with go1.18.3 Thu Jul  7)`

Error Log:
```
FATA[0000] Parse config error: proxy 0: 'password' expected type 'string', got unconvertible type 'int64'
```

**Comment by qwerzl** [comment]
@sinowood This is not a bug. Passwords should be `string` instead of `int`.

Wrap quotation marks around your password.

**Comment by sinowood** [comment]
> @sinowood This is not a bug. Passwords should be `string` instead of `int`.
> 
> Wrap quotation marks around your password.

I think any password content should be treated as string?
Clash for Windows and Clash for Android can handle the same config file well...

**Comment by Dreamacro** [comment]
```yaml

proxies:
- name: somename
  server: some.name.ml
  port: 443
  type: trojan
  password: "213218259897123"
  skip-cert-verify: true

```
