### ISSUE TITLE
0.15.0配合公司内网DNS出现解析失败和内网无法访问，0.14.0版本不存在该情况

### ISSUE THREAD

**Issue by tony1016** [Dreamacro/clash#224]
说一下我司的情况，我司使用某VPN产品分配内网DNS和内网路由，今天更新ClashX到0.15.0版本后日志中出现以下问题，切内网无法访问：
```
2019/07/01 15:48:24:240  [warning] Proxy[DIRECT] connect [127.0.0.1 --> mail.company.com] error: All DNS requests failed
2019/07/01 15:48:24:249  [info] 127.0.0.1 --> mail.company.com match DomainSuffix using DIRECT
```
但是我用`dig`命令实测DNS是好的
```
dig mail.company.com @111.222.9.68

; <<>> DiG 9.10.6 <<>> mail.company.com @111.222.9.68
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 39516
;; flags: qr aa rd ra ad; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;mail.company.com.		IN	A

;; ANSWER SECTION:
mail.company.com.	86400	IN	A	111.1.56.59

;; Query time: 7 msec
;; SERVER: 111.222.9.68#53(111.222.9.68)
;; WHEN: Mon Jul 01 15:49:42 CST 2019
;; MSG SIZE  rcvd: 51
```
我的配置文件相关内容如下：
```
# DNS 设置
dns:
  enable: true # set true to enable dns (default is false)
  ipv6: false # default is false
  listen: 0.0.0.0:8853 #这里8853是因为我用dnsmasq将系统请求转过来的
  enhanced-mode: redir-host # redir-host or fake-ip
  # fake-ip-range: 198.18.0.1/16 # if you don't know what it is, don't change it
  nameserver:
    - 117.50.10.10
    - 119.29.29.29
    - 223.5.5.5
    - 114.114.114.114
    - 111.222.9.68
  fallback: # concurrent request with nameserver, fallback used when GEOIP country isn't CN
    - tls://8.8.4.4:853
    - tls://1.0.0.1:853
    - 192.168.193.53

- DOMAIN-SUFFIX,company.com,DIRECT
- IP-CIDR,111.0.0.0/8,DIRECT
```

测试情况如下：
- 0.14.0是好的
- 关闭DNS后，是好的

抱歉处于隐私目的，案例中的地址和IP是假的，但是不影响情况分析
