### ISSUE TITLE
[Bug] TUN模式DNS劫持不生效

### ISSUE THREAD

**Issue by a490077** [Dreamacro/clash#2249]
### Verify steps

- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

docker dreamacro/clash-premium 2022.07.07

### Clash config

```yaml
tun:
  enable: true
  stack: system # or gvisor
  dns-hijack:
    - any:53
    - tcp://any:53
  auto-route: true # auto set global route
  auto-detect-interface: false # conflict with interface-name

tun已经按如上配置了dns-hijack，目前的情况是docker-clash做旁路网关，指定终端的DNS为clash的地址就可以正常使用，若终端DNS不是clash的地址，无法访问外网， 是否我的本地DNS劫持没有配置好
```

### Description

tun:
  enable: true
  stack: system # or gvisor
  dns-hijack:
    - any:53
    - tcp://any:53
  auto-route: true # auto set global route
  auto-detect-interface: false # conflict with interface-name

tun已经按如上配置了dns-hijack，目前的情况是docker-clash做旁路网关，指定终端的DNS为clash的地址就可以正常使用，若终端DNS不是clash的地址，无法访问外网， 是否我的本地DNS劫持没有配置好

**Comment by Dreamacro** [comment]
如果你的 dns 是内网地址，那确实是没法 hijack 的，可以下发随便一个外网的 dns

**Comment by a490077** [comment]
您好,  我终端的DNS是主路由下发的 119.29.29.29 , 114.114.114.114  网关是clash的ip地址, 
这样可以访问国内网站, 但外网无法连通,
将终端的DNS改为clash的地址, 就可以正常访问了.
导致这个情况的问题可能出在哪个地方呢?

**Comment by Dreamacro** [comment]
给出其他基本配置，还有 dig curl 及 clash 日志

**Comment by a490077** [comment]
其他配置如下:
```yaml
# Port of HTTP(S) proxy server on the local end
port: 7890

# Port of SOCKS5 proxy server on the local end
socks-port: 7891

# Transparent proxy server port for Linux and macOS (Redirect TCP and TProxy UDP)
redir-port: 7892

# Transparent proxy server port for Linux (TProxy TCP and TProxy UDP)
tproxy-port: 7893

# HTTP(S) and SOCKS4(A)/SOCKS5 server on the same port
mixed-port: 7894

# authentication of local SOCKS5/HTTP(S) server
# authentication:
#  - "user1:pass1"
#  - "user2:pass2"

# Set to true to allow connections to the local-end server from
# other LAN IP addresses
allow-lan: true

# This is only applicable when `allow-lan` is `true`
# '*': bind all IP addresses
# 192.168.122.11: bind a single IPv4 address
# "[aaaa::a8aa:ff:fe09:57d8]": bind a single IPv6 address
bind-address: '*'

# Clash router working mode
# rule: rule-based packet routing
# global: all packets will be forwarded to a single endpoint
# direct: directly forward the packets to the Internet
mode: rule

# Clash by default prints logs to STDOUT
# info / warning / error / debug / silent
log-level: info

# When set to false, resolver won't translate hostnames to IPv6 addresses
ipv6: false

# RESTful web API listening address
external-controller: 0.0.0.0:9090

# A relative path to the configuration directory or an absolute path to a
# directory in which you put some static web resource. Clash core will then
# serve it at `${API}/ui`.
# external-ui: folder

# Secret for the RESTful API (optional)
# Authenticate by spedifying HTTP header `Authorization: Bearer ${secret}`
# ALWAYS set a secret if RESTful API is listening on 0.0.0.0
secret: ""

# Outbound interface name
interface-name: eth0

# Static hosts for DNS server and connection establishment (like /etc/hosts)
#
# Wildcard hostnames are supported (e.g. *.clash.dev, *.foo.*.example.com)
# Non-wildcard domain names have a higher priority than wildcard domain names
# e.g. foo.example.com > *.example.com > .example.com
# P.S. +.foo.com equals to .foo.com and foo.com
hosts:
  # '*.clash.dev': 127.0.0.1
  # '.dev': 127.0.0.1
  # 'alpha.clash.dev': '::1'

  # Firebase Cloud Messaging
  'mtalk.google.com': 108.177.125.188
  # Google Dl
  'dl.google.com': 180.163.151.161
  'dl.l.google.com': 180.163.151.161

profile:
  # Store the `select` results in $HOME/.config/clash/.cache
  # set false If you don't want this behavior
  # when two different configurations have groups with the same name, the selected values are shared
  # store-selected: false
  store-selected: true
  store-fake-ip: true

# DNS server settings
# This section is optional. When not present, the DNS server will be disabled.
dns:
  enable: true
  listen: 0.0.0.0:53
  ipv6: false # when the false, response to AAAA questions will be empty

  # These nameservers are used to resolve the DNS nameserver hostnames below.
  # Specify IP addresses only
  default-nameserver:
    - 119.29.29.29
    - 114.114.114.114
  enhanced-mode: fake-ip # or redir-host
  fake-ip-range: 198.18.0.1/16 # Fake IP addresses pool CIDR
  # use-hosts: true # lookup hosts and return IP record
  
  # Hostnames in this list will not be resolved with fake IPs
  # i.e. questions to these domain names will always be answered with their
  # real IP addresses
  fake-ip-filter:
    - '*.lan'
    - localhost.ptlogin2.qq.com
    - '+.srv.nintendo.net'
    - '+.stun.playstation.net'
    - '+.msftconnecttest.com'
    - '+.msftncsi.com'
    - '+.xboxlive.com'
    - 'msftconnecttest.com'
    - 'xbox.*.microsoft.com'
    - '*.battlenet.com.cn'
    - '*.battlenet.com'
    - '*.blzstatic.cn'
    - '*.battle.net'
  
  # Supports UDP, TCP, DoT, DoH. You can specify the port to connect to.
  # All DNS questions are sent directly to the nameserver, without proxies
  # involved. Clash answers the DNS question with the first result gathered.
  nameserver:
    - 119.29.29.29
    - 114.114.114.114 # default value
    - 119.28.28.28
    - 223.5.5.5
    # - 8.8.8.8 # default value
    # - tls://dns.rubyfish.cn:853 # DNS over TLS
    # - https://1.1.1.1/dns-query # DNS over HTTPS
    # - dhcp://en0 # dns from dhcp

  # When `fallback` is present, the DNS server will send concurrent requests
  # to the servers in this section along with servers in `nameservers`.
  # The answers from fallback servers are used when the GEOIP country
  # is not `CN`.
  fallback:
    - https://doh.pub/dns-query
    - https://dns.alidns.com/dns-query
    - https://cloudflare-dns.com/dns-query
    - https://dns.rubyfish.cn/dns-query
    - https://1.1.1.1/dns-query

  # If IP addresses resolved with servers in `nameservers` are in the specified
  # subnets below, they are considered invalid and results from `fallback`
  # servers are used instead.
  #
  # IP address resolved with servers in `nameserver` is used when
  # `fallback-filter.geoip` is true and when GEOIP of the IP address is `CN`.
  #
  # If `fallback-filter.geoip` is false, results from `nameserver` nameservers
  # are always used if not match `fallback-filter.ipcidr`.
  #
  # This is a countermeasure against DNS pollution attacks.
  fallback-filter:
    geoip: true
    geoip-code: CN
    ipcidr:
      - 0.0.0.0/8
      - 10.0.0.0/8
      - 100.64.0.0/10
      - 127.0.0.0/8
      - 169.254.0.0/16
      - 172.16.0.0/12
      - 192.0.0.0/24
      - 192.0.2.0/24
      - 192.88.99.0/24
      - 192.168.0.0/16
      - 198.18.0.0/15
      - 198.51.100.0/24
      - 203.0.113.0/24
      - 224.0.0.0/4
      - 240.0.0.0/4
      - 255.255.255.255/32
    domain:
      - "+.google.com"
      - "+.facebook.com"
      - "+.youtube.com"
      - "+.githubusercontent.com"
      - "+.googlevideo.com" 
  
  # Lookup domains via specific nameservers
  # nameserver-policy:
  #   'www.baidu.com': '114.114.114.114'
  #   '+.internal.crop.com': '10.0.0.1'

#
# https://github.com/Dreamacro/clash/wiki/premium-core-features
#
tun:
  enable: true
  stack: system # or gvisor
  dns-hijack:
  #   - 8.8.8.8:53
  #   - tcp://8.8.8.8:53
    - any:53
    - tcp://any:53
    
  auto-route: true # auto set global route
  auto-detect-interface: false # conflict with interface-name
```
# 测试
因为涉及测试命令, 我用了局域网下的一个ubuntu20.04, 地址10.0.0.55, 
主路由: 爱快(10.0.0.1), 
目前用的旁路由: openwrt(10.0.0.11)
正在折腾的docker旁路网关,计划替换掉旁路由: dreamacro/clash-premium(10.0.0.66)
## 网关设为clash-premium(10.0.0.66)测试:
 ```shell
$ ip route show
default via 10.0.0.66 dev ens160 proto dhcp src 10.0.0.55 metric 100 
10.0.0.0/24 dev ens160 proto kernel scope link src 10.0.0.55 
10.0.0.66 dev ens160 proto dhcp scope link src 10.0.0.55 metric 100 
```
 ```shell
$  dig baidu.com

; <<>> DiG 9.16.1-Ubuntu <<>> baidu.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 26166
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 65494
;; QUESTION SECTION:
;baidu.com.                     IN      A

;; ANSWER SECTION:
baidu.com.              488     IN      A       110.242.68.66
baidu.com.              488     IN      A       39.156.66.10

;; Query time: 12 msec
;; SERVER: 127.0.0.53#53(127.0.0.53)
;; WHEN: Wed Aug 03 11:47:33 CST 2022
;; MSG SIZE  rcvd: 70

$ dig google.com   

; <<>> DiG 9.16.1-Ubuntu <<>> google.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 64681
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 65494
;; QUESTION SECTION:
;google.com.                    IN      A

;; ANSWER SECTION:
google.com.             30      IN      A       8.7.198.46

;; Query time: 43 msec
;; SERVER: 127.0.0.53#53(127.0.0.53)
;; WHEN: Wed Aug 03 11:50:23 CST 2022
;; MSG SIZE  rcvd: 55
```
```shell
 $ curl -v baidu.com
*   Trying 39.156.66.10:80...
* Connected to baidu.com (39.156.66.10) port 80 (#0)
> GET / HTTP/1.1
> Host: baidu.com
> User-Agent: curl/7.82.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Date: Wed, 03 Aug 2022 03:48:46 GMT
< Server: Apache
< Last-Modified: Tue, 12 Jan 2010 13:48:00 GMT
< ETag: "51-47cf7e6ee8400"
< Accept-Ranges: bytes
< Content-Length: 81
< Cache-Control: max-age=86400
< Expires: Thu, 04 Aug 2022 03:48:46 GMT
< Connection: Keep-Alive
< Content-Type: text/html
< 
<html>
<meta http-equiv="refresh" content="0;url=http://www.baidu.com/">
</html>
* Connection #0 to host baidu.com left intact

$ curl -v google.com
*   Trying 8.7.198.46:80...
* Connected to google.com (8.7.198.46) port 80 (#0)
> GET / HTTP/1.1
> Host: google.com
> User-Agent: curl/7.82.0
> Accept: */*
> 
* Recv failure: Connection reset by peer
* Closing connection 0
curl: (56) Recv failure: Connection reset by peer
```
```shell
$ ping -c 3 baidu.com
PING baidu.com (39.156.66.10) 56(84) bytes of data.
64 bytes from 39.156.66.10 (39.156.66.10): icmp_seq=1 ttl=50 time=42.6 ms
64 bytes from 39.156.66.10 (39.156.66.10): icmp_seq=2 ttl=50 time=40.7 ms
64 bytes from 39.156.66.10 (39.156.66.10): icmp_seq=3 ttl=50 time=40.7 ms

--- baidu.com ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 2004ms
rtt min/avg/max/mdev = 40.698/41.348/42.646/0.917 ms

$ ping -c 3 google.com
PING google.com (142.251.42.238) 56(84) bytes of data.

--- google.com ping statistics ---
3 packets transmitted, 0 received, 100% packet loss, time 2026ms
```
### 此时只能访问国内网站
### 在以上测试时  clash 的日志没有任何输出  日志等级为info


## 网关设为openwrt(10.0.0.11), 安装了openclash(同一份配置文件)测试:
```shell
$ ip route show
default via 10.0.0.11 dev ens160 proto dhcp src 10.0.0.55 metric 100 
10.0.0.0/24 dev ens160 proto kernel scope link src 10.0.0.55 
10.0.0.11 dev ens160 proto dhcp scope link src 10.0.0.55 metric 100 
```
```shell
$ dig baidu.com 

; <<>> DiG 9.16.1-Ubuntu <<>> baidu.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 7288
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 65494
;; QUESTION SECTION:
;baidu.com.                     IN      A

;; ANSWER SECTION:
baidu.com.              1       IN      A       198.18.9.194

;; Query time: 0 msec
;; SERVER: 127.0.0.53#53(127.0.0.53)
;; WHEN: Wed Aug 03 11:58:02 CST 2022
;; MSG SIZE  rcvd: 54

$ dig google.com    

; <<>> DiG 9.16.1-Ubuntu <<>> google.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 52964
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 65494
;; QUESTION SECTION:
;google.com.                    IN      A

;; ANSWER SECTION:
google.com.             1       IN      A       198.18.9.195

;; Query time: 4 msec
;; SERVER: 127.0.0.53#53(127.0.0.53)
;; WHEN: Wed Aug 03 11:58:30 CST 2022
;; MSG SIZE  rcvd: 55

$ dig google.com @10.0.0.66

; <<>> DiG 9.16.1-Ubuntu <<>> google.com @10.0.0.66
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 40422
;; flags: qr aa rd ra ad; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; MBZ: 0x0001, udp: 4096
; COOKIE: 3c493dd5c5e1e3f4 (echoed)
;; QUESTION SECTION:
;google.com.                    IN      A

;; ANSWER SECTION:
google.com.             1       IN      A       198.18.0.110

;; Query time: 96 msec
;; SERVER: 10.0.0.66#53(10.0.0.66)
;; WHEN: Wed Aug 03 12:03:23 CST 2022
;; MSG SIZE  rcvd: 67
```
```shell
$ curl -v baidu.com 
*   Trying 198.18.9.194:80...
* Connected to baidu.com (198.18.9.194) port 80 (#0)
> GET / HTTP/1.1
> Host: baidu.com
> User-Agent: curl/7.82.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Date: Wed, 03 Aug 2022 03:59:05 GMT
< Server: Apache
< Last-Modified: Tue, 12 Jan 2010 13:48:00 GMT
< ETag: "51-47cf7e6ee8400"
< Accept-Ranges: bytes
< Content-Length: 81
< Cache-Control: max-age=86400
< Expires: Thu, 04 Aug 2022 03:59:05 GMT
< Connection: Keep-Alive
< Content-Type: text/html
< 
<html>
<meta http-equiv="refresh" content="0;url=http://www.baidu.com/">
</html>
* Connection #0 to host baidu.com left intact

$ curl -v google.com
*   Trying 198.18.9.195:80...
* Connected to google.com (198.18.9.195) port 80 (#0)
> GET / HTTP/1.1
> Host: google.com
> User-Agent: curl/7.82.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 301 Moved Permanently
< Location: http://www.google.com/
< Content-Type: text/html; charset=UTF-8
< Date: Wed, 03 Aug 2022 03:59:33 GMT
< Expires: Fri, 02 Sep 2022 03:59:33 GMT
< Cache-Control: public, max-age=2592000
< Server: gws
< Content-Length: 219
< X-XSS-Protection: 0
< X-Frame-Options: SAMEORIGIN
< 
<HTML><HEAD><meta http-equiv="content-type" content="text/html;charset=utf-8">
<TITLE>301 Moved</TITLE></HEAD><BODY>
<H1>301 Moved</H1>
The document has moved
<A HREF="http://www.google.com/">[here](http://www.google.com/)</A>.
</BODY></HTML>
* Connection #0 to host google.com left intact
```
```shell
$ ping -c 3 baidu.com 
PING baidu.com (198.18.9.194) 56(84) bytes of data.
64 bytes from 198.18.9.194 (198.18.9.194): icmp_seq=1 ttl=62 time=0.217 ms
64 bytes from 198.18.9.194 (198.18.9.194): icmp_seq=2 ttl=62 time=0.285 ms
64 bytes from 198.18.9.194 (198.18.9.194): icmp_seq=3 ttl=62 time=0.251 ms

--- baidu.com ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 2003ms
rtt min/avg/max/mdev = 0.217/0.251/0.285/0.027 ms

ping -c 3 google.com
PING google.com (198.18.9.195) 56(84) bytes of data.
64 bytes from 198.18.9.195 (198.18.9.195): icmp_seq=1 ttl=62 time=0.241 ms
64 bytes from 198.18.9.195 (198.18.9.195): icmp_seq=2 ttl=62 time=0.268 ms
64 bytes from 198.18.9.195 (198.18.9.195): icmp_seq=3 ttl=62 time=0.282 ms

--- google.com ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 2012ms
rtt min/avg/max/mdev = 0.241/0.263/0.282/0.017 ms
```
### 此时可正常访问所有网站


以上, 网关和DNS全部由爱快静态DHCP分配,  主DNS:119.29.29.29  备用DNS:114.114.114.114     其它设置无任何更改, 
由于我不太会手动修改ubuntu的DNS, 所以没有修改DNS以后正常使用的日志, 但在win系统手动指定DNS为docker-clash的ip是正常使用的, dig测试指定DNS服务器以后也可以正常返回fake-ip的地址,  所以怀疑DNS劫持未生效

我用了openclash做网关来对比, 不知openwrt和docker中的clash为何会有差异导致无法使用,  麻烦看看我的设置有无问题
