### ISSUE TITLE
[Bug] clash与tailscale的兼容问题

### ISSUE THREAD

**Issue by gouku** [Dreamacro/clash#2251]
### Verify steps

- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

1.11.4

### What OS are you seeing the problem on?

macOS

### Clash config

```yaml
port: 7890
socks-port: 7891
allow-lan: true
mode: rule
log-level: info
ipv6: true
external-controller: :9090
secret: xxxx
profile:
  store-selected: true
tun:
  enable: true
  stack: system
  dns-hijack:
    - any:53
  auto-route: true
  auto-detect-interface: true
dns:
  enabled: true
  listen: 127.0.0.1:15353
  ipv6: true
  default-nameserver:
    - 119.29.29.29
    - 223.5.5.5
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - "*.lan"
    - "*.local"
  nameserver:
    - tls://1.12.12.12
    - tls://223.6.6.6
proxies:
  - ...
proxy-groups:
  - ...
rules:
 - ...
 - DOMAIN,localhost,DIRECT
 - DOMAIN-SUFFIX,local,DIRECT
 - DOMAIN-SUFFIX,local.,DIRECT
 - DOMAIN-SUFFIX,direct,DIRECT
 - IP-CIDR,0.0.0.0/32,DIRECT
 - IP-CIDR,10.0.0.0/8,DIRECT
 - IP-CIDR,17.0.0.0/8,DIRECT
 - IP-CIDR,100.64.0.0/10,DIRECT
 - IP-CIDR,172.16.0.0/12,DIRECT
 - IP-CIDR,127.0.0.0/8,DIRECT
 - IP-CIDR,192.168.0.0/16,DIRECT
 - IP-CIDR6,::1/128,DIRECT
 - IP-CIDR6,fc00::/7,DIRECT
 - IP-CIDR6,fe80::/10,DIRECT
 - IP-CIDR6,fd00::/8,DIRECT
 - GEOIP,CN,DIRECT
 - MATCH,Proxy
```

### Clash log

```shell
[TCP] dial DIRECT (match IPCIDR/100.64.0.0/10) to 100.65.221.33:8080 error: dial tcp4 100.65.221.33:8080: i/o timeout
```

### Description

- 当clash开启增强模式并开启Tailscale时，所有浏览器（firefox、chrome、safari、edge）均无法正常访问目标机器上的网页
- 关闭增强模式后可正常访问
- Surge for Mac开启增强模式就不存在此问题
- 无论开启/关闭增强模式，在命令行中使用curl均可返回网页内容：
```
curl -i http://100.65.221.33:8080
HTTP/1.1 200 OK
Accept-Ranges: bytes
Content-Length: 11228
Content-Type: text/html; charset=utf-8
Etag: "rby9io8nw"
Last-Modified: Mon, 16 May 2022 00:32:48 GMT
Server: Caddy
Date: Wed, 03 Aug 2022 17:22:32 GMT

<!DOCTYPE html.....
```

**Comment by gouku** [comment]
https://github.com/Dreamacro/clash/issues/1026 看了下这个切gvisor没用，然后macos上也没有解决方案用到的iptables

**Comment by Dreamacro** [comment]
只开增强模式不开系统代理就可以吧？surge 开了系统代理应该也不行

**Comment by gouku** [comment]
@Dreamacro 才知道竟然可以只开增强模式不开系统代理，那这个和两个都开的区别是什么呢？

Surge开了系统代理是可以的：
![image](https://user-images.githubusercontent.com/9361308/182767148-c8f438ca-fe24-4e37-8a7b-7033f52a30d7.png)
![image](https://user-images.githubusercontent.com/9361308/182767213-72bad6f0-757f-42e4-a8e9-516d427f3ed8.png)

**Comment by Dreamacro** [comment]
系统代理就是该系统的设置，增强模式是改路由。前者要关是因为这个流量进到 clash 后，clash 从默认网卡出口出，导致连不上。只开增强意味着还会走 tailscale 自己的路由，所以不影响使用。

有空我看一下 surge 怎么做的，理论上需要读系统的路由才能做到。

**Comment by Dreamacro** [comment]
surge 有什么特殊的配置吗？还是不需要配置就可以做到的？

**Comment by gouku** [comment]
@Dreamacro 并没有什么特殊的配置，我是用subconverter直接转换出来的，理论上除了surge专属的一些配置外，大体上是一样的

**Comment by gouku** [comment]
Surge的配置：

```
#!MANAGED-CONFIG https://xxxxx interval=86400 strict=false

[General]
loglevel = warning
bypass-system = true
ipv6 = false
skip-proxy = 0.0.0.0, 127.0.0.1, 192.168.0.0/16, 10.0.0.0/8, 172.16.0.0/12, 100.64.0.0/10, 17.0.0.0/8, localhost, *.local, *.local., *.direct, captive.apple.com, ::ffff:0:0:0:0/1, ::ffff:128:0:0:0/1
bypass-tun = 10.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16
tun-excluded-routes = 10.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16
exclude-simple-hostnames = true
collapse-policy-group-items = true
external-controller-access = `xxxxxx@127.0.0.1:6170
http-listen = 0.0.0.0:3333
socks5-listen = 0.0.0.0:3334
read-etc-hosts = true
internet-test-url = http://www.baidu.com/
proxy-test-url = http://www.gstatic.com/generate_204
test-timeout = 3
dns-server = 119.29.29.29, 223.5.5.5
hijack-dns = *:53
enhanced-mode-by-rule = false
hide-apple-request = true
hide-crashlytics-request = true
hide-udp = false
keyword-filter-type = false
show-error-page-for-reject = true
```

**Comment by Dreamacro** [comment]
试着把 100.64.0.0/10 删掉呢？这个是 tailscale 用到的段

**Comment by Dreamacro** [comment]
那么我猜你打开 surge 的系统代理时，在网络设置的代理中，会包含 100.64.0.0/10 这个配置。而目前 clashx 不会

**Comment by gouku** [comment]
经过排查，我发现 个诡异的情况：

- 完全删除上述surge配置中的`skip-proxy`，无法访问网站
- 仅删除`100.64.0.0/10`，依然可以访问
- 删除全部`skip-proxy`内容，每次只添加一个，最后排出后发现只要有`::ffff:0:0:0:0/1`或者 `::ffff:128:0:0:0/1`存在，就可以访问tailscale的网络

**Comment by Bpazy** [comment]
@Dreamacro @gouku Hi, 我遇到了相同的问题，请问这个问题有进展吗？

**Comment by gouku** [comment]
@Bpazy 目前增强模式下，不开启系统代理，是没问题的

**Comment by gouku** [comment]
我又多测试了一下，目前surge和clash都不能完美兼容tailscale，在开启增强模式的情况下，自行搭建的derp服务器（都在国内，已备案域名）都无法直连目标节点，只能以relay的方式中转

但是关掉derp，只使用tailscale官方的那批服务器时，开启增强模式又都能直连了

**Comment by Bpazy** [comment]
我也描述一下我的环境背景：
1. windows 11；
2. 自建了 derp；
3. 未启用系统代理；

问题描述：
1. 先开启 tailscale 再开启 clash TUN 时，可正常访问 tailscale subnet 机器；
2. 在 1 的基础上，从有线网切换为无线网（断开有线网然后连接无线网），此时无法访问 tailscale subnet 机器，但是关闭 clash TUN 后，立刻可以访问 tailscale subent 机器了；

如果我的这个问题被认为是和当前 issue 无关，我可以重新提一个新的

**Comment by xdays** [comment]
相同的问题，给大神们提供一个线索，我同时使用zerotier和tailscale，当开启增强模式的时候由zerotier路由的ip仍然能访问，tailscale路由ip不可访问

Zerotier添加的路由
```
$ netstat -nr | grep 10.101
10.101/16          10.147.19.85       UGSc          feth124
10.101/16          10.147.19.85       UGScI           utun5
```

Tailscale添加的路由
```
$ netstat -nr | grep 172.31
172.31             link#27            UCS             utun5
```

**Comment by Bpazy** [comment]
今天抽空对 tailscaled, tailscale 的源码进行了调试，发现当开启 Clash Tun 的时候，tailscaled 因为连接不上这两个域名导致始终无法成功启动：
* controlplane.tailscale.com
* log.tailscale.io

所以我通过将这两个域名添加到 fake-ip-filter 列表中解决了问题:
```yaml
  dns:
    enable: true
    enhanced-mode: fake-ip
    nameserver:
      - 114.114.114.114
    fallback: []
    fake-ip-filter:
      # 省略了部分配置
      - controlplane.tailscale.com
      - log.tailscale.io
```
同时注意，Clash for Windows 不会读取 user profile 中的 dns 模块，所以上面的这段代码要写在 Clash for Windows 的 Mixin 配置中：
![image](https://user-images.githubusercontent.com/9838749/197592050-932be5d3-b68f-44ce-824d-961fd885214b.png)

我的完整 Mixin：
```yaml
mixin: # object
  dns:
    enable: true
    enhanced-mode: fake-ip
    nameserver:
      - 114.114.114.114
      - 223.5.5.5
      - 8.8.8.8
    fallback: []
    fake-ip-filter:
      - +.stun.*.*
      - +.stun.*.*.*
      - +.stun.*.*.*.*
      - +.stun.*.*.*.*.*
      - "*.n.n.srv.nintendo.net"
      - +.stun.playstation.net
      - xbox.*.*.microsoft.com
      - "*.*.xboxlive.com"
      - "*.msftncsi.com"
      - "*.msftconnecttest.com"
      - WORKGROUP
      - controlplane.tailscale.com
      - log.tailscale.io
  tun:
    enable: true
    stack: gvisor
    auto-route: true
    auto-detect-interface: true
    dns-hijack:
      - any:53
```

@gouku @xdays 几位不妨试试看，另外注意系统 HTTP 代理也是要关掉的。

以上测试基于：
* Clash for Windows v0.20.6
* Clash Core 2022.08.26 Premium (56523)
* Tailscale 1.24.2
* Tailscale 1.32.1
* Tailscale a6b77bcb008f14c8356b6618904b11b209c5e156
