### ISSUE TITLE
[Feature] 【proxy-groups】通过正则筛选的方式生成 group

### ISSUE THREAD

**Issue by krkrchan** [Dreamacro/clash#2252]
### Description

类似于 Quantumult X 中 [policy] 策略组，它能通过正则筛选的方式生成一个策略组：
```
static=policy-name-5, resource-tag-regex=^sample, server-tag-regex=^example, img-url=http://example.com/icon.png
筛选出订阅名含有example且节点名含有sample的节点，组成一个策略组，名为policy-name-5
```

希望 clash 的配置文件也能退出类似功能，生成group。如：
```
proxy-groups:
  - name: HK节点
    type: select
    filter: HK|港
```

但我也没很好的想到，怎么在 filter 里加入同时对订阅和节点名的筛选。
比如说【proxy-providers】我有三个订阅，名为A、B、C，我想筛选A和B里名字含有“HK”的节点。
希望有大佬可以优化一下。

**Comment by QiangF** [comment]
这个也许可以用脚本实现
https://github.com/felinae98/clashup/

**Comment by zam157** [comment]
`|`在YAML中有其他作用，要想表达带有`|`的字符需要带上引号，试试`filter: 'HK|港'`
详细内容可以看 #1511

**Comment by QiangF** [comment]
没搞明白，一般从网上下载一个机场yaml订阅文件，直接把那个文件放在这里吗？

    path: ./Proxies/AAA.yaml

**Comment by QiangF** [comment]
好像还是要处理一下啊

**Comment by zam157** [comment]
不好意思我没仔细看你的描述，filter是在proxy-groups中提供的

不知道这样能不能满足你的需求
```yaml
proxy-groups:
  - name: HK节点
    type: select
    use: [hk_B, hk_B]

proxy-providers:
  A:
    # ...
    path: ./providers/A.yaml
  B:
    # ...
    path: ./providers/B.yaml
  C:
    # ...
    path: ./providers/C.yaml
  hk_A:
    type: file
    filter: 'HK|港'
    path: ./providers/A.yaml
  hk_B:
    type: file
    filter: 'HK|港'
    path: ./providers/B.yaml
```

（不过这么写确实还是很麻烦😅
