### ISSUE TITLE
Start Tun interface error: ebpf redirect to run need to set `routing-mark`

### ISSUE THREAD

**Issue by cjwddtc** [Dreamacro/clash#2253]
### Verify steps

- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

Premium 2022.07.07

### What OS are you seeing the problem on?

Linux

### Clash config

```yaml
ipv6: false
mode: rule
log-level: info
allow-lan: true
external-controller: 0.0.0.0:9090
secret: '123456'
interface-name: enp1s0
bind-address: "*"
tun:
  enable: true
  stack: system
  device: utun
  auto-detect-interface: false
  dns-hijack:
  - udp://any:53

ebpf:
  redirect-to-tun:
    - enp1s0 

profile:   
  store-selected: true
  store-fake-ip: true
auto-redir:
  enable: true
  auto-route: true
```

### Clash log

```shell
ERRO[0000] Start Tun interface error: ebpf redirect to run need to set `routing-mark`
```

### Description

archlinux系统使用ebpf会报错

ERRO[0000] Start Tun interface error: ebpf redirect to run need to set `routing-mark`
