### ISSUE TITLE
[Bug] [Metadata PreHandle] error: fake DNS record

### ISSUE THREAD

**Issue by Rakau** [Dreamacro/clash#2259]
### Verify steps

- [ ]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

P核心 2022.07.07 及之后的DEV版本

### What OS are you seeing the problem on?

Linux

### Clash config

```yaml
bind-address: "*"
mode: rule
allow-lan: true
log-level: info
ipv6: false
udp: true
external-controller: 127.0.0.1:9090
external-ui: Dashboard
profile:
  store-fake-ip: true
tun:
    enable: true
    stack: system
    dns-hijack:
        - any:53
    auto-route: true
    auto-detect-interface: true
dns:
  enable: true
  listen: 0.0.0.0:65535
  ipv6: false
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter: ['+.lan', '+.local', '+.localhost', '+.msftncsi.com', 'msftncsi.com', 'msftconnecttest.com', '+.msftconnecttest.com', '+.io.mi.com', 'lens.l.google.com', 'stun.l.google.com']
  nameserver: ['https://doh.pub/dns-query', 'https://dns.alidns.com/dns-query', 'https://rubyfish.cn/dns-query', 'https://i.233py.com/dns-query']
  fallback: ['https://dns.google/dns-query', 'https://cloudflare-dns.com/dns-query', 'https://dns.233py.com/dns-query', 'https://a.passcloud.xyz/dns-query']
  fallback-filter:
    geoip: true
    geoip-code: CN

rule-providers:
x

proxy-groups:
x

rules:
x
```

### Clash log

```shell
time="2022-08-08T12:56:38Z" level=info msg="Start initial provider 日本"
time="2022-08-08T12:56:38Z" level=info msg="Start initial provider 韩国"
time="2022-08-08T12:56:38Z" level=info msg="Start initial provider 香港"
time="2022-08-08T12:56:38Z" level=info msg="Start initial provider 普通"
time="2022-08-08T12:56:38Z" level=info msg="Start initial provider 俄罗斯"
time="2022-08-08T12:56:38Z" level=info msg="Start initial provider 土耳其"
time="2022-08-08T12:56:38Z" level=info msg="Start initial provider 美国"
time="2022-08-08T12:56:38Z" level=info msg="Start initial provider 专线"
time="2022-08-08T12:56:38Z" level=info msg="Start initial provider x"
time="2022-08-08T12:56:38Z" level=info msg="Start initial provider 新加坡"
time="2022-08-08T12:56:38Z" level=info msg="Start initial compatible provider 🌠 游民星空"
time="2022-08-08T12:56:38Z" level=info msg="Start initial compatible provider 🥝 爱奇艺"
time="2022-08-08T12:56:38Z" level=info msg="Start initial compatible provider 🛰️ 微信FCM"
time="2022-08-08T12:56:38Z" level=info msg="Start initial compatible provider 🚫 全球拦截"
time="2022-08-08T12:56:38Z" level=info msg="Start initial compatible provider 🎮 新服游戏"
time="2022-08-08T12:56:38Z" level=info msg="Start initial compatible provider 🕹️ 任天堂平台"
time="2022-08-08T12:56:38Z" level=info msg="Start initial compatible provider 🛍️ Paypal地区"
time="2022-08-08T12:56:38Z" level=info msg="Start initial compatible provider 🧱 节点选择"
time="2022-08-08T12:56:38Z" level=info msg="Start initial compatible provider 🎮 日服游戏"
time="2022-08-08T12:56:38Z" level=info msg="Start initial compatible provider 🎯 全球直连"
time="2022-08-08T12:56:38Z" level=info msg="Start initial compatible provider 🕊️ 钉钉服务"
time="2022-08-08T12:56:38Z" level=info msg="Start initial compatible provider 🗞️ 电报信息"
time="2022-08-08T12:56:38Z" level=info msg="Start initial compatible provider 🚂 Steam下载区域"
time="2022-08-08T12:56:38Z" level=info msg="Start initial compatible provider 🎮 台服游戏"
time="2022-08-08T12:56:38Z" level=info msg="Start initial compatible provider Ⓜ️ 微软服务"
time="2022-08-08T12:56:38Z" level=info msg="Start initial compatible provider 🎮 港服游戏"
time="2022-08-08T12:56:38Z" level=info msg="Start initial compatible provider 🚂 Steam服务"
time="2022-08-08T12:56:38Z" level=info msg="Start initial compatible provider 🕹️ 索尼平台"
time="2022-08-08T12:56:38Z" level=info msg="Start initial compatible provider 🕹️ EA平台"
time="2022-08-08T12:56:38Z" level=info msg="Start initial compatible provider 🍎 苹果服务"
time="2022-08-08T12:56:38Z" level=info msg="Start initial compatible provider 🎮 韩服游戏"
time="2022-08-08T12:56:38Z" level=info msg="Start initial compatible provider 🛰️ 谷歌FCM"
time="2022-08-08T12:56:38Z" level=info msg="Start initial compatible provider 🎮 俄服游戏"
time="2022-08-08T12:56:38Z" level=info msg="Start initial compatible provider 🐟 漏网之鱼"
time="2022-08-08T12:56:38Z" level=info msg="Start initial compatible provider 📺 哔哩哔哩"
time="2022-08-08T12:56:38Z" level=info msg="Start initial compatible provider ⛏️ 主流矿池"
time="2022-08-08T12:56:38Z" level=info msg="Start initial compatible provider 📽️ 国外媒体"
time="2022-08-08T12:56:38Z" level=info msg="Start initial compatible provider ☁️ 数据下载"
time="2022-08-08T12:56:38Z" level=info msg="Start initial compatible provider 🕹️ xbox平台"
time="2022-08-08T12:56:38Z" level=info msg="Start initial rule provider applications"
time="2022-08-08T12:56:38Z" level=info msg="Start initial rule provider ruservergame"
time="2022-08-08T12:56:38Z" level=info msg="Start initial rule provider gamersky"
time="2022-08-08T12:56:38Z" level=info msg="Start initial rule provider dingtalk"
time="2022-08-08T12:56:38Z" level=info msg="Start initial rule provider bilibili"
time="2022-08-08T12:56:38Z" level=info msg="Start initial rule provider weixinfcm"
time="2022-08-08T12:56:38Z" level=info msg="Start initial rule provider ad"
time="2022-08-08T12:56:39Z" level=info msg="Start initial rule provider steamdl"
time="2022-08-08T12:56:39Z" level=info msg="Start initial rule provider download"
time="2022-08-08T12:56:39Z" level=info msg="Start initial rule provider globalmedia"
time="2022-08-08T12:56:39Z" level=info msg="Start initial rule provider krservergame"
time="2022-08-08T12:56:39Z" level=info msg="Start initial rule provider twservergame"
time="2022-08-08T12:56:39Z" level=info msg="Start initial rule provider nintendo"
time="2022-08-08T12:56:39Z" level=info msg="Start initial rule provider apple"
time="2022-08-08T12:56:39Z" level=info msg="Start initial rule provider gfw"
time="2022-08-08T12:56:39Z" level=info msg="Start initial rule provider sony"
time="2022-08-08T12:56:39Z" level=info msg="Start initial rule provider hkservergame"
time="2022-08-08T12:56:39Z" level=info msg="Start initial rule provider sgservergame"
time="2022-08-08T12:56:39Z" level=info msg="Start initial rule provider xbox"
time="2022-08-08T12:56:39Z" level=info msg="Start initial rule provider miningpool"
time="2022-08-08T12:56:39Z" level=info msg="Start initial rule provider paypal"
time="2022-08-08T12:56:39Z" level=info msg="Start initial rule provider iqiyi"
time="2022-08-08T12:56:39Z" level=info msg="Start initial rule provider ea"
time="2022-08-08T12:56:39Z" level=info msg="Start initial rule provider jpservergame"
time="2022-08-08T12:56:39Z" level=info msg="Start initial rule provider telegram"
time="2022-08-08T12:56:39Z" level=info msg="Start initial rule provider googlefcm"
time="2022-08-08T12:56:39Z" level=info msg="Start initial rule provider microsoft"
time="2022-08-08T12:56:39Z" level=info msg="Start initial rule provider steam"
time="2022-08-08T12:56:39Z" level=info msg="RESTful API listening at: 127.0.0.1:9090"
time="2022-08-08T12:56:39Z" level=info msg="DNS server listening at: [::]:65535"
time="2022-08-08T12:56:39Z" level=info msg="Tun Proxy listening at: utun(198.18.0.1)"
```

### Description

6.19版本之前都没有问题，使用环境是ARMv8的核，分别在安卓9的MIUI11的小米6和安卓11的MIUI12.5的红米 K30U复现，而在红米K50 MIUI13的安卓12和小米平板5P的MIUI13安卓12没有此问题。都是同样的配置文件，问题表现于yacd面板能加载，但无任何流量通过，clash核也是启动的
