### ISSUE TITLE
clash 的 vmess 会被墙，v2rayN 不会

### ISSUE THREAD

**Issue by hatiwowo** [Dreamacro/clash#2274]
### Verify steps

- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

1.94.0

### What OS are you seeing the problem on?

macOS

### Clash config

```yaml
# VMess
  - name: "v2ray"
    type: vmess
    server: rocket.********.fun
    port: 444
    uuid: **************************
    alterId: 0
    cipher: auto
    # udp: true
    tls: true
    skip-cert-verify: false
    # tls-hostname: rocket.*********.fun
    # network: ws
    # ws-path: /path
    # ws-headers: #这一行后面不要写东西
    #   Host: v2ray.com # 填写伪装域名
```

### Description

macos使用clashX，windows上使用docker部署都一样，代理可以使用，但用个可能十几分钟就会被墙，是vps服务器被墙，再使用其他代理工具也不行。（过两三分钟🈶️可以恢复）。但使用v2rayN进行代理就没出现过这样的问题。想问一下是哪里有区别？
