### ISSUE TITLE
开通代理后，如果设authentication，则YOUTUBE及INSTAGRAM等无法打开[Bug] 

### ISSUE THREAD

**Issue by my5123** [Dreamacro/clash#2285]
### Verify steps

- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

latest

### Clash config

```yaml
port: 7893
mixed-port: 7890 
socks-port: 7891 
authentication: 
  - 'XXX:XXXX'
redir-port: 7892 #   
allow-lan: true #                    
mode: rule
log-level: silent
external-controller: '0.0.0.0:9090'
```

### Description

开通代理后，如果设代理的authentication，IPHONE直接在WIFI选项里设http代理，则YOUTUBE及INSTAGRAM等无法打开（其中YOUTUBE可以打开视频列表，无法播放视频），需用小火箭等第三方代理APP设HTTP或SOCKS方能正常。

以上问题在不设置authentication的情况下完全正常。
