### ISSUE TITLE
[Bug] eBPF  HookEgress: program hook_egress: load program: invalid argument:  (BTF disabled)

### ISSUE THREAD

**Issue by 786259135** [Dreamacro/clash#2287]
### Verify steps

- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

Clash 2022.08.26-1-g8720ef5 linux amd64 with go1.19 Fri 26 Aug 2022 02:52:04 PM UTC

### What OS are you seeing the problem on?

Linux

### Clash config

```yaml
# Transparent proxy server port for Linux and macOS
#redir-port: 7892
#tproxy-port: 7893
#mixed-port: 7890
allow-lan: true
#log-level: info
#log-level: debug
#log-level: warning
#log-level: error
log-level: debug
external-controller: :9090
secret: ''
ipv6: false

external-ui: folder

routing-mark: 6666

dns:
  enable: true                   # set true to enable dns (default is false)
  ipv6: false                    # default is false
  listen: :53
  default-nameserver:
    - 114.114.114.114
    - 223.5.5.5
  enhanced-mode: fake-ip #redir-host      # or fake-ip
  fake-ip-range: 198.18.0.1/16
  use-hosts: true                # lookup hosts and return IP record
  fake-ip-filter:                # fake ip white domain list, aka Always Real IP
    - '*.lan'
    - localhost.ptlogin2.qq.com
  nameserver:
    - 223.5.5.5
    - 114.114.114.114
  fallback:
    - tls://dns.rubyfish.cn:853
    - https://1.1.1.1/dns-query
    - https://dns.google/dns-query

  fallback-filter:
    geoip: true                  # default
    geoip-code: CN
    ipcidr:                      # ips in these subnets will be considered polluted
      - 240.0.0.0/4
    domain:
      - '+.google.*'
      - '+.google.co.*'
      - '+.google.com.*'
      - '+.gstatic.com'
      - '+.facebook.com'
      - '+.youtube.com'
  
interface-name: ens192

auto-redir:
  enable: true
  auto-route: true

tun:
  enable: true
  stack: system
  dns-hijack:
    - any:53
  auto-route: true
  auto-detect-interface: true

ebpf:
  redirect-to-tun:
    - ens192

experimental:
  sniff-tls-sni: true

proxies:
  - name: "hk02"
    type: vmess
    server: 
    port: 
    uuid: 
    alterId: 0
    cipher: auto
    udp: true
    tls: true
    # skip-cert-verify: true
    servername: 
    network: ws


  - name: "ca01"
    type: vmess
    server: 
    port: 
    uuid: 
    alterId: 0
    cipher: auto
    udp: true
    tls: true

  - name: "cn"
    type: vmess
    server: 
    port: 
    uuid: 
    alterId: 0
    cipher: auto
    udp: true

proxy-groups:
  - name: "PROXY"
    type: fallback
    proxies:
      - hk02
      - ca01
#      - cn
    url: 'http://www.gstatic.com/generate_204'
    interval: 300

rule-providers:
  reject:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/reject.txt"
    path: ./ruleset/reject.yaml
    interval: 86400

  icloud:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/icloud.txt"
    path: ./ruleset/icloud.yaml
    interval: 86400

  apple:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/apple.txt"
    path: ./ruleset/apple.yaml
    interval: 86400

  google:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/google.txt"
    path: ./ruleset/google.yaml
    interval: 86400

  proxy:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/proxy.txt"
    path: ./ruleset/proxy.yaml
    interval: 86400

  direct:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/direct.txt"
    path: ./ruleset/direct.yaml
    interval: 86400

  private:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/private.txt"
    path: ./ruleset/private.yaml
    interval: 86400

  gfw:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/gfw.txt"
    path: ./ruleset/gfw.yaml
    interval: 86400

  greatfire:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/greatfire.txt"
    path: ./ruleset/greatfire.yaml
    interval: 86400

  tld-not-cn:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/tld-not-cn.txt"
    path: ./ruleset/tld-not-cn.yaml
    interval: 86400

  telegramcidr:
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/telegramcidr.txt"
    path: ./ruleset/telegramcidr.yaml
    interval: 86400

  cncidr:
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/cncidr.txt"
    path: ./ruleset/cncidr.yaml
    interval: 86400

  lancidr:
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/lancidr.txt"
    path: ./ruleset/lancidr.yaml
    interval: 86400

  applications:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/applications.txt"
    path: ./ruleset/applications.yaml
    interval: 86400

rules:
  - RULE-SET,reject,REJECT
  - RULE-SET,tld-not-cn,PROXY
  - RULE-SET,gfw,PROXY
  - RULE-SET,google,PROXY
  - RULE-SET,proxy,PROXY
  - RULE-SET,greatfire,DIRECT
  - RULE-SET,telegramcidr,PROXY
  - GEOIP,LAN,DIRECT
  - MATCH,DIRECT
```

### Clash log

```shell
21:46:30 INF [Config] initial compatible provider name=PROXY
21:46:30 INF [Config] initial rule provider name=proxy
21:46:30 INF [Config] initial rule provider name=private_server
21:46:30 INF [Config] initial rule provider name=private
21:46:30 INF [Config] initial rule provider name=lancidr
21:46:30 INF [Config] initial rule provider name=greatfire
21:46:30 INF [Config] initial rule provider name=google
21:46:30 INF [Config] initial rule provider name=direct
21:46:30 INF [Config] initial rule provider name=tld-not-cn
21:46:30 INF [Config] initial rule provider name=cncidr
21:46:30 INF [Config] initial rule provider name=private_domain
21:46:30 INF [Config] initial rule provider name=reject
21:46:31 INF [Config] initial rule provider name=applications
21:46:31 INF [Config] initial rule provider name=gfw
21:46:31 INF [Config] initial rule provider name=apple
21:46:31 INF [Config] initial rule provider name=telegramcidr
21:46:31 INF [Config] initial rule provider name=private_iptv_hz
21:46:31 INF [Config] initial rule provider name=private_ip
21:46:31 INF [Config] initial rule provider name=private_cf
21:46:31 INF [Config] initial rule provider name=icloud
21:46:31 INF [Config] initial rule provider name=private_pt
21:46:31 INF [Config] initial rule provider name=private_tg
21:46:31 INF [DNS] server listening addr=[::]:53
21:46:31 INF [API] listening addr=[::]:9090
21:46:31 ERR [Inbound] start failed error=field HookEgress: program hook_egress: load program: invalid argument:  (BTF disabled) type=TUN stackType=system inet=198.18.0.1/16
21:46:31 WRN [AutoRedir] auto set route failed error=netlink receive: file exists
21:46:31 INF [Inbound] Auto Redir listening iface=redir gateway=198.18.0.5
```

### Description

centos7.9 意外断电后，无法启用tun模式
