### ISSUE TITLE
[Bug] 开启tun模式连接数据库时，会重复建立连接，导致超过最大连接数并报错：unexpected EOF

### ISSUE THREAD

**Issue by Richard1ybb** [Dreamacro/clash#2289]
### Verify steps

- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

2022.08.26 premium

### Clash config

```yaml
#---------------------------------------------------#
## 更新：2022-08-29 09:37:20
#---------------------------------------------------#

port: 7890
socks-port: 7891
redir-port: 7892
allow-lan: false
mode: rule
log-level: silent
external-controller: '0.0.0.0:9090'
secret: ''
proxies:
  # socks5
  - name: "深信服socks"
    type: socks5
    server: 127.0.0.1
    port: 12000
    # username: username
    # password: password
    # tls: true
    # skip-cert-verify: true
    # udp: true

  # http
  - name: "深信服http"
    type: http
    server: 127.0.0.1
    port: 12001
    # username: username
    # password: password
    # tls: true # https
    # skip-cert-verify: true
    # sni: custom.com
  -
    name: 'V11 台湾 丨原生'
 
```

### Description

开启tun模式后无法连接数据库，但是浏览器能够通过代理正常访问。
查看日志时我发现：在连接mysql时，建立了很多重复的连接，是不是连接过多导致的这个问题（日志里显示最大的端口号到6xxxx）？

我们公司需要使用深信服进行内网的访问。我使用了[docker-easyconnect](https://github.com/Hagb/docker-easyconnect)将深信服运行在容器中，开放出来socks5端口用作访问。

在本机上，我使用clash-for-windows开始TUN模式代理本地的流量。开启tun后，浏览器，以及ping都能正常访问内网的服务，但是数据库链接不上。使用工具时返回timeout；代码连接时，返回[mysql] 2022/09/03 15:47:30 packets.go:36: unexpected EOF

clash-for-windows log
[2022-09-05-100806.log](https://github.com/Dreamacro/clash/files/9486303/2022-09-05-100806.log)
