### ISSUE TITLE
[Question] 使用 openvpn 时, 可以 ping 通, 但无法解析域名

### ISSUE THREAD

**Issue by moonheart** [Dreamacro/clash#2292]
### Verify steps

- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

Clash 2022.08.26 linux amd64 with go1.19 Fri Aug 26 13:42:29 UTC 2022

### What OS are you seeing the problem on?

Linux

### Clash config

```yaml
mixed-port: 7890
allow-lan: false
mode: rule
log-level: debug
ipv6: false
external-controller: 127.0.0.1:9090
external-ui: /home/moon/clash/yacd/
# external-ui: /srv/clash/clash-dashboard/
profile:
  store-selected: true
  store-fake-ip: true

routing-mark: 6666

# interface-name: wlp1s0
tun:
  enable: true
  stack: gvisor # system gvisor
  auto-route: true
  auto-detect-interface: true
  dns-hijack:
    - any:53

auto-redir:
  enable: true
  auto-route: true

dns:
  enable: true
  listen: 0.0.0.0:53
  ipv6: false
  default-nameserver:
    - 223.5.5.5
    - 223.6.6.6
  nameserver:
    - 223.5.5.5
    - 223.6.6.6
  enhanced-mode: fake-ip # fake-ip redir-host
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.lan'
    - '*.localdomain'
    - '*.example'
    - '*.invalid'
    - '*.localhost'
    - 'localhost'
    - '*.test'
    - '*.local'
    - '*.zzz.net'
    - '*.home.arpa'
    - '*.*.*.*.*.nip.io'
    - '*.*.*.*.*.*.nip.io'
    - router.asus.com
    - localhost.sec.qq.com
    - localhost.ptlogin2.qq.com
    - '+.msftconnecttest.com'
  nameserver-policy:
    '*.zzz.net': '10.2.1.1'

rules:
  - DOMAIN-SUFFIX,zzz.net,DIRECT
  - DOMAIN-SUFFIX,snapdrop.net,DIRECT
  - PROCESS-NAME,kdeconnectd,DIRECT
  # - RULE-SET,applications,DIRECT
  - DOMAIN,clash.razord.top,DIRECT
  - DOMAIN,yacd.haishan.me,DIRECT
  - RULE-SET,private,DIRECT
  - RULE-SET,icloud,DIRECT
  - RULE-SET,apple,DIRECT
  - RULE-SET,google,DIRECT
  - RULE-SET,proxy,PROXY
  # - RULE-SET,reject,REJECT
  - RULE-SET,direct,DIRECT
  - RULE-SET,lancidr,DIRECT
  - RULE-SET,cncidr,DIRECT
  - RULE-SET,telegramcidr,PROXY
  # - GEOIP,,DIRECT
  - GEOIP,CN,DIRECT
  - MATCH,PROXY
```

### Clash log

```shell
Sep 06 11:17:09 arch-tb14p clash[611575]: 11:17:09 DBG [TUN] hijack udp dns addr=10.2.1.1:53
Sep 06 11:17:14 arch-tb14p clash[611575]: 11:17:14 DBG [DNS Server] exchange failed error=all DNS requests failed, first error: read udp4 192.168.50.207:47460->10.2.1.1:53: i/o timeout question=;aaa.zzz.net.        IN         A
```

### 场景:
使用 openvpn 连接公司内网, 内网 dns 10.2.1.1, 内网域名 aaa.zzz.net

使用命令 `nslookup aaa.zzz.net 10.2.1.1`, 
连接 openvpn 并开启 clash 时, 无法解析域名, 关闭 clash 后可以解析;
不论是先启动 clash 还是 openvpn 都无法解析.

可以 ping 通 10.2.1.1, 也可以 ping 通其他内网 ip.

---
路由表
```
0.0.0.0/2 via 192.168.50.1 dev wlan0 
default via 192.168.50.1 dev wlan0 proto dhcp src 192.168.50.207 metric 600 
10.0.0.0/8 via 10.2.100.1 dev tunx 
10.2.100.0/24 dev tunx proto kernel scope link src 10.2.100.244 
64.0.0.0/2 via 192.168.50.1 dev wlan0 
128.0.0.0/2 via 192.168.50.1 dev wlan0 
172.17.0.0/16 dev docker0 proto kernel scope link src 172.17.0.1 
172.18.0.0/16 dev br-6c9eaed9e288 proto kernel scope link src 172.18.0.1 linkdown 
172.19.0.0/16 dev br-33e4904e97a7 proto kernel scope link src 172.19.0.1 linkdown 
172.20.0.0/16 dev br-2a25c32aee5e proto kernel scope link src 172.20.0.1 linkdown 
172.21.0.0/16 dev br-a58d659cadb3 proto kernel scope link src 172.21.0.1 
172.21.0.0/16 dev br-a58d659cadb3 proto kernel scope link src 172.21.0.1 metric 428 
172.22.0.0/16 dev br-b2550c871834 proto kernel scope link src 172.22.0.1 linkdown 
192.0.0.0/2 via 192.168.50.1 dev wlan0 
192.168.0.0/16 via 10.2.100.1 dev tunx 
192.168.50.0/24 dev wlan0 proto kernel scope link src 192.168.50.207 metric 600 
198.18.0.0/16 dev utun proto kernel scope link src 198.18.0.1 
198.18.0.0/16 dev redir proto kernel scope link src 198.18.0.5 
```

iptables filter
```
Chain INPUT (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain FORWARD (policy DROP 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination         
52083  143M DOCKER-USER  all  --  *      *       0.0.0.0/0            0.0.0.0/0           
52083  143M DOCKER-ISOLATION-STAGE-1  all  --  *      *       0.0.0.0/0            0.0.0.0/0           
26594  141M ACCEPT     all  --  *      docker0  0.0.0.0/0            0.0.0.0/0            ctstate RELATED,ESTABLISHED
    0     0 DOCKER     all  --  *      docker0  0.0.0.0/0            0.0.0.0/0           
25471 1480K ACCEPT     all  --  docker0 !docker0  0.0.0.0/0            0.0.0.0/0           
    0     0 ACCEPT     all  --  docker0 docker0  0.0.0.0/0            0.0.0.0/0           
    0     0 ACCEPT     all  --  *      br-6c9eaed9e288  0.0.0.0/0            0.0.0.0/0            ctstate RELATED,ESTABLISHED
    0     0 DOCKER     all  --  *      br-6c9eaed9e288  0.0.0.0/0            0.0.0.0/0           
    0     0 ACCEPT     all  --  br-6c9eaed9e288 !br-6c9eaed9e288  0.0.0.0/0            0.0.0.0/0           
    0     0 ACCEPT     all  --  br-6c9eaed9e288 br-6c9eaed9e288  0.0.0.0/0            0.0.0.0/0           
    0     0 ACCEPT     all  --  *      br-33e4904e97a7  0.0.0.0/0            0.0.0.0/0            ctstate RELATED,ESTABLISHED
    0     0 DOCKER     all  --  *      br-33e4904e97a7  0.0.0.0/0            0.0.0.0/0           
    0     0 ACCEPT     all  --  br-33e4904e97a7 !br-33e4904e97a7  0.0.0.0/0            0.0.0.0/0           
    0     0 ACCEPT     all  --  br-33e4904e97a7 br-33e4904e97a7  0.0.0.0/0            0.0.0.0/0           
    0     0 ACCEPT     all  --  *      br-2a25c32aee5e  0.0.0.0/0            0.0.0.0/0            ctstate RELATED,ESTABLISHED
    0     0 DOCKER     all  --  *      br-2a25c32aee5e  0.0.0.0/0            0.0.0.0/0           
    0     0 ACCEPT     all  --  br-2a25c32aee5e !br-2a25c32aee5e  0.0.0.0/0            0.0.0.0/0           
    0     0 ACCEPT     all  --  br-2a25c32aee5e br-2a25c32aee5e  0.0.0.0/0            0.0.0.0/0           
    0     0 ACCEPT     all  --  *      br-b2550c871834  0.0.0.0/0            0.0.0.0/0            ctstate RELATED,ESTABLISHED
    0     0 DOCKER     all  --  *      br-b2550c871834  0.0.0.0/0            0.0.0.0/0           
    0     0 ACCEPT     all  --  br-b2550c871834 !br-b2550c871834  0.0.0.0/0            0.0.0.0/0           
    0     0 ACCEPT     all  --  br-b2550c871834 br-b2550c871834  0.0.0.0/0            0.0.0.0/0           
    0     0 ACCEPT     all  --  *      br-a58d659cadb3  0.0.0.0/0            0.0.0.0/0            ctstate RELATED,ESTABLISHED
    0     0 DOCKER     all  --  *      br-a58d659cadb3  0.0.0.0/0            0.0.0.0/0           
   18  1542 ACCEPT     all  --  br-a58d659cadb3 !br-a58d659cadb3  0.0.0.0/0            0.0.0.0/0           
    0     0 ACCEPT     all  --  br-a58d659cadb3 br-a58d659cadb3  0.0.0.0/0            0.0.0.0/0           

Chain OUTPUT (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain DOCKER (6 references)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 ACCEPT     tcp  --  !br-a58d659cadb3 br-a58d659cadb3  0.0.0.0/0            172.21.0.2           tcp dpt:9443

Chain DOCKER-ISOLATION-STAGE-1 (1 references)
 pkts bytes target     prot opt in     out     source               destination         
25471 1480K DOCKER-ISOLATION-STAGE-2  all  --  docker0 !docker0  0.0.0.0/0            0.0.0.0/0           
    0     0 DOCKER-ISOLATION-STAGE-2  all  --  br-6c9eaed9e288 !br-6c9eaed9e288  0.0.0.0/0            0.0.0.0/0           
    0     0 DOCKER-ISOLATION-STAGE-2  all  --  br-33e4904e97a7 !br-33e4904e97a7  0.0.0.0/0            0.0.0.0/0           
    0     0 DOCKER-ISOLATION-STAGE-2  all  --  br-2a25c32aee5e !br-2a25c32aee5e  0.0.0.0/0            0.0.0.0/0           
    0     0 DOCKER-ISOLATION-STAGE-2  all  --  br-b2550c871834 !br-b2550c871834  0.0.0.0/0            0.0.0.0/0           
   18  1542 DOCKER-ISOLATION-STAGE-2  all  --  br-a58d659cadb3 !br-a58d659cadb3  0.0.0.0/0            0.0.0.0/0           
52083  143M RETURN     all  --  *      *       0.0.0.0/0            0.0.0.0/0           

Chain DOCKER-ISOLATION-STAGE-2 (6 references)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 DROP       all  --  *      docker0  0.0.0.0/0            0.0.0.0/0           
    0     0 DROP       all  --  *      br-6c9eaed9e288  0.0.0.0/0            0.0.0.0/0           
    0     0 DROP       all  --  *      br-33e4904e97a7  0.0.0.0/0            0.0.0.0/0           
    0     0 DROP       all  --  *      br-2a25c32aee5e  0.0.0.0/0            0.0.0.0/0           
    0     0 DROP       all  --  *      br-b2550c871834  0.0.0.0/0            0.0.0.0/0           
    0     0 DROP       all  --  *      br-a58d659cadb3  0.0.0.0/0            0.0.0.0/0           
25489 1482K RETURN     all  --  *      *       0.0.0.0/0            0.0.0.0/0           

Chain DOCKER-USER (1 references)
 pkts bytes target     prot opt in     out     source               destination         
52083  143M RETURN     all  --  *      *       0.0.0.0/0            0.0.0.0/0   
```

iptables nat
```
Chain PREROUTING (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination         
 5903 1969K DOCKER     all  --  *      *       0.0.0.0/0            0.0.0.0/0            ADDRTYPE match dst-type LOCAL

Chain INPUT (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain OUTPUT (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination         
 3363  201K DOCKER     all  --  *      *       0.0.0.0/0           !127.0.0.0/8          ADDRTYPE match dst-type LOCAL

Chain POSTROUTING (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination         
  276 17458 MASQUERADE  all  --  *      !docker0  172.17.0.0/16        0.0.0.0/0           
    1    60 MASQUERADE  all  --  *      !br-6c9eaed9e288  172.18.0.0/16        0.0.0.0/0           
    1    60 MASQUERADE  all  --  *      !br-33e4904e97a7  172.19.0.0/16        0.0.0.0/0           
    1    60 MASQUERADE  all  --  *      !br-2a25c32aee5e  172.20.0.0/16        0.0.0.0/0           
    1    60 MASQUERADE  all  --  *      !br-b2550c871834  172.22.0.0/16        0.0.0.0/0           
    1    60 MASQUERADE  all  --  *      !br-a58d659cadb3  172.21.0.0/16        0.0.0.0/0           
    0     0 MASQUERADE  tcp  --  *      *       172.21.0.2           172.21.0.2           tcp dpt:9443

Chain DOCKER (2 references)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 RETURN     all  --  docker0 *       0.0.0.0/0            0.0.0.0/0           
    0     0 RETURN     all  --  br-6c9eaed9e288 *       0.0.0.0/0            0.0.0.0/0           
    0     0 RETURN     all  --  br-33e4904e97a7 *       0.0.0.0/0            0.0.0.0/0           
    0     0 RETURN     all  --  br-2a25c32aee5e *       0.0.0.0/0            0.0.0.0/0           
    0     0 RETURN     all  --  br-b2550c871834 *       0.0.0.0/0            0.0.0.0/0           
    0     0 RETURN     all  --  br-a58d659cadb3 *       0.0.0.0/0            0.0.0.0/0           
    0     0 DNAT       tcp  --  !br-a58d659cadb3 *       0.0.0.0/0            0.0.0.0/0            tcp dpt:9443 to:172.21.0.2:9443
```

openvpn 配置
```
client
dev-type tun
dev tunx
proto udp
tun-mtu 1400
cipher AES-128-CBC
comp-lzo
remote xxxxxxx.xxx.com 4873
resolv-retry infinite
nobind
persist-key
persist-tun
verb 3
auth-user-pass
script-security 2 

route 0.0.0.0 192.0.0.0 net_gateway
route 64.0.0.0 192.0.0.0 net_gateway
route 128.0.0.0 192.0.0.0 net_gateway
route 192.0.0.0 192.0.0.0 net_gateway

dhcp-option DNS 10.2.1.1

<ca>
-----BEGIN CERTIFICATE-----
xxxxx
-----END CERTIFICATE-----
</ca>
```

**Comment by Dreamacro** [comment]
把 vpn dns 加到 clash 的配置里

**Comment by moonheart** [comment]
@Dreamacro 我在 `rules` 中添加了一条 `  - IP-CIDR,10.2.1.1/32,DIRECT` 还是不行

**Comment by Dreamacro** [comment]
加到 nameserver 里不是加到规则上

**Comment by moonheart** [comment]
我尝试加到 nameserver 也是不行,  日志中都是 resolve failed error=all DNS requests failed, first error: read udp4 192.168.50.207:44581->10.2.1.1:53: i/o timeout

**Comment by dageyun** [comment]
[github.com](https://www.dageyun2.com/#/register?code=XE4fSTsg) 大哥云vpn速度快质量好免费试用一天

**Comment by dageyun** [comment]
https://www.dageyun2.com/#/register?code=XE4fSTsg

**Comment by Dreamacro** [comment]
@moonheart dns 可以指定网卡

**Comment by moonheart** [comment]
@Dreamacro 我没有在 wiki 里面找到关于 dns 指定网卡的信息, 可以麻烦说一下怎么配置吗?

**Comment by olliecheung** [comment]
> @Dreamacro 我没有在 wiki 里面找到关于 dns 指定网卡的信息, 可以麻烦说一下怎么配置吗?

https://github.com/Dreamacro/clash/wiki/Configuration

**Comment by moonheart** [comment]
@olliecheung 谢谢, 我之前没有看仔细, 似乎是可以在后面使用 `#` 来指定网卡?
我使用如下配置没法解析, 是这样配置的吗
```
dns:
  enable: true
  listen: 0.0.0.0:53
  ipv6: false
  default-nameserver:
    - 223.5.5.5
    - 223.6.6.6
  nameserver:
    - 223.5.5.5
    - 223.6.6.6
    - 10.2.1.1#tunx  <--- added this
  enhanced-mode: fake-ip # fake-ip redir-host
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.lan'
    - '*.localdomain'
    - '*.example'
    - '*.invalid'
    - '*.localhost'
    - 'localhost'
    - '*.test'
    - '*.local'
    - '*.zzz.net'
    - '*.home.arpa'
    - '*.*.*.*.*.nip.io'
    - '*.*.*.*.*.*.nip.io'
    - router.asus.com
    - localhost.sec.qq.com
    - localhost.ptlogin2.qq.com
    - '+.msftconnecttest.com'
  nameserver-policy:
    '*.zzz.net': '10.2.1.1'
```
