### ISSUE TITLE
[Bug] 200 error

### ISSUE THREAD

**Issue by Gomememe** [Dreamacro/clash#2296]
### Verify steps

- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

v1.10

### What OS are you seeing the problem on?

Linux

### Clash config

```yaml
port: 8888
socks-port: 1888
allow-lan: true
bind-address: '*'
mode: rule
log-level: debug
ipv6: true

proxies:
  # vmess
  # cipher support auto/aes-128-gcm/chacha20-poly1305/none
  - name: "vmess"
    type: vmess
    server: niu.sample.com
    port: 2087
    uuid: 8xxxx5-b291-73e8-0xx6-ccxxxx2cb855
    alterId: 0
    cipher: auto
    # udp: true
    tls: true
    skip-cert-verify: true
    network: ws
    ws-path: /yourpath/
    #ws-headers:
    #Host: v2ray.com



proxy-groups:
  - name: "vproxy" 
    type: select
    proxies:
      - vmess

rules:

  - IP-CIDR,127.0.0.0/8,DIRECT
  - MATCH,vproxy
```

### Clash log

```shell
DEBU[0198] [DNS] android.googleapis.com --> 172.217.160.74 
DEBU[0198] [DNS] android.googleapis.com --> 172.217.160.74 
WARN[0199] [TCP] dial vproxy (match Match/) to android.googleapis.com:443 error: dial niu.sample.com:2087 error: 200 OK 
WARN[0199] [TCP] dial vproxy (match Match/) to android.googleapis.com:443 error: dial niu.sample.com:2087 error: 200 OK
```

### Description

debian 11系统

nginx反向代理模式，

客户端使用sock5，但是不行。 
[config.zip](https://github.com/Dreamacro/clash/files/9525214/config.zip)
