### ISSUE TITLE
[Bug] 如何设置TUN + Internet Connection Sharing (ICS)?

### ISSUE THREAD

**Issue by qiangxinglin** [Dreamacro/clash#2298]
### Verify steps

- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

Premium 2022.08.26

### What OS are you seeing the problem on?

Windows

### Clash config

```yaml
dns:
  enable: true
  enhanced-mode: fake-ip
  nameserver:
    - 10.xxx.xxx.xxx // local dns ip

tun: 
  enable: true
  stack: gvisor
  auto-route: true
  interface-name: eth1
  dns-hijack:
    - 198.18.0.2:53

proxy-groups:
  -name: INNER
  type: select
  interface-name: eth1
  proxies:
    - DIRECT

rules:
  - IP-CIDR,10.0.0.0/8,INNER,no-resolve
  - MATCH, PROXY
```

### Clash log

```shell
[UDP] dial INNER (match IPCIDR/10.0.0.0/8) to 10.xxx.xxx.xxx:53 error:listen udp :0: bind: An attempt was made to access a socket in a way forbidden by its access permissions.
```

### Description

网络拓扑

PC1
- eth1 -- 通过某认证, 连接 10.xxx.xxx.0/24网段, DNS 10.xxx.xxx.xxx, 在NIC`属性 -> 共享` 页面开启`Internet 连接共享`, 家庭网络连接选择 `eth0`
- eth0 -- 网线连接PC2, 设置固定IP 192.168.137.1, DNS 同上 10.xxx.xxx.xxx

PC2
- eth2 -- 网线连接PC1 eth0, 设置固定IP 192.168.137.3, 默认网关 192.168.137.1, DNS同上 10.xxx.xxx.xxx

目标:
- PC2通过PC1的网卡接入10.0.0.0/8网段 (NAT)
- 在PC1上开启clash, 相当于PC2的透明网关

注:
- Internet 连接共享已确认可以连接, 并且在PC2上开启clash也没问题, 在PC1上开启TUN模式clash会如上log错误, 目测是 `0` 端口占用问题
- 3个网卡以及clash config里设置的DNS均为同一ip
