### ISSUE TITLE
[Bug] FAKE-IP TUN模式 只能处理域名请求

### ISSUE THREAD

**Issue by 412999826** [Dreamacro/clash#2302]
### Verify steps

- [x]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

Premium 2022.08.26

### What OS are you seeing the problem on?

Linux

### Clash config

```yaml
redir-port: 7892
allow-lan: true
log-level: info
external-controller: 0.0.0.0:9090
external-ui: clash-ui
dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:1053
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  nameserver:
    - 114.114.114.114
    - https://223.5.5.5/dns-query
  fallback:
    - 8.8.8.8
    - tls://8.8.4.4:853
  fallback-filter:
    geoip: true
    geoip-code: CN
tun:
  enable: true
  stack: system # or gvisor
  dns-hijack:
    - any:53
    - tcp://any:53
  auto-route: true
  auto-detect-interface: true
```

### Description

采用fake-ip的tun模式之后，只能代理域名的请求，无法处理ip直连的请求。
通过clash dashboard查看，ip直连的请求都没有经过clash，只有域名类经过，导致tg之类的应用无法代理。
