### ISSUE TITLE
[Bug] 自建的websocket+tls+web节点，clash无法使用，TCP连接错误

### ISSUE THREAD

**Issue by jksherk** [Dreamacro/clash#2306]
### Verify steps

- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

1.11.8

### What OS are you seeing the problem on?

Linux

### Clash config

```yaml
# vmess
  # cipher support auto/aes-128-gcm/chacha20-poly1305/none
  - name: "v2ray"
    type: vmess
    server: 154.27.19.121
    port: 443
    uuid: 105ff30e-310b-19ad-a361-0712ad111302
    alterId: 0
    cipher: auto
    # udp: true
    tls: true
    skip-cert-verify: true
    #servername: www.dfdfdgfdgfdgfdgdfgfd.quest
    #ws-opts:
    network: ws
    path: /GWFthbf
    #headers:
    Host: www.dfdfdgfdgfdgfdgdfgfd.quest
     #  max-early-data: 2048
     #  early-data-header-name: Sec-WebSocket-Protocol
```

### Clash log

```shell
WARN[0011] [TCP] dial PROXY (match DomainKeyword/google) to optimizationguide-pa.googleapis.com:443 error: dial 154.27.19.121:443 error: 200 OK
WARN[0012] [TCP] dial PROXY (match DomainKeyword/google) to optimizationguide-pa.googleapis.com:443 error: dial 154.27.19.121:443 error: 200 OK
WARN[0012] [TCP] dial PROXY (match DomainKeyword/google) to www.google.com:443 error: dial 154.27.19.121:443 error: 200 OK
```

### Description

最近我的机场失效，索性自建一个websocket+tls+web，追求稳定性，
建好后，windows MAC上，v2rayN能正常连接使用，可是clash就偏偏无法使用，而我平时使用linux时间多，clash是刚需
在windows Linux上测试过，clash设置贴上来了，运行就报错，无法访问外网
在配置文件里，我把自建的节点，换成机场节点（非ws+tls）就没问题可以访问外网
而我把 networks: ws 注销了，也不会报错，当然也无法访问外网
研究了几天了，一直没有解决，还望各位大大赐教！
