### ISSUE TITLE
[Bug] TUN模式疑似和远程软件(向日葵、Todesk)存在兼容性问题。

### ISSUE THREAD

**Issue by fuchanghao** [Dreamacro/clash#2307]
### Verify steps

- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

v2022.08.26 Premium

### What OS are you seeing the problem on?

Windows

### Clash config

```yaml
TUN配置文件如下：


dns:
  enable: true
  enhanced-mode: fake-ip
  nameserver:
    - https://1.1.1.1/dns-query
    - https://dns.google/dns-query
    - https://dns.alidns.com/dns-query
  fallback:
    - https://1.0.0.1/dns-query
  fake-ip-filter:
    - +.stun.*.*
    - +.stun.*.*.*
    - +.stun.*.*.*.*
    - +.stun.*.*.*.*.*
    - "*.n.n.srv.nintendo.net"
    - +.stun.playstation.net
    - xbox.*.*.microsoft.com
    - "*.*.xboxlive.com"
    - "*.msftncsi.com"
    - "*.msftconnecttest.com"
    - WORKGROUP
tun:
  enable: true
  stack: gvisor
  auto-route: true
  auto-detect-interface: true
  dns-hijack:
    - any:53
```
```


### Clash log

_No response_

### Description

已知远程桌面在进行文件传输的时候，如果两台电脑为内网，会直接用内网传输，不经过远程服务器

设置如下：
1.远程软件均设置“不使用代理”。
2.关闭Clash软件，使用向日葵等软件进行文件传输，走的是内网传输。
3.被控电脑均开启TUN模式，CLASH规则设置为全局DIRECT，进行文件传输，走的是外网传输，向日葵等软件无法识别被连主机为同一内网下的机器。主控电脑均开启TUN模式，CLASH规则设置为全局DIRECT，进行文件传输，还是走的是外网传输。
4.不知道具体是什么原理导致TUN模式劫持DNS之后内网识别出现问题了。
