### ISSUE TITLE
[Bug] OpenWrt 重启PPP后fallback组解析失败

### ISSUE THREAD

**Issue by luckyyyyy** [Dreamacro/clash#2313]
### Clash version

Premium 2022.08.26

### What OS are you seeing the problem on?

OpenWrt

### Clash config

```yaml
# 配置非常简单，不加什么魔法。

mixed-port: 7890
redir-port: 7892
authentication:
  - ''
allow-lan: true
mode: Rule
log-level: info
ipv6: false
external-controller: ':9999'
external-ui: ui
secret: 123456
tun:
  enable: false
dns:
  enable: true
  ipv6: false
  listen: '0.0.0.0:1053'
  use-hosts: true
  enhanced-mode: redir-host
  default-nameserver:
    - 114.114.114.114
    - 223.5.5.5
  nameserver:
    - 202.101.172.35
    - 202.101.172.47
    - 119.28.28.28
    - 223.5.5.5
  fallback:
    - 'tls://1.1.1.1:853'
    - 'tls://8.8.8.8:853'
  fallback-filter:
    geoip: true
hosts:
  localhost: 127.0.0.1
profile:
  store-selected: true
  store-fake-ip: true
  tracing: true
```

### Clash log

```shell
如果是 https 会报告 
All DNS requests failed, first error: context deadline exceeded 
如果是 TCP 会报告
i/o error
客户端直接使用 dig -p 1053 无任何转发 无任何魔法

```

### Description

重启ppp接口后随机出现，而且只有fallback的dns会出现这个问题，nameserver的并不会，所以国内解析全部正常。
重启PPP后，解析成功的网站打开全部正常(节点正常)，只有DNS解析会出现这个问题。

我猜是和接口有关系，但为什么会导致fallback失败，而nameserver并不会有问题？

相关 #899
