### ISSUE TITLE
[Question] 同一主机下，不同的docker容器走不同的透明代理

### ISSUE THREAD

**Issue by nzmd** [Dreamacro/clash#2315]
### Verify steps

- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version
Premium clash-linux-amd64-2022.08.26

### What OS are you seeing the problem on?

Linux

### Clash config

```yaml
mixed-port: 7890
log-level: debug
dns:
  enable: true
  listen: 0.0.0.0:53
  enhanced-mode: fake-ip
  nameserver:
    - 114.114.114.114
  fallback:
    - 8.8.8.8
tun:
  enable: true
  stack: system # or gvisor
  dns-hijack:
    - 8.8.8.8:53
    - tcp://8.8.8.8:53
    - any:53
    - tcp://any:53
  auto-route: true # auto set global route
  auto-detect-interface: true # conflict with interface-name
proxies:
  - name: "jx-home-socks5"
    type: socks5
    server: xx.xxx.xxx.104
    port: 7001
  - name: "hk-myServer-socks5"
    type: socks5
    server: 192.168.50.xx
    port: 10808
proxy-groups:
  - name: Proxy
    type: select
    proxies:
      - jx-home-socks5
      - hk-myServer-socks5
rules:
  - DOMAIN-KEYWORD,ident,DIRECT
  - SRC-IP-CIDR,172.17.0.1/16,DIRECT
  - MATCH,Proxy
```

### Description

在一台linux主机上 使用clash并开启Tun模式这台主机上还有多个docker容器服务，

有什么好的办法可以使不同docker容器全局(透明代理)走指定的不同的代理

使用 iptables 吗？
