### ISSUE TITLE
[Bug] "Trojan"+"grpc"+"security none" not working

### ISSUE THREAD

**Issue by thisismzm** [Dreamacro/clash#2337]
### Verify steps

- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

1.11.8

### What OS are you seeing the problem on?

Linux

### Clash config

```yaml
mixed-port: 1083
allow-lan: false
bind-address: '*'
mode: rule
log-level: debug
ipv6: false
proxies:
  - name: trojan
    type: trojan
    server: xxxxxxxxx
    port: 80
    password: "xxxxxxxxxxx"
    network: grpc
    grpc-opts:
      grpc-service-name: "xxxxxxxxxxxx"
    udp: true
    tls: false
    alpn:
      - h2
rules:
  - GEOIP,IR,DIRECT
  - IP-CIDR,127.0.0.0/8,DIRECT
  - DOMAIN-SUFFIX,ad.com,REJECT
  - MATCH,trojan
```

### Clash log

```shell
error: tls: first record does not look like a TLS handshake
```

### Description

I am running a trojan server with grpc and security none. I can connect to it by v2ray-core but I cannot connect by clash because it doesn't support `tls: false` for trojan.
