### ISSUE TITLE
redir 不支持 UDP 转发

### ISSUE THREAD

**Issue by winguse** [Dreamacro/clash#234]
clash config.yml

```yaml
log-level: debug
redir-port: 7892
allow-lan: true
mode: Rule
Proxy:
- name: Proxy
  type: vmess
  server: <domain.com>
  port: 443
  uuid: <uuid>
  alterId: <alterId>
  cipher: <cipher>
  network: ws
  ws-path: <ws-path>
  tls: true
  udp: true
Rule:
- MATCH,Proxy
```

iptables / ipset:

```shell
ipset -N setmefree iphash

# tcp redirect
iptables -t nat -I OUTPUT -p tcp -m set --match-set setmefree dst -j REDIRECT --to-port 7892
iptables -t nat -I PREROUTING -p tcp -m set --match-set setmefree dst -j REDIRECT --to-port 7892

# udp redirect
ip route add local default dev lo table 100
ip rule add fwmark 1 lookup 100
iptables -t mangle -I PREROUTING -p udp -m set --match-set setmefree dst -j TPROXY --on-port 7892 --tproxy-mark 0x01/0x01
iptables -t mangle -I OUTPUT -p udp -m set --match-set setmefree dst -j MARK --set-mark 1
```

在 ipset 里面添加一个地址：
```
ipset add setmefree 8.8.8.8
```

1. `dig www.google.com @8.8.8.8` clash 日志没有任何反应。
2. `dig www.google.com @8.8.8.8 +vc` clash 日志会显示相关连接，工作正常。

同样对配置使用 v2ray 是没问题的，所以是 clash 对 udp redir 支持有问题？或者是，我姿势不正确？

Note: v2ray 接受 udp 的时候是需要 sudo 的，当然这里 clash 即使 sudo 也不成功。
