### ISSUE TITLE
[Bug] 无法访问透明网关上的 docker 服务

### ISSUE THREAD

**Issue by ymj0424** [Dreamacro/clash#2342]
### Verify steps

- [ ]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

v1.11.8

### What OS are you seeing the problem on?

Linux

### Clash config

```yaml
port: 7890
redir-port: 7892
mode: rule
allow-lan: true
bind-address: '*'
log-level: debug
ipv6: false
routing-mark: 6666
interface-name: eno1
dns:
  enable: true
  listen: 0.0.0.0:5353
  default-nameserver:
    - 223.5.5.5
    - 8.8.8.8
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  nameserver:
    - 223.5.5.5
    - 114.114.114.114 
  fallback:
    - tcp://1.1.1.1
proxies:
...
proxy-groups:
...
rules:
  - GEOIP,CN,DIRECT
  - MATCH,proxy
```

### Clash log

```shell
clash  | time="2022-10-11T01:35:40Z" level=warning msg="[TCP] dial DIRECT (match RuleSet(custom_direct)) to 192.168.50.17:12964 error: dial tcp4 192.168.50.1
:12964: connect: connection refused"
```

### Description

clash 作为透明网关搭建在内网的一台 NAS 上，NAS 上部署了其他 docker 服务，iptables 配置如下：
```
iptables -t nat -N CLASH
iptables -t nat -A CLASH  -p tcp -j RETURN -m mark --mark 6666
iptables -t nat -s 192.168.50.149 -p tcp -j REDIRECT --to-ports 7892
iptables -t nat -A PREROUTING -p tcp -j CLASH
```
NAS 的内网地址是 `192.168.50.17`，`192.168.50.149` 是内网中的一台电脑，电脑已经将网关指向了 NAS。
上述配置电脑可以正常访问外网，但无法访问 NAS 上的 docker 服务。
经过排查，发现经过 clash 的流量，在 iptables DNAT 之后，会 routing 到 `eno1`（出口网卡），而不是 `br-6f47e51875d8`（docker 服务的网桥）
虽然可以通过添加 iptables 规则，让访问局域网的流量不走 clash，但在以下场景还是无法避免这个问题。
公司的电脑不能装 clash，为了使用代理，我通过 ssh tunnel 将 clash 的 http port foward 到本地，浏览器再通过 http 代理上网。这种情况下，流量一定会经过 clash，无法通过 iptables 规避此问题。
