### ISSUE TITLE
[Bug] tun模式下rule代理UDP始终直连

### ISSUE THREAD

**Issue by fsdfkefs** [Dreamacro/clash#2343]
### Verify steps

- [ ]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

0.20.5

### What OS are you seeing the problem on?

Windows

### Clash config

```yaml
port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
  - {
      name: 
      server: 
      port: 443,
      type: trojan,
      password:
      sni:
      skip-cert-verify: false,
    }
proxy-groups:
  - name: 🚀 节点选择
    type: select
    proxies:
      - ♻️ 自动选择
      - DIRECT
  - name: ♻️ 自动选择
    type: url-test
    url: http://www.gstatic.com/generate_204
    interval: 300
    tolerance: 50
    proxies:
  
rules:
 - DST-PORT,22101,📲 电报信息
 - DST-PORT,22102,📲 电报信息
 - SRC-PORT,22101,📲 电报信息
 - SRC-PORT,22102,📲 电报信息
 - DOMAIN-SUFFIX,acl4.ssr,🎯 全球直连
```

### Description

我设置了 22101 端口走代理节点，

在 tun 模式 rulu 规则下，如果是tcp数据请求 22101 端口，是正常走代理的，但udp数据始终直连。

如果切换到global模式走代理，这时udp数据是可以走代理的。

想问一下应该怎样配置才能使得udp数据在rulu规则下也走代理呢
