### ISSUE TITLE
[Bug] 开启tun模式chrome不能正常使用 edge ie可以

### ISSUE THREAD

**Issue by seenline** [Dreamacro/clash#2347]
### Verify steps

- [ ]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [x]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [x]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

v 0.19.6

### What OS are you seeing the problem on?

Windows

### Clash config

```yaml
mixed-port: 7890
allow-lan: true
log-level: info
external-controller: 127.0.0.1:14939
secret: ''
ipv6: true

# Will be ignored after profile selection
proxies:
  - name: Debug
    type: socks5
    server: 127.0.0.1
    port: 1080
proxy-groups:
  - name: Proxy
    type: select
    proxies:
      - Debug
rules:
  - 'MATCH,DIRECT'
```

### Description

# 开启tun模式chrome不能正常使用

我在使用过程中发现开启tun mode后发现chrome不能正常使用，没有开启代理相关插件，但是edge等其他浏览器可以正常使用代理。在打开system proxy（系统代理）后chrome正常，困惑tun mode式下不就相当于系统代理么，求解
