### ISSUE TITLE
[Bug]  tun模式下的doh解析问题

### ISSUE THREAD

**Issue by ailinal** [Dreamacro/clash#2352]
### Verify steps

- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

1.11.8

### What OS are you seeing the problem on?

Windows

### Clash config

```yaml
mixed-port: 7890
allow-lan: true
bind-address: "*"
mode: rule
log-level: info
external-controller: 127.0.0.1:9090
dns:
  enable: true
  ipv6: false
  default-nameserver:
    - 223.5.5.5
    - 119.29.29.29
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  use-hosts: true
  nameserver:
    - https://doh.pub/dns-query
    - https://dns.alidns.com/dns-query
  fallback:
    - https://dns.cloudflare.com/dns-query
  fallback-filter:
    geoip: true
    ipcidr:
      - 240.0.0.0/4
```

### Clash log

```shell
·
```

### Description

在配置dns 通过doh的方式中，如果doh服务器是以域名的形式配置，在抓包后发现，doh服务器的域名会通过114.114.114.114和8.8.8.8去解析。但是我的网络环境会拦截掉所有的dns请求，只允许使用内网的dns服务器解析。所以doh服务器的域名无法被解析成功，接着就导致无法连接到doh执行其他的域名解析。
如果doh服务器的域名的域名解析是使用系统通过dhcp分配的dns服务器进行的就不会有这个问题了。
不知道这算不算个bug。
