### ISSUE TITLE
[Bug] premium在centos7.9上无法运行

### ISSUE THREAD

**Issue by Wrandz** [Dreamacro/clash#2354]
### Verify steps

- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

20220826及以后

### What OS are you seeing the problem on?

Linux

### Clash config

```yaml
mixed-port: 7890
allow-lan: true
mode: Rule
log-level: info
external-controller : 0.0.0.0:9090
external-ui : /root/clashui

proxy-providers:
  niuniu:
    type: http
    url: ""
    interval: 3600
    path: ./niuniu.yaml
    health-check:
      enable: true
      interval: 600
      # lazy: true
      url: http://www.gstatic.com/generate_204
  yunshen:
    type: http
    url: ""
    interval: 3600
    path: ./yunshen.yaml
    health-check:
      enable: true
      interval: 600
      # lazy: true
      url: http://www.gstatic.com/generate_204
  xinhua:
    type: http
    url: ""
    interval: 3600
    path: ./xinhua.yaml
    health-check:
      enable: true
      interval: 600
      # lazy: true
      url: http://www.gstatic.com/generate_204

proxy-groups:
   
  - name: ♻️ 自动选择
    type: url-test
    url: http://www.gstatic.com/generate_204
    interval: 300
    tolerance: 50
    use:
      - niuniu
      - yunshen
      - xinhua


rules:
 - GEOIP,CN,DIRECT
 - MATCH,♻️ 自动选择
```

### Clash log

```shell
没有生成就退出了
```

### Description

premium的20220826及latest版本，在我的centos7.9上面，一运行就出现下面的情况
![Snipaste_2022-10-20_18-36-57](https://user-images.githubusercontent.com/70056470/196933766-5dda7e04-149f-4d51-bbe6-b1293508f7d3.png)
没有报错就退出了，我试了一下20220707的版本，是可以正常运行的。
普通版本也可以正常运行。
