### ISSUE TITLE
[Bug] Source IP shows Fake-IP rather than the real one.

### ISSUE THREAD

**Issue by wmyfelix** [Dreamacro/clash#2360]
### Verify steps

- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

Clash 2022.08.26 linux amd64 with go1.19 Fri Aug 26 13:42:29 UTC 2022

### What OS are you seeing the problem on?

Linux

### Clash config

```yaml
port: 8888
socks-port: 8889
mixed-port: 8899
allow-lan: true
mode: Rule
log-level: info
external-controller: 127.0.0.1:6170
experimental:
  ignore-resolve-fail: true
tun:
  enable: true
  stack: system
  auto-route: false
  auto-detect-interface: false
  dns-hijack:
  - tcp://any:53
external-ui: "/usr/share/yacd"
profile:
  store-selected: true
  store-fake-ip: true
dns:
  enable: true
  ipv6: true
  listen: 0.0.0.0:53
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  default-nameserver:
    - 119.29.29.29
    - 223.5.5.5
    - 223.6.6.6
    - 1.2.4.8
    - 192.168.0.1
  nameserver:
    - https://doh.pub/dns-query
    - https://dns.alidns.com/dns-query
```

### Clash log

```shell
20:11:06 INF [TCP] connected lAddr=198.18.0.1:55862 rAddr=github.githubassets.com:443 mode=rule rule=RuleSet(Global) proxy=
```

### Description

![Screenshot from 2022-10-23 20-13-28](https://user-images.githubusercontent.com/58871134/197391460-2d5a7c11-69d3-433d-ba42-220f30ce3f82.png)
