### ISSUE TITLE
[Bug] TUN下curl、ssh和python无DNS泄露，但即使命中域名规则或开全局模式，Chrome、Edge和Firefox浏览器都泄露，而代理模式下浏览器都不泄露

### ISSUE THREAD

**Issue by slusludy** [Dreamacro/clash#2367]
### Verify steps

- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

premium 2022.08.26 windows amd64v3

### What OS are you seeing the problem on?

Windows

### Clash config

```yaml
tun:
  enable: true
  dns-hijack:
    - 198.18.0.2:53
  stack: gvisor
  auto-route: true
  auto-detect-interface: true
dns:
  enable: true
  ipv6: true
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.0/16
  fake-ip-filter:
    - localhost.ptlogin2.qq.com
  default-nameserver:
    - 223.6.6.6
  nameserver:
    - 119.29.29.29
proxies:
  - {
      name: "vmess",
      server: xxxx,
      port: 443,
      type: vmess,
      uuid: xxxx,
      alterId: 0,
      udp: true
      tls: true,
      cipher: auto,
      skip-cert-verify: false,
      network: ws,
      ws-opts: {
        path: /xxxx,
        headers: {
          Host: xxxx
        }
      },
    }
```

### Clash log

```shell
DBG [TCP] accept connection lAddr=198.18.0.1:9775 rAddr=www.google.com:443 inbound=TUN
DBG [Matcher] find process success addr=www.google.com path=\Device\HarddiskVolume5\Program Files\Google\Chrome\Application\chrome.exe
INF [TCP] connected lAddr=198.18.0.1:9775 rAddr=www.google.com:443 mode=rule rule=DomainSuffix(google.com) proxy=vmess
DBG [DNS] dns response source=119.29.29.29:53 qType=A name=www.google.com. answer=["xxx.xxx.xxx.xxx"]
```

### Description

TUN模式下运行命令行程序curl、ssh或python，如果访问的域名命中了域名规则，那么用Wireshark给物理网卡抓包抓不到向`119.29.29.29`查DNS。但在TUN模式下用Chrome、Edge或Firefox浏览器访问的域名命中了域名规则，用Wireshark配合Procmon64，可以确定就是Clash向`119.29.29.29`发起了查询（Wireshark可以看到查DNS用的UDP端口号，在Procmon64的记录中过滤这个UDP端口号，发现就是Clash进程发起的DNS查询）。但如果让浏览器把Clash设为代理服务器，那么没有DNS泄露。
