### ISSUE TITLE
[Feature] Update Proxy Providers through Proxy

### ISSUE THREAD

**Issue by Kingsmanvn-Official** [Dreamacro/clash#2368]
### Verify steps

- [ ]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

all version

### What OS are you seeing the problem on?

Windows, Linux, OpenBSD/FreeBSD

### Clash config

```yaml
port: 7890
socks-port: 7891
allow-lan: true
bind-address: '*'
mode: rule
ipv6: true
log-level: debug
external-controller: '127.0.0.1:9090'
clash-for-android:
  append-system-dns: true
profile:
  store-selected: false
  store-fake-ip: true
experimental:
  ignore-resolve-fail: true
  sniff-tls-sni: false
dns:
  enable: true
  ipv6: true
  default-nameserver:
    - 192.168.1.1
    - 1.1.1.1
    - 1.0.0.1
    - 8.8.8.8
    - 8.8.4.4
    - 9.9.9.9
    - 119.29.29.29
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  use-hosts: true
  nameserver:
    - dhcp://system
    - https://dns.google/dns-query
    - https://dns.adguard-dns.com/dns-query
    - https://dns.quad9.net/dns-query
    - https://dns.nextdns.io/fd88ba
    - https://cloudflare-dns.com/dns-query
  fallback:
    - dhcp://system
    - https://dns.google/dns-query
    - https://dns.adguard-dns.com/dns-query
    - https://dns.quad9.net/dns-query
    - https://dns.nextdns.io/fd88ba
    - https://cloudflare-dns.com/dns-query
tun:
  enable: true
  stack: gvisor # (gvisor|system)
  dns-hijack:
    - 198.18.0.2:53
  auto-route: true
  auto-detect-interface: true
proxies:
  - name: '🇸🇬 SG snell'
    type: snell
    server: xxx
    port: xxx
    psk: xxx
    version: 3
    udp: true
    obfs-opts:
      mode: tls
      host: xxx
proxy-groups:
    - name: KINGSMANVN
      type: select
      use:
        - yuna
      proxies:
        - "🇸🇬 SG snell"
proxy-providers:
  yuna:
    type: http
    url: "https://xxx"
    path: ./profiles/yuna.yml
    interval: 3600
    health-check:
      enable: true
      interval: 420
      url: http://www.gstatic.com/generate_204
rule-providers:
  hostsvn:
    behavior: domain # domain, ipcidr or classical (premium core only)
    type: http
    url: "https://xxx/hostsVN-clash-rule.yaml"
    interval: 72240
    path: ./ruleset/hostsvn.yaml
  reject:
    type: http
    behavior: domain
    url: "https://xxx/reject.txt"
    path: ./ruleset/reject.yaml
    interval: 86400
rules:
  - RULE-SET,hostsvn,REJECT
  - RULE-SET,reject,REJECT
  - MATCH,KINGSMANVN
```

### Description

I have also opened the issue before in [#1706 @Kr328 (ClashForAndroid)](https://github.com/Kr328/ClashForAndroid/issues/1706) and [#3607 in @Fndroid (ClashForWindows)](https://github.com/Fndroid/clash_for_windows_pkg/issues/3607) repositories
