### ISSUE TITLE
[Bug] proxy-providers 无法更新 https://s.juzicloud.vip/link/xxxxxxxx?clash=1

### ISSUE THREAD

**Issue by yingwenbo** [Dreamacro/clash#2373]
### Verify steps

- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

Clash 2022.08.26 linux amd64 with go1.19 Fri Aug 26 13:42:29 UTC 2022

### What OS are you seeing the problem on?

Linux

### Clash config

```yaml
proxy-providers:
  myss:
    type: file
    path: ./myss.yaml
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300
  juzicloud:
    type: http
    path: ./juzicloud.yaml
    url: https://s.juzicloud.vip/link/xxxxxx?clash=1
    interval: 43200
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300
  yecao:
    type: http
    path: ./yecao.yaml
    url: https://yc.wenjiushuobuzhidao.top/41184/c?auth=xxxxxx
    interval: 43200
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300
```

### Clash log

```shell
17:40:39 ERR [Config] configuration file test failed error=initial proxy provider juzi error: Get "https://s.juzicloud.vip/link/xxxxxxxx?clash=1": EOF path=xxxxxx
```

### Description

proxy-provider 无法更新桔子云的订阅规则
