### ISSUE TITLE
proxy-groups 配置fallback interval 只检查一次 [Bug] 

### ISSUE THREAD

**Issue by Sanchew** [Dreamacro/clash#2381]
### Verify steps

- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

v1.11.8

### What OS are you seeing the problem on?

macOS

### Clash config

```yaml
proxies:
  - name: charles
    type: socks5
    server: 127.0.0.1
    port: 8889


proxy-groups:
  - name: Charles
    proxies:
      - charles
      - DIRECT
    type: fallback
    url: http://*/abc.json
    interval: 10
```

### Clash log

```shell
111
```

### Description

配置是代码片段 主要问题是  

我配置了一个proxy-groups type为fallback proxies 一个为代理软件 另一个是DIRECT 代理软件映射url访问的文件为本地文件
interval 设置为10 我希望我代理软件开启时走代理软件 否则直连,
但我发两步url的检查只请求一次 并不是每10秒一次 当代理软件关闭后可正常直连 但再次打开代理软件后无法自动转发连接到代理软件中, 需要clash重新加载,

type设置为fallback 然后添加一个抓包软件 会发现 请求并不是按interval的时间间隔来请求
