### ISSUE TITLE
iptables redir-port ipv6-vps不能连接，mix-port正常工作

### ISSUE THREAD

**Issue by thincen** [Dreamacro/clash#2382]
### Verify steps

- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

v1.10.0

### What OS are you seeing the problem on?

Linux

### Clash config

```yaml
mixed-port: 7890
redir-port: 7893
allow-lan: true
mode: Rule
dns:
  enable: true
  listen: 0.0.0.0:53
  # 相对干净的国内 明文 DNS 服务器地址
  default-nameserver:
    - 119.29.29.29
    - 223.5.5.5
  enhanced-mode: redir-host
  # 解析国内域名时使用的加密 DNS 服务器地址
  nameserver:
    - https://223.5.5.5/dns-query
    - https://119.29.29.29/dns-query
  fallback:
    - https://dns.cloudflare.com/dns-query
    - https://dns.google/dns-query
  fallback-filter:
    geoip: true
    geoip-code: CN
...
proxy-groups:
...
  - name: 🐟 漏网之鱼
    type: select
    proxies:
      - 🎯 全球直连
rules:
  - DOMAIN-SUFFIX,github.com,PROXY
  - MATCH,🐟 漏网之鱼
```

### Clash log

```shell
INFO[0042] [TCP] 192.168.200.250:11655 --> github.com:443 match DomainSuffix(github.com) using 🔰 节点选择[hax]
```

### Description

有两个节点，1. ipv4-virmach 2. ipv6-hax （套了cf)
debian作为旁路由，网关为debian lan ip, debian设置iptables 类似于
iptables -t nat -N clash
iptables -t nat -A PREROUTING -p tcp -j clash
iptables -t nat -A clash -p tcp -j REDIRECT --to-ports 7893

节点1. ipv4-virmach**正常工作**，
节点为2. ipv6-hax不正常工作
host (github.com:443) DL(0 B) UL(517 B) DLSpeed(0 B/s) ULSpeed(0 B/s) Chains( 🔰 节点选择 / hax) Rule（DomainSuffix(github.com)  Time（less than a minute） Source（192.168.200.250:12118）distnationIp(192.30.255.112)
Type:Redir(tcp)
log 无报错信息

如果使用http代理, 网关不使用debian，节点2ipv6-hax工作正常。
请问是设置问题吗？
