### ISSUE TITLE
[Feature] [DNS] 是否应该让不符合 fallback-filter 条件的DNS查询*只*采用 nameserver 中解析的结果？

### ISSUE THREAD

**Issue by frezcirno** [Dreamacro/clash#2386]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

某些域名通过不同DNS server解析得到的地址不同，以`leetcode.cn`为例，用国内DNS解析到`***.aliyunddos***.com`，用国外的DNS则解析到`leetcode.cn.cdn.cloudflare.net`，前者可以直连，后者不可以。

在使用clash内置的DNS功能时，可能会出现 dns.fallback 中的 DNS server 比 dns.nameserver 中的先返回结果的情况（例如 nameserver 使用了 dhcp://interface-name 时），按照目前的逻辑，对于*不*符合 fallback-filter 条件的DNS查询，clash会采用所有上游DNS中最先返回的结果，这就会导致可能解析到一个国外DNS返回的ip地址。

还是以leetcode.cn为例，在分流规则中`leetcode.cn`这一条是直连（我相信大多数人都是这样），但是clash的DNS将`leetcode.cn`解析到了`leetcode.cn.cdn.cloudflare.net`，就导致无法连接。

### Possible Solution

让不符合dns.fallback-filter条件的DNS查询只采用dns.nameserver中解析的结果？

**Comment by Dreamacro** [comment]
由于我所使用的网络环境只会把 dns 污染成 0.0.0.0，所以我一般都只是这么配置的

```yaml
dns:
  enable: true
  fallback-filter:
    geoip: false
    ipcidr:
      - 0.0.0.0/32
```

**Comment by frezcirno** [comment]
感觉D大没理解我的意思，不是DNS污染的问题

问题是有国内cdn的网站，使用内置的DNS有可能会解析到国外ip去，就比如nameserver中的DNS很慢的时候

```yaml
dns:
  nameserver: # 国内dns
    - dhcp://WLAN
  fallback: # 国外dns
    - 8.8.8.8
    - ...
```

出错的情况：
Clash DNS: 解析leetcode.cn -> fallback中的DNS先返回结果 -> leetcode.cn.cdn.cloudflare.net -> 172.67.24.32 (国内不可访问)
Clash: 查规则表leetcode.cn -> DOMAIN-SUFFIX,cn,DIRECT -> 这条连接不需要代理
结果是clash去直连172.67.24.32，失败

感觉这个问题本质上是基于域名的规则和内置DNS实际解析的结果可能不匹配

个人想到的一个粗浅的办法是把nameserver和fallback的解析完全分开，符合fallback-filter的就走fallback，否则就只用nameserver，不知道有没有其他方案。
