### ISSUE TITLE
[Bug] domain related rules not working

### ISSUE THREAD

**Issue by behzadsh** [Dreamacro/clash#2392]
### Verify steps

- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

Premium 2022.08.26

### What OS are you seeing the problem on?

macOS

### Clash config

```yaml
mixed-port: 6789
allow-lan: true
bind-address: '*'
mode: rule
log-level: info
ipv6: false
external-controller: 127.0.0.1:52142

tun:
  enable: true
  stack: gvisor # or system
  dns-hijack:
    - 8.8.8.8:53
    - tcp://8.8.8.8:53
    - any:53
    - tcp://any:53
  auto-route: true
  auto-detect-interface: true

profile:
  store-selected: false
  store-fake-ip: false

dns:
  enable: true
  ipv6: true
  default-nameserver:
    - 1.1.1.1
    - 8.8.8.8
    - 114.114.114.114
  nameserver:
    - 1.1.1.1
    - 8.8.8.8
    - 114.114.114.114
  fallback:
    - 1.1.1.1
    - 8.8.8.8
    - 114.114.114.114
  enhanced-mode: fake-ip # or redir-host (not recommended)
  fake-ip-range: 198.18.0.0/16 # Fake IP addresses pool CIDR
  use-hosts: true

proxies:
  - name: vmess1
    type: vmess
    server: example.com
    port: "443"
    uuid: uuid
    alterId: "0"
    cipher: auto
    tls: true
    skip-cert-verify: true
    network: ws
    ws-opts:
      path: /websocket
      headers:
        Host: dst1.myhost.com
  - name: vmess2
    type: vmess
    server: something.com
    port: "443"
    uuid: uuid
    alterId: "0"
    cipher: auto
    tls: true
    skip-cert-verify: true
    network: ws
    ws-opts:
      path: /graphql
      headers:
        Host: dst2.myhost.com

proxy-groups:
  - name: "Fastest"
    type: url-test
    proxies:
      - vmess1
      - vmess2
    url: 'http://www.gstatic.com/generate_204'
    interval: 3600
  - name: Wireguard
    type: select
    interface-name: utun3
    proxies:
      - DIRECT

rules:
  - DOMAIN,open.spotify.com,vmess1
  - DOMAIN-SUFFIX,spotify.com,vmess1
  - DOMAIN-KEYWORD,spotify,vmess1
  - IP-CIDR,127.0.0.0/8,DIRECT
  - IP-CIDR,192.168.0.0/16,DIRECT
  - SRC-IP-CIDR,192.168.0.0/16,DIRECT
  - MATCH,Fastest
```

### Description

I want to set a rule for **spotify.com** to use a specific proxy. I tried every domain-related rule but it won't work at all.
When I check the log, it says the MATCH rule is used for spotify.com, not the vmess1.

The expected behavior is to resolve **open.spotify.com**, spotify.com and any subdomain of it, or any address that contains **soptify** via **vmess1** proxy.
