### ISSUE TITLE
[Bug] tun模式下rule代理UDP始终直连，TUN模式下开启auto route后报错

### ISSUE THREAD

**Issue by dsl888** [Dreamacro/clash#2396]
### Verify steps

- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

clash premium lastest

### What OS are you seeing the problem on?

Linux

### Clash config

```yaml
port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: 0.0.0.0:9090
external-ui: /clash/ui/yacd
ipv6: false
geodata-mode: false
geodata-loader: memconservative
tcp-concurrent: true


  
tun:
  enable: true
  stack: system
  dns-hijack:
    - 198.18.0.1:53 
  auto-route: true 
  auto-detect-interface: true 


  
dns:
  enable: true
  enhanced-mode: redir-host
  listen: 0.0.0.0:53
  default-nameserver:
      - 119.29.29.29
      - 223.5.5.5
  nameserver:
      - https://doh.pub/dns-query
      - https://dns.alidns.com/dns-query
```

### Description

[Bug] tun模式下rule代理UDP始终直连，TUN模式下开启auto route后报错，之前看到有其他人提过，可能是docker权限问题，不够ROS的docker无法修改权限，使用clash.meta的话，auto route可以正常运行，进入tun模式
