### ISSUE TITLE
[Question] TUN模式下默认只会从1.0.0.1解析域名，而忽略DNS的配置，貌似dns-hijack没有起作用

### ISSUE THREAD

**Issue by tony1016** [Dreamacro/clash#2399]
### Verify steps

- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

2022.08.26

### What OS are you seeing the problem on?

Linux

### Clash config

```yaml
mixed-port: 7890
# Set to true to allow connections to the local-end server from
# other LAN IP addresses
allow-lan: false

# Clash router working mode
# rule: rule-based packet routing
# global: all packets will be forwarded to a single endpoint
# direct: directly forward the packets to the Internet
mode: rule

# Clash by default prints logs to STDOUT
# info / warning / error / debug / silent
log-level: info

# When set to false, resolver won't translate hostnames to IPv6 addresses
ipv6: false

# RESTful web API listening address
external-controller: 127.0.0.1:9090

# secret: ""

dns:
    enable: true
    listen: 0.0.0.0:53
    # ipv6: false # when the false, response to AAAA questions will be empty

    # These nameservers are used to resolve the DNS nameserver hostnames below.
    # Specify IP addresses only
    default-nameserver:
        - 114.114.114.114
        - 8.8.8.8
    enhanced-mode: fake-ip # or redir-host (not recommended)
    fake-ip-range: 198.18.0.1/16 # Fake IP addresses pool CIDR
    # use-hosts: true # lookup hosts and return IP record

    # Hostnames in this list will not be resolved with fake IPs
    # i.e. questions to these domain names will always be answered with their
    # real IP addresses
    # fake-ip-filter:
    #   - '*.lan'
    #   - localhost.ptlogin2.qq.com

    # Supports UDP, TCP, DoT, DoH. You can specify the port to connect to.
    # All DNS questions are sent directly to the nameserver, without proxies
    # involved. Clash answers the DNS question with the first result gathered.
    nameserver:
        - 114.114.114.114 # default value
        - 119.29.29.29      # DNSpod DNS 17ms
        - 223.5.5.5         # 阿里 19ms

    # When `fallback` is present, the DNS server will send concurrent requests
    # to the servers in this section along with servers in `nameservers`.
    # The answers from fallback servers are used when the GEOIP country
    # is not `CN`.
    fallback:
        - tls://8.8.8.8:853         # Google DNS over TLS 50ms
        - tls://8.8.4.4:853         # cloudflare DNS over TLS 50ms
        - https://1.1.1.1/dns-query # cloudflare DNS over HTTPS
        - https://dns.google/dns-query # Google DNS over HTTPS

    # If IP addresses resolved with servers in `nameservers` are in the specified
    # subnets below, they are considered invalid and results from `fallback`
    # servers are used instead.
    #
    # IP address resolved with servers in `nameserver` is used when
    # `fallback-filter.geoip` is true and when GEOIP of the IP address is `CN`.
    #
    # If `fallback-filter.geoip` is false, results from `nameserver` nameservers
    # are always used if not match `fallback-filter.ipcidr`.
    #
    # This is a countermeasure against DNS pollution attacks.
    fallback-filter:
        geoip: true
        geoip-code: CN
        ipcidr:
            - 240.0.0.0/4
    #   domain:
    #     - '+.google.com'
    #     - '+.facebook.com'
    #     - '+.youtube.com'

    # Lookup domains via specific nameservers
    # nameserver-policy:
    #   'www.baidu.com': '114.114.114.114'
    #   '+.internal.crop.com': '10.0.0.1'
interface-name: enp2s0
#auto-redir:
    #enable: true
    #auto-route: true
tun:
    enable: true
    stack: system
    dns-hijack:
        - any:53
    auto-route: true

以下无关，省略
....
```

### Description

发现clash在TUN模式开启后，服务器地址解析都走的1.0.0.1，而没有按照dns配置进行分流发送解析请求。tcpdump实体网卡，发现全部请求都走了1.0.0.1

19:52:22.282660 IP 192.168.31.165.57138 > 1.0.0.1.53: 1500+ A? [www.bilibili.com](http://www.bilibili.com/). (34)
19:52:22.282665 IP 192.168.31.165.51356 > 1.0.0.1.53: 1500+ A? [www.bilibili.com](http://www.bilibili.com/). (34)
19:52:22.282666 IP 192.168.31.165.39165 > 1.0.0.1.53: 1500+ A? [www.bilibili.com](http://www.bilibili.com/). (34)
