### ISSUE TITLE
[Bug] Websocket earlydata (0rtt) not working

### ISSUE THREAD

**Issue by SakuraSakuraSakuraChan** [Dreamacro/clash#2400]
### Verify steps

- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

1.11.8

### What OS are you seeing the problem on?

Windows, Linux

### Clash config

```yaml
- name: "FUCKGFW"
  type: vmess
  server: 1.2.4.8
  port: 80
  uuid: 0d714e36-2975-4878-b151-1c766b78f604
  alterId: 0
  cipher: auto
  udp: true
  tls: false
  skip-cert-verify: false
  network: ws
  ws-opts:
    path: /fuckgfw
    headers:
      Host: fuck.gfw.com
    max-early-data: 2048
    early-data-header-name: Sec-WebSocket-Protocol
```

### Clash log

```shell
连接正常，日志正常，无任何Warn或Error。
```

### Description

启用Earlydata后，测试真延迟，发现数值无变化。因为我不是直连VPS，是过CDN的，后来经多重测试，发现本地到CDN之间rtt无变化，CDN服务器回源到VPS时能减少一个rtt，我没法确定这是预期的行为还是bug，于是去提交PR的v2fly那边问了下，暂时没人回复。
后来逛github，发现clash用户似乎都有这个问题： https://github.com/SagerNet/sing-box/issues/169  还有一个 https://github.com/MetaCubeX/Clash.Meta/issues/224 这些用户应该不是过CDN的，所以感觉是clash的问题，提交个issue看看，另外祝D大身体早日康复~~
