### ISSUE TITLE
公司网络环境，访问公司网络如何用内网ip，而不是公网ip

### ISSUE THREAD

**Issue by fredericky123** [Dreamacro/clash#2418]
### Verify steps

- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

1.95

### What OS are you seeing the problem on?

macOS

### Clash config

```yaml
# HTTP 端口
port: 7890

# SOCKS5 端口
socks-port: 7891

# Linux 及 macOS 的 redir 端口
# redir-port: 7892

allow-lan: false

# 仅适用于设置 allow-lan 为 true 时

# Rule / Global / Direct (默认为 Rule 模式)
mode: Rule

# 设置输出日志的等级 (默认为 info)
# info / warning / error / debug / silent
log-level: info

ipv6: true

# RESTful API for clash
external-controller: 127.0.0.1:9090

# you can put the static web resource (such as clash-dashboard) to a directory, and clash would serve in `${API}/ui`
# input is a relative path to the configuration directory or an absolute path
# external-ui: folder

# Secret for RESTful API (Optional)
# secret: ""

# 实验性功能
experimental:
  ignore-resolve-fail: true # 忽略 DNS 解析失败，默认值为true
  # interface-name: en0 # 出站接口名称

# 本地 SOCKS5/HTTP(S) 服务器认证
# authentication:
#  - "user1:pass1"
#  - "user2:pass2"

# # 实验性 hosts, 支持通配符（如 *.clash.dev 甚至 *.foo.*.examplex.com ）
# # 静态域的优先级高于通配符域（foo.example.com > *.example.com）
hosts:
#  'mtalk.google.com': 108.177.125.188
#   '*.clash.dev': 127.0.0.1
#   'alpha.clash.dev': '::1'

dns:
  enable: true # set true to enable dns (default is false)
  ipv6: true # default is false
  listen: 127.0.0.1:53
  default-nameserver: # resolve dns nameserver host, should fill pure IP
     - 127.0.0.1
```

### Clash log

```shell
无
```

### Description

使用的自建的adguard进行dns解析
所以是127.0.0.1
已经设置了公司域名的rule为direct，导致访问公司域名时为公网ip，因此会自动跳转至webvpn链接
请问如何设置使得访问公司域名时为内网ip呢？这样就会直接登录访问了
