### ISSUE TITLE
[Feature] 希望在 `Script Shortcut` 中增加 `resolve_process_name` 支持

### ISSUE THREAD

**Issue by yi-Xu-0100** [Dreamacro/clash#2423]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

在 Script 模式下，是支持 `resolve_process_name` 的，但是 Shortcut 的 function 中没有。

希望能够增加这个支持

![image](https://user-images.githubusercontent.com/25523606/202843140-fc83bf38-3756-408c-80db-c26d7b983469.png)

### Possible Solution

如果可以，甚至希望能够支持增加正则 function 支持！

**Comment by Dreamacro** [comment]
在 latest 更新了几个 function

```yaml
script:
  shortcuts:
    curl: resolve_process_name() == 'curl'
    # curl: resolve_process_path() == '/usr/bin/curl'

```
