### ISSUE TITLE
[Bug] "Read Aloud" feature of Microsoft Edge for Android failed to load when using clash

### ISSUE THREAD

**Issue by MUTED64** [Dreamacro/clash#2425]
### Verify steps

- [ ]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [ ]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [x]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

2022.08.26 Premium

### Clash config

```yaml
profile:
  store-selected: false
  tracing: false
  store-fake-ip: true
dns:
  enable: true
  enhanced-mode: fake-ip
  nameserver:
    - tls://dns.alidns.com
    - tls://dot.pub
  fallback:
    - 199.85.127.10
    - 8.8.8.8
    - 223.6.6.6
  fake-ip-filter:
    - +.stun.*.*
    - +.stun.*.*.*
    - +.stun.*.*.*.*
    - +.stun.*.*.*.*.*
    - "*.n.n.srv.nintendo.net"
    - +.stun.playstation.net
    - xbox.*.*.microsoft.com
    - "*.*.xboxlive.com"
    - "*.msftncsi.com"
    - "*.msftconnecttest.com"
    - WORKGROUP
proxy-providers:
  socloud:
    type: http
    path: ./proxyproviders/socloud.yaml
    url: ***
    interval: 86400
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300
  relaycloud:
    type: http
    path: ./proxyproviders/relaycloud.yaml
    url: ***
    interval: 86400
    filter: "S[1-9].*"
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300
  bujidao:
    type: http
    path: ./proxyproviders/bujidao.yaml
    url: ***
    interval: 86400
    filter: "[0-9]{3}|.+元/G"
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
proxy-groups: 
  - name: PROXY
    type: select
    proxies:
      - socloud
      - relaycloud
      - bujidao
  - name: socloud
    type: select
    use:
      - socloud
  - name: relaycloud
    type: select
    use:
      - relaycloud
  - name: bujidao
    type: select
    use:
      - bujidao
rules:
  - PROCESS-NAME,avp.exe,DIRECT
  - PROCESS-NAME,avp,DIRECT
  - DST-PORT,7680,DIRECT
  - DOMAIN-SUFFIX,cn.bing.com,DIRECT
  - DOMAIN-SUFFIX,sharepoint.com,DIRECT
  - DOMAIN-SUFFIX,smartscreen.microsoft.com,DIRECT
  - DOMAIN-SUFFIX,edge.microsoft.com,DIRECT
  - DOMAIN-SUFFIX,googleapis.cn,PROXY
  - DOMAIN-SUFFIX,store.steampowered.com,PROXY
  - DOMAIN-SUFFIX,steamcontent.com,DIRECT
  - DOMAIN-SUFFIX,steamstatic.com,DIRECT
  - DOMAIN-SUFFIX,steampowered.com,DIRECT
  - DOMAIN-SUFFIX,steam-chat.com,DIRECT
  - DOMAIN-SUFFIX,steamserver.net,DIRECT
  - DOMAIN-KEYWORD,steamcdn,DIRECT
  - DOMAIN-KEYWORD,steamstore,DIRECT
  - DOMAIN-KEYWORD,steamuserimages,DIRECT
  - DOMAIN-KEYWORD,steambroadcast,DIRECT
  - DOMAIN-SUFFIX,mozilla.org,DIRECT
  - RULE-SET,applications,DIRECT
  - DOMAIN,clash.razord.top,DIRECT
  - DOMAIN,yacd.haishan.me,DIRECT
  - DOMAIN,openwrt.lan,DIRECT
  - RULE-SET,private,DIRECT
  - RULE-SET,icloud,DIRECT
  - RULE-SET,apple,DIRECT
  - RULE-SET,google,DIRECT
  - RULE-SET,proxy,PROXY
  - RULE-SET,direct,DIRECT
  - RULE-SET,lancidr,DIRECT
  - RULE-SET,cncidr,DIRECT
  - RULE-SET,telegramcidr,PROXY
  - GEOIP,LAN,DIRECT
  - GEOIP,CN,DIRECT
  - MATCH,PROXY

rule-providers:
  reject:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/reject.txt"
    path: ./ruleset/reject.yaml
    interval: 86400

  icloud:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/icloud.txt"
    path: ./ruleset/icloud.yaml
    interval: 86400

  apple:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/apple.txt"
    path: ./ruleset/apple.yaml
    interval: 86400

  google:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/google.txt"
    path: ./ruleset/google.yaml
    interval: 86400

  proxy:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/proxy.txt"
    path: ./ruleset/proxy.yaml
    interval: 86400

  direct:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/direct.txt"
    path: ./ruleset/direct.yaml
    interval: 86400

  private:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/private.txt"
    path: ./ruleset/private.yaml
    interval: 86400

  gfw:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/gfw.txt"
    path: ./ruleset/gfw.yaml
    interval: 86400

  greatfire:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/greatfire.txt"
    path: ./ruleset/greatfire.yaml
    interval: 86400

  tld-not-cn:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/tld-not-cn.txt"
    path: ./ruleset/tld-not-cn.yaml
    interval: 86400

  telegramcidr:
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/telegramcidr.txt"
    path: ./ruleset/telegramcidr.yaml
    interval: 86400

  cncidr:
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/cncidr.txt"
    path: ./ruleset/cncidr.yaml
    interval: 86400

  lancidr:
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/lancidr.txt"
    path: ./ruleset/lancidr.yaml
    interval: 86400

  applications:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/applications.txt"
    path: ./ruleset/applications.yaml
    interval: 86400
```

### Clash log

```shell
# Capture on 2022-11-19 22:27:58.425
22:28:00.861   Debug: [PKG] 127.0.0.1:34040 --> gateway.bingviz.microsoftapp.net:443 by 10212[com.microsoft.emmx]
22:28:00.861   Debug: [Process] gateway.bingviz.microsoftapp.net from process com.microsoft.emmx
22:28:00.862   Debug: [DNS] gateway.bingviz.microsoftapp.net --> 13.107.213.39
22:28:00.899    Info: [TCP] 127.0.0.1:34040 --> gateway.bingviz.microsoftapp.net:443 match Match() using PROXY[S111 香港]
22:28:02.065   Debug: [PKG] 127.0.0.1:34044 --> in.appcenter.ms:443 by 10248[com.github.kr328.clash]
22:28:02.066   Debug: [Process] in.appcenter.ms from process com.github.kr328.clash
22:28:02.106    Info: [TCP] 127.0.0.1:34044 --> in.appcenter.ms:443 match RuleSet(proxy) using PROXY[S111 香港]
22:28:02.331    Info: [APP] request force GC
22:28:02.782   Debug: [PKG] 127.0.0.1:34048 --> self.events.data.microsoft.com:443 by 10212[com.microsoft.emmx]
22:28:02.782   Debug: [Process] self.events.data.microsoft.com from process com.microsoft.emmx
22:28:02.825    Info: [TCP] 127.0.0.1:34048 --> self.events.data.microsoft.com:443 match RuleSet(proxy) using PROXY[S111 香港]
22:28:03.142   Debug: [PKG] 172.19.0.1:48474 --> speech.platform.bing.com:43745 by 10212[com.microsoft.emmx]
22:28:03.142   Debug: [Process] speech.platform.bing.com from process com.microsoft.emmx
22:28:03.194    Info: [TCP] 172.19.0.1:48474 --> speech.platform.bing.com:43745 match RuleSet(proxy) using PROXY[S111 香港]
22:28:06.427   Debug: [PKG] 172.19.0.1:53450 --> speech.platform.bing.com:43745 by 10212[com.microsoft.emmx]
22:28:06.427   Debug: [Process] speech.platform.bing.com from process com.microsoft.emmx
22:28:06.468    Info: [TCP] 172.19.0.1:53450 --> speech.platform.bing.com:43745 match RuleSet(proxy) using PROXY[S111 香港]
22:28:09.011   Debug: [PKG] 127.0.0.1:34064 --> connectivitycheck.gstatic.com:443 by 10169[com.android.vending]
22:28:09.012   Debug: [Process] connectivitycheck.gstatic.com from process com.android.vending
22:28:09.047    Info: [TCP] 127.0.0.1:34064 --> connectivitycheck.gstatic.com:443 match RuleSet(google) using DIRECT
22:28:09.899    Info: [APP] request force GC
22:28:15.700    Info: [APP] request force GC
22:28:16.737    Info: [APP] request force GC
22:28:19.245   Debug: [PKG] 127.0.0.1:34068 --> gateway.bingviz.microsoftapp.net:443 by 10212[com.microsoft.emmx]
22:28:19.245   Debug: [Process] gateway.bingviz.microsoftapp.net from process com.microsoft.emmx
22:28:19.245   Debug: [DNS] gateway.bingviz.microsoftapp.net --> 13.107.213.39
22:28:19.306    Info: [TCP] 127.0.0.1:34068 --> gateway.bingviz.microsoftapp.net:443 match Match() using PROXY[S111 香港]
```

## Environment
OS: MIUI 13.0.24, Android 12
Clash Core: 2022.08.26 Premium
Client App: Clash for Android 2.5.9 premium by kr328
Browser: Edge for Android 107.0.1418.43

## Behavior
I have the "Clash for Android" client installed on an Android phone. 

When Clash for Android is not running on my Android phone, the Edge browser's "Read Aloud" feature works well as expected. When clash is running, no matter which mode(direct/global/rule) is chosen, and no matter whether I use fake-ip mode, that "Read Aloud" feature does not work at all. I checked the log and it has no warning and no error, I cannot figure out what happened.

Then I tried to stop clash on my phone and set my computer(Windows 10 22H2) as my phone's proxy server, which has a Clash Core 2022.08.26 Premium running on it, and that still not going to work(in direct/global/rule mode). However, everything goes well when I use other proxy apps such as "Shadowsocks". So I think this is an issue of clash core.

I finally captured my phone's packets using Wireshark. And the result is, When clash is not running, the browser will first send a DNS request for `speech.platform.bing.com` and get the result `13.107.21.237`, then the data will be transferred from `TCP 13.107.21.237:443`. When clash is running, even if I choose the `DIRECT` mode, no packet related to that API can be captured, but the log seems to have those connections, which is weird.

In addition, there is no problem when I visit `speech.platform.bing.com` directly in the browser using HTTPS. But when it comes to the feature using that API, it just cannot use at all.

I have no idea what I can do to fix this by myself. If it is a clash problem, I hope it can be fixed soon.
