### ISSUE TITLE
[Question] Clash configuration details (long-ish)

### ISSUE THREAD

**Issue by IngwiePhoenix** [Dreamacro/clash#2444]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

Hello!

Alright, I think I am quite confy with reading and understanding the Clash config; I even learned there is an Android client, which is quite amazing and opens the door for some pretty fun setups :)! Also, disclaimer: This is kinda long... I apologize!

I just want to iron out my understanding before I go and break everything:

- `dns.default-nameservers` vs. `dns.nameservers`: Which one has priority - or do I even need to specify both? Idealy, is there a way to specify which host to query based on their TLD? For instance, I would like to send requests to my AdGuard DNS server first (to short-circuit ad-site requests), then "new TLDs" requests to [OpenNIC](https://www.opennic.org/) and finally fall-through to Cloudflare via DoH. Which of the two settings would I use - and is such a "conditional resolving" even supported? I don't think so, as it was listed nowhere, but I just want to make sure in case I missed something. (I am literally visually impaired - overlooking things is kinda my nature... :)). (I did get `dns.fallback` though, I live in the EU, no need for me to use it, so that will end up completely empty.) If I understand right, then this *should* be right?

```yaml
dns:
  enable: true
  listen: 192.168.8.2:53
  ipv6: true # My ISP supports IPv6.
  default-nameservers:
    - 1.1.1.1
    - 1.0.0.1
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  use-hosts: true # hosts: { "*.birb.it": "192.168.8.2" }
  fake-ip-filter:
    - "ingwie.me"
    - "*.ingwie.me"
    - # My other domains
  nameserver:
    - 192.168.8.2:5335 # Imagine a local AdGuard server here.
    - 54.36.111.116 # German OpenNIC server
    - [2001:41d0:700:1174::] # Same, but IPv6
    - https://1.1.1.1/dns-query # CloudFlare DoH
  fallback-servers: # Empty, unused. I can resolve CN IPs just fine...i think? Genshin and Tower Of Fantasy work, both hosted in CN.
  fallback-filter: # Empty, unused.
  nameserver-policy:
    - "*.o": 54.36.111.116 # an OpenNic TLD example
```

- Which values are supported for `proxy.type`? I found:
  * `type: ss` -> ShadowSocks
  * `type: vmess` -> VMess
  * `type: vmess-grpc` -> VMess via gRPC
  * `type: socks5` -> Just SOCKS5, not mixed (though I guess I could point it at a mixed port, might not be a good idea though.)
  * `type: http` -> HTTP Proxy Server (both tor and i2pd expose one to my knowledge - not sure if this would do HTTPS (HTTP over TLS) - different issue alltogether though.)
  * `type: shell` -> SSH Tunnel, if my guess is correct.
  * `type: trojan` -> Trojan - never heared of that protocol ever, actually. o.o
  * `type: trojan-grpc` -> Trojan but via gRPC
  * `type: trojan-ws` -> Trojan via WebSockets (WSS though?)
  * `type: ssr` -> ShadowSocksR
  I am sure the `server: server` part in the examples [in this part of the docs](https://github.com/Dreamacro/clash/wiki/Configuration#all-configuration-options) is just the server address (`[http(s)://]($host|$ip)` etc.)

- Am I right in understanding that `proxy-groups` is only ment to be used when chaining remote proxies? I.e.: Go to provider A, from there connect to provider B and then use A->B to get result from the final destination C?

- `tunnels` is basically like an SSH port-forwarding?

- If I register a VPN connection on a virtual network device - i.e. `vpn0` - how can I specify that as a "proxy"? The idea is that I could then use a `rules` config like this:

```yaml
rules:
  - DOMAIN-SUFFIX,onion,tor
  - DOMAIN-SUFFIX,exit,tor
  - DOMAIN-SUFFIX,i2p,i2p
  # Whitelist start
  - DOMAIN,somedomain.com,DIRECT
  # Whitelist end
  - MATCH,vpn # <- vpn meaning traffic goes out of vpn0
```

I am so sorry this is so long x) But I am getting quite familiar with the configuration now - those are literally just little nic-nacks I think the docs don't cover too well. Since the OSS version does not support WireGuard, I'll likely just route traffic through the created interface instead - which is what `vpn0` will be. And yes, I did [see the example](https://github.com/Dreamacro/clash/wiki/Examples).

Thank you for your patience and time, I appreciate it a lot!

Kind regards and a great day,
Ingwie.

### Possible Solution

The solution is largely a me-problem at this point; hence why I just want to make sure I get all the details right.

Thank you in advance! ^.^

**Comment by BirkhoffLee** [comment]
> Alright, I think I am quite confy with reading and understanding the Clash config; I even learned there is an Android client, which is quite amazing and opens the door for some pretty fun setups :)! Also, disclaimer: This is kinda long... I apologize!

All good, I'm happy the wiki helped you to navigate around. :-)

> * `dns.default-nameservers` vs. `dns.nameservers`: Which one has priority - or do I even need to specify both? Idealy, is there a way to specify which host to query based on their TLD?

`dns.default-nameservers` is solely used to solve nameservers specified in `dns.nameservers`

> For instance, I would like to send requests to my AdGuard DNS server first (to short-circuit ad-site requests), then "new TLDs" requests to [OpenNIC](https://www.opennic.org/) and finally fall-through to Cloudflare via DoH. Which of the two settings would I use

As stated above, they are resolved by `dns.nameservers` in the same time. The fastest answer is used by Clash. (this behaviour is documented in wiki)

> - and is such a "conditional resolving" even supported?

To clarify, there is no conditional resolving for now (for this scenario). Clash is designed for Chinese, so fallback servers are CN only (for now). You can only use `nameserver-policy` at this time.

In your scenario

```yaml
default-nameservers:
  - 1.1.1.1
  - 1.0.0.1
nameserver:
  - 192.168.8.2:5335 # Imagine a local AdGuard server here.
  - 54.36.111.116 # German OpenNIC server
  - [2001:41d0:700:1174::] # Same, but IPv6
  - https://1.1.1.1/dns-query # CloudFlare DoH
```

`default-nameservers` are never used, because you specified IP addresses for the nameservers, so Clash doesn't need to resolve any domains for the nameservers.

All four nameservers specified is used to solve an outbound target. Let's say you're connecting to `google.com` through Clash, it would ask all four nameservers for the IP address of `google.com`, and pick whichever the fastest response would be.

> type: http -> HTTP Proxy Server (both tor and i2pd expose one to my knowledge - not sure if this would do HTTPS (HTTP over TLS) - different issue alltogether though.)

i dont think there is https support

> type: shell -> SSH Tunnel, if my guess is correct.

it should be the `snell` protocol developed by the Surge developer. It's a proprietary protocol but only a small proportion of people use it

> I am sure the server: server part in the examples [in this part of the docs](https://github.com/Dreamacro/clash/wiki/Configuration#all-configuration-options) is just the server address ([http(s)://]($host|$ip) etc.)

it's the server address. IP address or FQDN.

> Am I right in understanding that proxy-groups is only ment to be used when chaining remote proxies? I.e.: Go to provider A, from there connect to provider B and then use A->B to get result from the final destination C?

There are other scenario in which proxy groups would be useful. For example in proxy groups you can specify `interface-name` in which the NIC would be used to connect to the "next hop" (i.e.: proxy node or DIRECT).

> If I register a VPN connection on a virtual network device - i.e. vpn0 - how can I specify that as a "proxy"? The idea is that I could then use a rules config like this:

This is an example. If you'd want to integrate like Cisco Anyconnect into Clash, you'd want to run openconnect on your machine, it sets up a TUN device on your system, and you can have a proxy group that uses `DIRECT` only, and specify the openconnect TUN device name in `interface-name`. (described [here](https://github.com/Dreamacro/clash/wiki/Examples#use-with-openconnect))

> tunnels is basically like an SSH port-forwarding?

exactly
