### ISSUE TITLE
paypal 等域名提示 All DNS requests failed

### ISSUE THREAD

**Issue by Chandler-Lu** [Dreamacro/clash#245]
ClashX: 1.10.1
Clash core: dev branch

日志（其中 Domestic 和 Apple 规则均为 DIRECT）：
```
2019/07/28 23:06:08:265  [info] 127.0.0.1 --> metrics.icloud.com match DomainSuffix using Apple
2019/07/28 23:06:09:414  [warning] Proxy[Apple] connect [127.0.0.1 --> metrics.icloud.com] error: All DNS requests failed
```
```
2019/07/28 23:27:24:647  [info] 127.0.0.1 --> imap-mail.outlook.com match Domain using DIRECT
2019/07/28 23:27:25:650  [warning] Proxy[DIRECT] connect [127.0.0.1 --> imap-mail.outlook.com] error: All DNS requests failed
```

```
2019/07/28 23:07:09:670  [info] 127.0.0.1 --> www.paypal.com match DomainSuffix using Domestic
2019/07/28 23:07:09:666  [warning] Proxy[Domestic] connect [127.0.0.1 --> www.paypal.com] error: All DNS requests failed
```

配置：
```
dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:53
  enhanced-mode: redir-host
  nameserver:
  - 117.50.10.10
  - 119.29.29.29
  - 223.5.5.5
  - tls://dns.rubyfish.cn:853
  fallback:
  - tls://1.1.1.1:853
  - tls://1.0.0.1:853
  - tls://dns.google:853
```

把 dns 关掉似乎可以解决该问题，但由于使用的是托管，无法上游每更新一次配置就手动修改一次，不知道有没有什么其他的解决办法，谢谢
