### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by KHSHATHRA** [Dreamacro/clash#2461]
### Verify steps

- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

0.20.10

### Clash config

```yaml
port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: 0.0.0.0:9090
proxies:
  - type: vmess
    name: vmes-nl.goserver.pw-ntls
    ws-opts:
      path: /worryfree-ntls
      headers:
        host: vmes-nl.goserver.pw
    server: 206.189.9.108
    port: "80"
    uuid: d706735a-a786-4ee2-9f89-dd758096269a
    alterId: "0"
    cipher: auto
    network: ws
proxy-groups:
  - name: 🚀 节点选择
    type: select
    proxies:
      - ♻️ 自动选择
      - DIRECT
      - vmes-nl.goserver.pw-ntls
  - name: ♻️ 自动选择
    type: url-test
    url: http://www.gstatic.com/generate_204
    interval: 300
    tolerance: 50
    proxies:
      - vmes-nl.goserver.pw-ntls
  - name: 🌍 国外媒体
    type: select
    proxies:
      - 🚀 节点选择
      - ♻️ 自动选择
      - 🎯 全球直连
      - vmes-nl.goserver.pw-ntls
  - name: 📲 电报信息
    type: select
    proxies:
      - 🚀 节点选择
      - 🎯 全球直连
      - vmes-nl.goserver.pw-ntls
  - name: Ⓜ️ 微软服务
    type: select
    proxies:
      - 🎯 全球直连
      - 🚀 节点选择
      - vmes-nl.goserver.pw-ntls
  - name: 🍎 苹果服务
    type: select
    proxies:
      - 🚀 节点选择
      - 🎯 全球直连
      - vmes-nl.goserver.pw-ntls
  - name: 🎯 全球直连
    type: select
    proxies:
      - DIRECT
      - 🚀 节点选择
      - ♻️ 自动选择
  - name: 🛑 全球拦截
    type: select
    proxies:
      - REJECT
      - DIRECT
  - name: 🍃 应用净化
    type: select
    proxies:
      - REJECT
      - DIRECT
  - name: 🐟 漏网之鱼
    type: select
    proxies:
      - 🚀 节点选择
      - 🎯 全球直连
      - ♻️ 自动选择
      - vmes-nl.goserver.pw-ntls
```

### Description

Hello
Thank you for making this application and providing continuous and useful updates.
Ever since I upgraded the program to the latest version, I encountered a problem that it is not possible to use VMess and Trojan protocols, and all servers are timed out.
please guide me .
I also have a request, if possible, add Vless protocol to the list of supported protocols.
my Ver : 0.20.10
