### ISSUE TITLE
[Question] what is tolerance and lazy options in url-test

### ISSUE THREAD

**Issue by hadifarnoud** [Dreamacro/clash#2464]
### Verify steps

- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

1.12.0

### What OS are you seeing the problem on?

macOS

### Clash config

```yaml
- name: Proxy
    type: url-test
    proxies:
      - US2
      - US3
      - US4
      - US5
      - US6
      - US7
      - US7-trojan-xtls
      - US7-trojan-grpc
      - US8
      - US9
      - US10_GRPC
      - US10_trojan_grpc
      - US10_Trojan
      - US10_VMESS
      - US10_ws
      - US10_xtls-rprx-splic
      - vless
    url: 'http://www.gstatic.com/generate_204'
    interval: 100
    tolerance: 300
    lazy: true
```

### Description

The documentation is not clear on what `tolerance` and `lazy` do exactly. does it mean the value of test cannot be higher than `tolerance`? 

and I have no idea what `lazy` does at all
