### ISSUE TITLE
[Feature] dns.fake-ip-range 是否无法使用 IPv6 地址范围？

### ISSUE THREAD

**Issue by ragnaroks** [Dreamacro/clash#2471]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

我使用如下配置文件：
```
allow-lan: false

bind-address: '*'

mode: rule

ipv6: true

hosts:
  localhost: '[::1]'

profile:
  store-selected: false
  store-fake-ip: true

interface-name: enp1s0

tun:
  enable: true
  stack: system
  dns-hijack:
    - '[fd00:0:0:1080:0:0:0:2]:53'
  auto-route: true
  auto-detect-interface: false

dns:
  enable: true
  listen: '[::]:53'
  ipv6: true
  default-nameserver:
    - '[2400:3200::]:53'
  enhanced-mode: fake-ip
  fake-ip-range: '[fd00:0:0:1080:0:0:0:0]/64'
  use-hosts: true
  fake-ip-filter:
    - +.lan
    - +.local
  nameserver:
    - '[2400:3200::]:53'
    - '[2402:4e00::]:53'
    - dhcp://enp1s0

proxies:
  - name: gateway
    type: socks5
    server: '[fd00:0054:9300:0302:5090::1]'
    port: 1080
    udp: true

rules:
  - IP-CIDR6,[::1]/128,DIRECT
  - IP-CIDR6,[fd00::]/16,DIRECT
  - IP-CIDR6,[2400:3200::]/32,DIRECT
  - IP-CIDR6,[2402:4e00::]/32,DIRECT
  - DOMAIN,localhost,DIRECT
  - MATCH,gateway
```

尝试启动时报错，经测试不管是完整（[fd00:0000:0000:1080:0000:0000:0000:0000]/64）表示还是缩写（[fd00::1080:0:0:0:0]/64）都是一样的错误。

```
17:01:07 FTL [Config] parse config failed error=netip.ParsePrefix("[fd00:0:0:1080:0:0:0:0]/64"): ParseAddr("[fd00:0:0:1080:0:0:0:0]"): each colon-separated field must have at least one digit (at "[fd00:0:0:1080:0:0:0:0]")
```
