### ISSUE TITLE
[Bug] Clash relay 代理链中存在SSR节点就会无法使用

### ISSUE THREAD

**Issue by xusenfa** [Dreamacro/clash#2475]
### Verify steps

- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

2022.11.25 Premium

### What OS are you seeing the problem on?

Windows

### Clash config

```yaml
mixed-port: 7890
mode: Rule
profile: {store-fake-ip: true}
hosts: {services.googleapis.cn: 142.250.196.131, www.google.cn: 142.250.196.131}
dns:
  enable: true
  enhanced-mode: fake-ip
  
  nameserver: [223.5.5.5, https://223.5.5.5/dns-query]
tun: {enable: true, stack: gvisor, dns-hijack: [any:53], auto-route: true, auto-detect-interface: true}
proxies:
  -
    name: a
    type: ssr
    server: *
    port: '8009'
    cipher: aes-256-cfb
    password: V2efLnR3SJZr
    protocol: auth_aes128_md5
    protocol-param: '*'
    obfs: http_simple
    obfs-param: *

 
  - {name: b, server: *, port: 21179, type: ss, cipher: aes-128-gcm, password: *, udp: true}
 
proxy-groups:

  - name: testrelay
    type: relay
    proxies:
      - a
      - b

rules:

  - MATCH,testrelay
```

### Description

当单独使用a节点或单独使用b节点时都可用，但是relay使用就会失败
