### ISSUE TITLE
[Bug] 部署clash后EMBY无法通过公网访问

### ISSUE THREAD

**Issue by Li-xp** [Dreamacro/clash#2476]
### Verify steps

- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

v1.12.0

### Clash config

```yaml
port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: debug
external-controller: :9090
proxies:
//隐去
proxy-groups:
  - name: 🚀 节点选择
    type: select
    proxies:
      - ♻️ 自动选择
      - 🔯 故障转移
      - 🔮 负载均衡
      - 🇭🇰 香港节点
      - 🇨🇳 台湾节点
      - 🇸🇬 狮城节点
      - 🇯🇵 日本节点
      - 🇺🇲 美国节点
      - 🇰🇷 韩国节点
      - 🚀 手动切换
      - DIRECT
  - name: 🚀 手动切换
    type: select
    proxies:
      - 懒人节点 01
      - 🇭🇰 香港 01
      - 🇭🇰 香港 02
      - 🇭🇰 香港 03
      - 🇭🇰 香港 04
      - 🇭🇰 香港 05
      - 🇭🇰 香港 06
      - 🇭🇰 香港 07#
      - 🇨🇳 台湾 01
      - 🇨🇳 台湾 02
      - 🇨🇳 台湾 03
      - 🇸🇬 新加坡 01
      - 🇸🇬 新加坡 02
      - 🇸🇬 新加坡 03
      - 🇯🇵 日本 01
      - 🇯🇵 日本 02
      - 🇯🇵 日本 03
      - 🇰🇷 韩国 01
      - 🇰🇷 韩国 02
      - 🇺🇸 美国 01
      - 🇺🇸 美国 02
      - 🇺🇸 美国 03
      - 🇷🇺 俄罗斯 01
      - 🇹🇷 土耳其 01
      - 🇩🇪 德国 01
      - 🇱🇺 卢森堡 01
      - 🇬🇧 英国 01
      - 🇵🇭 菲律宾 01
      - 🇮🇳 印度 01
      - 🇹🇭 泰国 01
      - 🇲🇾 马来西亚 01
      - 🇦🇪 阿联酋 01
      - 🇦🇺 澳洲 01
      - 🇿🇦 南非 01
      - 🇧🇷 巴西 01
      - 🇦🇷 阿根廷 01
      - 🇻🇳 越南 01
      - 🇺🇦 乌克兰 01
  - name: ♻️ 自动选择
    type: url-test
    url: http://www.gstatic.com/generate_204
    interval: 300
    tolerance: 50
    proxies:
      - 懒人节点 01
      - 🇭🇰 香港 01
      - 🇭🇰 香港 02
      - 🇭🇰 香港 03
      - 🇭🇰 香港 04
      - 🇭🇰 香港 05
      - 🇭🇰 香港 06
      - 🇭🇰 香港 07#
      - 🇨🇳 台湾 01
      - 🇨🇳 台湾 02
      - 🇨🇳 台湾 03
      - 🇸🇬 新加坡 01
      - 🇸🇬 新加坡 02
      - 🇸🇬 新加坡 03
      - 🇯🇵 日本 01
      - 🇯🇵 日本 02
      - 🇯🇵 日本 03
      - 🇰🇷 韩国 01
      - 🇰🇷 韩国 02
      - 🇺🇸 美国 01
      - 🇺🇸 美国 02
      - 🇺🇸 美国 03
      - 🇷🇺 俄罗斯 01
      - 🇹🇷 土耳其 01
      - 🇩🇪 德国 01
      - 🇱🇺 卢森堡 01
      - 🇬🇧 英国 01
      - 🇵🇭 菲律宾 01
      - 🇮🇳 印度 01
      - 🇹🇭 泰国 01
      - 🇲🇾 马来西亚 01
      - 🇦🇪 阿联酋 01
      - 🇦🇺 澳洲 01
      - 🇿🇦 南非 01
      - 🇧🇷 巴西 01
      - 🇦🇷 阿根廷 01
      - 🇻🇳 越南 01
      - 🇺🇦 乌克兰 01
  - name: 🔯 故障转移
    type: fallback
    url: http://www.gstatic.com/generate_204
    interval: 300
    tolerance: 50
    proxies:
      - 懒人节点 01
      - 🇭🇰 香港 01
      - 🇭🇰 香港 02
      - 🇭🇰 香港 03
      - 🇭🇰 香港 04
      - 🇭🇰 香港 05
      - 🇭🇰 香港 06
      - 🇭🇰 香港 07#
      - 🇨🇳 台湾 01
      - 🇨🇳 台湾 02
      - 🇨🇳 台湾 03
      - 🇸🇬 新加坡 01
      - 🇸🇬 新加坡 02
      - 🇸🇬 新加坡 03
      - 🇯🇵 日本 01
      - 🇯🇵 日本 02
      - 🇯🇵 日本 03
      - 🇰🇷 韩国 01
      - 🇰🇷 韩国 02
      - 🇺🇸 美国 01
      - 🇺🇸 美国 02
      - 🇺🇸 美国 03
      - 🇷🇺 俄罗斯 01
      - 🇹🇷 土耳其 01
      - 🇩🇪 德国 01
      - 🇱🇺 卢森堡 01
      - 🇬🇧 英国 01
      - 🇵🇭 菲律宾 01
      - 🇮🇳 印度 01
      - 🇹🇭 泰国 01
      - 🇲🇾 马来西亚 01
      - 🇦🇪 阿联酋 01
      - 🇦🇺 澳洲 01
      - 🇿🇦 南非 01
      - 🇧🇷 巴西 01
      - 🇦🇷 阿根廷 01
      - 🇻🇳 越南 01
      - 🇺🇦 乌克兰 01
  - name: 🔮 负载均衡
    type: load-balance
    strategy: consistent-hashing
    url: http://www.gstatic.com/generate_204
    interval: 300
    tolerance: 50
    proxies:
      - 懒人节点 01
      - 🇭🇰 香港 01
      - 🇭🇰 香港 02
      - 🇭🇰 香港 03
      - 🇭🇰 香港 04
      - 🇭🇰 香港 05
      - 🇭🇰 香港 06
      - 🇭🇰 香港 07#
      - 🇨🇳 台湾 01
      - 🇨🇳 台湾 02
      - 🇨🇳 台湾 03
      - 🇸🇬 新加坡 01
      - 🇸🇬 新加坡 02
      - 🇸🇬 新加坡 03
      - 🇯🇵 日本 01
      - 🇯🇵 日本 02
      - 🇯🇵 日本 03
      - 🇰🇷 韩国 01
      - 🇰🇷 韩国 02
      - 🇺🇸 美国 01
      - 🇺🇸 美国 02
      - 🇺🇸 美国 03
      - 🇷🇺 俄罗斯 01
      - 🇹🇷 土耳其 01
      - 🇩🇪 德国 01
      - 🇱🇺 卢森堡 01
      - 🇬🇧 英国 01
      - 🇵🇭 菲律宾 01
      - 🇮🇳 印度 01
      - 🇹🇭 泰国 01
      - 🇲🇾 马来西亚 01
      - 🇦🇪 阿联酋 01
      - 🇦🇺 澳洲 01
      - 🇿🇦 南非 01
      - 🇧🇷 巴西 01
      - 🇦🇷 阿根廷 01
      - 🇻🇳 越南 01
      - 🇺🇦 乌克兰 01
  - name: 📲 电报消息
    type: select
    proxies:
      - 🚀 节点选择
      - ♻️ 自动选择
      - 🇸🇬 狮城节点
      - 🇭🇰 香港节点
      - 🇨🇳 台湾节点
      - 🇯🇵 日本节点
      - 🇺🇲 美国节点
      - 🇰🇷 韩国节点
      - 🚀 手动切换
      - DIRECT
  - name: 📹 油管视频
    type: select
    proxies:
      - 🚀 节点选择
      - ♻️ 自动选择
      - 🇸🇬 狮城节点
      - 🇭🇰 香港节点
      - 🇨🇳 台湾节点
      - 🇯🇵 日本节点
      - 🇺🇲 美国节点
      - 🇰🇷 韩国节点
      - 🚀 手动切换
      - DIRECT
  - name: 🎥 奈飞视频
    type: select
    proxies:
      - 🎥 奈飞节点
      - 🚀 节点选择
      - ♻️ 自动选择
      - 🇸🇬 狮城节点
      - 🇭🇰 香港节点
      - 🇨🇳 台湾节点
      - 🇯🇵 日本节点
      - 🇺🇲 美国节点
      - 🇰🇷 韩国节点
      - 🚀 手动切换
      - DIRECT
  - name: 📺 巴哈姆特
    type: select
    proxies:
      - 🇨🇳 台湾节点
      - 🚀 节点选择
      - 🚀 手动切换
      - DIRECT
  - name: 📺 哔哩哔哩
    type: select
    proxies:
      - 🎯 全球直连
      - 🇨🇳 台湾节点
      - 🇭🇰 香港节点
  - name: 🌍 国外媒体
    type: select
    proxies:
      - 🚀 节点选择
      - ♻️ 自动选择
      - 🇭🇰 香港节点
      - 🇨🇳 台湾节点
      - 🇸🇬 狮城节点
      - 🇯🇵 日本节点
      - 🇺🇲 美国节点
      - 🇰🇷 韩国节点
      - 🚀 手动切换
      - DIRECT
  - name: 🌏 国内媒体
    type: select
    proxies:
      - DIRECT
      - 🇭🇰 香港节点
      - 🇨🇳 台湾节点
      - 🇸🇬 狮城节点
      - 🇯🇵 日本节点
      - 🚀 手动切换
  - name: 📢 谷歌FCM
    type: select
    proxies:
      - DIRECT
      - 🚀 节点选择
      - 🇺🇲 美国节点
      - 🇭🇰 香港节点
      - 🇨🇳 台湾节点
      - 🇸🇬 狮城节点
      - 🇯🇵 日本节点
      - 🇰🇷 韩国节点
      - 🚀 手动切换
  - name: Ⓜ️ 微软云盘
    type: select
    proxies:
      - DIRECT
      - 🚀 节点选择
      - 🇺🇲 美国节点
      - 🇭🇰 香港节点
      - 🇨🇳 台湾节点
      - 🇸🇬 狮城节点
      - 🇯🇵 日本节点
      - 🇰🇷 韩国节点
      - 🚀 手动切换
  - name: Ⓜ️ 微软服务
    type: select
    proxies:
      - DIRECT
      - 🚀 节点选择
      - 🇺🇲 美国节点
      - 🇭🇰 香港节点
      - 🇨🇳 台湾节点
      - 🇸🇬 狮城节点
      - 🇯🇵 日本节点
      - 🇰🇷 韩国节点
      - 🚀 手动切换
  - name: 🍎 苹果服务
    type: select
    proxies:
      - DIRECT
      - 🚀 节点选择
      - 🇺🇲 美国节点
      - 🇭🇰 香港节点
      - 🇨🇳 台湾节点
      - 🇸🇬 狮城节点
      - 🇯🇵 日本节点
      - 🇰🇷 韩国节点
      - 🚀 手动切换
  - name: 🎮 游戏平台
    type: select
    proxies:
      - DIRECT
      - 🚀 节点选择
      - 🇺🇲 美国节点
      - 🇭🇰 香港节点
      - 🇨🇳 台湾节点
      - 🇸🇬 狮城节点
      - 🇯🇵 日本节点
      - 🇰🇷 韩国节点
      - 🚀 手动切换
  - name: 🎶 网易音乐
    type: select
    proxies:
      - DIRECT
      - 🚀 节点选择
      - ♻️ 自动选择
  - name: 🎯 全球直连
    type: select
    proxies:
      - DIRECT
      - 🚀 节点选择
      - ♻️ 自动选择
  - name: 🛑 广告拦截
    type: select
    proxies:
      - REJECT
      - DIRECT
  - name: 🍃 应用净化
    type: select
    proxies:
      - REJECT
      - DIRECT
  - name: 🐟 漏网之鱼
    type: select
    proxies:
      - 🚀 节点选择
      - ♻️ 自动选择
      - DIRECT
      - 🇭🇰 香港节点
      - 🇨🇳 台湾节点
      - 🇸🇬 狮城节点
      - 🇯🇵 日本节点
      - 🇺🇲 美国节点
      - 🇰🇷 韩国节点
      - 🚀 手动切换
  - name: 🇭🇰 香港节点
    type: url-test
    url: http://www.gstatic.com/generate_204
    interval: 300
    tolerance: 50
    proxies:
      - 🇭🇰 香港 01
      - 🇭🇰 香港 02
      - 🇭🇰 香港 03
      - 🇭🇰 香港 04
      - 🇭🇰 香港 05
      - 🇭🇰 香港 06
      - 🇭🇰 香港 07#
  - name: 🇯🇵 日本节点
    type: url-test
    url: http://www.gstatic.com/generate_204
    interval: 300
    tolerance: 50
    proxies:
      - 🇯🇵 日本 01
      - 🇯🇵 日本 02
      - 🇯🇵 日本 03
  - name: 🇺🇲 美国节点
    type: url-test
    url: http://www.gstatic.com/generate_204
    interval: 300
    tolerance: 150
    proxies:
      - 🇺🇸 美国 01
      - 🇺🇸 美国 02
      - 🇺🇸 美国 03
  - name: 🇨🇳 台湾节点
    type: url-test
    url: http://www.gstatic.com/generate_204
    interval: 300
    tolerance: 50
    proxies:
      - 🇨🇳 台湾 01
      - 🇨🇳 台湾 02
      - 🇨🇳 台湾 03
  - name: 🇸🇬 狮城节点
    type: url-test
    url: http://www.gstatic.com/generate_204
    interval: 300
    tolerance: 50
    proxies:
      - 🇸🇬 新加坡 01
      - 🇸🇬 新加坡 02
      - 🇸🇬 新加坡 03
  - name: 🇰🇷 韩国节点
    type: url-test
    url: http://www.gstatic.com/generate_204
    interval: 300
    tolerance: 50
    proxies:
      - 🇰🇷 韩国 01
      - 🇰🇷 韩国 02
  - name: 🎥 奈飞节点
    type: select
    proxies:
      - DIRECT
rules:
 - DOMAIN-SUFFIX,acl4.ssr,🎯 全球直连
 - DOMAIN-SUFFIX,ip6-localhost,🎯 全球直连
 - DOMAIN-SUFFIX,ip6-loopback,🎯 全球直连
 - DOMAIN-SUFFIX,lan,🎯 全球直连
 - DOMAIN-SUFFIX,local,🎯 全球直连
 - DOMAIN-SUFFIX,localhost,🎯 全球直连
 - IP-CIDR,10.0.0.0/8,🎯 全球直连,no-resolve
 - IP-CIDR,100.64.0.0/10,🎯 全球直连,no-resolve
 - IP-CIDR,127.0.0.0/8,🎯 全球直连,no-resolve
 - IP-CIDR,172.16.0.0/12,🎯 全球直连,no-resolve
 - IP-CIDR,192.168.0.0/16,🎯 全球直连,no-resolve
 - IP-CIDR,198.18.0.0/16,🎯 全球直连,no-resolve
 - IP-CIDR,224.0.0.0/4,🎯 全球直连,no-resolve
 - IP-CIDR6,::1/128,🎯 全球直连,no-resolve
 - IP-CIDR6,fc00::/7,🎯 全球直连,no-resolve
 - IP-CIDR6,fe80::/10,🎯 全球直连,no-resolve
 - IP-CIDR6,fd00::/8,🎯 全球直连,no-resolve
 - GEOIP,CN,🎯 全球直连
 - MATCH,🐟 漏网之鱼
```

### Description

Clash以host网络形式部署在docker上，tag是dev版本，emby以host网络形式部署在相同服务器上，用域名访问ssl端口无法访问，报错ERR_CONNECTION_CLOSED，使用公网IP无法正常访问，使用内网IP可以访问。
