### ISSUE TITLE
[Bug]Raspbery Pi OS 下，Tun在auto-route开启时不创建虚拟端口

### ISSUE THREAD

**Issue by t4rf9** [Dreamacro/clash#2478]
### Verify steps

- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

clash-linux-arm64-v1.12.0

### What OS are you seeing the problem on?

Linux

### Clash config

```yaml
allow-lan: false 
external-controller: 0.0.0.0:9090
external-ui: clash-dashboard
ipv6: true
log-level: info
mixed-port: 7890
mode: Rule
port: 7891

tun:
  enable: true
  stack: system
  # auto-redir: true
  auto-route: true
  auto-detect-interface: true
  dns-hijack:
    - any:53
    - tcp://any:53

dns:
  enable: true                   # set true to enable dns (default is false)
  ipv6: true                     # default is false
  listen: 0.0.0.0:53
  # nameserver-policy:             # lookup domain through assigned nameserver
  #   'www.baidu.com': '114.114.114.114'
  #   '+.internal.crop.com': '10.0.0.1'
  
  default-nameserver:            # resolve dns nameserver host, should fill pure IP
                                 # aka Bootstrap DNS
    - 101.6.6.6
    - 223.5.5.5
    - 114.114.114.114
    - 8.8.8.8
            
  enhanced-mode: fake-ip         # redir-host or fake-ip
  fake-ip-range: 198.18.0.1/16   # if you don't know what it is, don't change it
  use-hosts: true                # lookup hosts and return IP record

  # Hostnames in this list will not be resolved with fake IPs
  # i.e. questions to these domain names will always be answered with their
  # real IP addresses
  # fake-ip-filter:                # fake ip white domain list, aka Always Real IP
  #   - '*.lan'
  #   - localhost.ptlogin2.qq.com

  nameserver:
    - 101.6.6.6
    - 223.5.5.5
    - 114.114.114.114
    # - tls://dns.rubyfish.cn:853  # dns over tls
    # - https://1.1.1.1/dns-query  # dns over https
    # - dhcp://en0 # dns from dhcp
    # - '8.8.8.8#en0' # specific interface for nameserver

  fallback:                      # concurrent request with nameserver, 
                                 # fallback used when GEOIP country isn't CN
    - 101.6.6.6
    - 223.5.5.5

  fallback-filter:
    geoip: true                  # default
    geoip-code: CN
    ipcidr:                      # ips in these subnets will be considered polluted
      - 240.0.0.0/4
   #domain:
    # - '+.google.com'
    # - '+.facebook.com'
    # - '+.youtube.com'
```

### Clash log

```shell
INFO[0000] Start initial compatible provider 🎓 Scholar  
INFO[0000] Start initial compatible provider 🛑 AD       
INFO[0000] Start initial compatible provider ↔️ 6to4    
INFO[0000] Start initial compatible provider 🚀 Accel.   
INFO[0000] Start initial compatible provider 🔔 Info     
INFO[0000] Start initial compatible provider 🧱 GFW      
INFO[0000] HTTP proxy listening at: 127.0.0.1:7891      
INFO[0000] RESTful API listening at: [::]:9090          
INFO[0000] SOCKS proxy listening at: 127.0.0.1:7892     
INFO[0000] Mixed(http+socks) proxy listening at: 127.0.0.1:7890 
INFO[0000] DNS server listening at: [::]:53
```

### Description

在Raspberry Pi OS bullseye下，我按照https://lancellc.gitbook.io/clash/start-clash/clash-tun-mode/setup-system-stack-in-fake-ip-mode中的说明配置，打开了auto-route，也用了sudo来运行clash，但是没有建立任何虚拟网卡，log里也没有相关内容。即使按说明中第三步手动设置，创建的utun0似乎也没有任何作用。与此同时，socks5等代理服务正常。
另外，对于说明的最后一步，“设置网关和dns”表述十分粗略，具体需要如何设置呢？结合在mac上的使用经验，按上述配置文件，tun模式下dns应该会全部被劫持。
