### ISSUE TITLE
[Feature] Modify the provider's parameter(s) before loading them.

### ISSUE THREAD

**Issue by hamedsbt** [Dreamacro/clash#2484]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

I'm using a provider, but I need to change some parameters about it.
Assume my provider returns **ws-opts: path: /websocket** and allows the client to change it however they want, so I want to change **path** to **my-websocket-xyz** for the specified proxy only and change **skip-cert-verify for** all proxies to **false** too.

### Possible Solution

Using an astrik (*) to identify all servers and a specific proxy server using its **address** +**:** +**port**

```
proxy-providers-overrides:
  provider1:
    identifier: * # all servers of provider1
    overrides:
      - path: blabla
      - sni: example.xyz
      
  provider1:
    identifier: "trojan:*" # all trojans of provider1
    overrides:
      - skip-cert-verify: false

  provider1:
    identifier: hkt-1.opensvr.net:443 # specify the server of provider1
    overrides:
      - path: abc
      - skip-cert-verify: true

  provider2:
    identifier: ust-1.opensvr.net:8443 # specify the server of provider2
    overrides:
      - skip-cert-verify: true
      - sni: mainland.xyz
```
