### ISSUE TITLE
[Bug] Docker运行clash，映射端口无法访问

### ISSUE THREAD

**Issue by AmintaCCCP** [Dreamacro/clash#2485]
### Verify steps

- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

dreamacro/clash-premium:latest

### What OS are you seeing the problem on?

Linux

### Clash config

```yaml
port: 7880
socks-port: 7891
mixed-port: 7890
allow-lan: true
bind-address: '*'
mode: rule
log-level: debug
external-controller: '0.0.0.0:9090'
external-ui: /ui
dns:
    enable: true
    ipv6: false
    default-nameserver: [8.8.8.8, 119.29.29.29]
    nameserver: [8.8.8.8, 119.29.29.29]
    fallback: ['tls://1.0.0.1:853', 'https://cloudflare-dns.com/dns-query', 'https://dns.google/dns-query']
    fallback-filter: { geoip: true, ipcidr: [240.0.0.0/4, 0.0.0.0/32] }
rules:
    - 'DOMAIN-SUFFIX,local,DIRECT'
    - 'IP-CIDR,127.0.0.0/8,DIRECT'
    - 'IP-CIDR,172.16.0.0/12,DIRECT'
    - 'IP-CIDR,192.168.0.0/16,DIRECT'
    - 'IP-CIDR,10.0.0.0/8,DIRECT'
    - 'IP-CIDR,17.0.0.0/8,DIRECT'
    - 'IP-CIDR,100.64.0.0/10,DIRECT'
    - 'IP-CIDR,224.0.0.0/4,DIRECT'
    - 'IP-CIDR6,fe80::/10,DIRECT'
    - 'GEOIP,CN,DIRECT'
```

### Clash log

```shell
D02:38:50 INF [Config] initial compatible provider name=自动选择
H02:38:50 INF [Config] initial compatible provider name=***手动打码***
,02:38:50 INF [API] listening addr=[::]:9090
;02:38:50 INF [Inbound] HTTP proxy listening addr=[::]:7880
<02:38:50 INF [Inbound] SOCKS proxy listening addr=[::]:7891
B02:38:50 INF [Inbound] Mixed(http+socks) listening addr=[::]:7890
```

### Description

# 问题描述
小米万兆路由上用docker运行clash，映射端口无法访问。同环境下其他容器没有问题。

# 尝试过的解决方案
- 重启Docker无效
- 彻底删除后重新拉取安装镜像无效（clash和clash-premium都试过）
- 各种修改配置，修改端口无效（确认端口未被占用，存储挂载没问题，配置文件在本地clash客户端使用也没有问题）

# 测试截图
## 容器信息
![WX20230105-104741@2x](https://user-images.githubusercontent.com/74942183/210692264-c9954f21-d304-45c9-86fa-8d05a4f12aea.png)
## clash容器内查看端口及网络
![WX20230105-104911@2x](https://user-images.githubusercontent.com/74942183/210692486-8d0608be-9333-4cca-88a6-03fb3e4bc202.png)
## clash容器外查看
![WX20230105-104656@2x](https://user-images.githubusercontent.com/74942183/210692719-d2f9db71-0b04-4ebe-b379-3315c54f5e0e.png)
