### ISSUE TITLE
[Feature] 配置文件中proxy-groups的简写法

### ISSUE THREAD

**Issue by hinak0** [Dreamacro/clash#2486]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

proxy-groups中能否直接使用某个关键字指代全部的poxies节点？这很好实现，但是可以有效降低配置文件的长度（来自于一个经常手写规则的人）
类似于这样：
```yaml
proxy-groups:
  - name: 节点选择
    type: select
    proxies:
      - ALL_PROXIES # 这指代所有的节点
      - AUTO
      - DIRECT
```
