### ISSUE TITLE
[Bug] clash tun网卡无法访问internet，但使用正常，除了微软应用相关服务

### ISSUE THREAD

**Issue by gg4924** [Dreamacro/clash#2493]
### Verify steps

- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

Premium 2022.11.25

### What OS are you seeing the problem on?

Windows

### Clash config

```yaml
port: 7890
socks-port: 7891
allow-lan: false
mode: rule
log-level: warning
external-controller: 0.0.0.0:9090
external-ui: ui
secret: ''
dns:
  enable: true
  listen: 0.0.0.0:53
  default-nameserver:
    - 192.168.0.1
    - 114.114.114.114
    - 8.8.8.8
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  nameserver:
  - 192.168.0.1
  - 114.114.114.114
  - https://dns.alidns.com/dns-query
  fallback:
  - https://dns.cloudflare.com/dns-query
  - tls://dns.google:853
  - https://1.1.1.1/dns-query
  - tls://8.8.8.8:853
  - https://public.dns.iij.jp/dns-query
  fallback-filter:
    geoip: true
    geoip-code: CN
    ipcidr:
    - 240.0.0.0/4
    domain:
    - +.google.com
    - +.facebook.com
    - +.youtube.com
  fake-ip-filter:
  - +.stun.*.*
  - +.stun.*.*.*
  - +.stun.*.*.*.*
  - +.stun.*.*.*.*.*
  - '*.n.n.srv.nintendo.net'
  - +.stun.playstation.net
  - xbox.*.*.microsoft.com
  - '*.*.xboxlive.com'
  - '*.msftncsi.com'
  - '*.msftconnecttest.com'
  - WORKGROUP
interface-name: 以太网
tun:
  enable: true
  stack: gvisor
  auto-route: true
  dns-hijack:
  - any:53
proxies:
#以下省略
```

### Description

如标题所述，启用clash tun后clash网卡显示无法访问internet，不过使用起来是正常的，除了微软商店相关的应用。
查找过各种解决办法，包括修改注册表禁用ncsi，tun stack在system和gvisor切换，使用ipconfig /renew命令等都无法解决此问题。
最后发现如果将配置中的dns下的fallback设置删除，就会正常，但是这会导致某些国外网站无法访问，可能是由于使用了国内dns结果。然后我将nameserver下的所有服务器都换成国外的，就避开了解析问题，但是访问国内的一些网站速度会变慢。
我所希望的是在启用fallback设置的情况下，让clash tun网卡不再显示无法访问internet提示，能够正常使用微软商店相关的应用。
配置中存在fallback时：
![1](https://user-images.githubusercontent.com/21310130/212273415-42f32ff0-3031-4c3b-bd9b-fd5134f53899.png)
在配置中注释掉fallback时正常，但是会导致上面所述的一些问题：
![Snipaste_2023-01-13_16-27-45](https://user-images.githubusercontent.com/21310130/212273754-4f197926-5ee8-4d4c-8c45-dcfc4d03b9be.png)
![Snipaste_2023-01-13_16-28-19](https://user-images.githubusercontent.com/21310130/212273878-49785913-e0f2-477d-8f14-14f64d9ff30c.png)
谢谢！
