### ISSUE TITLE
负载均衡load-balance的2种类型选择

### ISSUE THREAD

**Issue by jetwalk** [Dreamacro/clash#2502]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

负载均衡load-balance的 strategy 有2种类型：

consistent-hashing 同一个域名下会持续使用同一个ip, 默认选择该项，防止频繁跳ip被网站ban
round-robin 轮询，每访问一个链接，顺序更换节点访问

现在的问题是每次更新订阅后都是默认consistent-hashing
默认想改成round-robin ，请问该如何设置？

功能建议：比如在下面的订阅配置里能否加入参数，优雅地自主切换2种类型
custom_proxy_group=🔮 负载均衡`load-balance`(自建节点)`http://www.gstatic.com/generate_204`180

**Comment by pacmanzou** [comment]
你好,你用的客户端是什么,或者是命令行?

**Comment by SymphonyIceAttack** [comment]
那就自己通过parse功能创建自己的负载均衡组
```yaml
parsers:
  - reg: 'slbable$'
    yaml:
      append-proxy-groups:
        - name: ⚖️ 负载均衡-散列
          type: load-balance
          url: 'http://www.google.com/generate_204'
          interval: 300
          strategy: consistent-hashing
        - name: ⚖️ 负载均衡-轮询
          type: load-balance
          url: 'http://www.google.com/generate_204'
          interval: 300
          strategy: round-robin
      commands:
        - proxy-groups.⚖️ 负载均衡-散列.proxies=[]proxyNames|VIP
        - proxy-groups.0.proxies.0+⚖️ 负载均衡-散列
        - proxy-groups.⚖️ 负载均衡-轮询.proxies=[]proxyNames|VIP
        - proxy-groups.0.proxies.0+⚖️ 负载均衡-轮询
```
