### ISSUE TITLE
[Bug]  provider一直无法更新，提示clash initial proxy provider file "suying666"must have a proxies field，找了很多资料找不到原因了

### ISSUE THREAD

**Issue by GrinderLee** [Dreamacro/clash#2506]
### Verify steps

- [ ]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [ ]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [ ]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

0.20.14

### What OS are you seeing the problem on?

Windows

### Clash config

```yaml
port: 7890
socks-port: 7891
redir-port: 7892
allow-lan: true
mode: rule
log-level: silent
external-controller: 0.0.0.0:9090
secret: ""
#ProxyList:
#    type: http
#    url: https://api.wcc.best/sub?target=clash&url=https%3A%2F%2Fs.suying666.info%2Flink%2F9qiUz9kukhXnFeAm%3Fclash%3D1&insert=false&emoji=true&list=false&tfo=false&scv=false&fdn=false&sort=false&new_name=true
#    interval: 3600
#    path: ./profiles/proxies/suying666.yaml
#    health-check:
#      enable: true
#      url: http://www.gstatic.com/generate_204
#      interval: 300
proxy-providers:
  suying666:
    type: http
    url: https://api.wcc.best/sub?target=clash&url=https%3A%2F%2Fs.suying666.info%2Flink%2F9qiUz9kukhXnFeAm%3Fclash%3D1&insert=false&emoji=true&list=false&tfo=false&scv=false&fdn=false&sort=false&new_name=true
    interval: 3600
    path: ./profiles/proxies/suying666.yaml
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300

proxy-groups:
  - name: PROXY
    type: select
    use:
      - suying666
    proxies:
      - DIRECT

rule-providers:
  reject:
    type: http
    behavior: domain
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/reject.txt
    path: ./ruleset/reject.yaml
    interval: 86400
  icloud:
    type: http
    behavior: domain
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/icloud.txt
    path: ./ruleset/icloud.yaml
    interval: 86400
  apple:
    type: http
    behavior: domain
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/apple.txt
    path: ./ruleset/apple.yaml
    interval: 86400
  google:
    type: http
    behavior: domain
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/google.txt
    path: ./ruleset/google.yaml
    interval: 86400
  proxy:
    type: http
    behavior: domain
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/proxy.txt
    path: ./ruleset/proxy.yaml
    interval: 86400
  direct:
    type: http
    behavior: domain
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/direct.txt
    path: ./ruleset/direct.yaml
    interval: 86400
  private:
    type: http
    behavior: domain
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/private.txt
    path: ./ruleset/private.yaml
    interval: 86400
  gfw:
    type: http
    behavior: domain
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/gfw.txt
    path: ./ruleset/gfw.yaml
    interval: 86400
  greatfire:
    type: http
    behavior: domain
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/greatfire.txt
    path: ./ruleset/greatfire.yaml
    interval: 86400
  tld-not-cn:
    type: http
    behavior: domain
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/tld-not-cn.txt
    path: ./ruleset/tld-not-cn.yaml
    interval: 86400
  telegramcidr:
    type: http
    behavior: ipcidr
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/telegramcidr.txt
    path: ./ruleset/telegramcidr.yaml
    interval: 86400
  cncidr:
    type: http
    behavior: ipcidr
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/cncidr.txt
    path: ./ruleset/cncidr.yaml
    interval: 86400
  lancidr:
    type: http
    behavior: ipcidr
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/lancidr.txt
    path: ./ruleset/lancidr.yaml
    interval: 86400
  applications:
    type: http
    behavior: classical
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/applications.txt
    path: ./ruleset/applications.yaml
    interval: 86400
rules:
  - DOMAIN-KEYWORD,sifang,PROXY
  - DOMAIN-KEYWORD,51cg,PROXY
  - DOMAIN-KEYWORD,ledger,PROXY
  - DOMAIN-KEYWORD,letstalk,PROXY
  - DOMAIN-KEYWORD,adxadserv,PROXY
  - DOMAIN-KEYWORD,155.fun,PROXY
  - DOMAIN-KEYWORD,suying,PROXY
  - DOMAIN-KEYWORD,gtowizard,PROXY
  - PROCESS-NAME,Streamlabs OBS.exe,PROXY
  - PROCESS-NAME,obs-browser-page.exe,PROXY
  - PROCESS-NAME,obs64.exe,PROXY
  - PROCESS-NAME,crashpad_database_util.exe,PROXY
  - PROCESS-NAME,crashpad_handler.exe,PROXY
  - PROCESS-NAME,crash-handler-process.exe,PROXY
  - DOMAIN-KEYWORD,flopzilla,PROXY
  - PROCESS-NAME,GGnet.exe,PROXY
  - DOMAIN-KEYWORD,persistence.biatalk.cc,PROXY
  - DOMAIN-KEYWORD,doax,PROXY
  - DOMAIN-KEYWORD,cloudflare,PROXY
  - DOMAIN-KEYWORD,epicgames,PROXY
  - DOMAIN-KEYWORD,proxyrarbg,PROXY
  - DOMAIN-KEYWORD,steam-chat.com,PROXY
  - DOMAIN-KEYWORD,cloudflare.steamstatic,PROXY
  - DOMAIN-KEYWORD,api.steampowered.com,PROXY
  - DOMAIN-KEYWORD,fandom.com,PROXY
  - DOMAIN-KEYWORD,h2n-up,PROXY
  - DOMAIN-KEYWORD,ohsoft,PROXY
  - PROCESS-NAME,MTGA.exe,PROXY
  - DOMAIN-KEYWORD,mtgo,PROXY
  - DOMAIN-KEYWORD,gyan.dev,PROXY
  - DOMAIN-KEYWORD,ffmpeg,PROXY
  - DOMAIN-KEYWORD,pypi,PROXY
  - DOMAIN-KEYWORD,pythonhost,PROXY
  - DOMAIN-KEYWORD,winget,PROXY
  - PROCESS-NAME,pr-downloader.exe,PROXY
  - PROCESS-NAME,Beyond-All-Reason.exe,PROXY
  - DOMAIN,repos.springrts.com,PROXY
  - DOMAIN-KEYWORD,springrts,PROXY
  - DOMAIN-KEYWORD,bnbstatic,PROXY
  - DOMAIN-KEYWORD,binance,PROXY
  - DOMAIN-KEYWORD,yandex,PROXY
  - DOMAIN-KEYWORD,captcha,PROXY
  - PROCESS-NAME,Discord.exe,PROXY
  - DOMAIN-KEYWORD,discord,PROXY
  - DOMAIN-KEYWORD,itunes.apple,PROXY
  - RULE-SET,applications,DIRECT
  - DOMAIN,clash.razord.top,DIRECT
  - DOMAIN,yacd.haishan.me,DIRECT
  - RULE-SET,private,DIRECT
  - RULE-SET,tld-not-cn,PROXY
  - RULE-SET,gfw,PROXY
  - RULE-SET,greatfire,PROXY
  - RULE-SET,telegramcidr,PROXY
  - MATCH,DIRECT
```

### Clash log

```shell
02:29:04 INF [Config] start initial provider name=suying666
```

### Description

点击切换profiles后log里面就只有这一行，然后弹出窗口报错must have proxies

以前一直用的好好的，配置文件从来没有更改过，我的suying666.yaml的文件里开头第一行也一直是proxies: 。记得几个月前clash更新过一次后就这样无法更新providers里的proxy了，今天更新了这个版本后，直接无法选取以前这个profiles了，选取后弹出窗口后直接不能使用这个profiles了，求救，谢谢
