### ISSUE TITLE
[Bug] Linux无法正常测速ping 和 使用对应节点

### ISSUE THREAD

**Issue by SenkuuChin** [Dreamacro/clash#2515]
### Verify steps

- [ ]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [ ]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

1.13.0

### Clash config

```yaml
mixed-port: 7893
port: 7890
socks-port: 7891
redir-port: 7892
allow-lan: true
bind-address: '*'
mode: rule
log-level: info
external-controller: '0.0.0.0:9090'
external-ui: dashboard
dns:
    enable: true
    listen: 0.0.0.0:53
    ipv6: false
    default-nameserver: [223.5.5.5, 119.29.29.29]
    enhanced-mode: redir-host
    fake-ip-range: 198.18.0.1/16
    use-hosts: true
    nameserver: ['https://doh.pub/dns-query', 'https://dns.alidns.com/dns-query']
    fallback: ['8.8.8.8']
    fallback-filter: { geoip: true, ipcidr: [240.0.0.0/4, 0.0.0.0/32] }
```

### Description

在Linux 上使用 clash，我测速节点大部分都无反应。而Windows端和Android端都是全部正常。特别是我用配置文件默认的dns的fallback为 fallback: ['https://doh.dns.sb/dns-query', 'https://dns.cloudflare.com/dns-query', 'https://dns.twnic.tw/dns-query', 'tls://8.8.4.4:853'] ，更是全部都无法测速成功，当然，我选中节点后运行也是全部没网络。
把这个 fallback 改成只有一个 ：fallback: ['8.8.8.8']，就能成功几个。然后就是测速成功的就能使用。

这个问题只有Linux上出现，安卓和Windows都没出现过。这俩个都是正常的，全部能测能用。

我一直找寻办法，都没有找到，如果这个是个Bug，希望能被修复。如果不是，希望有一个解答。因为找了好久和好多方法都没没办法解决。
