### ISSUE TITLE
[Bug] 1.13.0

### ISSUE THREAD

**Issue by bigguyong** [Dreamacro/clash#2521]
### Verify steps

- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

0.45

### What OS are you seeing the problem on?

Linux

### Clash config

```yaml
Domestic Nodes:
    type: http
    path: "./proxy_provider/demestic-nodes-filter.yaml"
    url: https://gist.xxx.xx
    filter: "CN|Domestic|China|中国|cn|国内"
    interval: 3600
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300
      lazy: true
```

### Clash log

```shell
2023/02/03, 14:00:32.969  [info] initial proxy provider Domestic Nodes error: Get "https://gist.xxx.xx": context deadline exceeded
2023/02/03, 14:00:36.794  [info] initial proxy provider Domestic Nodes error: doesn't match any proxy, please check your filter
```

### Description

原意是过滤出订阅里的本地（国内）节点，但是过滤结果为空时，配置就出错了
考虑到订阅服务的节点变动，会出现某个区域节点为空的情况，希望可以兼容这种情况，支持过滤为空（或者这种情况下返回 DIRECT容错）
