### ISSUE TITLE
[Bug] 部分 Domain 类型的 Rule Provider 无法导入

### ISSUE THREAD

**Issue by xkww3n** [Dreamacro/clash#2526]
### Verify steps

- [X]  确保你使用的是**本仓库**最新的的 clash 或 clash premium 版本 Ensure you are using the latest version of Clash or Clash Premium from **this repository**. 
- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

Premium 2023.01.29

### What OS are you seeing the problem on?

Linux

### Clash config

```yaml
port: 1145
socks-port: 1146
mixed-port: 1145
allow-lan: true
mode: Rule
log-level: debug
external-controller: 127.0.0.1:9810

proxies: REDACTED

proxy-groups:
- type: select
  name: Proxy
  proxies: REDACTED
- type: select
  name: HK
  proxies: REDACTED
- type: select
  name: TW
  proxies: REDACTED
- type: select
  name: JP
  proxies: REDACTED
- type: select
  name: US
  proxies: REDACTED
- type: select
  name: Apple Music
  proxies:
  - DIRECT
  - Proxy
  - US
  - HK
  - TW
  - JP
- type: select
  name: Genshin Impact
  proxies:
  - DIRECT
  - Proxy
  - US
  - HK
  - TW
  - JP
- type: select
  name: Bilibili
  proxies:
  - DIRECT
  - Proxy
  - HK
  - TW
- type: select
  name: Microsoft
  proxies:
  - DIRECT
  - Proxy
- type: select
  name: Google FCM
  proxies:
  - DIRECT
  - Proxy
- type: select
  name: PayPal
  proxies:
  - DIRECT
  - Proxy
- type: select
  name: YouTube
  proxies:
  - DIRECT
  - Proxy
- type: select
  name: Speedtests
  proxies:
  - DIRECT
  - Proxy
- type: select
  name: Protection
  proxies:
  - REJECT
  - DIRECT
  - Final
- type: select
  name: Final
  proxies:
  - Proxy
  - DIRECT

rules:
- RULE-SET,CJMarketing,REJECT
- RULE-SET,Exceptions,Final
- RULE-SET,Protection,Protection
- RULE-SET,Bahamut,TW
- RULE-SET,DMM,JP
- RULE-SET,Niconico,JP
- RULE-SET,Bilibili,Bilibili
- RULE-SET,Speedtests,Speedtests
- RULE-SET,PayPal,PayPal
- RULE-SET,Google_FCM,Google FCM
- RULE-SET,YouTube,YouTube
- RULE-SET,Microsoft,Microsoft
- RULE-SET,CN,DIRECT
- GEOIP,CN,DIRECT
- MATCH,Final

rule-providers:
  Apple_Music:
    type: http
    behavior: domain
    url: https://rules.xkww3n.cyou/clash/apple-music.txt
    path: ./Rules/Apple_Music
    interval: 86400
  AzurLane_EN:
    type: http
    behavior: domain
    url: https://rules.xkww3n.cyou/clash/azurlane-en.txt
    path: ./Rules/AzurLane_EN
    interval: 86400
  Bahamut:
    type: http
    behavior: domain
    url: https://rules.xkww3n.cyou/clash/bahamut.txt
    path: ./Rules/Bahamut
    interval: 86400
  Bilibili:
    type: http
    behavior: domain
    url: https://rules.xkww3n.cyou/clash/bilibili.txt
    path: ./Rules/Bilibili
    interval: 86400
  CJMarketing:
    type: http
    behavior: domain
    url: https://rules.xkww3n.cyou/clash/cjmarketing.txt
    path: ./Rules/CJMarketing
    interval: 86400
  CN:
    type: http
    behavior: domain
    url: https://rules.xkww3n.cyou/clash/geolocation-cn.txt
    path: ./Rules/CN
    interval: 86400
  DMM:
    type: http
    behavior: domain
    url: https://rules.xkww3n.cyou/clash/dmm.txt
    path: ./Rules/DMM
    interval: 86400
  Exceptions:
    type: http
    behavior: domain
    url: https://rules.xkww3n.cyou/clash/exceptions.txt
    path: ./Rules/Special
    interval: 86400
  Google_FCM:
    type: http
    behavior: domain
    url: https://rules.xkww3n.cyou/clash/googlefcm.txt
    path: ./Rules/Google_FCM
    interval: 86400
  LoveLive_SIF_EN:
    type: http
    behavior: domain
    url: https://rules.xkww3n.cyou/clash/lovelivesif-en.txt
    path: ./Rules/LoveLive_SIF_EN
    interval: 86400
  Microsoft:
    type: http
    behavior: domain
    url: https://rules.xkww3n.cyou/clash/microsoft.txt
    path: ./Rules/Microsoft
    interval: 86400
  Niconico:
    type: http
    behavior: domain
    url: https://rules.xkww3n.cyou/clash/niconico.txt
    path: ./Rules/Niconico
    interval: 86400
  PayPal:
    type: http
    behavior: domain
    url: https://rules.xkww3n.cyou/clash/paypal.txt
    path: ./Rules/PayPal
    interval: 86400
  PJSK_TW:
    type: http
    behavior: domain
    url: https://rules.xkww3n.cyou/clash/pjsk-tw.txt
    path: ./Rules/PJSK_TW
    interval: 86400
  Protection:
    type: http
    behavior: domain
    url: https://rules.xkww3n.cyou/clash/protection.txt
    path: ./Rules/Protection
    interval: 86400
  Speedtests:
    type: http
    behavior: domain
    url: https://rules.xkww3n.cyou/clash/speedtests.txt
    path: ./Rules/Speedtests
    interval: 86400
  YouTube:
    type: http
    behavior: domain
    url: https://rules.xkww3n.cyou/clash/youtube.txt
    path: ./Rules/YouTube
    interval: 86400
```

### Clash log

```shell
13:35:08 INF [Config] initial compatible provider name=TW
13:35:08 INF [Config] initial compatible provider name=HK
13:35:08 INF [Config] initial compatible provider name=Final
13:35:08 INF [Config] initial compatible provider name=Protection
13:35:08 INF [Config] initial compatible provider name=YouTube
13:35:08 INF [Config] initial compatible provider name=JP
13:35:08 INF [Config] initial compatible provider name=Genshin Impact
13:35:08 INF [Config] initial compatible provider name=Google FCM
13:35:08 INF [Config] initial compatible provider name=US
13:35:08 INF [Config] initial compatible provider name=Bilibili
13:35:08 INF [Config] initial compatible provider name=Microsoft
13:35:08 INF [Config] initial compatible provider name=PayPal
13:35:08 INF [Config] initial compatible provider name=Speedtests
13:35:08 INF [Config] initial compatible provider name=Apple Music
13:35:08 INF [Config] initial compatible provider name=Proxy
13:35:08 INF [Config] initial rule provider name=CJMarketing
13:35:08 INF [Config] initial rule provider name=Google_FCM
13:35:08 INF [Config] initial rule provider name=Apple_Music
13:35:08 INF [Config] initial rule provider name=CN
13:35:08 INF [Config] initial rule provider name=Protection
13:35:08 FTL [Config] parse config failed error=initial rule provider Protection error: invalid domain
```

### Description

如日志所显示，"Protection" 这一 Domain 类型的 Rule Provider 所提供的 Ruleset 无法被 Clash 处理，提示 "Invaild domain"，且没有更详细的输出。注释掉此 Rule Provider 后即可正常运行，说明别的 Rule Provider 没有问题。
此 Ruleset 可在 <https://rules.xkww3n.cyou/clash/protection.txt> 获得。
以上 Rule Provider 提供的 Ruleset 全部使用同一个脚本生成（<https://github.com/xkww3n/Rules/blob/main/generate.py>），应该不会出现“某一个 Ruleset 有格式错误，而别的却没有”的情况。
