### ISSUE TITLE
[Bug] 配置如下，貌似端口，ip，域名都没问题，却连不上服务器，其他类似配置却能连上

### ISSUE THREAD

**Issue by fredericky123** [Dreamacro/clash#2530]
### Verify steps

- [X]  确保你使用的是**本仓库**最新的的 clash 或 clash premium 版本 Ensure you are using the latest version of Clash or Clash Premium from **this repository**. 
- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

1.13.0

### Clash config

```yaml
# VMess
- name: "vmess1"
  type: vmess
  server: us.pp.ua
  port: 443
  uuid: 19b51791-8017-403d-9914-xxxxxxxx
  alterId: 0
  cipher: auto
  # udp: true
  tls: true
  # skip-cert-verify: true
  servername: us.pp.ua # priority over wss host
  network: ws
  ws-opts:
    path: /oqwbvws
    headers:
      Host: us.pp.ua
    max-early-data: 2048
    early-data-header-name: Sec-WebSocket-Protocol

  # VMess
- name: "vmess2"
  type: vmess
  server: 172.64.xxx.72
  port: 443
  uuid: 19b51791-8017-403d-9914-xxxxxxxx
  alterId: 0
  cipher: auto
  # udp: true
  tls: true
  # skip-cert-verify: true
  servername: uscfworker.xxx.tk # priority over wss host
  network: ws
  ws-opts:
    path: /oqwbvws
    headers:
      Host: uscfworker.xxx.tk
    max-early-data: 2048
    early-data-header-name: Sec-WebSocket-Protocol

# VMess
- name: "vmess3"
  type: vmess
  server: "2606:xxxxx:25f:ce8xxxxxxx5"
  port: 443
  uuid: 19b51791-8017-403d-9914-xxxxxxxx
  alterId: 0
  cipher: auto
  # udp: true
  tls: true
  # skip-cert-verify: true
  servername: us.pp.ua # priority over wss host
  network: ws
  ws-opts:
    path: /oqwbvws
    headers:
      Host: us.pp.ua
    max-early-data: 2048
    early-data-header-name: Sec-WebSocket-Protocol

  # VMess
- name: "vmess4"
  type: vmess
  server: 172.64.xxx.72
  port: 443
  uuid: 19b51791-8017-403d-9914-xxxxxxxx
  alterId: 0
  cipher: auto
  # udp: true
  tls: true
  # skip-cert-verify: true
  servername: us.pp.ua # priority over wss host
  network: ws
  ws-opts:
    path: /oqwbvws
    headers:
      Host: us.pp.ua
    max-early-data: 2048
    early-data-header-name: Sec-WebSocket-Protocol
```

### Description

配置如下，貌似端口，ip，域名都没问题，却连不上服务器，其他类似配置却能连上
vmess1 2 3 能正常连，唯有4连不上服务器
而1说明域名没问题，2用的cf workers反代，说明自选ip没问题，3说明ipv6连接没问题，唯独4的配置连不上服务器(与2同一个自选ip)，同一网络，同时测试，why?
