### ISSUE TITLE
[Question] TUN是否依赖于DNS，已有DNS转发器的情况下是否需要配置DNS和DNS-HIJACK

### ISSUE THREAD

**Issue by Kr536** [Dreamacro/clash#2539]
### Verify steps

- [X]  确保你使用的是**本仓库**最新的的 clash 或 clash premium 版本 Ensure you are using the latest version of Clash or Clash Premium from **this repository**. 
- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

v1.13.0

### What OS are you seeing the problem on?

Linux

### Clash config

```yaml
port: 5555
socks-port: 5556
redir-port: 5557
mixed-port: 5558
allow-lan: true
mode: Rule
log-level: info
external-controller: :5559
external-ui: /etc/clash/yacd/
dns:
  enable: true
  enhanced-mode: redir-host
  nameserver:
    - 223.5.5.5
    - 119.29.29.29
tun:
  enable: true
  stack: system
  dns-hijack:
        - any:53
  auto-route: true
  auto-detect-interface: true
```

### Description

架构描述（涉及网段172.16.11.0/24）：
路由服务位于172.16.11.1
debian虚拟机位于172.16.11.4
该机部署有mosdns、bird、clash
mosdns监听53端口用于dns转发、分流及过滤
bird运行ospf用于同步路由（非cn地址路由到172.16.11.4）
clash用于代理ospf路由到本机的非cn流量

问题描述：
在本机上已有dns转发器，是否需要在clash中配置dns和dns-hijack，按照上述配置文件运行时未生成tun接口，代理端口均正常。
