### ISSUE TITLE
[Feature] Premium 版开启 tun.auto-route 能否不全局覆盖 IPv6 的路由？

### ISSUE THREAD

**Issue by samurai00** [Dreamacro/clash#2557]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### 大致现象说明

配置 clash 为 tun 模式，并启用 auto-route 之后，会导致 IPv6 路有全都失效。

### 情况

如果不关注 IPv6，只关注 IPv4 的话，没什么问题，可以正常上网，也可以作为旁路网关让其他设备上网。
而且，同时单独开一个 wireguard（不是 clash 中作为客户端的）作为网关，也没有问题。路由也正常起作用。

但是，如果 wireguard （不是 clash 中作为客户端的）中配了 IPv6 的话，比如 `2001:203:666::/64` 是 wireguard 的网段。这个路由好像会被 clash 覆盖掉，导致失效。如果把 clash 关掉的话，或者不启用 auto-route 的话，会恢复正常。

```
> ip -6 route                   
::1 dev lo proto kernel metric 256 pref medium
2001:203:666::/64 dev wg0 proto kernel metric 256 pref medium
```

```
❯ ip route get 2001:203:666::2
RTNETLINK answers: No route to host
```

### 需求

1. 有没有办法，只让 clash 处理 IPv4？
2. 或者有没有办法，让 clash 完全忽略一些指定的路由？该由 wireguard 处理，还是交给 wireguard 处理？

-----
clash 版本：

``` shell
❯ clash -v
Clash 2023.02.16 linux amd64 with go1.20.1 Thu Feb 16 13:44:40 UTC 2023
```

关键配置：

```yaml
port: 7890
socks-port: 7891
redir-port: 7892
allow-lan: true
mode: Rule
log-level: info
external-controller: '0.0.0.0:9090'
secret: ''
cfw-latency-url: 'http://cp.cloudflare.com/generate_204'

dns:
  enable: true
  listen: 0.0.0.0:5753
  ipv6: false
  nameserver:
    - 127.0.0.1:53
  default-nameserver:
    - 223.5.5.5
  enhanced-mode: fake-ip
  fake-ip-range: 198.19.0.1/16

interface-name: ens9
tun:
  enable: true
  stack: system
  auto-route: true
  auto-redir: true
  dns-hijack:
    - 198.19.0.2:53
    - 223.5.5.5:53
    - 119.29.29.29:53
```
