### ISSUE TITLE
RESTful API如何切换名字是中文的节点？

### ISSUE THREAD

**Issue by deuteros-gex** [Dreamacro/clash#2564]
### Verify steps

- [X]  确保你使用的是**本仓库**最新的的 clash 或 clash premium 版本 Ensure you are using the latest version of Clash or Clash Premium from **this repository**. 
- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

1.13.0

### What OS are you seeing the problem on?

Windows

### Clash config

```yaml
port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090

proxies:
  - name: Mario

  - name: 路易吉

proxy-groups:
  - name: Nintendo
    type: select
    proxies:
      - Mario
      - 路易吉
```

### Clash log

```shell
也没什么log，纯粹不会用。。
```

### Description

windows下实测通过，clash官方内核在cmd里直接跑，没有使用cfw之类的GUI。
`curl -X PUT --data "{\"name\":\"Mario\"}" http://127.0.0.1:9090/proxies/Nintendo`
确实可以把（命令中看着别扭的反斜杠是windows cmd要求的转义字符，其他系统应该不这样）使用的节点切到Mario上。
但是对于中文节点，下面这样做
`curl -X PUT --data "{\"name\":\"路易吉\"}" http://127.0.0.1:9090/proxies/Nintendo`
就不行了，会返回`{"message":"Body invalid"}`

谷歌了一下，说是urlencode可破，试着把`路易吉`用urlencode转成`%E8%B7%AF%E6%98%93%E5%90%89`
然后按下面的写法：
`curl -X PUT --data-urlencode "{\"name\":\"%E8%B7%AF%E6%98%93%E5%90%89\"}" http://127.0.0.1:9090/proxies/Nintendo`
也还是没用，还是会返回`{"message":"Body invalid"}`

所以在用curl控制RESTful API时，中文字符以及各种特殊符号（标点符号，emoji）有办法处理吗？
