### ISSUE TITLE
[Bug] IPv6 unavailable: no route to host

### ISSUE THREAD

**Issue by felicia-wen** [Dreamacro/clash#2565]
### Verify steps

- [X]  确保你使用的是**本仓库**最新的的 clash 或 clash premium 版本 Ensure you are using the latest version of Clash or Clash Premium from **this repository**. 
- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

since 2022.11.25-premium

### What OS are you seeing the problem on?

Linux

### Clash config

```yaml
port: 8888
socks-port: 8889
mixed-port: 8899
allow-lan: true
ipv6: true
mode: Rule
log-level: info
external-controller: 0.0.0.0:6170
#external-ui: "/usr/share/yacd"
experimental:
  ignore-resolve-fail: true
profile:
  # Store the `select` results in $HOME/.config/clash/.cache
  # set false If you don't want this behavior
  # when two different configurations have groups with the same name, the selected values are shared
  store-selected: true
  store-fake-ip: true
interface-name: enaphyt4i0
tun:
  enable: true
  stack: system
  auto-redir: true
  auto-route: true
```

### Clash log

```shell
00:52:11 INF [DNS] server listening addr=127.0.0.1:7874
00:52:11 INF [Inbound] HTTP proxy listening addr=[::]:8888
00:52:11 INF [API] listening addr=[::]:6170
00:52:11 INF [Inbound] SOCKS proxy listening addr=[::]:8889
00:52:11 INF [Inbound] Mixed(http+socks) listening addr=[::]:8899
00:52:11 INF [Inbound] TUN listening iface=utun gateway=198.18.0.1
```

### Description

Unable to ping any ipv6 address and access the host via other devices on the local network when running with TUN mode since version 2022.11.25 premium.
```sh
$ ping '2001:4860:4860::8888'
ping: connect: No route to host
```
It worked fine with the 2022.08.26 premium.
