### ISSUE TITLE
[Feature] 根据`用户名`来匹配 rules

### ISSUE THREAD

**Issue by panmenghan** [Dreamacro/clash#2570]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

我想"我的应用"能通过 clash 来把各种代理转换成 http 代理, 然后"我的应用"能自己决定哪个 connection 走哪个代理.

我目前能想到的是通过用"用户名"映射的方式来让应用自己决定用哪个代理, 假设 clash 的配置如下:
```yaml
port: 7890
  
proxies:
  - name: "ss1"
    server: server1

  - name: "ss2"
    server: server2 

  - name: "ss3"
    server: server3

# 每个代理建立一个相对应的用户
authentication:
 - "user1:pass"
 - "user2:pass"
 - "user3:pass"

# 能否实现以下功能? 
rules:
 - USER,"user1","ss1" # 让名为"user1"的用户, 用名为"ss1"的代理
 - USER,"user2","ss2" # 让名为"user2"的用户, 用名为"ss2"的代理
 - USER,"user3","ss3" # 让名为"user3"的用户, 用名为"ss3"的代理
```

既用这个 http://**user1**:pass@localhost:7890 访问 clash 的走 **ss1** 代理
既用这个 http://**user2**:pass@localhost:7890 访问 clash 的走 **ss2** 代理
