### ISSUE TITLE
[Bug] 新版clash-core配置fake-ip对于ip规则未处理

### ISSUE THREAD

**Issue by feileb** [Dreamacro/clash#2571]
### Verify steps

- [X]  确保你使用的是**本仓库**最新的的 clash 或 clash premium 版本 Ensure you are using the latest version of Clash or Clash Premium from **this repository**. 
- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

2023.02.16 Premium

### What OS are you seeing the problem on?

Windows

### Clash config

```yaml
cfw配置:

showNewVersionIcon: true
hideAfterStartup: false
randomControllerPort: true
runTimeFormat: "hh : mm : ss"
trayOrders:
  - - icon
  - - status
    - traffic
    - text
hideTrayIcon: false
mixinText: |2
    mixin: # object
      dns:
        enable: true
        ipv6: false
        #enhanced-mode: redir-host
        enhanced-mode: fake-ip
        #fake-ip-range: 198.18.0.1/16
        fake-ip-filter:
          - '*.lan'
      tun:
        enable: true
        stack: gvisor #gvisor|system
        dns-hijack:
          - 198.18.0.2:53
        auto-route: true
        auto-detect-interface: true
connShowProcess: true
showTrayProxyDelayIndicator: true
randomMixedPort: false
theme: 0

config.yml:

mixed-port: 7890
allow-lan: false
external-controller: 127.0.0.1:3165
secret: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
log-level: error
ipv6: false

profile部分配置:

    - IP-CIDR,202.80.104.28/32,proxy2,no-resolve
    - IP-CIDR,202.80.104.29/32,proxy2,no-resolve
```

### Clash log

```shell
14:03:35 WRN [TCP] dial failed error=dial tcp4 202.80.104.28:8484: i/o timeout proxy=🐟 漏网之鱼 lAddr=198.18.0.1:8261 rAddr=xxx.com:8484 rule=Match rulePayload=
```

### Description

以前使用redir-host模式没有问题，域名嗅探和ip规则都可以正常代理

本次更新后没有redir-host模式，只能使用fake-ip或者不使用enhance-mode：
1，使用fake-ip模式，域名嗅探可以正常代理，但是ip规则未匹配规则，默认都走了direct直连
2，如果不使用enhanced-mode，ip规则可以正常代理，但是嗅探域名又失效了
