### ISSUE TITLE
clash premium 能够判断出来ip 是内网还是外网的，这个怎么实现的？

### ISSUE THREAD

**Issue by liushiqi1001** [Dreamacro/clash#2572]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

```yaml
proxy-groups:
- name: relay
  proxies:
  - proxy
  - relay-service
  type: relay
- _index: 1
  interval: "2"
  name: proxy
  proxies:
  - V4-505|新加坡|x2.0
  - V4-265|新加坡|x2.5
  - V4-650|新加坡|x2.0
  - V4-478|香港|x2.0
  - V4-426|香港|x2.0
  - V4-453|香港|x1.5
  - V4-503|新加坡|x2.0
  - V4-550|香港|x1.5
  - V4-522|日本|x1.5
  - V4-611|香港|x2.0
  - V4-597|广东-香港|x2.0
  - V4-649|新加坡|x2.5
  - V4-578|新加坡|x2.5
  - V4-489|香港|x2.0
  - V4-523|日本|x1.5
  - V4-548|香港|x1.5
  - V4-292|新加坡|x2.0
  - V4-524|日本|x1.5
  type: load-balance
  url: https://aaaaaa.com/test.txt
rules:
- MATCH,relay

```
看日志用的是relay规则
17:56:52 INF [TCP] connected lAddr=198.18.0.1:34424 rAddr=172.20.53.185:22 mode=rule rule=Match() proxy=relay

使用 clash-premium 却不影响链接局域网的ip地址，可以正常访问内网服务，也不影响google，这个是什么原理？？？？
求教！！！！！！
