### ISSUE TITLE
[Feature] 规则分流的时候只能通过ip，无法使用域名

### ISSUE THREAD

**Issue by Giresharu** [Dreamacro/clash#2578]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

https://github.com/Dreamacro/clash/issues/2245
和这个Issue的问题一样。但是我尝试了添加 dns-hijack: 127.0.0.1:8053 ，结果是直接没网了。
 (我用的是padavan固件，似乎它的默认dns解析相关的端口是8053，53端口我也尝试过了，结果是一样的)

是不是路由器其他地方还要修改一下设置呢？
我在网络方面是完全是小白，对DNS以及上下游之类的完全没有了解。连续几天的谷歌也没有啥收获。
这个固件相关的教程也没有多少讲解这些的，固件来源的恩山论坛问了也没人回。无奈之下只好来这里问一问。
希望大佬能指导一下，告诉我应该怎么做。

clash中dns相关的配置我是这么写的：

``` yaml
dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:8053

  default-nameserver:
    - 119.29.29.29
    - 223.5.5.5

  nameserver:
    - https://doh.pub/dns-query
    - https://dns.alidns.com/dns-query

  fallback:
    - https://dns.google/dns-query
    - https://1.1.1.1/dns-query
    - tcp://8.8.8.8:53
    - tcp://8.8.4.4:53
    - tcp://208.67.222.222:443
    - tcp://208.67.220.220:443

  fallback-filter:
    geoip: true
    geoip-code: CN
    ipcidr:
      - 240.0.0.0/4
      - 127.0.0.1/8
      - 0.0.0.0/32
    domain:
      - "+.google.com"
      - "+.googleapis.com"
      - "+.youtube.com"
      - "+.appspot.com"
      - "+.telegram.com"
      - "+.facebook.com"
      - "+.twitter.com"
      - "+.blogger.com"
      - "+.gmail.com"
      - "+.gvt1.com"
      
sniffer:
  enable: true
  override-destination: true
  sniff:
    http: { ports: [80, 8080] }
    tls: { ports: [443, 8443] }
  skip-domain:
    #Apple
    - "courier.push.apple.com"
    #mi
    - "Mijia Cloud"

tun:
  enable: true
  stack: system
  dns-hijack:
    - 127.0.0.1:8053
  auto-route: true
```

路由器设置中的 LAN 内网 DNS 为空，然后 dnsmaqs.conf 的配置是这样的：

``` yaml
# Custom user conf file for dnsmasq
# Please add needed params only!

### Web Proxy Automatic Discovery (WPAD)
dhcp-option=252,"\n"

### Set the limit on DHCP leases, the default is 150
#dhcp-lease-max=150

### Add local-only domains, queries are answered from hosts or DHCP only
#local=/router/localdomain/

### Examples:

### Enable built-in TFTP server
#enable-tftp

### Set the root directory for files available via TFTP.
#tftp-root=/opt/srv/tftp

### Make the TFTP server more secure
#tftp-secure

### Set the boot filename for netboot/PXE
#dhcp-boot=pxelinux.0

# 过滤 IPv6（AAAA）查询请求
#filter-aaaa


#ss_tproxy
dns-forward-max=1000 #ss_tproxy
min-cache-ttl=1800 #ss_tproxy
conf-dir=/tmp/ss_tproxy/dnsmasq.d #ss_tproxy

```
dnsmasq.servers 则是：

``` yaml

# Custom user servers file for dnsmasq
# Example:
# 特定域名的自定义DNS设置例子:
#server=/mit.ru/izmuroma.ru/10.25.11.30
server=/update.adbyby.com/180.76.76.76#53

```

WAN 外网设置里还有个 DNS 设置，设置为 127.0.0.1 （无法填写#或者:来写端口）。
IPv4 硬件加速是关闭的。

其他 DNS 相关的插件比如 smartDNS 和Chinadns_ng 我都没有开启。

然后是路由器里启动 Clash 时的日志，不知道有没有啥作用：
···
Mar  4 03:02:00 【clash】: 初始化 clash dns 配置
Mar  4 03:02:05 【clash】: 变更 clash dns 端口 listen 0.0.0.0:8053 跳过自动开启第三方 DNS 程序但是继续把DNS绑定到 8053 端口的程序
Mar  4 03:02:06 【clash】: 初始化 clash 配置
Mar  4 03:02:07 【clash】: 允许局域网的连接
Mar  4 03:02:11 【clash】: redir 代理端口：7892
Mar  4 03:02:11 【clash】: 删除 Clash 配置文件中原有的 DNS 配置
Mar  4 03:02:16 【clash】: 设置日志输出: error
Mar  4 03:02:17 【clash】: 将 DNS 配置 /tmp/clash/dns.yml 以覆盖的方式与 /opt/app/clash/config/config.yaml 合并
Mar  4 03:02:17 【clash】: 初始化 clash 配置完成！实际运行配置：/opt/app/clash/config/config.yaml
Mar  4 03:02:17 【clash】: 仅代理 TCP 流量
Mar  4 03:02:17 【clash】: 启动路由自身流量走透明代理
Mar  4 03:02:17 【clash】: 运行 /opt/bin/clash
Mar  4 03:02:27 【clash】: 启动成功
Mar  4 03:02:27 【clash】: 【自动】设置 ss_tproxy 配置文件，配置导入中...
Mar  4 03:02:29 【clash】: 【自动】设置 ss_tproxy 配置文件，完成配置导入
Mar  4 03:02:30 【sh_ss_tproxy.sh】: flush_postrule
Mar  4 03:02:30 【sh_ss_tproxy.sh】: stop
Mar  4 03:02:31 dnsmasq[30980]: exiting on receipt of SIGTERM
Mar  4 03:02:33 【ss_tproxy】: 运行 /etc/storage/script/sh_ss_tproxy.sh
Mar  4 03:02:33 【sh_ss_tproxy.sh】: start
Mar  4 03:02:35 dnsmasq[32489]: exiting on receipt of SIGTERM
Mar  4 03:02:39 【sh_ss_tproxy.sh】: 完成加载 iptables 转发规则....
Mar  4 03:02:39 【update_gfwlist】: 开始加载 gfwlist 规则....
Mar  4 03:02:39 【update_gfwlist】: 配置匹配，完成加载 gfwlist 规则....
Mar  4 03:02:39 【update_chnroute】: 开始加载 chnroute 规则....
Mar  4 03:02:39 【update_chnroute】: 配置匹配，完成加载 chnroute 规则....
Mar  4 03:02:44 dnsmasq[394]: exiting on receipt of SIGTERM
Mar  4 03:02:44 【update_chnlist_mini】: 配置匹配，完成加载 chnlist_mini 规则....
Mar  4 03:02:46 【ss_tproxy】: 启动成功
Mar  4 03:02:46 【clash】: 同时将透明代理规则应用到 OUTPUT 链, 让路由自身流量走透明代理
Mar  4 03:02:46 【clash】: 完成 透明代理 转发规则设置
Mar  4 03:02:46 【clash】: 启动 clash DNS 防止域名污染【端口 ::1#8053】
Mar  4 03:02:47 【ss_tproxy】: 守护进程启动
Mar  4 03:02:47 【clash】: 启动后若发现一些网站打不开, 估计是 DNS 被污染了. 解决 DNS 被污染方法：
Mar  4 03:02:47 【clash】: ①电脑设置 DNS 自动获取路由 ip。检查 hosts 是否有错误规则。
Mar  4 03:02:47 【clash】: ②电脑运行 cmd 输入【ipconfig /flushdns】, 清理浏览器缓存。
Mar  4 03:02:48 【clash】: 守护进程启动
···
