### ISSUE TITLE
[Bug] 上传被记为下载

### ISSUE THREAD

**Issue by returnL** [Dreamacro/clash#2579]
### Verify steps

- [X]  确保你使用的是**本仓库**最新的的 clash 或 clash premium 版本 Ensure you are using the latest version of Clash or Clash Premium from **this repository**. 
- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

Premium 2023.03.03

### What OS are you seeing the problem on?

Windows

### Clash config

```yaml
tun:
  enable: true
  stack: system
  auto-route: true
  # auto-detect-interface: true
  dns-hijack:
    - any:53
    - tcp://any:53
interface-name: WLAN
dns:
  enable: true
  ipv6: true
  listen: 127.0.0.1:8853
  enhanced-mode: fake-ip
  fake-ip-range: 28.0.0.0/8
  default-nameserver:
    - 119.29.29.29
  nameserver:
    - dhcp://WLAN
    - https://
    - tls://
  fallback:
    - https://doh.pub/dns-query
  fallback-filter:
    geoip: false
    geoip-code: CN
    ipcidr:
      - 0.0.0.0/32
  fake-ip-filter:
    - '*.msftncsi.com'
    - '*.msftconnecttest.com'
    - '*.mcdn.bilivideo.cn'
    - WORKGROUP
    - ntp.ntsc.ac.cn
```

### Clash log

```shell
[2023-03-04 10:13:17][INFO] [TCP] connected lAddr=28.0.0.1:9188 rAddr=dsm01pap001.storage.live.com:443 mode=rule rule=RuleSet(OneDrive) proxy=Ⓜ️ OneDrive[DIRECT]
[2023-03-04 10:11:25][INFO] [TCP] connected lAddr=28.0.0.1:9202 rAddr=api.onedrive.com:443 mode=rule rule=RuleSet(OneDrive) proxy=Ⓜ️ OneDrive[DIRECT]
[2023-03-04 10:11:26][INFO] [TCP] connected lAddr=28.0.0.1:9206 rAddr=dsm01pap001files.storage.live.com:443 mode=rule rule=RuleSet(OneDrive) proxy=Ⓜ️ OneDrive[DIRECT]
```

### Description

最新版本的P核中，上传流量被统计为下载流量。比如我向OneDrive中上传一个文件，在Clash Dashboard中显示为下载
<img width="272" alt="Snipaste_2023-03-04_10-10-31" src="https://user-images.githubusercontent.com/44701395/222870496-04d9bb2e-d0d9-4ab5-9472-17c395e434cf.png">
<img width="899" alt="Snipaste_2023-03-04_10-10-53" src="https://user-images.githubusercontent.com/44701395/222870505-bf56ed7e-776a-4850-a0cc-a4ed728bd47a.png">
