### ISSUE TITLE
tunnels 怎么使用，看不懂

### ISSUE THREAD

**Issue by spacexnasa** [Dreamacro/clash#2581]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

如题

tunnels:
  # one line config
  - tcp/udp,127.0.0.1:6553,114.114.114.114:53,backhome
  - tcp,127.0.0.1:6666,rds.mysql.com:3306,corp
  # full yaml config
  - network: [tcp, udp]
    address: 127.0.0.1:7777
    target: target.com
    proxy: corp

backhome，或者 corp 该配置什么

**Comment by pfangzhi** [comment]
tcp,0.0.0.0:80,10.0.0.2:80,abc

本机路由器的80端口映射成通过abc代理访问的10.0.0.2的端口80

**Comment by pfangzhi** [comment]
abc是你的节点名字，比如你必须通过abc的加密通道才能访问到10.2这个主机。

**Comment by spacexnasa** [comment]
> abc是你的节点名字，比如你必须通过abc的加密通道才能访问到10.2这个主机。

那这个还不如使用rule-set 了

**Comment by cjwddtc** [comment]
> > abc是你的节点名字，比如你必须通过abc的加密通道才能访问到10.2这个主机。
> 
> 那这个还不如使用rule-set 了

这个功能应该是被设计出来用作dns的，clash目前的dns方式很秀，但是很不靠谱（我这边现在好多dns的dtoh之类的查询都被墙了），这是一个workaround。

**Comment by Infatuation-Fei** [comment]
用tunnel来代理DNS流量应该怎么配置呢

**Comment by Infatuation-Fei** [comment]
> > > abc是你的节点名字，比如你必须通过abc的加密通道才能访问到10.2这个主机。
> > 
> > 
> > 那这个还不如使用rule-set 了
> 
> 这个功能应该是被设计出来用作dns的，clash目前的dns方式很秀，但是很不靠谱（我这边现在好多dns的dtoh之类的查询都被墙了），这是一个workaround。

用tunnel来代理DNS流量应该怎么配置呢

**Comment by rbbt065** [comment]
> > > > abc是你的节点名字，比如你必须通过abc的加密通道才能访问到10.2这个主机。
> > > 
> > > 
> > > 那这个还不如使用rule-set 了
> > 
> > 
> > 这个功能应该是被设计出来用作dns的，clash目前的dns方式很秀，但是很不靠谱（我这边现在好多dns的dtoh之类的查询都被墙了），这是一个workaround。
> 
> 用tunnel来代理DNS流量应该怎么配置呢

https://github.com/Dreamacro/clash/issues/2642#issue-1640770378

**Comment by BirkhoffLee** [comment]
> > > > abc是你的节点名字，比如你必须通过abc的加密通道才能访问到10.2这个主机。
> > > 
> > > 
> > > 那这个还不如使用rule-set 了
> > 
> > 
> > 这个功能应该是被设计出来用作dns的，clash目前的dns方式很秀，但是很不靠谱（我这边现在好多dns的dtoh之类的查询都被墙了），这是一个workaround。
> 
> 用tunnel来代理DNS流量应该怎么配置呢

```yaml
tunnels:
  - network: [tcp, udp]
    address: 0.0.0.0:5301
    target: 114.114.114.114:53
    proxy: CN Outbound
  - network: [tcp, udp]
    address: 0.0.0.0:5302
    target: 1.1.1.2:53
    proxy: Cloudflare Network
  - network: [tcp, udp]
    address: 0.0.0.0:5303
    target: dns.alidns.com:443
    proxy: CN Outbound
```
