### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by Simonskiii** [Dreamacro/clash#2582]
### Verify steps

- [X]  确保你使用的是**本仓库**最新的的 clash 或 clash premium 版本 Ensure you are using the latest version of Clash or Clash Premium from **this repository**. 
- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

2023.02.16 Premium 10821

### What OS are you seeing the problem on?

Windows

### Clash config

```yaml
allow-lan: false
bind-address: 127.0.0.1
dns:
  ake-ip-range: 198.18.0.1/16
  default-nameserver:
  - 114.114.114.114
  - 119.29.29.29
  - 223.5.5.5
  enable: false
  enhanced-mode: fake-ip
  fallback-filter:
    ipcidr:
    - 240.0.0.0/4
    domain:
    - '+.google.com'
    - '+.facebook.com'
    - '+.youtube.com'
    - '+.bing.com'
  ipv6: false
  nameserver:
  - https://223.6.6.6/dns-query
  - https://doh.pub/dns-query
external-controller: 127.0.0.1:19090
log-level: warning
mixed-port: 9981
mode: rule
proxies:
- name: us3
  server: 111
  port: 443
  type: vmess
  uuid: 111
  alterId: 0
  cipher: none
  network: grpc
  tls: true
  servername: 111
  skip-cert-verify: true
  grpc-opts:
    grpc-service-name: "111"



- name: hk1
  server: 111
  port: 443
  type: vmess
  uuid: 111
  alterId: 0
  cipher: none
  network: grpc
  tls: true
  servername: 111
  skip-cert-verify: true
  grpc-opts:
    grpc-service-name: "111"

- name: hk2
  server: 111
  port: 443
  type: vmess
  uuid: 111
  alterId: 0
  cipher: none
  network: grpc
  tls: true
  servername: 111
  skip-cert-verify: true
  grpc-opts:
    grpc-service-name: "111"

- name: hk3
  server: 111
  port: 443
  type: vmess
  uuid: 111
  alterId: 0
  cipher: none
  network: grpc
  tls: true
  servername: 111
  skip-cert-verify: true
  grpc-opts:
    grpc-service-name: "111"


- name: hk4
  server: 111
  port: 443
  type: vmess
  uuid: 111
  alterId: 0
  cipher: none
  network: grpc
  tls: true
  servername: 111
  skip-cert-verify: true
  grpc-opts:
    grpc-service-name: "111"

proxy-groups:
- name: PROXY
  proxies:
  - 全球智能
  - hk1
  - hk2
  - us3
  - hk3
  - hk4
  type: select
- interval: 360
  name: 全球智能
  proxies:
  - hk1
  - hk2
  - hk3
  - hk4
  type: url-test
  url: http://www.gstatic.com/generate_204
- name: US
  proxies:
  - us3
  type: select
 
rules:
  - DOMAIN-KEYWORD,google,PROXY
  - DOMAIN-KEYWORD,bing,US
  - DOMAIN,*.bing.com,US
  - DOMAIN-KEYWORD,msn,US
  - DOMAIN-KEYWORD,openai,US
  - RULE-SET,proxy,PROXY
  - GEOIP,LAN,DIRECT
  - GEOIP,CN,DIRECT
  - DOMAIN,clash.razord.top,DIRECT
  - DOMAIN,yacd.haishan.me,DIRECT
  - MATCH,PROXY
```

### Description

之前把us3节点放在PROXY里，没有新建US组，没有这个问题。
后来，设置的分流，bing默认走US组。
PROXY组没有问题，但是US组过一段时间就会出现断流的问题，刷新一两分钟就连上了，客户端日志中是有和bing的TCP连接的。
盲猜过了一段时间再次访问bing，clash 连接US组的端口换了，但是还是使用之前的端口。
不知道这个问题应该怎么解决呀？
