### ISSUE TITLE
[Question] 非同一网段下 子网互通 fakeip不通

### ISSUE THREAD

**Issue by Victor2333** [Dreamacro/clash#2584]
### Verify steps

- [X]  确保你使用的是**本仓库**最新的的 clash 或 clash premium 版本 Ensure you are using the latest version of Clash or Clash Premium from **this repository**. 
- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

clash-premium:2023.03.04

### What OS are you seeing the problem on?

Linux

### Clash config

```yaml
dns:
  enable: true
  listen: 0.0.0.0:53
  default-nameserver:
    - 8.8.8.8
  enhanced-mode: fake-ip # or redir-host (not recommended)
  fake-ip-range: 10.1.0.0/16 # Fake IP addresses pool CIDR
  fake-ip-filter:
    - localhost
  nameserver:
    - *
  fallback:
    - 8.8.8.8 # default value
    - https://1.1.1.1/dns-query # DNS over HTTPS
  fallback-filter:
    geoip: true
    geoip-code: CN
tun:
  enable: true
  stack: system # or gvisor
  dns-hijack:
    - any:53
    - tcp://any:53
  auto-route: true
  auto-detect-interface: true
```

### Clash log

[2023-03-05 22:49:35][DEBUG] [UDP] accept session lAddr=10.0.2.2:58830 rAddr=www.google.com.hk:443 inbound=TUN
[2023-03-05 22:49:35][DEBUG] [Matcher] find process failed error=process not found addr=www.google.com.hk
[2023-03-05 22:49:35][INFO] [UDP] connected lAddr=10.0.2.2:58830 rAddr=www.google.com.hk:443 mode=rule rule=RuleSet(proxy) proxy=***********
[2023-03-05 22:49:38][DEBUG] [UDP] accept session lAddr=10.0.2.2:53889 rAddr=optimizationguide-pa.googleapis.com:443 inbound=TUN
[2023-03-05 22:49:38][DEBUG] [Matcher] find process failed error=process not found addr=optimizationguide-pa.googleapis.com
[2023-03-05 22:49:38][INFO] [UDP] connected lAddr=10.0.2.2:53889 rAddr=optimizationguide-pa.googleapis.com:443 mode=rule rule=RuleSet(proxy) proxy=***********
[2023-03-05 22:49:38][DEBUG] [UDP] accept session lAddr=10.1.0.32:443 rAddr=10.0.2.2:53889 inbound=TUN
[2023-03-05 22:49:38][DEBUG] [Matcher] find process failed error=process not found addr=10.0.2.2
[2023-03-05 22:49:38][INFO] [UDP] connected lAddr=10.1.0.32:443 rAddr=10.0.2.2:53889 mode=rule rule=RuleSet(lancidr) proxy=direct[DIRECT]

### Description

step by step

1.路由器 10.0.0.0/24
静态ip配置了fake ip 网段网关设为macvlan 的docker clash

2.clash ip 10.0.0.254 (fake ip 10.1.0.0/16)

3.内网访问无问题
eg. 10.0.0.2 ping fakeip 10.1.0.1 success

4.跨子网访问无返回
eg. 三层交换机ip 10.0.0.2 Lan子网10.0.2.0/24
路由器配置了静态路由 
10.0.2.0/24 -> 10.0.0.2(三层交换机子网转发规则)
10.1.0.0/16 -> 10.0.0.241 (fakeip 转发规则)

5.clash docker ping 10.0.2.2 success
6.10.0.2.2 ping clash(10.0.0.241) success
7.clash docker ping fakeip 10.1.0.1 success
**8.10.0.2.2 ping fakeip 10.1.0.1 failed**

9. 若三层交换机配置了nat 则无问题 但是子网真实ip就被nat掉了
`iptables -t nat -A POSTROUTING -o eth+ -j MASQUERADE
`

<img width="542" alt="image" src="https://user-images.githubusercontent.com/20839187/222967614-9e1945b7-9ada-47f4-932e-cd1810b1c37a.png">
<img width="549" alt="image" src="https://user-images.githubusercontent.com/20839187/222967644-2a6a2809-d15c-4316-9b99-dbb5fefc4d2e.png">
<img width="556" alt="image" src="https://user-images.githubusercontent.com/20839187/222967654-2d6f5070-cf04-441c-a756-5e1f149b25ee.png">
<img width="540" alt="image" src="https://user-images.githubusercontent.com/20839187/222967670-a2658ec8-2a9c-46db-baa6-f6b26fb97789.png">
