### ISSUE TITLE
[Bug] 在走外部流量时，clash有时会突然极大的占用cpu

### ISSUE THREAD

**Issue by cccpism** [Dreamacro/clash#2586]
### Verify steps

- [X]  确保你使用的是**本仓库**最新的的 clash 或 clash premium 版本 Ensure you are using the latest version of Clash or Clash Premium from **this repository**. 
- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

0.20.17与0.19.20

### What OS are you seeing the problem on?

Windows

### Clash config

```yaml
dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:5353
  enhanced-mode: fake-ip
  fake-ip-filter:
    - "*.lan"
    - localhost.ptlogin2.qq.com
  fallback:
    - https://162.159.36.1/dns-query
    - https://dns.google/dns-query
    - tls://8.8.8.8:853
  fallback-filter:
    geoip: false
```

### Description

在走外部流量时，clash有时会突然极大的占用cpu，尝试过多种方法，包括但不限于重装clash，使用旧版本，enableloopback中取消所有豁免等，都无法解决这一问题。只能在出现这一bug后重启clash，但下一次仍然会出现此bug。本人小白，在Fndroid那边问过了，那边大佬说可能是因为核心的问题。叫我来这边找大佬问问，拜托诸位了。
