### ISSUE TITLE
[Bug] Windows 平台上，TUN 模式可自用，但不能为局域网内其它设备提供服务

### ISSUE THREAD

**Issue by pcteams** [Dreamacro/clash#2588]
### Verify steps

- [X]  确保你使用的是**本仓库**最新的的 clash 或 clash premium 版本 Ensure you are using the latest version of Clash or Clash Premium from **this repository**. 
- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

2023.03.04

### What OS are you seeing the problem on?

Windows

### Clash config

```yaml
dns:
  enable: true
  listen: 0.0.0.0:53
  enhanced-mode: fake-ip
  ipv6: false
  nameserver:
    - 119.29.29.29
    - 223.5.5.5
  fallback:
    - 114.114.114.114

tun:
  enable: true
  stack: gvisor
  dns-hijack:
    - 198.18.0.2:53
  auto-route: true
  auto-detect-interface: true
```

### Description

新手小白，不知道该如何正确反映问题的实质，仅通过描述现象初步反映问题；但可以持续补充所需信息。

现象概述：Windows 10 平台上，clash 的 TUN 模式**可以自用**，但不能为(无线)局域网内其它设备提供**网关服务**

网络拓扑
互联网 ←→ 光猫(桥接模式) ←→ 无线路由器【IP：192.168.10.1】
                                                            | ←→ Windows 10【IP：192.168.10.3；WiFi 连接；DHCP】【用途：网关1】
                                                            | ←→ 树莓派【IP：192.168.10.6；有线连接；静态 IP】【用途：网关2】
                                                            | ←→ 安卓平板【WiFi 连接；静态 IP(手动配置 IP 地址、路由器和 DNS)】

问题：
Windows 10 21H2 教育版，使用 clash 的 TUN 模式，运行正常(运行 ipconfig /all，可观察到【未知适配器 Clash】字段)，在本机上使用浏览器(Microsoft Edge/Google Chrome)观看 Youtube/Netflix 正常；使用 Netflix UWP 应用观看正常。
安卓平板通过 WiFi 连接至无线路由器后，正常连接，可联网。再调整为使用静态设置(IP 地址：192.168.10.10；路由器：192.168.10.3；前缀长度：24；DNS1：192.168.10.3)，提示信息：**已连接，但无法访问互联网**
config.yaml 配置文件中，TUN 模式核心字段配置信息已贴在上面。

作为对比，使用树莓派＋官方 Raspberry Pi OS Lite 系统＋Clash，作为网关为其它设备提供服务，Windows 10 使用正常，安卓平板使用正常。
Windows 10 静态 IP 设置信息
IP 地址：192.168.10.3；网关：192.168.10.6；前缀长度：24；DNS1：192.168.10.6
安卓平板静态 IP 设置信息
IP 地址：192.168.10.10；路由器：192.168.10.6；前缀长度：24；DNS1：192.168.10.6

Raspberry Pi OS Lite 系统上 Clash 的TUN 模式核心字段配置信息如下：
profile:
  store-selected: true
  store-fake-ip: false

dns:
  enable: true
  listen: 0.0.0.0:53
  ipv6: false
  enhanced-mode: fake-ip
  nameserver:
    - 119.29.29.29
    - 223.5.5.5
  fallback:
     - 114.114.114.114

tun:
  enable: true
  stack: system
  auto-route: true
  auto-detect-interface: true

以上。如有需要可进一步补充相关信息。谢谢！
