### ISSUE TITLE
Clash 作为客户端（iptables redirect->clash->squid）HTTP 协议请求代理时是否可以把 Host 头部域名带上

### ISSUE THREAD

**Issue by daihanyang** [Dreamacro/clash#2589]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

https://github.com/Dreamacro/clash/blob/8c7c8f43741923d6a7650dc723b4b51b0f540777/adapter/outbound/http.go

# 问题
Clash 作为客户端（iptables redire->clash->squid）HTTP 协议请求代理时是否可以把 Host 头部域名带上便于后续代理识别并做出处理（类似 Squid 多级代理）

## Clash
![image](https://user-images.githubusercontent.com/89181622/223103941-a6e30273-51ae-4809-a904-4c2e67bd8907.png)

## Squid
![image](https://user-images.githubusercontent.com/89181622/223103803-dbc9cb63-62bc-4c59-a39b-43124d1645a7.png)

**Comment by Dreamacro** [comment]
clash 拿到的时候就是 ip 吧？可以使用 fakeip，并且 dns 改成 clash 的 dns server

**Comment by jeff-an** [comment]
I'm having the same issue as well (sorry, my Chinese is not so good!):

my clash version:
```
$ ./clash -v
Clash v1.13.0 linux amd64 with go1.19.5 Sun Jan 29 10:49:23 UTC 2023
```

my configuration, note that I have `fake-ip` on:
```
cat config.yaml
redir-port: 8080
mode: rule
log-level: debug
dns:
  enable: true
  listen: 0.0.0.0:53
  default-nameserver:
    - 172.20.0.10
    - 8.8.8.8
  enhanced-mode: fake-ip
  nameserver:
    - 172.20.0.10
proxies:
  - name: "http"
    type: http
    server: 54.212.239.41
    port: 3128
rules:
  - MATCH,http
```

on my proxy server, i see the following logs, indicating IP address only and no host name.
```
[06/Mar/2023:20:32:05 +0000] "CONNECT 34.160.111.145:80 HTTP/1.1" 200 335 "-" "Go-http-client/1.1" "Host: 34.160.111.145:80" TCP_TUNNEL:HIER_DIRECT
```
