### ISSUE TITLE
dns ttl 异常?

### ISSUE THREAD

**Issue by soffchen** [Dreamacro/clash#260]
```
# clash -v
Clash v0.15.0 linux amd64 Sat Jun 29 09:19:28 UTC 2019
```

最近遇到有时候解析国外域名，会遇到 ttl 超级大，导致下游 dns 服务器异常处理

```
$ dig -p 4053 gateway.icloud.com @10.0.0.3

; <<>> DiG 9.10.6 <<>> -p 4053 gateway.icloud.com @10.0.0.3
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 59029
;; flags: qr rd ra; QUERY: 1, ANSWER: 9, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 1, flags:; MBZ: 0x3f26, udp: 2048
;; QUESTION SECTION:
;gateway.icloud.com.		IN	A

;; ANSWER SECTION:
gateway.icloud.com.	81702	IN	CNAME	gateway.fe.apple-dns.net.
gateway.fe.apple-dns.net. 81702	IN	A	17.248.161.108
gateway.fe.apple-dns.net. 81702	IN	A	17.248.161.17
gateway.fe.apple-dns.net. 81702	IN	A	17.248.161.38
gateway.fe.apple-dns.net. 81702	IN	A	17.248.161.102
gateway.fe.apple-dns.net. 81702	IN	A	17.248.161.69
gateway.fe.apple-dns.net. 81702	IN	A	17.248.161.107
gateway.fe.apple-dns.net. 81702	IN	A	17.248.161.140
gateway.fe.apple-dns.net. 81702	IN	A	17.248.161.16

;; Query time: 0 msec
;; SERVER: 10.0.0.3#4053(10.0.0.3)
;; WHEN: Fri Aug 09 15:38:20 CST 2019
;; MSG SIZE  rcvd: 423
```

```
dns:
  enable: true
  listen: 0.0.0.0:4053
  enhanced-mode: redir-host
  nameserver:
    - 114.114.114.114
    - 223.223.5.5
    - 119.29.29.29
  fallback:
    - tcp://1.1.1.1
    - tcp://8.8.8.8
```
