### ISSUE TITLE
[Bug] VMess协议在Fake-IP模式下UDP流量不通

### ISSUE THREAD

**Issue by InspoOnU** [Dreamacro/clash#2600]
### Clash version

03.04 premium

### What OS are you seeing the problem on?

Linux OpenWRT ARM64 & Windows 11 x64

### Clash config

```yaml
dns:
  enable: true
  ipv6: true
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/15
  listen: 0.0.0.0:52544
allow-lan: true
ipv6: true
experimental:
  sniff-tls-sni: true
profile:
  store-selected: true
  store-fake-ip: true
```

### Description

使用VMess协议，如果UDP连接被解析成Fake-IP，那么每次传输几KB的流量就自动断开了。Windows和Linux下都会出现，TUN和TProxy下都会出现。日志无异常。
如果不使用Clash的DNS直接用IP连接或者添加域名到fake-ip-filter，UDP可以连通。老版本Redir-host模式也正常。Trojan和SS节点也正常。
这个bug导致QUIC不可用，如Youtube、Instagram、DNS over QUIC。部分直播也无法连接。
