### ISSUE TITLE
[Bug] Premium 2023.03.03 版本开始无法通过api获取的delay全部是0

### ISSUE THREAD

**Issue by zanbzx** [Dreamacro/clash#2612]
### Verify steps

- [X]  确保你使用的是**本仓库**最新的的 clash 或 clash premium 版本 Ensure you are using the latest version of Clash or Clash Premium from **this repository**. 
- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

Premium 2023.03.04

### What OS are you seeing the problem on?

Linux

### Clash config

```yaml
mixed-port: 1899
allow-lan: true
bind-address: '*'
mode: rule
log-level: info
ipv6: false
external-controller: 0.0.0.0:9090
external-ui: yacd
tun:
  enable: true
hosts:
profile:
  store-selected: true
  store-fake-ip: true
dns:
  enable: true
  listen: 0.0.0.0:53
  default-nameserver:
    - 114.114.114.114
    - 8.8.8.8
```

### Description

Premium 2023.03.03之前版本可以正常获取delay信息，docker镜像升级到Premium 2023.03.03及之后版本获取到的delay都是0
