### ISSUE TITLE
[Bug] Macos 开启tun模式后，curl google 报 35 错误 SSL_ERROR_SYSCALL

### ISSUE THREAD

**Issue by gsy44355** [Dreamacro/clash#2614]
### Verify steps

- [X]  确保你使用的是**本仓库**最新的的 clash 或 clash premium 版本 Ensure you are using the latest version of Clash or Clash Premium from **this repository**. 
- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

2023.03.04 premium

### What OS are you seeing the problem on?

Macos

### Clash config

```yaml
mixed-port: 7890
allow-lan: false
bind-address: "*"
external-controller: 127.0.0.1:9090
mode: rule
log-level: info
ipv6: true
profile:
  tracing: true
dns:
  enable: true
  enhanced-mode: fake-ip
  nameserver:
    - 8.8.8.8
    - 114.114.114.114
    - 223.5.5.5
  fallback: []
  fake-ip-filter:
    - +.stun.*.*
    - +.stun.*.*.*
    - +.stun.*.*.*.*
    - +.stun.*.*.*.*.*
    - "*.n.n.srv.nintendo.net"
    - +.stun.playstation.net
    - xbox.*.*.microsoft.com
    - "*.*.xboxlive.com"
    - apps.apple.com
proxy-providers:
  。。。

proxy-groups:
  。。。
rule-providers:
  。。。
rules:
  。。。
tun:
  enable: true
  stack: gvisor
  auto-route: true
  auto-detect-interface: true
  dns-hijack:
    - any:53
```
```


### Clash log

```shell
clash 未打印相关日志，命令如下，报错见第二行


➜  /dev curl https://www.google.com
curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to www.google.com:443 
```
```


### Description

使用premium版本，sudo 开启tun模式后，可以正常使用浏览器访问google，也可以给其他软件做代理，但在使用curl的时候会出现35报错如下，判断好像是在terminal中直接操作是没有走tun代理的，不知道是我哪里出现了操作问题。衍生出来的问题是，在terminal中直接开启某些需要翻墙的service服务，使用cfw的tun模式可以正常翻墙访问，但是直接使用clash就会报 Error: Client network socket disconnected before secure TLS connection was established。
操作
```
sudo ./clash -d ./config
```
```
(base) ➜  /dev curl https://www.google.com
curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to www.google.com:443 
```
