### ISSUE TITLE
[Bug] TUN模式下DNS hijack失效

### ISSUE THREAD

**Issue by Ao-Last** [Dreamacro/clash#2615]
### Verify steps

- [X]  确保你使用的是**本仓库**最新的的 clash 或 clash premium 版本 Ensure you are using the latest version of Clash or Clash Premium from **this repository**. 
- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

Clash Premium 2023.03.04

### What OS are you seeing the problem on?

macOS

### Clash config

```yaml
mixed-port: 7890
dns:
  enable: true
  enhanced-mode: fake-ip

  # dns servers in this field is used for field `nameserver`
  nameserver:
    - dhcp://en0 # DNS from device `en0`'s dhcp
    - 119.29.29.29
    - https://doh.pub/dns-query # Tencent DoH
    - https://dns.alidns.com/dns-query # Alibaba DoH
    - https://1.1.1.1/dns-query # A DoH outside China
    
    # - 119.29.29.29
    # - 223.5.5.5
    # - 8.8.8.8
  # Used for non-chinese services.
  fallback: []
  fake-ip-filter:
    - +.stun.*.*
    - +.stun.*.*.*
    - +.stun.*.*.*.*
    - +.stun.*.*.*.*.*
    - "*.n.n.srv.nintendo.net"
    - +.stun.playstation.net
    - xbox.*.*.microsoft.com
    - "*.*.xboxlive.com"
    - apps.apple.com
tun:
  enable: true
  stack: gvisor
  auto-route: true
  auto-detect-interface: true
  dns-hijack:
    - any:53  #listen to all dns requests (defualt port 53)
```

### Description

TUN模式下, 无系统代理, DNS hijack失效, 连接全部显示为ip地址, 无域名解析的结果; 开启系统代理后, 恢复正常.
此外, 观察到hijack失效后, 会有指向8.8.8.8, 8.8.4.4的连接, 且唯一出现的域名解析结果为dns.google.com.

> 该问题为突然发生, 而后胡乱调试后又恢复; 反复出现多次;

**Comment by Ao-Last** [comment]
@Dreamacro 我查看了这个issue #2614, 不是很懂. 修改系统dns就能解决问题的原理是? 
1. 我遇到的问题发生-恢复前后没有对dns进行修改过
2. 系统dns我需要保持使用dhcp获取的内网dns
3. 为什么其他条件不变, 同时开启tun, system proxy可以恢复正常, 而只开启tun, 关闭system proxy则hijack失败?

**Comment by Dreamacro** [comment]
> 系统 dns 我需要保持使用 dhcp 获取的内网 dns

可以配置里 dns 写 dhcp://网卡名，但系统 dns 可以设置为 114，这个不冲突

> 为什么其他条件不变, 同时开启 tun, system proxy 可以恢复正常, 而只开启 tun, 关闭 system proxy 则 hijack 失败?

因为遵循系统代理的程序会直接把域名信息给我，但透明代理下需要一个手段拿到域名，dns 就是这个手段

**Comment by Ao-Last** [comment]
@Dreamacro 感谢解答! 还有一点关于clash及其dns的疑惑, 如果您能解答, 我将尽我所能更新wiki, 使其详尽.
根据您的回答,

1) > 遵循系统代理的程序会直接把域名信息给我

这是否意味将会直接使用系统dns, 而不是clash dns?

2) > 透明代理下需要一个手段拿到域名，dns 就是这个手段

仅使用TUN, 不开启system proxy情况下, 使用clash的dns server, 而clash dns 又依赖于系统dns吗? 
那么clash配置里, `dns.nameserver`, `dns.default-nameserver`在此过程中是如何使用的呢?

3) 总而言之, 系统dns, clash dns, 在透明代理下, 系统代理下, 分别遵循怎样的规则?

**Comment by Dreamacro** [comment]
> 这是否意味将会直接使用系统 dns, 而不是 clash dns?

不是，只要 clash dns 是开着的，就还是走 clash 的 dns，不会使用系统的 dns

> 仅使用 TUN, 不开启 system proxy 情况下, 使用 clash 的 dns server, 而 clash dns 又依赖于系统 dns 吗?

clash dns enable 后，完全不依赖系统 dns 了

> 总而言之, 系统 dns, clash dns, 在透明代理下, 系统代理下, 分别遵循怎样的规则?

同上，但 clash dns enable false 时，使用系统 dns，所以无法使用透明代理，但系统代理不影响

**Comment by Ao-Last** [comment]
> clash dns enable false 时，使用系统 dns，所以无法使用透明代理

在我此次所遇到的问题情境下, 配置中的 dns.enable 一直为 true, 那么为何改变系统dns能引起这个问题?

系统dns设置为内网地址就引发错误(无域名解析结果, 全是ip地址, 致使基于域名的规则全部失效, 系统dns设置为public dns则问题解决; 
clash的dns配置中如下(全程未做改变):
```
dns:
  enable: true
  enhanced-mode: fake-ip
  default-nameserver:
    - 119.29.29.29
    - 8.8.8.8
    - 114.114.114.114
  nameserver:
    - https://doh.pub/dns-query
    - https://dns.alidns.com/dns-query
    - https://1.1.1.1/dns-query
    - dhcp://en0
```

**Comment by Dreamacro** [comment]
因为 auto-route 并不会拦截局域网流量（也不应该拦截），所以 dns 流量并不会被 hijack，所以拿不到域名。

此外 stack 能用 system 的话尽量用 system，性能更好一些

**Comment by Ao-Last** [comment]
理解了, 十分感谢!

**Comment by Ao-Last** [comment]
因为没有找到如何可以直接修改wiki, 在这里提出以下建议:
在[该段中](https://github.com/Dreamacro/clash/wiki/Clash-Premium-Features#tun-device)增加以下内容:
```
Notice: Set `system dns` to a local ip may lead to hijack failure. Since `auto-route` will not capture local network traffics, given a local dns ip, dns request will skip the tun hijack. 

```

**Comment by Dreamacro** [comment]
增加了

**Comment by javenwang** [comment]
> 因为 auto-route 并不会拦截局域网流量（也不应该拦截），所以 dns 流量并不会被 hijack，所以拿不到域名。

@Dreamacro 抱歉，虽然这个issue已经关闭了，不过我发现「auto-route 并不会拦截局域网流量」在我机器上似乎不完全成立。

操作系统：macOS
clash配置：
```yaml
dns:
  enable: true
  enhanced-mode: fake-ip
  nameserver:
    - 127.0.0.1
  fallback: []
  fake-ip-filter:
    - +.*
tun:
  enable: true
  stack: system
  auto-route: true
  auto-detect-interface: true
  dns-hijack:
    - 8.8.8.8:53
```

```
 ~  netstat -nr -f inet
Routing tables

Internet:
Destination        Gateway            Flags           Netif Expire
default            192.168.1.1        UGScg             en0       
1                  198.18.0.1         UGSc            utun3       
2/7                198.18.0.1         UGSc            utun3       
4/6                198.18.0.1         UGSc            utun3       
8/5                198.18.0.1         UGSc            utun3       
16/4               198.18.0.1         UGSc            utun3       
32/3               198.18.0.1         UGSc            utun3       
64/2               198.18.0.1         UGSc            utun3       
127                127.0.0.1          UCS               lo0       
127.0.0.1          127.0.0.1          UH                lo0       
128.0/1            198.18.0.1         UGSc            utun3       
169.254            link#7             UCS               en0      !
192.168.1          link#7             UCS               en0      !
192.168.1.1/32     link#7             UCS               en0      !
192.168.1.1        3c:30:6f:8f:9f:66  UHLWIir           en0   1191
192.168.1.36       66:43:f6:c8:9a:1f  UHLWIi            en0    241
192.168.1.37/32    link#7             UCS               en0      !
198.18.0/16        utun3              UGSc            utun3       
198.18.0.1         198.18.0.1         UH              utun3       
224.0.0/4          link#7             UmCS              en0      !
224.0.0.251        1:0:5e:0:0:fb      UHmLWI            en0       
239.255.255.250    1:0:5e:7f:ff:fa    UHmLWI            en0       
255.255.255.255/32 link#7             UCS               en0      !
```

```
 ~  route get 192.168.1.1
   route to: 192.168.1.1
destination: 192.168.1.1
  interface: en0
      flags: <UP,HOST,DONE,LLINFO,WASCLONED,IFSCOPE,IFREF,ROUTER>
 recvpipe  sendpipe  ssthresh  rtt,msec    rttvar  hopcount      mtu     expire
       0         0         0         0         0         0      1500      1059 
 ~  route get 192.168.2.1
   route to: 192.168.2.1
destination: 128.0.0.0
       mask: 128.0.0.0
    gateway: 198.18.0.1
  interface: utun3
      flags: <UP,GATEWAY,DONE,STATIC,PRCLONING>
 recvpipe  sendpipe  ssthresh  rtt,msec    rttvar  hopcount      mtu     expire
       0         0         0         0         0         0      9000         0
```

可能是我理解有误，应该是机器当前所在局域网IP地址段不会被拦截，而不是所有局域网地址都不会被拦截？
