### ISSUE TITLE
[Feature]  希望增加对proxy group增加ipv6优先的选项

### ISSUE THREAD

**Issue by 123485k** [Dreamacro/clash#2617]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

在目前clash是使用基于延迟的双栈选优, 这就导致了一个问题, 在某些网络环境下, 如校园网, 对ipv4限速但是对ipv6不限速, 这就导致了如果使用了clash,虽然ipv6的速度更快,因为延迟更高而不会被选中, 只能通过ipv4访问, 这样就会导致速度变慢.

### Possible Solution

对于直连的链接，添加ipv6优先的选项，当有ipv6地址的时候优先直连ipv6,否则再选择ipv4

**Comment by zhiqiang02** [comment]
script mode 可以满足你的需求

**Comment by 123485k** [comment]
> script mode 可以满足你的需求

如何使用？

**Comment by zhiqiang02** [comment]
> 如何使用？
需要编程基础，例子参考
https://github.com/Dreamacro/clash/wiki/Clash-Premium-Features#script
or https://lancellc.gitbook.io/clash/clash-config-file/script

**Comment by 123485k** [comment]
> > 如何使用？
> 
> 需要编程基础，例子参考 https://github.com/Dreamacro/clash/wiki/Clash-Premium-Features#script or https://lancellc.gitbook.io/clash/clash-config-file/script

resolve_ip返回的是一个ip地址还是域名解析出来的所有ip地址？

**Comment by zhiqiang02** [comment]
> resolve_ip返回的是一个ip地址还是域名解析出来的所有ip地址？

不知道。。。如果是一个，抱歉打扰了

**Comment by yuedai** [comment]
分享一个自己的解决方案，希望对大家有所帮助。

*当然，需要写些代码。

首先假设你的电脑可以ipv4 + ipv6 双栈运行。
如@Dreamacro在早先年的一个帖子中说过的，clash现在的resolve_ip接口不能指定解析A Record还是AAAA Record。所以我们其实需要一个特别的DNS逻辑：如果某个DNS A查询的FQDN有一个合法的AAAA记录，则返回NODATA; 否则返回正常的解析结果。

下面这段Go代码是GPT帮助写的一个框架，我自己调试修了一些Bug。

```
package main

import (
	"fmt"
	"net"

	"github.com/miekg/dns"
)

var dnsClient dns.Client

func main() {
	dns.HandleFunc(".", handleDnsRequest)

	server := &dns.Server{Addr: ":5352", Net: "udp"}
	fmt.Println("Starting at :5352")
	err := server.ListenAndServe()
	defer server.Shutdown()
	if err != nil {
		fmt.Printf("Failed to start server: %s\n ", err.Error())
	}
}

func handleDnsRequest(w dns.ResponseWriter, r *dns.Msg) {

	switch r.Question[0].Qtype {
	case dns.TypeA:
		handleARecordRequest(w, r)
	default:
		in, _, err := dnsClient.Exchange(r, net.JoinHostPort("192.168.123.1", "53")) // replace with your preferred DNS server
		if err != nil {
			print(err.Error() + "\n")
		}

		if in != nil {
			w.WriteMsg(in)
		} else {
			m := new(dns.Msg)
			m.SetReply(r)
			w.WriteMsg(m)
		}
	}
}

func handleARecordRequest(w dns.ResponseWriter, r *dns.Msg) {
	// Check for AAAA records
	aaaaReq := new(dns.Msg)
	aaaaReq.SetQuestion(dns.Fqdn(r.Question[0].Name), dns.TypeAAAA)
	in, _, err := dnsClient.Exchange(aaaaReq, net.JoinHostPort("192.168.123.1", "53")) // replace with your preferred DNS server
	if err != nil {
		print(err.Error() + "\n")
		return
	}

	if in.Rcode == dns.RcodeSuccess && len(in.Answer) > 0 {
		// If AAAA record exists, reply with NODATA
		for _, a := range in.Answer {
			switch a.(type) {
			case *dns.AAAA:
				m := new(dns.Msg)
				m.SetReply(r)
				w.WriteMsg(m)
				return
			}
		}
	}

	{
		// If AAAA record does not exist, proceed with original request
		in, _, _ := dnsClient.Exchange(r, net.JoinHostPort("192.168.123.1", "53")) // replace with your preferred DNS server
		if err != nil {
			print(err.Error() + "\n")
		}
		w.WriteMsg(in)
	}
}
```
下面是我的Clash Script。我的使用场景有些不同，我是从海外翻墙回国内。@Dreeamacro早先的建议，我们可以通过检测ip地址中是否有":"来判断这是一个v4还是v6的地址。注意我的DNS指向了127.0.0.1:5352. 这是假设你把上面那段代码编译部署在了本地。

```
redir-port: 7892
port: 7890
socks-port: 7891
ipv6: true
mode: rule
log-level: silent
no-resolve:
external-controller: 0.0.0.0:9090
secret: "123456"
allow-lan: true
bind-address: "*"
hosts: null
dns:
  use-hosts: true
  enhanced-mode: normal
  enable: true
  ipv6: true
  listen: 0.0.0.0:7874
  nameserver:
    - 127.0.0.1:5352
  fake-ip-filter:
    - dns.msftncsi.com
    - www.msftncsi.com
    - www.msftconnecttest.com
  fallback-filter:
    geoip: true
experimental:
  interface-name: NETGEAR05
proxies:
  - name: cn-forward-tcp
  - name: hk-forward-tcp
  - name: jp-forward-tcp
proxy-groups:
  - name: ChinaVPN
    type: select
    proxies:
      - cn-forward-tcp
    url: https://speed.neu6.edu.cn/
    interval: 300
    prefer: stable
  - name: ChinaVPNV6
    type: select
    proxies:
      - hk-forward-tcp
      - jp-forward-tcp
    url: https://speed.neu6.edu.cn/
    interval: 300
    prefer: stable
rule-providers:
  china:
    behavior: classical
    type: file
    path: ./china-domain-rule-provider.txt
    format: text
script:
  code: |
    def main(ctx, metadata):
      if ctx.rule_providers['china'].match(metadata):
          ip = ctx.resolve_ip(metadata["host"])
          if ':' in ip:
            return "ChinaVPNV6"
          else:
            return "ChinaVPN"
      return "DIRECT"

```
