### ISSUE TITLE
[Bug] TUN模式似乎与windows传入连接功能冲突(导致回环)？

### ISSUE THREAD

**Issue by Olympus-E** [Dreamacro/clash#2619]
### Verify steps

- [X]  确保你使用的是**本仓库**最新的的 clash 或 clash premium 版本 Ensure you are using the latest version of Clash or Clash Premium from **this repository**. 
- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

2023.03.04 Premium (4908)

### What OS are you seeing the problem on?

Windows

### Clash config

```yaml
port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: 127.0.0.1:9090
dns:
  enable: true
  nameserver:
    - 223.5.5.5
    - 119.29.29.29
  fallback:
    - https://doh.buzz:8000/dns-query
    - https://doh.beauty:8000/dns-query
    - https://cloudflare-dns.com/dns-query
    - tls://1.1.1.1:853
    - tls://1.0.0.1:853
    - https://1.1.1.1/dns-query
    - https://1.0.0.1/dns-query
    - tls://8.8.8.8:853
    - tls://8.8.4.4:853
    - https://dns.google/dns-query
    - https://dns.twnic.tw/dns-query
  fallback-filter:
    geoip: true
    geoip-code: CN
    ipcidr:
      - 240.0.0.0/4
    domain:
      - +.google.com
      - +.facebook.com
      - +.youtube.com
  nameserver-policy: null
cfw-bypass:
  - qq.com
  - music.163.com
  - "*.music.126.net"
  - localhost
  - 127.*
  - 10.*
  - 172.16.*
  - 172.17.*
  - 172.18.*
  - 172.19.*
  - 172.20.*
  - 172.21.*
  - 172.22.*
  - 172.23.*
  - 172.24.*
  - 172.25.*
  - 172.26.*
  - 172.27.*
  - 172.28.*
  - 172.29.*
  - 172.30.*
  - 172.31.*
  - 192.168.*
  - <local>
cfw-latency-timeout: 5000
proxies:
  *Hidden*
rules:
  *Omitted*
```

### Clash log

```shell
见下文
```

### Description

开启windows传入连接功能后，cfw启用tun模式会导致回环，具体表现为发往代理服务器的数据包被路由回了tun设备，并最终导致程序卡死。

Clash日志:
[2023-03-16-112920.log](https://github.com/Dreamacro/clash/files/10986456/2023-03-16-112920.log)

Fndroid/clash_for_windows_pkg#4157
