### ISSUE TITLE
[Bug] Premium 2023.01.29 -> 2023.03.04，同一个配置文件，在新版中延迟测试 timeout/error。但节点同样可用（即使测试不过）。

### ISSUE THREAD

**Issue by wolonge95** [Dreamacro/clash#2622]
### Verify steps

- [X]  确保你使用的是**本仓库**最新的的 clash 或 clash premium 版本 Ensure you are using the latest version of Clash or Clash Premium from **this repository**. 
- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

Clash 2023.03.04 windows amd64 with go1.20.1 Sat Mar  4 02:54:16 UTC 2023

### What OS are you seeing the problem on?

Windows

### Clash config

```yaml
mixed-port: 7890
mode: rule
external-controller: 127.0.0.1:9090
log-level: debug
proxies:
  - name: 'xxx name'
    type: ss
    server: server
    port: *
    cipher: *
    password: *
proxy-groups:
  - name: High
    type: select
    proxies:
      - 'xxx name'
rules:
  # 最终规则
  - GEOIP,LAN,DIRECT
  - GEOIP,CN,DIRECT
  - MATCH,High
```

### Clash log

```shell
（DEBUG）日志里没有关于「测速/测延迟」的信息。
```

### Description

昨晚，升级了我用的客户端，Clash 从 Premium 2023.01.29 -> 2023.03.04。发现客户端里延迟测试是`error`，且在外部网站 http://clash.razord.top/ 测试也一样。（clash 2023.01.29 在客户端和外部网站均正常。）

然后我又换了一个不常用的客户端升级到最新版（clash Premium 2023.03.04），同样是延迟测试不过。

**虽然**，所有的客户端测延迟都不过，但是节点都是可用的，我可以正常上 YouTube。

不确定我做错了什么，「Windows 安全中心」里的防火墙都关闭了。

需要帮助，谢谢大家了。
