### ISSUE TITLE
[Bug] 电脑休眠后再打开dhcp的dns失效, 报错address already in use

### ISSUE THREAD

**Issue by Ao-Last** [Dreamacro/clash#2624]
### Verify steps

- [X]  确保你使用的是**本仓库**最新的的 clash 或 clash premium 版本 Ensure you are using the latest version of Clash or Clash Premium from **this repository**. 
- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

Clash Premium 2023.03.04

### What OS are you seeing the problem on?

macOS

### Clash config

```yaml
dns:
  enable: true
  enhanced-mode: fake-ip
  default-nameserver:
    - 119.29.29.29
    - 8.8.8.8
    - 114.114.114.114
  nameserver:
    - https://doh.pub/dns-query
    - https://dns.alidns.com/dns-query
    - https://1.1.1.1/dns-query
    - dhcp://en0

tun:
  enable: true
  stack: system
  auto-route: true
  auto-detect-interface: true
  dns-hijack:
    - any:53
```

### Description

1. clash一切运行正常
2. 电脑合盖, 进入休眠(Wi-Fi会断开)
3. 打开电脑, Wi-Fi重新连接
4. clash dns 中使用dhcp的dns失效, 错误:`listen udp4 0.0.0.0:68: bind: address already in use`
5. 重启clash, 一切恢复正常
