### ISSUE TITLE
[Bug] socks-port not listening

### ISSUE THREAD

**Issue by sbilly** [Dreamacro/clash#2627]
### Verify steps

- [X]  确保你使用的是**本仓库**最新的的 clash 或 clash premium 版本 Ensure you are using the latest version of Clash or Clash Premium from **this repository**. 
- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [x]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

1.97.0.4

### What OS are you seeing the problem on?

macOS

### Clash config

```yaml
# Port of HTTP(S) proxy server on the local end
# port: 7890
port: 8118 

# Port of SOCKS5 proxy server on the local end
socks-port: 7891

# Transparent proxy server port for Linux and macOS
redir-port: 7892

# HTTP(S) and SOCKS5 server on the same port
# mixed-port: 7890

# authentication of local SOCKS5/HTTP(S) server
# authentication:
#  - "user1:pass1"
#  - "user2:pass2"

# Set to true to allow connections to local-end server from
# other LAN IP addresses
allow-lan: true

# This is only applicable when `allow-lan` is `true`
# '*': bind all IP addresses
# 192.168.122.11: bind a single IPv4 address
# "[aaaa::a8aa:ff:fe09:57d8]": bind a single IPv6 address
# bind-address: '127.0.0.1'
bind-address: '*'

# Clash router working mode
# rule: rule-based packet routing
# global: all packets will be forwarded to a single endpoint
# direct: directly forward the packets to the Internet
mode: rule

# Clash by default prints logs to STDOUT
# info / warning / error / debug / silent
log-level: debug 

# When set to false, resolver won't translate hostnames to IPv6 addresses
ipv6: false

# RESTful web API listening address
external-controller: 127.0.0.1:9090

# A relative path to the configuration directory or an absolute path to a
# directory in which you put some static web resource. Clash core will then
# serve it at `http://{{external-controller}}/ui`.
# external-ui: ui

# Secret for the RESTful API (optional)
# Authenticate by spedifying HTTP header `Authorization: Bearer ${secret}`
# ALWAYS set a secret if RESTful API is listening on 0.0.0.0
# secret: ""

# Outbound interface name
# interface-name: en0
# interface-name: eno1

# Static hosts for DNS server and connection establishment, only works
# when `dns.enhanced-mode` is `redir-host`.
#
# Wildcard hostnames are supported (e.g. *.clash.dev, *.foo.*.example.com)
# Non-wildcard domain names have a higher priority than wildcard domain names
# e.g. foo.example.com > *.example.com > .example.com
# P.S. +.foo.com equals to .foo.com and foo.com
hosts:
  # '*.clash.dev': 127.0.0.1
  # '.dev': 127.0.0.1
  # 'alpha.clash.dev': '::1'

# DNS server settings
# This section is optional. When not present, DNS server will be disabled.
dns:
  enable: false
  listen: 0.0.0.0:9053
  # listen: 0.0.0.0:53
  # ipv6: false # when false, response to AAAA questions will be empty

  # These nameservers are used to resolve the DNS nameserver hostnames below.
  # Specify IP addresses only
  default-nameserver:
    - 114.114.114.114
    - 8.8.8.8
  # enhanced-mode: redir-host # or fake-ip
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16 # Fake IP addresses pool CIDR
  
  # Hostnames in this list will not be resolved with fake IPs
  # i.e. questions to these domain names will always be answered with their
  # real IP addresses
  # fake-ip-filter:
  #   - '*.lan'
  #   - localhost.ptlogin2.qq.com
  
  # Supports UDP, TCP, DoT, DoH. You can specify the port to connect to.
  # All DNS questions are sent directly to the nameserver, without proxies
  # involved. Clash answers the DNS question with the first result gathered.
  nameserver:
    # - 192.168.0.249
    - 127.0.0.1
    # - 114.114.114.114 # default value
    # - 8.8.8.8 # default value
    # - tls://dns.rubyfish.cn:853 # DNS over TLS
    # - https://1.1.1.1/dns-query # DNS over HTTPS

  # When `fallback` is present, the DNS server will send concurrent requests
  # to the servers in this section along with servers in `nameservers`.
  # The answers from fallback servers are used when the GEOIP country
  # is not `CN`.
  # fallback:
  #   - tcp://1.1.1.1

  # If IP addresses resolved with servers in `nameservers` are in the specified
  # subnets below, they are considered invalid and results from `fallback`
  # servers are used instead.
  #
  # IP address resolved with servers in `nameserver` is used when
  # `fallback-filter.geoip` is true and when GEOIP of the IP address is `CN`.
  #
  # If `fallback-filter.geoip` is false, results from `fallback` nameservers
  # are always used, and answers from `nameservers` are discarded.
  #
  # This is a countermeasure against DNS pollution attacks.
  fallback-filter:
    geoip: true
    geoip-code: CN
    ipcidr:
       - 240.0.0.0/4
    domain:
      - '+.google.com'
      - '+.facebook.com'
      - '+.youtube.com'

proxy-providers:
...
proxy-groups:
...
# Premium only
rule-providers:
...
rules:
...
```

### Clash log

```shell
2023/03/18 16:18:10.715  [info] applicationWillFinishLaunching
2023/03/18 16:18:10.731  [info] applicationDidFinishLaunching
2023/03/18 16:18:10.731  [info] Appversion: 1.97.0.4 1.97.0.4
2023/03/18 16:18:10.748  [info] postFinishLaunching
2023/03/18 16:18:10.767  [debug] checkInstall
2023/03/18 16:18:10.768  [info] initClashCore
2023/03/18 16:18:10.768  [info] initClashCore finish
2023/03/18 16:18:10.770  [info] Trying start proxy, build-in mode: true, allow lan: false custom port: 8118
2023/03/18 16:18:10.783  [debug] helper version 2.0 require version 2.0
2023/03/18 16:18:10.783  [info] check helper using time: 0.015352964401245117
2023/03/18 16:18:10.783  [debug] check result: installed
2023/03/18 16:18:11.152  [info] Start proxy done
2023/03/18 16:18:11.154  [info] set up autoUpateTimer
2023/03/18 16:18:11.154  [info] Tigger config auto update check
2023/03/18 16:18:11.154  [info] [Auto Upgrade] Bypassing config due to time check
2023/03/18 16:18:11.296  [info] Saving Remote Config Setting
2023/03/18 16:18:11.520  [info] port config updated,new: 8118,8118
2023/03/18 16:18:11.521  [info] Startup: enableStatusAtLastExit = false, settings = false
2023/03/18 16:18:11.522  [debug] loggingWebSocket did Connect
```

### Description

没有遵循配置文件中的配置 `socks-port` 监听 `7891` 端口

```shell
❯ lsof -nP|grep Clash|grep LISTEN
ClashX    44987 xxx   15u     IPv4 0xf41bcc064f7f2de1        0t0                 TCP 127.0.0.1:7892 (LISTEN)
ClashX    44987 xxx   18u     IPv4 0xf41bcc064f288401        0t0                 TCP 127.0.0.1:8118 (LISTEN)
ClashX    44987 xxx   19u     IPv4 0xf41bcc064f5ce531        0t0                 TCP 127.0.0.1:9090 (LISTEN)
```
