### ISSUE TITLE
[Bug] 白群晖ipv6无法进行ddns解析

### ISSUE THREAD

**Issue by qiuyan81** [Dreamacro/clash#2651]
### Verify steps

- [X]  确保你使用的是**本仓库**最新的的 clash 或 clash premium 版本 Ensure you are using the latest version of Clash or Clash Premium from **this repository**. 
- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

1.14.0

### Clash config

```yaml
mixed-port: 7890
allow-lan: true
bind-address: '*'
mode: rule
log-level: info
external-controller: '0.0.0.0:9090'
external-ui: /ui
dns:
    enable: false
    ipv6: false
    default-nameserver: [223.5.5.5, 119.29.29.29]
    enhanced-mode: fake-ip
    fake-ip-range: 198.18.0.1/16
    use-hosts: true
    nameserver: ['https://doh.pub/dns-query', 'https://dns.alidns.com/dns-query']
    fallback: ['https://doh.dns.sb/dns-query', 'https://dns.cloudflare.com/dns-query', 'https://dns.twnic.tw/dns-query', 'tls://8.8.4.4:853']
    fallback-filter: { geoip: true, ipcidr: [240.0.0.0/4, 0.0.0.0/32] }
rules:
    - DOMAIN-SUFFIX,synology.com,DIRECT
    - DOMAIN-SUFFIX,dyndns.org,DIRECT
    - DOMAIN-SUFFIX,synocommunity.com,DIRECT
    - 'DOMAIN-KEYWORD,synology,DIRECT'
```

### Clash log

```shell
日志看起来synology的都是DIRECT了
```

### Description

我的白群晖想走代理,能削刮电影.我只有ipv6的公网ip,ddns在不走代理的情况下是能正常解析ipv6的.经过代理后就失败了.在日志里面没看到有经过代理的.我甚至把群晖的ip SRC-IP-CIDR,192.168.50.2/32, DIRECT都设置了.看日志也是正常的.是不是ipv6那块我没设置好?日志等级我已经开到debug了,也没看到ipv6的访问信息..
