### ISSUE TITLE
订阅后在Linux版本上更新配置后无法使用

### ISSUE THREAD

**Issue by Deardongfl** [Dreamacro/clash#2653]
### Verify steps

- [X]  确保你使用的是**本仓库**最新的的 clash 或 clash premium 版本 Ensure you are using the latest version of Clash or Clash Premium from **this repository**. 
- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

clash-linux-amd64-v3-v1.14.0.gz

### What OS are you seeing the problem on?

Linux

### Clash config

```yaml
port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: 127.0.0.1:9090
dns:
  enable: true
  nameserver:
    - 223.5.5.5
    - 119.29.29.29
  fallback:
    - https://doh.buzz:8000/dns-query
    - https://doh.beauty:8000/dns-query
    - https://cloudflare-dns.com/dns-query
    - tls://1.1.1.1:853
    - tls://1.0.0.1:853
    - https://1.1.1.1/dns-query
    - https://1.0.0.1/dns-query
    - tls://8.8.8.8:853
    - tls://8.8.4.4:853
    - https://dns.google/dns-query
    - https://dns.twnic.tw/dns-query
  fallback-filter:
    geoip: true
    geoip-code: CN
    ipcidr:
      - 240.0.0.0/4
    domain:
      - +.google.com
      - +.facebook.com
      - +.youtube.com
  nameserver-policy: ~
proxies:
  - {name:  V5-香港1, server: hk01-vm5.entry.hsrtd.club, port: 450, type: vmess, uuid: 6710d759-5f87-332f-a5cb-4158030dd1cf, alterId: 1, cipher: auto, tls: false, skip-cert-verify: false, network: ws, ws-opts: {path: /hls/cctv5phd.m3u8, headers: {Host: bgp-01-01.entry-0.chinasnow.net}}, ws-path: /hls/cctv5phd.m3u8, ws-headers: {Host: bgp-01-01.entry-0.chinasnow.net}}
  - {name:  V5-京日1, server: jp01-vm5.entry.hsrtd.club, port: 448, type: vmess, uuid: 6710d759-5f87-332f-a5cb-4158030dd1cf, alterId: 1, cipher: auto, tls: false, skip-cert-verify: false, network: ws, ws-opts: {path: /hls/cctv5phd.m3u8, headers: {Host: bgp-02-01.entry-0.chinasnow.net}}, ws-path: /hls/cctv5phd.m3u8, ws-headers: {Host: bgp-02-01.entry-0.chinasnow.net}}
  - {name:  V5-香港2, server: hk02-vm5.entry.hsrtd.club, port: 451, type: vmess, uuid: 6710d759-5f87-332f-a5cb-4158030dd1cf, alterId: 1, cipher: auto, tls: false, skip-cert-verify: false, network: ws, ws-opts: {path: /hls/cctv5phd.m3u8, headers: {Host: bgp-01-02.entry-0.chinasnow.net}}, ws-path: /hls/cctv5phd.m3u8, ws-headers: {Host: bgp-01-02.entry-0.chinasnow.net}}
```

### Clash log

```shell
日志为空
```

### Description

更新Linux配置后无法使用，./classh -d .后无法开启代理，请问是什么原因？按照教程操作的，在Windows和Android上均能正常使用。
![微信图片_20230401223905](https://user-images.githubusercontent.com/102734479/229295807-1ee713b1-464c-4dbd-88d3-3475acc0e9d0.jpg)
![微信图片_20230401223915](https://user-images.githubusercontent.com/102734479/229295808-3c818d2d-10eb-44a5-9fa5-6a8d97dcbbea.jpg)
![微信图片_20230401223920](https://user-images.githubusercontent.com/102734479/229295810-e31a92db-61e0-491e-bcd7-0d4f86b76e0e.jpg)
