### ISSUE TITLE
[Bug] 重构后的 TUN 在 Linux 4.14 无法接管 TCP 流量

### ISSUE THREAD

**Issue by Blankdlh** [Dreamacro/clash#2655]
### Verify steps

- [X]  确保你使用的是**本仓库**最新的的 clash 或 clash premium 版本 Ensure you are using the latest version of Clash or Clash Premium from **this repository**. 
- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

Clash 2023.03.18 linux mipsle with go1.20.2 Sat Mar 18 12:41:31 PM UTC 2023

### What OS are you seeing the problem on?

Linux

### Clash config

```yaml
redir-port: 7892
mixed-port: 7890
allow-lan: true
bind-address: '*'
mode: rule
log-level: info
ipv6: true
external-controller: 0.0.0.0:9090
tun:
  enable: true
  stack:  system # gvisor
  dns-hijack:
    - any:53
  auto-route: true # auto set global route
  auto-redir: false
  auto-detect-interface: true # conflict with interface-name

profile:
shared
  store-selected: false
  store-fake-ip: true
dns:
  enable: true
  listen: 0.0.0.0:1053
  ipv6: true # when the false, response to AAAA questions will be empty

  # These nameservers are used to resolve the DNS nameserver hostnames below.
  # Specify IP addresses only
  default-nameserver:
    - 114.114.114.114
    - 8.8.8.8

  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16 # Fake IP addresses pool CIDR
  use-hosts: true # lookup hosts and return IP record

  nameserver:
    - 114.114.114.114 # default value
    - 8.8.8.8 # default value
  fallback:
    - tls://8.8.8.8:853         # Google DNS over TLS 50ms
    - tls://8.8.4.4:853         # cloudflare DNS over TLS 50ms
    - https://1.1.1.1/dns-query # cloudflare DNS over HTTPS
    - https://dns.google/dns-query # Google DNS over HTTPS

  fallback-filter:
    geoip: true
    geoip-code: CN
```

### Clash log

```shell
log 没有异常
```

### Description

自从 tun 模式重构以后（2022.11.25 及之后版本），无法正常使用，log 中看不到任何 tcp 请求，只有 udp 请求。同样的配置在老版本可以正常使用。

设备是 UBNT 的 edgerouter-x，Linux ubnt 4.14.54-UBNT #1 SMP Thu Jun 30 07:04:36 UTC 2022 mips GNU/Linux，不知道跟这个定制系统有没有关系，求助～
