### ISSUE TITLE
在linux上docker容器代理失败

### ISSUE THREAD

**Issue by Rick630** [Dreamacro/clash#2660]
### Verify steps

- [x]  确保你使用的是**本仓库**最新的的 clash 或 clash premium 版本 Ensure you are using the latest version of Clash or Clash Premium from **this repository**. 
- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

v1.14.0

### Clash config

```yaml
mixed-port: 7890
allow-lan: true
bind-address: '*'
mode: rule
log-level: info
external-controller: '127.0.0.1:9090'
dns:
    enable: true
    listen: '127.0.0.1:35353'
    ipv6: false
    default-nameserver: [223.5.5.5, 1.0.0.1]
    enhanced-mode: fake-ip
    fake-ip-range: 198.18.0.1/16
    fake-ip-filter: ['*.lan', 'stun.*.*.*', 'stun.*.*', time.windows.com, time.nist.gov, time.apple.com, time.asia.apple.com, '*.ntp.org.cn', '*.openwrt.pool.ntp.org', time1.cloud.tencent.com, time.ustc.edu.cn, pool.ntp.org, ntp.ubuntu.com, ntp.aliyun.com, ntp1.aliyun.com, ntp2.aliyun.com, ntp3.aliyun.com, ntp4.aliyun.com, ntp5.aliyun.com, ntp6.aliyun.com, ntp7.aliyun.com, time1.aliyun.com, time2.aliyun.com, time3.aliyun.com, time4.aliyun.com, time5.aliyun.com, time6.aliyun.com, time7.aliyun.com, '*.time.edu.cn', time1.apple.com, time2.apple.com, time3.apple.com, time4.apple.com, time5.apple.com, time6.apple.com, time7.apple.com, time1.google.com, time2.google.com, time3.google.com, time4.google.com, music.163.com, '*.music.163.com', '*.126.net', musicapi.taihe.com, music.taihe.com, songsearch.kugou.com, trackercdn.kugou.com, '*.kuwo.cn', api-jooxtt.sanook.com, api.joox.com, joox.com, y.qq.com, '*.y.qq.com', streamoc.music.tc.qq.com, mobileoc.music.tc.qq.com, isure.stream.qqmusic.qq.com, dl.stream.qqmusic.qq.com, aqqmusic.tc.qq.com, amobile.music.tc.qq.com, '*.xiami.com', '*.music.migu.cn', music.migu.cn, '*.msftconnecttest.com', '*.msftncsi.com', localhost.ptlogin2.qq.com, '*.*.*.srv.nintendo.net', '*.*.stun.playstation.net', 'xbox.*.*.microsoft.com', '*.ipv6.microsoft.com', '*.*.xboxlive.com', speedtest.cros.wr.pvp.net]
    nameserver: [8.8.8.8, 8.8.4.4, 1.1.1.1, 1.0.0.1]
    fallback: [119.29.29.29, 223.5.5.5, 'https://dns.rubyfish.cn/dns-query', 'tls://8.8.4.4', 'tls://1.0.0.1:853', 'https://cloudflare-dns.com/dns-query', 'https://dns.google/dns-query']
    fallback-filter: { geoip: true, ipcidr: [240.0.0.0/4, 0.0.0.0/32, 127.0.0.1/32], domain: [+.google.com, +.facebook.com, +.twitter.com, +.youtube.com, +.xn--ngstr-lra8j.com, +.google.cn, +.googleapis.cn, +.googleapis.com, +.gvt1.com] }
proxies:
    - { name: '🇯🇵 日本 ² x 1.0', type: trojan, server: vpn-domain, port: 443, password: password, udp: true, skip-cert-verify: true }
proxy-groups:
    - { name: XFLASH, type: select, proxies: ['🇯🇵 日本 ² x 1.0'] }
rule-providers:
    reject: { type: http, behavior: domain, url: 'https://ghproxy.com/https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/reject.txt', path: ./ruleset/reject.yaml, interval: 86400 }
    icloud: { type: http, behavior: domain, url: 'https://ghproxy.com/https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/icloud.txt', path: ./ruleset/icloud.yaml, interval: 86400 }
    apple: { type: http, behavior: domain, url: 'https://ghproxy.com/https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/apple.txt', path: ./ruleset/apple.yaml, interval: 86400 }
    google: { type: http, behavior: domain, url: 'https://ghproxy.com/https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/google.txt', path: ./ruleset/google.yaml, interval: 86400 }
    proxy: { type: http, behavior: domain, url: 'https://ghproxy.com/https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/proxy.txt', path: ./ruleset/proxy.yaml, interval: 86400 }
    direct: { type: http, behavior: domain, url: 'https://ghproxy.com/https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/direct.txt', path: ./ruleset/direct.yaml, interval: 86400 }
    private: { type: http, behavior: domain, url: 'https://ghproxy.com/https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/private.txt', path: ./ruleset/private.yaml, interval: 86400 }
    gfw: { type: http, behavior: domain, url: 'https://ghproxy.com/https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/gfw.txt', path: ./ruleset/gfw.yaml, interval: 86400 }
    greatfire: { type: http, behavior: domain, url: 'https://ghproxy.com/https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/greatfire.txt', path: ./ruleset/greatfire.yaml, interval: 86400 }
    tld-not-cn: { type: http, behavior: domain, url: 'https://ghproxy.com/https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/tld-not-cn.txt', path: ./ruleset/tld-not-cn.yaml, interval: 86400 }
    telegramcidr: { type: http, behavior: ipcidr, url: 'https://ghproxy.com/https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/telegramcidr.txt', path: ./ruleset/telegramcidr.yaml, interval: 86400 }
    cncidr: { type: http, behavior: ipcidr, url: 'https://ghproxy.com/https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/cncidr.txt', path: ./ruleset/cncidr.yaml, interval: 86400 }
    lancidr: { type: http, behavior: ipcidr, url: 'https://ghproxy.com/https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/lancidr.txt', path: ./ruleset/lancidr.yaml, interval: 86400 }
    applications: { type: http, behavior: classical, url: 'https://ghproxy.com/https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/applications.txt', path: ./ruleset/applications.yaml, interval: 86400 }
rules:
    - 'PROCESS-NAME,v2ray,DIRECT'
    - 'PROCESS-NAME,xray,DIRECT'
    - 'PROCESS-NAME,naive,DIRECT'
    - 'PROCESS-NAME,trojan,DIRECT'
    - 'PROCESS-NAME,trojan-go,DIRECT'
    - 'PROCESS-NAME,ss-local,DIRECT'
    - 'PROCESS-NAME,privoxy,DIRECT'
    - 'PROCESS-NAME,leaf,DIRECT'
    - 'PROCESS-NAME,v2ray.exe,DIRECT'
    - 'PROCESS-NAME,xray.exe,DIRECT'
    - 'PROCESS-NAME,naive.exe,DIRECT'
    - 'PROCESS-NAME,trojan.exe,DIRECT'
    - 'PROCESS-NAME,trojan-go.exe,DIRECT'
    - 'PROCESS-NAME,ss-local.exe,DIRECT'
    - 'PROCESS-NAME,privoxy.exe,DIRECT'
    - 'PROCESS-NAME,leaf.exe,DIRECT'
    - 'PROCESS-NAME,Surge,DIRECT'
    - 'PROCESS-NAME,Surge 2,DIRECT'
    - 'PROCESS-NAME,Surge 3,DIRECT'
    - 'PROCESS-NAME,Surge 4,DIRECT'
    - 'PROCESS-NAME,Surge%202,DIRECT'
    - 'PROCESS-NAME,Surge%203,DIRECT'
    - 'PROCESS-NAME,Surge%204,DIRECT'
    - 'PROCESS-NAME,Thunder,DIRECT'
    - 'PROCESS-NAME,DownloadService,DIRECT'
    - 'PROCESS-NAME,qBittorrent,DIRECT'
    - 'PROCESS-NAME,Transmission,DIRECT'
    - 'PROCESS-NAME,fdm,DIRECT'
    - 'PROCESS-NAME,aria2c,DIRECT'
    - 'PROCESS-NAME,Folx,DIRECT'
    - 'PROCESS-NAME,NetTransport,DIRECT'
    - 'PROCESS-NAME,uTorrent,DIRECT'
    - 'PROCESS-NAME,WebTorrent,DIRECT'
    - 'PROCESS-NAME,aria2c.exe,DIRECT'
    - 'PROCESS-NAME,BitComet.exe,DIRECT'
    - 'PROCESS-NAME,fdm.exe,DIRECT'
    - 'PROCESS-NAME,NetTransport.exe,DIRECT'
    - 'PROCESS-NAME,qbittorrent.exe,DIRECT'
    - 'PROCESS-NAME,Thunder.exe,DIRECT'
    - 'PROCESS-NAME,ThunderVIP.exe,DIRECT'
    - 'PROCESS-NAME,transmission-daemon.exe,DIRECT'
    - 'PROCESS-NAME,transmission-qt.exe,DIRECT'
    - 'PROCESS-NAME,uTorrent.exe,DIRECT'
    - 'PROCESS-NAME,WebTorrent.exe,DIRECT'
    - 'DOMAIN,clash.razord.top,DIRECT'
    - 'DOMAIN,yacd.haishan.me,DIRECT'
    - 'GEOIP,LAN,DIRECT'
    - 'GEOIP,CN,DIRECT'
    - 'MATCH,XFLASH'
```

### Description

在宿主机上用curl调用是通的
`curl --proxy socks5h://172.17.0.5:7890 https://api.openai.com/v1/chat/completions`

`[36mINFO[0m[0178] [TCP] 172.17.0.1:39516 --> api.openai.com:443 match Match() using XFLASH[🇯🇵 日本 ² x 1.0] `

但是容器里调用是timeout
`[33mWARN[0m[0194] [TCP] dial XFLASH (match Match/) 172.17.0.4:35376 --> api.openai.com:443 error: vpn-domain:443 connect error: dial tcp4 vpn-ip:443: i/o timeout `

请教一下是什么问题
