### ISSUE TITLE
[Question] filter regex: invalid or unsupported Perl syntax '(?!'

### ISSUE THREAD

**Issue by QS0x01** [Dreamacro/clash#2666]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Clash version

20230318 Premium 49742

### What OS are you seeing the problem on?

Windows

### Clash config

```yaml
proxy-providers:
  Hybrid:
    type: http
    url: "https://sub.xeton.dev/sub?target=clash&url=A|B&list=true"
    interval: 7200
    path: ./Hybrid.yaml
    filter: "^(?!.*(?:abc|cde)).*$"
    health-check:
      enable: true
      interval: 60
      url: https://www.gstatic.com/generate_204
```

### Clash log

```shell
invalid filter regex: error parsing regexp: invalid or unsupported Perl syntax '(?!'
```

### Description

用的 cfw 的 gui，不清楚是 cfw 还是 core 不支持？如果是 cfw 的问题我就到那边再问问。

试图使用正则排除一些高倍率节点，但是提示无法 parse 负向前瞻断言的 (?! 标识符。
wiki 里对应部分注明的是：#golang regex string. 请问是我的语法有误还是不支持?
