### ISSUE TITLE
[Feature] Clash能否只配置DNS服务，将代理的流量通过DNS解析道IP后，直接连接

### ISSUE THREAD

**Issue by XhstormR** [Dreamacro/clash#2669]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

我本地电脑有个限制，不能手动更改DNS服务地址，只能接收上游设置的默认DNS；所以我想将流量转发至配置了DNS的clash，然后再连接，但是在没有配置proxy server的情况下，只能选择DIRECT或者REJECT。

想请问在 DIRECT 模式下是否能够只配置DNS，然后代理流量？

这是我的配置
```yaml
dns:
    enable: true
    listen: 0.0.0.0:53
    default-nameserver:
        - 1.2.4.8
    nameserver:
        - 1.2.4.8
```
