### ISSUE TITLE
[Feature] fake-ip 模式下，ICMP 协议请求域名不响应问题

### ISSUE THREAD

**Issue by daihanyang** [Dreamacro/clash#2678]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

# iptables 规则
```
# 本机器出网需求
iptables -t nat -N CLASH
iptables -t nat -A CLASH -d  10.0.0.0/8 -j RETURN
iptables -t nat -A CLASH -d  127.0.0.0/8 -j RETURN
iptables -t nat -A CLASH -d  172.16.0.0/12 -j RETURN
iptables -t nat -A CLASH -d  192.168.0.0/16 -j RETURN
iptables -tnat  -A CLASH -d  169.254.0.0/16 -j RETURN
iptables -tnat  -A CLASH -d  33.0.0.0/16 -j RETURN
iptables -tnat  -A CLASH -d  9.0.0.0/16 -j RETURN
iptables -t nat -A CLASH -p tcp -j REDIRECT --to-ports 12345
iptables -t nat -A OUTPUT -p tcp -j CLASH

#容器出网需求
iptables -tnat -APREROUTING -p tcp -j CLASH
```
# Clash 配置
```
redir-port: 12345
allow-lan: true
mode: Rule
log-level: debug
#web ui
external-controller: 0.0.0.0:1270
dns:
  enable: true
  listen: 0.0.0.0:53
  default-nameserver:
    - 183.60.83.19
    - 183.60.82.98
  enhanced-mode: fake-ip
  nameserver:
    - 183.60.83.19
    - 183.60.82.98
proxies:
  - name: "proxy-squid"
    type: http
    server: xxxxxxxx
    port: 8081
rules:
  - IP-CIDR,10.0.0.0/8,DIRECT
  - IP-CIDR,127.0.0.0/8,DIRECT
  - IP-CIDR,172.16.0.0/12,DIRECT
  - IP-CIDR,192.168.0.0/16,DIRECT
  - IP-CIDR,198.18.0.1/16,DIRECT
  - IP-CIDR,169.254.0.0/16,DIRECT
  - IP-CIDR,33.0.0.0/16,DIRECT
  - IP-CIDR,9.0.0.0/16,DIRECT
  - DST-PORT,22,DIRECT
  - DST-PORT,36000,DIRECT
  - MATCH,proxy-squid
```

# 问题
因 `/etc/resolv.conf` 里面配置本机 fakeip 为名称服务器，任何域名解析都会解析为 fakeip，TCP 类请求会被转发到 Clash 后随即立即响应，ICMP 类请求无法处理，请教这里有什么好的处理方式（期望 ICMP 请求域名时能到达实际的后端服务器，不被 fakeip 响应，但同时因为 Clash->Squid 的 squid 有读取 Host 的需求，要使用 fakeip 的能力使 Clash 透传 Host）。
![image](https://user-images.githubusercontent.com/89181622/231992426-d5270475-fb53-407f-b022-823730b751aa.png)
