### ISSUE TITLE
[Bug] linux无法使用trojan类节点无法使用

### ISSUE THREAD

**Issue by yzh1994414** [Dreamacro/clash#2687]
### Verify steps

- [X]  确保你使用的是**本仓库**最新的的 clash 或 clash premium 版本 Ensure you are using the latest version of Clash or Clash Premium from **this repository**. 
- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

v1.15.1

### What OS are you seeing the problem on?

Linux

### Clash config

```yaml
####################################
# 创建者：v2rayse.com
# 客户端：Clash
# 创建时间：2023-04-19 20:12:24
# 使用模版：V2RaySE 默认模版
# 节点数量：5
####################################
mixed-port: 7890
allow-lan: true
log-level: info
external-controller: 0.0.0.0:9090
dns:
  enabled: true
  nameserver:
    - 119.29.29.29
    - 223.5.5.5
  fallback:
    - 8.8.8.8
    - 8.8.4.4
    - tls://1.0.0.1:853
    - tls://dns.google:853

proxies:
  - - {"name":"🇯🇵_JP_日本","type":"trojan","server":"fschk.fscloud123456789.com","port":443,"udp":true,"password":"2e31a75e-ce52-4d2c-95e1-41c8acdbc80c","skip-cert-verify":true,"network":"tcp"}
```

### Description

注：docker环境下使用的指令如下——
docker pull dreamacro/clash
docker run -d --name clash_test -p 7990:7890 -p 7991:7891 -v /home/yang/RemoteWorking/clash/config_test.yaml:/root/.config/clash/config.yaml dreamacro/clash
测试vmess类型节点可以使用正常，trojan节点无法使用。100%可复现（节点在windows端可以使用，linux下无法使用）
