### ISSUE TITLE
[Bug] 自定义host 时，dns AAAA 超时

### ISSUE THREAD

**Issue by zxh326** [Dreamacro/clash#2692]
### Verify steps

- [X]  确保你使用的是**本仓库**最新的的 clash 或 clash premium 版本 Ensure you are using the latest version of Clash or Clash Premium from **this repository**. 
- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

2023.4.13 premium

### What OS are you seeing the problem on?

Linux

### Clash config

```yaml
...
tun:
  enable: true
  stack: system # or gvisor
  auto-route: true # auto set global route
  auto-redir: true
  auto-detect-interface: true # conflict with interface-name
hosts:
  "baidu.com": 39.156.66.10
...


dns IPv6， clash IPv6 开或者关都试过。
```

### Clash log

```shell
clash 无相关 dns 日志
```

### Description

在配置了 clash hosts 时，如示例
```
...
hosts:
  "baidu.com": 39.156.66.10
...
```

使用 dig 超时，去掉正常。
```sh
root@clash:~# dig AAAA baidu.com

; <<>> DiG 9.16.37-Debian <<>> AAAA baidu.com
;; global options: +cmd
;; connection timed out; no servers could be reached


root@clash:~# dig A baidu.com

; <<>> DiG 9.16.37-Debian <<>> baidu.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 27016
;; flags: qr aa rd ra ad; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
; COOKIE: 882f3dcaf6dbfa51 (echoed)
;; QUESTION SECTION:
;baidu.com.			IN	A

;; ANSWER SECTION:
baidu.com.		600	IN	A	39.156.66.10
```

_clash.ipv6, clash.dns.ipv6 关掉或开，都可以复现。_

这会影响优先使用 ipv6 的工具，例如 curl，会等待 IPv6 dns timeout 之后才会走 IPv4
