### ISSUE TITLE
[Feature] Add Provider bulk relay to another proxy

### ISSUE THREAD

**Issue by kingofnull** [Dreamacro/clash#2697]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

I have a pc that don't have direct internet access , I had to use a socks proxy to connect to internet. So the problem is I have to define relay provider for each one and my list changes a lot. Also clash cant ping them and switch to working one. 

### Possible Solution

Add a option to proxy-providers and set upstream proxy name for it , then it relay all it's proxies to mentioned proxy. 

example config:

```yaml
proxy-providers:
  my_realyed_provider:
    type: file
    path: ./proxies.yaml
    proxy: my_interent_socks_proxy
```
