### ISSUE TITLE
[Bug] tunnels无法建立连接

### ISSUE THREAD

**Issue by y8244249** [Dreamacro/clash#2705]
### Verify steps

- [X]  确保你使用的是**本仓库**最新的的 clash 或 clash premium 版本 Ensure you are using the latest version of Clash or Clash Premium from **this repository**. 
- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

v0.45.112-beta

### What OS are you seeing the problem on?

OpenBSD/FreeBSD

### Clash config

```yaml
dns解析配置
fallback:
  - tcp://127.0.0.1:1053
隧道配置
tunnels:
- network:
  - tcp
  address: 127.0.0.1:1053
  target: 8.8.8.8:443
  proxy: Proxy
- tcp,127.0.0.1:1053,dns.google:443,Proxy
```

### Description

*自定义上游 DNS 服务器去掉勾选

也尝试了勾选自定义上游 DNS 服务器去掉勾选并把tcp://127.0.0.1:1053填入到fallback组

是需要映射1053这个端口吗
