### ISSUE TITLE
[Feature] Proxy Providers的配置太过冗长了，不够优美，建议简化

### ISSUE THREAD

**Issue by tony1016** [Dreamacro/clash#2709]
### 先决条件

- [X] 我了解这里是 Clash 官方仓库，并非 Clash.Meta / OpenClash / ClashX / Clash For Windows 或其他任何衍生版本
- [X] 我已经在[这里](https://github.com/Dreamacro/clash/issues?q=is%3Aissue+label%3Aenhancement)找过我要提出的建议，**并且没有找到相关问题**
- [X] 我已经仔细阅读 [官方 Wiki](https://github.com/Dreamacro/clash/wiki/) 

### 描述

目前一套Proxy Providers配置下来，配置文件的割裂非常严重，而Proxy Providers里最重要就一个url，其他项其实也不是很关心，建议直接整合到Proxy Group里

### 可能的解决方案

比如：
- name: UseProvider
    type: select
    use:
      - [url]
      - [url]
    proxies:
      - Proxy
      - DIRECT

**Comment by Dreamacro** [comment]
provider 被设计为可以被多个 proxy group 使用，放在 proxy group 里反而麻烦，如果说非要有什么可以减少的，那么可以减少的部分是 proxy provider 包含一些合理的默认值来减少样板配置。

可以想象下面的这个配置如果放在 group 里会有多灾难，并且 provider 是可以操作的，放在 group 的无法进行操作

```yaml
proxy-groups:
  - name: Proxy
    type: select
    use: [香港, 台湾, 日本, 美国, 新加坡, 测试]
  - name: Custom
    type: select
    use:  [香港, 新加坡, 测试]
    proxies: [DIRECT]
  - name: Crypto
    type: select
    use: [台湾]
  - name: OpenAI
    type: select
    use: [美国]
  - name: VPN
    type: select
    proxies: [DIRECT]
  - name: Switch
    type: select
    use: [香港]
    proxies: [DIRECT]
  - name: Xbox
    type: select
    use:  [香港, 测试]
    proxies: [DIRECT]
```
