### ISSUE TITLE
[Bug] Raspberry Pi OS 选择 NetworkManager 会导致 TUN 模式不起作用

### ISSUE THREAD

**Issue by cntrump** [Dreamacro/clash#2714]
### 先决条件

- [X] 我了解这里是官方开源版 Clash 核心仓库，**只提供开源版或者 Premium 内核的支持**
- [X] 我要提交 Clash 核心的问题，并非 Clash.Meta / OpenClash / ClashX / Clash For Windows 或其他任何衍生版本的问题
- [X] 我使用的是**本仓库**最新版本的 Clash 或 Clash Premium 内核
- [X] 我已经在 [Issue Tracker](……/) 中找过我要提出的 bug，**并且没有找到相关问题**
- [X] 我已经仔细阅读 [官方 Wiki](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题
- [ ] （非 Premium 内核必填）我已经使用 dev 分支版本测试过，问题依旧存在

### 版本

Clash 2023.04.16 linux arm64 with go1.20.3 Sun Apr 16 13:20:30 UTC 2023

### 适用的作业系统

Linux

### 适用的硬件架构

arm64

### 配置文件

```YAML
log-level: info
mode: rule
ipv6: false
http:
  url-rewrite:
    - ^http(s)?:\/\/(www.)?g\.cn https://www.google.com 302
    - ^http(s)?:\/\/(www.)?google\.cn https://www.google.com 302
  mitm:
    - '*.g.cn'
    - '*.google.cn'
dns:
  enable: true
  listen: 0.0.0.0:53
  ipv6: false
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  default-nameserver:
    - 119.29.29.29
  nameserver:
    - 119.29.29.29
hosts:
  'dot.pub': 1.12.12.12
  'dns.alidns.com': 223.5.5.5
tun:
  enable: true
  stack: gvisor
  dns-hijack:
    - any:53
  auto-redir: true
  auto-route: true
  auto-detect-interface: true
```

### 问题描述

Raspi OS 使用 `dhcpcd` ，TUN 模式可以正常接管流量。
使用 `sudo raspi-config` 把网络配置改成 `NetworkManager` ，TUN 模式就不能接管任何流量了。
