### ISSUE TITLE
[Bug] Chrome (Firefox) 不能使用新的tun模式

### ISSUE THREAD

**Issue by im20A0** [Dreamacro/clash#2715]
### 先决条件

- [X] 我了解这里是官方开源版 Clash 核心仓库，**只提供开源版或者 Premium 内核的支持**
- [X] 我要提交 Clash 核心的问题，并非 Clash.Meta / OpenClash / ClashX / Clash For Windows 或其他任何衍生版本的问题
- [X] 我使用的是**本仓库**最新版本的 Clash 或 Clash Premium 内核
- [X] 我已经在 [Issue Tracker](……/) 中找过我要提出的 bug，**并且没有找到相关问题**
- [X] 我已经仔细阅读 [官方 Wiki](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题
- [ ] （非 Premium 内核必填）我已经使用 dev 分支版本测试过，问题依旧存在

### 版本

2023.04.16

### 适用的作业系统

Linux

### 适用的硬件架构

amd64-v3

### 配置文件

```YAML
mixed-port: 7890
allow-lan: true
mode: rule
log-level: info
external-controller: '127.0.0.1:9090'
external-ui: /etc/clash/yacd/
hosts:
  services.googleapis.cn: 216.58.200.67
  www.google.cn: 216.58.200.67
dns:
  enable: true
  enhanced-mode: fake-ip
  nameserver:
    - 114.114.114.114
    - 223.5.5.5
    - 8.8.8.8
  ipv6: false
  fake-ip-filter: ['*.lan', 'stun.*.*.*', 'stun.*.*', time.windows.com, time.nist.gov, time.apple.com, time.asia.apple.com, '*.ntp.org.cn', '*.openwrt.pool.ntp.org', time1.cloud.tencent.com, time.ustc.edu.cn, pool.ntp.org, ntp.ubuntu.com, ntp.aliyun.com, ntp1.aliyun.com, ntp2.aliyun.com, ntp3.aliyun.com, ntp4.aliyun.com, ntp5.aliyun.com, ntp6.aliyun.com, ntp7.aliyun.com, time1.aliyun.com, time2.aliyun.com, time3.aliyun.com, time4.aliyun.com, time5.aliyun.com, time6.aliyun.com, time7.aliyun.com, '*.time.edu.cn', time1.apple.com, time2.apple.com, time3.apple.com, time4.apple.com, time5.apple.com, time6.apple.com, time7.apple.com, time1.google.com, time2.google.com, time3.google.com, time4.google.com, music.163.com, '*.music.163.com', '*.126.net', musicapi.taihe.com, music.taihe.com, songsearch.kugou.com, trackercdn.kugou.com, '*.kuwo.cn', api-jooxtt.sanook.com, api.joox.com, joox.com, y.qq.com, '*.y.qq.com', streamoc.music.tc.qq.com, mobileoc.music.tc.qq.com, isure.stream.qqmusic.qq.com, dl.stream.qqmusic.qq.com, aqqmusic.tc.qq.com, amobile.music.tc.qq.com, '*.xiami.com', '*.music.migu.cn', music.migu.cn, '*.msftconnecttest.com', '*.msftncsi.com', localhost.ptlogin2.qq.com, '*.*.*.srv.nintendo.net', '*.*.stun.playstation.net', 'xbox.*.*.microsoft.com', '*.ipv6.microsoft.com', '*.*.xboxlive.com', speedtest.cros.wr.pvp.net]
  fallback: ['https://dns.rubyfish.cn/dns-query', 'https://public.dns.iij.jp/dns-query', 'tls://8.8.4.4']
  fallback-filter: { geoip: true, ipcidr: [240.0.0.0/4, 0.0.0.0/32, 127.0.0.1/32], domain: [+.google.com, +.facebook.com, +.twitter.com, +.youtube.com, +.xn--ngstr-lra8j.com, +.google.cn, +.googleapis.cn, +.googleapis.com, +.gvt1.com] }
tun:
  enable: true
  stack: system # or gvisor
  dns-hijack:
    - any:53
  auto-route: true # auto set global route
  auto-detect-interface: true # conflict with interface-name
```

### 问题描述

发现仅Chrome (Firefox) 不能使用新的tun模式，其他应用暂时没有发现问题。
开启tun模式后在Chrome中浏览网页在clash日志里不会产生相关连接，打开google.com产生错误NET::ERR_CERT_COMMON_NAME_INVALID
![image](https://user-images.githubusercontent.com/10060276/235979250-63c1a6da-8122-421a-b753-a0464528cddf.png)
使用http代理一切正常
