### ISSUE TITLE
Support for multiple inbound proxy ports

### ISSUE THREAD

**Issue by orwithout** [Dreamacro/clash#2716]
### Prerequisites

- [X] I understand that this is the official open-source version of the Clash core, **only providing support for the open-source version or Premium version**
- [X] I have looked for my idea in [the issue tracker](https://github.com/Dreamacro/clash/issues?q=is%3Aissue+label%3Aenhancement), **and found none of which being related**
- [X] I have read the [official Wiki](https://github.com/Dreamacro/clash/wiki/)

### Description
Clash is a great network proxy software that supports directing traffic using multiple settings such as ports, IP addresses, and domain names to different backend proxy servers. However, it currently does not support using multiple HTTP/SOCKS proxy ports simultaneously to direct incoming traffic to different backend proxy servers. This feature is available in other software like V2rayA and V2ray. It would be great if Clash could also support this feature. This feature is useful for directing traffic based on incoming port number to different backend proxy servers.

Steps to Reproduce:
N/A

Expected Results:
Users can configure multiple HTTP and SOCKS proxy ports to direct traffic to different backend proxy servers based on the incoming port number.

Actual Results:
Users cannot configure multiple HTTP and SOCKS proxy ports to direct traffic to different backend proxy servers based on the incoming port number.

Additional Information:
None.

**Comment by orwithout** [comment]
Thank you for your reply! Regarding the use cases you asked about, here are some possible scenarios:

- Different proxy requirements for different applications
- Need for more convenient and controllable custom routing support (e.g., for web scraping purposes)

Here, I have some specific examples to further explain these use cases:

1. Browser extensions like SwitchyOmega allow users to set whether to use a proxy and which backend proxy to use for each web page. If Clash could provide multiple SOCKS or HTTP proxy ports (as entrances), then we could set these ports as backend proxies in SwitchyOmega. This way, when browsing the web, users can choose which proxy to use for each page individually without having to modify Clash's configuration.

2. When you want to share proxy services with family members or colleagues within a local network, you can inform them of the multiple proxy ports provided by Clash. This way, they can choose different ports based on their needs to connect to proxy servers in different countries. For example, one port might connect to a proxy server in the United States, while another port might connect to a proxy server in the United Kingdom. This provides them with more flexibility and freedom of choice.

3. Regarding the need for more convenient and controllable custom routing support, for example, when running web scraping programs, developers might need to choose different proxy servers based on the target website or request type. Providing multiple entrance ports allows developers to configure independent ports for these different strategies, enabling more complex policy routing.

I have tried other proxy tools (e.g., V2Ray/Xray), but Clash's policy routing feature is the most powerful and flexible. Therefore, I feel that supporting multiple HTTP/SOCKS proxy ports would be a beneficial addition to Clash.

I hope you will consider adding this feature to make Clash even more powerful. If you need more information or suggestions, please feel free to let me know.

**Comment by kery** [comment]
I have a similar requirement that depends on this feature. For example, normally my browser uses Clash's socks5/http port as proxy service, and in Clash the requests are distributed by Clash's rules. Sometimes, I need all requests forwarded by a specific outbound.

Without this feature, I have to comment out all the rules and set the default proxy as the desired outbound; If this feature is implemented, I can and an additional inbound and a rule which matches the new inbound and forward request to the desired outbound.

**Comment by Dreamacro** [comment]
already implementation

**Comment by kery** [comment]
> 

```
inbounds:
  - mixed://0.0.0.0:7890
  - mixed://0.0.0.0:7891

rules:
  - INBOUND-PORT,7891,Proxy1
```

**Comment by Cr4ckPwd** [comment]
Myconfig bellow can you help me fix it
```

port: 7890
socks-port: [1000, 1001]
redir-port: 7892
allow-lan: false
mode: rule
log-level: info
external-controller: '0.0.0.0:8080'

proxies:
  - name: "MyProxy1"
    type: http
    server: 115.74.112.188
    port: 1000
    username: king
    password: king

  - name: "MyProxy2"
    type: http
    server: 115.74.112.188
    port: 1001
    username: king
    password: king

proxy-groups:
  - name: "ProxyGroup1"
    type: select
    proxies:
      - MyProxy1
      - DIRECT

  - name: "ProxyGroup2"
    type: select
    proxies:
      - MyProxy2
      - DIRECT

rules:
  - SOURCE-PORT,1000,ProxyGroup1
  - SOURCE-PORT,1001,ProxyGroup2
  - DOMAIN-SUFFIX,google.com,MyProxy1
  - DOMAIN-SUFFIX,facebook.com,MyProxy1
  - DOMAIN-SUFFIX,whoer.net,MyProxy1
  - DOMAIN-SUFFIX,gologin.com,MyProxy1
  - DOMAIN-SUFFIX,youtube.com,MyProxy2
  - DOMAIN-SUFFIX,instagram.com,MyProxy2
  - DOMAIN-SUFFIX,twitter.com,MyProxy2
  - MATCH,ProxyOrDirect

```

**Comment by Cr4ckPwd** [comment]
> > how to create config with multiple ports and multiple proxies
> 
> 
> 
> ```
> 
> inbounds:
> 
>   - mixed://0.0.0.0:7890
> 
>   - mixed://0.0.0.0:7891
> 
> 
> 
> rules:
> 
>   - INBOUND-PORT,7891,Proxy1
> 
> ```

Myconfig bellow can you help me fix it
```

port: 7890
socks-port: [1000, 1001]
redir-port: 7892
allow-lan: false
mode: rule
log-level: info
external-controller: '0.0.0.0:8080'

proxies:
  - name: "MyProxy1"
    type: http
    server: 115.74.112.188
    port: 1000
    username: king
    password: king

  - name: "MyProxy2"
    type: http
    server: 115.74.112.188
    port: 1001
    username: king
    password: king

proxy-groups:
  - name: "ProxyGroup1"
    type: select
    proxies:
      - MyProxy1
      - DIRECT

  - name: "ProxyGroup2"
    type: select
    proxies:
      - MyProxy2
      - DIRECT

rules:
  - SOURCE-PORT,1000,ProxyGroup1
  - SOURCE-PORT,1001,ProxyGroup2
  - DOMAIN-SUFFIX,google.com,MyProxy1
  - DOMAIN-SUFFIX,facebook.com,MyProxy1
  - DOMAIN-SUFFIX,whoer.net,MyProxy1
  - DOMAIN-SUFFIX,gologin.com,MyProxy1
  - DOMAIN-SUFFIX,youtube.com,MyProxy2
  - DOMAIN-SUFFIX,instagram.com,MyProxy2
  - DOMAIN-SUFFIX,twitter.com,MyProxy2
  - MATCH,ProxyOrDirect

```
