### ISSUE TITLE
Discussion: Rule Script

### ISSUE THREAD

**Issue by Dreamacro** [Dreamacro/clash#272]
In the actual daily use case, the number of `Rule` is usually in the thousands. It is time to propose a simpler and more efficient matching method.

In `Surge`, the solution is `RULE-SET`. For example, `RULE-SET,https://url/xxx.list,yourproxy`. `xxx.list` define a `rule` list:

```
DOMAIN-KEYWORD,amazon,force-remote-dns
DOMAIN-KEYWORD,google,force-remote-dns
DOMAIN-KEYWORD,gmail,force-remote-dns
DOMAIN-KEYWORD,youtube,force-remote-dns
DOMAIN-KEYWORD,facebook,force-remote-dns
```

It's simple but not flexible. If we use an embedded language, we can do some optimization and customization. For example (pseudocode written in typescript):

```typescript
interface Context {
    metadata: object,
    proxies: { [key: string]: Proxy }
    domainTree: {
        match: (domain: string): boolean
    }
}

const random = (s: number, e: number) => s + Math.floor(Math.random() * (e - s))

function (ctx: Context): Proxy {
    const { proxies, metadata, domainTree } = ctx
    const hk = Object.keys(proxies)
        .filter(key => proxies[key].name.include('hk'))
        .map(key => proxies[key])
        .sort((a, b) => a.delay > b.delay ? 1 : -1)

    if (domainTree.match(metadata.host)) {
        return hk[0]
    }

    return hk[random(0, hk.length)]
}
```

`domainTree` is a simple trie tree now used in `host`, and `Context` could provide more util function to help the user write their own script. BTW, Configuration can get rid of the binding of lists and rules.

```yaml
# define a list
lists:
    - url: https://example.com/list.yaml
       interval: 300
       type: trie-tree
    - file: /opt/list.yaml
       type: trie-tree
```

### About embedded language

I found out two embedded languages that can be used in clash

* https://github.com/gates/gates
* https://github.com/google/starlark-go

### Relation issue
#33 
#41 
#79

**Comment by Fndroid** [comment]
filter 是不是写错了
```
const hk = Object.keys(proxies)
    .filter(key => proxies[proxy].name.include('hk')) // proxies[key]
```

后面这个 lists 里面是什么样子的呢，每个``trie tree``对应一个``script``吗

**Comment by Dreamacro** [comment]
@Fndroid Typo fixed. 列表里目前设想是一个 domain list，具体细节要接着讨论，我就是写个原型

**Comment by cjjdaq** [comment]
期待新功能。同时期待surge中的支持mitm的url-regxp,那就完美了.

**Comment by ruisiji** [comment]
Some questions:

1. Where to set a proxy for a domain?

    The use case is for Netflix, not all proxies support Netflix.

    In the example `list`, there is no proxies, so if the list.yaml contains Netflix domains, how to choose proxies?

2. How to detect IP-CIDR and other types of MATCH RULE?

    Usually we will have a google.list which contains google services domain and IP CIDR, how to detect the domain or domain suffix or IP cidr?

**Comment by tslling** [comment]
这样是不是相当于消除了proxy group的概念，一个list匹配的请求选择哪个proxy由rule script决定？但是一个rule script能利用的信息非常有限（proxy的name/ip等），仅由这些信息可能不足以决断出是否应该选用这个proxy。

可以借鉴Kubernetes里label和selector的[概念](https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/)，给节点加上label来描述节点，这样rule script在选择节点时有了更多参考信息。
例如：
```yaml
Proxy:
- name: "hk01"
  server: 1.1.1.1
  type: ss
  labels:
  - hk
  - netflix
- name: "us01"
  server: 1.1.1.2
  type: ss
  labels:
  - us
  - youtube
  - netflix
```
这样YouTube对应的rule script就可以这样写了：
```js
const hk = Object.keys(proxies)
    .filter(key => proxies[proxy].labels.contains('youtube'))
```

**Comment by laincat** [comment]
其实在 Clash 的配置文件来说，已经不需要“参考” Surge 的写法，或者接近它。

---------------------------------------------------

https://github.com/v2ray/domain-list-community

这个项目怎么样？只提供有限的内容，其它靠配置文件来定义。

对于规则来说，这个项目就够了，足够轻盈，维护简单，也能创建自己的 list。

当然也可以创建一套自己的，问题不大的，转换一下就好。

---------------------------------------------------

而对于需要订阅的用户来说，节点订阅的格式规范，更有意义吧？

**Comment by ruisiji** [comment]
I think we can YAML everything, this makes it easy to parse by golang.

* google.yaml

```
IP-CIDR:
- 35.190.247.0/24
- 64.233.160.0/19
DOMAIN-SUFFIX:
- android.com
- golang.org
DOMAIN-KEYWORD:
- google
- blogspot
```

* general.yaml

```
port: 1087
socks-port: 1080
allow-lan: true
```

* proxy.yaml

```
proxy:
- name: us1
  server: 1.1.1.1
  type: ss
- name: hk1
  server: 1.1.1.2
  type: ss
```

* virtual-proxy.yaml

```
virtual-proxy:
- name: proxy
  type: select
  proxies:
  - us1
  - hk1
  labels:
  - us
  - hk
```

* rules.yaml

```
remote-rules:
- url: https://example.com/google.yaml
  interval: 3600
  selector:
  - us
rules:
- IP-CIDR:
  - 1.1.1.1/8
  DOMAIN-SUFFIX:
  - netflix.com
```

**Comment by lincolnguang** [comment]
Even if users can use a specific DNS server to query a domain. For example, use 223.5.5.5 to query taobao.com

**Comment by reorx** [comment]
支持这个想法，作为 yaml Rule 的可替代选项存在，方便进行更复杂的定制而无需增加新的指令（如 USER-AGENT）。

只不过发明或者选择另一种 embedded language，还不如直接弄一个 go 的 v8 binding，用 JavaScript PAC 的成熟规则（FindProxyForURL），这样适用性也更广，许多已有的优秀 PAC 也可以直接应用过来。

**Comment by Dreamacro** [comment]
@reorx v8 可太大了，我不需要 v8 里面的大部分东西，所以一个精简的 embedded language 才是我想要的。PAC 的限制太多了，内置的函数也太少了。网上随便找一个规则类的 PAC 都是上万行，这不是我想要的。

**Comment by ruisiji** [comment]
Rule Set is easy to read and edit for end users, so I think it is better to implement a `rule-provider` to support both ruleset and rule script, something like:

```
rule-provider:
  google:
    type: set
    path: google.yaml
    url: https://example.com/google.yaml
    interval: 3600
    use: proxy-group-us
  netflix:
    type: set
    path: netflix.yaml
    url: https://example.com/netflix.yaml
    interval: 3600
    use: proxy-group-media
  custom:
    type: script
    path: custom.script
    url: https://example.com/custom.script
    interval: 3600
    use: proxy-group-other
```

**Comment by Dreamacro** [comment]
@ruisiji I have a doubt about `use`, What is it for?

**Comment by ruisiji** [comment]
@Dreamacro  The ruleset does not contain proxy/proxy-group, the `use` means which proxy/proxy-group handles this ruleset.

**Comment by lincolnguang** [comment]
> Rule Set is easy to read and edit for end users, so I think it is better to implement a `rule-provider` to support both ruleset and rule script, something like:
> 
> ```
> rule-provider:
>   google:
>     type: set
>     path: google.yaml
>     url: https://example.com/google.yaml
>     interval: 3600
>     use: proxy-group-us
>   netflix:
>     type: set
>     path: netflix.yaml
>     url: https://example.com/netflix.yaml
>     interval: 3600
>     use: proxy-group-media
>   custom:
>     type: script
>     path: custom.script
>     url: https://example.com/custom.script
>     interval: 3600
>     use: proxy-group-other
> ```

I think this style of config is inflexible. In one hand, users can’t switch rule set’s proxy group easily. In the other hand, I think separating rules and script is not easy of maintaining, users will jump in different files to add,  modify or delete rules.

In my opinion:

Here’s an example of config.yaml:
```
proxy-provider:
 hk:
  type: http
  path: ./hk.yaml
  url: http://remote.lancelinked.icu/files/hk.yaml
  interval: 3600
  health-check:
   enable: true
   url: http://www.gstatic.com/generate_204
   interval: 300
 us:
  type: file
  path: /home/lance/.clash/provider/us.yaml
  health-check:
   enable: true
   url: http://www.gstatic.com/generate_204
   interval: 300

Proxy Group:
  - name: Proxy
    type: select
    proxies:
      - hk
      - us

rule-provider:
 googleset:
    type: http #or file
    path: ./googleset.yaml
    url: https://example.com/google.yaml
    interval: 3600
 
Rule:
 - SET-MATCH, googleset, Proxy

```
Here is an example of rule set file:
```
rules:

  - DOMAIN-SUFFIX,ampproject.org
  - DOMAIN-SUFFIX,appspot.com
  - DOMAIN-SUFFIX,blogger.com
  - DOMAIN-SUFFIX,getoutline.org

dnsmap:

  - HOST, abc.com, 1.2.3.4
  - DNS-SERVER, def.com, 8.8.8.8 #or system

rewrite:
  - URL-REWRITE, ^http://www\.google\.cn http://www.google.com, header # 302 or REJECT
  - HEADER-REWRITE, ^http://example.com,header-replace=User-Agent, Unknown

script:

  - http-response, ^http://www.example.com/test, script-path=test.js, max-size=16384, debug=true
```
