### ISSUE TITLE
[Bug] auto-redir 的路由规则设置导致所有包须经过一次 kernel ARP lookup

### ISSUE THREAD

**Issue by BirkhoffLee** [Dreamacro/clash#2720]
### 先决条件

- [X] 我了解这里是官方开源版 Clash 核心仓库，**只提供开源版或者 Premium 内核的支持**
- [X] 我要提交 Clash 核心的问题，并非 Clash.Meta / OpenClash / ClashX / Clash For Windows 或其他任何衍生版本的问题
- [X] 我使用的是**本仓库**最新版本的 Clash 或 Clash Premium 内核
- [X] 我已经在 [Issue Tracker](……/) 中找过我要提出的 bug，**并且没有找到相关问题**
- [X] 我已经仔细阅读 [官方 Wiki](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题
- [ ] （非 Premium 内核必填）我已经使用 dev 分支版本测试过，问题依旧存在

### 版本

Clash 2023.04.16-2-gbb54ec7 linux amd64 with go1.20.3 Thu Apr 27 07:14:33 UTC 2023

### 适用的作业系统

Linux

### 适用的硬件架构

amd64, amd64-v3

### 配置文件

```YAML
mode: direct
mixed-port: 7890

interface-name: ens18

tun:
  enable: true
  stack: system
  auto-redir: true
  auto-route: true

dns:
  enable: true
  listen: 0.0.0.0:53
  ipv6: false
  default-nameserver: [ '8.8.8.8', '1.1.1.1' ]

  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  use-hosts: true

  nameserver: [ '1.1.1.1' ]
```

### 日志输出

```Text
无
```

### 问题描述

Linux (Ubuntu 22.04.1) 上可稳定复现（全新 LXC 跟 VM 都可以复现  
macOS 13.3.1 (22E261) 上没这问题  

我在想这个问题有可能跟 https://github.com/Dreamacro/clash/issues/2621#issuecomment-1525039553 有关系（QUIC 第一次 DIRECT 冷链接有几率失败

### 复现步骤

1. 随意决定一个 fake ip address 如 198.18.123.123
2. 第一次 ping 可以看到延迟很高，有一次测试出 700+ 的延迟
    ```
    $ ping 198.18.123.123
    PING 198.18.123.123 (198.18.123.123) 56(84) bytes of data.
    64 bytes from 198.18.123.123: icmp_seq=1 ttl=62 time=234 ms
    64 bytes from 198.18.123.123: icmp_seq=2 ttl=62 time=0.084 ms
    64 bytes from 198.18.123.123: icmp_seq=3 ttl=62 time=0.075 ms
    64 bytes from 198.18.123.123: icmp_seq=4 ttl=62 time=0.077 ms
    64 bytes from 198.18.123.123: icmp_seq=5 ttl=62 time=0.082 ms
    64 bytes from 198.18.123.123: icmp_seq=6 ttl=62 time=0.077 ms
    ^C
    --- 198.18.123.123 ping statistics ---
    6 packets transmitted, 6 received, 0% packet loss, time 5100ms
    rtt min/avg/max/mdev = 0.075/39.106/234.242/87.267 ms
    ```
3. 大概三分钟左右以内的时间再 ping 都是正常的延迟：
     ```
    $ ping 198.18.123.123
    PING 198.18.123.123 (198.18.123.123) 56(84) bytes of data.
    64 bytes from 198.18.123.123: icmp_seq=1 ttl=62 time=0.054 ms
    64 bytes from 198.18.123.123: icmp_seq=2 ttl=62 time=0.090 ms
    64 bytes from 198.18.123.123: icmp_seq=3 ttl=62 time=0.078 ms
    64 bytes from 198.18.123.123: icmp_seq=4 ttl=62 time=0.079 ms
    ^C
    --- 198.18.123.123 ping statistics ---
    4 packets transmitted, 4 received, 0% packet loss, time 3049ms
    rtt min/avg/max/mdev = 0.054/0.075/0.090/0.013 ms
    ```
    过了三分钟左右之后（或者重新启动 clash）就会跟第二步一样很高延迟
