### ISSUE TITLE
[Bug] 将 clash 部署在带公网 ip 的服务器上，并通过配置网络代理使用，部分网站无法连接

### ISSUE THREAD

**Issue by Apolsus** [Dreamacro/clash#2721]
### 先决条件

- [X] 我了解这里是官方开源版 Clash 核心仓库，**只提供开源版或者 Premium 内核的支持**
- [X] 我要提交 Clash 核心的问题，并非 Clash.Meta / OpenClash / ClashX / Clash For Windows 或其他任何衍生版本的问题
- [X] 我使用的是**本仓库**最新版本的 Clash 或 Clash Premium 内核
- [X] 我已经在 [Issue Tracker](……/) 中找过我要提出的 bug，**并且没有找到相关问题**
- [X] 我已经仔细阅读 [官方 Wiki](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题
- [ ] （非 Premium 内核必填）我已经使用 dev 分支版本测试过，问题依旧存在

### 版本

Clash v1.15.1 linux 386 with go1.20.3 Sun Apr 16 13:17:49 UTC 2023

### 适用的作业系统

Linux

### 适用的硬件架构

386

### 配置文件

```YAML
mix-port: 7890
port: 7890
socks-port: 7891
redir-port: 7892
allow-lan: true
mode: rule
log-level: silent
external-controller: '127.0.0.1:9090'
secret: ''

ipv6: true

dns:
  enable: true
  ipv6: true
  nameserver:
    - "[2400:3200::1]:53"
    - 114.114.114.114

proxies:
  -
    // 后面是一些策略和规则信息，都是可用的，经过测试的
```

### 日志输出

```Text
在后面给出，这里拖不进来图
```

### 问题描述

clash 运行在服务器，打开局域网代理后，客户端使用公网域名:7890（或者公网ip:7890）使用服务器上代理，部分页面无法正常访问。（例如 backend.raycast.com、openai、whatismyapp）。但同样的指令，在服务器运行就可以访问。

### 复现步骤

服务器配置局域网代理完成后打开 clash 服务
客户端配置网络代理使用公网ip+端口访问这个服务
