### ISSUE TITLE
[Feature] script provider 

### ISSUE THREAD

**Issue by LiHang941** [Dreamacro/clash#2726]
### 先决条件

- [X] 我了解这里是 Clash 官方仓库，并非 Clash.Meta / OpenClash / ClashX / Clash For Windows 或其他任何衍生版本
- [X] 我已经在[这里](https://github.com/Dreamacro/clash/issues?q=is%3Aissue+label%3Aenhancement)找过我要提出的建议，**并且没有找到相关问题**
- [X] 我已经仔细阅读 [官方 Wiki](https://github.com/Dreamacro/clash/wiki/) 

### 描述

```
2020.08.16
upgrade to v1.1.0
script support path
script:
    path: ./script.star
upgrade gvisor
bug fixed
```

2020.08.16版本提供了脚本路径，但是不能像proxy-providers做成http远程加载的方式。
希望能支持类似proxy-providers ，

```
script-provider:
  type: http
  url: "url"
  interval: 3600
  path: ./script-provider.yaml
```
