### ISSUE TITLE
[Bug] kernel: out_fd is a pipe

### ISSUE THREAD

**Issue by JiaRG** [Dreamacro/clash#2732]
### 先决条件

- [X] 我了解这里是官方开源版 Clash 核心仓库，**只提供开源版或者 Premium 内核的支持**
- [X] 我要提交 Clash 核心的问题，并非 Clash.Meta / OpenClash / ClashX / Clash For Windows 或其他任何衍生版本的问题
- [X] 我使用的是**本仓库**最新版本的 Clash 或 Clash Premium 内核
- [X] 我已经在 [Issue Tracker](……/) 中找过我要提出的 bug，**并且没有找到相关问题**
- [X] 我已经仔细阅读 [官方 Wiki](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题

### 版本

Clash 2023.04.16 linux arm with go1.20.3 Sun Apr 16 13:20:30 UTC 2023

Premium 2023.04.16 [clash-linux-armv5-2023.04.16.gz](https://github.com/Dreamacro/clash/releases/download/premium/clash-linux-armv5-2023.04.16.gz)

Linux RT-AC68U-00B0 2.6.36.4brcmarm # 1 SMP PREEMPT Tue Oct 25 14:31:19 CST 2022 armv7l ASUSWRT-Merlin-KoolShare

### 适用的作业系统

Linux

### 适用的硬件架构

armv5

### 配置文件

```YAML
# 透明代理开启DNS
dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:1053
  enhanced-mode: fake-ip # redir-host or fake-ip
  fake-ip-range: 198.18.0.1/16 # Fake IP addresses pool CIDR
  use-hosts: true # lookup hosts and return IP record
  nameserver:
    - 192.168.50.1  # AdguardHome DNS
tun:
  enable: true
  stack: system # system or gvisor
  dns-hijack:
    - any:53
  auto-route: true # manage `ip route` and `ip rules`
  #auto-redir: true # manage nftable REDIRECT
  auto-detect-interface: true # conflict with `interface-name
```

### 日志输出

未启用 tun 模式时
```Text
clash 日志正常
```

启用 tun 模式后
```Text
最开始是

ERR [Inbound] start failed error=CreateTUN("utun") failed; /dev/net/tun does not exist type=TUN stackType=system inet=198.18.0.1/16

后来通过 modprobe tun 手动 load 了下变成了

ERR [Inbound] start failed error=device or resource busy type=TUN stackType=system inet=198.18.0.1/16
```

### 问题描述

开启 clash 后系统日志疯狂打印 kernel: out_fd is a pipe

### 复现步骤

clash 配合 iptables 实现路由器的透明代理后，系统日志疯狂打印 kernel: out_fd is a pipe

see: https://vlike.work/tech/trans_proxy.html
