### ISSUE TITLE
[Bug] TUN 模式导致 Docker 容器服务无法从外网访问

### ISSUE THREAD

**Issue by silenaker** [Dreamacro/clash#2733]
### 先决条件

- [X] 我了解这里是官方开源版 Clash 核心仓库，**只提供开源版或者 Premium 内核的支持**
- [X] 我要提交 Clash 核心的问题，并非 Clash.Meta / OpenClash / ClashX / Clash For Windows 或其他任何衍生版本的问题
- [X] 我使用的是**本仓库**最新版本的 Clash 或 Clash Premium 内核
- [X] 我已经在 [Issue Tracker](……/) 中找过我要提出的 bug，**并且没有找到相关问题**
- [X] 我已经仔细阅读 [官方 Wiki](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题
- [X] （非 Premium 内核必填）我已经使用 dev 分支版本测试过，问题依旧存在

### 版本

Clash 2023.04.16 linux amd64 with go1.20.3 Sun Apr 16 13:20:30 UTC 2023

### 适用的作业系统

Linux

### 适用的硬件架构

amd64

### 配置文件

```YAML
mode: rule
dns:
  enable: true
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  nameserver:
  - 114.114.114.114
  - 223.5.5.5
  - 8.8.8.8
  fallback: []
  fake-ip-filter:
  - dns.msftncsi.com
  - www.msftncsi.com
  - www.msftconnecttest.com
tun:
  enable: true
  stack: gvisor
  dns-hijack:
  - any:53
  auto-route: true
  auto-detect-interface: true
```

### 问题描述

Clash Premium TUN 模式会导致 Docker 容器中的服务无法从外网访问

### 复现步骤

1. 在 clash 的配置文件中启用 tun，启动 clash premium
2. 用 docker 跑一个服务，比如 `docker run -p 80:80 nginx`
3. 在 host 和 容器内都能正常访问外网，出入流量走的都是 tun 接口
4. 但从外网访问 nginx 服务（容器），入流量没问题，但出流量也被路由到了 tun 接口，导致无法正常建立连接
5. 检查路由规则（`ip rule`），发现 clash 自动添加了以下规则

   ```shell
   0:      from all lookup local
   9500:   not from all dport 53 lookup main suppress_prefixlength 0
   9510:   not from all iif lo lookup 1970566510
   9520:   from 0.0.0.0 iif lo uidrange 0-4294967294 lookup 1970566510
   9530:   from 198.18.0.1 iif lo uidrange 0-4294967294 lookup 1970566510
   32766:  from all lookup main
   32767:  from all lookup default
   ```

6. 通过添加以下两条规则可暂时解决这个问题

   ```shell
   ip rule add pref 9504 from all iif docker0 dport 53 lookup 1970566510
   ip rule add pref 9505 from all iif docker0 lookup main
   ```
