### ISSUE TITLE
[Bug] DOMAIN-SUFFIX 没有效果

### ISSUE THREAD

**Issue by fuqiyang11** [Dreamacro/clash#2734]
### Prerequisites

- [X] I understand that this is the official open-source version of the Clash core, **only providing support for the open-source version or Premium version**
- [X] I am submitting an issue with the Clash core, not Clash.Meta / OpenClash / ClashX / Clash For Windows or any other derivative version
- [X] I am using the latest version of the Clash or Clash Premium core **in this repository**
- [X] I have searched at the [Issue Tracker](……/) **and have not found any related issues**
- [X] I have read the [official Wiki](https://github.com/Dreamacro/clash/wiki/) **and was unable to solve the issue**
- [ ] (required for Premium core) I've tried the `dev` branch and the issue still exists

### Version

Clash v1.15.1-10-g7f1b50f darwin amd64 with go1.20.4 2023年 5月12日 星期五 08时30分25秒 UTC

### Operating System

macOS (darwin)

### Architecture

arm64

### Configuration File

```YAML
#port: 64112
#socks-port: 64113
mixed-port: 64111

log-level: debug
allow-lan: true
bind-address: '*'
interface-name: en0

# RESTful web API listening address
#external-controller: 192.168.3.39:9090

# Clash router working mode
# rule: rule-based packet routing
# global: all packets will be forwarded to a single endpoint
# direct: directly forward the packets to the Internet
mode: rule

proxies:
  - name: "socks"
    type: socks5
    server: xxxxxx
    port: 64222
    username: xxxxxx
    password: xxxxxx
    # tls: true
    # skip-cert-verify: true
    # udp: true

rules:
  - DOMAIN-KEYWORD,baidu,socks
  - DOMAIN-SUFFIX,google.com,socks
  - MATCH,DIRECT
  #- MATCH,socks
```

### Log

```Text
只有info日志, 我也纳闷

time="2023-05-12T18:00:06+08:00" level=info msg="Mixed(http+socks) proxy listening at: [::]:64111"
time="2023-05-12T18:00:38+08:00" level=info msg="[TCP] 127.0.0.1:62227 --> 172.217.24.238:80 match Match() using DIRECT"
```

### Description

我直接修改metadata.Host是可以的

![image](https://github.com/Dreamacro/clash/assets/18230345/52e78797-c3a8-46be-9166-019bacd8d184)

### Reproduction Steps

curl -v -4 --connect-timeout 5 --socks5 127.0.0.1:64111  http://google.com
