### ISSUE TITLE
[Bug] 使用docker部署后，telnet 7892端口，会导致异常。

### ISSUE THREAD

**Issue by cklxh** [Dreamacro/clash#2742]
### 先决条件

- [X] 我了解这里是官方开源版 Clash 核心仓库，**只提供开源版或者 Premium 内核的支持**
- [X] 我要提交 Clash 核心的问题，并非 Clash.Meta / OpenClash / ClashX / Clash For Windows 或其他任何衍生版本的问题
- [X] 我使用的是**本仓库**最新版本的 Clash 或 Clash Premium 内核
- [X] 我已经在 [Issue Tracker](……/) 中找过我要提出的 bug，**并且没有找到相关问题**
- [X] 我已经仔细阅读 [官方 Wiki](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题
- [ ] （非 Premium 内核必填）我已经使用 dev 分支版本测试过，问题依旧存在

### 版本

1.15.1

### 适用的作业系统

Linux

### 适用的硬件架构

arm64

### 配置文件

```YAML
port: 7890
socks-port: 7891
redir-port: 7892
mixed-port: 7893
allow-lan: true
mode: rule
log-level: info
ipv6: false

hosts:
  services.googleapis.cn: 142.250.196.131
  www.google.cn: 142.250.196.131
external-controller: 0.0.0.0:9090
clash-for-android:
  append-system-dns: false
profile:
  tracing: true

rules:
 - DOMAIN-SUFFIX,local,DIRECT
 - IP-CIDR,192.168.0.0/16,DIRECT,no-resolve
 - IP-CIDR,10.0.0.0/8,DIRECT,no-resolve
 - IP-CIDR,172.16.0.0/12,DIRECT,no-resolve
 - IP-CIDR,127.0.0.0/8,DIRECT,no-resolve
 - IP-CIDR,100.64.0.0/10,DIRECT,no-resolve
```

### 日志输出

```Text
time="2023-05-16T14:33:34Z" level=info msg="[TCP] 172.17.0.2:59242 --> 172.17.0.2:7892 match IPCIDR(172.16.0.0/12) using DIRECT"
time="2023-05-16T14:33:34Z" level=info msg="[TCP] 172.17.0.2:59244 --> 172.17.0.2:7892 match IPCIDR(172.16.0.0/12) using DIRECT"
time="2023-05-16T14:33:34Z" level=info msg="[TCP] 172.17.0.2:59246 --> 172.17.0.2:7892 match IPCIDR(172.16.0.0/12) using DIRECT"
time="2023-05-16T14:33:34Z" level=info msg="[TCP] 172.17.0.2:59248 --> 172.17.0.2:7892 match IPCIDR(172.16.0.0/12) using DIRECT"
time="2023-05-16T14:33:34Z" level=info msg="[TCP] 172.17.0.2:59250 --> 172.17.0.2:7892 match IPCIDR(172.16.0.0/12) using DIRECT"
time="2023-05-16T14:33:34Z" level=info msg="[TCP] 172.17.0.2:59252 --> 172.17.0.2:7892 match IPCIDR(172.16.0.0/12) using DIRECT"
time="2023-05-16T14:33:34Z" level=info msg="[TCP] 172.17.0.2:59254 --> 172.17.0.2:7892 match IPCIDR(172.16.0.0/12) using DIRECT"
time="2023-05-16T14:33:39Z" level=warning msg="[TCP] dial DIRECT 192.168.31.103:64295 --> beacons.gvt2.com:443 error: dial tcp4 172.217.28.227:443: i/o timeout"
time="2023-05-16T14:33:39Z" level=warning msg="[TCP] dial DIRECT (match IPCIDR/172.16.0.0/12) 172.17.0.2:59256 --> 172.17.0.2:7892 error: dial tcp4 172.17.0.2:7892: socket: too many open files"
```

### 问题描述

我是在docker中部署的，配置文件如上，rules部分未完整贴出，dns未贴，我在局域网内，另外一台电上执行telnet 172.17.0.2 7892就会出现此问题。（当然了，iptables -t nat -A PREROUTING -s 192.168.31.103 -p tcp --dport 80 -j DNAT --to-destination 172.17.0.2:7892）这样子也是会出现这个问题。。。。。我尝试过telnet 7890端口，不会出现此问题，并且7890端口的代理配置后可以正常使用。

### 复现步骤

在docker中部署（https://hub.docker.com/r/dreamacro/clash），直接telnet容器ip 7892。
