### ISSUE TITLE
config配置文件问题咨询

### ISSUE THREAD

**Issue by yzh1994414** [Dreamacro/clash#2743]
### 先决条件

- [X] 我了解这里是官方开源版 Clash 核心仓库，**只提供开源版或者 Premium 内核的支持**
- [X] 我要提交 Clash 核心的问题，并非 Clash.Meta / OpenClash / ClashX / Clash For Windows 或其他任何衍生版本的问题
- [X] 我使用的是**本仓库**最新版本的 Clash 或 Clash Premium 内核
- [X] 我已经在 [Issue Tracker](……/) 中找过我要提出的 bug，**并且没有找到相关问题**
- [X] 我已经仔细阅读 [官方 Wiki](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题
- [X] （非 Premium 内核必填）我已经使用 dev 分支版本测试过，问题依旧存在

### 版本

latest

### 适用的作业系统

Linux

### 适用的硬件架构

amd64

### 配置文件

```YAML
allow-lan: true
dns:
  enable: true
  fallback:
  - 8.8.8.8
  - 8.8.4.4
  - tls://1.0.0.1:853
  - tls://dns.google:853
  nameserver:
  - 119.29.29.29
  - 223.5.5.5
external-controller: 0.0.0.0:9090
log-level: info
mixed-port: 7890
proxies:
- alterId: 0
  cipher: auto
  name: proxy_1
  netword: ws
  port: 40187
  server: 7a6rs.cdn.node.a.tddns-ounk.com
  skip-cert-verify: true
  tls: false
  type: vmess
  uuid: 6ab60db7-8906-36b1-aecb-b1090714bf
  ws-opts:
    path: /80b48db1-7a27-4d2b-a12b-009feb3b04.j.live001.m3u8
proxy-groups:
- name: 节点选择
  proxies:
  - 自动选择
  - DIRECT
  type: select
- interval: 300
  name: 自动选择
  proxies:
  - proxy_1
  tolerance: 50
  type: url-test
  url: http://www.gstatic.com/generate_204
rules:
- DOMAIN-SUFFIX,chat.openai.com, 节点选择
- DOMAIN-SUFFIX,openai.com, 节点选择
```

### 日志输出

```Text
time="2023-05-16T16:21:22Z" level=info msg="Mixed(http+socks) proxy listening at: [::]:7890"
time="2023-05-16T16:21:22Z" level=info msg="RESTful API listening at: [::]:9090"
time="2023-05-16T16:21:36Z" level=info msg="[TCP] 192.161.20.1:43464 --> api.openai.com:443 match DomainSuffix(openai.com) using 节点选择[proxy_1]"
```

### 问题描述

**配置文件中proxies参数写成 这样是可以使用的。**
proxies:
  \- {"name":"proxy_1","type":"vmess","server":"7a6rs.cdn.node.a.tddns-ounk.com","port":40187,"cipher":"auto","uuid":"6ab60db7-8906-36bcb-b1091a0714bf","alterId":0,"tls":false,"skip-cert-verify":true,"servername":"","network":"ws","ws-opts":{"path":"m3u8"}}

**但是参考https://github.com/Dreamacro/clash/wiki/Configuration%3A-Example-Configuration文档写成yaml标准格式就是不可用**
proxies:
\- alterId: 0
  cipher: auto
  name: proxy_1
  netword: ws
  port: 40187
  server: 7a6rs.cdn.node.a.tddns-ounk.com
  skip-cert-verify: true
  tls: false
  type: vmess
  uuid: 6ab60db7-8906-36b1-aecb-b1091a0714bf
  ws-opts:
    path: /m3u8
