### ISSUE TITLE
[Question] 开启tun模式后无法接管流量

### ISSUE THREAD

**Issue by hanshuang87** [Dreamacro/clash#2744]
### 先决条件

- [X] 我了解这里是官方开源版 Clash 核心仓库，**只提供开源版或者 Premium 内核的支持**
- [X] 我要提交 Clash 核心的问题，并非 Clash.Meta / OpenClash / ClashX / Clash For Windows 或其他任何衍生版本的问题
- [X] 我使用的是**本仓库**最新版本的 Clash 或 Clash Premium 内核
- [X] 我已经在 [Issue Tracker](……/) 中找过我要提出的 bug，**并且没有找到相关问题**
- [X] 我已经仔细阅读 [官方 Wiki](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题
- [ ] （非 Premium 内核必填）我已经使用 dev 分支版本测试过，问题依旧存在

### 版本

Version 2023.04.16

### 适用的作业系统

Linux

### 适用的硬件架构

amd64

### 配置文件

```YAML
# HTTP 代理端口
port: 7890

# SOCKS5 代理端口
socks-port: 7891

# Linux 和 macOS 的 redir 代理端口
redir-port: 7892

# 允许局域网的连接
allow-lan: true

# 规则模式：Rule（规则） / Global（全局代理）/ Direct（全局直连）
mode: rule

# 设置日志输出级别 (默认级别：silent，即不输出任何内容，以避免因日志内容过大而导致程序内存溢出）。
# 5 个级别：silent / info / warning / error / debug。级别越高日志输出量越大，越倾向于调试，若需要请自行开启。
log-level: info
# Clash 的 RESTful API
external-controller: '0.0.0.0:9090'

# RESTful API 的口令
secret: 123456

# 您可以将静态网页资源（如 clash-dashboard）放置在一个目录中，clash 将会服务于 `RESTful API/ui`
# 参数应填写配置目录的相对路径或绝对路径。
external-ui: /home/clash-for-linux/dashboard/public

interface-name: ens33

tun:
  enable: true
  stack: system
  dns-hijack:
    - any:53
  auto-redir: true
  auto-route: true

dns:
    enable: true
    listen: :53 # 必须要开启Server监听
    enhanced-mode: fake-ip
    nameserver:
        - 114.114.114.114
        - 223.5.5.5
    fallback:
        - 8.8.8.8
```

### 日志输出

```Text
09:56:59 INF [DNS] server listening addr=[::]:53
09:56:59 INF [Inbound] HTTP proxy listening addr=[::]:7890
09:56:59 INF [API] listening addr=[::]:9090
09:56:59 INF [Inbound] SOCKS proxy listening addr=[::]:7891
09:56:59 INF [Inbound] Redirect proxy listening addr=[::]:7892
09:56:59 DBG [TUN] mtu updated iface=utun gateway=198.18.0.2
09:56:59 DBG [TUN] interface up iface=utun gateway=198.18.0.2
09:56:59 DBG [TUN] interface up iface=utun gateway=198.18.0.2
09:56:59 DBG [TUN] mtu updated iface=utun gateway=198.18.0.2
09:56:59 INF [Inbound] TUN listening iface=utun gateway=198.18.0.1
```

### 问题描述

开启tun模式后，ip route输出如下：
default via 172.24.194.254 dev ens33 
169.254.0.0/16 dev ens33 scope link metric 1002 
172.24.194.0/24 dev ens33 proto kernel scope link src 172.24.194.39 
198.18.0.0/16 dev utun proto kernel scope link src 198.18.0.1 

感觉流量没有被接管
[root@localhost /home/clash-for-linux]#curl -vvv https://www.google.com 
* About to connect() to www.google.com port 443 (#0)
*   Trying 198.18.0.5...
* Connected to www.google.com (198.18.0.5) port 443 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
*   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
* NSS error -5961 (PR_CONNECT_RESET_ERROR)
* TCP connection reset by peer
* Closing connection 0
curl: (35) TCP connection reset by peer
