### ISSUE TITLE
[Bug] <proxy-provider和ruler-provider，在获取配置文件和在线规则集时只能直连，导致无法获取配置和规则集>

### ISSUE THREAD

**Issue by wangke123147** [Dreamacro/clash#2775]
### 先决条件

- [X] 我了解这里是官方开源版 Clash 核心仓库，**只提供开源版或者 Premium 内核的支持**
- [X] 我要提交 Clash 核心的问题，并非 Clash.Meta / OpenClash / ClashX / Clash For Windows 或其他任何衍生版本的问题
- [X] 我使用的是**本仓库**最新版本的 Clash 或 Clash Premium 内核
- [X] 我已经在 [Issue Tracker](……/) 中找过我要提出的 bug，**并且没有找到相关问题**
- [X] 我已经仔细阅读 [官方 Wiki](https://dreamacro.github.io/clash/) 并无法自行解决问题
- [ ] （非 Premium 内核必填）我已经使用 dev 分支版本测试过，问题依旧存在

### 版本

v1.16.0

### 适用的作业系统

Windows

### 适用的硬件架构

amd64

### 配置文件

```YAML
mixed-port: 7890
allow-lan: true
mode: rule
log-level: info
external-controller: '127.0.0.1:9090'
dns:
    enable: true
    ipv6: false
    default-nameserver: [223.5.5.5, 119.29.29.29]
    enhanced-mode: fake-ip
    fake-ip-range: 198.18.0.1/16
    use-hosts: true
    nameserver: ['https://doh.pub/dns-query', 'https://dns.alidns.com/dns-query']
    fallback: ['https://doh.dns.sb/dns-query', 'https://dns.cloudflare.com/dns-query', 'https://dns.twnic.tw/dns-query', 'tls://8.8.4.4:853']
    fallback-filter: { geoip: true, ipcidr: [240.0.0.0/4, 0.0.0.0/32] }
proxy-providers:
  INIT1:
    type: http
    path: ./profiles/INIT1.yaml
    url: 
    interval: 10800
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300

  NETFLIX:
    type: file
    path: ./profiles/INIT1.yaml
    filter: 🇸🇬
    interval: 10800
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300

  bahamut:
    type: file
    path: ./profiles/INIT1.yaml
    filter: 台湾|🇭🇰|🇸🇬|🇯🇵|🇰🇷
    interval: 10800
    health-check:
      enable: true
      interval: 300
      url: http://www.gstatic.com/generate_204

  HK:
    type: file
    path: ./profiles/INIT1.yaml
    filter: 🇭🇰
    interval: 10800
    health-check:
      enable: true
      interval: 300
      url: http://www.gstatic.com/generate_204

  TikTok:
    type: file
    path: ./profiles/INIT1.yaml
    filter: 🇸🇬|🇯🇵|🇰🇷|🇺🇸
    interval: 10800
    health-check:
      enable: true
      interval: 300
      url: http://www.gstatic.com/generate_204

  BILIBILI:
    type: file
    path: ./profiles/INIT1.yaml
    filter: 台湾|🇭🇰
    interval: 10800
    health-check:
      enable: true
      interval: 300
      url: http://www.gstatic.com/generate_204

proxy-groups:
  - name: 国外流量
    type: select
    use:
      - INIT1
    proxies:
      - DIRECT
      - 香港选择⚡

  - name: 香港选择⚡
    type: select
    use: 
      - HK

  - name: bilibili
    type: select
    use:
      - BILIBILI
    proxies:
      - DIRECT
      - 香港选择⚡

  - name: Netflix
    type: select
    use:
      - NETFLIX

  - name: GPT
    type: select
    use:
      - INIT1

  - name: TikTok
    type: select
    use:
      - TikTok

  - name: 动画疯
    type: select
    use:
      - bahamut
    proxies:
      - 国外流量

  - name: 其他流量
    type: select
    proxies:
      - DIRECT
      - 国外流量

rule-providers:
  reject:
    type: http
    behavior: domain
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/reject.txt
    path: ./ruleset/reject.yaml
    interval: 21600

  icloud:
    type: http
    behavior: domain
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/icloud.txt
    path: ./ruleset/icloud.yaml
    interval: 21600

  apple:
    type: http
    behavior: domain
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/apple.txt
    path: ./ruleset/apple.yaml
    interval: 21600

  proxy:
    type: http
    behavior: domain
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/proxy.txt
    path: ./ruleset/proxy.yaml
    interval: 21600

  direct:
    type: http
    behavior: domain
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/direct.txt
    path: ./ruleset/direct.yaml
    interval: 21600

  private:
    type: http
    behavior: domain
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/private.txt
    path: ./ruleset/private.yaml
    interval: 21600

  gfw:
    type: http
    behavior: domain
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/gfw.txt
    path: ./ruleset/gfw.yaml
    interval: 21600

  tld-not-cn:
    type: http
    behavior: domain
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/tld-not-cn.txt
    path: ./ruleset/tld-not-cn.yaml
    interval: 21600

  telegramcidr:
    type: http
    behavior: ipcidr
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/telegramcidr.txt
    path: ./ruleset/telegramcidr.yaml
    interval: 21600

  cncidr:
    type: http
    behavior: ipcidr
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/cncidr.txt
    path: ./ruleset/cncidr.yaml
    interval: 21600

  lancidr:
    type: http
    behavior: ipcidr
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/lancidr.txt
    path: ./ruleset/lancidr.yaml
    interval: 21600

  applications:
    type: http
    behavior: classical
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/applications.txt
    path: ./ruleset/applications.yaml
    interval: 21600
  bilibili:
    behavior: classical
    type: http
    url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/BiliBili/BiliBili.yaml
    path: ./ruleset/bilibili.yaml
    interval: 21600

  TikTok:
    behavior: classical
    type: http
    url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/TikTok/TikTok.yaml
    path: ./ruleset/TikTok.yaml
    interval: 21600

  NetFlix:
    behavior: classical
    type: http
    url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Netflix/Netflix_Classical.yaml
    path: ./ruleset/NetFlix.yaml
    interval: 21600

  GPT:
    behavior: classical
    type: http
    url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/OpenAI/OpenAI.yaml
    path: ./ruleset/GPT.yaml
    interval: 21600

  巴哈姆特:
    behavior: classical
    type: http
    url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Bahamut/Bahamut.yaml
    path: ./ruleset/Bahamut.yaml
    interval: 21600

rules:
  #谷歌
  - DOMAIN-SUFFIX,googleapis.cn,国外流量
  - DOMAIN-SUFFIX,googleapis.com,国外流量

  #bilibili
  - RULE-SET,bilibili,bilibili

  #TikTok
  - RULE-SET,TikTok,TikTok

  #巴哈姆特动画疯
  - RULE-SET,巴哈姆特,动画疯

  #ChatGpt
  - RULE-SET,GPT,GPT

  #奈飞
  - RULE-SET,NetFlix,Netflix











  - PROCESS-NAME,v2ray,DIRECT
  - PROCESS-NAME,xray,DIRECT
  - PROCESS-NAME,naive,DIRECT
  - PROCESS-NAME,trojan,DIRECT
  - PROCESS-NAME,trojan-go,DIRECT
  - PROCESS-NAME,ss-local,DIRECT
  - PROCESS-NAME,privoxy,DIRECT
  - PROCESS-NAME,leaf,DIRECT
  - PROCESS-NAME,v2ray.exe,DIRECT
  - PROCESS-NAME,xray.exe,DIRECT
  - PROCESS-NAME,naive.exe,DIRECT
  - PROCESS-NAME,trojan.exe,DIRECT
  - PROCESS-NAME,trojan-go.exe,DIRECT
  - PROCESS-NAME,ss-local.exe,DIRECT
  - PROCESS-NAME,privoxy.exe,DIRECT
  - PROCESS-NAME,leaf.exe,DIRECT
  - PROCESS-NAME,Surge,DIRECT
  - PROCESS-NAME,Surge 2,DIRECT
  - PROCESS-NAME,Surge 3,DIRECT
  - PROCESS-NAME,Surge 4,DIRECT
  - PROCESS-NAME,Surge%202,DIRECT
  - PROCESS-NAME,Surge%203,DIRECT
  - PROCESS-NAME,Surge%204,DIRECT
  - PROCESS-NAME,Thunder,DIRECT
  - PROCESS-NAME,DownloadService,DIRECT
  - PROCESS-NAME,qBittorrent,DIRECT
  - PROCESS-NAME,Transmission,DIRECT
  - PROCESS-NAME,fdm,DIRECT
  - PROCESS-NAME,aria2c,DIRECT
  - PROCESS-NAME,Folx,DIRECT
  - PROCESS-NAME,NetTransport,DIRECT
  - PROCESS-NAME,uTorrent,DIRECT
  - PROCESS-NAME,WebTorrent,DIRECT
  - PROCESS-NAME,aria2c.exe,DIRECT
  - PROCESS-NAME,BitComet.exe,DIRECT
  - PROCESS-NAME,fdm.exe,DIRECT
  - PROCESS-NAME,NetTransport.exe,DIRECT
  - PROCESS-NAME,qbittorrent.exe,DIRECT
  - PROCESS-NAME,Thunder.exe,DIRECT
  - PROCESS-NAME,ThunderVIP.exe,DIRECT
  - PROCESS-NAME,transmission-daemon.exe,DIRECT
  - PROCESS-NAME,transmission-qt.exe,DIRECT
  - PROCESS-NAME,uTorrent.exe,DIRECT
  - PROCESS-NAME,WebTorrent.exe,DIRECT
  - DOMAIN,clash.razord.top,DIRECT
  - DOMAIN,yacd.haishan.me,DIRECT
  - RULE-SET,applications,DIRECT
  - RULE-SET,private,DIRECT
  - RULE-SET,reject,REJECT
  - RULE-SET,icloud,DIRECT
  - RULE-SET,apple,DIRECT
  - RULE-SET,direct,DIRECT
  - RULE-SET,proxy,国外流量
  - RULE-SET,lancidr,DIRECT
  - RULE-SET,cncidr,DIRECT
  - RULE-SET,telegramcidr,国外流量
  - GEOIP,LAN,DIRECT
  - GEOIP,CN,DIRECT
  - MATCH,其他流量
```

### 问题描述

在自己写配置文件时，发现配置文件一直不能下载成功。后发现是因为proxy-provider和ruler-provider，在获取配置文件和在线规则集时只能直连。而我的订阅链接直连时无法正常访问，导致配置文件无法下载并报错。
