### ISSUE TITLE
[Bug] proxy-provider 下载失败，通过浏览器手动下载可以成功。

### ISSUE THREAD

**Issue by QS0x01** [Dreamacro/clash#2779]
### 先决条件

- [X] 我了解这里是官方开源版 Clash 核心仓库，**只提供开源版或者 Premium 内核的支持**
- [X] 我要提交 Clash 核心的问题，并非 Clash.Meta / OpenClash / ClashX / Clash For Windows 或其他任何衍生版本的问题
- [X] 我使用的是**本仓库**最新版本的 Clash 或 Clash Premium 内核
- [X] 我已经在 [Issue Tracker](……/) 中找过我要提出的 bug，**并且没有找到相关问题**
- [X] 我已经仔细阅读 [官方 Wiki](https://dreamacro.github.io/clash/) 并无法自行解决问题
- [ ] （非 Premium 内核必填）我已经使用 dev 分支版本测试过，问题依旧存在

### 版本

2023.05.19

### 适用的作业系统

Windows

### 配置文件

```YAML
proxy-providers:
  Hybrid:
    type: http
    url: "http://127.0.0.1:25500/sub?target=clash&url=https://sub.xsus.me/api/v1/client/subscribe?token=XXX&udp=true&list=true"
    interval: 7200
    path: ./Hybrid.yaml
    health-check:
      enable: true
      interval: 60
      url: https://www.gstatic.com/generate_204
```

### 日志输出
![image](https://user-images.githubusercontent.com/119924985/244225880-524ae4e5-ffbd-4dd4-a949-f69dc6116a38.png)

### 问题描述

https://github.com/Fndroid/clash_for_windows_pkg/issues/4531
https://github.com/Fndroid/clash_for_windows_pkg/issues/4338
https://github.com/Fndroid/clash_for_windows_pkg/issues/3931
<img width="189" alt="image" src="https://github.com/Dreamacro/clash/assets/119924985/4c2891ab-1abf-4596-b000-ba46a1951a3b">

proxy-provider 文件通过浏览器能成功下载，但是通过 cfw 始终失败。
考虑到远程 sub-sonverter 不可控，就自己在本地搭了个进程收集日志,。

### 复现步骤

1. 使用 cfw child-process 运行 sub-sonverter，配置更新订阅使用系统代理（localhost: 27890 ）
2.  载入一个包含 proxy-provider 的 profile，提示 file must have a proxies filed，实为 sub-converter 下载源订阅失败，日志见 CFW Log
3.  打开该 profile，Ctrl+Click 在 EDGE 浏览器打开 porxy=provider 的 url，成功下载，日志见 EDGE LOG.
4.  Disabled cache of sub-converter. Retry Step.2. Fail.
5.  Retry Step.3. Success.
