### ISSUE TITLE
[Bug] docker v1.13.0以上的版本都无法使用以前的配置文件正常启动

### ISSUE THREAD

**Issue by czxinshui** [Dreamacro/clash#2790]
### 先决条件

- [X] 我了解这里是官方开源版 Clash 核心仓库，**只提供开源版或者 Premium 内核的支持**
- [X] 我要提交 Clash 核心的问题，并非 Clash.Meta / OpenClash / ClashX / Clash For Windows 或其他任何衍生版本的问题
- [X] 我使用的是**本仓库**最新版本的 Clash 或 Clash Premium 内核
- [X] 我已经在 [Issue Tracker](……/) 中找过我要提出的 bug，**并且没有找到相关问题**
- [X] 我已经仔细阅读 [官方 Wiki](https://dreamacro.github.io/clash/) 并无法自行解决问题
- [ ] （非 Premium 内核必填）我已经使用 dev 分支版本测试过，问题依旧存在

### 版本

v1.16.0

### 适用的作业系统

Linux

### 适用的硬件架构

amd64

### 配置文件

```YAML
port: 7890
socks-port: 7891
allow-lan: true
ipv6: true
mode: Rule
log-level: info
external-controller: 0.0.0.0:9090
experimental:
      ignore-resolve-fail: true 
dns:
  enable: true
  enhanced-mode: redir-host
  nameserver:
    - https://dns.alidns.com/dns-query
  fallback:
    - https://dns.google/dns-query
proxies:
```

### 日志输出

```Text
1
```

### 问题描述

CPU: i3-8100
系统：unraid 
DOCKER CLASH v1.13.0和 v1.13.0以下的版本都可以正常使用， v1.13.0以上的版本都无法使用以前的配置文件正常启动

### 复现步骤

1
