### ISSUE TITLE
[Bug] fake-ip-filter 中过滤的部分域名无法正常访问

### ISSUE THREAD

**Issue by Well2333** [Dreamacro/clash#2792]
### 先决条件

- [X] 我了解这里是官方开源版 Clash 核心仓库，**只提供开源版或者 Premium 内核的支持**
- [X] 我要提交 Clash 核心的问题，并非 Clash.Meta / OpenClash / ClashX / Clash For Windows 或其他任何衍生版本的问题
- [X] 我使用的是**本仓库**最新版本的 Clash 或 Clash Premium 内核
- [X] 我已经在 [Issue Tracker](……/) 中找过我要提出的 bug，**并且没有找到相关问题**
- [X] 我已经仔细阅读 [官方 Wiki](https://dreamacro.github.io/clash/) 并无法自行解决问题
- [ ] （非 Premium 内核必填）我已经使用 dev 分支版本测试过，问题依旧存在

### 版本

2023.05.29

### 适用的作业系统

Windows

### 适用的硬件架构

amd64

### 配置文件

```YAML
dns:
  enable: true
  listen: 0.0.0.0:53
  use-hosts: true
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  nameserver:
    - https://dns.alidns.com/dns-query
    - tls://dns.alidns.com
    - https://doh.pub/dns-query
    - tls://dns.rubyfish.cn:853
  fallback:
    - tcp://1.1.1.1
    - https://dns.adguard-dns.com/dns-query
    - https://dns.google/dns-query
    - https://dns.cloudflare.com/dns-query
  fake-ip-filter:
    - "*.lan"
    - "*.linksys.com"
    - "*.linksyssmartwifi.com"
    - swscan.apple.com
    - mesu.apple.com
    - "*.msftconnecttest.com"
    - "*.msftncsi.com"
    - time.*.com
    - time.*.gov
    - time.*.edu.cn
    - time.*.apple.com
    - time1.*.com
    - time2.*.com
    - time3.*.com
    - time4.*.com
    - time5.*.com
    - time6.*.com
    - time7.*.com
    - ntp.*.com
    - ntp1.*.com
    - ntp2.*.com
    - ntp3.*.com
    - ntp4.*.com
    - ntp5.*.com
    - ntp6.*.com
    - ntp7.*.com
    - "*.time.edu.cn"
    - "*.ntp.org.cn"
    - +.pool.ntp.org
    - time1.cloud.tencent.com
    - +.srv.nintendo.net
    - +.stun.playstation.net
    - xbox.*.microsoft.com
    - +.xboxlive.com
    - localhost.ptlogin2.qq.com
    - +.stun.*.*
    - +.stun.*.*.*
    - +.stun.*.*.*.*
    - +.stun.*.*.*.*.*
    - WORKGROUP
tun:
  enable: true
  stack: gvisor
  auto-route: true
  auto-detect-interface: true
  dns-hijack:
    - any:53
```

### 问题描述

在使用 TUN 模式开启 clash 后，无法访问 [www.msftconnecttest.com](http://www.msftconnecttest.com/connecttest.txt)

![image](https://github.com/Dreamacro/clash/assets/40534114/36f3e4d3-cb77-4c07-8722-9301cb94147a)

我在日志中也并未找到相关的条目，说明 fake-ip-filter 是正常工作的，clash 理论上没有处理此连接的流量。为了验证这个猜想，我使用了 ping 去尝试连接，ip 也是正常的（说明 fake-ip 未进行拦截，否则应该是 `198.18.0.x`）。

![image](https://github.com/Dreamacro/clash/assets/40534114/3fe03cbc-0c28-4a4c-909a-a0ebea97b593)

同时，我在控制面板中也查询到 clash tunnel 没有网络连接

![image](https://github.com/Dreamacro/clash/assets/40534114/5336e8dd-4b19-4ba7-bfc5-eb4bfe72389b)

我尝试手动指定了 interface，配置如下，也未能解决问题（其中 `以太网 3` 是我的物理网卡），其表现与自动检测完全一致，因此我认为也不是选择了错误的网卡导致的

```yaml
tun:
  enable: true
  stack: gvisor
  auto-route: true
  dns-hijack:
    - any:53
interface-name: 以太网 3
```

![image](https://github.com/Dreamacro/clash/assets/40534114/251eca87-4ffc-45b7-a966-3f1910de6e71)

我尝试使用 `stack: system` 但由于防火墙或某种东西的拦截导致 TUN 模式直接失效了，不过这是另外的问题了。

cfw 仓库中相似的 issue 
https://github.com/Fndroid/clash_for_windows_pkg/issues/3242

目前我不太理解这个问题的成因，我在关闭 clash 后是可以稳定访问 [www.msftconnecttest.com](http://www.msftconnecttest.com/connecttest.txt) 的，所以我不认为是我的网络出现问题了。但是开启一个理论上不会处理该流量的虚拟网卡就会导致无法访问，而且是非 UWP 的浏览器也无法访问，甚至在开启前后的 DNS 也都是正常的。我无法确定这是否是 clash 内核的问题，希望有了解此问题的大佬可以找到此问题真正的成因吧。
