### ISSUE TITLE
[Feature] 按照规则如果节点失效，触发 fallback，是否支持持续 test 节点判断是否恢复重新选用新节点

### ISSUE THREAD

**Issue by Kaijun** [Dreamacro/clash#2799]
### 先决条件

- [X] 我了解这里是 Clash 官方仓库，并非 Clash.Meta / OpenClash / ClashX / Clash For Windows 或其他任何衍生版本
- [X] 我已经在[这里](https://github.com/Dreamacro/clash/issues?q=is%3Aissue+label%3Aenhancement)找过我要提出的建议，**并且没有找到相关问题**
- [X] 我已经仔细阅读 [官方 Wiki](https://dreamacro.github.io/clash/) 

### 描述

假设我有个一组节点，其中 n1 n2 n3 为低倍率节点，我希望通常情况都优先使用低倍率节点。

我想要配置如下优先级

1. 优先 select （可选范围是全部节点，日常我从中选中低倍率的）
2. 如果节点崩了使用 fallback （挨个尝试低倍率节点 n1 n2 n3 ）
3. 如果还是失败，则 url-test 剩下的节点
4. （重要）如果 select 节点恢复了，则自动切回 select

我按照我对文档的理解，大概做了如下配置，通过 proxy-group 的嵌套功能：

```
proxy-groups:
  - name: PROXY
    type: fallback
    proxies:
      - Select
      - Fallback
      - UrlTest
  - name: Select
    type: select
    use:
      - ...
  - name: Fallback
    type: fallback
    use:
      - ...
    filter: "低倍率"
  - name: UrlTest
    type: url-test
    use:
      - ...
 ```

这里我有两个疑虑：

1：这里我让最终的 PROXY 组进行嵌套，使用 fallback 类型，并自动尝试 Select -> Fallback -> UrlTest

不知道这样的 fallback 类型是不是合理？

2：**实际测试下来，这里是能实现我前面提到的 1-3 功能，但是我发现 Select 节点回归正常后，clash 并不会再重新按照 proxies 的优先级重新选择使用 Select ，而是一直保持之前 fallback 选中的节点**

有没有方式能实现恢复后重新优先使用 Select 的操作？

### 可能的解决方案

fallback 类型，是否能够支持设置 reset interval，重新从前往后进行探测发现可用节点
