### ISSUE TITLE
[Bug] <clash本地端口设置身份认证后，iphone连接代理，不能访问bilibili，youtube等网站>

### ISSUE THREAD

**Issue by laningya** [Dreamacro/clash#2807]
### 先决条件

- [X] 我了解这里是官方开源版 Clash 核心仓库，**只提供开源版或者 Premium 内核的支持**
- [X] 我要提交 Clash 核心的问题，并非 Clash.Meta / OpenClash / ClashX / Clash For Windows 或其他任何衍生版本的问题
- [X] 我使用的是**本仓库**最新版本的 Clash 或 Clash Premium 内核
- [X] 我已经在 [Issue Tracker](……/) 中找过我要提出的 bug，**并且没有找到相关问题**
- [X] 我已经仔细阅读 [官方 Wiki](https://dreamacro.github.io/clash/) 并无法自行解决问题
- [ ] （非 Premium 内核必填）我已经使用 dev 分支版本测试过，问题依旧存在

### 版本

1.15.1

### 适用的作业系统

Linux, Windows

### 适用的硬件架构

armv7

### 配置文件

```YAML
external-ui: /ui
secret: "***"
mixed-port: 7890
authentication:
 - "***:***"
allow-lan: true
mode: Rule
log-level: info
external-controller: 0.0.0.0:9090
```

### 问题描述

局域网有块linux开发板通过docker运行clash，暴露7890端口，在配置文件设置authentication选项后，iphone连接wifi配置代理后，访问twitter正常，youtube打开可以正常刷新，但是打开视频会提示网络错误，国内的B站也显示网络连接失败，windows使用代理则没有问题。如果删掉authentication选项，windows和iphone都能正常使用。why？
