### ISSUE TITLE
[Bug] <问题标题>节点状态检测的问题

### ISSUE THREAD

**Issue by ac169** [Dreamacro/clash#2809]
### 先决条件

- [X] 我了解这里是官方开源版 Clash 核心仓库，**只提供开源版或者 Premium 内核的支持**
- [X] 我要提交 Clash 核心的问题，并非 Clash.Meta / OpenClash / ClashX / Clash For Windows 或其他任何衍生版本的问题
- [X] 我使用的是**本仓库**最新版本的 Clash 或 Clash Premium 内核
- [X] 我已经在 [Issue Tracker](……/) 中找过我要提出的 bug，**并且没有找到相关问题**
- [X] 我已经仔细阅读 [官方 Wiki](https://dreamacro.github.io/clash/) 并无法自行解决问题
- [ ] （非 Premium 内核必填）我已经使用 dev 分支版本测试过，问题依旧存在

### 版本

1.35

### 适用的作业系统

Linux

### 适用的硬件架构

amd64, mips-softfloat

### 配置文件

```YAML
......

log-level: error

......

proxy-providers:
  frees:
    type: file
    path: ./frees.yaml
    health-check:
      enable: true
      url: https://www.google.com/generate_204
      interval: 3600

proxy-groups:
  - name: 默认
    type: select
    proxies:
      - 延迟
      - 均衡
      - 转移
      - 选择
      - DIRECT
  - name: 延迟
    type: url-test
    url: https://www.google.com/generate_204
    interval: 900
    use:
      - frees
  - name: 转移
    type: fallback
    url: https://www.google.com/generate_204
    interval: 900
    use:
      - frees
  - name: 均衡
    type: load-balance
    url: https://www.google.com/generate_204
    interval: 900
    use:
      - frees
  - name: 选择
    type: select
    use:
      - frees

......
```

### 问题描述

本次提问主要涉及节点自动检测准确性和是否重复等相关问题展开

1. 在上述配置下： proxy-providers 和 proxy-groups 都会按照自己配置的频率来检查节点状态（检查 1 + 4 次），还是只检查1次 （proxy-providers）或是 4次 （proxy-groups）也就是是否存在多次重复检测的情况？

2. 状态检测是简单的做各类ping端口测试，还是连上节点具体协议后带负载测试url状态（个人认为应该是后者这种方式）但是有一个问题就是很多时候无效的节点直接选择却是可以用的，也就是检测结果不是太准确，不知道问题出在哪里？

3. 同样都是 log-level: error 在x86平台可以正常输出系统日志，在MIPS上无系统日志。

需求：尽量减少重复检测及检测的准确性，避免节点被墙或者是节点误认为攻击！比如：设定一个失败的阈，值当 proxy-providers 节点加载之后检测结果达到失败的阈值后 就不再检测（包括 proxy-groups ），否可以增加多个检测的 url 以提高准确性
