### ISSUE TITLE
[Bug] 从订阅源获取到的proxy-groups, rules 丢失

### ISSUE THREAD

**Issue by BonderTam** [Dreamacro/clash#2814]
### 先决条件

- [X] 我了解这里是官方开源版 Clash 核心仓库，**只提供开源版或者 Premium 内核的支持**
- [X] 我要提交 Clash 核心的问题，并非 Clash.Meta / OpenClash / ClashX / Clash For Windows 或其他任何衍生版本的问题
- [X] 我使用的是**本仓库**最新版本的 Clash 或 Clash Premium 内核
- [X] 我已经在 [Issue Tracker](……/) 中找过我要提出的 bug，**并且没有找到相关问题**
- [X] 我已经仔细阅读 [官方 Wiki](https://dreamacro.github.io/clash/) 并无法自行解决问题
- [ ] （非 Premium 内核必填）我已经使用 dev 分支版本测试过，问题依旧存在

### 版本

v1.9.0

### 适用的作业系统

Linux, Windows

### 配置文件

```YAML
proxy-providers:
  bitznet:
    type: http
    url: http://host.docker.internal:3005/clashsub.yaml
    interval: 3600
    path: ./profiles/proxies/bitznet.yaml
    health-check:
      enable: true
      interval: 600
      url: http://www.gstatic.com/generate_204
```

### 日志输出

```Text
2023-06-28 17:06:59 time="2023-06-28T09:06:59Z" level=info msg="Start initial provider bitznet"
2023-06-28 17:06:59 time="2023-06-28T09:06:59Z" level=info msg="Mixed(http+socks) proxy listening at: [::]:7890"
2023-06-28 17:06:59 time="2023-06-28T09:06:59Z" level=error msg="Start DNS server error: missing port in address"
2023-06-28 17:06:59 time="2023-06-28T09:06:59Z" level=info msg="RESTful API listening at: [::]:7811"
```

### 问题描述

url: http://host.docker.internal:3005/clashsub.yaml
bitznet 提供的订阅源返回的是base64,  这里自己做了个代理，使得能得到完整的.yaml 配置， 部分配置截图如下:
![图片](https://github.com/Dreamacro/clash/assets/249648/a26bc67d-844c-4b21-bf5e-4023247cc5b9)

docker 容器正常启动，通过UI，或者API 都是只能获取到 proxy:
![图片](https://github.com/Dreamacro/clash/assets/249648/431a73eb-b59a-4caf-96c0-06168df9da3b)

rules 等信息丢失了。
访问www.google.com 后，clash 的日志是：
www.google.com:443 doesn't match any rule using DIRECT

纯小白，希望只是配置的问题， 望赐教。
