### ISSUE TITLE
请问，我想用来代理上网，应该怎么配置

### ISSUE THREAD

**Issue by snltty** [Dreamacro/clash#2815]
### 先决条件

- [X] 我了解这里是官方开源版 Clash 核心仓库，**只提供开源版或者 Premium 内核的支持**
- [X] 我要提交 Clash 核心的问题，并非 Clash.Meta / OpenClash / ClashX / Clash For Windows 或其他任何衍生版本的问题
- [X] 我使用的是**本仓库**最新版本的 Clash 或 Clash Premium 内核
- [X] 我已经在 [Issue Tracker](……/) 中找过我要提出的 bug，**并且没有找到相关问题**
- [X] 我已经仔细阅读 [官方 Wiki](https://dreamacro.github.io/clash/) 并无法自行解决问题
- [X] （非 Premium 内核必填）我已经使用 dev 分支版本测试过，问题依旧存在

### 版本

Clash 2023.05.29 windows amd64 with go1.20.4 Thu Jun  1 14:44:13 UTC 2023

### 适用的作业系统

Windows

### 适用的硬件架构

amd64

### 配置文件

```YAML
log-level: debug

mode: rule

proxies:
    #socks5
  - name: "socks"
    type: socks5
    server: 127.0.0.1
    port: 5413
    udp: true
    # username: username
    # password: password
    

    #http
  - name: "http"
    type: http
    server: 127.0.0.1
    port: 5413
    # username: username
    # password: password

rules:
  #- GEOIP,CN,DIRECT
  #- PROCESS-NAME,Google Chrome,socks5 #进程名
  #- PROCESS-PATH,C:\Program Files\Google\Chrome\Application\chrome.exe,socks5 #进程路径
  #- DOMAIN-SUFFIX,google.com,socks5 #域名后缀
  #- DOMAIN-KEYWORD,google,socks5 #域名关键字
  #- DOMAIN,google.com,socks5 #域名
  #- SRC-PORT,7777,DIRECT #源端口
  #- SRC-IP-CIDR,192.168.1.201/32,socks5 #源IP
  #- IP-CIDR,127.0.0.0/8,socks5 #目标ip
  #- DST-PORT,80,socks5 #目标端口
  #- GEOIP,CN,socks5

  - MATCH,socks
```

### 日志输出

```Text
只输出了 

[90m17:53:37[0m [32mINF[0m [API] listening [36maddr=[90m127.0.0.1:64980[0m
[90m17:53:37[0m [32mINF[0m [Inbound] Mixed(http+socks) listening [36maddr=[90m127.0.0.1:7890[0m
```

### 问题描述

我已经有一个socks5服务端，在 127.0.0.1:5413，我想使用clash去劫持流量达到代理上网的目的（比如，代理google chrome的所有流量，或者某些域名的流量），是否能实现呢

按照我发的那个配置信息去运行，没有任何反应，也没有日志输出

**Comment by lhbdhr** [comment]
https://www.youtube.com/playlist?list=PL5TbbtexT8T3d_7UX2aSFhoMYk-cl4kf4

节点搭建系列了解一下？

**Comment by snltty** [comment]
好的，我自己写有代理协议，自己有代理服务器 @lhbdhr

**Comment by lhbdhr** [comment]
刚注意到你说的已经有搭建好socks的服务器，推荐不要用这个。
用socks协议，属于明牌上网，你访问的域名什么的，都会被墙知道。
拿来访问谷歌，估计会被封

**Comment by snltty** [comment]
好吧，我用自己写的，半年了没被封

**Comment by lhbdhr** [comment]
自己写的socks？原来是大佬啊。

看日志输出第二行，监听了7890端口，
你是直接跑的内核？你不会是犯了低级错误，没有设置系统代理吧。用clash for window试试？

还有配置文件可以设置日志等级啊
log-level: debug

**Comment by snltty** [comment]
@lhbdhr 已经放弃了，已经开始自己写进程劫持代理了

**Comment by lupguo** [comment]
看配置都配的出口流量outbounds，可以考虑将Inbounds配置成http协议监听`127.0.0.1:5412`，outbounds协议用socks配置成`127.0.0.1:5413`（就是你原先的socks监听端口）P.S: 这里端口号要区分下，因为监听端口不能一样

1. inbounds部分，配置入流量
```
# Port of HTTP(S) proxy server on the local end
port: 5412
```

2. outbounds部分：配置你的本地socks监听地址
```
proxies:
    #socks5
  - name: "socks"
    type: socks5
    server: 127.0.0.1
    port: 5413
    udp: true
    # username: username
    # password: password
```

3. 日志可以通过访问` RESTful API listening at: 127.0.0.1:9090` API地址就可以
```
$ curl 127.0.0.1:9090/logs
```

4. 测试访问，可以看下出口IP信息
```
$ curl -x http://127.0.0.1:5412 ipinfo.io
```

流量劫持实际也是代理转发下，我理解就是 chrome -> [本地clash的http端口转发(入口流量) -> 本地clash socks出口流量 ]-> 远端socks的机器，这里就是多了一层转发
