### ISSUE TITLE
[Bug] <clash dns 只能运行在UDP6下>

### ISSUE THREAD

**Issue by shookgao** [Dreamacro/clash#2826]
### 先决条件

- [X] 我了解这里是官方开源版 Clash 核心仓库，**只提供开源版或者 Premium 内核的支持**
- [X] 我要提交 Clash 核心的问题，并非 Clash.Meta / OpenClash / ClashX / Clash For Windows 或其他任何衍生版本的问题
- [X] 我使用的是**本仓库**最新版本的 Clash 或 Clash Premium 内核
- [X] 我已经在 [Issue Tracker](……/) 中找过我要提出的 bug，**并且没有找到相关问题**
- [X] 我已经仔细阅读 [官方 Wiki](https://dreamacro.github.io/clash/) 并无法自行解决问题
- [ ] （非 Premium 内核必填）我已经使用 dev 分支版本测试过，问题依旧存在

### 版本

Clash 2023.06.30 linux amd64 with go1.20.5 Fri Jun 30 13:16:01 UTC 2023

### 适用的作业系统

Linux

### 适用的硬件架构

amd64

### 配置文件

```YAML
mixed-port: 7890
allow-lan: true
bind-address: '*'
mode: rule
log-level: info
dns:
  enable: true
  listen: 0.0.0.0:53
  default-nameserver:
    - 114.114.114.114
    - 8.8.8.8
  fake-ip-range: 198.18.0.1/16
  nameserver:
    - 114.114.114.114
    - 8.8.8.8 # default value
    - tls://dns.rubyfish.cn:853
    - https://1.1.1.1/dns-query
tun:
  enable: true
  stack: system
  auto-route: true
  auto-redir: true
  auto-detect-interface: true
```

### 日志输出

```Text
[warn] [TCP] dial failed error=dial tcp4 58.208.2.82:51413: connect: connection refused proxy=DIRECT lAddr=198.18.0.1:33993 rAddr=58.208.2.82:51413 rule=GeoIP rulePayload=CN
```

### 问题描述

clash部署在Debian服务器上，Debian版本如下：
