### ISSUE TITLE
[Bug] <clash dns 只能运行在UDP6下>

### ISSUE THREAD

**Issue by shookgao** [Dreamacro/clash#2827]
### 先决条件

- [X] 我了解这里是官方开源版 Clash 核心仓库，**只提供开源版或者 Premium 内核的支持**
- [X] 我要提交 Clash 核心的问题，并非 Clash.Meta / OpenClash / ClashX / Clash For Windows 或其他任何衍生版本的问题
- [X] 我使用的是**本仓库**最新版本的 Clash 或 Clash Premium 内核
- [X] 我已经在 [Issue Tracker](……/) 中找过我要提出的 bug，**并且没有找到相关问题**
- [X] 我已经仔细阅读 [官方 Wiki](https://dreamacro.github.io/clash/) 并无法自行解决问题
- [ ] （非 Premium 内核必填）我已经使用 dev 分支版本测试过，问题依旧存在

### 版本

Clash 2023.06.30 linux amd64 with go1.20.5 Fri Jun 30 13:16:01 UTC 2023

### 适用的作业系统

Linux

### 适用的硬件架构

amd64

### 配置文件

```YAML
mixed-port: 7890
allow-lan: true
bind-address: '*'
mode: rule
log-level: info
dns:
  enable: true
  listen: 0.0.0.0:53
  default-nameserver:
    - 114.114.114.114
    - 8.8.8.8
  fake-ip-range: 198.18.0.1/16
  nameserver:
    - 114.114.114.114
    - 8.8.8.8 # default value
    - tls://dns.rubyfish.cn:853
    - https://1.1.1.1/dns-query
tun:
  enable: true
  stack: system
  auto-route: true
  auto-redir: true
  auto-detect-interface: true
```

### 日志输出

```Text
[warn] [TCP] dial failed error=dial tcp4 58.208.2.82:51413: connect: connection refused proxy=DIRECT lAddr=198.18.0.1:33993 rAddr=58.208.2.82:51413 rule=GeoIP rulePayload=CN
```

### 问题描述

clash部署在Debian服务器上，Debian服务器做为主路由，版本如下：
`Linux myaio 5.10.0-23-amd64 #1 SMP Debian 5.10.179-1 (2023-05-12) x86_64 GNU/Linux`
clash启动成功后，能在其他电脑的浏览器中设置代理，能正常代理，但不能做为主路由的透明代理，查看端口占用发现只监听在UDP6下：
```
root@myaio:~/clash# lsof -i:53
COMMAND   PID USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
clash   29313 root   16u  IPv6 606696      0t0  UDP *:domain
root@myaio:~/clash# 
```
`ip rule` 命令下也有错误提示：
```
root@myaio:~/clash# ip rule
0:      from all lookup local
9500:   not from all dport 53 lookup main suppress_prefixlength 0
9510:   not from all iif lo lookup 1970566510
9520:   from 0.0.0.0 iif lo uidrange 0-4294967294 lookup 1970566510
9530:   from 198.18.0.1 iif lo uidrange 0-4294967294 lookup 1970566510
32766:  from all lookup main
32767:  from all lookup default
root@myaio:~/clash#
```
不清楚是怎么回事，期盼回复。
