### ISSUE TITLE
[Feature] 希望 TUN 能支持跨网段代理流量

### ISSUE THREAD

**Issue by daiyeqi** [Dreamacro/clash#2831]
### 先决条件

- [X] 我了解这里是 Clash 官方仓库，并非 Clash.Meta / OpenClash / ClashX / Clash For Windows 或其他任何衍生版本
- [X] 我已经在[这里](https://github.com/Dreamacro/clash/issues?q=is%3Aissue+label%3Aenhancement)找过我要提出的建议，**并且没有找到相关问题**
- [X] 我已经仔细阅读 [官方 Wiki](https://dreamacro.github.io/clash/) 

### 描述

尝试使用 Clash 的 Tun 功能，发现了几个问题，先简单描述下自己的网络情况
主路由是RouterOS
Clash 的虚拟机在 ether3 口，网关是192.168.87.1/24
客户机对应的交换机在 ether2 口，网关是 192.168.86.1/24
Clash 和 客户机两边网都是通的。

第一个问题是如果 Clash 启用了 eBPF Redirect to TUN 功能，客户机就无法连接上 Clash 虚拟机的 SSH，如果在同一网段没有问题。
```
interface-name: ens34 # conflict with `tun.auto-detect-interface`

routing-mark: 0x82

tun:
  enable: true
  stack: system # or gvisor
  # dns-hijack:
  #   - 8.8.8.8:53
  #   - tcp://8.8.8.8:53
  #   - any:53
  #   - tcp://any:53
  auto-route: false # manage `ip route` and `ip rules`
  auto-redir: false # manage nftable REDIRECT
  auto-detect-interface: false # conflict with `interface-name`

ebpf:
  redirect-to-tun:
    - ens34
```
第二个问题，如果仅启用 TUN 功能
```
interface-name: ens34

tun:
  enable: true
  stack: system # or gvisor
  # dns-hijack:
  #   - 8.8.8.8:53
  #   - tcp://8.8.8.8:53
  #   - any:53
  #   - tcp://any:53
  auto-route: true # manage `ip route` and `ip rules`
  auto-redir: true # manage nftable REDIRECT
  auto-detect-interface: false # conflict with `interface-name`
```
如果 Clash 和 客户机不在一个网段，就无法正常代理。同一网段的话，流量正常能发送过去。

### 可能的解决方案

是否可以在 TUN 这里增加一个配置，允许转发的 IP，如：192.168.86.0/23
