### ISSUE TITLE
[Help] It doesn't do anything.

### ISSUE THREAD

**Issue by pegasusearl** [Dreamacro/clash#2834]
### Prerequisites

- [X] I understand that this is the official open-source version of the Clash core, **only providing support for the open-source version or Premium version**
- [X] I am submitting an issue with the Clash core, not Clash.Meta / OpenClash / ClashX / Clash For Windows or any other derivative version
- [X] I am using the latest version of the Clash or Clash Premium core **in this repository**
- [X] I have searched at the [Issue Tracker](……/) **and have not found any related issues**
- [X] I have read the [official Wiki](https://dreamacro.github.io/clash/) **and was unable to solve the issue**
- [ ] (required for Premium core) I've tried the `dev` branch and the issue still exists

### Version

Clash 1.16.0 linux amd64 with go1.20.4 unknown time

### Operating System

Linux

### Architecture

amd64

### Configuration File

```YAML
# Port of HTTP(S) proxy server on the local end
port: 7890

# Port of SOCKS5 proxy server on the local end
socks-port: 7891

# Transparent proxy server port for Linux and macOS (Redirect TCP and TProxy UDP)
# redir-port: 7892

# Transparent proxy server port for Linux (TProxy TCP and TProxy UDP)
# tproxy-port: 7893

# HTTP(S) and SOCKS4(A)/SOCKS5 server on the same port
# mixed-port: 7890

# authentication of local SOCKS5/HTTP(S) server
# authentication:
#  - "user1:pass1"
#  - "user2:pass2"

# Set to true to allow connections to the local-end server from
# other LAN IP addresses
# allow-lan: false

# This is only applicable when `allow-lan` is `true`
# '*': bind all IP addresses
# 192.168.122.11: bind a single IPv4 address
# "[aaaa::a8aa:ff:fe09:57d8]": bind a single IPv6 address
# bind-address: '*'

# Clash router working mode
# rule: rule-based packet routing
# global: all packets will be forwarded to a single endpoint
# direct: directly forward the packets to the Internet
mode: rule

# Clash by default prints logs to STDOUT
# info / warning / error / debug / silent
log-level: debug

# When set to false, resolver won't translate hostnames to IPv6 addresses
# ipv6: false

# RESTful web API listening address
external-controller: 127.0.0.1:9090

# A relative path to the configuration directory or an absolute path to a
# directory in which you put some static web resource. Clash core will then
# serve it at `http://{{external-controller}}/ui`.
# external-ui: folder

# Secret for the RESTful API (optional)
# Authenticate by spedifying HTTP header `Authorization: Bearer ${secret}`
# ALWAYS set a secret if RESTful API is listening on 0.0.0.0
secret: "123456"

# Outbound interface name
# interface-name: en0

# fwmark on Linux only
# routing-mark: 6666

# Static hosts for DNS server and connection establishment (like /etc/hosts)
#
# Wildcard hostnames are supported (e.g. *.clash.dev, *.foo.*.example.com)
# Non-wildcard domain names have a higher priority than wildcard domain names
# e.g. foo.example.com > *.example.com > .example.com
# P.S. +.foo.com equals to .foo.com and foo.com
# hosts:
  # '*.clash.dev': 127.0.0.1
  # '.dev': 127.0.0.1
  # 'alpha.clash.dev': '::1'


# DNS server settings
# This section is optional. When not present, the DNS server will be disabled.
dns:
  enable: false
  listen: 0.0.0.0:53
  default-nameserver:
    - 114.114.114.114
    - 8.8.8.8
  # enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16 # Fake IP addresses pool CIDR
  nameserver:
    - 114.114.114.114 # default value
    - 8.8.8.8 # default value
    - tls://dns.rubyfish.cn:853 # DNS over TLS
    - https://1.1.1.1/dns-query # DNS over HTTPS
    - dhcp://en0 # dns from dhcp
    # - '8.8.8.8#en0'


proxies:
  - name: trojan-ws
    server: server
    port: 443
    type: trojan
    password: "example"
    network: ws
    sni: example.com
    # skip-cert-verify: true
    udp: true
    # ws-opts:
      # path: /path
      # headers:
      #   Host: example.com

proxy-groups:
  # select is used for selecting proxy or proxy group
  # you can use RESTful API to switch proxy is recommended for use in GUI.
  - name: Proxy
    type: select
    # disable-udp: true
    # filter: 'someregex'
    proxies:
      - trojan-ws


rules:
  - DOMAIN-SUFFIX,reddit.com,Proxy
  - DOMAIN-SUFFIX,newgrounds.com,Proxy
  - SRC-IP-CIDR,192.168.1.201/32,DIRECT
  - IP-CIDR,127.0.0.0/8,DIRECT
  - MATCH,DIRECT
```

### Log

```Text
clash                                                                                                                                                                   INT ✘ 
INFO[0000] Start initial compatible provider Proxy      
INFO[0000] HTTP proxy listening at: 127.0.0.1:7890      
INFO[0000] SOCKS proxy listening at: 127.0.0.1:7891     
INFO[0000] RESTful API listening at: 127.0.0.1:9090
```

### Description

Hello, I'm trying to use clash on desktop PC. But it doesn't do anything.
Using yacd I can see the proxies, proxy group, rules, etc however in the "Conns" section is completely empty even when I'm accessing internet.

What might be the problem?

Sorry if this is the wrong place to ask for help. I didn't find any other community section.

![Screenshot_20230713_212522](https://github.com/Dreamacro/clash/assets/23167087/8f9da2cf-e5b5-4524-8306-18f339dbcee5)
![Screenshot_20230713_212536](https://github.com/Dreamacro/clash/assets/23167087/9c289884-b6bb-42ed-99dc-52c54b465d80)
![Screenshot_20230713_212547](https://github.com/Dreamacro/clash/assets/23167087/9db6cc59-3e02-47a3-9f7d-ab0a2add3563)

**Comment by techblack** [comment]
u need set system proxy or  broswer proxy

**Comment by pegasusearl** [comment]
> u need set system proxy or broswer proxy

Is it like this?
![Screenshot_20230717_151354](https://github.com/Dreamacro/clash/assets/23167087/9d0900b5-5253-47f6-a08d-515642ce878a)
It still doesn't do anything. So then I tried to set browser proxy.

![Screenshot_20230717_151533](https://github.com/Dreamacro/clash/assets/23167087/54595e95-11bd-4607-af4d-171eed3902f9)
Is it like this? With this, firefox will instead says, `The proxy server is refusing connections`.

Clash is running, there is also no output.

```
clash                                                                                                                                                                       ✔ 
INFO[0000] Start initial compatible provider Proxy      
INFO[0000] RESTful API listening at: 127.0.0.1:9090     
INFO[0000] HTTP proxy listening at: 127.0.0.1:7890      
INFO[0000] SOCKS proxy listening at: 127.0.0.1:7891
```

**Comment by techblack** [comment]
simplely try (need root or net_admin !!!!!):
```
tun:
  enable: true
  stack: gvisor
  auto-route: true
  auto-detect-interface: true
  dns-hijack:
    - any:53
```

u set proxy maybe notwork for your browser or  u are using quic?
