### ISSUE TITLE
[Bug] Clash DNS doesn't comply to 'interface-name' specific in proxy-groups

### ISSUE THREAD

**Issue by ingjieye** [Dreamacro/clash#2839]
### Prerequisites

- [X] I understand that this is the official open-source version of the Clash core, **only providing support for the open-source version or Premium version**
- [X] I have looked for my idea in [the issue tracker](https://github.com/Dreamacro/clash/issues?q=is%3Aissue+label%3Aenhancement), **and found none of which being related**
- [X] I have read the [official Wiki](https://dreamacro.github.io/clash/)

### Description

For example, I've setup a ppp device in `/dev/ppp0`
Currently, I'll need `danted` to convert this device to socks5, so that Clash can route traffic to it:
```
internal: eth0 port = 1080
external: ppp0
client pass {
    from: 0.0.0.0/0 to: 0.0.0.0/0
}
```

Is that possible for Clash to directly use the network interface as outbound so that I can specify which traffic should go to with this interface? 
Example configuration:
```yaml
proxies: 
- { name: 'ppp', type: network_interface, device: "/dev/ppp0"}
```

**Comment by ingjieye** [comment]
Seems the `proxy-groups` can specify which interface to use
```yaml
proxy-groups:
  - { name: OpenFortiClient, type: select, interface-name: ppp0, proxies: [DIRECT]}
```
However, the clash DNS as well as `nameserver-policy` doesn't comply with "interface-name" and still goes with the default interface.

For example, consider the following configurations:
```yaml
dns:
  enable: true
  nameserver: 
    - PUBLIC_NS
  nameserver-policy:
    - '+.internal.company.com': 'INTERNAL_NS'
proxy-groups:
  - { name: OpenFortiClient, type: select, interface-name: ppp0, proxies: [DIRECT]}
rules:
  - DOMAIN-SUFFIX,internal.company.com,OpenFortiClient
  - DOMAIN-SUFFIX,public.company.com,OpenFortiClient
```
Currently, all DNS traffic goes to PUBLIC_NS and INTERNAL_NS directly (with default network interface) when accessing both `internal.company.com` and `public.company.com`, instead of going through `ppp0` as specific in `proxy-groups`

**Comment by Dreamacro** [comment]
dns support custom interface

```yaml
dns:
  enable: true
  nameserver: 
    - PUBLIC_NS
  nameserver-policy:
    - '+.internal.company.com': udp://INTERNAL_NS#ppp0
proxy-groups:
  - { name: OpenFortiClient, type: select, interface-name: ppp0, proxies: [DIRECT]}
rules:
  - DOMAIN-SUFFIX,internal.company.com,OpenFortiClient
  - DOMAIN-SUFFIX,public.company.com,OpenFortiClient
```

DIRECT is special because all local dns requests are managed in the dns field, rather than each proxy having its own dns
 config
