### ISSUE TITLE
TUN 模式下，auto-route 为 true 则无法联网

### ISSUE THREAD

**Issue by domeniczz** [Dreamacro/clash#2844]
### 先决条件

- [X] 我了解这里是官方开源版 Clash 核心仓库，**只提供开源版或者 Premium 内核的支持**
- [X] 我要提交 Clash 核心的问题，并非 Clash.Meta / OpenClash / ClashX / Clash For Windows 或其他任何衍生版本的问题
- [X] 我使用的是**本仓库**最新版本的 Clash 或 Clash Premium 内核
- [X] 我已经在 [Issue Tracker](……/) 中找过我要提出的 bug，**并且没有找到相关问题**
- [X] 我已经仔细阅读 [官方 Wiki](https://dreamacro.github.io/clash/) 并无法自行解决问题
- [X] （非 Premium 内核必填）我已经使用 dev 分支版本测试过，问题依旧存在

### 版本

2023.06.30-3-g24a3047 Premium (56010)

### 适用的作业系统

Windows

### 适用的硬件架构

amd64

### 配置文件

```YAML
mixin:
  dns:
    enable: true
    enhanced-mode: fake-ip
    ipv6: false
    listen: 0.0.0.0:1053
    fake-ip-range: 198.18.0.1/16
    default-nameserver:
      - 114.114.114.114
      - 223.5.5.5
      - 8.8.8.8
      - 1.1.1.1
      - 180.76.76.76
      - 119.29.29.29
    nameserver:
      - https://1.1.1.1/dns-query
      - https://223.5.5.5/dns-query
      - https://doh.pub/dns-query
      - https://dns.alidns.com/dns-query
    fallback:
      - https://1.1.1.1/dns-query
      - https://doh.dns.sb/dns-query
      - tls://8.8.8.8:853
      - 114.114.114.114
      - tls://1.1.1.1:853
      - tls://1.0.0.1:853
      - 101.6.6.6:5353
    fake-ip-filter:
      - +.stun.*.*
      - +.stun.*.*.*
      - +.stun.*.*.*.*
      - +.stun.*.*.*.*.*
      - "*.n.n.srv.nintendo.net"
      - +.stun.playstation.net
      - xbox.*.*.microsoft.com
      - "*.*.xboxlive.com"
      - "*.msftncsi.com"
      - "*.msftconnecttest.com"
      - WORKGROUP
    nameserver-policy:
      "www.msftconnecttest.com": "223.5.5.5"
      "dns.msftncsi.com": "223.5.5.5"
      "www.msftncsi.com": "223.5.5.5"
  tun:
    enable: true
    stack: system
    auto-route: false
    auto-detect-interface: true
    dns-hijack:
      - any:53
```

### 问题描述

TUN 模式下，若 auto-route 为 true 就不能上网，改为 false 就可以

现在 clash 显示 no internet access (我连着 WIFI，WIFI 是 internet access），但是使用一切正常，microsoft store 可以正常登录

![image](https://github.com/Dreamacro/clash/assets/42294390/0dafd290-d161-460c-9e3e-b7e3ed03e103)
![image](https://github.com/Dreamacro/clash/assets/42294390/ac3ec160-8c3b-4706-b2d4-1e6ed9d35ce2)

### 复现步骤

使用 Clash For Windows，打开 TUN 模式和 Mixin，将配置文件贴入 Mixin 中，重启软件
