### ISSUE TITLE
[Feature] 请求加入下游的实用功能

### ISSUE THREAD

**Issue by ghost** [Dreamacro/clash#2848]
### 先决条件

- [X] 我了解这里是 Clash 官方仓库，并非 Clash.Meta / OpenClash / ClashX / Clash For Windows 或其他任何衍生版本
- [X] 我已经在[这里](https://github.com/Dreamacro/clash/issues?q=is%3Aissue+label%3Aenhancement)找过我要提出的建议，**并且没有找到相关问题**
- [X] 我已经仔细阅读 [官方 Wiki](https://dreamacro.github.io/clash/) 

### 描述

发现 Clash.Meta 有几个实用的功能，不知道是否可以和他们商量一下。

1、 url-test 可以手动选择
https://github.com/MetaCubeX/Clash.Meta/commit/2c09ce44f6a439524fcc97a66ea24dd92a17d3cb
解释一下就是 Clash.Meta 中仅需使用一个 `url-test`  就可以实现原版 clash 中需要
```
  - name: PROXY
    type: select
    # disable-udp: true
    # filter: 'someregex'
    proxies:
      - fallback
      - select
      - url-test

  - name: fallback
    type: fallback
    proxies:
      - select
      - url-test
    url: 'http://www.gstatic.com/generate_204'
    interval: 300

  - name: select
    type: select
    # disable-udp: true
    # filter: 'someregex'
    proxies:
      - ss1
      - ss2
      - vmess1

  - name: url-test
    type: url-test
    proxies:
      - ss1
      - ss2
      - vmess1
    # tolerance: 150
    # lazy: true
    url: 'http://www.gstatic.com/generate_204'
    interval: 300
```
就可以实现原版clash中需要 `fallback` `select` `url-test` 三项功能四个分组配合起来的功能，

大致使用背景

日常用某个节点看NF倍率低又快又稳定（select）
但这个节点失联的时候，可以自动切换到另一个（fallback）
另一个节点也是能保证访问（url-test）
节点有时还需要它不被 fallback 干扰（PROXY）

这只是看一个nf就设了四个分组，如果再搞一个emby的、一个openai的......
而有了这个功能一个分组就能搞定，所以 url-test 可以手动选择是一个很实用的功能。

---
2、 GeoSite 加载
根据 https://github.com/v2fly/domain-list-community/tree/master/data
[https://github.com/MetaCubeX/Clash.Meta/commit/900e85252529ee67ac396af8417664de5aa60639](https://github.com/MetaCubeX/Clash.Meta/blob/900e85252529ee67ac396af8417664de5aa60639/rule/geosite.go)
```
rules:
  - GEOSITE,geolocation-!cn,PROXY
  - GEOSITE,cn,DIRECT
  - MATCH,PROXY
```
约等于 Clash Premium 内核的
```
rule-providers:
  proxy:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/proxy.txt"
    path: ./ruleset/proxy.yaml
    interval: 86400
  direct:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/direct.txt"
    path: ./ruleset/direct.yaml
    interval: 86400
rules:
  - RULE-SET,proxy,PROXY
  - RULE-SET,direct,DIRECT
  - MATCH,PROXY
```
非 Premium 内核就更麻烦了，基本只能依靠订阅转换。可见使用 GeoSite 要简洁的多，同时 GeoSite 还有许多别处没搜集到的域名分类。

能和那边商量下加过来吗？
