### ISSUE TITLE
[Bug] 5.29之后的p核版本udp流量异常

### ISSUE THREAD

**Issue by Hidarihitomi** [Dreamacro/clash#2855]
### 先决条件

- [X] 我了解这里是官方开源版 Clash 核心仓库，**只提供开源版或者 Premium 内核的支持**
- [X] 我要提交 Clash 核心的问题，并非 Clash.Meta / OpenClash / ClashX / Clash For Windows 或其他任何衍生版本的问题
- [X] 我使用的是**本仓库**最新版本的 Clash 或 Clash Premium 内核
- [X] 我已经在 [Issue Tracker](……/) 中找过我要提出的 bug，**并且没有找到相关问题**
- [X] 我已经仔细阅读 [官方 Wiki](https://dreamacro.github.io/clash/) 并无法自行解决问题
- [ ] （非 Premium 内核必填）我已经使用 dev 分支版本测试过，问题依旧存在

### 版本

Clash 2023.07.22-4-ge74b0af linux arm64 with go1.20.6 Mon Jul 31 02:35:52 PM UTC 2023

### 适用的作业系统

Android

### 适用的硬件架构

arm64

### 配置文件

```YAML
tun:
    enable: true
    stack: system
    dns-hijack:
        - any:53
    auto-route: true
    auto-detect-interface: true
dns:
    enable: true
    ipv6: true
    enhanced-mode: fake-ip
    fake-ip-range: 28.0.0.0/8
    fake-ip-filter:
        - '.lan'
        - +.local
        - localhost.ptlogin2.qq.com
    fallback-filter:
      geoip: false
      ipcidr:
        - 0.0.0.0/32
    listen: 0.0.0.0:53
    nameserver:
        - 223.5.5.5
        - 119.29.29.29
    fallback:
        - https://doh.pub/dns-query

script:
    engine: expr
    shortcuts:
      FCM: network == 'tcp' and dst_port > 5227 and dst_port < 5231
  - DOMAIN-SUFFIX,bard.google.com,TW
  - SCRIPT,FCM,DIRECT,no-resolve
  - IP-CIDR,127.0.0.0/8,DIRECT
  - GEOIP,LAN,DIRECT
  - GEOIP,CN,DIRECT
  - MATCH,Proxy
```

### 问题描述

一直在安卓设备上运行linux版p核(tun+自动路由)，5.29之后的版本突然出现游戏中出现类似断流情况，间歇性断网一秒钟后恢复正常，日志开启debug后没找到异常报错。尝试过设置为全局直连，依旧出现上述类似断流情况。
