### ISSUE TITLE
Specify TLS server name in configuration

### ISSUE THREAD

**Issue by amphineko** [Dreamacro/clash#286]
Configurations should be able to specify server name for Vmess TLS-enabled servers.

In case of a server having multiple TLS certificates configured, the SNI server name should be specified for the server to distinguish.

For example, a server located at `1.2.3.4` servers `example.com` and `example.net` without DNS records.  
In this case, we cannot simply put `1.2.3.4` as the server address: the server may reject the connection since we didn't specify `example.com` or `example.net` as SNI server name. The server has no way to know which certificates to use for decryption.

**Comment by amphineko** [comment]
For the case above, an example configuration should be like this:

```
Proxy:
  - name: example-com
    type: vmess

    server: 1.2.3.4
    port: 443
    uuid: 00000000-0000-0000-0000-114514191981
    alterId: 32
    cipher: none
    
    tls: true
    tls-hostname: example.com  # for TLS SNI

    network: ws
    ws-headers:
      Host: example.com  # for reverse proxy
    ws-path: /stream
```

**Comment by Dreamacro** [comment]
```yml
Proxy:
  - name: example-com
    type: vmess

    server: 1.2.3.4
    port: 443
    uuid: 00000000-0000-0000-0000-114514191981
    alterId: 32
    cipher: none
    
    tls: true
    tls-hostname: example.com  # for TLS SNI

    network: ws
    ws-headers:
      Host: example.com  # for reverse proxy
    ws-path: /stream
```

in `dev` branch, SNI is ws-headers Host
