### ISSUE TITLE
[Bug] [macOS] auto redir start failed error=unsupported

### ISSUE THREAD

**Issue by Meowzz95** [Dreamacro/clash#2871]
### Prerequisites

- [X] I understand that this is the official open-source version of the Clash core, **only providing support for the open-source version or Premium version**
- [X] I am submitting an issue with the Clash core, not Clash.Meta / OpenClash / ClashX / Clash For Windows or any other derivative version
- [X] I am using the latest version of the Clash or Clash Premium core **in this repository**
- [X] I have searched at the [Issue Tracker](……/) **and have not found any related issues**
- [X] I have read the [official Wiki](https://dreamacro.github.io/clash/) **and was unable to solve the issue**
- [ ] (required for Premium core) I've tried the `dev` branch and the issue still exists

### Version

Clash 2023.07.22 darwin arm64 with go1.20.6 Sat Jul 22 09:42:37 UTC 2023

### Operating System

macOS (darwin)

### Architecture

arm64

### Configuration File

```YAML
interface-name: en0
tun:
  enable: true
  stack: system
  dns-hijack:
    - any:53

  auto-route: true
  auto-redir: true

dns:
  enable: true
  listen: 0.0.0.0:53
  default-nameserver:
    - 8.8.8.8
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16

  fake-ip-filter:
    - 'xxxxxx.xxxx.xxxxx'
  nameserver:
    - https://dns.google/dns-query
```

### Log

```Text
16:26:25 INF [API] listening addr=127.0.0.1:9099
16:26:25 INF [DNS] server listening addr=[::]:53
16:26:25 INF [Inbound] HTTP proxy listening addr=127.0.0.1:7890
16:26:25 INF [Inbound] SOCKS proxy listening addr=127.0.0.1:7891
16:26:25 WRN [TUN] auto redir start failed error=unsupported
16:26:25 INF [Inbound] TUN listening iface=utun9 gateway=198.18.0.1
```

### Description

I've searched Google and the issue tracker and only found very old issues related to this, I'm using tun mode, macOS with ARM chip, and this is always reproducible, it doesn't seem to break anything but I think there must be something wrong since the doc says that this feature is supported in macOS.

> tun.auto-route and tun.auto-redir are only available on macOS, Windows, Linux and Android, and only receives IPv4 traffic.

### Reproduction Steps

run `sudo ./clash -d .` with the above config(non-related sections removed)

observe the log

`WRN [TUN] auto redir start failed error=unsupported` is logged to the console

However, nothing seems to be broken...
