### ISSUE TITLE
[Bug] <问题标题>无法导入v2ray节点订阅，转换成clash也无法导入

### ISSUE THREAD

**Issue by lilei121** [Dreamacro/clash#2880]
### 先决条件

- [X] 我了解这里是官方开源版 Clash 核心仓库，**只提供开源版或者 Premium 内核的支持**
- [X] 我要提交 Clash 核心的问题，并非 Clash.Meta / OpenClash / ClashX / Clash For Windows 或其他任何衍生版本的问题
- [X] 我使用的是**本仓库**最新版本的 Clash 或 Clash Premium 内核
- [X] 我已经在 [Issue Tracker](……/) 中找过我要提出的 bug，**并且没有找到相关问题**
- [X] 我已经仔细阅读 [官方 Wiki](https://dreamacro.github.io/clash/) 并无法自行解决问题
- [ ] （非 Premium 内核必填）我已经使用 dev 分支版本测试过，问题依旧存在

### 版本

0.20.31

### 适用的作业系统

macOS (darwin)

### 适用的硬件架构

arm64

### 配置文件

```YAML
port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- {name: dy.dudung.link-HTTPS-cdn.anycast.eu.org-EDtunnel 6, server: cdn.anycast.eu.org, port: 2083, client-fingerprint: random, type: vless, uuid: 4e0bfff6-1cfb-4c91-9d9c-e7b2005e70dc, tls: true, tfo: false, servername: dy.dudung.link, skip-cert-verify: true, network: ws, ws-opts: {path: "/?ed=2048", headers: {Host: dy.dudung.link}}, udp: true}
proxy-groups:
- name: 🔰 节点选择
    type: select
    proxies:
      - ♻️ 自动选择
      - 🎯 全球直连
      - dy.dudung.link-HTTP
```

### 问题描述

<img width="372" alt="image" src="https://github.com/Dreamacro/clash/assets/91684197/5fc5ddea-f82c-4618-a1e3-f814f422bc71">
