### ISSUE TITLE
[Bug] <DNS拦截成功但是不能看到log>

### ISSUE THREAD

**Issue by sususu98** [Dreamacro/clash#2894]
### 先决条件

- [X] 我了解这里是官方开源版 Clash 核心仓库，**只提供开源版或者 Premium 内核的支持**
- [X] 我要提交 Clash 核心的问题，并非 Clash.Meta / OpenClash / ClashX / Clash For Windows 或其他任何衍生版本的问题
- [X] 我使用的是**本仓库**最新版本的 Clash 或 Clash Premium 内核
- [X] 我已经在 [Issue Tracker](……/) 中找过我要提出的 bug，**并且没有找到相关问题**
- [X] 我已经仔细阅读 [官方 Wiki](https://dreamacro.github.io/clash/) 并无法自行解决问题
- [ ] （非 Premium 内核必填）我已经使用 dev 分支版本测试过，问题依旧存在

### 版本

Clash 2023.08.17 windows amd64 with go1.21.0 Thu Aug 17 03:08:46 PM UTC 2023

### 适用的作业系统

Windows

### 适用的硬件架构

amd64

### 配置文件

```YAML
mixed-port: 7890
allow-lan: true
mode: Rule
log-level: debug
dns:
  enable: true
  ipv6: true
  listen: 0.0.0.0:1053
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  default-nameserver:
    - 192.168.1.1
  nameserver:
    - 192.168.1.1
  fallback:
    - tls://dns.google
    - tls://one.one.one.one
    - https://doh.dns.sb/dns-query
  fake-ip-filter:
    - "*.sususu.cf"
    - "*.sufq.cf"
    - "*.ip.sb"
    - "*.fastweb.it"
    - +.bitpt.cn
    - +.dot.pub
proxies:
  - name: jp1
    server: 192.168.x.x
    port: xxxx
    type: socks5
    udp: true
proxy-groups:
  - name: 节点选择
    type: select
    proxies:
      - jp1
rules:
  - DOMAIN-KEYWORD,byr,节点选择
tun:
  enable: true
  stack: gvisor
  auto-route: true
  auto-detect-interface: true
  dns-hijack:
    - any:53
```

### 日志输出

```Text
[2023-08-21 10:20:01][DEBUG] [TUN] hijack udp dns addr=198.18.0.2:53
[2023-08-21 10:20:01][DEBUG] [TUN] hijack udp dns addr=198.18.0.2:53
[2023-08-21 10:20:01][DEBUG] [TUN] hijack udp dns addr=198.18.0.2:53
[2023-08-21 10:20:03][DEBUG] [TUN] hijack udp dns addr=198.18.0.2:53
```

### 问题描述

在tun模式下访问北邮人（byr.pt)教育网ipv6的PT站的时候显示本地的ipv6地址，并显示我的地址无法访问。
我尝试查看log，完全看不到byr相关的日志显示...

![image](https://github.com/Dreamacro/clash/assets/33882693/91819087-0c97-4873-97c8-0bbcddd54d60)

如果我在没有ipv6的环境中使用相同的配置，是可以访问北邮人的。或者我使用socks5代理的方式也是能够访问的。

*我最疑惑的点是我现在只能看到hijack udp dns，但是看不到详细的日志。。。*
