### ISSUE TITLE
[Bug] 把clash设置成透明网关后其他网关指向此机器会出现无法访问

### ISSUE THREAD

**Issue by MrLiuGangQiang** [Dreamacro/clash#2914]
### 先决条件

- [X] 我了解这里是官方开源版 Clash 核心仓库，**只提供开源版或者 Premium 内核的支持**
- [X] 我要提交 Clash 核心的问题，并非 Clash.Meta / OpenClash / ClashX / Clash For Windows 或其他任何衍生版本的问题
- [X] 我使用的是**本仓库**最新版本的 Clash 或 Clash Premium 内核
- [X] 我已经在 [Issue Tracker](……/) 中找过我要提出的 bug，**并且没有找到相关问题**
- [X] 我已经仔细阅读 [官方 Wiki](https://dreamacro.github.io/clash/) 并无法自行解决问题
- [ ] （非 Premium 内核必填）我已经使用 dev 分支版本测试过，问题依旧存在

### 版本

Clash 2023.08.17 linux amd64 with go1.21.0 Thu Aug 17 15:07:25 UTC 2023

### 适用的作业系统

Linux

### 适用的硬件架构

amd64

### 配置文件

```YAML
port: 7890
socks-port: 7891
redir-port: 7892
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
external-ui: /opt/clash-dashboard
dns:
  enable: true
  listen: 0.0.0.0:53
  enhanced-mode: fake-ip
  nameserver:
    - 114.114.114.114
  fallback:
    - 8.8.8.8
tun:
  enable: true
  stack: system
  auto-route: true
  auto-detect-interface: true 
  dns-hijack:
    - any:53
    - tcp://any:53
```

### 日志输出

```Text
x
```

### 问题描述

我在Debian服务上已正确安装Clash并设置成透明网关模式，服务器也已经打开端口转发，内网的其他机器把网关设置为此服务器IP可以正确访问谷歌和其他网站，但是现在发现只要把网关设置为此服务器IP的机器通过端口映射的服务就无法访问，猜测应该是还有些啥规则没设置，大佬们给点指导。
