### ISSUE TITLE
[Bug] Clash DNS 请求没打mark吗？

### ISSUE THREAD

**Issue by Student414** [Dreamacro/clash#2918]
### Prerequisites

- [X] I understand that this is the official open-source version of the Clash core, **only providing support for the open-source version or Premium version**
- [X] I am submitting an issue with the Clash core, not Clash.Meta / OpenClash / ClashX / Clash For Windows or any other derivative version
- [X] I am using the latest version of the Clash or Clash Premium core **in this repository**
- [X] I have searched at the [Issue Tracker](……/) **and have not found any related issues**
- [X] I have read the [official Wiki](https://dreamacro.github.io/clash/) **and was unable to solve the issue**
- [X] (required for Premium core) I've tried the `dev` branch and the issue still exists

### Version

latest

### Operating System

Linux

### Architecture

amd64, amd64-v3, arm64

### Configuration File

```YAML
# HTTP 代理端口
port: 7890

# SOCKS5 代理端口
socks-port: 7891

# Linux 和 macOS 的 redir 代理端口
redir-port: 7892

# Transparent proxy server port for Linux (TProxy TCP and TProxy UDP)
tproxy-port: 7893

routing-mark: 9011

# 允许局域网的连接
allow-lan: true

# 规则模式：Rule（规则） / Global（全局代理）/ Direct（全局直连）
mode: rule
script:
  code: |
    def main(ctx, metadata):
      ctx.log('[Script] Start matcheing')
      ip = metadata["src_ip"]

      # 无法获取源IP，不再进行后续匹配，直接直连
      if ip == "":
        return "DIRECT"

      # 白名单模式，列举出的IP走Clash分流，不在列表中的IP直连
      whitelist = [
        "192.168.88.88",
        "192.168.88.89",
        "192.168.88.90",
        "10.42.0.201",
      ]
      if ip not in whitelist:
        # 源IP不在白名单列表内，直接直连
        return "DIRECT"

      # 以下是源IP不在百名带列表内的逻辑
      # 匹配ACL4SSR的providers
      list = {
        "ACL4SSR-LocalAreaNetwork": "DIRECT",
        "ACL4SSR-BanAD": "ACL4SSR-BanAD",
        "ACL4SSR-BanEasyList": "ACL4SSR-BanEasyList",
        "ACL4SSR-BanEasyPrivacy": "ACL4SSR-BanEasyPrivacy",
        "ACL4SSR-ProxyGFWlist": "ACL4SSR-ProxyGFWlist",
        "ACL4SSR-ProxyMedia": "ACL4SSR-ProxyMedia",
        "ACL4SSR-ChinaMedia": "ACL4SSR-ChinaMedia",
        "ACL4SSR-ChinaDomain": "Domestic",
        "ACL4SSR-ChinaIp": "Domestic",
        "ACL4SSR-ChinaCompanyIp": "Domestic",
      }
      for key in list:
        if ctx.rule_providers[key].match(metadata):
          ctx.log('[Script] matched %s' % key)
          return list[key]

      # 这里添加一些其他的匹配逻辑，一般不用

      # 匹配geoip
      code = ctx.geoip(ip)
      if code == "LAN" or code == "CN":
        return "DIRECT"

      # 白名单之外的IP，如果匹配不到，默认走代理
      return "Proxy"

# 设置日志输出级别 (默认级别：silent，即不输出任何内容，以避免因日志内容过大而导致程序内存溢出）。
# 5 个级别：silent / info / warning / error / debug。级别越高日志输出量越大，越倾向于调试，若需要请自行开启。
log-level: warning
# Clash 的 RESTful API
external-controller: "0.0.0.0:9099"

# RESTful API 的口令
secret: ""

# 您可以将静态网页资源（如 clash-dashboard）放置在一个目录中，clash 将会服务于 `RESTful API/ui`
# 参数应填写配置目录的相对路径或绝对路径。
# external-ui: ui

ipv6: true

dns:
  enable: true
  ipv6: true
  listen: ':1053'
  enhanced-mode: fake-ip # or fake-ip
  fake-ip-range: 198.18.0.1/16
  nameserver:
    - 127.0.0.53
    - 119.29.29.29
    - 223.5.5.5
    - 156.154.70.1
    - 1.0.0.1
  fallback:
    - 208.67.222.222:5353
    - 208.67.220.220:5353
    - 208.67.222.220:5353
    - 208.67.220.222:5353
    - https://1.1.1.1/dns-query
    - https://1.1.1.2/dns-query
    - https://1.1.1.3/dns-query
    - https://1.0.0.1/dns-query
    - https://1.0.0.2/dns-query
    - https://1.0.0.3/dns-query
    - https://45.11.45.11/dns-query
    - https://146.112.41.2/dns-query
    - https://162.159.36.1/dns-query
    - https://162.159.46.1/dns-query
    - https://9.9.9.11:5053/dns-query
    - https://101.6.6.6:8443/dns-query
    - https://208.67.222.222/dns-query
    - https://208.67.220.220/dns-query
    - https://185.222.222.222/dns-query
    - https://101.101.101.101/dns-query
    - https://149.112.112.11:5053/dns-query
  fallback-filter:
    geoip: true
    ipcidr:
      - 240.0.0.0/4
```

### Description

因为在Clash中用到了DoT和DoH处理DNS污染，发现这些DoH请求会回发到Clash（因为我用iptables拦截了所有未打mark的DNS请求），获取到192.18.0.0/16的fake-ip。我已在iptables中过滤了所有带mark的包，保证不会重复发往clash,但是clash的dns端口仍能收到clash自己发来DoH查询请求，所以怀疑DNS出流量没打mark，不知道作者是出于什么原因不对DNS流量打mark，还请大佬解释:)

附iptables dns拦截部分：
```
if $enable_dns; then
        iptables -t nat -N TPROXY_DNS_EXTERNAL
        iptables -t nat -A TPROXY_DNS_EXTERNAL -p udp ! --dport 53 -j RETURN
        iptables -t nat -A TPROXY_DNS_EXTERNAL -m mark --mark $mark -j RETURN
        iptables -t nat -A TPROXY_DNS_EXTERNAL -p udp --dport 53 -j REDIRECT --to-ports $dns_port
        iptables -t nat -A PREROUTING -p udp -j TPROXY_DNS_EXTERNAL

        iptables -t nat -N TPROXY_DNS_LOCAL
        iptables -t nat -A TPROXY_DNS_LOCAL -p udp ! --dport 53 -j RETURN
        iptables -t nat -A TPROXY_DNS_LOCAL -m mark --mark $mark -j RETURN
# 这条过滤mark的规则并不起作用

        # iptables -t nat -A TPROXY_DNS_LOCAL -m owner --uid-owner systemd-resolve -j RETURN
        # iptables -t nat -A TPROXY_DNS_LOCAL -m owner --uid-owner clash -j RETURN
# 注释掉以上两行会导致DNS请求回环，所以平时日用我会取消注释以上两行
        iptables -t nat -A TPROXY_DNS_LOCAL -p udp --dport 53 -j REDIRECT --to-ports $dns_port
        iptables -t nat -A OUTPUT -p udp -j TPROXY_DNS_LOCAL
    fi
```
