### ISSUE TITLE
clash可以用作全局代理程序吗？

### ISSUE THREAD

**Issue by luckypoem** [Dreamacro/clash#292]
我看到readme里面说：
“# redir port for Linux and macOS
# redir-port: 7892 ”

意思是clash可以用作全局代理程序？具体怎么操作？

**Comment by luckypoem** [comment]
@Dreamacro 

我看到这里：https://docs.cfw.lbyczf.com/tap-wang-ka 有写：
dns:
enable: true
enhanced-mode: fake-ip
listen: 127.0.0.1:53
nameserver:
   - 8.8.8.8

可我试过，好像无法用作全局代理（指整台机器的代理）

**Comment by Dreamacro** [comment]
clash 不包含任何机器上的网络设置，iptables 之类的需要自己配置，clash 只做流量处理

**Comment by cjwddtc** [comment]
可以用作全局代理。我目前tcp已经成功了，参考 https://github.com/Dreamacro/clash/issues/158 页面。

**Comment by luckypoem** [comment]
@cjwddtc ，没看懂#158 页面。你能在此具体写篇教程吗

**Comment by luckypoem** [comment]
@cjwddtc ,我系统是mac

**Comment by cjwddtc** [comment]
我并没有使用过mac系统，如果同样能够使用iptables的话就没有问题。
首先你需要先配置好clash本身，首先正确配置dns
```
dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:53
  enhanced-mode: redir-host
  nameserver:
      - 114.114.114.114
      - 223.5.5.5
      - 1.1.1.1
      - 1.0.0.1
      - tls://dns.rubyfish.cn:853
  fallback:
      - tls://1.1.1.1:853
      - tls://1.0.0.1:853
      - tls://dns.google:853

```
然后配置redir-port，任选一个没有使用的端口比如12345
`redir-port: 12345`
由于你是自身配置透明代理（区别于网关），需要手动修改dns为自身127.0.0.1.
单独开一个账户运行clash，并配置转发
```
iptables -t nat -A PREROUTING -d 192.168.0.0/16 -j RETURN 
iptables -t nat -A PREROUTING  -m owner --uid-owner xxx -j RETURN
iptables -t nat -A PREROUTING -p tcp -j REDIRECT --to-ports 12345
```
其中xxx要改为运行clash账户的uid，第一条命令是不代理本地地址，第二条命令是不代理clash自身发出的流量，第三部分则是将tcp连接转发到12345端口（由clash监听）
我并没有使用过mac，也没有配置过自身的透明代理，所以关于转发那部分可能会有错误。
