### ISSUE TITLE
[Feature] 请问怎么在mac上启用tun模式

### ISSUE THREAD

**Issue by Yewenyu** [Dreamacro/clash#2921]
### 先决条件

- [X] 我了解这里是 Clash 官方仓库，并非 Clash.Meta / OpenClash / ClashX / Clash For Windows 或其他任何衍生版本
- [X] 我已经在[这里](https://github.com/Dreamacro/clash/issues?q=is%3Aissue+label%3Aenhancement)找过我要提出的建议，**并且没有找到相关问题**
- [X] 我已经仔细阅读 [官方 Wiki](https://dreamacro.github.io/clash/) 

### 描述

我pull了master的代码

我按照配置设置了config.yaml
```

mixed-port: 7778
allow-lan: true

bind-address: '0.0.0.0'

mode: rule

interface-name: en1   # conflict with `tun.auto-detect-interface`

tun:
  enable: true
  stack: system # or gvisor
  auto-route: true # manage `ip route` and `ip rules`
  auto-redir: true # manage nftable REDIRECT

......下面省略....

```
然后go build后 ./clash -d .
socks代理成功了，但是没看到tun启用
`
./clash -d .
INFO[0000] inbound mixed://0.0.0.0:7778 create success. 
`
