### ISSUE TITLE
[Bug] Tun模式DNS泄漏问题

### ISSUE THREAD

**Issue by 1nC0deWeTrust** [Dreamacro/clash#2922]
### 先决条件

- [X] 我了解这里是官方开源版 Clash 核心仓库，**只提供开源版或者 Premium 内核的支持**
- [X] 我要提交 Clash 核心的问题，并非 Clash.Meta / OpenClash / ClashX / Clash For Windows 或其他任何衍生版本的问题
- [X] 我使用的是**本仓库**最新版本的 Clash 或 Clash Premium 内核
- [X] 我已经在 [Issue Tracker](……/) 中找过我要提出的 bug，**并且没有找到相关问题**
- [X] 我已经仔细阅读 [官方 Wiki](https://dreamacro.github.io/clash/) 并无法自行解决问题
- [ ] （非 Premium 内核必填）我已经使用 dev 分支版本测试过，问题依旧存在

### 版本

2023.08.17 Premium

### 适用的作业系统

Windows

### 适用的硬件架构

amd64

### 配置文件

```YAML
dns:
  enable: true
  ipv6: false
  default-nameserver:
    - 223.5.5.5
    - 119.29.29.29
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  nameserver:
    - https://dns.alidns.com/dns-query
    - https://doh.pub/dns-query
  fallback:
    - https://1.1.1.1/dns-query
    - https://dns.google/dns-query
    - https://doh.opendns.com/dns-query
  fallback-filter:
    geoip: true
    geoip-code: CN
    ipcidr:
      - 240.0.0.0/4
  fake-ip-filter:
    - +.stun.*.*
    - +.stun.*.*.*
    - +.stun.*.*.*.*
    - +.stun.*.*.*.*.*
    - "*.n.n.srv.nintendo.net"
    - +.stun.playstation.net
    - xbox.*.*.microsoft.com
    - "*.*.xboxlive.com"
    - "*.msftncsi.com"
    - "*.msftconnecttest.com"
    - WORKGROUP
    - apps.apple.com
  nameserver-policy: {}

tun:
  enable: true
  stack: gvisor
  auto-route: true
  auto-detect-interface: true
  dns-hijack:
    - any:53
```

### 问题描述

相关的issue基本都看过了，物理网卡DNS已经改成198.18.0.2了，见图👇

![image](https://github.com/Dreamacro/clash/assets/25895481/5354aa0d-d98a-4ca7-943c-0a27df6ec9f3)

规则走的match，但是match之前的规则我都加了no-resolve了。

检测网址走的都是代理，按理说不应该发往国内DNS进行解析。
![image](https://github.com/Dreamacro/clash/assets/25895481/8528ba6d-03ae-4d0a-8be6-bda2fc811d7d)
