### ISSUE TITLE
[Bug] <关于节点不支持UDP代理情况下的兜底路由方案>

### ISSUE THREAD

**Issue by vtroisWhite** [Dreamacro/clash#2923]
### 先决条件

- [X] 我了解这里是官方开源版 Clash 核心仓库，**只提供开源版或者 Premium 内核的支持**
- [X] 我要提交 Clash 核心的问题，并非 Clash.Meta / OpenClash / ClashX / Clash For Windows 或其他任何衍生版本的问题
- [X] 我使用的是**本仓库**最新版本的 Clash 或 Clash Premium 内核
- [X] 我已经在 [Issue Tracker](……/) 中找过我要提出的 bug，**并且没有找到相关问题**
- [X] 我已经仔细阅读 [官方 Wiki](https://dreamacro.github.io/clash/) 并无法自行解决问题
- [ ] （非 Premium 内核必填）我已经使用 dev 分支版本测试过，问题依旧存在

### 版本

2023.06.30-3-g24a3047 Premium

### 适用的作业系统

Windows

### 适用的硬件架构

amd64

### 配置文件

```YAML
代理方式：System Proxy

节点A：
 udp: true
  server: xxx.com
  password: *
  port: 443
  name: 土耳其TR-T
  type: trojan
  sni: xxx.com
节点B：
  cipher: *
  udp: true
  server: xxx.management
  password: *
  port: 0
  type: ss
```

### 问题描述

我在使用steam pc客户端使用CFW选择节点A开启代理时，发现steam客户端显示登录地址是中国，这代表节点A没有生效，以至于让steam检测出了我的实际ip是中国。

在我经过了多次尝试后，发现是节点A问题，使用节点B就可以让我的登录地址变成海外，因此怀疑是可能是代理节点不支持UDP协议的原因（虽然配置显示支持UDP，但服务端可能实际不支持UDP吧），并且节点A可以正常使用谷歌，且显示我在国外，
所以感觉只能是UDP的问题了。

因此我想要咨询下，在当前节点不支持UDP时，内核是会不使用代理，直接直连发起UDP请求吗？
