### ISSUE TITLE
[Bug] Config file parsing error

### ISSUE THREAD

**Issue by nakululusatuva** [Dreamacro/clash#2931]
### Prerequisites

- [X] I understand that this is the official open-source version of the Clash core, **only providing support for the open-source version or Premium version**
- [X] I am submitting an issue with the Clash core, not Clash.Meta / OpenClash / ClashX / Clash For Windows or any other derivative version
- [X] I am using the latest version of the Clash or Clash Premium core **in this repository**
- [X] I have searched at the [Issue Tracker](……/) **and have not found any related issues**
- [X] I have read the [official Wiki](https://dreamacro.github.io/clash/) **and was unable to solve the issue**
- [ ] (required for Premium core) I've tried the `dev` branch and the issue still exists

### Version

Clash v1.18.0 windows amd64 with go1.21.0 Thu Aug 17 14:55:14 UTC 2023

### Operating System

Windows

### Architecture

amd64

### Configuration File

```YAML
mixed-port: 7890
allow-lan: false
mode: Rule
log-level: debug
external-controller: 127.0.0.1:63526
secret: XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX

proxies:
  - name: MY_PROXY_1
    type: vmess
    server: domain1.com
    port: 443
    uuid: XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX
    alterId: 9527
    cipher: auto
    udp: true
    tls: true
    network: ws
    ws-opts:
      path: /path
  - name: MY_PROXY_2
    type: vmess
    server: domain2.com
    port: 443
    uuid: XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX
    alterId: 9527
    cipher: auto
    udp: true
    tls: true
    network: ws
    ws-opts:
      path: /path
  - name: MY_PROXY_3
    type: vmess
    server: domain3.com
    port: 443
    uuid: XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX
    alterId: 9527
    cipher: auto
    udp: true
    tls: true
    network: ws
    ws-opts:
      path: /path

proxy-providers:
  IATA-Airport:
    type: http
    url: http://127.0.0.1:25500/sub?target=clash&url={URL_ENCODED}&list=true
    path: ./airport.yaml
    interval: 21600
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 3600

proxy-groups:
  -
    name: RELAY-Airport
    type: select
    use:
      - IATA-Airport

  -
    name: Oversea
    type: load-balance
    strategy: round-robin
    proxies:
      - MY_PROXY_1
      - MY_PROXY_2
      - MY_PROXY_3
    url: http://www.gstatic.com/generate_204
    interval: 1800
  -
    name: America
    type: load-balance
    strategy: round-robin
    proxies:
      - MY_PROXY_1
      - MY_PROXY_2
    url: http://www.gstatic.com/generate_204
    interval: 1800
  -
    name: Japan
    type: load-balance
    strategy: round-robin
    proxies:
      - MY_PROXY_3
    url: http://www.gstatic.com/generate_204
    interval: 1800

  -
    name: RELAY-Airport-Oversea
    type: relay
    proxies:
      - RELAY-Airport
      - Oversea
  -
    name: RELAY-Airport-America
    type: relay
    proxies:
      - RELAY-Airport
      - America
  -
    name: RELAY-Airport-Japan
    type: relay
    proxies:
      - RELAY-Airport
      - Japan

  -
    name: RELAY-Airport-MY_PROXY_1
    type: relay
    proxies:
      - RELAY-Airport
      - MY_PROXY_1
  -
    name: RELAY-Airport-MY_PROXY_2
    type: relay
    proxies:
      - RELAY-Airport
      - MY_PROXY_2
  -
    name: RELAY-Airport-MY_PROXY_3
    type: relay
    proxies:
      - RELAY-Airport
      - MY_PROXY_3

rules:
  - IP-CIDR,192.168.0.0/16,DIRECT,no-resolve
  - IP-CIDR,10.0.0.0/8,DIRECT,no-resolve
  - IP-CIDR,172.16.0.0/12,DIRECT,no-resolve
  - IP-CIDR,127.0.0.0/8,DIRECT,no-resolve
  - IP-CIDR,100.64.0.0/10,DIRECT,no-resolve
  - IP-CIDR6,::1/128,DIRECT,no-resolve
  - IP-CIDR6,fc00::/7,DIRECT,no-resolve
  - IP-CIDR6,fe80::/10,DIRECT,no-resolve
  - IP-CIDR6,fd00::/8,DIRECT,no-resolve
  - GEOIP,CN,DIRECT
  - MATCH,RELAY-Airport-Oversea
```

### Log

```Text
time="2023-09-11T10:24:47-07:00" level=info msg="Start initial provider IATA-Airport"
time="2023-09-11T10:24:48-07:00" level=fatal msg="Parse config error: initial proxy provider IATA-Airport error: yaml: unmarshal errors:\n  line 1: cannot unmarshal !!str `No node...` into provider.ProxySchema"
```

### Description

I converted my airport subscription with 'subconverter' using the options 'target=clash' and 'list=true'. The URL looks like this:
```
http://127.0.0.1:25500/sub?target=clash&url={ENCODED_URL}&list=true
```
When I request this URL in my browser, it returns the converted configuration:
```
proxies:
  - {name: HK01, server: airportdomain.com, port: 1234, type: trojan, password: XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX, sni: airportsni1.com, skip-cert-verify: true, udp: true}
  - {name: HK02, server: airportdomain.com, port: 5678, type: trojan, password: XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX, sni: airportsni2.com, skip-cert-verify: true, udp: true}
  - {name: HK03, server: airportdomain.com, port: 9101, type: trojan, password: XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX, sni: airportsni3.com, skip-cert-verify: true, udp: true}
```
Then I paste this URL into the 'proxy-providers' section in my config.yaml file and encounter the following error: "\n line 1: cannot unmarshal !!str No node...' into provider.ProxySchema" either in the cmd or Windows Terminal.
The strange thing is that the exact same configuration file works fine on Linux with the same version of Clash. Am I missing something?

clash: https://github.com/Dreamacro/clash/releases/tag/v1.18.0
subconverter: https://github.com/tindy2013/subconverter/releases/tag/v0.7.2
