### ISSUE TITLE
[Bug] <问题标题>

### ISSUE THREAD

**Issue by xiandu999-yu** [Dreamacro/clash#2938]
### 先决条件

- [X] 我了解这里是官方开源版 Clash 核心仓库，**只提供开源版或者 Premium 内核的支持**
- [X] 我要提交 Clash 核心的问题，并非 Clash.Meta / OpenClash / ClashX / Clash For Windows 或其他任何衍生版本的问题
- [X] 我使用的是**本仓库**最新版本的 Clash 或 Clash Premium 内核
- [X] 我已经在 [Issue Tracker](……/) 中找过我要提出的 bug，**并且没有找到相关问题**
- [X] 我已经仔细阅读 [官方 Wiki](https://dreamacro.github.io/clash/) 并无法自行解决问题
- [X] （非 Premium 内核必填）我已经使用 dev 分支版本测试过，问题依旧存在

### 版本

Clash v1.18.0 linux arm64 with go1.21.0 Thu Aug 17 14:49:08 UTC 2023

### 适用的作业系统

Linux, Windows

### 适用的硬件架构

amd64, arm64

### 配置文件

```YAML
proxies:
  - {name: ***• HK 1, server: ***.***.***, port: 93**, type: ss, cipher: chacha20-ietf, password: ****************, plugin: obfs, plugin-opts: {mode: http, host: ***********!@.download.microsoft.com}, udp: true}
proxies:
  - {name: 香港 01, server: ***.***.***, port: 93**, type: ss, cipher: chacha20-ietf, password: *****************, plugin: obfs, plugin-opts: {mode: http, host: ************.download.microsoft.com}, udp: true}
```

### 日志输出

```Text
error: http: invalid Host header

↑这是每行错误的结尾
```

### 问题描述

起初在openwrt上使用时发现无法测出延迟，但懒得更新的ClashforWindows能ping，后更新了CFW版本后又不能ping了，怀疑新版本bug，哦对了，我是在GitHub上捡漏的节点，上面是ping不了的，下面是能ping的[是同一个机场不用怀疑]
