### ISSUE TITLE
[Bug] 以proxy-providers形式配置wireguard类型的Outbound

### ISSUE THREAD

**Issue by kwokpia** [Dreamacro/clash#2940]
### 先决条件

- [X] 我了解这里是官方开源版 Clash 核心仓库，**只提供开源版或者 Premium 内核的支持**
- [X] 我要提交 Clash 核心的问题，并非 Clash.Meta / OpenClash / ClashX / Clash For Windows 或其他任何衍生版本的问题
- [X] 我使用的是**本仓库**最新版本的 Clash 或 Clash Premium 内核
- [X] 我已经在 [Issue Tracker](……/) 中找过我要提出的 bug，**并且没有找到相关问题**
- [X] 我已经仔细阅读 [官方 Wiki](https://dreamacro.github.io/clash/) 并无法自行解决问题
- [X] （非 Premium 内核必填）我已经使用 dev 分支版本测试过，问题依旧存在

### 版本

Clash 2023.06.30-1-g1524739 linux amd64 with go1.20.5 Fri Jul  7 03:19:26 PM UTC 2023

### 适用的作业系统

Linux

### 适用的硬件架构

amd64

### 配置文件

```YAML
proxy-providers:
  xVPN:
    type: file
    path: ./xVPN.yaml
    health-check:
      enable: true
      interval: 36000
      url: http://www.gstatic.com/generate_204

#xVPN.yaml
proxies:
  - name: "sgp-x"
    type: wireguard
    server: ...
    port: 1637
    ip: ...
    ipv6: ...
    private-key: ...
    public-key: ...
    preshared-key: ...
    remote-dns-resolve: true # 远程解析 DNS, 使用 `dns` 字段, 默认为 true
    dns: [..., ...]
    mtu: 1320
    udp: true
```

### 日志输出

```Text
#remote-dns-resolve = true
[TCP] dial failed error=dial: lookup www.google.com. on xxx write udp [xxx]:65236: i/o timeout proxy=proxy-G lAddr=192.168.1.66:50302 rAddr=www.google.com:443 rule=RuleSet rulePayload=proxy-domain

#remote-dns-resolve = false
[TCP] dial failed error=context deadline exceeded proxy=proxy-G lAddr=192.168.1.66:51420 rAddr=www.google.com:443 rule=RuleSet rulePayload=forced-proxy
```

### 问题描述

wireguard 类型的Outbound, 用 proxies的形式配置时, 功能正常; 
用 proxy-providers 的形式配置, 连不通.

### 复现步骤

以proxy-providers形式配置wireguard 类型的Outbound.
