### ISSUE TITLE
[Feature] <增强"rule groups"的 可配置性，添加诸如sub-rule、更多条件判断……等等>

### ISSUE THREAD

**Issue by Accademia** [Dreamacro/clash#2946]
### 先决条件

- [X] 我了解这里是 Clash 官方仓库，并非 Clash.Meta / OpenClash / ClashX / Clash For Windows 或其他任何衍生版本
- [X] 我已经在[这里](https://github.com/Dreamacro/clash/issues?q=is%3Aissue+label%3Aenhancement)找过我要提出的建议，**并且没有找到相关问题**
- [X] 我已经仔细阅读 [官方 Wiki](https://dreamacro.github.io/clash/) 

### 描述

目前，虽然规则中添加了 "rule groups"（如下），但仍然可配置性不够健壮。希望增强可配置性。做到一步到位
```
rules:
  - if: network == 'tcp'
    name: TCP
    # engine: expr # the default engine is `expr`, `starlark` is also valid
    rules:
      - if: dst_port == 443
        name: HTTPS
        rules:
          - MATCH,DIRECT
      - DOMAIN-SUFFIX,baidu.com,DIRECT
  - DOMAIN-KEYWORD,google,DIRECT
  - DOMAIN-KEYWORD,www.bing.com,DIRECT
  - MATCH,REJECT
```

Check https://github.com/Dreamacro/clash/releases/tag/premium.

### 可能的解决方案

--------------------------------------------

为了应对上述的问题。建议，增强，配置的灵活性。

这里给了一示例，用来解决，当检测到来自IDM下载器的流量时，如何分流。

```
proxy-groups: 
  - name: <VPS节点>-美国
    type: select
    url: https://captive.apple.com/generate_204 # 测试链接（Apple）
    proxies:
      - 禁用
      - 🔰[VPS]—[美国]—(Linode-2TB)
      - 🔰[VPS]—[美国]—(BWG-2TB)

  - name: <VPS节点>-日本
    type: select
    url: https://captive.apple.com/generate_204 # 测试链接（Apple）
    proxies:
      - 禁用
      - 🔰[VPS]—[日本]—(Linode-2TB)
      - 🔰[VPS]—[日本]—(BWG-2TB)


  - name: IDM下载器
    type: select
    url: https://captive.apple.com/generate_204 # 测试链接（Apple）
    proxies:
      - 禁用
      - 启用
      - DIRECT
      - 🔰[VPS]—(大流量节点-10TB)


rules:

  # 针对IDM软件进行配置分流
  - if: network == 'tcp' & (PROCESS-NAME == 'IDMan' or PROCESS-PATH == 'C:\Program Files (x86)\Internet Download Manager\') & proxy-groups(IDM下载器) !== '禁用'
    name: TCP
    # engine: expr # the default engine is `expr`, `starlark` is also valid
    rules:

      - if: dst_port == 443 &  proxy-groups(IDM下载器) == '启用'
        name: HTTPS
        rules:
          - RULE-SET , gfwlist     , 🚧<VPS节点>—GFWList
          - SUB-RULE , 按国家分流的子规则
          - MATCH,DIRECT

      - if: dst_port == 443 &  proxy-groups(IDM下载器) == '🔰[VPS]—(大流量节点-10TB)'
        name: HTTPS
        rules:
          - RULE-SET , gfwlist     , 🔰[VPS]—(大流量节点-10TB)
          - MATCH , DIRECT

  # 继续其他分流规则
  - DOMAIN-KEYWORD,google,DIRECT
  - DOMAIN-KEYWORD,www.bing.com,DIRECT
  - MATCH,REJECT


sub-rules:
  lable: '按国家分流的子规则'
  - GEOIP , us , <VPS节点>-美国
  - GEOIP , jp , <VPS节点>-日本


rule-providers: 
  gfwlist:
    type: http
    behavior: domain
    url: 'https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/gfw.txt'
    path: ./ruleset/gfwlist.yaml
    interval: 86400

```

**Comment by Accademia** [comment]
> > `if` field is the same as the shortcut syntax and if none of the sub-rules match, then continue to match the next rule.
> 
> 
> 
> 你真的看得懂这句话的意思吗？

你真的看懂了我写的意思了吗？

**Comment by Accademia** [comment]
> > `if` field is the same as the shortcut syntax
> 
> 问题是 `if` 字段使用的是跟 Script Shortcuts 脚本一样的语法啊。

C语言里面的 if else，跟 汇编语言中的Branch指令，不也是一样的语法？？？？？

所以，既然都一样，难道，汇编 = 包打天下 ？

所以，难道用 “脚本” 去割裂 “规则”，就是最优解法？

**Comment by Accademia** [comment]
> > `if` field is the same as the shortcut syntax
> 
> 问题是 `if` 字段使用的是跟 Script Shortcuts 脚本一样的语法啊。

如果要说，功能一样。其实，只要，图灵完备的《编程语言或指令集》，那在功能上，必定都是彼此全等价的。

而不同语言（或类语言）能在垂直市场有受众，必定在面向特定目标的效率上，是行业也最优的。

脚本这种《打补丁》的方式，不是《封装 分流算法》的最优解。

**Comment by Accademia** [comment]
> https://github.com/MetaCubeX/Clash.Meta

我之前是看过Clash.Meta。

先说结论：

 - 从《可维护性、可读性》，这俩角度来说，本项目的Rule Group写法，秒杀Clash.Meta的 竞品功能，至少100条街 ！！~~


对比一下：

```
# ------------
# Clash.Meta
# ------------
- AND,((DOMAIN,baidu.com),(NETWORK,tcp)),DIRECT

```

```
# ------------
# Clash官方版
# ------------

  - if: (network == 'tcp') 
    rules:
     - DOMAIN-SUFFIX , baidu.com DIRECT

或（未来）

  - if: (network == 'tcp') & (DOMAIN-SUFFIX == 'baidu.com')
    rules:
     - MATCH, DIRECT

```

你认为上述两者，哪种可读性更强？

非常明显，条件判断膨胀，那么， Clash.Meta那种写法，其可读性，会指数级下降。

最终，上述俩，其可维护性（可读性）相比，就像 Perl 与 Python之间的差异一样。

当然，最后在补充两点：
 1. 我在本issue中提到的Feature，在Clash.meta中也没有全部实现，比如带有接口的子规则（为了最大限度，提升，封装性）。
 2. Clash.Meta的稳定性，是不用他们的另一个主要原因。尽管他们实现了很多，痛点功能。但也只能忍痛不用。
