### ISSUE TITLE
[Bug] TUN模式下使用script模式时，不识别rule-providers中的PROCESS-NAME规则

### ISSUE THREAD

**Issue by Leyoud** [Dreamacro/clash#2964]
### 先决条件

- [X] 我了解这里是官方开源版 Clash 核心仓库，**只提供开源版或者 Premium 内核的支持**
- [X] 我要提交 Clash 核心的问题，并非 Clash.Meta / OpenClash / ClashX / Clash For Windows 或其他任何衍生版本的问题
- [X] 我使用的是**本仓库**最新版本的 Clash 或 Clash Premium 内核
- [X] 我已经在 [Issue Tracker](……/) 中找过我要提出的 bug，**并且没有找到相关问题**
- [X] 我已经仔细阅读 [官方 Wiki](https://dreamacro.github.io/clash/) 并无法自行解决问题
- [ ] （非 Premium 内核必填）我已经使用 dev 分支版本测试过，问题依旧存在

### 版本

clash-premium-2023.08.17

### 适用的作业系统

Windows

### 适用的硬件架构

amd64

### 配置文件

```YAML
mixed-port: 7890
external-ui: ./
log-level: info
allow-lan: false
bind-address: "*"
external-controller: 127.0.0.1:9090
secret: ""
ipv6: false
authentication: []
interface-name: ""

mode: script

dns:
  {
    enable: true, listen: 0.0.0.0:53,

    enhanced-mode: fake-ip, fake-ip-range: 198.18.0.1/16, 
    
    fake-ip-filter: ["*.msftncsi.com", "*.msftconnecttest.com"],

    nameserver: [tls://dns.alidns.com:853]

  }

tun: 
  { 
    enable: true, stack: gvisor, 

    auto-route: true, auto-detect-interface: true, 
    
    dns-hijack: [any:53]
  }

proxies: []

proxy-groups:
    - name: ProcessNameDirectlist
      type: select
      proxies:
          - DIRECT

    - name: Other
      type: select
      proxies:
          - DIRECT
          
rules: 
  - RULE-SET,ProcessNameDirectlist,DIRECT
  - MATCH,Other

rule-providers:
  ProcessNameDirectlist:
    type: http
    behavior: classical
    path: ./providers/rule/ProcessNameDirectlist.yaml
    url: https://raw.fgit.cf/Leyoud/Rules/master/ProcessNameDirectlist.yaml
    interval: 86400

script:
  code: |-
    def main(ctx,metadata):

      if ctx.rule_providers["ProcessNameDirectlist"].match(metadata):
        ctx.log("[Script] matched ProcessNameDirectlist PROCESS-NAME rule")
        return "ProcessNameDirectlist"

      return "Other"
```

### 问题描述

TUN模式下
使用script模式时，不识别rule-providers中的PROCESS-NAME规则
使用rule模式表现正常
