### ISSUE TITLE
[Bug] Ubuntu 上使用 clash premium 开启 TUN 模式后，局域网内其他设备无法通过该设备上网

### ISSUE THREAD

**Issue by KevinLoveGitHub** [Dreamacro/clash#2967]
### 先决条件

- [X] 我了解这里是官方开源版 Clash 核心仓库，**只提供开源版或者 Premium 内核的支持**
- [X] 我要提交 Clash 核心的问题，并非 Clash.Meta / OpenClash / ClashX / Clash For Windows 或其他任何衍生版本的问题
- [X] 我使用的是**本仓库**最新版本的 Clash 或 Clash Premium 内核
- [X] 我已经在 [Issue Tracker](……/) 中找过我要提出的 bug，**并且没有找到相关问题**
- [X] 我已经仔细阅读 [官方 Wiki](https://dreamacro.github.io/clash/) 并无法自行解决问题
- [ ] （非 Premium 内核必填）我已经使用 dev 分支版本测试过，问题依旧存在

### 版本

Clash 2023.08.17 linux amd64 with go1.21.0 Thu Aug 17 15:07:25 UTC 2023

### 适用的作业系统

Linux

### 适用的硬件架构

amd64

### 配置文件

```YAML
port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
ipv6: false
external-controller: 0.0.0.0:9090
dns:
  enable: true
  listen: 0.0.0.0:53
  nameserver:
    - https://223.5.5.5/dns-query
    - https://223.6.6.6/dns-query
    - https://doh.pub/dns-query
  fallback:
    - 8.8.8.8
  ipv6: false
  enhanced-mode: fake-ip
  fake-ip-filter:
    - "*.lan"
    - stun.*.*.*
tun:
  enable: true
  stack: system
  dns-hijack:
    - 8.8.8.8:53
    - tcp://8.8.8.8:53
    - any:53
    - tcp://any:53
  auto-route: true
  auto-detect-interface: true
```

### 问题描述

Ubuntu 服务器上开启 TUN 模式后，关闭了系统的 `systemd-resolved` 服务，`/etc/sysctl.conf` 文件添加了 `net.ipv4.ip_forward=1`，本机正常上网。路由器未做任何更改，把局域网内其他设备的网关设置为该服务器的 IP，发现无法上网，而且访问网络的时候，clash 日志中也没有看到相关的 DNS 解析。请问这种情况该如何排查？
