### ISSUE TITLE
麻烦给一个配置文件

### ISSUE THREAD

**Issue by viponedream** [Dreamacro/clash#2971]
### 先决条件

- [X] 我了解这里是官方开源版 Clash 核心仓库，**只提供开源版或者 Premium 内核的支持**
- [X] 我要提交 Clash 核心的问题，并非 Clash.Meta / OpenClash / ClashX / Clash For Windows 或其他任何衍生版本的问题
- [X] 我使用的是**本仓库**最新版本的 Clash 或 Clash Premium 内核
- [X] 我已经在 [Issue Tracker](……/) 中找过我要提出的 bug，**并且没有找到相关问题**
- [X] 我已经仔细阅读 [官方 Wiki](https://dreamacro.github.io/clash/) 并无法自行解决问题
- [X] （非 Premium 内核必填）我已经使用 dev 分支版本测试过，问题依旧存在

### 版本

Clash v1.18.0 linux amd64 with go1.21.0 Thu Aug 17 14:47:19 UTC 2023

### 适用的作业系统

Linux

### 适用的硬件架构

amd64

### 配置文件

```YAML
port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
ipv6: false
external-controller: 0.0.0.0:9090

proxies:
  - name: "socks"
    type: socks5
    server: 127.0.0.1
    port: 2001


dns:
  enable: true
  listen: 0.0.0.0:53
  nameserver:
    - https://223.5.5.5/dns-query
    - https://223.6.6.6/dns-query
    - https://doh.pub/dns-query
  fallback:
    - 8.8.8.8
  ipv6: false
  enhanced-mode: fake-ip
  fake-ip-filter:
    - "*.lan"
    - stun.*.*.*
tun:
  enable: true
  stack: system
  dns-hijack:
    - 8.8.8.8:53
    - tcp://8.8.8.8:53
    - any:53
    - tcp://any:53
  auto-route: true # manage `ip route` and `ip rules`
  auto-redir: true # manage nftable REDIRECT
  auto-detect-interface: true # conflict with `interface-name`
```

### 日志输出

```Text
level=error msg="Start DNS server error: listen udp 0.0.0.0:53>
```

### 问题描述

ubuntu server 20.04, 本机已经有socks5可以正常上网了, 
打算安装clash tun 全局代理上网(利用本机现成的s5代理), 这样上网更省心不必每次都要代理.
看了一下config.yaml没看懂, 麻烦给一个简易的版本, 谢谢.

所有连网 -> clash tun -> socks5出去, 

### 复现步骤

没法上
