### ISSUE TITLE
[Bug] <raspbian下clash-premium使用tun做透明代理，跟qbittorrent-nox进程冲突>

### ISSUE THREAD

**Issue by bishiping** [Dreamacro/clash#2972]
### 先决条件

- [X] 我了解这里是官方开源版 Clash 核心仓库，**只提供开源版或者 Premium 内核的支持**
- [X] 我要提交 Clash 核心的问题，并非 Clash.Meta / OpenClash / ClashX / Clash For Windows 或其他任何衍生版本的问题
- [X] 我使用的是**本仓库**最新版本的 Clash 或 Clash Premium 内核
- [X] 我已经在 [Issue Tracker](……/) 中找过我要提出的 bug，**并且没有找到相关问题**
- [X] 我已经仔细阅读 [官方 Wiki](https://dreamacro.github.io/clash/) 并无法自行解决问题
- [ ] （非 Premium 内核必填）我已经使用 dev 分支版本测试过，问题依旧存在

### 版本

root@raspberrypi:/etc/clash# ./clash -v Clash 2023.08.17 linux arm with go1.21.0 Thu Aug 17 15:07:26 UTC 2023

### 适用的作业系统

Linux

### 适用的硬件架构

armv7

### 配置文件

```YAML
root@raspberrypi:/etc/clash# cat config.yaml
allow-lan: true
mode: rule
log-level: warning
external-controller: 0.0.0.0:9090
external-ui: /etc/clash/dashboard

dns:
        enable: true
        listen: 0.0.0.0:53
        enhanced-mode: fake-ip
        fake-ip-range: 198.18.0.1/16
        nameserver:
                - 114.114.114.114
                - tcp://8.8.8.8:53
                - https://1.1.1.1/dns-query
tun:
        enable: true
        stack: system
        auto-route: true
        auto-redir: true
        auto-detect-interface: true

proxies:

proxy-groups:
        - name: proxy
          type: select
          proxies:
                  - DIRECT

rules:
        - DOMAIN-SUFFIX, google.com, proxy
        - DOMAIN-KEYWORD, google, proxy
        - DOMAIN-SUFFIX, youtube.com, proxy
        - DOMAIN-SUFFIX, android.com, proxy
        - DOMAIN-SUFFIX, github.com, proxy
        - DOMAIN-SUFFIX, teddysun.com, proxy
        - DOMAIN-SUFFIX, maxmind.com, proxy
        - DOMAIN-SUFFIX, edu.cn, DIRECT
        - IP-CIDR, 127.0.0.0/8, DIRECT
        - IP-CIDR, 192.168.0.0/16, DIRECT
        - SRC-PORT, 8999, DIRECT
        - PROCESS-NAME, qbittorrent-nox, DIRECT
        - GEOIP, CN, DIRECT
        - MATCH, proxy
```

### 问题描述

个人想在树莓派`raspbian 32bit系统`上使用 `clash-premium` 内核用`tun`模式自动配置透明代理，局域网下其它设备配置网关和dns后也正常使用，但是在树莓派系统上安装有`qbittorrent-nox`程序，在`clash`运行情况下，重启（断电自启动）`qbittorrent-nox`进程则启动失败，手动关闭clash运行，重启`qbittorrent-nox`则正常。

下面是在clash运行状态下，手动运行qbittorrent-nox的日志：
*************************************************************
Please file a bug report at http://bug.qbittorrent.org and provide the following information:

qBittorrent version: v4.1.5

Caught signal: SIGSEGV
Stack trace:
There were no function names found in the stack trace
.Seems like debug symbols are not installed, and the stack trace is useless.
Segmentation fault

![Snipaste_2023-10-22_11-47-28](https://github.com/Dreamacro/clash/assets/44999051/73d5ac3c-1252-432c-b013-f64311aa6289)

下面是手动关闭clash运行，手动重启qbittorrent-nox进程，正常：
![Snipaste_2023-10-22_11-48-07](https://github.com/Dreamacro/clash/assets/44999051/ca79f233-d416-4f99-af24-6663c24c4caf)
