### ISSUE TITLE
建议配置文件和规则分离

### ISSUE THREAD

**Issue by cjwddtc** [Dreamacro/clash#306]
clash里面配置文件中同时包含了配置和规则（包括服务器列表），这会导致每次更新订阅时，会丢失掉所有修改的配置（比如dns配置，还有redir-port），是否可以为配置信息另外定义一个文件，或者定义一个额外的配置文件，其中的配置可以覆盖原有的配置（此方案可以向前兼容）？

**Comment by Dreamacro** [comment]
提出一个完整的解决方案或者看看 #272

**Comment by comwrg** [comment]
可以用包含文件来实现

我们可以定义
关键字`include-proxy`用于包含节点文件
比如 
* 包含一个文件 `include-proxy: node.yml` 
* 包含一些文件 `include-proxy: nodes/*.yml`

关键字`include-rule`用于包含规则文件
比如
* 包含一个文件 `include-rule: rule.yml`
考虑到`rule`有优先级顺序，所以无法用通配符进行包含

其实上面的两个关键字在代码中实现并没有什么区别，不过考虑到`proxy`和`rule`混写进一个文件再进行包含会使得配置结构非常的混乱

---

### 我认为的比较理想的配置结构
假设 https://github.com/Dreamacro/clash/issues/272#issuecomment-523329209 中`label`的功能已经实现

考虑到众多节点文件的`label`肯定是不会非常统一的，比如`label`: [`油管` `youtu` `youtube`] 都是表示一样东西

那么需要对关键字`include-proxy`进行一些扩展
```yml
include-proxy:
 file: foo.yml
 alias: # 设置别名
  - youtube # 默认第一个为正式的名字
  - 油管
  - youtu
```

#### 文件结构

```yml
# config.yml
# 第一部分：程序的一些设置信息
port: 7890
...省略

# 第二部分：包含节点文件
include-proxy: nodes/*.yml

# 第三部分：定义各个标签的走向
Proxy Group:
  name: foo
  type: foo
  labels:
    - xxx
    - xxx

# 第四部分：包含规则文件
include-rule: lan.yml
include-rule: ad.yml
include-rule: apple.yml
...省略
```
