### ISSUE TITLE
8080 cannot be changed to another port?

### ISSUE THREAD

**Issue by SettingDust** [Dreamacro/clash#336]
```
port: 7890
socks-port: 7891
allow-lan: true
external-controller: 0.0.0.0:7892
external-ui: /ui
```

```
time="2019-09-30T12:53:47Z" level=info msg="HTTP proxy listening at: :7890"
time="2019-09-30T12:53:47Z" level=info msg="SOCKS proxy listening at: :7891"
time="2019-09-30T12:53:47Z" level=info msg="RESTful API listening at: 0.0.0.0:8080"
```

我确实是在配置放好之后运行的docker-compose，并且当我把docker-compose端口映射改为容器内8080之后，就可以访问了，貌似`external-controller`无效

**Comment by Dreamacro** [comment]
给出完整的 config 文件及完整 docker-compose 文件

**Comment by SettingDust** [comment]
config已经完整

```
version: '3'
services:
  clash:
    image: abreto/clash-ui
    volumes:
      - /home/settingdust/.config/clash/config.yaml:/root/.config/clash/config.yaml
    ports:
      - "7890:7890"
      - "7891:7891"
      - "7892:8080"
    restart: always
    network_mode: "bridge"
    container_name: clash 
```
