### ISSUE TITLE
遇到github.com无法访问，日志中的目标IP为fakeip

### ISSUE THREAD

**Issue by Masstone** [Dreamacro/clash#345]
clash内核版本：
v0.15.0-54-gd3c50cf
使用环境
OP路由器+Openclash+上游smartdns

问题：
一台mac上的chrome、safari均无法访问github.com
换到手机上的chrome也无法访问
![IMAGE 2019-10-08 16:19:40](https://user-images.githubusercontent.com/1457421/66379114-6e5fcc80-e9e7-11e9-99c0-08243764d97c.jpg)
![IMAGE 2019-10-08 16:19:54](https://user-images.githubusercontent.com/1457421/66379139-76b80780-e9e7-11e9-8e55-50581c88a737.jpg)
对应的日志中目标ip为fakeip
![IMAGE 2019-10-08 16:19:50](https://user-images.githubusercontent.com/1457421/66379138-7455ad80-e9e7-11e9-9df7-801a7a3e18c1.jpg)

其他线索：客户端socket连接clash可以正常访问GitHub

**Comment by comzyh** [comment]
希望能用 `dig` 确定 clash DNS 的响应是否为 这个 fake-ip

注意要直接 dig clash 而不是 clash 下游的 DNS cache

> dig github.com @127.0.0.1 -p <clash dns port>

**Comment by comzyh** [comment]
clash fake-IP 的 LRU 机制是有问题的。我提供一个 reproduce 便于理解

配置文件

```yaml
port: 8081
socks-port: 1081
redir-port: 7893
bind-address: "0.0.0.0"
allow-lan: true
mode: Rule
log-level: debug
dns:
  enable: true # set true to enable dns (default is false)
  listen: 0.0.0.0:7053
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  nameserver:
    - 114.114.114.114
```

测试脚本
```bash
#!/bin/bash

dns_port=7053
socks_port=1081

dig_and_print() {
    host=$1
    ret=$(dig ${host} @127.0.0.1 -p ${dns_port} +short)
    echo "${host} -> ${ret}"
}

# assume clash fake-ip pool have capacity of 1000
for i in {0000..0999}
do
    host="${i}.github.com"
    dig_and_print $host
done

echo "now, clash github-pool lru cache is filled with 1000 record of HOST->IP and 1000 record of OFFSET->HOST"

echo "dig 0000.github.com, to move the 0000.github.com->IP to the back, but keep the corresponding OFFSET->HOST as is."

dig_and_print "0000.github.com"

echo "we dig one more domain"

dig_and_print "1000.github.com" # comment this line, restart(important!) clash and try again.

echo "now, we try to dig 0000.github.com again"

dig_and_print "0000.github.com"

echo "but the corresponding OFFSET->HOST record is removed from LRU cache, let's have a try"

ip0000=$(dig 0000.github.com @127.0.0.1 -p ${dns_port} +short)

echo "curl --socks5 127.0.0.1:${socks_port} --connect-timeout 5 http://${ip0000} -I "
curl --socks5 127.0.0.1:${socks_port} --connect-timeout 5 http://${ip0000} -I
```

日志输出

```
INFO[0000] HTTP proxy listening at: 0.0.0.0:8081        
INFO[0000] DNS server listening at: 0.0.0.0:7053        
INFO[0000] Redir proxy listening at: 0.0.0.0:7893       
INFO[0000] SOCKS proxy listening at: 0.0.0.0:1081       
INFO[0005] 127.0.0.1 --> 198.18.0.2 doesn't match any rule using DIRECT 
```

这个 BUG 在于 fake-ip 的 pool 中同一个 LRU cache 同时存储了 `host->ip` 和 `offset->host` 两种映射

有可能某个 <host, ip> pair 中 `offset->host` 记录被淘汰，但是 `host->ip` 仍然存在
