### ISSUE TITLE
Feature Request: SIP003 Support

### ISSUE THREAD

**Issue by QuantumGhost** [Dreamacro/clash#365]
Shadowsocks has built an [extensible plugin mechanism](https://shadowsocks.org/en/spec/Plugin.html) to achieve traffic obfuscation. I believe clash could benefit from using plugins from community. (For example, there is [Cloak](https://github.com/cbeuw/Cloak), which obfuscating SS traffic by hiding it behind TLS.)

It seems that no one has mentioned SIP003 yet. I'd like to know if there is any consideration not  to implement SIP003 in clash.

Ref: [SIP003 discussion](https://github.com/shadowsocks/shadowsocks-org/issues/28)

**Comment by Dreamacro** [comment]
Do you mean simple-obfs or v2ray-plugin? It's already built-in clash.

```yaml
- name: "ss2"
  type: ss
  server: server
  port: 443
  cipher: chacha20-ietf-poly1305
  password: "password"
  plugin: obfs
  plugin-opts:
    mode: tls # or http
    # host: bing.com

- name: "ss3"
  type: ss
  server: server
  port: 443
  cipher: chacha20-ietf-poly1305
  password: "password"
  plugin: v2ray-plugin
  plugin-opts:
    mode: websocket # no QUIC now
    # tls: true # wss
    # skip-cert-verify: true
    # host: bing.com
    # path: "/"
    # mux: true
    # headers:
    #   custom: value
```

**Comment by QuantumGhost** [comment]
Yes, I have seen that both simple-obfs and v2ray-plugin have been integrated into Clash. 

However, there are plugins that are not part of clash, and it is impossible to integrate every plugin into Clash. 

I could implement SIP003 for myself and evaluate it for a while. I'd like to know is there any possibility that Clash accepts a PR for SIP003.

**Comment by Dreamacro** [comment]
Before you create a PR, I want to know the detail of your plan (config design etc)

**Comment by QuantumGhost** [comment]
I haven't write the code yet. 

I guess the structure below is OK.

```yaml
plugin: sip003
plugin-opts:
  name: "v2ray-plugin"     # path of plugin executable
  args: ["foo", "bar", "baz"]   # command line arguments to plugin
  opts: "path=/ping"          # options passed to plugin, as required by SIP003
```
