### ISSUE TITLE
VMess 配置不支持 IPv6 地址的服務器

### ISSUE THREAD

**Issue by Azureki** [Dreamacro/clash#381]
ss 的配置中，server部分直接填ipv6地址是没问题的。
但是 vmess 配置中则不行。错误信息如下：
(假设 ipv6地址是 aaaa:bbbb:cccc:dddd:eeee:ffff:gggg:hhhh )

> WARN[0029] dial Proxy error: Dial aaaa:bbbb:cccc:dddd:eeee:ffff:gggg:hhhh error: parse ws://aaaa:bbbb:cccc:dddd:eeee:ffff:gggg:hhhh: invalid port ":hhhh" after host

----

我现在的办法是把ipv6地址放到hosts中。

**Comment by Dreamacro** [comment]
"[aaaa:bbbb:cccc:dddd:eeee:ffff:gggg]:port"

**Comment by Azureki** [comment]
@Dreamacro 
不明白您的意思…… `hhhh`是地址的一部分，不是端口，端口是80。

如果server部分填"[aaaa:bbbb:cccc:dddd:eeee:ffff:gggg]:port"的话，错误信息是这样：
> WARN[0022] dial Proxy error: [[aaaa:bbbb:cccc:dddd:eeee:ffff:gggg]:hhhh]:80 connect error

如果server部分填"[aaaa:bbbb:cccc:dddd:eeee:ffff:gggg:hhhh]"的话，错误信息是这样：
> WARN[0022] dial Proxy error: [[aaaa:bbbb:cccc:dddd:eeee:ffff:gggg:hhhh]]:80 connect error

**Comment by Dreamacro** [comment]
host: "[ipv6-addr]:port"

**Comment by Azureki** [comment]
更加迷惑了……host指vmess中的吗？这个已经填了别的。而且这样的话server和port又该怎么办呢（

**Comment by Dreamacro** [comment]
😷泛指各种地址, 所有用到 IPv6 的地方都是 "[ipv6-addr]:port"

**Comment by Azureki** [comment]
可是如果server的value是"[ipv6-addr]:port"格式，那么port的value怎么办？如果也填80，错误信息和我上面提到的一样。如果删去port，clash无法启动。提示：
> key 'port' missing.

**Comment by Dreamacro** [comment]
我自己试了一下没问题啊, 不带 []

```yaml
Proxy:
- name: "vmess"
  type: vmess
  server: "::0"
  port: 443
  uuid: uuid
  alterId: 32
  cipher: auto
  # udp: true
  # tls: true
  # skip-cert-verify: true
  # network: ws
  # ws-path: /path
  # ws-headers:
  #   Host: v2ray.com
```
