### ISSUE TITLE
vmess+ws+tls config

### ISSUE THREAD

**Issue by tkkcc** [Dreamacro/clash#401]
你好,尝试连v2ray没成功,用v2rayN可以,希望大佬帮忙看看哪里配错了
```
WARN[0000] dial PROXY error: s4.bilabilax.tk:443 connect error
```

clash配置(不可用)
```
- name: v4
  type: vmess
  server: s4.bilabilax.tk
  port: 443
  uuid: d0058f92-a59e-4660-b1ba-e5173d049346
  alterId: 233
  cipher: auto
  tls: true
  #tls-hostname: s4.bilabilax.tk
  #skip-cert-verify: true
  network: ws
  ws-path: /
  ws-headers:
    Host: s4.bilabilax.tk
```

v2rayN配置(可用)
```
{
  "policy": null,
  "log": {
    "access": "",
    "error": "",
    "loglevel": "warning"
  },
  "inbounds": [
    {
      "tag": "proxy",
      "port": 10808,
      "listen": "127.0.0.1",
      "protocol": "socks",
      "sniffing": {
        "enabled": true,
        "destOverride": [
          "http",
          "tls"
        ]
      },
      "settings": {
        "auth": "noauth",
        "udp": true,
        "ip": null,
        "address": null,
        "clients": null
      },
      "streamSettings": null
    }
  ],
  "outbounds": [
    {
      "tag": "proxy",
      "protocol": "vmess",
      "settings": {
        "vnext": [
          {
            "address": "s4.bilabilax.tk",
            "port": 443,
            "users": [
              {
                "id": "d0058f92-a59e-4660-b1ba-e5173d049346",
                "alterId": 233,
                "email": "t@t.tt",
                "security": "auto"
              }
            ]
          }
        ],
        "servers": null,
        "response": null
      },
      "streamSettings": {
        "network": "ws",
        "security": "tls",
        "tlsSettings": {
          "allowInsecure": true,
          "serverName": "s4.bilabilax.tk"
        },
        "tcpSettings": null,
        "kcpSettings": null,
        "wsSettings": {
          "connectionReuse": true,
          "path": "/",
          "headers": {
            "Host": "s4.bilabilax.tk"
          }
        },
        "httpSettings": null,
        "quicSettings": null
      },
      "mux": {
        "enabled": true
      }
    },
    {
      "tag": "direct",
      "protocol": "freedom",
      "settings": {
        "vnext": null,
        "servers": null,
        "response": null
      },
      "streamSettings": null,
      "mux": null
    },
    {
      "tag": "block",
      "protocol": "blackhole",
      "settings": {
        "vnext": null,
        "servers": null,
        "response": {
          "type": "http"
        }
      },
      "streamSettings": null,
      "mux": null
    }
  ],
  "stats": null,
  "api": null,
  "dns": null,
  "routing": {
    "domainStrategy": "IPIfNonMatch",
    "rules": [
      {
        "type": "field",
        "port": null,
        "inboundTag": [
          "api"
        ],
        "outboundTag": "api",
        "ip": null,
        "domain": null
      }
    ]
  }
}
```

**Comment by Dreamacro** [comment]
skip-cert-verify: true

**Comment by Dreamacro** [comment]
mux 关闭

**Comment by tkkcc** [comment]
谢谢, 果然把mux关了就可以了

**Comment by tiancool** [comment]
> 谢谢，果然把mux关了就可以了


看不懂，新手，mux 怎么关闭？

**Comment by wensonsmith** [comment]
> > 谢谢，果然把mux关了就可以了
> 
> 看不懂，新手，mux 怎么关闭？


```
# VMess
- name: "XXXX"
  type: vmess
  server: domain.name
  port: 443
  uuid: 
  alterId: 0
  cipher: auto
  tls: true
  skip-cert-verify: true
  network: ws
  ws-opts:
    path: /ray
    headers: 
      Host: domain.name # 填写伪装域名
    mux: false
```
