### ISSUE TITLE
[Feature request]request of the same eTLD dial on different proxy

### ISSUE THREAD

**Issue by TTTPOB** [Dreamacro/clash#412]
I've noticed a statement in the sample configuration in the readme.
```yaml
# load-balance: The request of the same eTLD will be dial on the same proxy.
- name: "load-balance"
  type: load-balance
  proxies:
    - ss1
    - ss2
    - vmess1
  url: 'http://www.gstatic.com/generate_204'
  interval: 300
```

But sometimes I want to combine the speed from different proxies to get a reasonable speed. Is there a way to change the behavior of load-balance proxy groups?
