### ISSUE TITLE
内部特殊域名，不能解析

### ISSUE THREAD

**Issue by leosam1024** [Dreamacro/clash#444]
公司内部有自己的dns解析服务器，自己插上网线，电脑会自己设置dns服务器解析。
公司内部域名 xxxxno.com ，公共的dns 解析服务器都解析不了。会提示ALL DNS requst failed
因为clash的配置文件都是服务商提供的，一般不能改

能否提供一个方式，如果自己在yaml里配置的dns解析服务器都解析不了。能否用电脑默认的dns解析服务器

**Comment by Dreamacro** [comment]
clash 的配置还是能改的吧，加上自己电脑的 dns，或者关闭自定义 dns

**Comment by leosam1995** [comment]
我懂你的意思，我自己弄了一个服务器，进行clash 订阅转换。
但是有的时候，家里和公司网络环境不一致，就不能维护同一份配置文件。
关闭自定义dns或者加自己电脑的dns，都能解决。但是每次都要修改，比较麻烦

我的想法是，能否在自定义解析服务器中加一个特殊配置，增强一下功能。
只是建议
```
dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:53
  enhanced-mode: redir-host
  nameserver:
    - 114.114.114.114
    - 119.29.29.29
    - 180.76.76.76
    - 1.2.4.8
    - 223.5.5.5
    - 8.8.8.8 
    - system
  fallback:
    - tls://dns.rubyfish.cn:853
    - tls://1.0.0.1:853
    - tls://dns.google:853
```
就是有个特殊的 `  - system` 加上这个，可以替代本机的dns服务器。
这样自定义dns的功能就强大很多了
