### ISSUE TITLE
请教一下，如何设置`enhanced-mode`可以正常使用macOS下dictionary中的Wikipedia?

### ISSUE THREAD

**Issue by liby** [Dreamacro/clash#453]
- 在路由器上设置代理的话，是可以正常使用的；
- 但是如果路由器没做设置，通过电脑上的代理软件科学上网，就会出现“No entries found.”的提示；
- 查了一下，大概是因为 DNS 污染? 反正肯定是没走代理的
![image](https://user-images.githubusercontent.com/38807139/71544552-ea046080-29bb-11ea-828c-9b020a9b5ec5.png)

- 解决办法有很多，基本都推荐下载类似 proxifier 之类的软件，而后把 lookup 这个服务设置为使用代理
    - 但是强迫症又不想单纯为了使用这个功能而同时开两个软件
- 按照 [如何设置才能使 OS X 自带词典应用的中文维基恢复正常](https://www.v2ex.com/t/205818) 的某些楼层所说，Surge 下打开 enhanced-mode ，就可以正常使用 Wikipedia 了，但是我在 ClashX 下配置了一下，没有起作用；
![image](https://user-images.githubusercontent.com/38807139/71544593-6a2ac600-29bc-11ea-8678-1b52875e4845.png)

- 配置如下
```yaml
dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:53
  enhanced-mode: redir-host
  # 或 fake-ip
  # # fake-ip-range: 198.18.0.1/16 # 如果你不知道这个参数的作用，请勿修改
  # # 实验性功能 hosts, 支持通配符 (例如 *.clash.dev 甚至 *.foo.*.example.com)
  # # 静态的域名 比 通配域名 具有更高的优先级 (foo.example.com 优先于 *.example.com)
  # # 注意: hosts 在 fake-ip 模式下不生效
  # hosts:
  #   '*.clash.dev': 127.0.0.1
  #   'alpha.clash.dev': '::1'

  nameserver:
    - 1.2.4.8
    - 114.114.114.114
    - 223.5.5.5
    - tls://dns.rubyfish.cn:853
    #- https://dns.rubyfish.cn/dns-query

  fallback: # 与 nameserver 内的服务器列表同时发起请求，当规则符合 GEOIP 在 CN 以外时，fallback 列表内的域名服务器生效。
    - tls://dns.rubyfish.cn:853
    - tls://1.0.0.1:853
    - tls://dns.google:853

    #- https://dns.rubyfish.cn/dns-query
    #- https://cloudflare-dns.com/dns-query
    #- https://dns.google/dns-query
```
- 且 Surge 开启  Enhanced Mode 后， 会在菜单栏显示这一项，可供勾选
![image](https://user-images.githubusercontent.com/38807139/71544642-3603d500-29bd-11ea-9058-27c4c1f92643.png)
- 但是我在配置后，Clash 的菜单栏没有这个项目，所以我不确定我是否真的打开了  Enhanced Mode
