### ISSUE TITLE
0.17.1-19-g8757868开启fake-ip TUN时候，报socket: too many open files

### ISSUE THREAD

**Issue by NV3S** [Dreamacro/clash#494]
core：0.17.1-19-g8757868 on linux-amd64
ui：openclash v0.36.3

参数：
```
dns:
  enable: true
  ipv6: false
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  listen: 0.0.0.0:7874
##Custom DNS##
  nameserver:
  - 223.5.5.5
tun:
  enable: true
```

报错内容：
如图
![Inkedphoto_2020-02-05_15-38-48_LI (2)_Moment](https://user-images.githubusercontent.com/17755534/73821106-2e421680-482e-11ea-9fc5-81d6b4536323.jpg)
