### ISSUE TITLE
redir-host模式在某些情况下 fallback-filter 列表不生效

### ISSUE THREAD

**Issue by Mosney** [Dreamacro/clash#497]
### 使用环境：OpenWrt x86 19.07.1、[luci-app-clash](https://github.com/frainzy1477/luci-app-clash)、ISP没有劫持DNS
```
root@OP19:~# ps |grep -e  'clash -d' |grep -v grep
  393 root      117m S<   /etc/clash/clash -d /etc/clash
```
### 配置文件：
```
root@OP19:~# awk '/dns:/,/Proxy/' /etc/clash/config.yaml 
dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:5053
  enhanced-mode: redir-host
  #fake-ip-range: 198.18.0.1/16
  nameserver:
    - 127.0.0.1:6053
  fallback:
    - tls://8.8.4.4:853
  fallback-filter:
    geoip: true
    ipcidr:
      - 240.0.0.0/4
 
Proxy:
```
### DNS查询结果
```
srv :: ~ » dig gist.github.com @10.1.1.1 -p 5053

; <<>> DiG 9.11.5-P4-5.1-Debian <<>> gist.github.com @10.1.1.1 -p 5053
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 23455
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;gist.github.com.		IN	A

;; ANSWER SECTION:
gist.github.com.	139	IN	A	243.185.187.39

;; Query time: 0 msec
;; SERVER: 10.1.1.1#5053(10.1.1.1)
;; WHEN: 五 2月 07 19:39:58 CST 2020
;; MSG SIZE  rcvd: 64
```
在已有过滤名单的情况下，clash仍然返回了被污染后的地址。

OpenWrt上同时部署了[AdGuardHome](https://github.com/AdguardTeam/AdGuardHome)且clash是其唯一上游 ，通过日志可知大部分时间返回的 `gist.github.com` 都是被污染后的
<details> <summary>AdGuardHome日志页屏幕截图：</summary>

![image](https://user-images.githubusercontent.com/22477230/74027548-5a52c880-49e3-11ea-914d-7c2abd0466d0.png) 
</details>
