### ISSUE TITLE
iPhone无法显示快手app视频封面，无法播放微博视频

### ISSUE THREAD

**Issue by qiangd6** [Dreamacro/clash#507]
Hi，我的使用环境是在x86 openwrt软路由中运行clash，提供http代理服务，我的config.yml如下

```
port: 7890
socks-port: 7891
redir-port: 7892
allow-lan: true
mode: Rule
log-level: info
external-controller: 127.0.0.1:9090
secret: ""
cfw-bypass:
  - localhost
  - 127.*
  - 10.*
  - 172.16.*
  - 172.17.*
  - 172.18.*
  - 172.19.*
  - 172.20.*
  - 172.21.*
  - 172.22.*
  - 172.23.*
  - 172.24.*
  - 172.25.*
  - 172.26.*
  - 172.27.*
  - 172.28.*
  - 172.29.*
  - 172.30.*
  - 172.31.*
  - 192.168.*
  - <local>
cfw-latency-timeout: 3000
Proxy:
  - name: HKAli
    type: http
    server: 
    port: 
    username: 
    password: 
  - name: HKBD
    type: socks5
    server: 
    port: 
    username: 
    password: 
Proxy Group:
  - name: Proxy
    type: select
    proxies:
      - HKAli
      - HKBD
    _index: 0
Rule:
  - DOMAIN-KEYWORD,google,Proxy
  - MATCH,DIRECT

```
使用这个http代理，可以实现自动分流，等等，但是在iOS上的快手app中，无法显示视频的封面，和用户的头像（同一网络下，若不用clash http代理、直连则正常显示视频封面及头像）；在微博app中，只能显示视频封面，点进去无法播放视频（同一网络下，若不用clash http代理、直连则正常播放视频）

请问，是不是我的config哪里配置错了，谢谢
