### ISSUE TITLE
test outbound proxy independently by url-test policy group

### ISSUE THREAD

**Issue by RabbitYilia** [Dreamacro/clash#522]
I have two outbound proxy
Proxy:
- name: "eu"
  type: vmess
- name: "us"
  type: vmess

and two policy group
Proxy Group:
- name: "to-West"
  type: url-test
  proxies:
    - eu
    - us
   url:'bbc.com'

- name: "to-East"
  type: url-test
  proxies:
    - eu
    - us
   url:'att.com'
 
Rule:
- GEOIP,CN,DIRECT
- GEOIP,US,to-east
- GEOIP,JP,to-east
- GEOIP,EU,to-west

I'd like to achieve url-test can test load-speed by group independently,In each group,program can choose best one in group to connect remote server.But in dashboard
it shows that the latency of the proxy with the same name in different group  are same
example
group to east
US:123ms EU:222ms
group to east
US:123ms EU:222ms

but when I write config.yaml like this 

- name: "eu-to-east"
  type: vmess
- name: "eu-to-west"
  type: vmess
- name: "us-to-east"
  type: vmess
- name: "us-to-west"
  type: vmess

and two policy group
Proxy Group:
- name: "to-West"
  type: url-test
  proxies:
    - eu-to-west
    - us-to-west
   url:'bbc.com'

- name: "to-East"
  type: url-test
  proxies:
    - eu-to-east
    - us-to-east
   url:'att.com'
 
the result are different 
group to east
US:123ms EU:222ms
group to east
US:199ms EU:160ms

It seems that the clash test latency by name not by group,but if i have M zone and N outbounds,I need to set M*N outbound proxys.It's terrible.
Is there any improve plan?

By the way,Thank you for your hard working.

**Comment by Dreamacro** [comment]
Yep, It's already improved.

> I'd like to achieve url-test can test load-speed by group independently,In each group,program can choose best one in group to connect remote server.But in dashboard
> it shows that the latency of the proxy with the same name in different group are same
example

Each proxy has a field called `history`, it stores all speed test results, and the dashboard displays the latest result. So you would see the same result.

In the old clash version, each proxy group does health-check for themself. So a new feature call `Provider` solves it. Every proxy group get proxies from providers and do health-check only once. BTW, the provider can hot-reload and auto-update.

```yaml
Proxy Group:
  - name: groupA
      type: select
      use:
        - us
        - jp
  - name: groupB
      type: select
      proxies:
        - DIRECT
        - Proxy
      use:
        - us
        - jp
proxy-provider:
  us:
    type: file
    path: ./us.yaml
    health-check:
      enable: true
      interval: 36000
      url: http://www.gstatic.com/generate_204
  jp:
    type: file
    path: ./jp.yaml
    health-check:
      enable: true
      interval: 36000
      url: http://www.gstatic.com/generate_204
```
