### ISSUE TITLE
[Bug] ubuntu19.10 使用clash搭建透明代理，电视盒子无法看netflix

### ISSUE THREAD

**Issue by aaaisan** [Dreamacro/clash#529]
感谢你向 Clash Core 提交 issue！
在提交之前，请确认：

- [x] 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [x] 这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 Openclash、Koolclash 等）的特定问题
- [ ] 我已经使用 Clash core 的 dev 分支版本测试过，问题依旧存在
- [ ] 如果你可以自己 debug 并解决的话，提交 PR 吧！

请注意，如果你并没有遵照这个 issue template 填写内容，我们将直接关闭这个 issue。

我都确认过了，我要继续提交。
------------------------------------------------------------------

请附上任何可以帮助我们解决这个问题的信息，如果我们收到的信息不足，我们将对这个 issue 加上 *Needs more information* 标记并在收到更多资讯之前关闭 issue。

### clash core config

```
port: 7890

socks-port: 7891

redir-port: 7892

allow-lan: true

mode: Rule

log-level: debug

external-controller: 0.0.0.0:9090

experimental:
  ignore-resolve-fail: true

dns:
  enable: true
  ipv6: false
  enhanced-mode: redir-host
  listen: :5353

  nameserver:
     - 1.2.4.8
     - 114.114.114.114
  fallback
     - tls://dns.rubyfish.cn:853
     - tls://1.0.0.1:853
     - tls://dns.google:853
tun:
  enable: true

Proxy:
  ...
```

### Clash log

```
……
```

### 环境 Environment

* Clash Core 的操作系统 (the OS that the Clash core is running on)
ubuntu 19.10
……
* 使用者的操作系统 (the OS running on the client)
ubuntu 19.10
……
* 网路环境或拓扑 (network conditions/topology)
300M拨号网络
……
* iptables，如果适用 (if applicable)
```
iptables -t nat -A POSTROUTING -o ppp0 -j MASQUERADE
iptables -t nat -N CLASH
iptables -t nat -A CLASH -d 192.168.0.0/16 -j RETURN
iptables -t nat -A CLASH -p tcp -j REDIRECT --to-ports 7892
iptables -t nat -A PREROUTING -p tcp -j CLASH 
```
……
* ISP 有没有进行 DNS 污染 (is your ISP performing DNS pollution?)
安装了dnsmasq，使用了53端口，在配置中设上级DNS为clash，IPS对DNS无污染
……

### 说明 Description

使用树莓派4b安装ubuntu server 19.10后，安装了dnsmasq，使用53端口，在配置中设上级DNS为clash，使用clash搭建透明代理，在电脑端一切正常，但是使用小米盒子国际板看netflix会提示使用了代理！无论使用Clash Core还是Clash TUN都一样，请问改如何解决？谢谢！
