### ISSUE TITLE
[Bug] direct 转发后的连接会被视作外部连接

### ISSUE THREAD

**Issue by Rapiz1** [Dreamacro/clash#533]
### clash core config
```yaml
# Clash 的 RESTful API
external-controller: 127.0.0.1:9090
# SOCKS5 代理端口
socks-port: 1080 
# 允许局域网的连接
allow-lan: false
# 规则模式：Rule（规则） / Global（全局代理）/ Direct（全局直连）
mode: Rule

# 设置日志输出级别 (默认级别：silent，即不输出任何内容，以避免因日志内容过大而导致程序内存溢出）。
# 5 个级别：silent / info / warning / error / debug。级别越高日志输出量越大，越倾向于调试，若需要请自行开启。
log-level: warning

# 您可以将静态网页资源（如 clash-dashboard）放置在一个目录中，clash 将会服务于 `RESTful API/ui`
# 参数应填写配置目录的相对路径或绝对路径。
external-ui: yacd

Rule:
- IP-CIDR,192.168.0.0/16,DIRECT
- IP-CIDR,10.0.0.0/8,DIRECT
- IP-CIDR,172.16.0.0/12,DIRECT
- IP-CIDR,127.0.0.0/8,DIRECT
- IP-CIDR,100.64.0.0/10,DIRECT
```

### Clash log

![TIM图片20200224121540](https://user-images.githubusercontent.com/20105061/75128512-65099f00-56ff-11ea-8951-476a032bf15b.png)

### 环境 Environment

* Clash Core 的操作系统 (the OS that the Clash core is running on)
Arch Linux
* 使用者的操作系统 (the OS running on the client)
Arch Linux
* 网路环境或拓扑 (network conditions/topology)
……
* iptables，如果适用 (if applicable)
……
* ISP 有没有进行 DNS 污染 (is your ISP performing DNS pollution?)
……
* 其他
……

### 重现问题的具体布骤 Steps to Reproduce

1. allow-lan 设置为 false
2. 把一个 web dashboard 放到 external-ui
3. 浏览器设置为全部经过socks代理，访问对应的/ui

**我预期会发生……？**

正常运行
**实际上发生了什麽？**

dashborad无法连接
localhost:对应端口 refuse connection
