### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by gyzclw** [Dreamacro/clash#549]
在提交之前，请确认：

- [x] 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [x] 这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 Openclash、Koolclash 等）的特定问题
- [x] 我已经使用 Clash core 的 dev 分支版本测试过，问题依旧存在
我都确认过了，我要继续提交。

### clash core config

```
# HTTP 代理端口
port: 7890

# SOCKS5 代理端口
socks-port: 7891

# 允许局域网的连接（可用来共享代理）
allow-lan: false

# 规则模式：Rule（规则） / Global（全局代理）/ Direct（全局直连）
mode: Rule

# 设置日志输出级别 (默认级别：info，级别越高日志输出量越大，越倾向于调试)
# 四个级别：silent / info / warning / error / debug
log-level: info

# Clash 的 RESTful API
external-controller: 127.0.0.1:9090

dns:
  enable: true
  ipv6: false
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  listen: 0.0.0.0:7874
##Custom DNS##
  nameserver:
  - 223.5.5.5
tun:
  enable: true
……
```

### Clash log

```
# Logcat on 2020-03-03 11:14:28
1583205270721 INFO [TCP] 172.31.255.253:40394 --> 54.191.19.206 match Match using FINAL[x1.0 香港 - 中转1]
1583205279159 INFO [UDP] 172.31.255.253:57697 --> 13.112.35.82 match Match using FINAL[x1.0 香港 - 中转1]
1583205280510 INFO [UDP] 172.31.255.253:54231 --> 13.112.35.82 match Match using FINAL[x1.0 香港 - 中转1]
1583205291188 INFO [UDP] 172.31.255.253:56585 --> 13.112.35.82 match Match using FINAL[x1.0 香港 - 中转1]
1583205300368 INFO [UDP] 172.31.255.253:63189 --> 13.112.35.82 match Match using FINAL[x1.0 香港 - 中转1]
1583205335989 DEBUG [DNS] data.mistat.xiaomi.com --> 118.26.252.165
1583205336043 INFO [TCP] 172.31.255.253:38022 --> data.mistat.xiaomi.com match DomainSuffix using DIRECT

```

### 环境 Environment

* Clash Core 的操作系统 (the OS that the Clash core is running on)
Android 手机中clash for android
* 使用者的操作系统 (the OS running on the client)
switch
* 网路环境或拓扑 (network conditions/topology)
……
* iptables，如果适用 (if applicable)
……
* ISP 有没有进行 DNS 污染 (is your ISP performing DNS pollution?)
……
* 其他
……

### 重现问题的具体布骤 Steps to Reproduce

1. [使用clash for andorid 连接上clash 的ss 节点代理]
2. [通过vpn 热点共享给switch,马里奥制造2 联机,]

**我预期会发生……？**

正常联机匹配
**实际上发生了什麽？**

报nat 穿透失败,使用shadowsocks android udp 转发可以联机
![WechatIMG22](https://user-images.githubusercontent.com/10341322/75740132-dcfc4880-5d41-11ea-86e0-bb8860c20e7f.jpeg)
![WechatIMG21](https://user-images.githubusercontent.com/10341322/75740138-df5ea280-5d41-11ea-9e41-095dffb22ef0.jpeg)

### 可能的解决方案 Possible Solution
fake-ip 前置失败,怎么配置
