### ISSUE TITLE
[Bug]已普通用户运行clash的tun模式版本，提示权限不够

### ISSUE THREAD

**Issue by easonjim** [Dreamacro/clash#559]
感谢你向 Clash Core 提交 issue！
在提交之前，请确认：

- [x] 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [x] 这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 Openclash、Koolclash 等）的特定问题
- [x] 我已经使用 Clash core 的 dev 分支版本测试过，问题依旧存在
- [x] 如果你可以自己 debug 并解决的话，提交 PR 吧！

请注意，如果你并没有遵照这个 issue template 填写内容，我们将直接关闭这个 issue。

我都确认过了，我要继续提交。

------------------------------------------------------------------

请附上任何可以帮助我们解决这个问题的信息，如果我们收到的信息不足，我们将对这个 issue 加上 *Needs more information* 标记并在收到更多资讯之前关闭 issue。

### clash core config

```
dns:
  enable: true
  listen: 0.0.0.0:53
  enhanced-mode: fake-ip
  nameserver:
    - 114.114.114.114

experimental:
  interface-name: en0 # your interface-name

tun:
  enable: true
```

### Clash log

```
level=error msg="Start Tun interface error: operation not permitted"
```

### 环境 Environment

* Clash Core 的操作系统 (the OS that the Clash core is running on)
centos7.4
* 使用者的操作系统 (the OS running on the client)
centos7.4
* 网路环境或拓扑 (network conditions/topology)
/
* iptables，如果适用 (if applicable)
/
* ISP 有没有进行 DNS 污染 (is your ISP performing DNS pollution?)
/
* 其他
/

### 重现问题的具体布骤 Steps to Reproduce

1. [First Step]
2. [Second Step]
3. ……

**我预期会发生……？**

**实际上发生了什麽？**

### 更多信息 More Information
clash版本：Clash v0.18.0-8-g68b82c9 linux amd64
