### ISSUE TITLE
[Feature]对Rule功能和fake-ip功能的建议

### ISSUE THREAD

**Issue by 83390785** [Dreamacro/clash#571]
> 开发者你好，我从使用者的角度对clash的**Rule功能**和**fake-ip功能**提出了一些建议，这增加了clash的复杂程度，我不懂编程，不知道实现的困难程度以及系统资源消耗的变化，只是从个人使用中发现的一些问题和需求出发提供一些建议，希望开发者能够参考，如果能采纳就太好了。

# 一、Rule功能

##  1、问题

我将clash安装到旁路由openwrt系统中作为**透明代理**，使用**GFW规则模式**。

> **GFW规则模式**：MATCH为DIRECT的规则模式，类似：

```
- DOMAIN-SUFFIX,google.com,Proxy
- DOMAIN-KEYWORD,google,Proxy
- DOMAIN,google.com,Proxy
- MATCH,DIRECT
```

**问题1：**某台主机希望使用**国内外分流规则模式**，但是目前clash无法做到单独为某台主机设置此类规则（可以做到某台主机直连或者全局代理）。

> **国内外分流规则模式**：MATCH为Proxy的规则模式，类似：

```
- DOMAIN-SUFFIX,baidu.com,DIRECT
- DOMAIN-KEYWORD,baidu,DIRECT
- DOMAIN,baidu.com,DIRECT
- MATCH,Proxy
```

**问题2：**在问题1中，尝试通过设置http或者socks5代理的方式实现，但是目前clash的http和socks5端口无法单独设置规则。

**问题3：**目前规则写在配置文件中，如果**规则与配置分离**，设置单独的规则文件，修改配置、订阅规则将更加灵活。

## 2、解决设想

从主页的介绍看到，目前clash的规则有以下几种：

```yaml
- DOMAIN-SUFFIX,google.com,auto
- DOMAIN-KEYWORD,google,auto
- DOMAIN,google.com,auto
- SRC-IP-CIDR,192.168.1.201/32,DIRECT
- IP-CIDR,127.0.0.0/8,DIRECT
- GEOIP,CN,DIRECT
- DST-PORT,80,DIRECT
- SRC-PORT,7777,DIRECT
- MATCH,auto
```

这些规则可以分为**来源**和**去向**两类，**MATCH**规则作为一个兜底的规则，可以同时匹配来源和去向两种情况。

#### 	去向规则：

```yaml
- DOMAIN-SUFFIX
- DOMAIN-KEYWORD
- DOMAIN
- IP-CIDR
- DST-PORT
- MATCH
```

#### 	来源规则：

```
- SRC-IP-CIDR
- SRC-PORT
- MATCH
```

一般情况下使用的规则主要是**去向规则**，包括在网上分享的也都是去向规则。

而来源规则是一种**例外**的规则，比如默认情况下是**GFW规则模式**进行代理分流，但是局域网内的某一台主机想要直连或者全局代理，这种情况下就需要用到来源规则，在当前clash的配置文件中，可以加上

```yaml
- SRC-IP-CIDR,192.168.1.201/32,DIRECT
- SRC-IP-CIDR,192.168.1.202/32,Proxy
```

即可，但是**如果想要将某台主机设置为国内外分流规则模式，目前似乎没有办法做到。**

针对这种情况，可以把现行的规则分为去向规则与来源规则两级，比如叫做**Rule-DST**和**Rule-SRC**。

### (1)  Rule-DST：

在Rule-DST规则中，引入规则组（Rule-DST Group）的概念，可以参照配置文件中Proxy和Proxy Group参数的结构，例如：

```yaml
Rule-DST：
  - name: "GFW"
    Rule: 
      - DOMAIN-SUFFIX,google.com,auto
      - DOMAIN-KEYWORD,google,auto
      - DOMAIN,google.com,auto
      - IP-CIDR,127.0.0.0/8,auto
      - DST-PORT,80,auto
      - MATCH,DIRECT
  - name: "CN"
    Rule:
      - DOMAIN-SUFFIX,baidu.com,DIRECT
      - DOMAIN-KEYWORD,baidu,DIRECT
      - DOMAIN,baidu.com,DIRECT
      - IP-CIDR,127.0.0.0/8,DIRECT
      - GEOIP,CN,DIRECT
      - DST-PORT,80,DIRECT
      - MATCH,auto
```

#### 	DIRECT规则组

DIRECT是一个特殊的代理组（Proxy Group），也可以作为一个特殊的规则组（Rule-DST Group）

即：

```yaml
- name: "DIRECT"
  Rule: 
    - MATCH,DIRECT
```

#### 	规则组（Rule-DST Group）文件化

更进一步，可以将**规则组（Rule-DST Group）文件化**，而规则组（Rule-DST Group）文件中的代理名称与配置文件中代理名称的冲突可以通过在配置文件中进行字符串**映射**来解决，例如：

> 以代理组文件的代理名称为英文小写，配置文件中为英文大写为例

```yaml
Rule-DST：
  - name: "GFW"
    Rule:
    File:/路径/GFW.list
    Map:
      - DIRECT = direct
      - PROXY = proxy
      - AUTO = auto
  - name: "CN"
    Rule:
    File:/路径/CN.list
    Map:
      - DIRECT = direct
      - PROXY = proxy
      - AUTO = auto
```

### (2)  Rule-SRC：

Rule-SRC规则是clash最终依据的规则，Rule-SRC规则根据Rule-DST规则来编写，例如：

```yaml
Rule-DST：	
  - SRC-IP-CIDR,192.168.1.201/32,DIRECT
  - SRC-IP-CIDR,192.168.1.202/32,CN
  - SRC-PORT,7777,DIRECT
  - SRC-PORT,8888,CN
  - MATCH,GFW
```

### port 和 socks-port参数

HTTP及SOCKS5这两个代理端口遵循的规则变得不明确，这两个代理端口也是一种流量来源，可以在Rule-SRC规则中为其增加规则，例如：

```yaml
Rule-DST：
  - SRC-IP-CIDR,192.168.1.201/32,DIRECT
  - SRC-IP-CIDR,192.168.1.202/32,CN
  - SRC-PORT,7777,DIRECT
  - SRC-PORT,8888,CN
  - HTTP,GFW
  - SOCKS5,CN
  - MATCH,GFW
```

为HTTP代理端口及SOCKS5代理端口指定规则也可以解决**问题2**。

### mode参数

mode参数受到影响，其本来的3个选项，Rule，Global，Direct指代不明，可以修改为调整Rule-SRC规则中的MATCH规则调用的Rule-DST规则组（Rule-DST Group），其选项可以根据Rule-DST规则组（Rule-DST Group）改变，例如：

```
GFW
CN
DIRECT
GLOBAL
```

###  dashboard中的规则界面

规则界面显示的规则可以调整为显示Rule-SRC规则中的MATCH规则调用的Rule-DST规则组（Rule-DST Group），例如：

```yaml
Rule-DST：
  - SRC-IP-CIDR,192.168.1.201/32,DIRECT
  - SRC-IP-CIDR,192.168.1.202/32,CN
  - SRC-PORT,7777,DIRECT
  - SRC-PORT,8888,CN
  - HTTP,GFW
  - SOCKS5,CN
  - MATCH,GFW
```

此时显示GFW规则组（Rule-DST Group）中的规则。

# 二、fake-ip功能

## 1、问题

**问题4：**在fake-ip模式下，因添加规则或其他原因重启clash后，域名与fake-ip的映射丢失，在dns过期前，之前访问过的域名**无法连接**。

**问题5：**目前fake-ip模式有一个fake-ip-filter白名单参数，在该参数下的域名通过正常dns解析，该参数似乎是为了解决[NTP服务器](https://github.com/Dreamacro/clash/issues/258)等问题。若改成**黑名单模式**，则可以忽略此类问题并提升性能与体验。

**黑名单模式的优点：**

> 黑名单模式：仅在黑名单中的域名通过fake-ip解析，其余域名正常dns解析。

1、配合**GFW规则模式**，则可以忽略GFW列表之外的，特别是国内网站在fake-ip下的一些问题。即使出问题，也仅在GFW列表中，数量有限。

2、在白名单模式下，直连的网站也会进行fake-ip解析，在fake-ip解析之后，会继续进行正常的DNS解析，比正常情况多了一次fake-ip的解析，**造成性能损失**（可能可以忽略不计）。

3、fake-ip缓存持久化之后，在白名单模式下，缓存列表很大，而采用黑名单模式，因为仅黑名单中的域名进行fake-ip解析，缓存列表最多与黑名单数量相同，**缓存列表比白名单模式减小很多，减少性能损耗**。

4、如果需要临时关闭clash，黑名单之外的域名（大部分情况为国内网站）访问不受影响。

### (1)  fake-ip持久化

这个功能好像已经[在开发或者计划中了](https://github.com/Dreamacro/clash/issues/181#issuecomment-4929018538)，感谢开发者。

### (2)  fake-ip黑名单模式

> fake-ip黑名单模式最适合GFW规则模式，而对国内外分流规则模式来说不是一个完美的方法。

不需要特别设置一个黑名单列表，只需要将需要代理的域名规则中加上一个fake-ip的参数，对加上参数的域名进行fake-ip解析即可。例如：

```yaml
- DOMAIN-SUFFIX,google.com,auto,fake-ip
- DOMAIN-KEYWORD,google,Proxy,fake-ip
- DOMAIN,google.com,Proxy,fake-ip
```

但是，这样添加太过繁琐，且不利于调用外部规则，可以将fake-ip与代理组（Proxy Group）进行关联绑定，Proxy Group设置中加一个**新的参数——fake-ip**，例如：

```yaml
Proxy Group:
  - name: "auto"
    type: url-test
    proxies:
      - ss1
      - ss2
      - vmess1
    url: 'http://www.gstatic.com/generate_204'
    interval: 300
    fake-ip: true
  - name: "Proxy"
    type: select
    proxies:
      - ss1
      - ss2
      - vmess1
      - auto
     fake-ip: true
```

对fake-ip参数设置为true的代理组，其关联的域名规则的域名进行fake-ip解析。
