### ISSUE TITLE
intnerval: 300 里面的300 单位是什么？ms? seconds? mins?

### ISSUE THREAD

**Issue by caesarjing** [Dreamacro/clash#580]
```
  - name: "auto"
    type: url-test
    proxies:
      - ss1
      - ss2
      - vmess1
    url: 'http://www.gstatic.com/generate_204'
    interval: 300
```

请问config这里的`interval`的单位是什么？
