### ISSUE TITLE
File must have a `proxies` field"

### ISSUE THREAD

**Issue by sandianyue** [Dreamacro/clash#596]
当我尝试使用新的特性proxy-provider时 添加配置文件时总是报错 _File must have a `proxies` field"_  我对照了无数遍 并没有发现哪里有错和模板相比 我在您的https://github.com/Dreamacro/clash/blob/master/adapters/provider/provider.go
中翻到了这么一行
**if schema.Proxies == nil {
		return nil, errors.New("File must have a `proxies` field")**
但是没有理解

我的配置如下
```
- name: ✈ 稳定
    type: select
    use:
      - test
    proxies:
      - DIRECT
      
proxy-provider: 
  test:
    type: file
    path: /data/data/com.github.kr328.clash/files/profiles/test.yaml
    health-check:
        enable: true
        url: http://www.gstatic.com/generate_204
        interval: 300
```
ps：我用的还是上一版内核 所以还是proxy-provider而不是proxy-providers
