### ISSUE TITLE
[Bug]ClashX 按照模板添加Trojan配置后,UI中不显示Trojan的节点

### ISSUE THREAD

**Issue by kocx2046** [Dreamacro/clash#598]
感谢你向 Clash Core 提交 issue！
在提交之前，请确认：

- [x] 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [x] 这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 Openclash、Koolclash 等）的特定问题
- [ ] 我已经使用 Clash core 的 dev 分支版本测试过，问题依旧存在
- [ ] 如果你可以自己 debug 并解决的话，提交 PR 吧！

请注意，如果你并没有遵照这个 issue template 填写内容，我们将直接关闭这个 issue。

我都确认过了，我要继续提交。

------------------------------------------------------------------

请附上任何可以帮助我们解决这个问题的信息，如果我们收到的信息不足，我们将对这个 issue 加上 *Needs more information* 标记并在收到更多资讯之前关闭 issue。

### clash core config

```
- name: "49HSDtrojan"
  type: trojan
  server: example.xyz
  port: 443
  password: mypasswd
  udp: true
  sni: example.xyz
  alpn:
    - h2
    - http/1.1
  skip-cert-verify: true
# url-test 通过指定的 URL 测试并选择延迟最低的节点
- name: "自动节点选择"
  type: url-test
  proxies:
    - "HostDare"
    - "49HSDtrojan"
    - "BWG"
    - "GIGS"
    - "GoogleTrojan"
  url: 'http://www.gstatic.com/generate_204'
  interval: 300

# 代理节点选择
- name: "PROXY"
  type: select
  proxies:
    - "自动节点选择"
    - "HostDare"
    - "49HSDtrojan"
    - "BWG"
    - "GIGS"
    - "GoogleTrojan"
……
```

### Clash log

```
……
```

### 环境 Environment

* Clash Core 的操作系统 (the OS that the Clash core is running on)
……
* 使用者的操作系统 (the OS running on the client)
……
* 网路环境或拓扑 (network conditions/topology)
……
* iptables，如果适用 (if applicable)
……
* ISP 有没有进行 DNS 污染 (is your ISP performing DNS pollution?)
……
* 其他
……

### 重现问题的具体布骤 Steps to Reproduce

1. 按照本项目提供的Trojan模板添加Trojan配置
2. Trojan在别的代理软件中可正常连接，翻墙
3. ClashX 能ping到新配置的Trojan的节点(自动选择有时候会选到)
4. 但是列表UI中无法显示：
<img width="410" alt="Screen Shot 2020-03-24 at 1 39 37 AM" src="https://user-images.githubusercontent.com/59362011/77346063-91e9ba00-6d70-11ea-8019-f2c3c49d4925.png">

**我预期会发生……？**

**实际上发生了什麽？**
