### ISSUE TITLE
大佬您好 在#596中并未解决 被close了 所以新开一个issue（File must have a proxies field）

### ISSUE THREAD

**Issue by sandianyue** [Dreamacro/clash#599]
当我尝试使用新的特性proxy-provider时 添加配置文件时总是报错 File must have a proxies field" 我对照了无数遍 并没有发现哪里有错和模板相比 我在您的https://github.com/Dreamacro/clash/blob/master/adapters/provider/provider.go
中翻到了这么一行
```
if schema.Proxies == nil {
return nil, errors.New("File must have a proxies field")
```
但是没有理解

我的配置如下：
**config.yaml**里proxy-provider相关字段：
```
- name: ✈ 稳定
    type: select
    use:
      - test
    proxies:
      - DIRECT
      
proxy-provider: 
  test:
    type: file
    path: /data/data/com.github.kr328.clash/files/profiles/test.yaml
    health-check:
        enable: true
        url: http://www.gstatic.com/generate_204
        interval: 300
```
**test.yaml：**
```
proxies:
  - {name: 1, server: 1.1.1.1, port: 34119, type: ss, cipher: rc4-md5, password: 3M3duq}
  - {name: 2, server: 1.1.1.2, port: 34119, type: ss, cipher: rc4-md5, password: 3M3duq}
  - {name: 3, server: 1.1.1.3, port: 35119, type: ss, cipher: rc4-md5, password: 3M3duq}
  - {name: 4, server: 1.1.1.4, port: 35119, type: ss, cipher: rc4-md5, password: 3M3duq}

```
一开始我以为是test.yaml目录的问题 以为是sdcard里权限不够（不知道如何调整权限） 遂将它移动到/data/data/下 赋权777 可还是报错
昨天忘了贴上来test.yaml导致
https://github.com/Dreamacro/clash/issues/596#issuecomment-602713378
@CyberKoo 大佬以为是test.yaml缺失proxies字段

因为没有经历过closed issue没解决是否还能继续回复 遂上午回复解释8小时无响应后再发了个这个新issue 不知道算不算重复 希望没有违issue规矩吧 见谅大佬：）
