### ISSUE TITLE
[Feature] Specify Default Proxy in Proxy-Group

### ISSUE THREAD

**Issue by luvletter2333** [Dreamacro/clash#600]
您好，请问能否在Proxy-Group中加入default-proxy字段，而不是默认选取第一个？

```
  - name: Proxy
    type: select
    proxies:
      - ss1
      - ss2
      - vmess1
      - auto
    default: (optional)
      - auto
```

**Comment by athrunsun** [comment]
支持。现在`mode`为`GLOBAL`时实际上是`DIRECT`吧？因为`GLOBAL`是一个Selector，而`now`默认是`DIRECT`，需要手动调用API切换到其它proxy。我说的对吗？

**Comment by luvletter2333** [comment]
> 支持。现在`mode`为`GLOBAL`时实际上是`DIRECT`吧？因为`GLOBAL`是一个Selector，而`now`默认是`DIRECT`，需要手动调用API切换到其它proxy。我说的对吗？

这其实是我也想说的一个Feature，但是我的原意是设定Proxy-Group的default代理，这是在Rule模式下的。
我也支持你的看法，现在GLOBAL模式下默认选到的是DIRECT，我认为可以在config里面加上一个默认选择
```
  - name: Main-Proxy
    type: select
    proxies:
      - ss1
      - ss2
      - vmess1
      - auto
    default: (optional)
      - auto
    global-default: true (optional)

  - name: Forward-Proxy
    type: select
    proxies:
      - ss3
      - ss4
      - auto
    default: (optional)
      - ss3
# 在这里就不指定global-default了
```

```
- global-default: Main-Proxy
```
