### ISSUE TITLE
在配置文件中添加 external-ui 选项不生效[Bug]

### ISSUE THREAD

**Issue by Billin9** [Dreamacro/clash#603]
感谢你向 Clash Core 提交 issue！
在提交之前，请确认：

- [x] 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [x] 这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 Openclash、Koolclash 等）的特定问题
- [ ] 我已经使用 Clash core 的 dev 分支版本测试过，问题依旧存在
- [ ] 如果你可以自己 debug 并解决的话，提交 PR 吧！

请注意，如果你并没有遵照这个 issue template 填写内容，我们将直接关闭这个 issue。

我都确认过了，我要继续提交。
------------------------------------------------------------------

请附上任何可以帮助我们解决这个问题的信息，如果我们收到的信息不足，我们将对这个 issue 加上 *Needs more information* 标记并在收到更多资讯之前关闭 issue。

### clash core config

```
# HTTP 代理端口
port: 1087

# SOCKS5 代理端口
socks-port: 1080

# Linux 和 macOS 的 redir 代理端口 (如需使用此功能，请取消注释)
# redir-port: 7892

# 允许局域网的连接（可用来共享代理）
allow-lan: false

# 规则模式：Rule（规则） / Global（全局代理）/ DIRECT（全局直连）
mode: Rule

# 设置日志输出级别 (默认级别：silent，即不输出任何内容，以避免因日志内容过大而导致程序内存溢出）。
# 5 个级别：silent / info / warning / error / debug。级别越高日志输出量越大，越倾向于调试，若需要请自行开启。
log-level: silent

# clash 的 RESTful API
external-controller: 127.0.0.1:9090

# 这个地方写编译成静态资源的路径，可以是相对路径或绝对路径 然后用扩展配置的地址 (`external-controller`) + /ui 访问
# 例如：http://127.0.0.1:9090/ui
external-ui: ui

# RESTful API 的口令 (可选)
# secret: ""

# experimental feature
experimental:
  ignore-resolve-fail: true # 忽略 DNS 解析失败，默认值为 true
  interface-name: en0

# authentication of local SOCKS5/HTTP(S) server
# authentication:
#  - "user1:pass1"
#  - "user2:pass2"

tun:
  enable: true

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:53
  enhanced-mode: redir-host
  # enhanced-mode: fake-ip
  # fake-ip-range: 198.18.0.1/16
  nameserver:
    - 114.114.114.114
    - 223.5.5.5
    - tls://dns.rubyfish.cn:853 # dns over tls
    - https://1.1.1.1/dns-query # dns over https
    - 1.2.4.8
  fallback: 
    - tcp://1.1.1.1
    - tls://dns.rubyfish.cn:853
    - tls://dns.google
  fallback-filter:
    geoip: true # default
    ipcidr: # ips in these subnets will be considered polluted
      - 240.0.0.0/4
```

### Clash log

```
……
```

### 环境 Environment

* Clash Core 的操作系统 (the OS that the Clash core is running on)

macOS Catalina 10.15.3

* 使用者的操作系统 (the OS running on the client)

macOS Catalina 10.15.3

* 网路环境或拓扑 (network conditions/topology)
……
* iptables，如果适用 (if applicable)
……
* ISP 有没有进行 DNS 污染 (is your ISP performing DNS pollution?)
……
* 其他
……

### 重现问题的具体布骤 Steps to Reproduce

1. 编译 [yacd](https://github.com/haishanh/yacd), 这是一个第三方的 clash web UI
2. 将编译好的代码放入 `config.yaml` 同级目录下, 将代码的目录重命名为 `ui`

![image](https://user-images.githubusercontent.com/15778311/77718678-760b4000-701e-11ea-9f93-2d9a05053db4.png)

3. `config.yaml` 配置文件指定 ui 目录: `external-ui: ui`

4. 访问 http://127.0.0.1:9090/ui 后看到的是默认的 clash-dashboard

**我预期会发生……？**

我想看到的是
![image](https://user-images.githubusercontent.com/15778311/77718943-1b261880-701f-11ea-9a64-a4ef833b2d54.png)

**实际上发生了什麽？**

实际看到的是
![image](https://user-images.githubusercontent.com/15778311/77719053-51639800-701f-11ea-991f-4ad9fdef382d.png)
