### ISSUE TITLE
[Bug] Failed to start Redir UDP Listener: protocol not available

### ISSUE THREAD

**Issue by fanvinga** [Dreamacro/clash#609]
感谢你向 Clash Core 提交 issue！
在提交之前，请确认：

- [x] 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [x] 这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 Openclash、Koolclash 等）的特定问题
- [x] 我已经使用 Clash core 的 dev 分支版本测试过，问题依旧存在
- [] 如果你可以自己 debug 并解决的话，提交 PR 吧！

请注意，如果你并没有遵照这个 issue template 填写内容，我们将直接关闭这个 issue。

我都确认过了，我要继续提交。

------------------------------------------------------------------

请附上任何可以帮助我们解决这个问题的信息，如果我们收到的信息不足，我们将对这个 issue 加上 *Needs more information* 标记并在收到更多资讯之前关闭 issue。

### clash core config

```
port: 1081
socks-port: 1080
redir-port: 1082
allow-lan: true
mode: Rule
log-level: debug
external-controller: 0.0.0.0:9090
secret: 'fanvinga'
dns:
  enable: true
  listen: 0.0.0.0:55
  enhanced-mode: redir-host
  nameserver:
    - 119.29.29.29
    - 223.5.5.5
experimental:
  interface-name: eth0
```

### Clash log

```
INFO[0000] RESTful API listening at: 0.0.0.0:9090
WARN[0000] Failed to start Redir UDP Listener: protocol not available
INFO[0000] Redir proxy listening at: :1082
INFO[0000] DNS server listening at: 0.0.0.0:55
INFO[0000] HTTP proxy listening at: :1081
INFO[0000] SOCKS proxy listening at: :1080
```

### 环境 Environment

* Clash Core 的操作系统 (the OS that the Clash core is running on)
```
DDWrt (Linux on ARMv7 CPU with sh)
```

* iptables，如果适用 (if applicable)
```
iptables -t nat -N Clash
iptables -t nat -A PREROUTING -j Clash
iptables -t nat -A Clash -d 192.168.0.0/16 -j RETURN
iptables -t nat -A Clash -p tcp -s 192.168.1.21 -j REDIRECT --to-ports 1082
iptables -t nat -A Clash -p udp -m udp -s 192.168.1.21 -j TPROXY--to-ports 1082
```

### 重现问题的具体布骤 Steps to Reproduce

使用以上的配置文件在拥有armv7的CPU的Linux中启动0.19.0版本的clash-core

**我预期会发生……？**

一切工作正常并且redir-port可以接受TPROXY流量

**实际上发生了什麽？**

启动时发生报错

### 可能的解决方案 Possible Solution
https://github.com/slackhq/nebula/issues/32
