### ISSUE TITLE
[提问] Windows下proxy-providers的文件路径应该怎么写 ？

### ISSUE THREAD

**Issue by Mosney** [Dreamacro/clash#640]
感谢你向 Clash Core 提交 issue！
在提交之前，请确认：

- [x] 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [x] 这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 Openclash、Koolclash 等）的特定问题
- [ ] 我已经使用 Clash core 的 dev 分支版本测试过，问题依旧存在
- [ ] 如果你可以自己 debug 并解决的话，提交 PR 吧！

请注意，如果你并没有遵照这个 issue template 填写内容，我们将直接关闭这个 issue。

我都确认过了，我要继续提交。

------------------------------------------------------------------

请附上任何可以帮助我们解决这个问题的信息，如果我们收到的信息不足，我们将对这个 issue 加上 *Needs more information* 标记并在收到更多资讯之前关闭 issue。

### clash core config

```
clash-test|⇒ cat ./cfg.yaml
port: 17890
socks-port: 17891
allow-lan: true
mode: Rule
log-level: debug
proxies:
  - name: Shadowsocks
    type: socks5
    server: 127.0.0.1
    port: 1080
proxy-providers:
 test:
   type: file
   path: ./2.yml
   health-check:
     enable: true
     interval: 36000
     url: http://www.gstatic.com/generate_204
proxy-groups:
  - name: Proxy
    type: select
    proxies:
      - Shadowsocks
rules:
  - 'MATCH,DIRECT'
```

```
clash-test|⇒ cat ./2.yaml
proxies:
  - name: Shadowsocks
    type: socks5
    server: 127.0.0.1
    port: 1080
```
### Clash log

```
clash-test|⇒ ./clash -f ./cfg.yaml
INFO[0000] Start initial provider test
FATA[0000] Parse config error: File must have a `proxies` field
```

### 环境 Environment

* Clash Core 的操作系统 (the OS that the Clash core is running on)
Windows 10 WSL Debian 10 
```
clash-test|⇒ uname -a
Linux Vosrto3470 4.4.0-17763-Microsoft #864-Microsoft Thu Nov 07 15:22:00 PST 2019 x86_64 GNU/Linux
```

### 说明 Description

请问proxy-providers是如何使用的呢？使用最小化配置文件了，还是提示配置文件必须有proxies块，注释掉proxy-providers块是可以正常运行的。

**Comment by Mosney** [comment]
蠢了蠢了，文件名搞错了

**Comment by Mosney** [comment]
请求帮助：Windows下的文件路径怎么写？
刚试了试下述绝对路径报错"Parse config error: yaml: line 14: found unknown escape character"
```
proxy-providers:
 test:
   type: file
   path: "D:\clash-test\2.yaml"
```
改成如下所示又会报" level=fatal msg="Parse config error: File must have a `proxies` field"
```
proxy-providers:
 test:
   type: file
   path: ./2.yaml
```

**Comment by Fndroid** [comment]
绝对路径斜杠反了

相对路径也没问题的，检查下是不是空文件吧

**Comment by Mosney** [comment]
> 绝对路径斜杠反了
> 
> 相对路径也没问题的，检查下是不是空文件吧

D:\clash-test\2.yaml 这是按Shift右键直接复制的路径，在Windows下难道不应该按Windows的逻辑来？相对路径这里已经检查过配置文件没问题，如同上面的最开始说的最小化配置文件一样：
```
clash-test|⇒ cat ./2.yaml
proxies:
  - name: Shadowsocks
    type: socks5
    server: 127.0.0.1
    port: 1080
```
突然想到一种可能，Windows与Linux换行符不同，明天再测试一下。
