### ISSUE TITLE
[使用不当]redir模式Android系统微信视频通话异常

### ISSUE THREAD

**Issue by Alice-space** [Dreamacro/clash#655]
感谢你向 Clash Core 提交 issue！
在提交之前，请确认：

- [ ] 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [x] 这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 Openclash、Koolclash 等）的特定问题
- [ ] 我已经使用 Clash core 的 dev 分支版本测试过，问题依旧存在
- [ ] 如果你可以自己 debug 并解决的话，提交 PR 吧！

请注意，如果你并没有遵照这个 issue template 填写内容，我们将直接关闭这个 issue。

我都确认过了，我要继续提交。

------------------------------------------------------------------

请附上任何可以帮助我们解决这个问题的信息，如果我们收到的信息不足，我们将对这个 issue 加上 *Needs more information* 标记并在收到更多资讯之前关闭 issue。

### clash core config

```
port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: 0.0.0.0:9090

redir-port: 7892
dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:53
  enhanced-mode: redir-host
  nameserver:
     - 114.114.114.114
     - 223.5.5.5
  fallback:
     - tls://dns.rubyfish.cn:853
     - 8.8.8.8

cfw-bypass:
  - qq.com
  - music.163.com
  - "*.music.126.net"
  - localhost
  - 127.*
  - 10.*
  - 172.16.*
  - 172.17.*
  - 172.18.*
  - 172.19.*
  - 172.20.*
  - 172.21.*
  - 172.22.*
  - 172.23.*
  - 172.24.*
  - 172.25.*
  - 172.26.*
  - 172.27.*
  - 172.28.*
  - 172.29.*
  - 172.30.*
  - 172.31.*
  - 192.168.*
  - <local>
cfw-latency-timeout: 5000
Proxy:
***(无udp)
Proxy Group:
***
```

### 环境 Environment

* Clash Core 的操作系统 (the OS that the Clash core is running on)
debian buster
* 使用者的操作系统 (the OS running on the client)
windows 
* 网路环境或拓扑 (network conditions/topology)
```
主路由(192.168.123.1)<---clash作为旁路网关(192.168.123.23)
主路由(192.168.123.1)<---AP
```
* iptables，如果适用 (if applicable)
```
sudo iptables -t nat -N Clash
sudo iptables -t nat -A Clash -d 192.168.123.0/24 -j RETURN
sudo iptables -t nat -A Clash -p tcp -j REDIRECT --to-ports 7892
sudo iptables -t nat -A PREROUTING -p tcp -j Clash
```

### 说明 Description

进行了几次实验
- 网关设为旁路由时，视频通话可以接通，对方不能看见我动，我可以看见对方动
- 网关设为主路由时，视频通话可以接通，正常
- 移动数据网络，正常
- 尝试添加udp
```
sudo iptables -t nat -N Clashudp
sudo iptables -t nat -A Clashudp -d 192.168.123.0/24 -j RETURN
sudo iptables -t nat -A Clashudp -p udp -j REDIRECT --to-ports 7892
sudo iptables -t nat -A PREROUTING -p udp -j Clashudp
```
出现形式如下回环风暴
```
192.168.123.23:<random port>--->192.168.123.23:7892 （udp）
```
- 与远端服务器使用`netcat`进行udp连通性测试（旁路由作为网关）正常

**Comment by ZiGmaX809** [comment]
可参考以下规则，尝试将udp数据绕过clash并过滤DNS监听：

`#!/bin/sh
proxy_port=7892
lan_ip=192.168.2.1
ssh_port=22

# ports redirect for clash except port 22 for ssh connection
iptables -t nat -A PREROUTING -p tcp --dport $ssh_port -j ACCEPT

# new
iptables -t nat -N CLASH
iptables -t nat -A CLASH -d 192.168.0.0/16 -j RETURN
iptables -t nat -A CLASH -d 10.0.0.0/8 -j RETURN
iptables -t nat -A CLASH -d 127.0.0.0/8 -j RETURN
iptables -t nat -A CLASH -d 169.254.0.0/16 -j RETURN
iptables -t nat -A CLASH -d 172.16.0.0/12 -j RETURN
iptables -t nat -A CLASH -d 224.0.0.0/4 -j RETURN
iptables -t nat -A CLASH -d 240.0.0.0/4 -j RETURN

# redirect to Clash and except udp
iptables -t nat -A CLASH -p tcp -j REDIRECT --to-ports $proxy_port
iptables -t nat -A PREROUTING ! -p udp -j CLASH

# DNS
iptables -t nat -I PREROUTING -p udp -m udp -d $lan_ip --dport 53 -j DNAT --to-destination $lan_ip:55`

**Comment by Alice-space** [comment]
谢谢你！
不过我好像找到了解决方案
原因在于微信音视频貌似会尝试P2P穿透
参考[#432 ]去时流量走旁路由，回来的流量直连了
导致所有包丢失
iptables添加如下规则，nat更改源地址，让回包发送至旁路由,由旁路由转发至终端
```
sudo iptables -t nat -A POSTROUTING -s 192.168.123.0/24 -o enp0s31f6 -j MASQUERADE
```

**Comment by Alice-space** [comment]
> 可参考以下规则，尝试将udp数据绕过clash并过滤DNS监听：
> 
> ```shell
> #!/bin/sh
> proxy_port=7892
> lan_ip=192.168.2.1
> ssh_port=22
> 
> # ports redirect for clash except port 22 for ssh connection
> iptables -t nat -A PREROUTING -p tcp --dport $ssh_port -j ACCEPT
> 
> # new
> iptables -t nat -N CLASH
> iptables -t nat -A CLASH -d 192.168.0.0/16 -j RETURN
> iptables -t nat -A CLASH -d 10.0.0.0/8 -j RETURN
> iptables -t nat -A CLASH -d 127.0.0.0/8 -j RETURN
> iptables -t nat -A CLASH -d 169.254.0.0/16 -j RETURN
> iptables -t nat -A CLASH -d 172.16.0.0/12 -j RETURN
> iptables -t nat -A CLASH -d 224.0.0.0/4 -j RETURN
> iptables -t nat -A CLASH -d 240.0.0.0/4 -j RETURN
> 
> # redirect to Clash and except udp
> iptables -t nat -A CLASH -p tcp -j REDIRECT --to-ports $proxy_port
> iptables -t nat -A PREROUTING ! -p udp -j CLASH
> 
> # DNS
> iptables -t nat -I PREROUTING -p udp -m udp -d $lan_ip --dport 53 -j DNAT --to-destination $lan_ip:55
> ```

@ZiGmaX809 你的解决方案是正确的，解决了问题

**Comment by Alice-space** [comment]
没有改变，视频开始后仍然人物静止
iptables如下
![image](https://user-images.githubusercontent.com/47878052/80357581-c5f35600-88ad-11ea-99bf-5ccfb03d0792.png)

**Comment by Alice-space** [comment]
使用了fake-ip模式
使用如下iptables
```
sudo iptables -t nat -N clash
sudo iptables -t nat -N clash_dns

sudo iptables -t nat -A PREROUTING -p tcp --dport 53 -d 198.19.0.0/24 -j clash_dns
sudo iptables -t nat -A PREROUTING -p udp --dport 53 -d 198.19.0.0/24 -j clash_dns
sudo iptables -t nat -A PREROUTING -p tcp -j clash

sudo iptables -t nat -A clash_dns -p udp --dport 53 -d 198.19.0.0/24 -j DNAT --to-destination 192.168.123.23:53
sudo iptables -t nat -A clash_dns -p tcp --dport 53 -d 198.19.0.0/24 -j DNAT --to-destination 192.168.123.23:53

sudo iptables -t nat -A clash -d 0.0.0.0/8 -j RETURN
sudo iptables -t nat -A clash -d 10.0.0.0/8 -j RETURN
sudo iptables -t nat -A clash -d 127.0.0.0/8 -j RETURN
sudo iptables -t nat -A clash -d 169.254.0.0/16 -j RETURN
sudo iptables -t nat -A clash -d 172.16.0.0/12 -j RETURN
sudo iptables -t nat -A clash -d 192.168.0.0/16 -j RETURN
sudo iptables -t nat -A clash -d 224.0.0.0/4 -j RETURN
sudo iptables -t nat -A clash -d 240.0.0.0/4 -j RETURN

sudo iptables -t nat -A clash -p tcp -j REDIRECT --to-ports 7892
```
dns设置
```
dns:                                                                                                                                                 
    enhanced-mode: fake-ip                                                                                                                             
    fake-ip-range: 198.18.0.1/16                                                                                                                       

```

**Comment by ZiGmaX809** [comment]
其实没有必要去监听和转发53端口的tcp数据，dns只用udp。
还有我之前建议的匹配`! -p udp`目的是为了绕过邮件使用的iamp和pop3等协议。
还有我倒是没注意一开始你用的redir-host模式。

**Comment by Alice-space** [comment]
谢谢您
真的奇怪
我之前确实用的是redir-host
换成上面的fakeip就可以，而且现在邮件客户端也可以用，用redir-host就总有问题
不知道为什么

**Comment by ZiGmaX809** [comment]
> 谢谢您
> 
> 真的奇怪
> 
> 我之前确实用的是redir-host
> 
> 换成上面的fakeip就可以，而且现在邮件客户端也可以用，用redir-host就总有问题
> 
> 不知道为什么

dns被污染

**Comment by Alice-space** [comment]
现在基本可以使用，但是存在严重的断流问题
yt视频看一会就会断流，整个旁路由断线，ssh也无法连接，国内无法访问，这个很严重。
相反，在手机等终端使用clash就没有这个问题

**Comment by BirkhoffLee** [comment]
> 现在基本可以使用，但是存在严重的断流问题
> yt视频看一会就会断流，整个旁路由断线，ssh也无法连接，国内无法访问，这个很严重。
> 相反，在手机等终端使用clash就没有这个问题

能夠讓我們重現這個問題的資訊不足，看起來比較像是你旁路由性能不夠吧

> 谢谢您
> 真的奇怪
> 我之前确实用的是redir-host
> 换成上面的fakeip就可以，而且现在邮件客户端也可以用，用redir-host就总有问题
> 不知道为什么

這看起來像是 DNS 污染

**Comment by Alice-space** [comment]
> > 现在基本可以使用，但是存在严重的断流问题
> > yt视频看一会就会断流，整个旁路由断线，ssh也无法连接，国内无法访问，这个很严重。
> > 相反，在手机等终端使用clash就没有这个问题
> 
> 能夠讓我們重現這個問題的資訊不足，看起來比較像是你旁路由性能不夠吧
> 
> > 谢谢您
> > 真的奇怪
> > 我之前确实用的是redir-host
> > 换成上面的fakeip就可以，而且现在邮件客户端也可以用，用redir-host就总有问题
> > 不知道为什么
> 
> 這看起來像是 DNS 污染

谢谢！
我现在做做性能测试
```
主路由：newifi D2 （padavan）
旁路由：i3-7300T +16G RAM（debian buster）
均为千兆网卡、千兆网线
```
![image](https://user-images.githubusercontent.com/47878052/80437036-2aa4c400-8933-11ea-8dcc-f09409e3e05d.png)
关停frp反向代理与minecraft服务器后，闲置如上  
现在启动clash与iptables
cpu占用0.7%，RAM147M/15.5G
采用如下iptables
```
sudo iptables -t nat -N clash
sudo iptables -t nat -N clash_dns

sudo iptables -t nat -A PREROUTING -p tcp --dport 53 -d 198.19.0.0/24 -j clash_dns
sudo iptables -t nat -A PREROUTING -p udp --dport 53 -d 198.19.0.0/24 -j clash_dns
sudo iptables -t nat -A PREROUTING -p tcp -j clash

sudo iptables -t nat -A clash_dns -p udp --dport 53 -d 198.19.0.0/24 -j DNAT --to-destination 192.168.123.23:5353
sudo iptables -t nat -A clash_dns -p tcp --dport 53 -d 198.19.0.0/24 -j DNAT --to-destination 192.168.123.23:5353

sudo iptables -t nat -A clash -d 0.0.0.0/8 -j RETURN
sudo iptables -t nat -A clash -d 10.0.0.0/8 -j RETURN
sudo iptables -t nat -A clash -d 127.0.0.0/8 -j RETURN
sudo iptables -t nat -A clash -d 169.254.0.0/16 -j RETURN
sudo iptables -t nat -A clash -d 172.16.0.0/12 -j RETURN
sudo iptables -t nat -A clash -d 192.168.0.0/16 -j RETURN
sudo iptables -t nat -A clash -d 224.0.0.0/4 -j RETURN
sudo iptables -t nat -A clash -d 240.0.0.0/4 -j RETURN

sudo iptables -t nat -A clash -p tcp -j REDIRECT --to-ports 7892
```
clash采用如下配置
```
dns:
enable: true 
 ipv6: false
listen: 0.0.0.0:5353
enhanced-mode: fake-ip                                                                                                                            
 fake-ip-range: 198.18.0.1/16                                                                                                                       
nameserver:                                                                                                                                          
 - 114.114.114.114                                                                                                                                  
- 223.5.5.5                                                                                                                                     
fallback:                                                                                                                                            
- tls://dns.rubyfish.cn:853                                                                                                                        
- 8.8.8.8 
```
微信视频仍然出现上述现象，接通后人像静止无声音，在面板内关闭所有连接后，微信重新与`49.4.*.*`建立长连接后视频童通话正常，再次挂断后拨打（长连接不会自己断），接通后人像静止无声音
看视频正常，浏览网页速度正常
```
sudo iptables -t nat -A POSTROUTING -s 192.168.123.0/255.255.255.0 -o enp0s31f6 -j SNAT --to-source 192.168.123.23
```
添加如上语句后，微信视频正常  
稳定复现播放在线视频（youtube）就会崩溃，断连几秒，ssh也断开
出现DNS_PROBE_FINISHED_NO_INTERNET，几秒后正常  
是因为性能不够吗？还是配置的错误？谢谢！
