### ISSUE TITLE
Clash DNS server is always resolving AAAA domain

### ISSUE THREAD

**Issue by ygsk10** [Dreamacro/clash#662]
Thanks for submitting an issue towards the Clash core!
But before so, please do the following checklist:

- [ ] Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome.
- [x] Your issue may already be reported! Please search on the [issue tracker](……/) before creating one.
- [ ] I have tested using the dev branch, and the issue still exists.
- [x] This is an issue related to the Clash core, not to the derivatives of Clash, like Openclash or Koolclash

Please understand that we close issues that fail to follow the issue template.

None of the above, create a bug report
------------------------------------------------------------------

请附上任何可以帮助我们解决这个问题的信息，如果我们收到的信息不足，我们将对这个 issue 加上 *Needs more information* 标记并在收到更多资讯之前关闭 issue。

### clash core config

```
port: 7890
socks-port: 7891
redir-port: 0
allow-lan: true
mode: Rule
log-level: info
external-controller: '127.0.0.1:9090'
secret: ''
hosts:
...
dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:5354
  enhanced-mode: redir-host
  default-nameserver:
     - 8.8.8.8
     - 8.8.4.4
  nameserver:
    #- 
     - 
    #- 192.168.1.1
      #- 192.168.0.1
      #- 
  fallback:
    #- 
    #- 
Proxy:
Proxy Group:
ule:
......
- GEOIP,CN,Domestic

#below is lhie's rule
#https://raw.githubusercontent.com/lhie1/Rules/master/Clash/Rule.yaml
...

MATCH,V2-Y

```

### Clash log

![1588124014311](https://user-images.githubusercontent.com/60314251/80553531-c547e600-89b9-11ea-899a-a16bf1e5d214.png)

### 环境 Environment

* Clash Core 的操作系统 (the OS that the Clash core is running on)
**Linux**
* 使用者的操作系统 (the OS running on the client)
**Android**
* 网路环境或拓扑 (network conditions/topology)
**ipv4**
* iptables，如果适用 (if applicable)
……
* ISP 有没有进行 DNS 污染 (is your ISP performing DNS pollution?)
**yes**
* 其他
……

### 重现问题的具体布骤 Steps to Reproduce

1. **Set dns: true and ipv6: false**
2. **set dns upstream to any server with logging**
3. **connect to any site**

**我预期会发生……？**

![Screenshot_20200429-013419](https://user-images.githubusercontent.com/60314251/80553580-ead4ef80-89b9-11ea-9f0d-75228e7f488b.png)

**实际上发生了什麽？**

![1588124035539](https://user-images.githubusercontent.com/60314251/80553593-f32d2a80-89b9-11ea-954a-2b248664776a.png)
