### ISSUE TITLE
[Feature]希望支持proxies配置填写vmess-tcp+tls的伪装域名

### ISSUE THREAD

**Issue by 4b441** [Dreamacro/clash#665]
使用tcp+tls+web（https://guide.v2fly.org/advanced/tcp_tls_web.html ）方案搭v2ray服务端，并用国内VPS转发端口，用v2ray客户端连接没有问题。
在Clash的vmess配置里直接添加"Host: 服务端域名"无效，是否还没有可用的写法？
感谢工作。

**Comment by Santzzg** [comment]
这里举双手赞成!!! 我用的是h2+tls+web, 在配置clash的时候发现找不到关于怎么填写h2的path和host的说明, 只有ws的, 自己蒙了几个写法也都不行, 希望作者能看到解答一下这方面的问题

**Comment by xianren78** [comment]
支持一下，确实需要这个功能。

**Comment by xuan880** [comment]
clash直接按照正常的v2ray+tls配置看看.看教程客户端和正常的vmess+tls没有任何区别.

**Comment by xianren78** [comment]
> clash直接按照正常的v2ray+tls配置看看.看教程客户端和正常的vmess+tls没有任何区别.

中转

**Comment by heham** [comment]
我就差没用cdn，配置起来还可以，万一哪天IP被封了再试试cdn

**Comment by 4b441** [comment]
> clash直接按照正常的v2ray+tls配置看看.看教程客户端和正常的vmess+tls没有任何区别.

直连没有问题，但是用国内中转的时候没地方写host。

**Comment by phlinhng** [comment]
> > clash直接按照正常的v2ray+tls配置看看.看教程客户端和正常的vmess+tls没有任何区别.
> 
> 直连没有问题，但是用国内中转的时候没地方写host。

目前除了v2ray-core，其他的客户端好像都还不支持tcp+tls自订host

**Comment by phlinhng** [comment]
> 我就差没用cdn，配置起来还可以，万一哪天IP被封了再试试cdn

TCP+TLS套不了CDN，要套CDN的话WS是唯一解。

**Comment by xianren78** [comment]
> 用

v2rayng支持

**Comment by xianren78** [comment]
> > > clash直接按照正常的v2ray+tls配置看看.看教程客户端和正常的vmess+tls没有任何区别.
> > 
> > 
> > 直连没有问题，但是用国内中转的时候没地方写host。
> 
> 目前除了v2ray-core，其他的客户端好像都还不支持tcp+tls自订host。有一个曲线救国的方法你可以试试：把中转的入口ip也绑定域名，v2Ray服务端用泛域名证书，连接时和中转IP的入口域名连接。

v2rayng支持，kitsunebi应该也支持

**Comment by phlinhng** [comment]
> > > > clash直接按照正常的v2ray+tls配置看看.看教程客户端和正常的vmess+tls没有任何区别.
> > > 
> > > 
> > > 直连没有问题，但是用国内中转的时候没地方写host。
> > 
> > 
> > 目前除了v2ray-core，其他的客户端好像都还不支持tcp+tls自订host。有一个曲线救国的方法你可以试试：把中转的入口ip也绑定域名，v2Ray服务端用泛域名证书，连接时和中转IP的入口域名连接。
> 
> v2rayng支持，kitsunebi应该也支持

v2RayNG是v2ray-core套殼，就是我说的v2ray-core。
Kitsunebi我没用过不确定，但是Kitsunebi的内核据说很久没更新了所以速度很慢。

**Comment by xuan880** [comment]
> > clash直接按照正常的v2ray+tls配置看看.看教程客户端和正常的vmess+tls没有任何区别.
> 
> 直连没有问题，但是用国内中转的时候没地方写host。

国内中转的话,就把tls校验关闭掉.

**Comment by phlinhng** [comment]
> 国内中转的话,就把tls校验关闭掉.

不校验tls有被mitm attack的可能性。

**Comment by xuan880** [comment]
> > 国内中转的话,就把tls校验关闭掉.
> 
> 不校验tls有被mitm attack的可能性。

那么追求安全的话,服务端证书就改用中转服务器域名.

**Comment by wych42** [comment]
这样写是可以用的：
```
- name: "vmess-us01"
   type: vmess
   server: ip-addr
   port: 443
   uuid: xxxxxx
   alterId: 64
   cipher: none
   udp: true
   tls: true
   skip-cert-verify: false
   network: ws
   ws-path: /path
   ws-headers:
     Host: hostname
```
