### ISSUE TITLE
[Bug] DNS 配置的 hosts 不生效

### ISSUE THREAD

**Issue by kuyagic** [Dreamacro/clash#688]
感谢你向 Clash Core 提交 issue！
在提交之前，请确认：

- [x] 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [x] 这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 Openclash、Koolclash 等）的特定问题
- [ ] 我已经使用 Clash core 的 dev 分支版本测试过，问题依旧存在
- [ ] 如果你可以自己 debug 并解决的话，提交 PR 吧！

请注意，如果你并没有遵照这个 issue template 填写内容，我们将直接关闭这个 issue。

我都确认过了，我要继续提交。
------------------------------------------------------------------

请附上任何可以帮助我们解决这个问题的信息，如果我们收到的信息不足，我们将对这个 issue 加上 *Needs more information* 标记并在收到更多资讯之前关闭 issue。

### clash core config

```
# HTTP 代理端口
port: 7890

# SOCKS5 代理端口
socks-port: 7891

# Linux 和 macOS 的 redir 代理端口 (如需使用此功能，请取消注释)
# redir-port: 7892

# 允许局域网的连接（可用来共享代理）
allow-lan: false

# 规则模式：Rule（规则） / Global（全局代理）/ Direct（全局直连）
mode: Rule

# 设置日志输出级别 (默认级别：silent，即不输出任何内容，以避免因日志内容过大而导致程序内存溢出）。
# 5 个级别：silent / info / warning / error / debug。级别越高日志输出量越大，越倾向于调试，若需要请自行开启。
# log-level: debug

# clash 的 RESTful API
external-controller: 127.0.0.1:9090

# 您可以将静态网页资源（如 clash-dashboard）放置在一个目录中，clash 将会服务于 `${API}/ui`
# 参数应填写配置目录的相对路径或绝对路径。
external-ui: ../ui

# RESTful API 的口令 (可选)
# secret: ""

# 实验性功能
experimental:
  ignore-resolve-fail: true # 忽略 DNS 解析失败，默认值为 true

# 本地 SOCKS5 / HTTP(S) 服务认证
# authentication:
#  - "user1:pass1"
#  - "user2:pass2"

dns:
  enable: true
  ipv6: false
  listen: 127.0.0.9:53
  #redir-host # 或 fake-ip
  enhanced-mode: redir-host
  # # fake-ip-range: 198.18.0.1/16 # 如果你不知道这个参数的作用，请勿修改
  # # 实验性功能 hosts, 支持通配符 (例如 *.clash.dev 甚至 *.foo.*.example.com)
  # # 静态的域名 比 通配域名 具有更高的优先级 (foo.example.com 优先于 *.example.com)
  # # 注意: hosts 在 fake-ip 模式下不生效
  hosts:
    '*.clash.dev': '127.0.0.1'
    'a.com': '127.0.0.2'
    'alpha.clash.dev': '::1'

  nameserver:
     - 1.2.4.8
     - 114.114.114.114
     - 223.5.5.5
     #- https://dns.rubyfish.cn/dns-query
     
  fallback: # 与 nameserver 内的服务器列表同时发起请求，当规则符合 GEOIP 在 CN 以外时，fallback 列表内的域名服务器生效。
     - tls://dns.rubyfish.cn:853
     - tls://9.9.9.9:853
     #- tls://dns.google:853

```

### Clash log

```
没有对应DNS的日志
```

### 环境 Environment

* Clash Core 的操作系统 (the OS that the Clash core is running on)
…… windows 10 x64
* 使用者的操作系统 (the OS running on the client)
…… windows 10 x64
* 网路环境或拓扑 (network conditions/topology)
……
* iptables，如果适用 (if applicable)
……
* ISP 有没有进行 DNS 污染 (is your ISP performing DNS pollution?)
…… yes
* 其他
……

### 说明 Description
直接 系统设置网卡dns 为配置文件里监听的 地址 
使用 cmd 的nslookup 查询域名 没有得到 配置文件里 hosts 的设置的dns应答

### 重现问题的具体布骤 Steps to Reproduce

**我预期会发生……？**
```
a.com 解析到 127.0.0.2
```

**实际上发生了什麽？**
```
*** UnKnown can't find a.com: Non-existent domain
```

详细cmd操作
```
Default Server:  UnKnown
Address:  127.0.0.9

> a.com
Server:  UnKnown
Address:  127.0.0.9

*** UnKnown can't find a.com: Non-existent domain
> a.clash.dev
Server:  UnKnown
Address:  127.0.0.9

*** UnKnown can't find a.clash.dev: Non-existent domain
>
```
