### ISSUE TITLE
[Bug]premium版本rule-set规则有关解析dns的一个明显bug

### ISSUE THREAD

**Issue by fedstryale** [Dreamacro/clash#708]
感谢你向 Clash Core 提交 issue！
在提交之前，请确认：

- [x] 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [x] 这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 Openclash、Koolclash 等）的特定问题
- [ ] 我已经使用 Clash core 的 dev 分支版本测试过，问题依旧存在
- [ ] 如果你可以自己 debug 并解决的话，提交 PR 吧！

请注意，如果你并没有遵照这个 issue template 填写内容，我们将直接关闭这个 issue。

我都确认过了，我要继续提交。
--

### clash core config

```

tun:
  enable: false

rule-providers:
    "proxy-url": 
        type: http
        behavior: domain
        path: ./proxy-url.yaml
        url: http://xxx.com/proxy-url.yaml
        interval: 60

rules:
- DOMAIN-SUFFIX,google.com,PROXY
- RULE-SET,proxy-url,PROXY
```

### Clash log

```
[DNS] www.google.com.hk --> 31.13.69.86
[TCP] 192.168.xxx --> www.google.com.hk match RuleSet using PROXY
[TCP] 192.168.xxx --> www.google.com match DomainSuffix using PROXY
```

### 环境 Environment

* Clash Core 的操作系统 (the OS that the Clash core is running on)
openwrt 19.07.2
* 使用者的操作系统 (the OS running on the client)
all
* 网路环境或拓扑 (network conditions/topology)
fakeip模式旁路由，非tun模式

### 重现问题的具体布骤 Steps to Reproduce
当规则匹配是RuleSet时，即使behavior: domain，clash（premium）仍然去解析域名（虽然解析后仍然用domain RuleSet去请求代理）。匹配规则DomainSuffix则表现正常，不会解析域名。

**我预期会发生……？**
当规则匹配是RuleSet时，如果behavior: domain，表现应该与DomainSuffix等一致，无需解析域名，直接发送域名给代理连接

**实际上发生了什麽？**
1. 即使匹配是domain的RuleSet，clash只会在拿到域名后进行连接，降低了连接速度
2. 极端情况下，本地无法解析域名如ipv6.google.com（AAAA和A都为空），则报错，无法匹配RuleSet规则

另外还有个小问题，如果使用proxy-providers:，url-test或者fallback use这个provider中的代理，则定期测试不会生效，如果使用proxies，定期测试则没问题
