### ISSUE TITLE
[Bug] Unknown network type: http

### ISSUE THREAD

**Issue by Dr-Incognito** [Dreamacro/clash#710]
感谢你向 Clash Core 提交 issue！
在提交之前，请确认：

- [x] 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [x] 这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 Openclash、Koolclash 等）的特定问题
- [ ] 我已经使用 Clash core 的 dev 分支版本测试过，问题依旧存在
- [ ] 如果你可以自己 debug 并解决的话，提交 PR 吧！

请注意，如果你并没有遵照这个 issue template 填写内容，我们将直接关闭这个 issue。

我都确认过了，我要继续提交。

------------------------------------------------------------------

请附上任何可以帮助我们解决这个问题的信息，如果我们收到的信息不足，我们将对这个 issue 加上 *Needs more information* 标记并在收到更多资讯之前关闭 issue。

### clash core config

```
  - alterId: 4
    cipher: auto
    http-opts:
      headers:
        Accept-Encoding:
          - gzip, deflate
        Connection:
          - keep-alive
        Pragma: no-cache
        User-Agent:
          - Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.1777.15 Safari/537.36
          - Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.2386.92 Safari/537.36
          - Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.3362.27 Safari/537.36
        host:
          - www.baidu.com
          - www.bing.com
          - www.163.com
          - www.netease.com
      method: GET
      path: /
    name: Test
    network: http
    port: 443
    server: hk.example.com
    skip-cert-verify: false
    tls: true
    type: vmess
    udp: false
    uuid: 64fbd703-88c7-4fdc-ad43-b15ba0111d2f
```

### Clash log

```
2020/05/21 19:37:56 [fatal] clash: Parse config error: Proxy 3: Unknown network type: http
```

### 环境 Environment

* Clash Core 的操作系统 (the OS that the Clash core is running on)
Arch Linux

* 使用者的操作系统 (the OS running on the client)
Arch Linux

* 网路环境或拓扑 (network conditions/topology)
……

### 说明 Description

V2Ray with TCP protocol and HTTP header is not working with Clash **0.20**.

### 重现问题的具体布骤 Steps to Reproduce

1. Use the config mentioned above.
2. Run clash-core

**我预期会发生……？**

Everything works fine and I can start Clash normally.

**实际上发生了什麽？**

The Clash crashed and said "Unknown network type: http".

**Comment by Dreamacro** [comment]
it works fine. BTW, every header and path is a slice

**Comment by Dr-Incognito** [comment]
@Dreamacro 
1. You mean you can not reproduce my error?
2. What do you mean "slice"? Could you provide me a demo config?

**Comment by Dreamacro** [comment]
```yaml
proxies:
  - alterId: 4
    cipher: auto
    http-opts:
      headers:
        Accept-Encoding:
          - gzip, deflate
        Connection:
          - keep-alive
        Pragma:
          - no-cache
        User-Agent:
          - Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.1777.15 Safari/537.36
          - Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.2386.92 Safari/537.36
          - Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.3362.27 Safari/537.36
        host:
          - www.baidu.com
          - www.bing.com
          - www.163.com
          - www.netease.com
      method: GET
      path:
          - /
    name: Test
    network: http
    port: 443
    server: hk.example.com
    skip-cert-verify: false
    tls: true
    type: vmess
    udp: false
    uuid: 64fbd703-88c7-4fdc-ad43-b15ba0111d2f
```

it works on my mbp
