### ISSUE TITLE
[Bug] 是否只有select策略组才能使用proxies-provider？

### ISSUE THREAD

**Issue by Mosney** [Dreamacro/clash#715]
感谢你向 Clash Core 提交 issue！
在提交之前，请确认：

- [x] 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [x] 这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 Openclash、Koolclash 等）的特定问题
- [ ] 我已经使用 Clash core 的 dev 分支版本测试过，问题依旧存在
- [ ] 如果你可以自己 debug 并解决的话，提交 PR 吧！

请注意，如果你并没有遵照这个 issue template 填写内容，我们将直接关闭这个 issue。

### clash core config

```
proxy-groups:
 - name: 'HK Auto'
   type: url-test
   use: 
    - HK
   url: 'http://www.gstatic.com/generate_204'
   interval: 600
   timeout: 5
...
proxy-providers:
  HK:
    type: http
    url: "http://"
    interval: 36000
    path: ./HK.yaml
    health-check:
      enable: false
      interval: 6000
      url: http://cp.cloudflare.com/generate_204
```

### Clash log

```
不相关
```

### 环境 Environment

* Clash Core 的操作系统 (the OS that the Clash core is running on)
OpenWrt amd64 19.07.2
* 网路环境或拓扑 (network conditions/topology)
iptables 网关透明代理
* iptables，如果适用 (if applicable)
不相关
* ISP 有没有进行 DNS 污染 (is your ISP performing DNS pollution?)
不相关

### 重现问题的具体布骤 Steps to Reproduce
使用proxies-provider提供节点且关闭健康检查，在某个url-test策略组中完全使用此provider节点

**我预期会发生……？**

provider只负责按照设置的interval更新节点，不进行健康检测，url-test负责健康检测以及节点延迟测速并自动选择最快的节点。

**实际上发生了什麽？**

provider的健康检查依旧执行，但似乎只执行一次。据我观察此时url-test策略组的定时测速功能实际是失效的：暂时不可用节点一直标红直到在WebUI内手动给provider执行一次健康检查，同时选中的最佳延迟节点一直不变，符合前述测速功能处于非工作状态。
我尝试过把`health-check:` 整个去掉（虽然示例配置没有列出但我认为这部分配置是可选的），实际运行的确不进行健康检查了，但是clash会认为这里面所有的节点都是不可用的，此时url-test依然不发挥作用（WebUI中策略组内节点全红）。
