### ISSUE TITLE
[Feature]兼容tunctl创建的tun设备

### ISSUE THREAD

**Issue by galaxy001** [Dreamacro/clash#721]
感谢你向 Clash Core 提交 Feature Request！
在提交之前，请确认：

- [x] 我已经在 [Issue Tracker](……/) 中找过我要提出的请求

请注意，如果你并没有遵照这个 issue template 填写内容，我们将直接关闭这个 issue。

我都确认过了，我要继续提交。

------------------------------------------------------------------

请附上任何可以帮助我们解决这个问题的信息，如果我们收到的信息不足，我们将对这个 issue 加上 *Needs more information* 标记并在收到更多资讯之前关闭 issue。

### Clash core config

```
port: 7890

dns:
  enable: true
  listen: 0.0.0.0:8053
  enhanced-mode: redir-host
  nameserver:
    - 114.114.114.114

experimental:
  interface-name: en0 # your interface-name

tun:
  enable: true

mode: Script

tun:
  enable: true
  stack: system # or gvisor
log-level: debug
```

### Clash log

```
ERRO[0000] Start DNS server error: listen udp 0.0.0.0:53: bind: permission denied
ERRO[0000] Start Tun interface error: invalid argument
INFO[0000] HTTP proxy listening at: 127.0.0.1:7890
```

### 环境 Environment

* Clash Core 的操作系统 (the OS that the Clash core is running on)
Linux
* 使用者的操作系统 (the OS running on the client)
ubuntu 20.04 LTS
* 网路环境或拓扑 (network conditions/topology)
general
* iptables，如果适用 (if applicable)
empty
* ISP 有没有进行 DNS 污染 (is your ISP performing DNS pollution?)
Yes
* 其他
N/A

### 说明 Description

运行`tunctl -u USERID -t utun`可以创建不需要提权就能访问的tun设备。
但clash不能使用它。

```
$ USERID=`whoami`

$ sudo tunctl -3u $USERID -t utun
Set 'utun' persistent and owned by uid 1000
$ sudo ip link set dev utun mtu 9000

$ clash
INFO[0000] DNS server listening at: 0.0.0.0:8053
INFO[0000] HTTP proxy listening at: 127.0.0.1:7890
ERRO[0000] Start Tun interface error: failed to set MTU of TUN device
```

### 可能的解决方案 Possible Solution

clash在tun设备的MTU已经是9000的情况下，不再要求覆盖tun的MTU为9000。

### 更多信息 More Information

```

**Comment by Dreamacro** [comment]
不知道为什么一定要用 tunctl 自己创建一个 TUN，有什么好处吗

**Comment by galaxy001** [comment]
减少需要root权限的程序数量呀

**Comment by Dreamacro** [comment]
TUN 需要一个 CAP_NET_ADMIN 权限，给这个就行了吧

**Comment by galaxy001** [comment]
额，想问下<https://github.com/comzyh/clash>与你的tun版本有啥区别？
他那边只对macOS设置MTU，Linux不管MTU。

**Comment by Dreamacro** [comment]
@galaxy001 整体配置偏向 linux，premium 版本权衡了 macOS 和 Linux

**Comment by galaxy001** [comment]
你加个判断MTU是否已经是9000，或者简单地try catch一下，应该不费啥事吧？

**Comment by BirkhoffLee** [comment]
@galaxy001 歡迎 Pull request

**Comment by galaxy001** [comment]
tun部分不是没开源么……

**Comment by Dreamacro** [comment]
现在 premium 有了 docker image，只给 NET_ADMIN 加一层 docker 够了吧？

```
version: '3'
services:
  clash:
    image: dreamacro/clash-premium:latest
    cap_add:
      - NET_ADMIN
    volumes:
      - ./config.yaml:/root/.config/clash/config.yaml
      # dashboard volume
      # - ./ui:/ui
    ports:
      - "7890:7890"
      - "7891:7891"
      # If you need external controller, you can export this port.
      # - "8080:8080"
    restart: always
    network_mode: "host"
    container_name: clash
```
