### ISSUE TITLE
[Feature] Follow Subscription Source and Override Configuration

### ISSUE THREAD

**Issue by septs** [Dreamacro/clash#723]
Ideal configuration

```yaml
port: 7890
socks-port: 7891
redir-port: 7892
allow-lan: true
external-controller: :9090
log-level: debug
// ... and other overridable configuration ...

subscription: "subscription url for proxy provider"
```
