### ISSUE TITLE
[Feature]在relay中支持DIRECT 

### ISSUE THREAD

**Issue by Spedoske** [Dreamacro/clash#730]
感谢你向 Clash Core 提交 Feature Request！
在提交之前，请确认：

- [x] 我已经在 [Issue Tracker](……/) 中找过我要提出的请求

请注意，如果你并没有遵照这个 issue template 填写内容，我们将直接关闭这个 issue。

我都确认过了，我要继续提交。

------------------------------------------------------------------

请附上任何可以帮助我们解决这个问题的信息，如果我们收到的信息不足，我们将对这个 issue 加上 *Needs more information* 标记并在收到更多资讯之前关闭 issue。

### Clash core config

```
Proxy:
  - {name: "代理服务器"}
  - {name: "前置代理"}
Proxy Group:
  - name: 选择前置代理
    type: select
    proxies:
      - DIRECT
      - 前置代理
  - name: 使用代理
    type: relay
    proxies:
      - 选择前置代理
      - 代理服务器
```

### Clash log

当`选择前置代理` 选择 `Direct` 时，无法连接代理服务器
```
dial xxx error : connect error: missing port in address.
```

### 环境 Environment

* Clash Core 的操作系统 (the OS that the Clash core is running on)
Android
* 使用者的操作系统 (the OS running on the client)
Android
* 网路环境或拓扑 (network conditions/topology)
场合1 用户->前置代理->代理服务器
场景2 用户->代理服务器

### 说明 Description

当 `选择前置代理` 选择 `Direct` 时，无法连接代理服务器
，理想行为应该是忽略 `Direct` 项，直接连接代理服务器。
### 可能的解决方案 Possible Solution

relay 在 遇到 `Direct` 时更改处理逻辑，直接跳过`Direct`。
