### ISSUE TITLE
[Feature] DNS 规则

### ISSUE THREAD

**Issue by ygsk10** [Dreamacro/clash#732]
感谢你向 Clash Core 提交 Feature Request！
在提交之前，请确认：

- [x] 我已经在 [Issue Tracker](……/) 中找过我要提出的请求

请注意，如果你并没有遵照这个 issue template 填写内容，我们将直接关闭这个 issue。

我都确认过了，我要继续提交。

------------------------------------------------------------------

请附上任何可以帮助我们解决这个问题的信息，如果我们收到的信息不足，我们将对这个 issue 加上 *Needs more information* 标记并在收到更多资讯之前关闭 issue。

### Clash core config

```
port: 7890
socks-port: 7891
redir-port: 7892
allow-lan: true
mode: Rule
log-level: debug
external-controller: '127.0.0.1:9090'
secret: ''
hosts:
  #'www.bing.com': 1.1.1.1
    'counter1.stat.ovh': 51.77.152.115
    '*.google-analytics.com': 0.0.0.0
    '.doubleclick.net': 0.0.0.0
    '*.bdstatic.com': 0.0.0.0
    '*.baidustatic.com': 0.0.0.0
    '*.baidu.com': 0.0.0.0
    '*.googlesyndication.com': 0.0.0.0
    '*.doubleclickbygoogle.com': 0.0.0.0
    '*.googletagmanager.com': 0.0.0.0
    '*.googleadservices.com': 0.0.0.0
    'csi.gstatic.com': 0.0.0.0
    '.googletagservices.com': 0.0.0.0
    'beacons.gcp.gvt2.com': 0.0.0.0
    'beacons.gvt2.com': 0.0.0.0
    'app-measurement.com': 0.0.0.0
    '*.crashlytics.com': 0.0.0.0
    #'.cn': 0.0.0.0
    '*.ink': 0.0.0.0
    '.cnzz.com': 0.0.0.0
    '.facebook.com': 0.0.0.0
    '.facebook.net': 0.0.0.0
    '.fbcdn.net': 0.0.0.0
    '.qq.com': 0.0.0.0
    'qq.com': 0.0.0.0
    '.douban.com': 0.0.0.0
    '.zhihu.com': 0.0.0.0
    '.weibo.com': 0.0.0.0
    'collector.githubapp.com': 0.0.0.0
    'adservice.google.com': 0.0.0.0
    '.g2afse.com': 0.0.0.0
    '.alibaba.com': 0.0.0.0
    '.trafficjunky.net': 0.0.0.0
    '.flurry.com': 0.0.0.0
    'top-fwz1.mail.ru': 0.0.0.0
dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:5354
  enhanced-mode: fake-ip
  fake-ip-filter:
    - '.ntp.org'
    - '.ntp.org.cn'
    - 'time.'
    - '.google.com'
      #- '.google.com'
  default-nameserver:
     - 8.8.8.8
     - 8.8.4.4
  nameserver:
    #- tls://.dns.nextdns.io:853
    #- https://dns.nextdns.io
    - 192.168.1.1
    - 192.168.4.1
    - 192.168.0.1
    - 1.2.4.8
    - 8.8.8.8
    - 8.8.4.4
      #- 211.138.24.66
  fallback:
    #- tls://dns.google:853
       - https://
  fallback-filter:
      geoip: true
      ipcidr:
      - 240.0.0.0/4
Proxy:
Proxy Group:
  
Rule:
# hosts configured
# before e537955, hosts won't effect if configured domains were not in DIRECT
- DOMAIN-KEYWORD,facebook,DIRECT
- DOMAIN-KEYWORD,fbcdn,DIRECT
- DOMAIN-SUFFIX,cn,DIRECT
- DOMAIN-SUFFIX,qq.com,DIRECT
- DOMAIN-KEYWORD,bdstatic,DIRECT
- DOMAIN-KEYWORD,baidu,DIRECT
- DOMAIN-KEYWORD,baidustatic,DIRECT
- DOMAIN-SUFFIX,googlesyndication.com,DIRECT
- DOMAIN-SUFFIX,googletagmanager.com,DIRECT
- DOMAIN-SUFFIX,app-measurement.com,DIRECT
- DOMAIN-SUFFIX,crashlytics.com,REJECT
- DOMAIN-SUFFIX,google-analytics.com,DIRECT
- DOMAIN-KEYWORD,doubleclick,DIRECT
- DOMAIN-SUFFIX,googleadservices.com,DIRECT
- DOMAIN,adservice.google.com,DIRECT
- DOMAIN,csi.gstatic.com,DIRECT
- DOMAIN-SUFFIX,googletagservices.com,DIRECT
- DOMAIN,beacons.gcp.gvt2.com,DIRECT
- DOMAIN,beacons.gvt2.com,DIRECT
- DOMAIN,collector.githubapp.com,DIRECT
- DOMAIN-KEYWORD,weibo,DIRECT
- DOMAIN-KEYWORD,zhihu,DIRECT
- DOMAIN-KEYWORD,douban,DIRECT
- DOMAIN-SUFFIX,g2afse.com,DIRECT
- DOMAIN-SUFFIX,alibaba.com,DIRECT
- DOMAIN-SUFFIX,trafficjunky.net,DIRECT
- DOMAIN-SUFFIX,flurry.com,DIRECT
- DOMAIN,top-fwz1.mail.ru,DIRECT
  #- DOMAIN-KEYWORD,yahoo,DIRECT
  #- DOMAIN,bit.ly,DIRECT
  #- DOMAIN-KEYWORD,textnow,DIRECT


# Manual
- DOMAIN,time.android.com,DIRECT
- DOMAIN-SUFFIX,adform.net,AdBlock
- DOMAIN-SUFFIX,outbrain.com,AdBlock
- DOMAIN-SUFFIX,moatads.com,AdBlock
- DOMAIN-SUFFIX,amazon-adsystem.com,AdBlock
- DOMAIN-SUFFIX,ntp.org,DIRECT
- DOMAIN,smtp.yandex.com,DIRECT
- DOMAIN,imap.yandex.com,DIRECT
  #- DOMAIN-KEYWORD,yandex,DIRECT
  #- DOMAIN-KEYWORD,yastatic,DIRECT
- DOMAIN-KEYWORD,hotmail,DIRECT
- DOMAIN-KEYWORD,ipv2,DIRECT
- DOMAIN-SUFFIX,exhentai.org,DIRECT
- DOMAIN-KEYWORD,127,Domestic
- DOMAIN-KEYWORD,163,Domestic
- DOMAIN-KEYWORD,126,Domestic
- DOMAIN-SUFFIX,bowenpress.com,V2-Y
  #- DOMAIN,pincong.rocks,REJECT
- DOMAIN-SUFFIX,ehgt.org,DIRECT
- DOMAIN-KEYWORD,location,DIRECT

# Nextdns
- DOMAIN,dns.nextdns.io,DIRECT
- IP-CIDR,75.90.28.0/32,DIRECT

# honeypot


  #- DOMAIN-KEYWORD,2049bbs,REJECT
#- DOMAIN-SUFFIX,solidot.org,REJECT

# trackers
- DOMAIN-SUFFIX,aidata.com,REJECT
- DOMAIN-SUFFIX,branch.io,REJECT
- DOMAIN-SUFFIX,demdex.com,REJECT
- DOMAIN-SUFFIX,bugsnag.com,REJECT
- DOMAIN-SUFFIX,cnzz.com,REJECT
- DOMAIN,stats.wp.com,REJECT
- DOMAIN-KEYWORD,amplitude,REJECT
- DOMAIN-SUFFIX,events.redditmedia.com,REJECT

# Rubbish CN sites
- DOMAIN-KEYWORD,lz233,REJECT
- DOMAIN-KEYWORD,alicdn,AdBlock
  #- DOMAIN-KEYWORD,bilibili,REJECT
- DOMAIN-KEYWORD,cctv,REJECT

# Mi€ro$o£t
  #- DOMAIN,www.bing.com,DIRECT
  #- DOMAIN-SUFFIX,appcenter.ms,DIRECT
- DOMAIN-KEYWORD,outlook,DIRECT
- DOMAIN,cn.bing.com,REJECT


# Baidope

# Goolag

# Google MFSocket Service
- DOMAIN-KEYWORD,mtalk.google.com,DIRECT
- DOMAIN-KEYWORD,mobile-gtalk,DIRECT
- DOMAIN,www.gstatic.com,V2-Y
  #- DOMAIN,fonts.googleapis.com,DIRECT
- IP-CIDR,172.253.122.188/32,DIRECT
- IP-CIDR,172.253.67.188/32,DIRECT
- IP-CIDR,64.233.164.188/32,DIRECT
- IP-CIDR,74.125.137.188/32,DIRECT
- IP-CIDR,74.125.68.188/32,DIRECT
- IP-CIDR,108.177.97.188/32,DIRECT
- IP-CIDR,108.177.125.188/32,DIRECT
- IP-CIDR,14.250.96.188/32,DIRECT
- IP-CIDR,64.233.188.188/32,DIRECT
- IP-CIDR,74.125.204.188/32,DIRECT


# moz://a
#- DOMAIN-KEYWORD,mozilla,DIRECT
- DOMAIN,accounts.firefox.com,V2-Y
- DOMAIN,relay.firefox.com,V2-Y
  #- DOMAIN-SUFFIX,services.mozilla.com,DIRECT


# Final
- GEOIP,CN,Domestic

#below is lhie's rule #https://raw.githubusercontent.com/lhie1/Rules/master/Clash/Rule.yaml
```

### Clash log

```
……
```

### 环境 Environment

* Clash Core 的操作系统 (the OS that the Clash core is running on)
Linux (maybe ?
* 使用者的操作系统 (the OS running on the client)
Android
* 网路环境或拓扑 (network conditions/topology)
IPv4
* iptables，如果适用 (if applicable)
......
* ISP 有没有进行 DNS 污染 (is your ISP performing DNS pollution?)
Yes, but not for mtalk.google.com
* 其他
……

### 说明 Description

* DNS 请求时 支持 对 特定 域名 进行 本地 解析
* 因为 FCM 服务器 按照 GEOIP 在国外 会取 fallback 的 结果
which is 对 本地 不友好 （已被 屏蔽
