### ISSUE TITLE
[Feature] Support Proxy Provider in proxies

### ISSUE THREAD

**Issue by nickfan** [Dreamacro/clash#735]
感谢你向 Clash Core 提交 Feature Request！
在提交之前，请确认：

- [x] 我已经在 [Issue Tracker](……/) 中找过我要提出的请求

请注意，如果你并没有遵照这个 issue template 填写内容，我们将直接关闭这个 issue。

我都确认过了，我要继续提交。

------------------------------------------------------------------

请附上任何可以帮助我们解决这个问题的信息，如果我们收到的信息不足，我们将对这个 issue 加上 *Needs more information* 标记并在收到更多资讯之前关闭 issue。

### Clash core config

```
……
```

### Clash log

```
……
```

### 环境 Environment

* Clash Core 的操作系统 (the OS that the Clash core is running on)
……
* 使用者的操作系统 (the OS running on the client)
……
* 网路环境或拓扑 (network conditions/topology)
……
* iptables，如果适用 (if applicable)
……
* ISP 有没有进行 DNS 污染 (is your ISP performing DNS pollution?)
……
* 其他
……

### 说明 Description

目前的clash的master的版本，在config.yaml中的proxies段只支持具体的各个远程服务器的配置列表，而不支持Proxy Provider，Proxy Provider只能用于Proxy Group中。

而目前的Rest API对指定delay的探测，貌似只能用于proxies下而不能用于Proxy Group下的节点。
（/proxies/Proxy（主用的ProxyGroup的名字）/xxx/delay会报404）
于是，我只能把各个ProxyProvider文件中的proxies中的节点全部拷贝追加到config.yaml的proxies的节点中才能做针对每个server对目标url的delay测试。

能否让config.yaml中的proxies支持 use 各个Proxy Provider，
或者REST API的delay的测试支持各个Proxy Group下的节点。

**Comment by Dreamacro** [comment]
其实是有针对 provider 进行测速的 API，你可以在 clash dashboard 中看到

**Comment by nickfan** [comment]
proxies 能支持直接use多个Proxy Provider吗？

**Comment by Dreamacro** [comment]
1. proxies 和 proxy provider 是对等关系，不是从属关系，只有 groups 才能 use provider，你可以理解为 proxy provider 是可以动态更新的 proxies
2. 真的没那么多时间去处理 API 文档和最新代码实现的不一致问题

**Comment by nickfan** [comment]
![image](https://user-images.githubusercontent.com/100613/84132047-f7983900-aa77-11ea-9744-785b7c9eaa44.png)

请恕在下愚钝，在clash-dashboard里只找到了这个的测速请求代码，

```
proxies/${encodeURIComponent(name)}/delay
```
这个可以测速的前提是你的各项代理server的配置都是配置在config.yaml根配置的proxies中的。
然后就需要我把所use的n个proxy provider的proxies中的节点配置清单都追加拷贝到根config.yaml中来，才能做对应的所有proxy provider的针对指定url的测速。

理想的情况是，从各个服务商下载/订阅url在config.yaml中只需要添加proxy provider，然后就可以集体测速了，虽然如果节点多了会比较慢。

设想的是config.yaml可以写：

```
port:xxx
socks-port:xxx
external-controller:xxx.xxx.xxx:9090
...

proxies:
 use:
  - sp001
  - sp002
  - sp003

proxy-provider:
  sp001:
    type: file
    path: ./sp001.yaml
  sp002:
    type: file
    path: ./sp002.yaml
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300
  sp003:
    type: file
    path: ./sp003.yaml
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300


proxy-groups:

  - name: "auto"
    type: url-test
    use:
      - sp001
      - sp002
      - sp003
    url: "http://www.gstatic.com/generate_204"
    interval: 300
```

这样测速可以统一调用rest接口
然后各个服务商的spxxx.yaml配置文件中查找替换Proxy:为proxies:
这样不用把各家的proxies中的servers的配置信息都手工合并到config.yaml的proxies中来，而且一旦订阅更新，还需要人工维护根config.yaml中的proxies，非常麻烦。。
