### ISSUE TITLE
[Bug] 使用clash-premium的docker镜像无法创建tun

### ISSUE THREAD

**Issue by L0snight** [Dreamacro/clash#736]
感谢你向 Clash Core 提交 issue！
在提交之前，请确认：

- [√] 我已经在 [Issue Tracker](……/) 中找过我要提出的问题

我都确认过了，我要继续提交。
------------------------------------------------------------------

请附上任何可以帮助我们解决这个问题的信息，如果我们收到的信息不足，我们将对这个 issue 加上 *Needs more information* 标记并在收到更多资讯之前关闭 issue。

### clash core config

```
port: 7890
socks-port: 7891
redir-port: 7892
allow-lan: true
mode: Rule
log-level: info
external-controller: 127.0.0.1:9090
dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:1053
  enhanced-mode: fake-ip
  nameserver:
    - 119.29.29.29
    - 114.114.114.114
    - 223.5.5.5
experimental:
  interface-name: wlp4s0 
tun:
  enable: true
```

### Clash log

```
clash    | time="2020-06-10T11:31:40Z" level=error msg="Start Tun interface error: no such file or directory"
```

### 环境 Environment

* Clash Core 的操作系统 (the OS that the Clash core is running on)
Linux
* 使用者的操作系统 (the OS running on the client)
Arch linux
* 网路环境或拓扑 (network conditions/topology)
x
* iptables，如果适用 (if applicable)
x
* ISP 有没有进行 DNS 污染 (is your ISP performing DNS pollution?)
……
* 其他
docker-compose:
```
version: '3'
services:
  clash:
    image: dreamacro/clash-premium:latest
    cap_add:
      - NET_ADMIN
    volumes:
      - /srv/clash-tun/config.yaml:/root/.config/clash/config.yaml
      # dashboard volume
      # - ./ui:/ui
    ports:
      - "7890:7890"
      - "7891:7891"
      # If you need external controller, you can export this port.
      - "9090:9090"
    restart: always
    network_mode: "host"
    container_name: clash
```

### 说明 Description

使用dreamacro/clash-premium这个image无法创建tun, log如下:
```
clash    | time="2020-06-10T11:31:40Z" level=error msg="Start Tun interface error: no such file or directory"
```
### 重现问题的具体布骤 Steps to Reproduce

1. sudo docker-compose up

**我预期会发生……？**

**实际上发生了什麽？**

**Comment by Dreamacro** [comment]
增加 `devices` 字段, 把 TUN 地址加上

```yaml
version: '3'
services:
  clash:
    image: dreamacro/clash-premium:latest
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    volumes:
      - ./config.yaml:/root/.config/clash/config.yaml
      # dashboard volume
      # - ./ui:/ui
    ports:
      - "7890:7890"
      - "7891:7891"
      # If you need external controller, you can export this port.
      - "9090:9090"
    restart: always
    network_mode: host
    container_name: clash
```
