### ISSUE TITLE
macOS 用 redir-host 做透明代理

### ISSUE THREAD

**Issue by phlinhng** [Dreamacro/clash#745]
我試著在 macOS 上仿造 Linux 的步驟，用 clash 做透明代理提供給 mac 分享出的子網翻牆。
環境如下
```
對外網絡: en9
熱點網口: en0
clashX
```
配置文件如下
```
# HTTP 代理端口
port: 7890

# SOCKS5 代理端口
socks-port: 7891

# Linux 和 macOS 的 redir 代理端口 (如需使用此功能，请取消注释)
redir-port: 7892

# 允许局域网的连接（可用来共享代理）
allow-lan: true

# 规则模式：Rule（规则） / Global（全局代理）/ Direct（全局直连）
mode: Rule

# 设置日志输出级别 (默认级别：info，级别越高日志输出量越大，越倾向于调试)
# 四个级别：silent / info / warning / error / debug
log-level: info

# Clash 的 RESTful API
external-controller: 127.0.0.1:9090

# you can put the static web resource (such as clash-dashboard) to a directory, and clash would serve in `${API}/ui`
# input is a relative path to the configuration directory or an absolute path
# external-ui: folder

# Secret for RESTful API (Optional)
# secret: ""

# experimental feature
experimental:
  ignore-resolve-fail: true # ignore dns reslove fail, default value is true

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:53
  enhanced-mode: redir-host
  nameserver:
    - 119.29.29.29
    - 223.5.5.5
    - 1.1.1.1
    - tls://dns.rubyfish.cn:853
  fallback:
    - tls://1.1.1.1:853
    - tls://1.0.0.1:853
    - tls://dns.google:853
```
這是我目前設置透明代理的步驟
## 前置實驗 ( 還沒使用透明代理 )
1、mac 開啟網絡共享
2、手機連上 mac 的網絡，得知子網為 `192.168.2.0/24`，此時可以正常上網（沒經過代理）
3、clash 開啟 LAN 共享，手機設置  HTTP 代理為 `192.168.2.1:7890`，此時可以正常通過代理上網
## 開始設置透明代理
1、開啟 ipv4 forwarding
```sh
 sudo sysctl -w net.inet.ip.forwarding=1
```
2、編輯 `tproxy.rule`
```
rdr on en0 proto tcp from any to any port { 80 , 443 } -> 127.0.0.1 port 7892
```
3、啟用 pf 轉發
```sh
sudo pfctl -a com.apple.internet-sharing -f ~/tproxy.rule
sudo pfctl -a com.apple.internet-sharing -e
```
然後手機就連不上網了。推測轉發規則可能是有運作的（因為開啟轉發後才造成無法上網），但是轉發到錯誤的目標了。

**Comment by Dreamacro** [comment]
macOS 建议直接 clashx pro 或者 premium 上 TUN，一键化操作，不需要动 pf

**Comment by phlinhng** [comment]
感謝建議，我已經改用 clashX Pro 並開啟 tun，不過依然沒辦法讓 en0 的子網走代理。以下是我目前的配置
```yaml
experimental:
  ignore-resolve-fail: true # ignore dns reslove fail, default value is true
  # interface-name: en0 ## 加了以後會造成手機無法上網

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:53
  enhanced-mode: redir-host
  nameserver:
    - 119.29.29.29
    - 223.5.5.5
    - 1.1.1.1
    - tls://dns.rubyfish.cn:853
  fallback:
    - tls://1.1.1.1:853
    - tls://1.0.0.1:853
    - tls://dns.google:853

tun:
  enable: true
  #stack: system ## 加了以後會造成手機無法上網
  #macOS-auto-route: true ## 加了以後會造成手機無法上網
```
現在最多只能做到讓電腦和手機共享網絡，共享(透明)代理還沒辦法成功。

**Comment by Dreamacro** [comment]
只需要将手机的 WIFI 设置网关指向 mac 电脑，dns 也设置成 mac 电脑的 ip 就行了

**Comment by phlinhng** [comment]
> 只需要将手机的 WIFI 设置网关指向 mac 电脑，dns 也设置成 mac 电脑的 ip 就行了
> 
> 参考 https://rixcloudkb.io/kb/set-up-the-rixcloud-gateway-for-the-lan-through-surge-for-macos/

我現在搞懂 Enhance Mod 怎麼用了。只要開啟 Enhance Mod，不開 System Proxy，整個系統就會自動走 TUN 連網。ifconfig
```
dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:53
  enhanced-mode: fake-ip
  nameserver:
    - 119.29.29.29
    - 223.5.5.5
    - 1.1.1.1
    - tls://dns.rubyfish.cn:853
  fallback:
    - tls://1.1.1.1:853
    - tls://1.0.0.1:853
    - tls://dns.google:853

tun:
  enable: true
  macOS-auto-route: true
  macOS-auto-detect-interface: true
```
以上設置對電腦本身來說完全沒問題。    
但是 wifi 共享時就會出問題，mac 共享出的 wifi 其網關和DNS本身就是電腦，不用再改。在使用內建 wifi 熱點的時候，共享出的 wifi 配合以上設置無法連接任何網頁。
```
lo0: flags=8049<UP,LOOPBACK,RUNNING,MULTICAST> mtu 16384
	options=1203<RXCSUM,TXCSUM,TXSTATUS,SW_TIMESTAMP>
	inet 127.0.0.1 netmask 0xff000000
	inet6 ::1 prefixlen 128
	inet6 fe80::1%lo0 prefixlen 64 scopeid 0x1
	nd6 options=201<PERFORMNUD,DAD>
gif0: flags=8010<POINTOPOINT,MULTICAST> mtu 1280
stf0: flags=0<> mtu 1280
XHC0: flags=0<> mtu 0
XHC1: flags=0<> mtu 0
XHC20: flags=0<> mtu 0
VHC128: flags=0<> mtu 0
en5: flags=8863<UP,BROADCAST,SMART,RUNNING,SIMPLEX,MULTICAST> mtu 1500
	ether ac:de:48:00:11:22
	inet6 fe80::aede:48ff:fe00:1122%en5 prefixlen 64 scopeid 0x8
	nd6 options=201<PERFORMNUD,DAD>
	media: autoselect (100baseTX <full-duplex>)
	status: active
ap1: flags=8943<UP,BROADCAST,RUNNING,PROMISC,SIMPLEX,MULTICAST> mtu 1500
	options=400<CHANNEL_IO>
	ether 7e:b9:7f:bc:5b:55
	media: autoselect
	status: active
en0: flags=8863<UP,BROADCAST,SMART,RUNNING,SIMPLEX,MULTICAST> mtu 1500
	options=400<CHANNEL_IO>
	ether f0:18:98:66:4e:4a
	nd6 options=201<PERFORMNUD,DAD>
	media: autoselect (<unknown type>)
	status: inactive
p2p0: flags=8802<BROADCAST,SIMPLEX,MULTICAST> mtu 2304
	options=400<CHANNEL_IO>
	ether 02:18:98:66:4e:4a
	media: autoselect
	status: inactive
awdl0: flags=8902<BROADCAST,PROMISC,SIMPLEX,MULTICAST> mtu 1484
	options=400<CHANNEL_IO>
	ether 2e:50:ca:57:6f:f3
	nd6 options=201<PERFORMNUD,DAD>
	media: autoselect
	status: inactive
llw0: flags=8863<UP,BROADCAST,SMART,RUNNING,SIMPLEX,MULTICAST> mtu 1500
	options=400<CHANNEL_IO>
	ether 2e:50:ca:57:6f:f3
	nd6 options=201<PERFORMNUD,DAD>
	media: autoselect
	status: inactive
en9: flags=8863<UP,BROADCAST,SMART,RUNNING,SIMPLEX,MULTICAST> mtu 1500
	options=400<CHANNEL_IO>
	ether 60:63:4c:e2:c5:40
	inet6 fe80::14ec:ed2d:21b4:b61b%en9 prefixlen 64 secured scopeid 0x17
	inet 192.168.0.107 netmask 0xffffff00 broadcast 192.168.0.255
	nd6 options=201<PERFORMNUD,DAD>
	media: autoselect
	status: active
bridge100: flags=8863<UP,BROADCAST,SMART,RUNNING,SIMPLEX,MULTICAST> mtu 1500
	options=3<RXCSUM,TXCSUM>
	ether f2:18:98:66:ae:64
	inet 192.168.2.1 netmask 0xffffff00 broadcast 192.168.2.255
	inet6 fe80::189b:b00f:e7dd:ca06%bridge100 prefixlen 64 secured scopeid 0x18
	Configuration:
		id 0:0:0:0:0:0 priority 0 hellotime 0 fwddelay 0
		maxage 0 holdcnt 0 proto stp maxaddr 100 timeout 1200
		root id 0:0:0:0:0:0 priority 0 ifcost 0 port 0
		ipfilter disabled flags 0x0
	member: ap1 flags=3<LEARNING,DISCOVER>
	        ifmaxaddr 0 port 9 priority 0 path cost 0
	nd6 options=201<PERFORMNUD,DAD>
	media: autoselect
	status: active
utun3: flags=8051<UP,POINTOPOINT,RUNNING,MULTICAST> mtu 1380
	inet6 fe80::e824:19e4:2cec:20bb%utun3 prefixlen 64 scopeid 0x19
	nd6 options=201<PERFORMNUD,DAD>
utun4: flags=8051<UP,POINTOPOINT,RUNNING,MULTICAST> mtu 1380
	inet6 fe80::cdfc:de2:a0a6:2eac%utun4 prefixlen 64 scopeid 0x1a
	nd6 options=201<PERFORMNUD,DAD>
utun2: flags=8051<UP,POINTOPOINT,RUNNING,MULTICAST> mtu 9000
	inet 198.18.0.1 --> 198.18.0.1 netmask 0xffff0000
```
netstat -nr
```
Routing tables

Internet:
Destination        Gateway            Flags        Netif Expire
default            192.168.0.1        UGSc           en9
default            link#24            UCSI       bridge1      !
1                  198.18.0.1         UGSc         utun2
2/7                198.18.0.1         UGSc         utun2
4/6                198.18.0.1         UGSc         utun2
8/5                198.18.0.1         UGSc         utun2
16/4               198.18.0.1         UGSc         utun2
32/3               198.18.0.1         UGSc         utun2
64/2               198.18.0.1         UGSc         utun2
127                127.0.0.1          UCS            lo0
127.0.0.1          127.0.0.1          UH             lo0
128.0/1            198.18.0.1         UGSc         utun2
169.254            link#23            UCS            en9      !
192.168.0          link#23            UCS            en9      !
192.168.0.1/32     link#23            UCS            en9      !
192.168.0.1        74:da:88:21:50:d9  UHLWIir        en9   1200
192.168.0.103      d8:8f:76:b9:e0:16  UHLWI          en9   1190
192.168.0.107/32   link#23            UCS            en9      !
192.168.0.255      ff:ff:ff:ff:ff:ff  UHLWbI         en9      !
192.168.2          link#24            UC         bridge1      !
192.168.2.255      ff.ff.ff.ff.ff.ff  UHLWbI     bridge1      !
198.18.0/16        198.18.0.1         UGSc         utun2
198.18.0.1         198.18.0.1         UH           utun2
224.0.0/4          link#23            UmCS           en9      !
224.0.0.251        1:0:5e:0:0:fb      UHmLWI         en9
239.255.255.250    1:0:5e:7f:ff:fa    UHmLWI         en9
255.255.255.255/32 link#23            UCS            en9      !
255.255.255.255    ff:ff:ff:ff:ff:ff  UHLWbI         en9      !

Internet6:
Destination                             Gateway                         Flags         Netif Expire
default                                 fe80::%utun0                    UGcI          utun0
default                                 fe80::%utun1                    UGcI          utun1
default                                 fe80::%utun3                    UGcI          utun3
default                                 fe80::%utun4                    UGcI          utun4
::1                                     ::1                             UHL             lo0
fe80::%lo0/64                           fe80::1%lo0                     UcI             lo0
fe80::1%lo0                             link#1                          UHLI            lo0
fe80::%en5/64                           link#8                          UCI             en5
fe80::aede:48ff:fe00:1122%en5           ac:de:48:0:11:22                UHLI            lo0
fe80::aede:48ff:fe33:4455%en5           ac:de:48:33:44:55               UHLWIi          en5
fe80::%utun0/64                         fe80::d39d:67e6:f09:f212%utun0  UcI           utun0
fe80::d39d:67e6:f09:f212%utun0          link#19                         UHLI            lo0
fe80::%utun1/64                         fe80::106d:17ef:56b2:d90b%utun1 UcI           utun1
fe80::106d:17ef:56b2:d90b%utun1         link#20                         UHLI            lo0
fe80::%en9/64                           link#23                         UCI             en9
fe80::14ec:ed2d:21b4:b61b%en9           60:63:4c:e2:c5:40               UHLI            lo0
fe80::%bridge100/64                     link#24                         UCI        bridge10
fe80::fa:55d8:af1b:e743%bridge100       f2.18.98.66.ae.64               UHLI            lo0
fe80::%utun3/64                         fe80::e824:19e4:2cec:20bb%utun3 UcI           utun3
fe80::e824:19e4:2cec:20bb%utun3         link#25                         UHLI            lo0
fe80::%utun4/64                         fe80::cdfc:de2:a0a6:2eac%utun4  UcI           utun4
fe80::cdfc:de2:a0a6:2eac%utun4          link#26                         UHLI            lo0
ff01::%lo0/32                           ::1                             UmCI            lo0
ff01::%en5/32                           link#8                          UmCI            en5
ff01::%en0/32                           link#10                         UmCI            en0
ff01::%awdl0/32                         link#12                         UmCI          awdl0
ff01::%llw0/32                          link#13                         UmCI           llw0
ff01::%utun0/32                         fe80::d39d:67e6:f09:f212%utun0  UmCI          utun0
ff01::%utun1/32                         fe80::106d:17ef:56b2:d90b%utun1 UmCI          utun1
ff01::%en9/32                           link#23                         UmCI            en9
ff01::%bridge100/32                     link#24                         UmCI       bridge10
ff01::%utun3/32                         fe80::e824:19e4:2cec:20bb%utun3 UmCI          utun3
ff01::%utun4/32                         fe80::cdfc:de2:a0a6:2eac%utun4  UmCI          utun4
ff02::%lo0/32                           ::1                             UmCI            lo0
ff02::%en5/32                           link#8                          UmCI            en5
ff02::%en0/32                           link#10                         UmCI            en0
ff02::%awdl0/32                         link#12                         UmCI          awdl0
ff02::%llw0/32                          link#13                         UmCI           llw0
ff02::%utun0/32                         fe80::d39d:67e6:f09:f212%utun0  UmCI          utun0
ff02::%utun1/32                         fe80::106d:17ef:56b2:d90b%utun1 UmCI          utun1
ff02::%en9/32                           link#23                         UmCI            en9
ff02::%bridge100/32                     link#24                         UmCI       bridge10
ff02::%utun3/32                         fe80::e824:19e4:2cec:20bb%utun3 UmCI          utun3
ff02::%utun4/32                         fe80::cdfc:de2:a0a6:2eac%utun4  UmCI          utun4
```

電腦和手機連同一個路由器時，將手機的網關改成電腦可以翻牆。電腦連路由器，再透過另一個網口分享網絡給手機時才會失敗。推測可能是 `bridge100` 的原因。感謝作者熱心答覆，我再試試其他非 tun 方案吧，先 close 了。
