### ISSUE TITLE
规则匹配问题？

### ISSUE THREAD

**Issue by mervynsword** [Dreamacro/clash#752]
最近测试了使用Clash作为透明网关，目前比较突出的问题是规则匹配比较迷。
我使用树莓派搭建了测试环境，系统为archlinux，滚动更新至最新版本，clash中的代理全部为v2ray。
比方说同样是使用onedrive下载文件，在web面板中的connection和log看到的匹配有时是url，有时是ip地址。

目前不太清楚规则匹配逻辑和DNS部分，为什么规则匹配会这么随机？如何避免？
匹配到proxy的url地址，在解析时是否会像原生V2RAY一样，域名解析也传递至vps端进行？
目前解析这么随意，是否会影响到url解析？比方说匹配到proxy规则的url其实是先在本地dns进行解析，得到匹配到proxy规则的IP地址，再使用代理进行连接。这样可能会导致解析得到的IP地址其实对VPS来说距离很远，导致性能下降。

**Comment by Dreamacro** [comment]
作为透明网关，所有的 dns 流量必须流经 clash （或是先流经 clash），不存在任何「随意匹配」，把域名发往代理是基本操作（udp 除外）

**Comment by mervynsword** [comment]
看来我并没有表达明白我的意思，我的意思是，在处理DNS请求之前就先进行规则匹配。

比方说我要访问youtube，那么在浏览器中输入网址，我希望达成的效果是，youtube相关域名因为符合走proxy的规则，所以其DNS解析也经由proxy传至代理服务器端进行，从而一次性得到最符合服务器端网络情况的解析结果。

根据我搭建在本地的dnscrypt-proxy的log记录，现在是clash先使用本地dns对youtube所有相关域名进行解析，得到的IP地址是香港，所以虽然代理服务器端在美国，但是却走代理连接香港的IP地址，相当于跨国太平洋一来一回。

附上目前的config.yaml，如果是我设置的问题，烦请指教，感激不尽。

```
port: 7890
socks-port: 7891
redir-port: 7892
allow-lan: true

mode: Rule

log-level: info

external-controller: 0.0.0.0:9090

secret: ""

external-ui: dashboard

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:53
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  nameserver:
    - 192.168.1.2

Proxy Group: 
  - 

proxies:
  # vmess
  # cipher support auto/aes-128-gcm/chacha20-poly1305/none
  - 

rules:
```
