### ISSUE TITLE
[Bug] 经clash直连，iOS端微博和快手APP的视频或视频封面无法加载[附图]

### ISSUE THREAD

**Issue by qiangd6** [Dreamacro/clash#753]
在提交之前，请确认：

- [ YES ] 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [ YES ] 这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 Openclash、Koolclash 等）的特定问题
- [ YES ] 我已经使用 Clash core 的 dev 分支版本测试过，问题依旧存在
- [ 不会自己debug ] 如果你可以自己 debug 并解决的话，提交 PR 吧！

请注意，如果你并没有遵照这个 issue template 填写内容，我们将直接关闭这个 issue。

我都确认过了，我要继续提交。
------------------------------------------------------------------

请附上任何可以帮助我们解决这个问题的信息，如果我们收到的信息不足，我们将对这个 issue 加上 
### clash core config

```
port: 8888
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: 127.0.0.1:9090
Proxy:
Proxy Group:
  - name: 🎯 全球直连
    type: select
    proxies:
      - DIRECT

Rule:
 - DOMAIN-SUFFIX,local,🎯 全球直连
 - IP-CIDR,192.168.0.0/16,🎯 全球直连,no-resolve
 - IP-CIDR,10.0.0.0/8,🎯 全球直连,no-resolve
 - IP-CIDR,172.16.0.0/12,🎯 全球直连,no-resolve
 - IP-CIDR,127.0.0.0/8,🎯 全球直连,no-resolve
 - IP-CIDR,100.64.0.0/10,🎯 全球直连,no-resolve
 - IP-CIDR6,::1/128,🎯 全球直连,no-resolve
 - IP-CIDR6,fc00::/7,🎯 全球直连,no-resolve
 - IP-CIDR6,fe80::/10,🎯 全球直连,no-resolve
 - IP-CIDR6,fd00::/8,🎯 全球直连,no-resolve
 - DOMAIN-KEYWORD,1drv,Ⓜ️ 微软服务
 - DOMAIN-KEYWORD,microsoft,Ⓜ️ 微软服务
 - DOMAIN-SUFFIX,aadrm.com,Ⓜ️ 微软服务
 - DOMAIN-SUFFIX,acompli.com,Ⓜ️ 微软服务
 - DOMAIN-SUFFIX,acompli.net,Ⓜ️ 微软服务
 - DOMAIN-SUFFIX,zhuihd.com,🎯 全球直连
 - DOMAIN,download.jetbrains.com,🎯 全球直连
 - DOMAIN,images-cn.ssl-images-amazon.com,🎯 全球直连
 - DOMAIN,cdn.angruo.com,🎯 全球直连
 - IP-CIDR,119.28.28.28/32,🎯 全球直连,no-resolve
 - DOMAIN-SUFFIX,smtp,🎯 全球直连
 - DOMAIN-KEYWORD,aria2,🎯 全球直连
 - GEOIP,CN,🎯 全球直连


……
```

### Clash log

```
time="2020-06-19T01:50:39Z" level=warning msg="dial 🎯 全球直连 error: dial tcp4 117.147.183.2:80: socket: too many open files"
time="2020-06-19T01:50:39Z" level=warning msg="dial 🎯 全球直连 error: dial tcp4 117.147.183.1:80: socket: too many open files"
time="2020-06-19T01:50:39Z" level=warning msg="dial 🎯 全球直连 error: dial tcp4 112.13.83.239:80: socket: too many open files"
time="2020-06-19T01:50:39Z" level=warning msg="dial 🎯 全球直连 error: dial tcp4 117.147.183.1:80: socket: too many open files"
time="2020-06-19T01:50:39Z" level=warning msg="dial 🎯 全球直连 error: dial tcp4 117.147.183.2:80: socket: too many open files"
time="2020-06-19T01:50:40Z" level=warning msg="dial 🎯 全球直连 error: dial tcp4 120.199.94.27:80: socket: too many open files"
time="2020-06-19T01:50:40Z" level=warning msg="dial 🎯 全球直连 error: dial tcp4 112.13.83.239:80: socket: too many open files"
time="2020-06-19T01:50:40Z" level=warning msg="dial 🎯 全球直连 error: dial tcp4 112.13.83.239:80: socket: too many open files"
time="2020-06-19T01:50:40Z" level=warning msg="dial 🎯 全球直连 error: dial tcp4 112.13.83.239:80: socket: too many open files"
time="2020-06-19T01:50:40Z" level=warning msg="dial 🎯 全球直连 error: dial tcp4 103.107.217.69:80: socket: too many open files"
time="2020-06-19T01:50:40Z" level=warning msg="dial 🎯 全球直连 error: dial tcp4 103.107.217.69:80: socket: too many open files"
time="2020-06-19T01:50:40Z" level=warning msg="dial 🎯 全球直连 error: dial tcp4 117.147.183.1:80: socket: too many open files"


time="2020-06-19T01:50:41Z" level=warning msg="dial 🎯 全球直连 error: dial tcp4 117.147.183.2:80: i/o timeout"
time="2020-06-19T01:50:41Z" level=warning msg="dial 🎯 全球直连 error: dial tcp4 112.13.83.240:80: i/o timeout"
time="2020-06-19T01:50:41Z" level=warning msg="dial 🎯 全球直连 error: dial tcp4 117.147.183.1:80: i/o timeout"
time="2020-06-19T01:50:41Z" level=warning msg="dial 🎯 全球直连 error: dial tcp4 117.147.183.2:80: i/o timeout"
……
```

### 环境 Environment

* Clash Core 的操作系统 (the OS that the Clash core is running on)
x86-64 OpenWrt
* 使用者的操作系统 (the OS running on the client)
iOS 13.3
* 网路环境或拓扑 (network conditions/topology)
家庭openwrt主路由使用clash，自己iOS手机作为客户端，经过DHCP连接openwrt主路由
* iptables，如果适用 (if applicable)
……
* ISP 有没有进行 DNS 污染 (is your ISP performing DNS pollution?)
有，但不影响这个case，因为是直连国内网站时的问题
* 其他
……

### 说明 Description

iOS的微博APP和快手APP，走clash的DIRECT的策略时，无法加载视频或者视频封面，log中出现time out或者too many connections的情况；同样是这两个APP，不经过clash，在同一个网络里直连，一切正常，因此考虑是clash的DIRECT功能中的bug

### 重现问题的具体布骤 Steps to Reproduce

1. 准备一个openwrt x86-64的软路由，在上面安装最新版clash，config.yaml中设定国内网站走DIRECT模式
2. 使用iOS手机，下载快手和微博APP
3. 在微博上尝试打开有视频的微博内容，或者在快手APP的首页，查看多个视频封面时，问题出现，无法加载

**我预期会发生……？**
微博视频应正常播放，快手APP首页的视频封面应正常显示

**实际上发生了什麽？**
未正常播放，未正常显示，如图所示：

![image](https://user-images.githubusercontent.com/6195267/85089414-2f8c4280-b215-11ea-8128-f85dc6136e5f.png)

![image](https://user-images.githubusercontent.com/6195267/85089425-3450f680-b215-11ea-8b05-02f7d9555b45.png)
