### ISSUE TITLE
[Feature]rule-provider在http模式下，应调用内置DNS解析地址

### ISSUE THREAD

**Issue by Yuanandyuan** [Dreamacro/clash#756]
感谢你向 Clash Core 提交 Feature Request！
在提交之前，请确认：

- [x] 我已经在 [Issue Tracker](……/) 中找过我要提出的请求

请注意，如果你并没有遵照这个 issue template 填写内容，我们将直接关闭这个 issue。

我都确认过了，我要继续提交。

------------------------------------------------------------------

请附上任何可以帮助我们解决这个问题的信息，如果我们收到的信息不足，我们将对这个 issue 加上 *Needs more information* 标记并在收到更多资讯之前关闭 issue。

### Clash core config

```
mixed-port: 7890
allow-lan: false
mode: rule
log-level: info
external-controller: 127.0.0.1:9090
secret: ''

proxy-providers:
  SUb:
    type: http
    url: $url
    interval: 7200
    path: ./Proxy/Sub.yaml
    health-check:
      enable: true
      interval: 300
      url: http://www.gstatic.com/generate_204

proxy-groups:
  - name: Proxy
    type: select
    proxies:
      - Auto-test
    use:
      - Sub

  - name: Others
    type: select
    proxies:
      - Proxy
      - DIRECT

  - name: Auto-test
    type: url-test
    use:
      - Sub
    url: http://www.gstatic.com/generate_204
    interval: 300

  - name: Global
    type: select
    proxies:
      - Proxy
      - DIRECT
    use:
      - Sub

  - name: China
    type: select
    proxies:
      - DIRECT
      - Proxy

  - name: PayPal
    type: select
    proxies:
      - DIRECT
      - Proxy
  
  - name: Scholar
    type: select
    proxies:
      - DIRECT
      - Proxy

  - name: Telegram
    type: select
    proxies:
      - Proxy
      - DIRECT
    use:
      - Sub

  - name: Apple
    type: select
    proxies:
      - DIRECT
      - Proxy
    use:
      - Sub
  - name: Steam
    type: select
    proxies:
      - DIRECT
      - Proxy
    use:
      - Sub

  - name: OneDrive
    type: select
    proxies:
      - Proxy
      - DIRECT
    use:
      - Sub

  - name: Streaming
    type: select
    proxies:
      - Proxy
      - DIRECT
    use:
      - Sub

rule-providers:

  Global:
    type: http
    behavior: classical
    path: ./RuleSet/Global.yaml
    url: https://raw.githubusercontent.com/DivineEngine/Profiles/master/Clash/RuleSet/Global.yaml
    interval: 86400

  China:
    type: http
    behavior: classical
    path: ./RuleSet/China.yaml
    url: https://raw.githubusercontent.com/DivineEngine/Profiles/master/Clash/RuleSet/China.yaml
    interval: 86400

  ChinaIP:
    type: http
    behavior: ipcidr
    path: ./RuleSet/Extra/ChinaIP.yaml
    url: https://raw.githubusercontent.com/DivineEngine/Profiles/master/Clash/RuleSet/Extra/ChinaIP.yaml
    interval: 86400

  PayPal:
    type: http
    behavior: classical
    path: ./RuleSet/Extra/PayPal.yaml
    url: https://raw.githubusercontent.com/DivineEngine/Profiles/master/Clash/RuleSet/Extra/PayPal.yaml
    interval: 86400

  Scholar:
    type: http
    behavior: classical
    path: ./RuleSet/Extra/Scholar.yaml
    url: https://raw.githubusercontent.com/DivineEngine/Profiles/master/Clash/RuleSet/Extra/Scholar.yaml
    interval: 86400

  Telegram:
    type: http
    behavior: classical
    path: ./RuleSet/Extra/Telegram/Telegram.yaml
    url: https://raw.githubusercontent.com/DivineEngine/Profiles/master/Clash/RuleSet/Extra/Telegram/Telegram.yaml
    interval: 86400

  Apple:
    type: http
    behavior: classical
    path: ./RuleSet/Extra/Apple/Apple.yaml
    url: https://raw.githubusercontent.com/DivineEngine/Profiles/master/Clash/RuleSet/Extra/Apple/Apple.yaml
    interval: 86400
  
  Steam:
    type: http
    behavior: classical
    path: ./RuleSet/Extra/Game/Steam.yaml
    url: https://raw.githubusercontent.com/DivineEngine/Profiles/master/Clash/RuleSet/Extra/Game/Steam.yaml
    interval: 86400

  OneDrive:
    type: http
    behavior: classical
    path: ./RuleSet/Extra/Microsoft/OneDrive.yaml
    url: https://raw.githubusercontent.com/DivineEngine/Profiles/master/Clash/RuleSet/Extra/Microsoft/OneDrive.yaml
    interval: 86400

  Streaming:
    type: http
    behavior: classical
    path: ./RuleSet/StreamingMedia/Streaming.yaml
    url: https://raw.githubusercontent.com/DivineEngine/Profiles/master/Clash/RuleSet/StreamingMedia/Streaming.yaml
    interval: 86400

# 规则
rules:
  - RULE-SET,Apple,Apple
  - RULE-SET,OneDrive,OneDrive
  - RULE-SET,PayPal,PayPal
  - RULE-SET,Scholar,Scholar
  - RULE-SET,Telegram,Telegram
  - RULE-SET,Steam,Steam
  - RULE-SET,Streaming,Streaming
  - RULE-SET,Global,Global
  - RULE-SET,China,China

  # Local Area Network
  - IP-CIDR,192.168.0.0/16,DIRECT
  - IP-CIDR,10.0.0.0/8,DIRECT
  - IP-CIDR,172.16.0.0/12,DIRECT
  - IP-CIDR,127.0.0.0/8,DIRECT
  - IP-CIDR,100.64.0.0/10,DIRECT
  - IP-CIDR,224.0.0.0/4,DIRECT

  # ChinaIP
  - RULE-SET,ChinaIP,China

  # Final
  - MATCH,Others
```

### Clash log

```
……
```

### 环境 Environment

* Clash Core 的操作系统 (the OS that the Clash core is running on)
Windows 10 2004
* 使用者的操作系统 (the OS running on the client)
Windows 10 2004
* 网路环境或拓扑 (network conditions/topology)
……
* iptables，如果适用 (if applicable)
……
* ISP 有没有进行 DNS 污染 (is your ISP performing DNS pollution?)
……
* 其他
……

### 说明 Description

现在Clash在下载rule-provider中的配置文件时会直接调用系统DNS解析地址，一般情况下不会出现问题。但当对本机设置了透明代理并使用Fake IP模式时，上述解析的地址是一个Fake IP地址，然而Clash内核发出的流量又直接从设置的Interface name对应的网卡发出，不经过Clash处理，导致文件下载失败。这一问题可以通过配置fake-ip-filter解决，但仍希望开发者可以考虑让rule-provider调用内置DNS进行解析。
