### ISSUE TITLE
[Bug] Clash Premium rule-providers 配置检查不通过

### ISSUE THREAD

**Issue by kuyagic** [Dreamacro/clash#768]
感谢你向 Clash Core 提交 issue！
在提交之前，请确认：

- [x] 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [x] 这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 Openclash、Koolclash 等）的特定问题
- [ ] 我已经使用 Clash core 的 dev 分支版本测试过，问题依旧存在
- [ ] 如果你可以自己 debug 并解决的话，提交 PR 吧！

请注意，如果你并没有遵照这个 issue template 填写内容，我们将直接关闭这个 issue。

Clash 版本
```
root@zmbox:/opt/config/clash# clash -v
Clash 2020.06.27 linux amd64 2020年 6月27日 星期六 13时19分54秒 UTC
```

我都确认过了，我要继续提交。

------------------------------------------------------------------

请附上任何可以帮助我们解决这个问题的信息，如果我们收到的信息不足，我们将对这个 issue 加上 *Needs more information* 标记并在收到更多资讯之前关闭 issue。

### clash core config

```
port: 3128
socks-port: 1789
redir-port: 54321
allow-lan: true
#mixed-port: 7890
# bind-address: "127.0.0.1"


mode: rule

log-level: info
# log-level: silent

external-ui: ./ui
#external-controller: ''
# secret: ""

experimental:
  ignore-resolve-fail: true 


# authentication:
#  - "user1:pass1"
#  - "user2:pass2"

hosts:
  '*.clash.dev': '127.0.0.1'
dns:
  enable: false
  ipv6: false
  listen: 127.0.0.9:53
  #redir-host # 或 fake-ip
  enhanced-mode: redir-host

  nameserver:
     - 1.2.4.8
     - 114.114.114.114
     - 223.5.5.5
     #- https://dns.rubyfish.cn/dns-query
     
  fallback: 
     - tls://dns.rubyfish.cn:853
     - tls://9.9.9.9:853

# proxy provider start here
proxy-providers:
  duyaoo-local:
    type: file
    path: ./proxy.d/duyaoo.yaml
    url: ''
    interval: 600
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300
#  duyaoo-online:
#    type: http
#    path: ./conf.d/online.yaml
#    url: ''
#    interval: 3600
#    health-check:
#      enable: true
#      url: http://www.gstatic.com/generate_204
#      interval: 300
# proxy provider end
     

proxy-groups:
  - name: use-proxy
    type: select
    use:
      - duyaoo-local
      
rule-providers:
  #name of the provider
  name: ad-block
    # type of the provider, it can be a HTTP or a File  <<<<--- Line 77
    type: http
    # the type of rules
    behavior: classical
    # where is the file, ./ relative to clash home
    path: ./rule.d/ad.yaml
    # only available when type is HTTP, where to download a file. You don't need to create a new file in local space.
    url: 'https://binary.duyao.de/clash/rule.d/ad.yaml'
    # auto-update interval,only available when type is HTTP
    interval: 600
  name: lan
    # type of the provider, it can be a HTTP or a File
    type: http
    # the type of rules
    behavior: classical
    # where is the file, ./ relative to clash home
    path: ./rule.d/lan.yaml
    # only available when type is HTTP, where to download a file. You don't need to create a new file in local space.
    url: '<hidden>'
    # auto-update interval,only available when type is HTTP
    interval: 600
  name: china
    # type of the provider, it can be a HTTP or a File
    type: http
    # the type of rules
    behavior: classical
    # where is the file, ./ relative to clash home
    path: ./rule.d/lan.yaml
    # only available when type is HTTP, where to download a file. You don't need to create a new file in local space.
    url: '<hidden>'
    # auto-update interval,only available when type is HTTP
    interval: 600
  name: proxy
    # type of the provider, it can be a HTTP or a File
    type: http
    # the type of rules
    behavior: classical
    # where is the file, ./ relative to clash home
    path: ./rule.d/lan.yaml
    # only available when type is HTTP, where to download a file. You don't need to create a new file in local space.
    url: '<hidden>'
    # auto-update interval,only available when type is HTTP
    interval: 600
        
rules:
  - RULE-SET,ad-block,REJECT
  - RULE-SET,china,DRIECT
  - RULE-SET,lan,DRIECT
  - RULE-SET,proxy,use-proxy
  
  # Apple
  - DOMAIN-SUFFIX,apps.apple.com,use-proxy
  - DOMAIN-SUFFIX,music.apple.com,DIRECT
  - DOMAIN-SUFFIX,icloud.com,DIRECT
  - DOMAIN-SUFFIX,icloud-content.com,DIRECT
  - DOMAIN-SUFFIX,me.com,DIRECT
  - DOMAIN-SUFFIX,mzstatic.com,DIRECT
  - DOMAIN-SUFFIX,akadns.net,DIRECT
  - DOMAIN-SUFFIX,aaplimg.com,DIRECT
  - DOMAIN-SUFFIX,cdn-apple.com,DIRECT
  - DOMAIN-SUFFIX,apple.com,DIRECT
  - DOMAIN-SUFFIX,apple-cloudkit.com,DIRECT
  - DOMAIN,hls.itunes.apple.com,use-proxy
  
  #注释此选项有助于大多数App开发者分析崩溃信息；如果您拒绝一切崩溃数据统计、搜集，请取消 # 注释。
  #- DOMAIN,e.crashlytics.com,REJECT   
  
  # 最终规则
  - GEOIP,CN,DIRECT
  - MATCH,use-proxy
  
```

### Clash log

```
root@zmbox:/opt/config/clash# clash -t -d .
ERRO[0000] yaml: line 77: did not find expected key
configuration file /opt/config/clash/config.yaml test failed
```
配置文件节点部分已经标出 77行
### 环境 Environment

* Clash Core 的操作系统 (the OS that the Clash core is running on)
Debian 9 x86_64
* 使用者的操作系统 (the OS running on the client)
Debian 9 x86_64
* 网路环境或拓扑 (network conditions/topology)
……
* iptables，如果适用 (if applicable)
……
* ISP 有没有进行 DNS 污染 (is your ISP performing DNS pollution?)
……
* 其他
……

### 说明 Description
使用 闭源版本 根据 [这里]( https://lancellc.gitbook.io/clash/clash-config-file/rule-provider#example-of-a-rule-provider-file) 的例子 使用 rule-providers 配置 规则, 然后测试配置文件时候 报错.

**Comment by Dreamacro** [comment]
```yaml
rule-providers:
  ad-block:
    type: http
    behavior: classical
    path: ./rule.d/ad.yaml
    url: 'https://binary.duyao.de/clash/rule.d/ad.yaml'
    interval: 600
 
```
