### ISSUE TITLE
[Feature] 关于 TUN + redirt-host 下设置 hosts 的一些问题

### ISSUE THREAD

**Issue by liby** [Dreamacro/clash#774]
感谢你向 Clash Core 提交 Feature Request！
在提交之前，请确认：

- [x] 我已经在 [Issue Tracker](……/) 中找过我要提出的请求

请注意，如果你并没有遵照这个 issue template 填写内容，我们将直接关闭这个 issue。

我都确认过了，我要继续提交。

------------------------------------------------------------------

请附上任何可以帮助我们解决这个问题的信息，如果我们收到的信息不足，我们将对这个 issue 加上 *Needs more information* 标记并在收到更多资讯之前关闭 issue。

### Clash core config

<details>
  <summary>config.yaml</summary>

  ```yaml
  # 本地端 HTTP(S)代理服务器端口
  port: 7890

  # 本地端 SOCKS5 代理服务器端口
  socks-port: 7891

  # Linux 和 macOS 的透明代理服务器端口
  redir-port: 7892

  # HTTP(S) 和 SOCKS5 代理服务器共用端口
  # mixed-port: 7890

  # 本地 SOCKS5/HTTP(S) 服务器验证
  # authentication:
  #  - "user1:pass1"
  #  - "user2:pass2"

  # 设置为 true 以允许从其他 LAN IP 地址连接到本地端服务器
  allow-lan: false

  # 仅适用于设置 allow-lan 为 true 时
  # '*': 绑定所有 IP 地址
  # 192.168.122.11: 绑定一个 IPv4 地址
  # "[aaaa::a8aa:ff:fe09:57d8]": 绑定一个 IPv6 地址
  bind-address: '*'

  # Clash router working mode
  # rule: rule-based packet routing
  # global: all packets will be forwarded to a single endpoint
  # direct: directly forward the packets to the Internet
  mode: rule

  # Clash by default prints logs to STDOUT
  # info / warning / error / debug / silent
  log-level: info

  # When set to false, resolver won't translate hostnames to IPv6 addresses
  ipv6: true

  # RESTful web API listening address
  external-controller: 127.0.0.1:9090

  # A relative path to the configuration directory or an absolute path to a
  # directory in which you put some static web resource. Clash core will then
  # serve it at `${API}/ui`.
  # external-ui: folder

  # Secret for the RESTful API (optional)
  # Authenticate by spedifying HTTP header `Authorization: Bearer ${secret}`
  # ALWAYS set a secret if RESTful API is listening on 0.0.0.0
  # secret: ""

  # Outbound interface name
  # interface-name: en0

  # Static hosts for DNS server and connection establishment, only works
  # when `dns.enhanced-mode` is `redir-host`.
  #
  # Wildcard hostnames are supported (e.g. *.clash.dev, *.foo.*.example.com)
  # Non-wildcard domain names has a higher priority than wildcard domain names
  # e.g. foo.example.com > *.example.com > .example.com
  # P.S. +.foo.com equals to .foo.com and foo.com
  hosts:
    'mtalk.google.com': 108.177.125.188
    "dns.alidns.com": 223.5.5.5
    'local.right.de': 127.0.0.1
    'router.asus.com': 192.168.50.1

    # '*.clash.dev': 127.0.0.1
    # '.dev': 127.0.0.1
    # 'alpha.clash.dev': '::1'

  # DNS server settings
  # This section is optional. When not present, DNS server will be disabled.
  dns:
    enable: true
    listen: 0.0.0.0:53
    ipv6: false # when false, response to AAAA questions will be empty

    # These nameservers are used to resolve the DNS nameserver hostnames below.
    # Specify IP addresses only
    default-nameserver:
      - 114.114.114.114
      - 8.8.8.8
    enhanced-mode: redir-host # or fake-ip
    fake-ip-range: 198.18.0.1/16 # Fake IP addresses pool CIDR

    # Hostnames in this list will not be resolved with fake IPs
    # i.e. questions to these domain names will always be answered with their
    # real IP addresses
    # fake-ip-filter:
    #   - '*.lan'
    #   - localhost.ptlogin2.qq.com

    # Supports UDP, TCP, DoT, DoH. You can specify the port to connect to.
    # All DNS questions are sent directly to the nameserver, without proxies
    # involved. Clash answers the DNS question with the first result gathered.
    nameserver:
      - 114.114.114.114 # default value
      - 8.8.8.8 # default value
      - 119.29.29.29 # Tencent DNS: UDP
      - https://dns.alidns.com/dns-query # DNS over HTTPS
      - tls://dns.rubyfish.cn:853 # DNS over TLS

    # When `fallback` is present, the DNS server will send concurrent requests
    # to the servers in this section along with servers in `nameservers`.
    # The answers from fallback servers are used when the GEOIP country
    # is not `CN`.
    fallback:
      - 77.88.8.88
      - 208.67.222.222
      - https://dns.adguard.com/dns-query
      - tls://dns.google:853

    # If IP addresses resolved with servers in `nameservers` are in the specified
    # subnets below, they are considered invalid and results from `fallback`
    # servers are used instead.
    #
    # IP address resolved with servers in `nameserver` is used when
    # `fallback-filter.geoip` is true and when GEOIP of the IP address is `CN`.
    #
    # If `fallback-filter.geoip` is false, results from `fallback` nameservers
    # are always used, and answers from `nameservers` are discarded.
    #
    # This is a countermeasure against DNS pollution attacks.
    fallback-filter:
      geoip: true
      ipcidr:
        # - 240.0.0.0/4

  tun:
    enable: true
    stack: system
    macOS-auto-route: true
    macOS-auto-detect-interface: true
    dns-hijack:
      # - 8.8.8.8:1053
      # - tcp://8.8.8.8:53

  proxies:
  # 支持的协议及加密算法示例请查阅 Clash 项目 README 以使用最新格式：https://github.com/Dreamacro/clash/blob/master/README.md

    # VMess(Websocket + TLS)
    - name: "GCP"
      type: vmess
      server: vmess.com
      port: 443
      uuid: a5845733-e21s-4f4c-bdff-13fbg3920bfc
      alterId: 29
      cipher: auto
      # udp: true
      tls: true
      # skip-cert-verify: true
      network: ws
      ws-path: /ray
      # ws-headers:
      # Host: v2ray.com

  # 服务器节点订阅
  proxy-providers:
    # name: # Provider 名称
    #   type: http # http 或 file
    #   path: # 文件路径
    #   url: # 只有当类型为 HTTP 时才可用，您不需要在本地空间中创建新文件。
    #   interval: # 自动更新间隔，仅在类型为 HTTP 时可用
    #   health-check: # 健康检查选项从此处开始
    #     enable:
    #     url:
    #     interval:

    #
    # 「url」参数填写订阅链接
    #
    # 订阅链接可以使用 API 进行转换，如：https://sub.dler.io/
    #
    # 1.模式选择「进阶模式」 2.填写订阅链接 3.勾选「输出为 Node List」 4.「生成订阅链接」
    #

  proxy-groups:
  # 策略组示例请查阅 Clash 项目 README 以使用最新格式：https://github.com/Dreamacro/clash/blob/master/README.md

  #
  # 策略组说明
  #
  # 「MATCH」类似 Surge 的「Final」，此处用于选择白名单模式(PROXY 策略)和黑名单模式(DIRECT 策略)
  #
  # 「Streaming」和「StreamingSE」比较好理解，有专用于流媒体的节点就设置到其中，如果没有「StreamingSE」的需求可以连带 Rule 部分一起删掉，「Streaming」需至少保留 Rule，用「PROXY」即可。
  #
  # 「PROXY」是代理规则策略，它可以指定为某个节点或嵌套一个其他策略组，如：「自动测试」、「Fallback」或「负载均衡」的策略组，关于这 3 个策略组的具体示例可以看官方示例：https://github.com/Dreamacro/clash
  #

    # Fallback 比较实用的策略组类型，用于测试服务器节点的可用性，当第一个节点不可用时切换到第二个，以此类推。
    - name: "Fallback"
      type: fallback
      proxies:
        - GCP
      url: 'http://www.gstatic.com/generate_204'
      interval: 300

    # 代理节点选择
    - name: "PROXY"
      type: select
      proxies:
        - Fallback
        - GCP

    # 白名单模式 PROXY, 黑名单模式 DIRECT, 不知道别动
    - name: "MATCH"
      type: select
      proxies:
        - PROXY
        - DIRECT

    # 国际流媒体服务
    - name: "Streaming"
      type: select
      proxies:
        - PROXY
        - GCP

    # 中国流媒体服务（面向海外版本）
    - name: "StreamingSE"
      type: select
      proxies:
        - DIRECT

    # 手动选择节点订阅
    # - name: "DuckDuckGo"
    #   type: select # 亦可使用 fallback 或 load-balance
    #   use:
    #     - DuckDuckGo-Sub

  # 关于 Rule Provider 请查阅：https://lancellc.gitbook.io/clash/clash-config-file/rule-provider

  rule-providers:
  # name: # Provider 名称
  #   type: http # http 或 file
  #   behavior: classical # 或 ipcidr、domain
  #   path: # 文件路径
  #   url: # 只有当类型为 HTTP 时才可用，您不需要在本地空间中创建新文件。
  #   interval: # 自动更新间隔，仅在类型为 HTTP 时可用

    Unbreak:
      type: http
      behavior: classical
      path: ./RuleSet/Unbreak.yaml
      url: https://raw.githubusercontent.com/DivineEngine/Profiles/master/Clash/RuleSet/Unbreak.yaml
      interval: 86400

    Streaming:
      type: http
      behavior: classical
      path: ./RuleSet/StreamingMedia/Streaming.yaml
      url: https://raw.githubusercontent.com/DivineEngine/Profiles/master/Clash/RuleSet/StreamingMedia/Streaming.yaml
      interval: 86400

    StreamingSE:
      type: http
      behavior: classical
      path: ./RuleSet/StreamingMedia/StreamingSE.yaml
      url: https://raw.githubusercontent.com/DivineEngine/Profiles/master/Clash/RuleSet/StreamingMedia/StreamingSE.yaml
      interval: 86400

    Global:
      type: http
      behavior: classical
      path: ./RuleSet/Global.yaml
      url: https://raw.githubusercontent.com/DivineEngine/Profiles/master/Clash/RuleSet/Global.yaml
      interval: 86400

    China:
      type: http
      behavior: classical
      path: ./RuleSet/China.yaml
      url: https://raw.githubusercontent.com/DivineEngine/Profiles/master/Clash/RuleSet/China.yaml
      interval: 86400

    ChinaIP:
      type: http
      behavior: ipcidr
      path: ./RuleSet/Extra/ChinaIP.yaml
      url: https://raw.githubusercontent.com/DivineEngine/Profiles/master/Clash/RuleSet/Extra/ChinaIP.yaml
      interval: 86400

  # 规则
  rules:
    # Unbreak
    - RULE-SET,Unbreak,DIRECT

    # Global Area Network

    # (Streaming Media)
    - RULE-SET,Streaming,Streaming

    # (StreamingSE)
    - RULE-SET,StreamingSE,StreamingSE

    # (DNS Cache Pollution) / (IP Blackhole) / (Region-Restricted Access Denied) / (Network Jitter)
    - RULE-SET,Global,PROXY

    # China Area Network
    - RULE-SET,China,DIRECT

    # Local Area Network
    - IP-CIDR,192.168.0.0/16,DIRECT
    - IP-CIDR,10.0.0.0/8,DIRECT
    - IP-CIDR,172.16.0.0/12,DIRECT
    - IP-CIDR,127.0.0.0/8,DIRECT
    - IP-CIDR,100.64.0.0/10,DIRECT
    - IP-CIDR,224.0.0.0/4,DIRECT

    # （可选）使用来自 ipipdotnet 的 ChinaIP 以解决数据不准确的问题，使用 ChinaIP.yaml 时可禁用下列直至（包括）「GEOIP,CN」规则
    - RULE-SET,ChinaIP,DIRECT
    # Tencent
    # - IP-CIDR,119.28.28.28/32,DIRECT
    # - IP-CIDR,182.254.116.0/24,DIRECT
    # GeoIP China
    # - GEOIP,CN,DIRECT

    - MATCH,MATCH
  ```
</details>

### Clash log

```
  2020-06-30 11:39:01[debug] [TUN] hijack udp dns: 198.18.0.2:53
  2020-06-30 11:39:01[debug] [DNS] resolve router.asus.com error: couldn't find ip
  2020-06-30 11:39:01[info] [TCP] 198.18.0.1:63706 --> router.asus.com match Match using MATCH[GCP]
```

### 环境 Environment

* Clash Core 的操作系统 (the OS that the Clash core is running on)
  - ClashX Pro Version 1.20.4.3 
* 使用者的操作系统 (the OS running on the client)
  - macOS 10.15.2
* 网路环境或拓扑 (network conditions/topology)
  - ASUS（192.168.50.1）拨号 -> K2P（192.168.27.1）桥接 -> mac 开启 Clash + TUN + redirt-host
* iptables，如果适用 (if applicable)
  - None
* ISP 有没有进行 DNS 污染 (is your ISP performing DNS pollution?)
  - None
* 其他
  - None

### 说明 Description

  1. 前端的话经常需要在本地起一些服务，像我工作中经常需要用到 `localhost:3000` 和 `local.right.de`
  2. 部分路由器厂商也会有一些将特定域名解析到局域网 IP 的操作，比如我生活中用的比较多的 `p.to` 以及 `router.asus.com` 等
  3. 在没有使用 TUN + redirt-host（我还是认为 TUN 的影响大一些）之前，我会使用以下几种方式（不定）来达到启用 proxy 时不影响 1 和 2 的目的
      - Chrome 插件 - SwitchyOmega
      - System Preferences - Network - Advanced - Proxies - Bypass proxy settings for these Hosts & Domains
  4. 相同问题有很多：#444、#495、#636、#759，解决办法也有以下几种：
      1. 关闭 Clash 的自定义 DNS — 简单粗暴，在我这里优先级比较低
      2. 设置 hosts，但是这里有一个问题，就是 #759 中提到的
          > 是支持的，只是 resolve 不到，没法到 tunnel 里反映射，你可能需要加一个能解析 router.asus.com 的 dns
      3. 使用自己/公司的 DNS 服务器 - 比较折腾，也存在一定问题：#722 中有提到
### 可能的解决方案 Possible Solution

个人认为 `支持用特定域名服务器来解析特定域名` 是一个好主意，可能这对于作者来说是「老生常谈」了，也看到过作者的回应
  > 暂时不打算做单域名对应 dns 解析，要做的东西有挺多的，按照目前的设计这种单独的配置会增加程序的复杂度
不过遇到此类问题的人还是比较多的，至今也没什么比较完美的解决方案，回过头来，这个地方是不是可以考虑一下
### 更多信息 More Information
redirt-host 下还是可以在本地启动服务的，但是开启 TUN 后连本地服务都启动不了了。全部识别为 198.18.0.xx 而导致失败，不知道该怎么解决

![未开启 TUN](https://user-images.githubusercontent.com/38807139/86083957-309f5880-bace-11ea-848f-c63931219b1c.png)

实际上未开启 TUN 时，即使把 hosts 中的 `local.right.de`删掉，也可以正常访问，不存在影响问题

**注：想访问 `router.asus.com`的话，redirt-host/Enhanced mode 和 default-nameserver 都要关闭/注释**

<details>
  <summary>config.yaml/hosts</summary>

  ```yaml
  hosts:
    'mtalk.google.com': 108.177.125.188
    'dns.alidns.com': 223.5.5.5
    # 'local.right.de': 127.0.0.1
    # 'router.asus.com': 192.168.50.1
  ```
</details>

<details>
  <summary>Clash log</summary>

  ```
  2020-06-30 12:42:59[debug] [DNS] local.right.de --> 127.0.0.1
  2020-06-30 12:42:59[info] [TCP] 127.0.0.1:50332 --> local.right.de match IPCIDR using DIRECT
  2020-06-30 12:42:59[debug] [DNS] local.right.de --> 127.0.0.1
  2020-06-30 12:42:59[debug] [DNS] local.right.de --> 127.0.0.1
  2020-06-30 12:42:59[debug] [DNS] local.right.de --> 127.0.0.1
  2020-06-30 12:42:59[debug] [DNS] local.right.de --> 127.0.0.1
  2020-06-30 12:42:59[debug] [DNS] local.right.de --> 127.0.0.1
  2020-06-30 12:42:59[debug] [DNS] local.rightl.de --> 127.0.0.1
  2020-06-30 12:42:59[info] [TCP] 127.0.0.1:50335 --> local.right.de match IPCIDR using DIRECT
  ```
</details>

---

开启 TUN 后
![开启 TUN 后](https://user-images.githubusercontent.com/38807139/86084079-8116b600-bace-11ea-963e-37f577dd11ea.png)
```
2020-06-30 13:17:39[debug] [DNS] local.right.de --> 127.0.0.1
2020-06-30 13:17:39[warning] dial DIRECT error: dial tcp4 192.168.50.49:0->127.0.0.1:9000: connect: connection refused
2020-06-30 13:17:44[debug] [TUN] hijack udp dns: 198.18.0.2:53
```

所以我认为开启 TUN 后设置 `hosts` 并不能起到作用 => 就算 DNS 没有解析到，也不应该解析为 198.18.0.X 吧（虽然开启 TUN 后，这个貌似是本地 IP？我也没整明白），此外如果设置 `nameserver` 的话，完全可以注释掉 `default-nameserver`。

不过这个问题还是想请你看一下，我说的可能比较乱，想到哪里说哪里，不好意思
