### ISSUE TITLE
Docker for Mac上，DNS在主机上没法访问

### ISSUE THREAD

**Issue by tony1016** [Dreamacro/clash#78]
在macOS上，使用docker启动clash，dns无法访问，命令是
```
docker run -d --name=clash --restart=always -p 7890:7890 -p 7891:7891 -p 7892:7892 -p 53:53/udp -v /Users/t.l/Google\ 云端硬盘/Services/clash/config.yml:/root/.config/clash/config.yml dreamacro/clash
```

**Comment by tony1016** [comment]
DNS相关配置如下
```
dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:53
  # enhanced-mode: redir-host
  nameserver:
     - 114.114.114.114
     - 223.5.5.5
     - tls://dns.rubyfish.cn:853 # dns over tls
  fallback: # 与 nameserver 内的服务器列表同时发起请求，当规则符合 GEOIP 在 CN 以外时，fallback 列表内的域名服务器生效。
     - 114.114.114.114
     - tls://dns.rubyfish.cn:853 # dns over tls
     - 8.8.8.8
     - 192.168.193.53
```

**Comment by Dreamacro** [comment]
我这里测试 `0.10.2` 是可以的，但是我这里也遇到了一个问题：你应该是使用了类似 `http://registry.docker-cn.com` 之类的镜像仓库吧？

我试着拉了一下 `latest` 但发现是旧版的 clash，但是指定版本号拉就没有问题，可能是由于缓存原因导致的。我在 VPS 上拉原始仓库的 `latest` 就没有问题。你可以先看看镜像日期是否正确。

**Comment by tony1016** [comment]
> 我这里测试 `0.10.2` 是可以的，但是我这里也遇到了一个问题：你应该是使用了类似 `http://registry.docker-cn.com` 之类的镜像仓库吧？
> 
> 我试着拉了一下 `latest` 但发现是旧版的 clash，但是指定版本号拉就没有问题，可能是由于缓存原因导致的。我在 VPS 上拉原始仓库的 `latest` 就没有问题。你可以先看看镜像日期是否正确。

并没有啊，我用的是hub.docker.com的镜像
```
dreamacro/clash                        latest              5cb569f307aa        7 days ago          16.6MB
```

不过很奇怪，我试了诸如dnscrypt-proxy这样的docker镜像，也是tcp是好的，udp失败，难道是我的Docker for Mac的问题？？

**Comment by Dreamacro** [comment]
我也是 docker for mac，我这里是 ok 的，我的 docker-compose.yml

```
version: '3'
services:
  clash:
    image: dreamacro/clash:0.10.2
    volumes:
      - ./config.yml:/root/.config/clash/config.yml
    ports:
      - "6667:7890"
      - "6668:7891"
      - "53:53/udp"
    restart: always
    network_mode: "bridge"
    container_name: clash
```
