### ISSUE TITLE
[help wanted] 开启 dns 后有些域名解析出错

### ISSUE THREAD

**Issue by vanppo** [Dreamacro/clash#783]
以前使用客户端，没有用过 clash 的 dns 功能，可以正常使用。今天试着在路由器上面配置透明代理，大部分域名都能正常访问，少数几个有问题。
```yaml
# https://github.com/Dreamacro/clash/wiki/configuration

mode: Rule

# mixed-port: 4096
redir-port: 4096

# silent / error / warning / info / debug
log-level: debug

allow-lan: true

# external-controller: 127.0.0.1:9090

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:5533
  enhanced-mode: fake-ip # redir-host | fake-ip
  # fake-ip-range: 192.18.0.1/16
  default-nameserver:
    - 8.8.4.4
    - 8.8.8.8
  nameserver:
    - 114.114.114.114
    - tls://dns.rubyfish.cn
  fallback:
    - tls://dns.rubyfish.cn
    - tls://dns.google
```
访问 Google 但是返回的证书却是 Facebook 的，推测是域名解析的结果有问题。试着清除了 DNS 缓存，依然没有用。
![image](https://user-images.githubusercontent.com/7381804/86509509-01188500-be1b-11ea-9d16-e07379c060fb.png)
不太确定问题到底出在哪，麻烦帮我看看可以吗。

**Comment by BirkhoffLee** [comment]
DNS 污染

**Comment by vanppo** [comment]
> DNS 污染

请问设置透明代理可以关掉 clash 的 DNS 功能吗？我根据[文档](https://lancellc.gitbook.io/clash/clash-config-file/dns/config-your-dns-settings-in-right-ways)的建议换了 DNS 服务器还是不可以。

**Comment by OUZYcn** [comment]
别用rubyfish.cn，宁可119.29.29.29或者
```
tun:
  enable: true
  stack: gvisor
  dns-hijack:
  - tcp://8.8.8.8:53
  - tcp://8.8.4.4:53
dns:
  enable: true
  ipv6: false
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  listen: 127.0.0.1:7874
  fake-ip-filter:
##Custom fake-ip-filter##
。。。。。。
##Custom fake-ip-filter END##
##Custom DNS##
  nameserver:
  - 119.29.29.29
  fallback:
  - https://1.1.1.1/dns-query
  - tls://1.1.1.1:853
  fallback-filter:
    geoip: true
    ipcidr:
      - 240.0.0.0/4
```
