### ISSUE TITLE
无法切换到新配置

### ISSUE THREAD

**Issue by zhjnerv** [Dreamacro/clash#788]
使用新规则配置加入了以下字段

```
rule-providers:
  ChinaDomain:
    type: http
    behavior: classical
    path: ./RuleSet/ChinaDomain
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/ChinaDomain.yaml
    interval: 86400
rules:
  - RULE-SET,Global,PROXY
```
![](https://p.sda1.dev/0/41489755541b46a52fd9f17ecda6f8c2/2020-07-06_16-18-35.jpg)

这个该如何解决
