### ISSUE TITLE
[Bug] rules 中已加入- DOMAIN-SUFFIX,qq.com 规则，但是vd.l.qq.com没有按照qq.com的规则走向指定的endpoint

### ISSUE THREAD

**Issue by wunifeng** [Dreamacro/clash#804]
------------------------------------------------------------------

### Clash config

<details>
  <summary>config.yaml</summary>

```yaml
rule-providers:
# name: # Provider 名称
#   type: http # http 或 file
#   behavior: classical # 或 ipcidr、domain
#   path: # 文件路径
#   url: # 只有当类型为 HTTP 时才可用，您不需要在本地空间中创建新文件。
#   interval: # 自动更新间隔，仅在类型为 HTTP 时可用

    Unbreak:
        type: http
        behavior: classical
        path: ./RuleSet/Unbreak.yaml
        url: https://raw.githubusercontent.com/DivineEngine/Profiles/master/Clash/RuleSet/Unbreak.yaml
        interval: 86400
    
    Netflix:
        type: http
        behavior: classical
        path: ./RuleSet/Netflix/Netflix.yaml
        url: https://raw.githubusercontent.com/wunifeng/ConfigFile/master/Clash/Netflix.yaml
        interval: 86400

    国际流媒体:
        type: http
        behavior: classical
        path: ./RuleSet/StreamingMedia/Streaming.yaml
        url: https://raw.githubusercontent.com/DivineEngine/Profiles/master/Clash/RuleSet/StreamingMedia/Streaming.yaml
        interval: 86400

    中国流媒体:
        type: http
        behavior: classical
        path: ./RuleSet/StreamingMedia/StreamingSE.yaml
        url: https://raw.githubusercontent.com/DivineEngine/Profiles/master/Clash/RuleSet/StreamingMedia/StreamingSE.yaml
        interval: 86400

    国外网站:
        type: http
        behavior: classical
        path: ./RuleSet/Global.yaml
        url: https://raw.githubusercontent.com/DivineEngine/Profiles/master/Clash/RuleSet/Global.yaml
        interval: 86400

    国内网站:
        type: http
        behavior: classical
        path: ./RuleSet/China.yaml
        url: https://raw.githubusercontent.com/DivineEngine/Profiles/master/Clash/RuleSet/China.yaml
        interval: 86400

    国内IP:
        type: http
        behavior: ipcidr
        path: ./RuleSet/Extra/ChinaIP.yaml
        url: https://raw.githubusercontent.com/DivineEngine/Profiles/master/Clash/RuleSet/Extra/ChinaIP.yaml
        interval: 86400


rules:
    - DOMAIN,vd.l.qq.com,中国流媒体
    - DOMAIN-SUFFIX,xvideos.com,兵工厂节点

    - IP-CIDR,91.108.4.0/22,DIRECT,no-resolve
    - IP-CIDR,91.108.8.0/22,DIRECT,no-resolve
    - IP-CIDR,91.108.12.0/22,DIRECT,no-resolve
    - IP-CIDR,91.108.16.0/22,DIRECT,no-resolve
    - IP-CIDR,91.108.56.0/22,DIRECT,no-resolve
    - IP-CIDR,149.154.160.0/22,DIRECT,no-resolve
    - IP-CIDR,149.154.164.0/22,DIRECT,no-resolve
    - IP-CIDR,149.154.168.0/22,DIRECT,no-resolve
    - IP-CIDR,149.154.172.0/22,DIRECT,no-resolve

    # LAN
    - DOMAIN-SUFFIX,local,DIRECT
    - IP-CIDR,127.0.0.0/8,DIRECT
    - IP-CIDR,172.16.0.0/12,DIRECT
    - IP-CIDR,172.17.0.0/12,DIRECT
    - IP-CIDR,192.168.0.0/16,DIRECT
    - IP-CIDR,169.254.0.0/16,DIRECT
    - IP-CIDR,10.0.0.0/8,DIRECT
    - IP-CIDR,17.0.0.0/8,DIRECT
    - IP-CIDR,100.64.0.0/10,DIRECT
    - IP-CIDR,224.0.0.0/8,DIRECT
    - IP-CIDR,255.255.255.255/32,DIRECT

    # Unbreak
    - RULE-SET,Unbreak,DIRECT
    
    # (DNS Cache Pollution) / (IP Blackhole) / (Region-Restricted Access Denied) / (Network Jitter)
    - RULE-SET,Netflix,Netflix
    
#    - RULE-SET,YouTube,谷歌媒体
    
    # (Streaming Media)
    - RULE-SET,国际流媒体,国外网站

    # (StreamingSE)
    - RULE-SET,中国流媒体,中国流媒体

    # (DNS Cache Pollution) / (IP Blackhole) / (Region-Restricted Access Denied) / (Network Jitter)
    - RULE-SET,国外网站,国外网站
    
    # (国内网站)
    - RULE-SET,国内网站,中国网站

    - RULE-SET,国内IP,中国网站

    # Tencent
    - IP-CIDR,119.28.28.28/32,中国流媒体
    - IP-CIDR,182.254.116.0/24,中国流媒体

    # 最终规则
    - GEOIP,CN,中国网站
    - MATCH,DIRECT
```

</details>

### Clash log

```
……
```

### 环境 Environment

* 操作系统 (the OS that the Clash core is running on)
……
* 网路环境或拓扑 (network conditions/topology)
……
* iptables，如果适用 (if applicable)
……
* ISP 有没有进行 DNS 污染 (is your ISP performing DNS pollution?)
……
* 其他 (any other information that would be useful)
……

### 说明 Description
rules 中已加入- DOMAIN-SUFFIX,qq.com 规则，但是vd.l.qq.com没有按照qq.com的规则走向指定的endpoint

我不确定这算不算一个bug，所以提出来。原则上来讲，x.x.qq.com 应该与 DOMAIN-SUFFIX qq.com 规则一致对吗？
现在不一致是故意设置的吗？
### 重现问题的具体布骤 Steps to Reproduce

1. [First Step]
2. [Second Step]
3. ……

**我预期会发生……？**

xx.x.qq.com 与 DOMAIN-SUFFIX qq.com 规则一致
**实际上发生了什么？**

xx.x.qq.com 与 DOMAIN-SUFFIX qq.com 规则不一致
