### ISSUE TITLE
[Feature] 建议 proxy-providers 的 fetcher 添加自定义 User-Agent

### ISSUE THREAD

**Issue by tsln1998** [Dreamacro/clash#819]
感谢你向 Clash Core 提交 Feature Request！
在提交之前，请确认：

- [x] 我已经在 [Issue Tracker](……/) 中找过我要提出的请求

请注意，如果你并没有遵照这个 issue template 填写内容，我们将直接关闭这个 issue。

我都确认过了，我要继续提交。

------------------------------------------------------------------

请附上任何可以帮助我们解决这个问题的信息，如果我们收到的信息不足，我们将对这个 issue 加上 *Needs more information* 标记并在收到更多资讯之前关闭 issue。

### Clash core config

```yaml
mixed-port: 6789

allow-lan: true
mode: rule

log-level: debug
external-controller: 127.0.0.1:9090

hosts:
  '*.local': 127.0.0.1

dns:
  enable: true
  enhanced-mode: redir-host
  listen: 0.0.0.0:53
  nameserver:
    - ???.???.???.???

proxies:
- name: AWS
  type: ss
  server: example.com
  port: 1521
  cipher: aes-128-gcm
  password: "aKR9$y!24QIr3Wct"
proxy-providers:
  subscribe-test:
    type: http
    path: ./test.yaml
    url: "http://example.com/api/v1/client/subscribe?token=?????????"
    interval: 1800
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300
proxy-groups:
- name: "SUBSCRIBE"
  type: url-test
  use:
    - subscribe-test
  url: 'https://www.youtube.com/'
  interval: 300
- name: "PROXY"
  type: select
  proxies:
    - AWS
    - SUBSCRIBE
rules:
- IP-CIDR,127.0.0.0/8,DIRECT
- IP-CIDR,192.168.0.0/16,DIRECT
- GEOIP,CN,DIRECT
- MATCH,PROXY
```

### Clash log

```
INFO[0000] Start initial provider subscribe-ovo
FATA[0000] Parse config error: initial proxy provider subscribe-test error: yaml: unmarshal errors:
  line 1: cannot unmarshal !!str `dm1lc3M...` into provider.ProxySchema
```

### 说明 Description

建议 proxy-providers 的 fetcher 添加自定义 User-Agent，以助于第三方站点识别客户端版本

参考 [v2board](https://github.com/v2board/v2board) [App\Http\Controllers\Client\ClientController::subscribe](https://github.com/v2board/v2board/blob/master/app/Http/Controllers/Client/ClientController.php#L35)
