### ISSUE TITLE
[Bug] Clash Core 1.0.0 DNS server 不返回 Hosts ip

### ISSUE THREAD

**Issue by dbarobin** [Dreamacro/clash#849]
### Clash config

```yaml
hosts:
  'xxx.xxx.com': xxx.xxx.xxx.xxx

rules:
  - DOMAIN-KEYWORD,*.xxx.com,DIRECT
  - DOMAIN-SUFFIX,xxx.xxx.com,DIRECT
```

### Clash log

无。

### 环境 Environment

* 操作系统 (the OS that the Clash core is running on)

> 机型: OnePlus
> 系统 / ROM: H2OS
> Android 版本：10
> ROM 版本：10.0.4

* 网路环境或拓扑 (network conditions/topology)

> 家用 Wi-Fi，广东电信。

* iptables，如果适用 (if applicable)

> 无。

* ISP 有没有进行 DNS 污染 (is your ISP performing DNS pollution?)

> 有。

* 其他 (any other information that would be useful)

> 无。

### 说明 Description

无法实现打开自定义 Hosts，带来不少困扰。

### 重现问题的具体布骤 Steps to Reproduce

* 安装 Clash for Android v2.0.18；
* 通过 URL 订阅；
* 启动 Clash；
* Chrome 浏览器访问自定义 Hosts；
* Hosts 无法打开。

**我预期会发生……？**

> 正常打开自定义 Hosts。

**实际上发生了什么？**

> 实际上无法打开。

### 可能的解决方案 Possible Solution

> 对 hosts 关键词进行支持。

### 更多信息 More Information

* 在 Clash for Android 提交的 issue：https://github.com/Kr328/ClashForAndroid/issues/553
