### ISSUE TITLE
[Feature]希望可以由用户显式设置 Nameserver 和 Fallback DNS 是否通过代理来解析域名

### ISSUE THREAD

**Issue by Loyalsoldier** [Dreamacro/clash#857]
### 说明 Description

由于在大陆直连海外的 DoT/DoH fallback DNS 实在是太慢了，等一两秒甚至解析不出结果导致报错，希望可以由用户显式设置 Nameserver 和 Fallback DNS 是否通过代理来解析域名。

**Comment by ayanamist** [comment]
同意，目前fallback这里能填写的dns是非常少的，而且这里既然已经定义了default resolver，那应该是可以让这部分dns解析也去使用代理的

**Comment by Dreamacro** [comment]
功能不一样，fallback 主要是用来处理一部分污染的，default 相当于 adguard 的 bootstrap dns，是解析包含 host 的 dns 服务器的。

1. 对于只是想用无污染地址的，建议 fallback 直接填国内的 doh，比如我的 dns 配置是这样的
```yaml
dns:
  enable: true
  enhanced-mode: redir-host
  fake-ip-range: 10.19.0.1/16
  fake-ip-filter:
    - '.lan'
    - localhost.ptlogin2.qq.com
  fallback-filter:
    geoip: false
    ipcidr:
      - 0.0.0.0/32
  listen: 0.0.0.0:53
  nameserver:
    - 192.168.5.1
  fallback:
    - https://doh.pub/dns-query
```

2. 对于想保护 dns 隐私的，建议还是自建 adguard 之类的 dns server
