### ISSUE TITLE
[Bug] 使用 global mode 仍直连

### ISSUE THREAD

**Issue by Songkeys** [Dreamacro/clash#858]
------------------------------------------------------------------

### Clash config

<details>
  <summary>config.yaml</summary>

```yaml
port: 7890
socks-port: 7891
redir-port: 7892

authentication:
  - "xxx:xxx"

allow-lan: true

bind-address: '*'

mode: global

proxies:
  - name: "ss1"
    type: ss
    server: xxx
    port: xxx
    cipher: aes-256-gcm
    password: "xxx"
    
proxy-groups:
  - name: "auto"
    type: url-test
    proxies:
      - ss1
    url: 'https://google.com'
    interval: 300
    
rules:
  - MATCH,DIRECT
……
```

</details>

### Clash log

```
clash    | time="2020-08-01T14:03:28Z" level=info msg="Start initial compatible provider auto"
clash    | time="2020-08-01T14:03:28Z" level=info msg="RESTful API listening at: 127.0.0.1:9090"
clash    | time="2020-08-01T14:03:28Z" level=info msg="Authentication of local server updated"
clash    | time="2020-08-01T14:03:28Z" level=info msg="HTTP proxy listening at: :7890"
clash    | time="2020-08-01T14:03:28Z" level=info msg="SOCKS proxy listening at: :7891"
clash    | time="2020-08-01T14:03:28Z" level=info msg="Redir proxy listening at: :7892"
clash    | time="2020-08-01T14:03:40Z" level=info msg="[TCP] xxx.xxx.xxx.xxx:45116 --> ip.sb using GLOBAL"
clash    | time="2020-08-01T14:04:12Z" level=warning msg="dial GLOBAL error: dial tcp4 216.58.200.238:80: i/o timeout"
```

以上是用 `curl ip.sb` 和 `curl google.com` 的结果。
```bash
❯ curl ip.sb
(显示本机 IP 而非代理)


❯ curl google.com
curl: (52) Empty reply from server
```

### 环境 Environment

* 操作系统 (the OS that the Clash core is running on)
centos-7
* 网路环境或拓扑 (network conditions/topology)
……
* iptables，如果适用 (if applicable)
……
* ISP 有没有进行 DNS 污染 (is your ISP performing DNS pollution?)
……
* 其他 (any other information that would be useful)
……

### 重现问题的具体布骤 Steps to Reproduce

1. [First Step]
2. [Second Step]
3. ……

**我预期会发生……？**

**实际上发生了什么？**
