### ISSUE TITLE
[Feature] 在relay(proxy chains)中支持v2+ws

### ISSUE THREAD

**Issue by pannnnnnn** [Dreamacro/clash#863]
在提交之前，请确认：

- [x] 我已经在 [Issue Tracker](……/) 中找过我要提出的请求

### Clash core config
```
proxies:
- {"name":"A","type":"vmess","server":"1.1.1.1","port":80,"uuid":"xxx","alterId":2,"cipher":"auto","udp":true,"network":"ws","ws-path":"/","ws-headers":{"Host":"xxx.com"}}
- {"name":"B","type":"vmess","server":"2.2.2.2","port":80,"uuid":"xxx","alterId":2,"cipher":"auto","udp":true,"network":"ws","ws-path":"/","ws-headers":{"Host":"xxx.com"}}
proxy-groups:
-
  name: proxychains
  type: relay
  proxies:
    - 'A'
    - 'B'
```

### Clash log
```
time="xxx" level=warning msg="dial GLOBAL error: 2.2.2.2:80 connect error: Dial 2.2.2.2:80 error: 200 OK"
```

### Server A V2Ray log
```
v2ray.com/core/proxy/vmess/inbound: received request for tcp:2.2.2.2:80
v2ray.com/core/app/dispatcher: sniffed domain: xxx.com
v2ray.com/core/proxy/freedom: opening connection to tcp:xxx.com:80
```

### 说明 Description
无法在relay(proxy chains)中使用v2+ws的原因似乎是因为v2的proxySettings和streamSettings冲突，于是A把数据发到了伪装域名而不是B。解决方案似乎是使用dokodemo-door，然而在clash中好像没有类似解决方案，抑或是我没有发现，能请D大指点一下吗？

### 参考了
https://github.com/v2ray/discussion/issues/651
https://v2ray.com/chapter_02/01_overview.html
