### ISSUE TITLE
[Bug] 增强模式下，DNS 模块发生 DNS 泄漏

### ISSUE THREAD

**Issue by Loyalsoldier** [Dreamacro/clash#877]
## Clash config
<details>
  <summary>config.yaml</summary>

```yaml
dns:
  enable: true
  listen: 0.0.0.0:53
  ipv6: false
  default-nameserver:
    - 114.114.114.114
    - 1.1.1.1
  enhanced-mode: redir-host
  nameserver:
    - https://doh.pub/dns-query

rule-providers:
  🚫reject:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/reject.txt"
    path: ./parts/reject.yaml
    interval: 3600

  ☁️icloud:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/icloud.txt"
    path: ./parts/icloud.yaml
    interval: 3600

  🚀proxy:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/proxy.txt"
    path: ./parts/proxy.yaml
    interval: 3600

  🇨🇳direct:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/direct.txt"
    path: ./parts/direct.yaml
    interval: 3600

  🇨🇳cncidr:
    type: http
    behavior: ipcidr
    url: "https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/cncidr.txt"
    path: ./parts/cncidr.yaml
    interval: 3600

  🔁lancidr:
    type: http
    behavior: ipcidr
    url: "https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/lancidr.txt"
    path: ./parts/lancidr.yaml
    interval: 3600

rules:
  - RULE-SET,🚫reject,REJECT
  - RULE-SET,☁️icloud,DIRECT
  - RULE-SET,🚀proxy,PROXY
  - RULE-SET,🇨🇳direct,DIRECT
  - RULE-SET,🇨🇳cncidr,DIRECT,no-resolve
  - RULE-SET,🔁lancidr,DIRECT,no-resolve
  - MATCH,PROXY
```
</details>

### 环境 Environment

* 操作系统 (the OS that the Clash core is running on)
macOS Catalina

* ISP 有没有进行 DNS 污染 (is your ISP performing DNS pollution?)
有

### 重现问题的具体布骤 Steps to Reproduce

1. 使用上面配置，并使用 ClashX Pro 开启增强模式
2. 打开 https://dnsleaktest.com ，日志显示命中最终的 Match 规则，但是能检测到 DNS 泄漏

**我预期会发生……？**
因为配置中并没有 GEOIP 的判断，而且自定义的 CIDR 规则设置了 `no-resolve`，最终的 Match 规则走代理，理应不会出现 DNS 泄漏。

**实际上发生了什么？**
出现了 DNS 泄漏。

### 可能的解决方案 Possible Solution
对于命中 Proxy 规则的域名不进行本地 DNS 解析
