### ISSUE TITLE
[Bug] Premium Fake-IP 模式下 DNS 请求的疑惑 

### ISSUE THREAD

**Issue by hehehehehaha** [Dreamacro/clash#885]
------------------------------------------------------------------

- [x] 我已经使用 dev 分支版本测试过，问题依旧存在
- [x] 我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题
- [x] 这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题

### Clash config

<details>
  <summary>config.yaml</summary>

```yaml
dns:
  enable: true
  ipv6: false
  listen: 127.0.0.1:7874
  enhanced-mode: fake-ip
  nameserver:
  - 127.0.0.1:19990
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
  - ...
tun:
  enable: true
  stack: system
  dns-hijack:
  - 8.8.8.8
  - 8.8.4.4
```

</details>

### 环境 Environment

* 操作系统 (the OS that the Clash core is running on)
……
* 网路环境或拓扑 (network conditions/topology)
……
* iptables，如果适用 (if applicable)
……
* ISP 有没有进行 DNS 污染 (is your ISP performing DNS pollution?)
……
* 其他 (any other information that would be useful)
……

### 说明 Description

抱歉，打扰了。

我个人理解在 Fake-IP 模式下面，当域名匹配到非 DIRECT 规则时候，解析域名的工作是交给远端服务器完成。目前我的做法是在 Script 中先匹配已有规则，匹配到即返回代理组；若没有匹配到即使用 `ctx.resolve_ip(host)` 向自定义 DNS 服务器发起请求，以达到避免让非 DIRECT 域名向本地 DNS 服务器发起请求的效果。在其他应用（Spotify Instagram Twitter ......）中达到了效果，吊诡在于使用 Google 相关的应用时，在上游 DNS 服务器日志中发现了相关域名的请求，没达到预期效果。保证 Google 相关域名已在非 DIRECT 规则中。配置文件中端口 19990 的 DNS 服务器为 SmartDNS 。

- SmartDNS 日志

    ![Sun_20200810_152523](https://user-images.githubusercontent.com/45707218/89760207-75cb9700-db1e-11ea-97b7-f235fe437dcc.png)

- Clash 日志

    ![Sun_20200810_152858](https://user-images.githubusercontent.com/45707218/89760209-76642d80-db1e-11ea-9af4-2c762f26cabe.png)

麻烦了~
