### ISSUE TITLE
[Bug] 不同策略组（之间有重复节点）使用不同的 URL 进行测试，结果似乎不相互独立

### ISSUE THREAD

**Issue by h0cheung** [Dreamacro/clash#886]
------------------------------------------------------------------

### Clash config

<details>
  <summary>config.yaml</summary>

```yaml
  - name: auto
    type: url-test
    url: <Google 的 204 地址>
    interval: 240
    proxies:
      - Proxy1
      - Proxy2
      - ......
  - name: auto-b
    type: url-test
    url: <个人落地服务器的 204 地址>
    interval: 230
    proxies:
      - Proxy1
      - Proxy2
      - Proxy3
      - ......
```

</details>

### Clash log

```
……
```

### 环境 Environment

* 操作系统 (the OS that the Clash core is running on)
Linux, Android 均存在
* 网路环境或拓扑 (network conditions/topology)
* iptables，如果适用 (if applicable)
* ISP 有没有进行 DNS 污染 (is your ISP performing DNS pollution?)
* 其他 (any other information that would be useful)
使用了 yacd

### 说明 Description

在设置了这样的策略组之后，yacd 的界面上同一节点在两个策略组的延迟显示永远是一样的。不知道这仅仅是 yacd 显示的问题，或者仅仅是 clash 的 api 部分的问题，还是说 clash 完全无法正确处理这种不同 URL 测速相同节点的情况。如果是后两种情况，特别是第三种的话，希望能够修复。

### 重现问题的具体布骤 Steps to Reproduce

1. [First Step]
2. [Second Step]
3. ……

**我预期会发生……？**

**实际上发生了什么？**
