### ISSUE TITLE
Support DoT/DoH for bootstrap nameservers

### ISSUE THREAD

**Issue by hongyi-zhao** [Dreamacro/clash#897]
Clash claims that it has the following feature: `
Built-in DNS server that aims to minimize DNS pollution attack impact, supports DoH/DoT upstream and fake IP.`

While I note the following [dns reolvers](https://github.com/Dreamacro/clash/blob/35449bfa177ecead9d1de05ec74382958540e90b/config/config.go#L161) used by clash:

```
			DefaultNameserver: []string{
				"114.114.114.114",
				"8.8.8.8",
```

It's well known that "114.114.114.114" is not a pollution-free dns. Any hints for this problem?

Regards,
HY

**Comment by Fndroid** [comment]
Clash do provide a full custom DNS server and allows you to achive ``minimize DNS pollution attack impact``.

``default-nameserver`` are different from ``nameserver``:
```yaml
# These nameservers are used to resolve the DNS nameserver hostnames below.
# Specify IP addresses only
default-nameserver:
  - 114.114.114.114
  - 8.8.8.8

# Supports UDP, TCP, DoT, DoH. You can specify the port to connect to.
# All DNS questions are sent directly to the nameserver, without proxies
# involved. Clash answers the DNS question with the first result gathered.
nameserver:
  - 114.114.114.114 # default value
  - 8.8.8.8 # default value
  - tls://dns.rubyfish.cn:853 # DNS over TLS
  - https://1.1.1.1/dns-query # DNS over HTTPS
```

If you don't want these two server, you can change them at any time.
