### ISSUE TITLE
[Feature] 关于Clash DNS请求的问题。

### ISSUE THREAD

**Issue by douglas-lee** [Dreamacro/clash#904]
经过测试，Clash的DNS请求，不管是nameserver还是fallback，好像都是从本地直接请求，这样的方式其实不是最优，因为fallback出来的地址往往用于走代理线路，所以DNS的请求，理论上应该透过代理线路获取DNS结果。其实简单的说，Clash的fallback请求应该通过类似dns proxy的方式获取回来。

类似的方案有：
https://github.com/jtripper/dns-tcp-socks-proxy

希望能参考。

**Comment by BirkhoffLee** [comment]
那個解析出來的結果只是用於 GEOIP 規則，最後實際連線的對象其實是直接發 FQDN 到 remote server

**Comment by OUZYcn** [comment]
你先看看这里 ： [Unofficial Clash Wiki的DNS章节.](https://lancellc.gitbook.io/clash/clash-config-file/dns)

按照guidebook的说明，Clash是并行向定义在`nameserver`所有DNS发出查询，然后记录第一个返回的结果。
 ` similar with dnsmasq with --all-servers mode. `
The traffic of DoH or DoT will **not** pass proxy. All the traffic will direct to the server.
**fallback**
Defines several upstream DNS fallback server, support resolve by udp, tcp, udp on specific port, tcp on specific port, DNS over TLS, DNS over HTTPS.
**Concurrent** request with nameserver, fallback used when GEOIP country **isn't** CN.

```
##Custom DNS##
  nameserver:
  - 119.29.29.29
  - https://1.1.1.1/dns-query
  - 45.90.28.57
  - 223.5.5.5
  fallback:
  - 114.114.114.114
  - tls://8.8.8.8:853
  fallback-filter:
    geoip: true
    ipcidr:
      - 240.0.0.0/4
```

**Comment by douglas-lee** [comment]
我明白他的工作原理，但是在我的使用场景中，我是用iptables+ipset+dnsmasq来做分流，clash只是隧道和dns proxy，这样的话，我相当于是拿了clash返回的dns结果，再去用其它软件做判断和分流，就会出问题了。

**Comment by OUZYcn** [comment]
其实现在而言。Clash的ruleset机制已经挺不错了，你也可以使用Script模式更灵活的配置（貌似python也支持）。
我是半桶水，所以不折腾iptable了。
不过我比较疑虑的是Clash的fake-ip LRU hashmap的性能，貌似我启用Debug模式后，发现不少fake-ip DNS record missing错误信息。 另外一方面，我原来的设想是使用防火墙的DNS作为客户机DNS，（主要的目的是利用unbond的性能以及可以查阅cache hit/miss rate等信息），然后clash作为upstream，但在fake-ip模式下，这个思路就不行了。

**Comment by juewuy** [comment]
DNS是请求所有，然后根据最快的返回ip，进行规则分组，其中不走直连的节点则从fallback里获取最快的返回ip，并最终利用这个ip进行传输。

**Comment by leoorz** [comment]
运营商：移动
发现鸡场用一段时间就得切节点，过一伙再切回来又能继续用
但是用科学上网，国外 DNS 解析过代理就正常了
```
dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:53
  enhanced-mode: redir-host
  fake-ip-range: 198.18.0.1/16
  use-hosts: true
  nameserver:
    - 223.5.5.5
    - 180.76.76.76
    - 119.29.29.29
  fallback:
    - tls://1.1.1.1
    - https://cloudflare-dns.com/dns-query
    - 2.dnscrypt-cert.opendns.com
    - tls://dns.google
  fallback-filter:
    geoip: true
    ipcidr:
      - 240.0.0.0/4
```
![image](https://user-images.githubusercontent.com/57260496/91144784-15745200-e6e7-11ea-83d8-81bb06032515.png)

**Comment by lizenghui** [comment]
> 我明白他的工作原理，但是在我的使用场景中，我是用iptables+ipset+dnsmasq来做分流，clash只是隧道和dns proxy，这样的话，我相当于是拿了clash返回的dns结果，再去用其它软件做判断和分流，就会出问题了。

我跟你的情况一样  我目前用的dns2socks  dnsmasq配置gfwlist域名让dns2socks+clash去解析

**Comment by fanck0605** [comment]
@douglas-lee 运营商的 DNS 劫持最近似乎更加厉害了，最近访问 google 经常被解析到 facebook 的域名。配置如下，fallback-filter 保持默认，DoH 并不能解决 DNS 污染问题，让 DNS 走代理很有必要。
```
dns:
  enable: true
  ipv6: false
  enhanced-mode: redir-host
  listen: 127.0.0.1:7874
  nameserver:
  - 114.114.114.114
  - 119.29.29.29
  fallback:
  - https://cloudflare-dns.com/dns-query
  - https://dns.google/dns-query
  - https://1.1.1.1/dns-query
  - tls://8.8.8.8:853
 ```
