### ISSUE TITLE
[Bug][Premium 2020.08.16]rule-providers自动更新无效

### ISSUE THREAD

**Issue by asinitial** [Dreamacro/clash#914]
- [ ] 如果你可以自己 debug 并解决的话，提交 PR 吧！
- [x] 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [ ] 我已经使用 dev 分支版本测试过，问题依旧存在
- [x] 我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题
- [x] 这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题
### Clash config
<details>
  <summary>config.yaml</summary>

```yml
# Port of HTTP(S) proxy server on the local end
# port: 7890

# Port of SOCKS5 proxy server on the local end
# socks-port: 7891

# Transparent proxy server port for Linux and macOS
# redir-port: 7892

# HTTP(S) and SOCKS5 server on the same port
mixed-port: 1080

# authentication of local SOCKS5/HTTP(S) server
# authentication:
#  - "user1:pass1"
#  - "user2:pass2"

# Set to true to allow connections to local-end server from
# other LAN IP addresses
allow-lan: true

# This is only applicable when `allow-lan` is `true`
# '*': bind all IP addresses
# 192.168.122.11: bind a single IPv4 address
# "[aaaa::a8aa:ff:fe09:57d8]": bind a single IPv6 address
bind-address: '*'

# Clash router working mode
# rule: rule-based packet routing
# global: all packets will be forwarded to a single endpoint
# direct: directly forward the packets to the Internet
mode: rule

# Clash by default prints logs to STDOUT
# info / warning / error / debug / silent
log-level: debug

# When set to false, resolver won't translate hostnames to IPv6 addresses
ipv6: true

# RESTful API for clash
external-controller: 127.0.0.1:9090

# A relative path to the configuration directory or an absolute path to a
# directory in which you put some static web resource. Clash core will then
# serve it at `http://{{external-controller}}/ui`.
external-ui: ./ui

# Secret for the RESTful API (optional)
# Authenticate by spedifying HTTP header `Authorization: Bearer ${secret}`
# ALWAYS set a secret if RESTful API is listening on 0.0.0.0
# secret: ""

# Outbound interface name
# interface-name: en0

# Static hosts for DNS server and connection establishment, only works
# when `dns.enhanced-mode` is `redir-host`.
#
# Wildcard hostnames are supported (e.g. *.clash.dev, *.foo.*.example.com)
# Non-wildcard domain names has a higher priority than wildcard domain names
# e.g. foo.example.com > *.example.com > .example.com
# P.S. +.foo.com equals to .foo.com and foo.com
hosts:
  # '*.clash.dev': 127.0.0.1
  # '.dev': 127.0.0.1
  # 'alpha.clash.dev': '::1'

# DNS server settings
# This section is optional. When not present, DNS server will be disabled.
dns:
  enable: true
  listen: :53
  ipv6: true
  
  # These nameservers are used to resolve the DNS nameserver hostnames below.
  # Specify IP addresses only
  default-nameserver:
    - 223.5.5.5
    - 114.114.114.114
    - 8.8.8.8
  enhanced-mode: redir-host # or fake-ip
  fake-ip-range: 198.18.0.1/16 # Fake IP addresses pool CIDR
  
  # Hostnames in this list will not be resolved with fake IPs
  # i.e. questions to these domain names will always be answered with their
  # real IP addresses
  # fake-ip-filter: # fake ip white domain list
  #  - '*.lan'
  #  - localhost.ptlogin2.qq.com
    
  # Supports UDP, TCP, DoT, DoH. You can specify the port to connect to.
  # All DNS questions are sent directly to the nameserver, without proxies
  # involved. Clash answers the DNS question with the first result gathered.
  nameserver:
    - 223.5.5.5
    - 114.114.114.114
    - 8.8.8.8
    - tls://dns.rubyfish.cn:853 # dns over tls
    - https://1.0.0.1/dns-query # dns over https
    
  # When `fallback` is present, the DNS server will send concurrent requests
  # to the servers in this section along with servers in `nameservers`.
  # The answers from fallback servers are used when the GEOIP country
  # is not `CN`.
  fallback: # concurrent request with nameserver, fallback used when GEOIP country isn't CN
    - tls://1.0.0.1:853
    - tcp://1.0.0.1:53
    - tcp://208.67.222.222:443
    - tls://dns.google
    
  # If IP addresses resolved with servers in `nameservers` are in the specified
  # subnets below, they are considered invalid and results from `fallback`
  # servers are used instead.
  #
  # IP address resolved with servers in `nameserver` is used when
  # `fallback-filter.geoip` is true and when GEOIP of the IP address is `CN`.
  #
  # If `fallback-filter.geoip` is false, results from `fallback` nameservers
  # are always used, and answers from `nameservers` are discarded.
  #
  # This is a countermeasure against DNS pollution attacks.
  fallback-filter:
    geoip: true
    ipcidr:
      - 240.0.0.0/4
      - 0.0.0.0/32
  
proxies:
--------
--------
--------
proxy-groups:
--------
--------
--------
rule-providers:
  # name: # Provider 名称
  #   type: http # http 或 file
  #   behavior: classical # 或 ipcidr、domain
  #   path: # 文件路径
  #   url: # 只有当类型为 HTTP 时才可用，您不需要在本地空间中创建新文件。
  #   interval: # 自动更新间隔，仅在类型为 HTTP 时可用

  Unbreak:
    type: http
    behavior: classical
    path: ./RuleSet/Unbreak.yaml
    url: https://raw.githubusercontent.com/DivineEngine/Profiles/master/Clash/RuleSet/Unbreak.yaml
    interval: 86400

  Streaming:
    type: http
    behavior: classical
    path: ./RuleSet/StreamingMedia/Streaming.yaml
    url: https://raw.githubusercontent.com/DivineEngine/Profiles/master/Clash/RuleSet/StreamingMedia/Streaming.yaml
    interval: 86400
  StreamingCN:
    type: http
    behavior: classical
    path: ./RuleSet/StreamingMedia/StreamingCN.yaml
    url: https://raw.githubusercontent.com/DivineEngine/Profiles/master/Clash/RuleSet/StreamingMedia/StreamingCN.yaml
    interval: 86400
  StreamingSE:
    type: http
    behavior: classical
    path: ./RuleSet/StreamingMedia/StreamingSE.yaml
    url: https://raw.githubusercontent.com/DivineEngine/Profiles/master/Clash/RuleSet/StreamingMedia/StreamingSE.yaml
    interval: 86400

  Advertising:
    type: http
    behavior: classical
    path: ./RuleSet/Guard/Advertising.yaml
    url: https://raw.githubusercontent.com/DivineEngine/Profiles/master/Clash/RuleSet/Guard/Advertising.yaml
    interval: 86400
  Hijacking:
    type: http
    behavior: classical
    path: ./RuleSet/Guard/Hijacking.yaml
    url: https://raw.githubusercontent.com/DivineEngine/Profiles/master/Clash/RuleSet/Guard/Hijacking.yaml
    interval: 86400
  Privacy:
   type: http
   behavior: classical
   path: ./RuleSet/Guard/Privacy.yaml
   url: https://raw.githubusercontent.com/DivineEngine/Profiles/master/Clash/RuleSet/Guard/Privacy.yaml
   interval: 86400
  
  Global:
    type: http
    behavior: classical
    path: ./RuleSet/Global.yaml
    url: https://raw.githubusercontent.com/DivineEngine/Profiles/master/Clash/RuleSet/Global.yaml
    interval: 86400

  China:
    type: http
    behavior: classical
    path: ./RuleSet/China.yaml
    url: https://raw.githubusercontent.com/DivineEngine/Profiles/master/Clash/RuleSet/China.yaml
    interval: 86400

  ChinaIP:
    type: http
    behavior: ipcidr
    path: ./RuleSet/Extra/ChinaIP.yaml
    url: https://raw.githubusercontent.com/DivineEngine/Profiles/master/Clash/RuleSet/Extra/ChinaIP.yaml
    interval: 86400

# 规则
rules:
  # Unbreak
  - RULE-SET,Unbreak,DIRECT

  # Global Area Network

  # (Streaming Media)
  - RULE-SET,Streaming,Streaming
  - RULE-SET,StreamingCN,DIRECT

  # (StreamingSE)
  - RULE-SET,StreamingSE,DIRECT
  
  # Advertising,Hijacking,Privacy
  - RULE-SET,Advertising,Deny
  - RULE-SET,Hijacking,Deny
  - RULE-SET,Privacy,Deny

  # (DNS Cache Pollution) / (IP Blackhole) / (Region-Restricted Access Denied) / (Network Jitter)
  - RULE-SET,Global,Proxy

  # China Area Network
  - RULE-SET,China,DIRECT

  # Local Area Network
  - IP-CIDR,192.168.0.0/16,DIRECT
  - IP-CIDR,10.0.0.0/8,DIRECT
  - IP-CIDR,172.16.0.0/12,DIRECT
  - IP-CIDR,127.0.0.0/8,DIRECT
  - IP-CIDR,100.64.0.0/10,DIRECT
  - IP-CIDR,224.0.0.0/4,DIRECT

  # （可选）使用来自 ipipdotnet 的 ChinaIP 以解决数据不准确的问题，使用 ChinaIP.yaml 时可禁用下列直至（包括）「GEOIP,CN」规则
  - RULE-SET,ChinaIP,DIRECT
  - MATCH,Match
```
</details>

### Clash log
<details>
  <summary>log</summary>

```
INFO[0000] Start initial compatible provider LoadBalance 
INFO[0000] Start initial compatible provider UrlTest    
INFO[0000] Start initial compatible provider Relay      
INFO[0000] Start initial compatible provider Match      
INFO[0000] Start initial compatible provider Deny       
INFO[0000] Start initial compatible provider Fallback   
INFO[0000] Start initial compatible provider Proxy      
INFO[0000] Start initial compatible provider Streaming  
INFO[0000] Start initial compatible provider Unlock     
INFO[0000] Start initial compatible provider PersonalRules 
INFO[0000] Start initial rule provider Privacy          
INFO[0000] Start initial rule provider StreamingCN      
INFO[0000] Start initial rule provider Advertising      
INFO[0000] Start initial rule provider ChinaIP          
INFO[0000] Start initial rule provider Hijacking        
INFO[0000] Start initial rule provider China            
INFO[0000] Start initial rule provider Unbreak          
INFO[0000] Start initial rule provider StreamingSE      
INFO[0000] Start initial rule provider Streaming        
INFO[0000] Start initial rule provider Global           
INFO[0000] DNS server listening at: :53                 
INFO[0000] Mixed(http+socks5) proxy listening at: :1080 
INFO[0000] RESTful API listening at: 127.0.0.1:9090     

```
</details>

### 环境 Environment

* 操作系统 (the OS that the Clash core is running on)
Debian buster + Clash core Premium 2020.08.16
* 网路环境或拓扑 (network conditions/topology)
电信
* iptables，如果适用 (if applicable)
无
* ISP 有没有进行 DNS 污染 (is your ISP performing DNS pollution?)
无
* 其他 (any other information that would be useful)
……

### 重现问题的具体布骤 Steps to Reproduce

1. 按照上述配置正常安装使用。
2. 对比RuleSet内本地文件和rule-providers中引用的远程文件。

**我预期会发生……？**

本地文件和rule-providers中引用的远程文件自动同步

**实际上发生了什么？**

本地文件仍旧是首次配置安装后下载的文件，之后没有再自动同步更新过，虽然Web-Dashboard中显示的更新时间正常，但文件内容与远程不同步。
只有在Web-Dashboard中手动点击更新Rules才能成功更新。
