### ISSUE TITLE
[Feature] 为 External 提供 HTTPS 支持

### ISSUE THREAD

**Issue by kallydev** [Dreamacro/clash#928]
- [x] 我已经在 [Issue Tracker](……/) 中找过我要提出的请求

------------------------------------------------------------------

### 环境 Environment

* Clash Core 的操作系统 (the OS that the Clash core is running on)

```
Linux ubuntu 5.7.10-050710-generic #202007220834 SMP Wed Jul 22 08:52:23 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

* 网路环境或拓扑 (network conditions/topology)

```
                   +------------------------------------+      +--------------+
                   |                                    | http |              |
                   |             yacd server            |      | clash server |
+----------+       |                                    | <--> |              |
|          | https | +---------+               +------+ |      +--------------+
|  client  |       | |         | reverse proxy |      | |
|          | <---> | |  nginx  |               | yacd | |      +--------------+
+----------+       | |         | <-----------> |      | | http |              |
                   | +---------+               +------+ |      | clash server |
                   |                                    | <--> |              |
                   +------------------------------------+      +--------------+
```

### 说明 Description

我在多台国内的服务器上使用 Docker 部署 Clash，用于为构建代码的 CI 提供网络代理。为了方便对多个 Clash 服务器进行管理，我在单独的服务器上部署了 [yacd](https://github.com/haishanh/yacd)，并通过公网连接到各个 Clash 服务器。

由于数据在公网传输，我使用 Nginx 对 yacd 进行反向代理以便能够支持 HTTPS。但似乎受到浏览器的同源策略限制，yacd 无法在 HTTPS 中与其他 HTTP 服务进行交互。也有其他人遇到了这个问题，例如 https://github.com/haishanh/yacd/issues/472 。

以下是 Chrome Console 上的错误日志： 

```
Mixed Content: The page at 'https://yacd.example.com/' was loaded over HTTPS, but requested an insecure resource 'http://clash.example.com:9090/configs'. This request has been blocked; the content must be served over HTTPS.
```

```
Mixed Content: The page at 'https://yacd.example.com/' was loaded over HTTPS, but attempted to connect to the insecure WebSocket endpoint 'ws://clash.example.com:9090/traffic?token=********-****-****-****-************'. This request has been blocked; this endpoint must be available over WSS.
```

### 可能的解决方案 Possible Solution

提供 SSL 配置文件的支持。

```yaml
external-controller:
  address: 0.0.0.0:9090
  certificate: /etc/ssl/certs/example.com.crt
  certificate-key: /etc/ssl/private/example.com.key
```

由于上方的格式会与之前的配置冲突，所以下方的格式会更合适。

```yaml
external-controller: 0.0.0.0:9090
external-certificate: /etc/ssl/certs/example.com.crt
external-certificate-key: /etc/ssl/private/example.com.key
```

如果认可这个解决方案，我可以为此提供 PR。
