### ISSUE TITLE
DNS应答异常后退出

### ISSUE THREAD

**Issue by Felix2yu** [Dreamacro/clash#93]
```
DEBU[0613] [DNS] answer length is zero: &dns.Msg{MsgHdr:dns.MsgHdr{Id:0x6333, Response:true, Opcode:0, Authoritative:false, Truncated:false, RecursionDesired:true, RecursionAvailable:true, Zero:false, AuthenticatedData:false, CheckingDisabled:false, Rcode:0}, Compress:false, Question:[]dns.Question{dns.Question{Name:".", Qtype:0x1, Qclass:0x1}}, Answer:[]dns.RR(nil), Ns:[]dns.RR{(*dns.SOA)(0xc00008bc20)}, Extra:[]dns.RR(nil)}
DEBU[0613] [DNS] resolve  error: Can't parse msg
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x52f7b3]

goroutine 1354 [running]:
github.com/Dreamacro/clash/constant.(*Metadata).String(0xc0002a8340, 0xc000099cb0, 0xc0000af7c7)
	/home/travis/gopath/src/github.com/Dreamacro/clash/constant/metadata.go:44 +0x33
github.com/Dreamacro/clash/tunnel.(*Tunnel).match(0xc0000da460, 0xc0002a8340, 0x0, 0x0)
	/home/travis/gopath/src/github.com/Dreamacro/clash/tunnel/tunnel.go:160 +0x27e
github.com/Dreamacro/clash/tunnel.(*Tunnel).handleConn(0xc0000da460, 0x8f0040, 0xc0002584e0)
	/home/travis/gopath/src/github.com/Dreamacro/clash/tunnel/tunnel.go:133 +0x3fe
created by github.com/Dreamacro/clash/tunnel.(*Tunnel).process
	/home/travis/gopath/src/github.com/Dreamacro/clash/tunnel/tunnel.go:88 +0x93
```
配置中DNS部分
```
dns:
  enable: true
  ipv6: false
  nameserver:
     - 114.114.114.114
     - 223.5.5.5
     - tls://dns.rubyfish.cn:853 # dns over tls
  fallback:
     - tls://dns.rubyfish.cn:853 # dns over tls
     - 8.8.8.8
```

相同的配置文件，在macOS上没问题，在我的一台Debian 10 NAS上每隔数分钟就会出现。尝试仅留一个非DoT DNS依旧。
