### ISSUE TITLE
[Feature]希望增加proxy-group的url-test和fallback混合使用功能

### ISSUE THREAD

**Issue by railzy** [Dreamacro/clash#942]
我都确认过了，我要继续提交。

------------------------------------------------------------------

### Clash core config

```
proxy-groups:
  - name: 自动tw
    type: url-test
    url: http://www.gstatic.com/generate_204
    interval: 3600
    proxies:
      - 🇨🇳 台 1
      - 🇨🇳 台 2
      - 🇨🇳 台 3
  - name: 自动hk
    type: url-test
    url: http://www.gstatic.com/generate_204
    interval: 3600
    proxies:
      - 🇭🇰 港 1
      - 🇭🇰 港 2
      - 🇭🇰 港 3
      - 🇭🇰 港 4
      - 🇭🇰 港 5
  - name: 自动hktw
    type: url-test
    url: http://www.gstatic.com/generate_204
    interval: 3600
    proxies:
      - 自动hk
      - 自动tw
  - name: tw
    type: fallback
    url: http://www.gstatic.com/generate_204
    interval: 3600
    proxies:
      - 自动tw
      - DIRECT
  - name: hktw
    type: fallback
    url: http://www.gstatic.com/generate_204
    interval: 3600
    proxies:
      - 自动hktw
      - DIRECT
```

### Clash log

```
……
```

### 环境 Environment

* Clash Core 的操作系统 (the OS that the Clash core is running on)
Windows10
* 使用者的操作系统 (the OS running on the client)
Windows10
* 网路环境或拓扑 (network conditions/topology)
……
* iptables，如果适用 (if applicable)
……
* ISP 有没有进行 DNS 污染 (is your ISP performing DNS pollution?)
……
* 其他
……

### 说明 Description
我希望实现的效果是：

1. 首先proxy-group A中自动选择最快节点。
2. proxy-group B中包含proxy-group A和proxy-group C。对于proxy-group B，若proxy-group A中有节点都可用，则使用proxy-group A；若proxy-group A中所有节点都不可用，则选择proxy-group C。

但是按照上面的config设置后的实际效果是，在proxy-group A中自动选择了测速最快节点，在proxy-group B中测速proxy-group A结果却是timeout，导致错误选择了proxy-group C

### 可能的解决方案 Possible Solution

方法一：
在proxy-group内添加url-test和fallback的嵌套设置使用功能

方法二：
对于使用url-test或fallback的proxy-group添加节点统一测试功能，保证判断数据一致，proxy-group直接继承选择的节点的测试数据，对于本身不进行另外测速。并使proxy-group选择操作顺序执行，从使用基础节点的proxy-group A开始选择，再到使用proxy-group A的proxy-group B进行选择。
