### ISSUE TITLE
[Bug] Enhanced Mode ipv6 bind address error

### ISSUE THREAD

**Issue by timwa0669** [Dreamacro/clash#957]
### Clash config

```yaml
mixed-port: 1080
external-controller: 127.0.0.1:9090
allow-lan: true
mode: rule
log-level: debug
ipv6: true
dns:
  enable: true
  listen: 127.0.0.1:53
  default-nameserver:
    - 156.154.70.1
    - 1.0.0.1
  ipv6: true
  enhanced-mode: redir-host
  nameserver:
    - 119.29.29.29

proxies:
  - {name: dns_proxy, server: mirrors6.tuna.tsinghua.edu.cn, port: 1, type: ss, cipher: rc4-md5, password: test, udp: true}
  - {name: ip_proxy, server: 2001::32, port: 1, type: ss, cipher: rc4-md5, password: test, udp: true}

proxy-groups:
  - name: Test
    type: select
    proxies:
      - dns_proxy
      - ip_proxy

rules:
  - MATCH,Test
```

### Clash log
```
2020-09-08 22:15:42[warning] dial Test error: [2001::32]:1 connect error: dial tcp6 [fe80::7c:3953:4399:cbaa]:0->[2001::32]:1: bind: can't assign requested address

```

### 环境 Environment

* 操作系统 (the OS that the Clash core is running on)
macOS 10.15.6 Premium 2020.08.16
……
* 网路环境或拓扑 (network conditions/topology)
带公网ipv6地址
……
* iptables，如果适用 (if applicable)
……
* ISP 有没有进行 DNS 污染 (is your ISP performing DNS pollution?)
……
* 其他 (any other information that would be useful)
……

### 说明 Description

无法使用Enhanced Mode功能

### 重现问题的具体布骤 Steps to Reproduce

直接加载配置文件，启用Enhanced Mode

### 更多信息 More Information
普通Proxy模式下可以正常工作
