### ISSUE TITLE
[Bug] 高级版使用classical的rule-provider时，DNS操作异常

### ISSUE THREAD

**Issue by rayc345** [Dreamacro/clash#961]
------------------------------------------------------------------

### Clash config

<details>
  <summary>config.yaml</summary>

```yaml
mixed-port: 7890
allow-lan: false
mode: rule
log-level: debug
ipv6: true
external-controller: 127.0.0.1:9090
external-ui: dashboard

proxies:
  - name: "Proxy"
    type: vmess
    server: ***
    port: ***
    uuid: ******
    alterId: 1
    cipher: auto

rule-providers:
  Global:
    type: file
    behavior: classical
    path: ./rule1.yaml

rules:
  - RULE-SET,Global,Proxy
  - MATCH,Proxy
```

</details>

rule1.yaml内容：
payload:
  - DOMAIN-SUFFIX,google.com

### Clash log

```
time="2020-09-12T09:51:53+08:00" level=info msg="Start initial rule provider Global"
time="2020-09-12T09:51:53+08:00" level=info msg="RESTful API listening at: 127.0.0.1:9090"
time="2020-09-12T09:51:53+08:00" level=info msg="Mixed(http+socks5) proxy listening at: 127.0.0.1:7890"
time="2020-09-12T09:51:53+08:00" level=debug msg="[DNS] play.google.com --> 172.217.27.142"
time="2020-09-12T09:51:53+08:00" level=info msg="[TCP] 127.0.0.1:3718 --> play.google.com match RuleSet(Global) using Proxy"
time="2020-09-12T09:51:53+08:00" level=debug msg="[DNS] alive.github.com --> 140.82.113.25"
time="2020-09-12T09:51:53+08:00" level=info msg="[TCP] 127.0.0.1:3720 --> alive.github.com match Match() using Proxy"
time="2020-09-12T09:51:54+08:00" level=debug msg="[DNS] play.google.com --> 172.217.27.142"
time="2020-09-12T09:51:54+08:00" level=info msg="[TCP] 127.0.0.1:3716 --> play.google.com match RuleSet(Global) using Proxy"
```

### 环境 Environment

* 操作系统 (the OS that the Clash core is running on)
Windows10，64位clash高级版（闭源）
* 网路环境或拓扑 (network conditions/topology)
通过网线连接路由器
* iptables，如果适用 (if applicable)
无
* ISP 有没有进行 DNS 污染 (is your ISP performing DNS pollution?)
有
* 其他 (any other information that would be useful)
无

### 重现问题的具体布骤 Steps to Reproduce

使用clash闭源的高级版本，和上面提供的clash配置文件和rule-provider文件（rule模式，并使用rule-providers，类型为classical），clash通过SOCKS5和HTTP的混合端口接受SOCKS5代理请求
在规则中没有用GEOIP，也没有用IP匹配

**我预期会发生……？**
clash会直接根据域名进行规则匹配，没有匹配到的最后全部走MATCH，不涉及域名解析操作。

**实际上发生了什么？**
clash的日志显示，程序会对每一个代理的域名进行DNS解析操作。但这个解析并没有任何用处（规则无IP相关），反而会造成隐私泄露。
另外，如果rule-provider类型不是classical而是domain，那么rule1.yaml内容修改为：
payload:
  - '.google.com'
此时，clash接受代理时，不会对每个域名进行DNS解析。

### 可能的解决方案 Possible Solution
当前，使用rule-provider时，不要用classical的behavior
