### ISSUE TITLE
[Feature] Requests and responses logs for DNS server

### ISSUE THREAD

**Issue by ysc3839** [Dreamacro/clash#963]
### Clash core config

```
mixed-port: 11080
log-level: debug
dns:
  enable: true
  listen: 127.0.0.1:15353
  nameserver:
    - 1.1.1.1
```

### Clash log

```
time="2020-09-12T21:38:34+08:00" level=info msg="Mixed(http+socks5) proxy listening at: 127.0.0.1:11080"
time="2020-09-12T21:38:34+08:00" level=info msg="DNS server listening at: 127.0.0.1:15353"
```

### 说明 Description

Start clash with above config, and send DNS requests to `127.0.0.1:15353`. There's no log for DNS requests and upstream nameserver responses, which makes debugging DNS errors difficult.
