### ISSUE TITLE
[Bug] Only a JSON file is returned on the dashboard page

### ISSUE THREAD

**Issue by Will-ChenYW** [Dreamacro/clash#967]
------------------------------------------------------------------

### Clash config

<details>
  <summary>config.yaml</summary>

```yaml
# HTTP 代理端口
port: 7890
# SOCKS5 代理端口
socks-port: 7891
# Linux 和 macOS 的 redir 代理端口
redir-port: 7892
# 允许局域网的连接
allow-lan: true

# 规则模式：Rule（规则） / Global（全局代理）/ Direct（全局直连）
mode: Rule

# 设置日志输出级别 (默认级别：silent，即不输出任何内容，以避免因日志内容过大而导致程序内存溢出）。
# 5 个级别：silent / info / warning / error / debug。级别越高日志输出量越大，越倾向于调试，若需要请自行开启。
log-level: debug
# Clash 的 RESTful API
external-controller: '0.0.0.0:8080'

# RESTful API 的口令
secret: ''

# 您可以将静态网页资源（如 clash-dashboard）放置在一个目录中，clash 将会服务于 `RESTful API/ui`
# 参数应填写配置目录的相对路径或绝对路径。
# external-ui: folder
```

</details>

### Clash log

```
INFO[0000] Start initial compatible provider CYLINK     
INFO[0000] Start initial compatible provider Domestic   
INFO[0000] Start initial compatible provider Others     
INFO[0000] Start initial compatible provider Global     
INFO[0000] Redir proxy listening at: :7892              
INFO[0000] RESTful API listening at: 0.0.0.0:8080       
INFO[0000] SOCKS proxy listening at: :7891              
INFO[0000] HTTP proxy listening at: :7890
```

### 环境 Environment

* 操作系统 (the OS that the Clash core is running on)
Kali Linux 2020.3
* 网路环境或拓扑 (network conditions/topology)
Wifi Network
* iptables，如果适用 (if applicable)
……
* ISP 有没有进行 DNS 污染 (is your ISP performing DNS pollution?)
Possibly (Hubei Telecom)
* 其他 (any other information that would be useful)
……

### 重现问题的具体布骤 Steps to Reproduce

1. Download Clash and the configuration file
2. Run chmod +x clash
3. Run sudo ./clash -d .
4. After seeing the message of "INFO[0000] RESTful API listening at: 0.0.0.0:8080", go to the given url, and change proxy settings on it.

**我预期会发生……？**

A graphical interface that allows me to dynamically change the settinggs
**实际上发生了什么？**

Only returns a JSON file and no interaction can be done
