### ISSUE TITLE
请教TUN模式下UDP转发

### ISSUE THREAD

**Issue by DanteSung** [Dreamacro/clash#971]
目前使用Mac ClashX Pro 1.30.2.1, 参照https://github.com/Dreamacro/clash/issues/745 ，配置dns如下：
```
dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:53
  enhanced-mode: fake-ip
  nameserver:
    - 119.29.29.29
    - 223.5.5.5
    - 1.1.1.1
    - tls://dns.rubyfish.cn:853
  fallback:
    - tls://1.1.1.1:853
    - tls://1.0.0.1:853
    - tls://dns.google:853

tun:
  enable: true
  macOS-auto-route: true
  macOS-auto-detect-interface: true
```
仅开启增强模式，关闭系统代理
移动端配置http代理后（无论是否设置dns指向Mac）可以由clashX接管流量。
问题：将switch代理服务器和DNS均指向MAC内网ip后，可转发TCP流量，UDP流量仍然没有转发。尝试将DNS指向198.18.0.2，仍然只转发了TCP流量。
请问是否需要进一步设置？谢谢！

**Comment by DanteSung** [comment]
另外请问手机端目前无法链接WhatsApp，似乎也没有成功转发UDP流量

**Comment by Dreamacro** [comment]
是设置网关和 dns，不是设置代理服务器

**Comment by DanteSung** [comment]
感谢回复！网关和DNS设置可以接管设备的UDP流量。
目前问题是不知道目标服务器的子网掩码，用IP-CIDR规则无法转发目标服务器的流量，请问是否有规则按照MAC地址判断流量，即检测到来自switch的访问统一转发至一个特定的服务器？

**Comment by Dreamacro** [comment]
`- SRC-IP-CIDR,ns-lan-ip,Proxy`

**Comment by DanteSung** [comment]
谢谢！在手机上测试成功。请问该规则是否会和其他规则冲突？如手机访问Youtube时：
`- SRC-IP-CIDR,android-lan-ip/32,Proxy1` 和`-DOMAIN-KEYWORD,youtube,Proxy2`同时存在，clash会以哪条规则转发呢？
如果存在冲突，是否可以定义优先级？

**Comment by Dreamacro** [comment]
写前面优先级高

**Comment by hongzzz** [comment]
> 感谢回复！网关和DNS设置可以接管设备的UDP流量。
> 目前问题是不知道目标服务器的子网掩码，用IP-CIDR规则无法转发目标服务器的流量，请问是否有规则按照MAC地址判断流量，即检测到来自switch的访问统一转发至一个特定的服务器？

请教一下最终是怎么配置的呢 ？PC & switch，十分感谢

**Comment by DanteSung** [comment]
> > 感谢回复！网关和DNS设置可以接管设备的UDP流量。
> > 目前问题是不知道目标服务器的子网掩码，用IP-CIDR规则无法转发目标服务器的流量，请问是否有规则按照MAC地址判断流量，即检测到来自switch的访问统一转发至一个特定的服务器？
> 
> 请教一下最终是怎么配置的呢 ？PC & switch，十分感谢

增强模式可以使用的情况下添加规则 `- SRC-IP-CIDR,ns-lan-ip/32,Proxy`， 其中`ns-lan-ip`是你NS在局域网中的ip地址， `Proxy`是想让ns流量走的代理

增强模式设置，添加下面代码到yaml文件头
```
dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:53
  enhanced-mode: fake-ip
  nameserver:
    - 119.29.29.29
    - 223.5.5.5
    - 1.1.1.1
    - tls://dns.rubyfish.cn:853
  fallback:
    - tls://1.1.1.1:853
    - tls://1.0.0.1:853
    - tls://dns.google:853

tun:
  enable: true
  macOS-auto-route: true
  macOS-auto-detect-interface: true
```
只在mac下测试过；Windows下的Clash for Windows增强模式直接导入这段代码可能会报错；好像可以通过mix-min方式启用，但是具体的没有测过
