### ISSUE TITLE
[Bug] fail to access ANY foreign website without changing any config that had worked well for a while.

### ISSUE THREAD

**Issue by hanfei1991** [Dreamacro/clash#973]
------------------------------------------------------------------

### Clash config

<details>
  <summary>config.yaml</summary>

```yaml
ort: 7890
socks-port: 7891
redir-port: 7892
mixed-port: 7893
ipv6: false
allow-lan: true
mode: rule
log-level: debug
external-controller: '0.0.0.0:9999'
external-ui: ui
secret: ''
dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:53
  default-nameserver:
    - 114.114.114.114
  #enhanced-mode: redir-host
  enhanced-mode: fake-ip #............netflix...............fake-ip
  fake-ip-range: 198.18.0.1/16
  nameserver:
    - 114.114.114.114
    - 223.5.5.5
    - tls://8.8.8.8:853
  fallback:
    - tls://8.8.8.8:853

# .....................
proxies:
  # http
  - name: "vmess01"
    type: vmess
    server: 103.70.59.141
    port: ***
    uuid: ***
    alterId: 4
    cipher: auto

rules:
# LAN
  - DOMAIN-SUFFIX,local,DIRECT
  - IP-CIDR,127.0.0.0/8,DIRECT
  - IP-CIDR,172.16.0.0/12,DIRECT
  - IP-CIDR,192.168.0.0/16,DIRECT
  - IP-CIDR,10.0.0.0/8,DIRECT


# .................................IP...........................
  - GEOIP,CN,DIRECT
  - MATCH,vmess01

```

</details>

### Clash log

```
time="2020-09-17T17:36:06Z" level=error msg="Start DNS server error: listen udp 0.0.0.0:53: bind: address already in use"
time="2020-09-17T17:36:06Z" level=info msg="SOCKS proxy listening at: :7891"                                            
time="2020-09-17T17:36:06Z" level=info msg="Redir proxy listening at: :7892"                                            
time="2020-09-17T17:36:06Z" level=info msg="Mixed(http+socks5) proxy listening at: :7893"                               
time="2020-09-17T17:36:06Z" level=info msg="RESTful API listening at: 0.0.0.0:9999"                                     
time="2020-09-17T17:36:06Z" level=info msg="HTTP proxy listening at: :7890"  
 level=info msg="[TCP] 192.168.31.226:35262 --> 31.13.91.33 match Match() using vmess01" 
```

This IP points to facebook server in holland. as https://www.ip138.com/iplookup.asp?ip=31.13.91.33&action=2

### 环境 Environment

* 操作系统 (the OS that the Clash core is running on)
root@XiaoQiang:/userdisk/data/clash# uname -a
Linux XiaoQiang 3.4.103 #1 MiWiFi-R3D-2.29.5 SMP PREEMPT Thu May 30 08:23:40 UTC 2019 armv7l GNU/Linux

* 网路环境或拓扑 (network conditions/topology)
……
* iptables，如果适用 (if applicable)
-A prerouting_rule -d 10.0.0.0/8 -j RETURN
-A prerouting_rule -d 127.0.0.0/8 -j RETURN                                                  
-A prerouting_rule -d 169.254.0.0/16 -j RETURN           
-A prerouting_rule -d 172.16.0.0/12 -j RETURN          
-A prerouting_rule -d 192.168.0.0/16 -j RETURN               
-A prerouting_rule -d 224.0.0.0/4 -j RETURN                                               
-A prerouting_rule -d 240.0.0.0/4 -j RETURN            
-A prerouting_rule -p tcp -j REDIRECT --to-ports 7892

* ISP 有没有进行 DNS 污染 (is your ISP performing DNS pollution?)
Don't know
* 其他 (any other information that would be useful)
……

### 说明 Description

I have suceeded in using clash for a long time, by adding iptables rule as above. But recently I cannot use it to access any website. Even restart clash many times. I'm sure my vpn is working well, because I can cross wall using 4G network.

### 重现问题的具体布骤 Steps to Reproduce

1. run clash on my router
2. add iptables rules, transfer all tcp packets.
3. access facek , but failed.

**我预期会发生……？**
access fackbook as usual

**实际上发生了什么？**
Firefox report the error, as following, facebook don't return any result

```
连接到 www.facebook.com 时发生错误。PR_END_OF_FILE_ERROR

    由于不能验证所收到的数据是否可信，无法显示您想要查看的页面。
    建议向此网站的管理员反馈这个问题。
```

here is the results of `curl --trace trace.txt www.facebook.com`. I wish it would be helpful:

```
== Info:   Trying 31.13.91.33...
== Info: TCP_NODELAY set 
== Info: Connected to www.facebook.com (31.13.91.33) port 80 (#0)
=> Send header, 84 bytes (0x54)
0000: 47 45 54 20 2f 20 48 54 54 50 2f 31 2e 31 0d 0a GET / HTTP/1.1..
0010: 48 6f 73 74 3a 20 77 77 77 2e 66 61 63 65 62 6f Host: www.facebo
0020: 6f 6b 2e 63 6f 6d 0d 0a 55 73 65 72 2d 41 67 65 ok.com..User-Age
0030: 6e 74 3a 20 63 75 72 6c 2f 37 2e 36 33 2e 30 2d nt: curl/7.63.0-
0040: 44 45 56 0d 0a 41 63 63 65 70 74 3a 20 2a 2f 2a DEV..Accept: */* 
0050: 0d 0a 0d 0a                                     
== Info: Empty reply from server
== Info: Connection #0 to host www.facebook.com left intact                                                           
```

### 可能的解决方案 Possible Solution

我注意到 log 里用的是 UTC + 0 的时间，但是我的 router 和 server 使用 UTC + 8 的时间，是不是时间的问题导致了 vmess 验证失败？
