### ISSUE TITLE
TUN模式下规则冲突

### ISSUE THREAD

**Issue by DanteSung** [Dreamacro/clash#976]
根据之前[issue](https://github.com/Dreamacro/clash/issues/971)中的反馈，我在TUN模式下设置了两条规则
```
 - SRC-IP-CIDR,192.168.1.113/32,Proxy1 # 用于分流来自内网内固定设备113的流量
....
....
 - MATCH,Proxy2 # 用于兜底
```

`SRC-IP-CIDR`是所有规则的第一条，理论上拥有最高优先级，但是实测中仍然发现有部分流量走了`Match`规则。
请问是设置方面有问题吗？

---
另外附上版本信息：`Mac ClashX Pro 1.30.2.1`，以及TUN模式的设置
```
dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:53
  enhanced-mode: fake-ip
  nameserver:
    - 119.29.29.29
    - 223.5.5.5
    - 1.1.1.1
    - tls://dns.rubyfish.cn:853
  fallback:
    - tls://1.1.1.1:853
    - tls://1.0.0.1:853
    - tls://dns.google:853

tun:
  enable: true
  macOS-auto-route: true
  macOS-auto-detect-interface: true
```
