### ISSUE TITLE
[Feature] ClashX-iCloud-rule-providers did not work

### ISSUE THREAD

**Issue by yangxyo** [Dreamacro/clash#977]
感谢你向 Clash Core 提交 Feature Request！
在提交之前，请确认：

- [x] 我已经在 [Issue Tracker](……/) 中找过我要提出的请求

请注意，如果你并没有遵照这个 issue template 填写内容，我们将直接关闭这个 issue。

我都确认过了，我要继续提交。

------------------------------------------------------------------
### Clash core config
```
rule-providers:
  reject:
    behavior: "domain"
    type: file
    path: ./ruleset/reject.yaml
  reject2:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/reject.txt"
    path: ./ruleset/reject2.yaml
    interval: 86400
……
```

### Clash log
```
initial rule provider reject error: open ~/.config/clash/ruleset/reject.yaml: no such file or directory
……
```

### 环境 Environment

MacOS、ClashX 1.30.2.1
……

### 说明 Description
使用 ClashX 的实验性功能->使用iCloud，但是配置文件查找和生成都是在 ~/.config/clash的默认配置文件上，而不是icloud的Clash文件里，但是使用proxy-providers却是正常的。

```
proxy-providers:
  provider1:
    type: http
    url: 
    interval: 3600
    path: ./
    health-check:
      enable: true
      interval: 600
      url: http://www.gstatic.com/generate_204
```
这个时候icloud和config里面都有通过url下载的文件。

由于ClashX没有issue，所以问题只能放在这儿了。
