### ISSUE TITLE
[Bug] 高级版使用classical的rule-provider时，DNS操作异常 之二

### ISSUE THREAD

**Issue by rayc345** [Dreamacro/clash#979]
------------------------------------------------------------------
### Clash config

<details>
  <summary>config.yaml</summary>

```yaml
mixed-port: 7890
allow-lan: false
mode: rule
log-level: debug
ipv6: true

proxies:
  - name: "Proxy"
    type: vmess
    server: ***
    port: ***
    uuid: ***
    alterId: 1
    cipher: auto

rule-providers:
  EducateIP:
    type: file
    behavior: ipcidr
    path: ./RuleSet/EducateIP.yaml

rules:
  - RULE-SET,EducateIP,DIRECT
  - GEOIP,CN,DIRECT
  - MATCH,Proxy
```

</details>

### EducateIP.yaml 内容
<details>
  <summary>EducateIP.yaml</summary>

```yaml
payload:
  - '202.118.0.0/15'
```

</details>

### 使用6.27发布的版本：Clash log
```
time="2020-09-20T13:53:45+08:00" level=debug msg="[DNS] lib.nuaa.edu.cn --> 202.119.70.20"
time="2020-09-20T13:53:45+08:00" level=debug msg="[DNS] lib.nuaa.edu.cn --> 202.119.70.20"
time="2020-09-20T13:53:45+08:00" level=info msg="[TCP] 127.0.0.1:1721 --> lib.nuaa.edu.cn match GeoIP(CN) using DIRECT"
time="2020-09-20T13:53:45+08:00" level=info msg="[TCP] 127.0.0.1:1722 --> lib.nuaa.edu.cn match GeoIP(CN) using DIRECT"
time="2020-09-20T13:53:46+08:00" level=debug msg="[DNS] edge.activity.windows.com --> 20.184.57.167"
time="2020-09-20T13:53:46+08:00" level=info msg="[TCP] 127.0.0.1:1725 --> edge.activity.windows.com match Match() using Proxy"
time="2020-09-20T13:53:46+08:00" level=info msg="[TCP] 127.0.0.1:1727 --> 202.119.70.22 match RuleSet(EducateIP) using DIRECT"
……
```

### 使用8.16发布的版本：Clash log
```
time="2020-09-20T14:07:22+08:00" level=debug msg="[DNS] lib.nuaa.edu.cn --> 202.119.70.20"
time="2020-09-20T14:07:22+08:00" level=debug msg="[DNS] lib.nuaa.edu.cn --> 202.119.70.20"
time="2020-09-20T14:07:22+08:00" level=info msg="[TCP] 127.0.0.1:1985 --> lib.nuaa.edu.cn match RuleSet(EducateIP) using DIRECT"
time="2020-09-20T14:07:22+08:00" level=info msg="[TCP] 127.0.0.1:1986 --> lib.nuaa.edu.cn match RuleSet(EducateIP) using DIRECT"
time="2020-09-20T14:07:22+08:00" level=info msg="[TCP] 127.0.0.1:1989 --> 202.119.70.22 match RuleSet(EducateIP) using DIRECT"
……
```

### 环境 Environment

* 操作系统 (the OS that the Clash core is running on)
Windows10，64位clash高级版（闭源）
* 网路环境或拓扑 (network conditions/topology)
通过网线连接路由器
* iptables，如果适用 (if applicable)
无
* ISP 有没有进行 DNS 污染 (is your ISP performing DNS pollution?)
有
* 其他 (any other information that would be useful)
无

### 重现问题的具体布骤 Steps to Reproduce

1. 运行Clash高级版，使用上文的配置
2. 浏览 lib.nuaa.edu.cn

**我预期会发生……？**
当进行规则匹配时，第一条为IP匹配规则， Clash应当进行DNS解析并根据规则判断。lib.nuaa.edu.cn服务器IP为202.119.70.22，应当匹配到EducateIP规则，而不是GeoIP(CN)。

**实际上发生了什么？**

## 使用6.27发布的版本：
使用上文中的配置，虽然进行了DNS解析，但该网址匹配到了GeoIP(CN)，不符合预期。
若去掉配置文件中的GEOIP,CN,DIRECT，则Clash不会进行DNS解析，说明是GEOIP,CN,DIRECT触发了Clash的DNS解析，类型为ipcidr的rule-provider并没有触发DNS解析。

## 使用8.16发布的版本：
使用上文中的配置，该网址匹配到了EducateIP，与预期一致

###由于8.16发布的版本DNS存在问题（不该进行DNS匹配时去匹配）（已通过issue#961反馈，作者回应已修复），可能歪打正着匹配正确，然而逻辑是有问题的，可能目前最新版的代码中任然存在此问题。之前试着联系作者获取内测版以验证此bug是否存在
，但由于两个bug在一个issue反馈，前后文没有说清楚情况，不便于开发者理解，未获得回应，所以决定新开issue反馈问题，由作者判断。
