### ISSUE TITLE
[Bug]macOS的Wifi设置里的socks代理使用的端口不是config.yaml里的那个

### ISSUE THREAD

**Issue by owenzhao** [Dreamacro/clash#982]
------------------------------------------------------------------

### Clash config

<details>
  <summary>config.yaml</summary>

```yaml
port: 7890
socks-port: 1086
allow-lan: false
mode: Rule
log-level: info
external-controller: 127.0.0.1:9090
```

</details>

### 环境 Environment

* 操作系统 (the OS that the Clash core is running on)
macOS 10.15.6 (19G2021)
* 网路环境或拓扑 (network conditions/topology)
WiFi
* iptables，如果适用 (if applicable)
……
* ISP 有没有进行 DNS 污染 (is your ISP performing DNS pollution?)
……
* 其他 (any other information that would be useful)
……

### 说明 Description

ClashX中，点击设置为系统代理。在ClashX中查看socks-port，是正常设置的1086端口。但是在Wifi设置中看，却设置的是7890。实际使用发现，1086是正确的。

### 重现问题的具体布骤 Steps to Reproduce

1. [First Step]
2. [Second Step]
3. ……

**我预期会发生……？**

两处设置的端口是一致的。

**实际上发生了什么？**

端口不一致。

### 可能的解决方案 Possible Solution

Wifi设置的部分改成和ClashX控制台中看到的一致的。
### 更多信息 More Information

<img width="1575" alt="clash_socks_issue" src="https://user-images.githubusercontent.com/2182896/93831573-abc77380-fca5-11ea-8609-5e907ff78089.png">
