### ISSUE TITLE
【问题】linux 命令行下如何选择和启动代理节点？

### ISSUE THREAD

**Issue by conphi** [Dreamacro/clash#984]
**Terminal输入命令：**
clash -f config.yaml

**Terminal输出：**
INFO[0000] Start initial compatible provider Proxy

**结果：打开浏览器无法访问Google**

**config.yaml文件配置如下：**
```
port: 7890
socks-port: 7891
redir-port: 7892
allow-lan: false
mode: global
log-level: silent
external-controller: '0.0.0.0:9090'
secret: ''
proxies:
  - name: ss1
    type: ss
    server: 11.22.33.44
    port: 6666
    cipher: aes-256-cfb
    password: 123456
proxy-groups:
  - name: Proxy
    type: select
    proxies:
      - 'ss1'
```

**PS：看了Clash的wiki，我看了很久，实在是找不到“启动”代理节点的方法。**
