### ISSUE TITLE
[Feature] 可以为ipv6优先提供一个选项吗

### ISSUE THREAD

**Issue by Liquor030** [Dreamacro/clash#990]
感谢你向 Clash Core 提交 Feature Request！
在提交之前，请确认：

- [x] 我已经在 [Issue Tracker](……/) 中找过我要提出的请求

请注意，如果你并没有遵照这个 issue template 填写内容，我们将直接关闭这个 issue。

我都确认过了，我要继续提交。

------------------------------------------------------------------

请附上任何可以帮助我们解决这个问题的信息，如果我们收到的信息不足，我们将对这个 issue 加上 *Needs more information* 标记并在收到更多资讯之前关闭 issue。

### Clash core config

```
port: 7890
socks-port: 7891
allow-lan: false
mode: Rule
log-level: info
ipv6: true
external-controller: 127.0.0.1:9090
experimental:
  ignore-resolve-fail: true
dns:
  enable: true
  ipv6: true
  listen: 0.0.0.0:53
  enhanced-mode: redir-host
```

### Clash log

```
……
```

### 环境 Environment

* Clash Core 的操作系统 (the OS that the Clash core is running on)
Windows 10 专业版 2004
* 使用者的操作系统 (the OS running on the client)
Windows 10 专业版 2004
* 网路环境或拓扑 (network conditions/topology)
校园网 ipv4/ipv6双栈
* iptables，如果适用 (if applicable)
……
* ISP 有没有进行 DNS 污染 (is your ISP performing DNS pollution?)
……
* 其他
……

### 说明 Description

因为所在的校园网对ipv4限速，但是ipv6未限速，因此想让一些网址走ipv6来提升网速。
在clash的配置中更改hosts，想让指定地址走ipv6，但是发现clash仍然会通过ipv4的地址访问。

### 可能的解决方案 Possible Solution

可以提供一个ipv6优先级的选项吗，优先使用ipv6。
