### ISSUE TITLE
[Feature] Add no-resolve option support to ipcidr type of RULE-SET

### ISSUE THREAD

**Issue by Loyalsoldier** [Dreamacro/clash#994]
在提交之前，请确认：

- [x] 我已经在 [Issue Tracker](……/) 中找过我要提出的请求

------------------------------------------------------------------

### 说明 Description

As I mentioned in https://github.com/Dreamacro/clash/issues/877#issuecomment-700063161
I hope `ipcidr` type of `RULE-SET` can support `no-resolve` option to avoid DNS resolving process.

**Comment by Dreamacro** [comment]
不知道你想要到什么程度的「防止 DNS 泄漏」，理论上如果你完全不通过 clash 去进行 dns 解析，你需要自己准备一个完整的域名名单，保证这个名单内的域名不进行 dns 解析

**Comment by Loyalsoldier** [comment]
先回答开这个 issue 的原因：自制了 ipcidr 类型的 RULE-SET，希望遇到这条规则，不会触发 DNS 解析。
GEOIP、IP-CIDR、IP-CIDR6 都有 `no-resolve` 选项，希望 RULE-SET 也有。

---

下面回答关于 DNS 泄漏的问题。

目的：用国外的 DNS 泄漏测试网站（例如：https://dnsleaktest.com 和 https://www.astrill.com/vpn-leak-test ）来测试时，不会出现大陆的 DNS。

我在用 ClashX Pro，为了达成这个目标：

1. 在 Clash 里**没有**开启 DNS 功能
2. 在本机**没有**使用第三方 DNS 软件
3. 准备了详尽的 RULE-SET（见下方配置）
4. 配置文件里跟 IP 相关的规则只有 GEOIP 匹配，但使用了 `no-resolve` 选项，不需要进行 DNS 解析（也就是说整个规则匹配过程不涉及任何 DNS 解析）
5. 兜底策略是走代理（`MATCH,PROXY`）

ClashX Pro 配置如下：

```yaml
mode: rule
log-level: debug
allow-lan: false
ipv6: false
external-controller: 0.0.0.0:9090

proxy-groups:
  - name: PROXY
    type: select
    use:
      - SSRService

proxy-providers:
  SSRService:
    type: http
    url: "https://service/subscribe/url"
    path: ./service.yaml
    interval: 43200

rule-providers:
  🚫reject:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/reject.txt"
    path: ./ruleset/reject.yaml
    interval: 43200

  🚀proxy:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/proxy.txt"
    path: ./ruleset/proxy.yaml
    interval: 43200

  🇨🇳direct:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/direct.txt"
    path: ./ruleset/direct.yaml
    interval: 43200

  🇨🇳cncidr:
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/cncidr.txt"
    path: ./ruleset/cncidr.yaml
    interval: 43200

  🔁lancidr:
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/lancidr.txt"
    path: ./ruleset/lancidr.yaml
    interval: 43200

rules:
  - RULE-SET,🚫reject,REJECT
  - RULE-SET,🚀proxy,PROXY
  - RULE-SET,🇨🇳direct,DIRECT
  - GEOIP,CN,DIRECT,no-resolve
  - MATCH,PROXY
```

在这种情况下，用上面的国外 DNS 泄漏测试网站来测试，理应是不会出现大陆 DNS 的，但有趣的是：

1. 无论是`设置为系统代理` 还是 `增强模式`，FAKEIP 模式都**没有发生** DNS 泄漏
2. 无论是`设置为系统代理` 还是 `增强模式`，Redir-Host 模式都**发生**了 DNS 泄漏

怀疑 Redir-Host 的设计有逻辑问题，因为根据上面配置，对于命中代理的域名根本不需要 DNS 解析，所以本应不会看到大陆 DNS。
